---------------------------------------------------
--          Z O N E S        M O D U L E         --
---------------------------------------------------

root(ROOTS.Zones, m(SHADOWLANDS, bubbleDown({ ["timeline"] = { ADDED_9_0_2_LAUNCH } }, {
	m(BASTION, {
		n(ACHIEVEMENTS, {
			ach(14307, {		-- Adventurer of Bastion (automated)
				crit(50582, {
					["_npcs"] = { 158659 },	-- Herculon <Aspirant Assessor>
				}),
				crit(50611, {
					["_npcs"] = { 171011 },	-- Demi the Relic Hoarder
				}),
				crit(50614, {
					["_npcs"] = { 171255 },	-- Echo of Aella <Hand of Courage>
				}),
			}),
			ach(14767, {	-- Count Your Blessings
				crit(49944, {		-- Purified Blessing of Grace
					["description"] = createLocalizationString({
						readable = "Requires a |cFFFFFFFFRipe Purian|r to activate.",
						constant = "REQUIRES_A_CFFFFFFFFRIPE_PURIAN_R_TO_ACTIVATE",
						export = true,
						text = {
							en = "Requires a |cFFFFFFFFRipe Purian|r to activate.",
							-- TODO: de = "",
							-- TODO: es = "",
							-- TODO: mx = "",
							-- TODO: fr = "",
							-- TODO: it = "",
							-- TODO: ko = "",
							-- TODO: pt = "",
							-- TODO: ru = "",
							cn = "需要|cFFFFFFFF成熟的普里安|r才能激活。",
							-- TODO: tw = "",
						},
					}),
					["coord"] = { 53.8, 28.9, BASTION },
				}),
				crit(49945, {		-- Purified Blessing of Power
					["description"] = "~L.REQUIRES_A_CFFFFFFFFRIPE_PURIAN_R_TO_ACTIVATE",
					["coord"] = { 45.3, 59.8, BASTION },
				}),
				crit(49946, {		-- Purified Blessing of Fortitude
					["description"] = "~L.REQUIRES_A_CFFFFFFFFRIPE_PURIAN_R_TO_ACTIVATE",
					["coord"] = { 34.7, 30.0, BASTION },
				}),
			}),
			ach(14303),	-- Explore Bastion
			ach(14735, {	-- Flight School Graduate
				crit(49820, {		-- Flight School: Falling With Style
					["_quests"] = { 60844 },	-- Flight School: Falling With Style
				}),
				crit(49821, {		-- Flight School: Up and Away!
					["_quests"] = { 60858 },	-- Flight School: Up and Away!
				}),
				crit(49822, {		-- Flight School: Flapping Frenzy
					["_quests"] = { 60911 },	-- Flight School: Flapping Frenzy
				}),
			}),
			ach(14734, {	-- Rallying Cry of the Ascended
				crit(49815, {		-- Vesper of Courage
					["coord"] = { 33.3, 59.7, BASTION },
				}),
				crit(49819, {		-- Vesper of Wisdom
					["coord"] = { 39.1, 20.4, BASTION },
				}),
				crit(49816, {		-- Vesper of Humility
					["coord"] = { 71.8, 38.8, BASTION },
				}),
				crit(49817, {		-- Vesper of Loyalty
					["coord"] = { 32.1, 17.8, BASTION },
				}),
				crit(49818, {		-- Vesper of Purity
					["coord"] = { 64.3, 69.8, BASTION },
				}),
			}),
			ach(14339, {	-- Shard Labor
				["description"] = createLocalizationString({
					readable = "'Collect all trackable things' must be enabled to see the location of each shard in the list.\n\nShards are collected account-wide. There are shards to collect in Bastion, Necrotic Wake, and Spires of Ascension.",
					constant = "COLLECT_ALL_TRACKABLE_THINGS_MUST_BE_ENABLED_TO",
					export = true,
					text = {
						en = "'Collect all trackable things' must be enabled to see the location of each shard in the list.\n\nShards are collected account-wide. There are shards to collect in Bastion, Necrotic Wake, and Spires of Ascension.",
						-- TODO: de = "",
						-- TODO: es = "",
						-- TODO: mx = "",
						-- TODO: fr = "",
						-- TODO: it = "",
						-- TODO: ko = "",
						-- TODO: pt = "",
						-- TODO: ru = "",
						cn = "必须启用“收集所有可追踪物品”，才能在列表中看到每块碎片的所在地。\n\n碎片为账号通用收集。在晋升堡垒、凋魂之殇和晋升之巅都有需要收集的碎片。",
						-- TODO: tw = "",
					},
				}),
				["groups"] = {
					-- https://www.wowhead.com/achievement=14339/shard-labor#comments
					-- moving completed ones up to the top for now so it's easier to see which one checks off (to verify coords + add data more easily)
					q(61295, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "On a bookshelf inside the room behind Rector Kalliope.",
							constant = "ON_A_BOOKSHELF_INSIDE_THE_ROOM_BEHIND_RECTOR",
							export = true,
							text = {
								en = "On a bookshelf inside the room behind Rector Kalliope.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在院长卡莉奥佩身后房间内的书架上。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 24.3, 18.2, BASTION },
					}),
					q(61293, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "On a pillar underneath the platform. The shard is surrounded by mobs that will attack you even if you land properly on top of the pillar, so you need a way to stun, fear, or kill them so you can loot.\n\nDon't jump all the way down to the middle section. There is a small gap between the staircase to the top of the platform and the archway the waterfall passes through. Walk through the gap and forward along the ledge. The shard can be difficult to see, depending on your camera angle, but you need to jump off the ledge towards the pillar.",
							constant = "ON_A_PILLAR_UNDERNEATH_THE_PLATFORM_THE_SHARD",
							export = true,
							text = {
								en = "On a pillar underneath the platform. The shard is surrounded by mobs that will attack you even if you land properly on top of the pillar, so you need a way to stun, fear, or kill them so you can loot.\n\nDon't jump all the way down to the middle section. There is a small gap between the staircase to the top of the platform and the archway the waterfall passes through. Walk through the gap and forward along the ledge. The shard can be difficult to see, depending on your camera angle, but you need to jump off the ledge towards the pillar.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在平台下方的一根柱子上。碎片周围有小怪，即使你准确落在柱子顶端它们也会攻击你，所以你需要有办法控制、恐惧或击杀它们才能拾取。\n\n不要一路跳到中间层。在通往平台顶部的楼梯与瀑布穿过的拱门之间有一道小缝。穿过缝隙沿岩架向前走。根据视角不同，碎片可能很难看清，但你需要从岩架朝柱子方向跳下去。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 24.6, 22.9, BASTION },
					}),
					q(61294, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "Behind some barrels of anima.",
							constant = "BEHIND_SOME_BARRELS_OF_ANIMA",
							export = true,
							text = {
								en = "Behind some barrels of anima.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在一些心能桶后面。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 26.1, 22.6, BASTION },
					}),
					q(61292, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "The pathway to this shard starts at |cFFFFFFFF27.7, 19.2|r, in an area full of elite mobs. Run up the ledge on the side of the mountain until you can jump down to the archway and pick up the shard.",
							constant = "THE_PATHWAY_TO_THIS_SHARD_STARTS_AT_CFFFFFFFF27",
							export = true,
							text = {
								en = "The pathway to this shard starts at |cFFFFFFFF27.7, 19.2|r, in an area full of elite mobs. Run up the ledge on the side of the mountain until you can jump down to the archway and pick up the shard.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "通往这块碎片的路径起点在|cFFFFFFFF27.7, 19.2|r，位于一片布满精英怪物的区域。沿着山侧的岩架向上跑，直到你能跳到拱门处并拾取碎片。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 30.6, 23.7, BASTION },
					}),
					q(61291, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "At the bottom of the lake, hidden inside the base of a fallen statue.",
							constant = "AT_THE_BOTTOM_OF_THE_LAKE_HIDDEN_INSIDE_THE",
							export = true,
							text = {
								en = "At the bottom of the lake, hidden inside the base of a fallen statue.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在湖底，藏在一座倒塌雕像的基座内。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 31.0, 27.4, BASTION },
					}),
					q(61290, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "Jump over the short wall to the left of the statue at |cFFFFFFFF33.2, 36.8|r. The shard is at the end of the ledge.",
							constant = "JUMP_OVER_THE_SHORT_WALL_TO_THE_LEFT_OF_THE",
							export = true,
							text = {
								en = "Jump over the short wall to the left of the statue at |cFFFFFFFF33.2, 36.8|r. The shard is at the end of the ledge.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "跳过 |cFFFFFFFF33.2, 36.8|r 处雕像左侧的矮墙。碎片在平台尽头。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 33.0, 37.6, BASTION },
					}),
					q(61257, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "On a tiny outcropping behind Epistasia. Jump from the side, rather than trying to fall backwards to the shard.",
							constant = "ON_A_TINY_OUTCROPPING_BEHIND_EPISTASIA_JUMP",
							export = true,
							text = {
								en = "On a tiny outcropping behind Epistasia. Jump from the side, rather than trying to fall backwards to the shard.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在埃皮斯塔西娅身后的一小块凸出岩石上。从侧面跳过去，不要试图背对着碎片往下落。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 34.8, 65.7, BASTION },
					}),
					q(61287, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "The path to this shard starts at |cFFFFFFFF35.1, 23.2|r. Just follow the ledge around the cliffs.",
							constant = "THE_PATH_TO_THIS_SHARD_STARTS_AT_CFFFFFFFF35_1",
							export = true,
							text = {
								en = "The path to this shard starts at |cFFFFFFFF35.1, 23.2|r. Just follow the ledge around the cliffs.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "通往这块碎片的路径起点在|cFFFFFFFF35.1, 23.2|r。沿着悬崖周围的岩架前行即可。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 37.1, 24.6, BASTION },
					}),
					q(61264, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "Up at the top of a small fallen pillar.",
							constant = "UP_AT_THE_TOP_OF_A_SMALL_FALLEN_PILLAR",
							export = true,
							text = {
								en = "Up at the top of a small fallen pillar.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在一根倒下的小石柱的顶端。",
								-- TODO: tw = "",
							},
						}),	-- TODO: i don't remember if it was a pillar or a crumbled building or something, fix wording?
						["icon"] = 3528288,
						["coord"] = { 38.5, 53.2, BASTION },
					}),
					q(61225, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "Underneath the bridge that runs from Aspirant's Crucible to the Vestibule of Eternity.\n\nUse a Goblin Glider at |cFFFFFFFF39.6, 74.6|r to reach the platform. After you've collected the shard, leap off the side and a Kyrian will carry you to safety.",
							constant = "UNDERNEATH_THE_BRIDGE_THAT_RUNS_FROM_ASPIRANT_S",
							export = true,
							text = {
								en = "Underneath the bridge that runs from Aspirant's Crucible to the Vestibule of Eternity.\n\nUse a Goblin Glider at |cFFFFFFFF39.6, 74.6|r to reach the platform. After you've collected the shard, leap off the side and a Kyrian will carry you to safety.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在从候选者熔炉通往永恒前庭的桥下。\n\n在 |cFFFFFFFF39.6, 74.6|r 处使用地精滑翔器即可到达平台。拾取碎片后，从侧面跳下，会有基瑞安将你带到安全处。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 39.0, 77.0, BASTION },
					}),
					q(61263, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "On top of a pillar. Jump down from the cliffs above. Levitate helped me reach this one.",
							constant = "ON_TOP_OF_A_PILLAR_JUMP_DOWN_FROM_THE_CLIFFS",
							export = true,
							text = {
								en = "On top of a pillar. Jump down from the cliffs above. Levitate helped me reach this one.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在一根柱子顶部。从上方悬崖跳下。漂浮术帮我够到了这一个。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 40.0, 59.1, BASTION },
					}),
					q(61261, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "Don't fully jump down from the cliffs. It's on the lower portion, hidden on a narrow ledge.",
							constant = "DON_T_FULLY_JUMP_DOWN_FROM_THE_CLIFFS_IT_S_ON",
							export = true,
							text = {
								en = "Don't fully jump down from the cliffs. It's on the lower portion, hidden on a narrow ledge.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "不要从悬崖上直接跳下去。它在较低的位置，藏在一处狭窄的岩架上。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 41.4, 46.6, BASTION },
					}),
					q(61286, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "From |cFFFFFFFF43.8, 21.6|r, simply walk toward the shard's coordinates. It's just through an arch on a ledge.",
							constant = "FROM_CFFFFFFFF43_8_21_6_R_SIMPLY_WALK_TOWARD",
							export = true,
							text = {
								en = "From |cFFFFFFFF43.8, 21.6|r, simply walk toward the shard's coordinates. It's just through an arch on a ledge.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "从|cFFFFFFFF43.8, 21.6|r出发，径直朝碎片的坐标走去即可。它就在穿过一道拱门后的平台上。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 42.3, 24.0, BASTION },
					}),
					q(61289, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "On top of a gazebo with a crystal roof. You will have to jump down to the shard from the cliffs above.",
							constant = "ON_TOP_OF_A_GAZEBO_WITH_A_CRYSTAL_ROOF_YOU_WILL",
							export = true,
							text = {
								en = "On top of a gazebo with a crystal roof. You will have to jump down to the shard from the cliffs above.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在一座水晶顶凉亭的顶部。你需要从上方悬崖跳到碎片处。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 42.7, 39.4, BASTION },
					}),
					q(61288, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "At the end of a narrow ledge that starts at |cFFFFFFFF43.6, 33.8|r.",
							constant = "AT_THE_END_OF_A_NARROW_LEDGE_THAT_STARTS_AT",
							export = true,
							text = {
								en = "At the end of a narrow ledge that starts at |cFFFFFFFF43.6, 33.8|r.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在一条狭窄岩架的尽头，岩架起点位于 |cFFFFFFFF43.6, 33.8|r。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 42.8, 33.2, BASTION },
					}),
					q(61235, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "On the middle level of the waterfall. Jump down from above.",
							constant = "ON_THE_MIDDLE_LEVEL_OF_THE_WATERFALL_JUMP_DOWN",
							export = true,
							text = {
								en = "On the middle level of the waterfall. Jump down from above.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在瀑布的中层。从上方跳下。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 43.6, 76.2, BASTION },
					}),
					q(61285, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "On a ledge underneath a waterfall. The path starts at |cFFFFFFFF45.6, 25.2|r. Follow the ledge to the right until you get to the shard.",
							constant = "ON_A_LEDGE_UNDERNEATH_A_WATERFALL_THE_PATH",
							export = true,
							text = {
								en = "On a ledge underneath a waterfall. The path starts at |cFFFFFFFF45.6, 25.2|r. Follow the ledge to the right until you get to the shard.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在瀑布下方的一处岩架上。路径起点位于 |cFFFFFFFF45.6, 25.2|r。沿着岩架向右走，直到抵达碎片。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 44.9, 28.4, BASTION },
					}),
					q(61284, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "The path starts around |cFFFFFFFF45.5, 20.3|r. Just follow the ledge on the right. You will pass a statue of a steward when you are about halfway to the shard. The path is so narrow and short in some places that mounting will knock you off the path or prevent you from continuing along it.",
							constant = "THE_PATH_STARTS_AROUND_CFFFFFFFF45_5_20_3_R",
							export = true,
							text = {
								en = "The path starts around |cFFFFFFFF45.5, 20.3|r. Just follow the ledge on the right. You will pass a statue of a steward when you are about halfway to the shard. The path is so narrow and short in some places that mounting will knock you off the path or prevent you from continuing along it.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "路径起点大约在|cFFFFFFFF45.5, 20.3|r。沿着右侧的岩架前行即可。当你走到通往碎片路程的一半左右时，会经过一座管家雕像。有些地方路径又窄又短，上坐骑会把你从路上撞下去或使你无法继续沿路前进。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 46.7, 18.0, BASTION },
					}),
					q(61253, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "On top of a fallen wall. Climb up, and then you can carefully fall backwards towards the shard.",
							constant = "ON_TOP_OF_A_FALLEN_WALL_CLIMB_UP_AND_THEN_YOU",
							export = true,
							text = {
								en = "On top of a fallen wall. Climb up, and then you can carefully fall backwards towards the shard.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在一堵倒塌的墙顶上。爬上去，然后你可以小心地背对着碎片往下落。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 46.7, 65.9, BASTION },
					}),
					q(61260, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "On the middle section of the cliffside, underneath the platform.",
							constant = "ON_THE_MIDDLE_SECTION_OF_THE_CLIFFSIDE",
							export = true,
							text = {
								en = "On the middle section of the cliffside, underneath the platform.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在崖壁的中段，平台下方。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 47.0, 49.2, BASTION },
					}),
					q(61236, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "On a very narrow piece of the framework of Aspirant's Rest. Use a Goblin Glider. You can go to the highest cliff on the other side of the building, but I was able to glide straight towards the shard from |cFFFFFFFF48.6, 70.7|r, land on the nearby pillar, and hop over to pick up the shard.",
							constant = "ON_A_VERY_NARROW_PIECE_OF_THE_FRAMEWORK_OF",
							export = true,
							text = {
								en = "On a very narrow piece of the framework of Aspirant's Rest. Use a Goblin Glider. You can go to the highest cliff on the other side of the building, but I was able to glide straight towards the shard from |cFFFFFFFF48.6, 70.7|r, land on the nearby pillar, and hop over to pick up the shard.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在晋升者之憩框架结构中一段非常狭窄的部分上。使用地精滑翔器。你可以到建筑另一侧最高的悬崖，但我可以从 |cFFFFFFFF48.6, 70.7|r 直接滑翔向碎片，落在附近的柱子上，再跳过去拾取碎片。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 48.4, 72.7, BASTION },
					}),
					q(61279, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "On top of a pillar. You will need to jump down from the cliffs above.",
							constant = "ON_TOP_OF_A_PILLAR_YOU_WILL_NEED_TO_JUMP_DOWN",
							export = true,
							text = {
								en = "On top of a pillar. You will need to jump down from the cliffs above.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在一根柱子顶部。你需要从上方悬崖跳下。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 48.5, 34.9, BASTION },
					}),
					q(61278, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "On a rock underneath the bridge. You will have to jump down from the cliffs on the western side.",
							constant = "ON_A_ROCK_UNDERNEATH_THE_BRIDGE_YOU_WILL_HAVE",
							export = true,
							text = {
								en = "On a rock underneath the bridge. You will have to jump down from the cliffs on the western side.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在桥下的一块岩石上。你需要从西侧的悬崖跳下。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 49.9, 38.2, BASTION },
					}),
					q(61254, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "On a beam that goes across the top of a little hut. You will have to jump down to the shard from the cliffs above.",
							constant = "ON_A_BEAM_THAT_GOES_ACROSS_THE_TOP_OF_A_LITTLE",
							export = true,
							text = {
								en = "On a beam that goes across the top of a little hut. You will have to jump down to the shard from the cliffs above.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在一座小屋顶横跨的横梁上。你需要从上方悬崖跳下才能到达碎片。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 50.6, 56.1, BASTION },
					}),
					q(61258, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "On the ledge of Hero's Rest, next to the stairs. You have to jump down to the bottom of the rocky platform and walk along the edge to reach the shard.",
							constant = "ON_THE_LEDGE_OF_HERO_S_REST_NEXT_TO_THE_STAIRS",
							export = true,
							text = {
								en = "On the ledge of Hero's Rest, next to the stairs. You have to jump down to the bottom of the rocky platform and walk along the edge to reach the shard.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在英雄之眠的岩架上，楼梯旁边。你需要跳到岩石平台底部，沿着边缘走过去才能到达碎片。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 51.6, 48.0, BASTION },
					}),
					q(61277, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "On top of a pillar. You will have to jump down from the cliffs above.",
							constant = "ON_TOP_OF_A_PILLAR_YOU_WILL_HAVE_TO_JUMP_DOWN",
							export = true,
							text = {
								en = "On top of a pillar. You will have to jump down from the cliffs above.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在一根柱子顶部。你需要从上方悬崖跳下。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 52.1, 39.4, BASTION },
					}),
					q(61283, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "Enter Covinkles' Workshop at |cFFFFFFFF53.8, 9.6|r. The shard is on the left side, behind some barrels.",
							constant = "ENTER_COVINKLES_WORKSHOP_AT_CFFFFFFFF53_8_9_6_R",
							export = true,
							text = {
								en = "Enter Covinkles' Workshop at |cFFFFFFFF53.8, 9.6|r. The shard is on the left side, behind some barrels.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在|cFFFFFFFF53.8, 9.6|r进入科文克的工作室。碎片在左侧，藏在一些木桶后面。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 52.4, 09.3, BASTION },
					}),
					q(61237, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "Underneath the cliff, on a small outcropping above the water. You'll need to jump from the side of the hill to get to the shard. Slow fall abilities are useful here.",
							constant = "UNDERNEATH_THE_CLIFF_ON_A_SMALL_OUTCROPPING",
							export = true,
							text = {
								en = "Underneath the cliff, on a small outcropping above the water. You'll need to jump from the side of the hill to get to the shard. Slow fall abilities are useful here.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在悬崖下方，水面上方的一小块突出岩台上。你需要从山坡侧面跳下去才能拿到碎片。缓落技能在这里很有用。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 52.6, 75.5, BASTION },
					}),
					q(61238, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "Underwater, beneath the little bridge.",
							constant = "UNDERWATER_BENEATH_THE_LITTLE_BRIDGE",
							export = true,
							text = {
								en = "Underwater, beneath the little bridge.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在水下，小桥的下方。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 53.3, 73.6, BASTION },
					}),
					q(61239, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "On top of one of the pillars. Some strategic jumping is required to get to this one (and luck).",
							constant = "ON_TOP_OF_ONE_OF_THE_PILLARS_SOME_STRATEGIC",
							export = true,
							text = {
								en = "On top of one of the pillars. Some strategic jumping is required to get to this one (and luck).",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在其中一根柱子顶部。需要一些技巧性的跳跃（还有运气）才能到达这一个。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 53.5, 80.6, BASTION },
					}),
					q(61251, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "At the bottom of waterfall on the left-hand side, inside a small shrine.",
							constant = "AT_THE_BOTTOM_OF_WATERFALL_ON_THE_LEFT_HAND",
							export = true,
							text = {
								en = "At the bottom of waterfall on the left-hand side, inside a small shrine.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在瀑布底部左侧的一座小神龛内。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 54.0, 59.6, BASTION },
					}),
					q(61241, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "On a little outcropping on the cliffside. Some strategic falling is required to reach this shard.",
							constant = "ON_A_LITTLE_OUTCROPPING_ON_THE_CLIFFSIDE_SOME",
							export = true,
							text = {
								en = "On a little outcropping on the cliffside. Some strategic falling is required to reach this shard.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在崖壁上的一小块凸出岩石上。需要一些技巧性的下落才能到达这个碎片。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 55.9, 86.6, BASTION },
					}),
					q(61281, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "Underneath the highest part of the cliff. Jump down to the second part of the cliff and walk underneath the large outcropping.",
							constant = "UNDERNEATH_THE_HIGHEST_PART_OF_THE_CLIFF_JUMP",
							export = true,
							text = {
								en = "Underneath the highest part of the cliff. Jump down to the second part of the cliff and walk underneath the large outcropping.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在悬崖最高处的下方。向下跳到悬崖的第二段，然后走到巨大突出岩体的下方。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 56.2, 17.3, BASTION },
					}),
					q(61280, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "Behind the Gilded Bulwark, on the left side of a small table.",
							constant = "BEHIND_THE_GILDED_BULWARK_ON_THE_LEFT_SIDE_OF_A",
							export = true,
							text = {
								en = "Behind the Gilded Bulwark, on the left side of a small table.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在镀金壁垒后面，一张小桌子的左侧。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 56.7, 28.8, BASTION },
					}),
					q(61247, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "Partway up the wall. You must jump down from the platform above.",
							constant = "PARTWAY_UP_THE_WALL_YOU_MUST_JUMP_DOWN_FROM_THE",
							export = true,
							text = {
								en = "Partway up the wall. You must jump down from the platform above.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在墙壁的中段。你必须从上面的平台跳下来。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 56.9, 74.9, BASTION },
					}),
					q(61275, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "Enter the Hall of Beasts at |cFFFFFFFF55.6, 43.0|r. The shard is all the way at the back, hidden behind some barrels.",
							constant = "ENTER_THE_HALL_OF_BEASTS_AT_CFFFFFFFF55_6_43_0",
							export = true,
							text = {
								en = "Enter the Hall of Beasts at |cFFFFFFFF55.6, 43.0|r. The shard is all the way at the back, hidden behind some barrels.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在|cFFFFFFFF55.6, 43.0|r进入野兽大厅。碎片在最里面，藏在一些木桶后面。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 57.5, 38.3, BASTION },
					}),
					q(61270, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "On top of the cliff (not in the cave below), at the base of a tree.",
							constant = "ON_TOP_OF_THE_CLIFF_NOT_IN_THE_CAVE_BELOW_AT",
							export = true,
							text = {
								en = "On top of the cliff (not in the cave below), at the base of a tree.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在悬崖顶部（不是下方的洞穴里），一棵树的树根处。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 57.6, 55.6, BASTION },
					}),
					q(61250, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "Don't go up the small staircase. To the right of the stairs, there is a passage that leads to the bottom of a little waterfall on the cliffside. The shard is there, to the left, underneath a Vesper.",
							constant = "DON_T_GO_UP_THE_SMALL_STAIRCASE_TO_THE_RIGHT_OF",
							export = true,
							text = {
								en = "Don't go up the small staircase. To the right of the stairs, there is a passage that leads to the bottom of a little waterfall on the cliffside. The shard is there, to the left, underneath a Vesper.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "不要上那段小楼梯。楼梯右侧有一条通道，通往崖壁上一处小瀑布的底部。碎片就在那里，在左侧一只薄暮者下方。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 58.1, 63.9, BASTION },
					}),
					q(61245, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "You have to carefully jump down from the cliffs. The shard is close to the edge of the map, next to a small pool of water at the top of a waterfall.",
							constant = "YOU_HAVE_TO_CAREFULLY_JUMP_DOWN_FROM_THE_CLIFFS",
							export = true,
							text = {
								en = "You have to carefully jump down from the cliffs. The shard is close to the edge of the map, next to a small pool of water at the top of a waterfall.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "你需要小心地从悬崖上跳下。碎片位于地图边缘附近，在瀑布顶端的一个小水潭旁。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 58.1, 80.0, BASTION },
					}),
					q(61282, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "On a ledge. You will need to jump down from the cliffs above.",
							constant = "ON_A_LEDGE_YOU_WILL_NEED_TO_JUMP_DOWN_FROM_THE",
							export = true,
							text = {
								en = "On a ledge. You will need to jump down from the cliffs above.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在一处岩架上。你需要从上方悬崖跳下。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 59.8, 13.9, BASTION },
					}),
					q(61244, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "On the edge of the cliffs.",
							constant = "ON_THE_EDGE_OF_THE_CLIFFS",
							export = true,
							text = {
								en = "On the edge of the cliffs.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在悬崖边缘。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 61.0, 85.6, BASTION },
					}),
					q(61271, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "On the upper level, in a bookshelf.",
							constant = "ON_THE_UPPER_LEVEL_IN_A_BOOKSHELF",
							export = true,
							text = {
								en = "On the upper level, in a bookshelf.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在上层的一个书架里。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 65.2, 42.8, BASTION },
					}),
					q(61249, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "Use the Anima Gateway at |cFFFFFFFF63.5, 72.4|r. You can only use the gateway if you aren't in combat, so be careful what you pull.\n\nAfter taking the gateway, head to the shard coordinates. It is hidden behind a pillar.",
							constant = "USE_THE_ANIMA_GATEWAY_AT_CFFFFFFFF63_5_72_4_R",
							export = true,
							text = {
								en = "Use the Anima Gateway at |cFFFFFFFF63.5, 72.4|r. You can only use the gateway if you aren't in combat, so be careful what you pull.\n\nAfter taking the gateway, head to the shard coordinates. It is hidden behind a pillar.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在 |cFFFFFFFF63.5, 72.4|r 处使用心能传送门。只有在你未处于战斗状态时才能使用传送门，所以拉怪时要小心。\n\n通过传送门后，前往碎片坐标。它藏在一根柱子后面。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 65.5, 71.9, BASTION },
					}),
					q(61274, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "Underneath the edge of the platform. Facing north, towards the sky, drop off the left-hand side of the platform and walk under it.",
							constant = "UNDERNEATH_THE_EDGE_OF_THE_PLATFORM_FACING",
							export = true,
							text = {
								en = "Underneath the edge of the platform. Facing north, towards the sky, drop off the left-hand side of the platform and walk under it.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "在平台边缘下方。面朝北方、朝向天空，从平台左侧跳下并走到平台下方。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 66.9, 26.9, BASTION },
					}),
					q(61273, {	-- Anima Crystal Shard
						["name"] = "Anima Crystal Shard",
						["description"] = createLocalizationString({
							readable = "Walk along the lower ledge that starts at |cFFFFFFFF71.4, 38.9|r.",
							constant = "WALK_ALONG_THE_LOWER_LEDGE_THAT_STARTS_AT",
							export = true,
							text = {
								en = "Walk along the lower ledge that starts at |cFFFFFFFF71.4, 38.9|r.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "沿着始于|cFFFFFFFF71.4, 38.9|r的下层岩架行走。",
								-- TODO: tw = "",
							},
						}),
						["icon"] = 3528288,
						["coord"] = { 72.4, 40.2, BASTION },
					}),
					-- TODO: keep these here, within the achievement, or move them to treasures or something?  you do the final 3 steps after the achievement is totally completed, it's just a prerequisite...so i'm not sure if it makes sense to have them here??
					n(171732, {	-- Forgelite Hephaesius
						["description"] = createLocalizationString({
							readable = "After you finish collecting all the shards from Bastion, Necrotic Wake, and Spires of Ascension, visit Hephaesius. Give him the shards, and he will forge them into a mallet.",
							constant = "AFTER_YOU_FINISH_COLLECTING_ALL_THE_SHARDS_FROM",
							export = true,
							text = {
								en = "After you finish collecting all the shards from Bastion, Necrotic Wake, and Spires of Ascension, visit Hephaesius. Give him the shards, and he will forge them into a mallet.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "从晋升堡垒、凋魂之殇和升腾堡垒收集完所有碎片后，去拜访赫菲斯乌斯。把碎片交给他，他会将它们锻造成一柄木槌。",
								-- TODO: tw = "",
							},
						}),
						["questID"] = 61229,	-- receiving the mallet from Hephaesius
						["coord"] = { 59.3, 31.4, BASTION },
						["groups"] = {
							i(180858),	-- Crystal Mallet of Heralds
						},
					}),
					o(355435, {	-- Vesper of the Silver Wind
						["description"] = createLocalizationString({
							readable = "Once you have the mallet, take it to the Vesper of the Silver Wind and ring the bell.",
							constant = "ONCE_YOU_HAVE_THE_MALLET_TAKE_IT_TO_THE_VESPER",
							export = true,
							text = {
								en = "Once you have the mallet, take it to the Vesper of the Silver Wind and ring the bell.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "拿到锤子后，把它带到银风晚祷处并敲响钟。",
								-- TODO: tw = "",
							},
						}),
						["questID"] = 61191,	-- ringing the bell
						["sourceQuest"] = 61229,	-- receiving the mallet from Hephaesius
						["coord"] = { 36.1, 26.6, BASTION },
						["provider"] = { "i", 180858 },	-- Crystal Mallet of Heralds
					}),
					o(355449, {	-- Gift of the Silver Wind
						["description"] = createLocalizationString({
							readable = "A Silverwind Larion will spawn behind you and drop a treasure chest containing the mount.",
							constant = "A_SILVERWIND_LARION_WILL_SPAWN_BEHIND_YOU_AND",
							export = true,
							text = {
								en = "A Silverwind Larion will spawn behind you and drop a treasure chest containing the mount.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "一只银风翼狮会在你身后刷新，并掉落一个装有该坐骑的宝箱。",
								-- TODO: tw = "",
							},
						}),
						["questID"] = 61183,	-- looting the treasure
						["sourceQuest"] = 61191,	-- ringing the bell
						["coord"] = { 36.1, 26.6, BASTION },
						["groups"] = {
							i(180772),	-- Silverwind Larion (MOUNT!)
						},
					}),
				},
			}),
			ach(14801, {	-- Sojourner of Bastion
				crit(50336, {	-- In Agthia's Memory
					["sourceQuests"] = { 57555 },	-- Shadow's Fall
				}),
				crit(50337, {	-- Wings of Freedom
					["sourceQuests"] = { 59865 },	-- Glimmerflight
				}),
				crit(50338, {	-- In the Garden of Respite
					["sourceQuests"] = { 57568 },	-- Tough Love
				}),
				crit(50339, {	-- The Spear of Kalliope
					["sourceQuests"] = { 60906 },	-- Rightful Resting Place (non-Kyrian)
				}),
				crit(50340, {	-- The Spear of Kalliope
					["sourceQuests"] = { 57967 },	-- Rightful Resting Place (Kyrian)
				}),
				crit(50334, {	-- Pride or Unit
					["sourceQuests"] = { 58103 },	-- Pride or Unit (Pelodis - Phalynx)
				}),
				crit(50333, {	-- Pride or Unit
					["sourceQuests"] = { 60296 },	-- Pride or Unit (Nemea - Larion)
				}),
			}),
			achWithRep(14335, FACTION_THE_ASCENDED),	-- The Ascended
			ach(14281, {	-- The Path to Ascension
				crit(48148, {	-- Eternity's Call
					["sourceQuests"] = { 57677 },	-- A Soulbind In Need
				}),
				crit(48149, {	-- The Aspirant's Crucible
					["sourceQuests"] = { 58174 },	-- All An Aspirant Can Do
				}),
				crit(48150, {	-- The Temple of Purity
					["sourceQuests"] = { 57447 },	-- Purity's Prerogative
				}),
				crit(48151, {	-- Chasing a Memory
					["sourceQuests"] = { 60013 },	-- Leave it to Mnemis
				}),
				crit(50099, {	-- Your Personal Assistant
					["sourceQuests"] = { 59426 },	-- Your Personal Assistant
				}),
				crit(48152, {	-- A Time for Courage
					["sourceQuests"] = { 60055 },	-- A Time for Courage
				}),
				crit(48153, {	-- A Land of Strife
					["sourceQuests"] = { 61107 },	-- A Land of Strife
				}),
			}),
			pvp(ach(14514)),	-- Tour of Duty: Bastion
			ach(14311, {	-- Treasures of Bastion
				crit(50047, {	-- Scroll of Aeons
					["_quests"] = { 58298 },
				}),
				crit(50048, {	-- Vesper of Virtues
					["_quests"] = { 60478 },
				}),
				crit(50049, {	-- Purifying Draught
					["_quests"] = { 58329 },
				}),
				crit(50050, {	-- Lost Disciple's Notes
					["_quests"] = { 61048 },
				}),
				crit(50051, {	-- Larion Tamer's Harness
					["_quests"] = { 61049 },
				}),
				crit(50052, {	-- Stolen Equipment
					["_quests"] = { 61044 },
				}),
				crit(50053, {	-- Abandoned Stockpile
					["_quests"] = { 61006 },
				}),
				crit(50054, {	-- Experimental Construct Part
					["_quests"] = { 61052 },
				}),
				crit(50055, {	-- Windsmith's Tools
					["_quests"] = { 61053 },
				}),
				crit(50056, {	-- Memorial Offerings
					["_quests"] = { 61150 },
				}),
				crit(50058, {	-- Gift of Agthia
					["_quests"] = { 60893 },
				}),
				crit(50059, {	-- Gift of Vesiphone
					["_quests"] = { 60890 },
				}),
				crit(50060, {	-- Gift of Chyrus
					["_quests"] = { 60892 },
				}),
				crit(50061, {	-- Gift of Thenios
					["_quests"] = { 60894 },
				}),
				crit(50062, {	-- Gift of Devos
					["_quests"] = { 60895 },
				}),
				i(284546, { ["timeline"] = { ADDED_12_1_5 } }),	-- Runic Kyrian Reliquary (DECOR!)
			}),
			ach(14768, {	-- What is that Melody?
				crit(49947, {		-- Hymn of Purity
					["description"] = createLocalizationString({
						readable = "Triangular stacks of bundled scrolls, often found on tables and benches. The coordinates given are not exhaustive; this scroll can spawn throughout the Temple of Purity. Part of this temple is full of elite mobs.",
						constant = "TRIANGULAR_STACKS_OF_BUNDLED_SCROLLS_OFTEN",
						export = true,
						text = {
							en = "Triangular stacks of bundled scrolls, often found on tables and benches. The coordinates given are not exhaustive; this scroll can spawn throughout the Temple of Purity. Part of this temple is full of elite mobs.",
							-- TODO: de = "",
							-- TODO: es = "",
							-- TODO: mx = "",
							-- TODO: fr = "",
							-- TODO: it = "",
							-- TODO: ko = "",
							-- TODO: pt = "",
							-- TODO: ru = "",
							cn = "成捆卷轴堆成的三角形垛，通常出现在桌子和长凳上。所给坐标并不完整；这份卷轴可在纯净神庙各处刷新。这座神庙的部分区域到处都是精英怪物。",
							-- TODO: tw = "",
						},
					}),
					["coords"] = {
						{ 57.8, 73.8, BASTION },
						{ 57.8, 79.1, BASTION },
						{ 60.6, 76.4, BASTION },
						{ 61.0, 76.1, BASTION },
						{ 62.8, 71.2, BASTION },
						{ 63.8, 73.5, BASTION },
					},
				}),
				crit(49948, {		-- Hymn of Courage
					["description"] = createLocalizationString({
						readable = "Rolled scrolls that can be found on the ground. The coordinates given are not exhaustive; this scroll can spawn throughout the Temple of Courage. The transport pad to reach the area is located at |cFFFFFFFF39.2, 56.1|r.",
						constant = "ROLLED_SCROLLS_THAT_CAN_BE_FOUND_ON_THE_GROUND",
						export = true,
						text = {
							en = "Rolled scrolls that can be found on the ground. The coordinates given are not exhaustive; this scroll can spawn throughout the Temple of Courage. The transport pad to reach the area is located at |cFFFFFFFF39.2, 56.1|r.",
							-- TODO: de = "",
							-- TODO: es = "",
							-- TODO: mx = "",
							-- TODO: fr = "",
							-- TODO: it = "",
							-- TODO: ko = "",
							-- TODO: pt = "",
							-- TODO: ru = "",
							cn = "卷起的卷轴，可在地面上找到。所给坐标并不完整；该卷轴可在整个勇气神殿内刷新。前往该区域的传送台位于|cFFFFFFFF39.2, 56.1|r。",
							-- TODO: tw = "",
						},
					}),
					["coords"] = {
						{ 29.7, 56.5, BASTION },
						{ 30.8, 54.8, BASTION },
						{ 31.9, 54.6, BASTION },
						{ 32.1, 55.9, BASTION },
						{ 33.6, 59.6, BASTION },
						{ 34.1, 58.5, BASTION },
						{ 35.4, 55.6, BASTION },
					},
				}),
				crit(49949, {		-- Hymn of Humility
					["description"] = createLocalizationString({
						readable = "Vertical scrolls that are often on tables. The coordinates given are not exhaustive; this scroll can spawn throughout the Temple of Humility.",
						constant = "VERTICAL_SCROLLS_THAT_ARE_OFTEN_ON_TABLES_THE",
						export = true,
						text = {
							en = "Vertical scrolls that are often on tables. The coordinates given are not exhaustive; this scroll can spawn throughout the Temple of Humility.",
							-- TODO: de = "",
							-- TODO: es = "",
							-- TODO: mx = "",
							-- TODO: fr = "",
							-- TODO: it = "",
							-- TODO: ko = "",
							-- TODO: pt = "",
							-- TODO: ru = "",
							cn = "通常放在桌子上的竖直卷轴。所给坐标并不完整；这份卷轴可在谦逊神庙各处刷新。",
							-- TODO: tw = "",
						},
					}),
					["coords"] = {
						{ 63.0, 42.8, BASTION },
						{ 63.9, 44.1, BASTION },
						{ 65.2, 43.1, BASTION },
						{ 66.0, 40.8, BASTION },
						{ 67.1, 43.3, BASTION },
						{ 67.2, 43.1, BASTION },
						{ 67.6, 43.4, BASTION },
					},
				}),
				crit(49950, {		-- Hymn of Wisdom
					["description"] = createLocalizationString({
						readable = "Vertical scrolls that are often pinned to monuments or walls. The coordinates given are not exhaustive; this scroll can spawn throughout the Temple of Wisdom.",
						constant = "VERTICAL_SCROLLS_THAT_ARE_OFTEN_PINNED_TO",
						export = true,
						text = {
							en = "Vertical scrolls that are often pinned to monuments or walls. The coordinates given are not exhaustive; this scroll can spawn throughout the Temple of Wisdom.",
							-- TODO: de = "",
							-- TODO: es = "",
							-- TODO: mx = "",
							-- TODO: fr = "",
							-- TODO: it = "",
							-- TODO: ko = "",
							-- TODO: pt = "",
							-- TODO: ru = "",
							cn = "通常钉在纪念碑或墙上的竖直卷轴。所给坐标并不完整；这份卷轴可在智慧神庙各处刷新。",
							-- TODO: tw = "",
						},
					}),
					["coords"] = {
						{ 41.6, 24.2, BASTION },
						{ 42.1, 23.7, BASTION },
						{ 43.1, 28.1, BASTION },
						{ 43.9, 25.9, BASTION },
					},
				}),
			}),
		}),
	}),
})));
