#!/usr/bin/env python3
"""Validate the final ATT ZIP, without executing addon code or publishing it."""

import argparse
import pathlib
import re
import subprocess
import tempfile
import zipfile
import xml.etree.ElementTree as ET

# Match the database targets generated by Parser.yml, including both Era modes.
GAMES = {
    "Standard": "mainline", "Vanilla": "vanilla", "VanillaSOD": "vanilla",
    "TBC": "tbc", "Wrath": "wrath", "Cata": "cata", "Mists": "mists",
    "Camelot": "camelot",
}
# Match the flavored TOC names recognized by the pinned packager. Its Mainline
# TOCs also support the Forever/Camelot target; Classic TOCs explicitly do not.
TOC_SUFFIXES = {
    "Standard": ("Mainline",), "Vanilla": ("Vanilla", "Classic"),
    "VanillaSOD": ("Vanilla", "Classic"), "TBC": ("TBC", "BCC", "Classic"),
    "Wrath": ("Wrath", "WOTLKC", "Classic"), "Cata": ("Cata", "Classic"),
    "Mists": ("Mists", "Classic"), "Camelot": ("Camelot", "Mainline"),
}
CONDITION = re.compile(r"\s*\[(Allow|Exclude)LoadGameType\s+([^]]+)\]\s*$", re.I)


def family(game):
    return "Mainline" if game in ("Standard", "Camelot") else "Classic"


def select_toc(addon, game):
    for suffix in TOC_SUFFIXES[game]:
        for separator in ("_", "-"):
            toc = addon / f"AllTheThings{separator}{suffix}.toc"
            if toc.is_file():
                return toc
    return addon / "AllTheThings.toc"


def toc_reference(line, game):
    """WoW TOC conditions follow the filename; 'classic' includes classic games."""
    allowed = True
    while match := CONDITION.search(line):
        kinds = {kind.strip().lower() for kind in match[2].split(",")}
        matches = GAMES[game] in kinds or (family(game) == "Classic" and "classic" in kinds)
        allowed &= matches if match[1].lower() == "allow" else not matches
        line = line[:match.start()].strip()
    return line if allowed else None


def validate_references(addon, game):
    visited = set()

    def resolve(base, name):
        name = name.replace("\\", "/").replace("[Game]", game)
        name = name.replace("[Family]", family(game))
        path = (base / name).resolve()
        if not path.is_relative_to(addon):
            raise ValueError(f"Reference escapes addon: {name}")
        if not path.is_file():
            raise ValueError(f"Missing {game} reference: {path.relative_to(addon)}")
        return path

    def visit(path):
        if path in visited:
            return
        visited.add(path)
        if path.suffix.lower() == ".xml":
            for element in ET.parse(path).iter():
                if element.tag.rsplit("}", 1)[-1] in ("Script", "Include") and "file" in element.attrib:
                    visit(resolve(path.parent, element.attrib["file"]))

    # Also detect an entirely missing generated flavor (not just missing files).
    for name in ("ReferenceDB.lua", "Database.xml"):
        visit(resolve(addon, f"db/{game}/{name}"))
    toc = select_toc(addon, game)
    if not toc.is_file():
        raise ValueError(f"Missing {game} TOC")
    for line in toc.read_text(encoding="utf-8-sig").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            reference = toc_reference(line, game)
            if reference:
                visit(resolve(toc.parent, reference))


def validate_archive(archive, luac="luac5.1"):
    version = subprocess.run([luac, "-v"], capture_output=True, check=True)
    if not re.search(rb"Lua 5\.1(?:\.|\s)", version.stdout + version.stderr):
        raise ValueError("Package syntax checks require Lua 5.1")
    with tempfile.TemporaryDirectory(prefix="att-package-check-") as temp:
        with zipfile.ZipFile(archive) as package:
            names = set()
            for entry in package.infolist():
                path = pathlib.PurePosixPath(entry.filename)
                if path.is_absolute() or ".." in path.parts or "\\" in entry.filename:
                    raise ValueError(f"Unsafe ZIP path: {entry.filename}")
                if entry.filename in names or (entry.external_attr >> 16) & 0o170000 == 0o120000:
                    raise ValueError(f"Duplicate or symlink ZIP entry: {entry.filename}")
                names.add(entry.filename)
            toc_names = {"AllTheThings/AllTheThings.toc"} | {
                f"AllTheThings/AllTheThings{separator}{suffix}.toc"
                for suffixes in TOC_SUFFIXES.values() for suffix in suffixes
                for separator in ("_", "-")
            }
            if not names.intersection(toc_names):
                raise ValueError("ZIP is missing an AllTheThings TOC")
            bad = package.testzip()
            if bad:
                raise ValueError(f"ZIP CRC failure: {bad}")
            package.extractall(temp)
        addon = (pathlib.Path(temp) / "AllTheThings").resolve()
        lua_files = list(addon.rglob("*.lua"))
        for path in lua_files:
            # WoW accepts UTF-8 BOMs; stock Lua 5.1's compiler does not.
            source = path.read_bytes().removeprefix(b"\xef\xbb\xbf")
            result = subprocess.run([luac, "-p", "-"], input=source, capture_output=True)
            if result.returncode:
                raise ValueError(f"{path.relative_to(addon)}: {result.stderr.decode(errors='replace').strip()}")
        for game in GAMES:
            validate_references(addon, game)
        print(f"Validated {archive}: {len(lua_files)} Lua files, {len(GAMES)} database targets")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("archives", nargs="+", type=pathlib.Path)
    parser.add_argument("--luac", default="luac5.1")
    args = parser.parse_args()
    try:
        for archive in args.archives:
            validate_archive(archive, args.luac)
    except (OSError, ValueError, zipfile.BadZipFile, ET.ParseError, subprocess.CalledProcessError) as error:
        parser.exit(1, f"Package validation failed: {error}\n")


if __name__ == "__main__":
    main()
