STARTER_GEAR = createHeader({
	readable = "Starter Gear",
	icon = 135018,
	text = {
		en = "Starter Gear",
		--de = "",
		--es = "",
		--mx = "",
		--fr = "",
		--it = "",
		--ko = "",
		--pt = "",
		--ru = "",
		cn = "起始装备",
		--tw = "",
	},
	description = {
		en = "The following contains gear that can be acquired by creating a brand new character of a given class and race.",
		--de = "",
		--es = "",
		--mx = "",
		--fr = "",
		--it = "",
		--ko = "",
		--pt = "",
		--ru = "",
		cn = "以下装备可通过创建对应种族与职业的全新角色获取。",
		--tw = "",
	},
});
