local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[568276] = {
		readable = "Unoccupied Mana Loom",
		model = 7197584,
		text = {
			en = "Unoccupied Mana Loom",
			es = "[Unoccupied Mana Loom]",
			mx = "[Unoccupied Mana Loom]",
			de = "[Unoccupied Mana Loom]",
			fr = "[Unoccupied Mana Loom]",
			it = "[Unoccupied Mana Loom]",
			pt = "[Unoccupied Mana Loom]",
			ru = "[Unoccupied Mana Loom]",
			ko = "[Unoccupied Mana Loom]",
			cn = "[Unoccupied Mana Loom]",
			tw = "[Unoccupied Mana Loom]",
		},
	},
	[584515] = {
		readable = "Bountiful Heavy Trunk",
		model = 5128194,
		text = {
			en = "Bountiful Heavy Trunk",
			es = "[Bountiful Heavy Trunk]",
			mx = "[Bountiful Heavy Trunk]",
			de = "[Bountiful Heavy Trunk]",
			fr = "[Bountiful Heavy Trunk]",
			it = "[Bountiful Heavy Trunk]",
			pt = "[Bountiful Heavy Trunk]",
			ru = "[Bountiful Heavy Trunk]",
			ko = "[Bountiful Heavy Trunk]",
			cn = "[Bountiful Heavy Trunk]",
			tw = "[Bountiful Heavy Trunk]",
		},
	},
	[584518] = {
		readable = "Bountiful Heavy Trunk",
		model = 5128194,
		text = {
			en = "Bountiful Heavy Trunk",
			es = "[Bountiful Heavy Trunk]",
			mx = "[Bountiful Heavy Trunk]",
			de = "[Bountiful Heavy Trunk]",
			fr = "[Bountiful Heavy Trunk]",
			it = "[Bountiful Heavy Trunk]",
			pt = "[Bountiful Heavy Trunk]",
			ru = "[Bountiful Heavy Trunk]",
			ko = "[Bountiful Heavy Trunk]",
			cn = "[Bountiful Heavy Trunk]",
			tw = "[Bountiful Heavy Trunk]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
