
local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[572785] = {
		readable = "Olemba Lumber",
		model = 6922313,
		text = {
			en = "Olemba Lumber",
			es = "Madera de olemba",
			mx = "Madera de olemba",
			de = "Olembaholz",
			fr = "Bois d’olemba",
			it = "Legname di Olemba",
			ru = "Олембовая древесина",
		},
	},
	[628447] = {
		readable = "Jan'alai's Breath",
		model = 6866517,
		text = {
			en = "Jan'alai's Breath",
			es = "Aliento de Jan'alai",
			mx = "Aliento de Jan'alai",
			de = "Jan'alais Atem",
			fr = "Souffle de Jan’alai",
			it = "Respiro di Jan'alai",
			pt = "Sopro de Jan'alai",
			ru = "Дыхание Джан'алай",
			ko = "잔알라이의 숨결",
			cn = "加亚莱的呼吸",
			tw = "賈納雷的吐息",
		},
	},
	[649651] = {
		readable = "Eye of Szarith",
		model = 1382579,
		text = {
			en = "Eye of Szarith",
			es = "Ojo de Szarith",
			mx = "Ojo de Szarith",
			de = "Auge von Szarith",
			fr = "Œil de Szarith",
			it = "Occhio di Szarith",
			pt = "Olho de Szarith",
			ru = "Око Сзарита",
			ko = "스자리스의 눈",
			cn = "萨里斯之眼",
			tw = "札里斯之眼",
		},
	},
	[653064] = {
		readable = "Ossified Relic",
		model = 6153817,
		text = {
			en = "Ossified Relic",
			es = "Reliquia osificada",
			mx = "Reliquia osificada",
			de = "Verknöchertes Relikt",
			fr = "Relique ossifiée",
			it = "Reliquia Ossificata",
			pt = "Relíquia Ossificada",
			ru = "Окостеневшая реликвия",
			ko = "골화 성물",
			cn = "骨化圣物",
			tw = "骨化聖物",
		},
	},
	[655007] = {
		readable = "Wooden Toy Sword",
		model = 5658299,
		text = {
			en = "Wooden Toy Sword",
		},
	},
	[656046] = {
		readable = "Unfortunate Scout's Satchel",
		model = 6212425,
		text = {
			en = "Unfortunate Scout's Satchel",
			de = "Tasche des unglückseligen Spähers",
			fr = "Sacoche d’éclaireur malchanceux",
			pt = "Algibeira do Batedor Desafortunado",
			ru = "Сумка неудачливого разведчика",
		},
	},
	[671498] = {
		readable = "Venom-Worn Coffer",
		model = 1382579,
		text = {
			en = "Venom-Worn Coffer",
			es = "Arca desgastada por el veneno",
			mx = "Arca desgastada por el veneno",
			de = "Giftzersetzte Kiste",
			fr = "Coffret usé par le venin",
			it = "Scrigno Consumato dal Veleno",
			pt = "Cofre Desgastado por Peçonha",
			ru = "Изъеденный ядом ларец",
			ko = "맹독에 닳은 궤짝",
			cn = "毒蚀宝匣",
			tw = "毒蝕寶庫",
		},
	},
	[671500] = {
		readable = "Feather of Tok'jara",
		model = 7550572,
		text = {
			en = "Feather of Tok'jara",
			es = "Pluma de Tok'jara",
			mx = "Pluma de Tok'jara",
			de = "Feder von Tok'jara",
			fr = "Plume de Tok’jara",
			it = "Piuma di Tok'jara",
			pt = "Pena de Tok'jara",
			ru = "Перо Ток'джары",
			ko = "토크자라의 깃털",
			cn = "托克贾拉的羽毛",
			tw = "托加拉之羽",
		},
	},
	[671508] = {
		readable = "Jin'tal's Reliquary",
		model = 7277200,
		text = {
			en = "Jin'tal's Reliquary",
			es = "Relicario de Jin'tal",
			mx = "Relicario de Jin'tal",
			de = "Jin'tals Reliquiar",
			fr = "Reliquaire de Jin’tal",
			it = "Reliquiario di Jin'tal",
			pt = "Relicário de Jin'tal",
			ru = "Реликварий Джин'тала",
			ko = "진탈의 성물함",
			cn = "金塔尔的遗物匣",
			tw = "金塔爾的聖匣",
		},
	},
	[673637] = {
		readable = "Lost Explorer's Bounty",
		model = 1805764,
		text = {
			en = "Lost Explorer's Bounty",
		},
	},
})
do ObjectDB[objectID] = objectData; end
