local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[572474] = {
		readable = "Arcane Mana Crystal",
		model = 5144849,
		text = {
			en = "Arcane Mana Crystal",
			es = "Cristal de maná Arcano",
			mx = "Cristal de maná arcano",
			de = "Arkanmanakristall",
			fr = "Cristal de mana arcanique",
			it = "Cristallo di Mana Arcano",
			pt = "Cristal de Mana Arcano",
			ru = "Чародейский кристалл маны",
			ko = "비전 마나 결정",
			cn = "奥术法力水晶",
			-- TODO: tw = "",
		},
	},
	[572475] = {
		readable = "Magister's Elixir",
		model = 243481,
		text = {
			en = "Magister's Elixir",
			es = "Elixir de magister",
			mx = "Elixir de magíster",
			de = "Elixier des Magisters",
			fr = "Élixir de magistère",
			it = "Elisir del Magistro",
			pt = "Elixir do Magíster",
			ru = "Эликсир магистра",
			ko = "마법학자의 비약",
			cn = "魔导师的灵药",
			tw = "[Magister's Elixir]",
		},
	},
	[572477] = {
		readable = "Weapons Rack",
		model = 6005301,
		text = {
			en = "Weapons Rack",
			es = "Expositor de armas",
			mx = "Expositor de armas",
			de = "Waffenregal",
			fr = "Râteliers d’armes",
			it = "Rastrelliera delle Armi",
			pt = "Cavalete de Armas",
			ru = "Стойка с оружием",
			ko = "무기 선반",
			cn = "武器架",
			-- TODO: tw = "",
		},
	},
	[572766] = {
		readable = "Trash Heap",
		model = 1255034,
		text = {
			en = "Trash Heap",
			es = "Montón de basura",
			mx = "Montón de basura",
			de = "Müllhaufen",
			fr = "Tas d’ordures",
			it = "Mucchio di Spazzatura",
			pt = "Monte de Lixo",
			ru = "Гора мусора",
			ko = "쓰레기 더미",
			cn = "垃圾堆",
			tw = "垃圾堆",
		},
	},
	[574460] = {
		readable = "Replica Twin Blades of Azzinoth",
		model = 124618,
		text = {
			en = "Replica Twin Blades of Azzinoth",
			es = "Réplica de las hojas gemelas de Azzinoth",
			mx = "Réplica de las Hojas gemelas de Azzinoth",
			de = "Nachbildung: Zwillingsklingen von Azzinoth",
			fr = "Réplique des Lames jumelles d’Azzinoth",
			it = "Replica delle Lame Gemelle di Azzinoth",
			pt = "Réplica das Lâminas Gêmeas de Azzinoth",
			ru = "Копия парных клинков Аззинота",
			ko = "복제 아지노스의 쌍날검",
			cn = "仿制的埃辛诺斯双刃",
			tw = "埃辛諾斯雙刃複製品",
		},
	},
	[577702] = {
		readable = "Barricade",
		model = 6005292,
		text = {
			en = "Barricade",
			es = "Barricada",
			mx = "Barricada",
			de = "Barrikade",
			fr = "Barricade",
			it = "Barricata",
			pt = "Barricada",
			ru = "Баррикада",
			ko = "방벽",
			cn = "路障",
			-- TODO: tw = "",
		},
	},
	[578273] = {
		readable = "Delivery Crate",
		model = 4198209,
		text = {
			en = "Delivery Crate",
			es = "Cajón de reparto",
			mx = "Cajón de entrega",
			de = "Lieferkiste",
			fr = "Caisse de livraison",
			it = "Cassa di Consegne",
			pt = "Caixote de Entrega",
			ru = "Ящик с грузом",
			ko = "배달 상자",
			cn = "货运箱子",
			tw = "運送木箱",
		},
	},
	[578955] = {
		readable = "Flickering Spoils",
		model = 193578,
		text = {
			en = "Flickering Spoils",
			es = "Botín parpadeante",
			mx = "Botines titilantes",
			de = "Flackernde Schätze",
			fr = "Butin vacillant",
			it = "Spoglie Guizzanti",
			pt = "Espólios Tremeluzentes",
			ru = "Мерцающие трофеи",
			ko = "명멸하는 전리품",
			cn = "闪烁战利品",
			tw = "閃爍戰利品",
		},
	},
	[578956] = {
		readable = "Shadowed Flickering Spoils",
		model = 193578,
		text = {
			en = "Shadowed Flickering Spoils",
			es = "Botín parpadeante ensombrecido",
			mx = "Botines titilantes oscurecidos",
			de = "Schattenhafte flackernde Schätze",
			fr = "Butin ombreux vacillant",
			it = "Spoglie Guizzanti Adombrate",
			pt = "Espólios Tremeluzentes Sombrios",
			ru = "Затененные мерцающие трофеи",
			ko = "어둠에 물든 명멸하는 전리품",
			cn = "蔽影闪烁战利品",
			tw = "朧影的閃爍戰利品",
		},
	},
	[580106] = {
		readable = "Void Zeal",
		model = 166432,
		text = {
			en = "Void Zeal",
			es = "Celo del Vacío",
			-- TODO: mx = "",
			de = "Leereneifer",
			fr = "Zèle du Vide",
			-- TODO: it = "",
			pt = "Fervor do Caos",
			ru = "Рвение Бездны",
			ko = "공허의 열정",
			cn = "虚空狂热",
			-- TODO: tw = "",
		},
	},
	[584540] = {
		readable = "Chest of Proven Valor",
		model = 6195763,
		text = {
			en = "Chest of Proven Valor",
			es = "Cofre de valor acreditado",
		},
	},
})
do ObjectDB[objectID] = objectData; end
