local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[654975] = {
		readable = "Ingredients",
		model = 533073,
		text = {
			en = "Ingredients",
			es = "[Ingredients]",
			mx = "[Ingredients]",
			de = "[Ingredients]",
			fr = "[Ingredients]",
			it = "[Ingredients]",
			pt = "[Ingredients]",
			ru = "[Ingredients]",
			ko = "[Ingredients]",
			cn = "[Ingredients]",
			tw = "[Ingredients]",
		},
	},
	[654977] = {
		readable = "Stormstout Brewery Lantern",
		model = 526368,
		text = {
			en = "Stormstout Brewery Lantern",
			es = "[Stormstout Brewery Lantern]",
			mx = "[Stormstout Brewery Lantern]",
			de = "[Stormstout Brewery Lantern]",
			fr = "[Stormstout Brewery Lantern]",
			it = "[Stormstout Brewery Lantern]",
			pt = "[Stormstout Brewery Lantern]",
			ru = "[Stormstout Brewery Lantern]",
			ko = "[Stormstout Brewery Lantern]",
			cn = "[Stormstout Brewery Lantern]",
			tw = "[Stormstout Brewery Lantern]",
		},
	},
	[654980] = {
		readable = "Stormstout Brewery Lantern",
		model = 526368,
		text = {
			en = "Stormstout Brewery Lantern",
			es = "[Stormstout Brewery Lantern]",
			mx = "[Stormstout Brewery Lantern]",
			de = "[Stormstout Brewery Lantern]",
			fr = "[Stormstout Brewery Lantern]",
			it = "[Stormstout Brewery Lantern]",
			pt = "[Stormstout Brewery Lantern]",
			ru = "[Stormstout Brewery Lantern]",
			ko = "[Stormstout Brewery Lantern]",
			cn = "[Stormstout Brewery Lantern]",
			tw = "[Stormstout Brewery Lantern]",
		},
	},
	[667556] = {
		readable = "Grain",
		model = 577323,
		text = {
			en = "Grain",
			es = "[Grain]",
			mx = "[Grain]",
			de = "[Grain]",
			fr = "[Grain]",
			it = "[Grain]",
			pt = "[Grain]",
			ru = "[Grain]",
			ko = "[Grain]",
			cn = "[Grain]",
			tw = "[Grain]",
		},
	},
	[667558] = {
		readable = "Ingredients",
		model = 533060,
		text = {
			en = "Ingredients",
			es = "[Ingredients]",
			mx = "[Ingredients]",
			de = "[Ingredients]",
			fr = "[Ingredients]",
			it = "[Ingredients]",
			pt = "[Ingredients]",
			ru = "[Ingredients]",
			ko = "[Ingredients]",
			cn = "[Ingredients]",
			tw = "[Ingredients]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
