local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[572448] = {
		readable = "Ebon Banner",
		model = 194802,
		text = {
			en = "Ebon Banner",
			es = "Estandarte ébano",
			-- TODO: mx = "",
			de = "Schwarzbanner",
			fr = "Bannière d’ébène",
			it = "Stendardo d'Ebano",
			pt = "Estandarte de Ébano",
			ru = "Черное знамя",
			ko = "칠흑 깃발",
			-- TODO: cn = "",
			tw = "黯黑旌旗",
		},
	},
	[572453] = {
		readable = "Pylon Fragment",
		model = 1327768,
		text = {
			en = "Pylon Fragment",
			es = "Fragmento de pilón",
			-- TODO: mx = "",
			de = "Pylonfragment",
			fr = "Fragment de pylône",
			it = "Frammento di Pilone",
			-- TODO: pt = "",
			ru = "Фрагмент пилона",
			ko = "수정탑 파편",
			cn = "晶塔碎片",
			-- TODO: tw = "",
		},
	},
	[649209] = {
		readable = "Misplaced Ritual Candle",
		model = 5975162,
		text = {
			en = "Misplaced Ritual Candle",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
})
do ObjectDB[objectID] = objectData; end
