local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[544785] = {
		readable = "Empty Seed Sack",
		model = 6055097,
		text = {
			en = "Empty Seed Sack",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[548700] = {
		readable = "Well-Worn Ladle",
		model = 6326885,
		text = {
			en = "Well-Worn Ladle",
			es = "[Well-Worn Ladle]",
			mx = "[Well-Worn Ladle]",
			de = "[Well-Worn Ladle]",
			fr = "[Well-Worn Ladle]",
			it = "[Well-Worn Ladle]",
			pt = "[Well-Worn Ladle]",
			ru = "[Well-Worn Ladle]",
			ko = "[Well-Worn Ladle]",
			cn = "[Well-Worn Ladle]",
			tw = "[Well-Worn Ladle]",
		},
	},
	[548703] = {
		readable = "Pilfered Crafting Drill",
		model = 6252856,
		text = {
			en = "Pilfered Crafting Drill",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[549189] = {
		readable = "The Great Vault",
		model = 6036354,
		text = {
			en = "The Great Vault",
			es = "La gran cámara",
			mx = "La Gran bóveda",
			de = "Die Große Schatzkammer",
			fr = "La grande chambre forte",
			it = "La Gran Banca",
			pt = "O Grande Cofre",
			ru = "Великое хранилище",
			ko = "위대한 금고",
			cn = "宏伟宝库",
			tw = "寶庫",
		},
	},
	[550008] = {
		readable = "Splattered Scroll",
		model = 6326920,
		text = {
			en = "Splattered Scroll",
			-- TODO: es = "",
		},
	},
})
do ObjectDB[objectID] = objectData; end
