local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[618536] = {
		readable = "Scout's Pack",
		model = 6701013,
		text = {
			en = "Scout's Pack",
			es = "[Scout's Pack]",
			mx = "[Scout's Pack]",
			de = "[Scout's Pack]",
			fr = "[Scout's Pack]",
			it = "[Scout's Pack]",
			pt = "[Scout's Pack]",
			ru = "[Scout's Pack]",
			ko = "[Scout's Pack]",
			cn = "[Scout's Pack]",
			tw = "[Scout's Pack]",
		},
	},
	[618542] = {
		readable = "Void Armor",
		model = 6860745,
		text = {
			en = "Void Armor",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[618554] = {
		readable = "Ancient Tablet",
		model = 4235304,
		text = {
			en = "Ancient Tablet",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[618558] = {
		readable = "Abandoned Telescope",
		model = 6700990,
		text = {
			en = "Abandoned Telescope",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[618569] = {
		readable = "Tattered Page",
		model = 3152067,
		text = {
			en = "Tattered Page",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[618571] = {
		readable = "Shadowgraft Harness",
		model = 6860752,
		text = {
			en = "Shadowgraft Harness",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[618828] = {
		readable = "Stormarion Fragment",
		model = 1982821,
		text = {
			en = "Stormarion Fragment",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[619217] = {
		readable = "Overtaken Voidcaster",
		model = 511490,
		text = {
			en = "Overtaken Voidcaster",
			es = "Taumaturgo del Vacío superado",
			mx = "Invocavacío poseído",
			de = "Überwältigter Leerenwirker",
			fr = "Lanceur du Vide submergé",
			it = "Incantatore del Vuoto Sopraffatto",
			pt = "Lança-caos Sobrepujado",
			ru = "Поверженный маг Бездны",
			ko = "잠식당한 공허시전자",
			cn = "罹难的虚空施法者",
			tw = "受壓制的虛無法師",
		},
	},
	[619616] = {
		readable = "Thorncap",
		model = 5838120,
		text = {
			en = "Thorncap",
			-- TODO: es = "",
			mx = "Hongoespina",
			de = "Dornenkappe",
			fr = "Champépine",
			it = "Cappaspina",
			pt = "Coguespinho",
			ru = "Капитерн",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[619621] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "Punto de observación",
			mx = "Mirador",
		},
	},
})
do ObjectDB[objectID] = objectData; end
