local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[525948] = {
		readable = "Primal Essence Orb",
		model = 4508234,
		text = {
			en = "Primal Essence Orb",
			-- TODO: es = "",
			-- TODO: mx = "",
			de = "Urzeitliche Essenzkugel",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[525949] = {
		readable = "Entropic Shard",
		model = 4320282,
		text = {
			en = "Entropic Shard",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			fr = "Éclat entropique",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[525950] = {
		readable = "Everblazing Sunmote",
		model = 5597754,
		text = {
			en = "Everblazing Sunmote",
			es = "Mota de sol de fuego eterno",
			-- TODO: mx = "",
			de = "Immerbrennender Sonnenpartikel",
			fr = "Granule de soleil semperardent",
			it = "Granulo del Sole Ardente",
			-- TODO: pt = "",
			ru = "Вечнопылающая частица солнца",
			-- TODO: ko = "",
			-- TODO: cn = "",
			tw = "恆燃太陽微粒",
		},
	},
	[525951] = {
		readable = "Pure Void Crystal",
		model = 4563732,
		text = {
			en = "Pure Void Crystal",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[525953] = {
		readable = "Enchanted Amani Mask",
		model = 6163854,
		text = {
			en = "Enchanted Amani Mask",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[525954] = {
		readable = "Silvermoon Blacksmith's Hammer",
		model = 6033619,
		text = {
			en = "Silvermoon Blacksmith's Hammer",
			es = "Martillo de herrería de Lunargenta",
			mx = "Martillo de herrero de Lunargenta",
			de = "Silbermondschmiedehammer",
			fr = "Marteau de forge de Lune-d’Argent",
			it = "Martello da Fabbro di Lunargenta",
			pt = "[Silvermoon Blacksmith's Hammer]",
			ru = "Луносветский кузнечный молот",
			ko = "[Silvermoon Blacksmith's Hammer]",
			cn = "[Silvermoon Blacksmith's Hammer]",
			tw = "[Silvermoon Blacksmith's Hammer]",
		},
	},
	[525955] = {
		readable = "Sin'dorei Master's Forgemace",
		model = 6033619,
		text = {
			en = "Sin'dorei Master's Forgemace",
			es = "Mazo de forja de maestro sin'dorei",
			mx = "Maza de forja de maestro sin'dorei",
			de = "Schmiedestreitkolben des Sin'dorei-Meisters",
			fr = "Masse de forge de maîtrise sin’dorei",
			it = "Forgiamazza del Mastro Sin'dorei",
			pt = "[Sin'dorei Master's Forgemace]",
			ru = "Молот син'дорайского мастера",
			ko = "[Sin'dorei Master's Forgemace]",
			cn = "[Sin'dorei Master's Forgemace]",
			tw = "[Sin'dorei Master's Forgemace]",
		},
	},
	[525956] = {
		readable = "Rutaani Floratender's Sword",
		model = 6055061,
		text = {
			en = "Rutaani Floratender's Sword",
			es = "[Rutaani Floratender's Sword]",
			mx = "[Rutaani Floratender's Sword]",
			de = "[Rutaani Floratender's Sword]",
			fr = "[Rutaani Floratender's Sword]",
			it = "[Rutaani Floratender's Sword]",
			pt = "[Rutaani Floratender's Sword]",
			ru = "[Rutaani Floratender's Sword]",
			ko = "[Rutaani Floratender's Sword]",
			cn = "[Rutaani Floratender's Sword]",
			tw = "[Rutaani Floratender's Sword]",
		},
	},
	[525958] = {
		readable = "Metalworking Cheat Sheet",
		model = 5679909,
		text = {
			en = "Metalworking Cheat Sheet",
			es = "Guía rápida para trabajar con metales",
			-- TODO: mx = "",
			de = "Spickzettel zu Metallarbeiten",
			fr = "Le travail du métal pour les nuls",
			it = "Promemoria sulla Lavorazione dei Metalli",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[525959] = {
		readable = "Carefully Racked Spear",
		model = 6212433,
		text = {
			en = "Carefully Racked Spear",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[525960] = {
		readable = "Silvermoon Smithing Kit",
		model = 6125157,
		text = {
			en = "Silvermoon Smithing Kit",
			es = "Equipo de herrería de Lunargenta",
			-- TODO: mx = "",
			de = "Silbermondschmiedeset",
			fr = "Kit de forge de Lune-d’Argent",
			it = "Kit da Forgiatura di Lunargenta",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[525961] = {
		readable = "Deconstructed Forge Techniques",
		model = 203429,
		text = {
			en = "Deconstructed Forge Techniques",
			es = "Técnicas de forja deconstruidas",
			-- TODO: mx = "",
			de = "Dekonstruierte Schmiedetechniken",
			fr = "Manifeste pour une forge déconstruite",
		},
	},
})
do ObjectDB[objectID] = objectData; end
