local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[103815] = {
		readable = "Ambermill Strongbox",
		model = 196979,
		text = {
			en = "Ambermill Strongbox",
			es = "Caja fuerte del Molino Ámbar",
			-- TODO: mx = "",
			de = "Ambermill-Geldkassette",
			fr = "Coffre-fort d'Ambermill",
			it = "Ambermill Strongbox",
			pt = "Cofre de Lenhâmbar",
			ru = "Сейф Янтарной мельницы",
			ko = "앰버밀 금고",
			-- TODO: cn = "",
			tw = "安伯米爾保險箱",
		},
	},
	[105176] = {
		readable = "Venture Co. Strongbox",
		model = 196976,
		text = {
			en = "Venture Co. Strongbox",
			es = "Caja fuerte de Ventura y Cía.",
			mx = "Caja fuerte de Ventura y Cía.",
			de = "Geldkassette der Venture Co.",
			fr = "Coffre de la KapitalRisk",
			it = "Venture Co. Strongbox",
			pt = "Cofre da Empreendimentos S.A.",
			ru = "Сейф торговой компании",
			ko = "투자개발회사 금고",
			cn = "风险投资公司保险箱",
			tw = "風險投資公司保險箱",
		},
	},
	[105570] = {
		readable = "Alliance Strongbox",
		model = 219372,
		text = {
			en = "Alliance Strongbox",
			es = "Caja fuerte de la Alianza",
			mx = "Caja fuerte de la Alianza",
			de = "Geldkassette der Allianz",
			fr = "Coffre de l'Alliance",
			it = "Alliance Strongbox",
			pt = "Caixa-forte da Aliança",
			ru = "Сейф Альянса",
			ko = "얼라이언스 금고",
			cn = "联盟保险箱",
			tw = "聯盟保險箱",
		},
	},
})
do ObjectDB[objectID] = objectData; end
