local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[525976] = {
		readable = "Peculiar Lotus",
		model = 577018,
		text = {
			en = "Peculiar Lotus",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[525977] = {
		readable = "Planting Shovel",
		model = 929413,
		text = {
			en = "Planting Shovel",
			-- TODO: es = "",
			-- TODO: mx = "",
			de = "Pflanzschaufel",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[527670] = {
		readable = "Lightwood Pile",
		model = 6690013,
		text = {
			en = "Lightwood Pile",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[531204] = {
		readable = "Completed Javelin",
		model = 4631422,
		text = {
			en = "Completed Javelin",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[531575] = {
		readable = "Glowshroom",
		model = 973608,
		text = {
			en = "Glowshroom",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[539042] = {
		readable = "Ruz'avalt's Prized Tackle",
		model = 6075567,
		text = {
			en = "Ruz'avalt's Prized Tackle",
			es = "[Ruz'avalt's Prized Tackle]",
			mx = "Derribo preciado de Ruz'avalt",
			de = "Ruz'avalts wertvoller Besitz",
			fr = "Précieux appâts de Ruz’avalt",
			it = "Equipaggiamento da Pesca Pregevole di Ruz'avalt",
			pt = "Equipamento de Pesca Precioso de Ruz'avalt",
			ru = "[Ruz'avalt's Prized Tackle]",
			ko = "[Ruz'avalt's Prized Tackle]",
			cn = "[Ruz'avalt's Prized Tackle]",
			tw = "[Ruz'avalt's Prized Tackle]",
		},
	},
	[539046] = {
		readable = "Honored Warrior's Cache",
		model = 6195750,
		text = {
			en = "Honored Warrior's Cache",
			es = "[Honored Warrior's Cache]",
			mx = "[Honored Warrior's Cache]",
			de = "[Honored Warrior's Cache]",
			fr = "[Honored Warrior's Cache]",
			it = "[Honored Warrior's Cache]",
			pt = "[Honored Warrior's Cache]",
			ru = "[Honored Warrior's Cache]",
			ko = "[Honored Warrior's Cache]",
			cn = "[Honored Warrior's Cache]",
			tw = "[Honored Warrior's Cache]",
		},
	},
	[539049] = {
		readable = "Bait and Tackle",
		model = 3857150,
		text = {
			en = "Bait and Tackle",
			es = "Cebo y aparejos",
			mx = "Artículos de pesca",
			de = "Köder und Angelzubehör",
			fr = "Appât appâteur",
			it = "Esca e Attrezzatura",
			-- TODO: pt = "",
			ru = "Наживка и снасти",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[539050] = {
		readable = "Burrow Bounty",
		model = 1859057,
		text = {
			en = "Burrow Bounty",
			-- TODO: es = "",
			mx = "Recompensa de madriguera",
			de = "Vergrabene Beute",
			fr = "Trésor enfoui",
			-- TODO: it = "",
			pt = "Recompensa de Escavação",
			ru = "Зарытые запасы",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[539052] = {
		readable = "Secret Formula",
		model = 1310400,
		text = {
			en = "Secret Formula",
			-- TODO: es = "",
			mx = "Fórmula secreta",
			de = "Geheime Formel",
			fr = "Formule secrète",
			it = "Formula Segreta",
			pt = "Fórmula Secreta",
			ru = "Секретный рецепт",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[539053] = {
		readable = "Abandoned Nest",
		model = 4532354,
		text = {
			en = "Abandoned Nest",
			-- TODO: es = "",
			mx = "Nido abandonado",
			de = "Verlassenes Nest",
			fr = "Nid abandonné",
			it = "Nido Abbandonato",
			pt = "Ninho Abandonado",
			ru = "Заброшенное гнездо",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[542839] = {
		readable = "K'areshi Keepsake",
		model = 6320659,
		text = {
			en = "K'areshi Keepsake",
			es = "[K'areshi Keepsake]",
			mx = "[K'areshi Keepsake]",
			de = "[K'areshi Keepsake]",
			fr = "[K'areshi Keepsake]",
			it = "[K'areshi Keepsake]",
			pt = "[K'areshi Keepsake]",
			ru = "[K'areshi Keepsake]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
