local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[573743] = {
		readable = "Crown of the High King",
		model = 7429000,
		text = {
			en = "Crown of the High King",
			es = "[Crown of the High King]",
			mx = "[Crown of the High King]",
			de = "[Crown of the High King]",
			fr = "[Crown of the High King]",
			it = "[Crown of the High King]",
			pt = "[Crown of the High King]",
			ru = "[Crown of the High King]",
			ko = "[Crown of the High King]",
			cn = "[Crown of the High King]",
			tw = "[Crown of the High King]",
		},
	},
	[617884] = {
		readable = "Lucifern",
		model = 219442,
		text = {
			en = "Lucifern",
			es = "[Lucifern]",
			mx = "[Lucifern]",
			de = "[Lucifern]",
			fr = "[Lucifern]",
			it = "[Lucifern]",
			pt = "[Lucifern]",
			ru = "[Lucifern]",
			ko = "[Lucifern]",
			cn = "[Lucifern]",
			tw = "[Lucifern]",
		},
	},
	[618284] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "[Sturdy Chest]",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618296] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "[Sturdy Chest]",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[623258] = {
		readable = "Pilfered Trunk",
		model = 5128194,
		text = {
			en = "Pilfered Trunk",
			es = "[Pilfered Trunk]",
			mx = "[Pilfered Trunk]",
			de = "[Pilfered Trunk]",
			fr = "[Pilfered Trunk]",
			it = "[Pilfered Trunk]",
			pt = "[Pilfered Trunk]",
			ru = "Опустошенный ларь",
			ko = "[Pilfered Trunk]",
			cn = "[Pilfered Trunk]",
			tw = "[Pilfered Trunk]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
