local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[527903] = {
		readable = "Spectral Battle Chest",
		model = 6210898,
		text = {
			en = "Spectral Battle Chest",
			es = "Cofre de batalla espectral",
			mx = "Cofre de batalla espectral",
			de = "Geisterschlachttruhe",
			fr = "Coffre de combat spectral",
			it = "Cassa da Battaglia Spettrale",
			pt = "Baú de Batalha Espectral",
			ru = "Призрачный боевой сундук",
			ko = "유령 전투 보관함",
			cn = "幽灵战斗宝箱",
			tw = "鬼靈戰鬥寶箱",
		},
	},
	[536214] = {
		readable = "Blossom-Bound Nest",
		model = 5199469,
		text = {
			en = "Blossom-Bound Nest",
			es = "Nido vinculado a la floración",
			mx = "Nido de atadura floral",
			de = "Blütengebundenes Nest",
			fr = "Nid de florelige",
			it = "Nido Fiorito",
			pt = "Ninho Preso na Flor",
			ru = "Цветочное гнездо",
			ko = "만개결속 둥지",
			cn = "覆花巢穴",
			tw = "花縛巢穴",
		},
	},
	[568519] = {
		readable = "Chest of Stolen Valuables",
		model = 6017293,
		text = {
			en = "Chest of Stolen Valuables",
			es = "Cofre de bienes valiosos robados",
			mx = "[Chest of Stolen Valuables]",
			de = "Truhe mit gestohlenen Wertgegenständen",
			fr = "Coffre d’objets précieux volés",
			it = "[Chest of Stolen Valuables]",
			pt = "[Chest of Stolen Valuables]",
			ru = "Сундук краденых сокровищ",
			ko = "[Chest of Stolen Valuables]",
			cn = "[Chest of Stolen Valuables]",
			tw = "失竊貴重物品箱",
		},
	},
	[584750] = {
		readable = "Lost Page from Nostro's Compendium",
		model = 4324473,
		text = {
			en = "Lost Page from Nostro's Compendium",
			es = "[Lost Page from Nostro's Compendium]",
			mx = "[Lost Page from Nostro's Compendium]",
			de = "[Lost Page from Nostro's Compendium]",
			fr = "[Lost Page from Nostro's Compendium]",
			it = "[Lost Page from Nostro's Compendium]",
			pt = "[Lost Page from Nostro's Compendium]",
			ru = "[Lost Page from Nostro's Compendium]",
			ko = "[Lost Page from Nostro's Compendium]",
			cn = "[Lost Page from Nostro's Compendium]",
			tw = "[Lost Page from Nostro's Compendium]",
		},
	},
	[618287] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "[Sturdy Chest]",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618518] = {
		readable = "Thalassian Lumber",
		model = 6922313,
		text = {
			en = "Thalassian Lumber",
			es = "Madera thalassiana",
			mx = "Madera thalassiana",
			de = "Thalassisches Holz",
			fr = "Bois thalassien",
			it = "Legname Thalassiano",
			pt = "Lenha Talassiana",
			ru = "Талассийская древесина",
			ko = "탈라시안 목재",
			cn = "萨拉斯木料",
			tw = "薩拉斯木材",
		},
	},
	[618519] = {
		readable = "Thalassian Lumber",
		model = 6922313,
		text = {
			en = "Thalassian Lumber",
			es = "Madera thalassiana",
			mx = "Madera thalassiana",
			de = "Thalassisches Holz",
			fr = "Bois thalassien",
			it = "Legname Thalassiano",
			pt = "Lenha Talassiana",
			ru = "Талассийская древесина",
			ko = "탈라시안 목재",
			cn = "萨拉斯木料",
			tw = "薩拉斯木材",
		},
	},
	[618520] = {
		readable = "Thalassian Lumber",
		model = 6922313,
		text = {
			en = "Thalassian Lumber",
			es = "Madera thalassiana",
			mx = "Madera thalassiana",
			de = "Thalassisches Holz",
			fr = "Bois thalassien",
			it = "Legname Thalassiano",
			pt = "Lenha Talassiana",
			ru = "Талассийская древесина",
			ko = "탈라시안 목재",
			cn = "萨拉斯木料",
			tw = "薩拉斯木材",
		},
	},
})
do ObjectDB[objectID] = objectData; end
