local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[613269] = {
		readable = "Battered Safebox Key",
		model = 970204,
		text = {
			en = "Battered Safebox Key",
			es = "Llave de caja fuerte maltrecha",
			-- TODO: mx = "",
			de = "Lädierter Truhenschlüssel",
			fr = "Clé de coffre endommagée",
			it = "Chiave della Cassetta di Sicurezza Rovinata",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			cn = "破烂的保险箱钥匙",
			tw = "殘破的保險箱鑰匙",
		},
	},
	[613271] = {
		readable = "Worn Safebox Key",
		model = 970204,
		text = {
			en = "Worn Safebox Key",
			es = "Llave de caja fuerte desgastada",
			-- TODO: mx = "",
			de = "Abgenutzter Truhenschlüssel",
			fr = "Clé de coffre usée",
			it = "Chiave della Cassetta di Sicurezza Consumata",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			cn = "磨损的保险箱钥匙",
			tw = "磨損的保險箱鑰匙",
		},
	},
	[613272] = {
		readable = "Tarnished Safebox Key",
		model = 970204,
		text = {
			en = "Tarnished Safebox Key",
			es = "Llave de caja fuerte deslustrada",
			-- TODO: mx = "",
			de = "Befleckter Truhenschlüssel",
			fr = "Clé de coffre ternie",
			it = "Chiave della Cassetta di Sicurezza Ossidata",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			cn = "褪色的保险箱钥匙",
			tw = "黯淡的保險箱鑰匙",
		},
	},
	[613317] = {
		readable = "Half-Digested Viscera",
		model = 337611,
		text = {
			en = "Half-Digested Viscera",
			es = "[Half-Digested Viscera]",
			mx = "[Half-Digested Viscera]",
			de = "[Half-Digested Viscera]",
			fr = "[Half-Digested Viscera]",
			it = "[Half-Digested Viscera]",
			pt = "[Half-Digested Viscera]",
			ru = "[Half-Digested Viscera]",
			ko = "[Half-Digested Viscera]",
			cn = "[Half-Digested Viscera]",
			tw = "[Half-Digested Viscera]",
		},
	},
	[613327] = {
		readable = "Faindel's Quiver",
		model = 6700995,
		text = {
			en = "Faindel's Quiver",
			es = "[Faindel's Quiver]",
			mx = "[Faindel's Quiver]",
			de = "[Faindel's Quiver]",
			fr = "[Faindel's Quiver]",
			it = "[Faindel's Quiver]",
			pt = "[Faindel's Quiver]",
			ru = "[Faindel's Quiver]",
			ko = "[Faindel's Quiver]",
			cn = "[Faindel's Quiver]",
			tw = "[Faindel's Quiver]",
		},
	},
	[613358] = {
		readable = "Exaliburn",
		model = 6980930,
		text = {
			en = "Exaliburn",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[613392] = {
		readable = "Impenetrably Sealed Gourd",
		model = 6326901,
		text = {
			en = "Impenetrably Sealed Gourd",
			-- TODO: es = "",
			-- TODO: mx = "",
			de = "Undurchdringlich versiegelter Kürbis",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[613701] = {
		readable = "Honored Warrior's Urn",
		model = 6870560,
		text = {
			en = "Honored Warrior's Urn",
			es = "[Honored Warrior's Urn]",
			mx = "Urna de guerrero honrado",
			de = "[Honored Warrior's Urn]",
			fr = "Urne de combat glorieux",
			it = "[Honored Warrior's Urn]",
			pt = "[Honored Warrior's Urn]",
			ru = "[Honored Warrior's Urn]",
			ko = "[Honored Warrior's Urn]",
			cn = "[Honored Warrior's Urn]",
			tw = "[Honored Warrior's Urn]",
		},
	},
	[613727] = {
		readable = "Honored Warrior's Cache",
		model = 6195750,
		text = {
			en = "Honored Warrior's Cache",
			es = "[Honored Warrior's Cache]",
			mx = "Alijo de guerrero honrado",
			de = "Schatz des wohlwollenden Kriegers",
			fr = "Cache de combat glorieux",
			it = "Cassa del Guerriero Onorato",
			pt = "Baú do Guerreiro Honrado",
			ru = "Сундук почетного воина",
			ko = "[Honored Warrior's Cache]",
			cn = "[Honored Warrior's Cache]",
			tw = "[Honored Warrior's Cache]",
		},
	},
	[613729] = {
		readable = "Sunstrider Vessel",
		model = 4324806,
		text = {
			en = "Sunstrider Vessel",
			es = "Recipiente de Caminante del Sol",
			mx = "Receptáculo de Caminante del Sol",
			de = "Gefäß der Sonnenwanderer",
			fr = "Réceptacle de Haut-Soleil",
			it = "Ricettacolo dei Solealto",
			pt = "Receptáculo Andassol",
			ru = "Сосуд Солнечного Скитальца",
			-- TODO: ko = "",
			cn = "逐日者容器",
			-- TODO: tw = "",
		},
	},
	[613757] = {
		readable = "Honored Warrior's Urn",
		model = 6870560,
		text = {
			en = "Honored Warrior's Urn",
		},
	},
})
do ObjectDB[objectID] = objectData; end
