local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[525897] = {
		readable = "Lightbloom Afflicted Hide",
		model = 4288076,
		text = {
			en = "Lightbloom Afflicted Hide",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[587195] = {
		readable = "Mysterious Domanaar Vessel",
		model = 6391990,
		text = {
			en = "Mysterious Domanaar Vessel",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[587238] = {
		readable = "Stashed Singularity Supplies",
		model = 6701013,
		text = {
			en = "Stashed Singularity Supplies",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[620533] = {
		readable = "Lost Page",
		model = 6103388,
		text = {
			en = "Lost Page",
			es = "Página perdida",
			mx = "Página perdida",
			de = "Verlorene Seite",
			fr = "Page perdue",
			it = "Pagina Perduta",
			pt = "Página Perdida",
			ru = "Потерянная страница",
			ko = "잃어버린 책장",
			cn = "失落纸页",
			tw = "遺失的書頁",
		},
	},
	[620537] = {
		readable = "Lost Page",
		model = 6103388,
		text = {
			en = "Lost Page",
			es = "Página perdida",
			mx = "Página perdida",
			de = "Verlorene Seite",
			fr = "Page perdue",
			it = "Pagina Perduta",
			pt = "Página Perdida",
			ru = "Потерянная страница",
			-- TODO: ko = "",
			cn = "失落纸页",
			tw = "遺失的書頁",
		},
	},
	[620538] = {
		readable = "Lost Page",
		model = 6103388,
		text = {
			en = "Lost Page",
			es = "Página perdida",
			mx = "Página perdida",
			de = "Verlorene Seite",
			fr = "Page perdue",
			it = "Pagina Perduta",
			pt = "Página Perdida",
			ru = "Потерянная страница",
			-- TODO: ko = "",
			cn = "失落纸页",
			tw = "遺失的書頁",
		},
	},
	[620688] = {
		readable = "Incomplete Book of Sonnets",
		model = 6081188,
		text = {
			en = "Incomplete Book of Sonnets",
			es = "Libro de sonetos incompleto",
			mx = "Libro de sonetos incompleto",
			de = "Unvollständiges Buch der Sonette",
			fr = "Livret de sonnets incomplet",
			it = "Libro di Sonetti Incompleto",
			pt = "Livreto dos Sonetos Incompleto",
			ru = "Неполная книга сонетов",
			-- TODO: ko = "",
			cn = "未完成的十四行诗集",
			tw = "未完成的長詩集",
		},
	},
})
do ObjectDB[objectID] = objectData; end
