local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[568276] = {
		readable = "Unoccupied Mana Loom",
		model = 7197584,
		text = {
			en = "Unoccupied Mana Loom",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[584515] = {
		readable = "Bountiful Heavy Trunk",
		model = 5128194,
		text = {
			en = "Bountiful Heavy Trunk",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[584518] = {
		readable = "Bountiful Heavy Trunk",
		model = 5128194,
		text = {
			en = "Bountiful Heavy Trunk",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
})
do ObjectDB[objectID] = objectData; end
