local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[616804] = {
		readable = "Ancient Amani Tablet",
		model = 6212409,
		text = {
			en = "Ancient Amani Tablet",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[617077] = {
		readable = "Vilebranch Scroll",
		model = 5975119,
		text = {
			en = "Vilebranch Scroll",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[639875] = {
		readable = "Feather of Jan'alai",
		model = 7550572,
		text = {
			en = "Feather of Jan'alai",
			es = "[Feather of Jan'alai]",
			mx = "[Feather of Jan'alai]",
			de = "[Feather of Jan'alai]",
			fr = "[Feather of Jan'alai]",
			it = "[Feather of Jan'alai]",
			pt = "[Feather of Jan'alai]",
			ru = "[Feather of Jan'alai]",
			ko = "[Feather of Jan'alai]",
			cn = "[Feather of Jan'alai]",
			tw = "[Feather of Jan'alai]",
		},
	},
	[654422] = {
		readable = "Energized Crystal Conductor",
		model = 5916222,
		text = {
			en = "Energized Crystal Conductor",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[654497] = {
		readable = "Energized Crystal Conductor",
		model = 5916222,
		text = {
			en = "Energized Crystal Conductor",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[655270] = {
		readable = "Domanaar Storage Vessel",
		model = 6391990,
		text = {
			en = "Domanaar Storage Vessel",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[655271] = {
		readable = "Hal'hadar Pocket-Storage",
		model = 6320659,
		text = {
			en = "Hal'hadar Pocket-Storage",
			es = "[Hal'hadar Pocket-Storage]",
			mx = "[Hal'hadar Pocket-Storage]",
			de = "[Hal'hadar Pocket-Storage]",
			fr = "[Hal'hadar Pocket-Storage]",
			it = "[Hal'hadar Pocket-Storage]",
			pt = "[Hal'hadar Pocket-Storage]",
			ru = "[Hal'hadar Pocket-Storage]",
			ko = "[Hal'hadar Pocket-Storage]",
			cn = "[Hal'hadar Pocket-Storage]",
			tw = "[Hal'hadar Pocket-Storage]",
		},
	},
	[655738] = {
		readable = "Nullframe Holoprint",
		model = 6321897,
		text = {
			en = "Nullframe Holoprint",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[656141] = {
		readable = "Soul Lattice Holoprint",
		model = 6321897,
		text = {
			en = "Soul Lattice Holoprint",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[656142] = {
		readable = "Glittering Crypt Holoprint",
		model = 6321897,
		text = {
			en = "Glittering Crypt Holoprint",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
		},
	},
})
do ObjectDB[objectID] = objectData; end
