local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[566083] = {
		readable = "Stormarion Supplies",
		model = 6391989,
		text = {
			en = "Stormarion Supplies",
			es = "Suministros de Tormentarion",
			mx = "[Stormarion Supplies]",
			de = "Sturmarionvorräte",
			fr = "Fournitures de Fulgarion",
			it = "Rifornimenti di Buferion",
			pt = "Suprimentos de Tempestrião",
			ru = "Штормарионские припасы",
			ko = "스토마리온 보급품",
			cn = "斯托玛兰补给品",
			tw = "風瑪利昂補給品",
		},
	},
	[616878] = {
		readable = "Malignant Node",
		model = 6210883,
		text = {
			en = "Malignant Node",
			es = "Nodo maligno",
			mx = "Nodo maligno",
			de = "Heimtückischer Knoten",
			fr = "Nœud malveillant",
			it = "Nodo Maligno",
			pt = "Nodo Maligno",
			ru = "Тлетворная находка",
			ko = "악성 지점",
			cn = "怨毒节点",
			tw = "惡意節點",
		},
	},
	[616890] = {
		readable = "Malignant Node",
		model = 6210883,
		text = {
			en = "Malignant Node",
			es = "Nodo maligno",
			mx = "Nodo maligno",
			de = "Heimtückischer Knoten",
			fr = "Nœud malveillant",
			it = "Nodo Maligno",
			pt = "Nodo Maligno",
			ru = "Тлетворная находка",
			ko = "악성 지점",
			cn = "怨毒节点",
			tw = "惡意節點",
		},
	},
	[616891] = {
		readable = "Malignant Node",
		model = 6210883,
		text = {
			en = "Malignant Node",
			es = "Nodo maligno",
			mx = "Nodo maligno",
			de = "Heimtückischer Knoten",
			fr = "Nœud malveillant",
			it = "Nodo Maligno",
			pt = "Nodo Maligno",
			ru = "Тлетворная находка",
			ko = "악성 지점",
			cn = "怨毒节点",
			tw = "惡意節點",
		},
	},
	[616892] = {
		readable = "Malignant Node",
		model = 6210883,
		text = {
			en = "Malignant Node",
			es = "Nodo maligno",
			mx = "Nodo maligno",
			de = "Heimtückischer Knoten",
			fr = "Nœud malveillant",
			it = "Nodo Maligno",
			pt = "Nodo Maligno",
			ru = "Тлетворная находка",
			ko = "악성 지점",
			cn = "怨毒节点",
			tw = "惡意節點",
		},
	},
})
do ObjectDB[objectID] = objectData; end
