local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[525932] = {
		readable = "Half-Baked Techniques",
		model = 4337371,
		text = {
			en = "Half-Baked Techniques",
			es = "Técnicas a medio terminar",
			mx = "Técnicas a medio elaborar",
			de = "Halbherzige Techniken",
			fr = "Techniques malléables",
			it = "Tecniche Approssimative",
			pt = "Técnicas Malconcebidas",
			ru = "Недоработанные техники",
			ko = "[Half-Baked Techniques]",
			cn = "烧了一半的技巧书",
			tw = "[Half-Baked Techniques]",
		},
	},
	[525952] = {
		readable = "Enchanted Sunfire Silk",
		model = 6718145,
		text = {
			en = "Enchanted Sunfire Silk",
			es = "Seda de fuego solar encantada",
			mx = "Seda de fuego solar encantada",
			de = "Verzauberte Sonnenfeuerseide",
			fr = "Soie du feu solaire enchantée",
			it = "Seta del Fuoco Solare Incantata",
			pt = "Seda de Fogo Solar Encantada",
			ru = "Зачарованный шелк солнечного огня",
			ko = "마력 깃든 태양불꽃 비단",
			cn = "附魔的阳炎丝绸",
			tw = "附魔日炎絲綢",
		},
	},
	[568507] = {
		readable = "Relocation Crate",
		model = 6005278,
		text = {
			en = "Relocation Crate",
			es = "[Relocation Crate]",
			mx = "[Relocation Crate]",
			de = "[Relocation Crate]",
			fr = "[Relocation Crate]",
			it = "[Relocation Crate]",
			pt = "[Relocation Crate]",
			ru = "[Relocation Crate]",
			ko = "[Relocation Crate]",
			cn = "[Relocation Crate]",
			tw = "[Relocation Crate]",
		},
	},
	[579180] = {
		readable = "Ways of the Roots--Part 1: Serving",
		model = 6326920,
		text = {
			en = "Ways of the Roots--Part 1: Serving",
			es = "[Ways of the Roots--Part 1: Serving]",
			mx = "[Ways of the Roots--Part 1: Serving]",
			de = "[Ways of the Roots--Part 1: Serving]",
			fr = "[Ways of the Roots--Part 1: Serving]",
			it = "[Ways of the Roots--Part 1: Serving]",
			pt = "Os Rumos das Raízes, Parte 1: Servir",
			ru = "[Ways of the Roots--Part 1: Serving]",
			ko = "[Ways of the Roots--Part 1: Serving]",
			cn = "[Ways of the Roots--Part 1: Serving]",
			tw = "樹根之道--第1部：奉獻",
		},
	},
	[579182] = {
		readable = "Ways of the Roots--Part 2: Growing",
		model = 6326920,
		text = {
			en = "Ways of the Roots--Part 2: Growing",
			es = "[Ways of the Roots--Part 2: Growing]",
			mx = "[Ways of the Roots--Part 2: Growing]",
			de = "[Ways of the Roots--Part 2: Growing]",
			fr = "[Ways of the Roots--Part 2: Growing]",
			it = "[Ways of the Roots--Part 2: Growing]",
			pt = "Os Rumos das Raízes, Parte 2: Crescer",
			ru = "[Ways of the Roots--Part 2: Growing]",
			ko = "[Ways of the Roots--Part 2: Growing]",
			cn = "[Ways of the Roots--Part 2: Growing]",
			tw = "樹根之道--第2部：成長",
		},
	},
	[579183] = {
		readable = "Ways of the Roots--Part 3: Pruning",
		model = 6326920,
		text = {
			en = "Ways of the Roots--Part 3: Pruning",
			es = "[Ways of the Roots--Part 3: Pruning]",
			mx = "[Ways of the Roots--Part 3: Pruning]",
			de = "[Ways of the Roots--Part 3: Pruning]",
			fr = "[Ways of the Roots--Part 3: Pruning]",
			it = "[Ways of the Roots--Part 3: Pruning]",
			pt = "Os Rumos das Raízes, Parte 3: Podar",
			ru = "[Ways of the Roots--Part 3: Pruning]",
			ko = "[Ways of the Roots--Part 3: Pruning]",
			cn = "[Ways of the Roots--Part 3: Pruning]",
			tw = "樹根之道--第3部：修剪",
		},
	},
	[584503] = {
		readable = "Grand Sanctified Spoils",
		model = 6435027,
		text = {
			en = "Grand Sanctified Spoils",
			es = "Botín santificado grandioso",
			mx = "Gran botín santificado",
			de = "Große geheiligte Schätze",
			fr = "Butin sanctifié majestueux",
			it = "Gran Spoglie Benedette",
			pt = "Grandes Espólios Santificados",
			ru = "Великие освященные трофеи",
			ko = "위대한 축성된 전리품",
			cn = "宏伟圣化战利品",
			tw = "大型沐聖戰利品",
		},
	},
})
do ObjectDB[objectID] = objectData; end
