local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[525906] = {
		readable = "Spare Expedition Torch",
		model = 5347378,
		text = {
			en = "Spare Expedition Torch",
			es = "Antorcha de expedición de repuesto",
			mx = "Antorcha de expedición de repuesto",
			de = "Ersatzexpeditionsfackel",
			fr = "Torche d’expédition de rechange",
			it = "Torcia da Spedizione di Scorta",
			pt = "Tocha de Expedição Reserva",
			ru = "Запасной факел экспедиции",
			ko = "예비용 원정대 횃불",
			cn = "备用的勘探火炬",
			tw = "備用遠征隊火炬",
		},
	},
	[525907] = {
		readable = "Star Metal Deposit",
		model = 1692857,
		text = {
			en = "Star Metal Deposit",
			es = "Depósito de metal estelar",
			mx = "Depósito de metal estelar",
			de = "Sternenmetallvorkommen",
			fr = "Gisement de stellum",
			it = "Deposito di Metallo Stellare",
			pt = "Depósito de Metal Estelar",
			ru = "Залежи звездного металла",
			ko = "운철 매장지",
			cn = "星辰金属矿物",
			tw = "星辰金屬礦床",
		},
	},
	[525908] = {
		readable = "Amani Expert's Chisel",
		model = 6125159,
		text = {
			en = "Amani Expert's Chisel",
			es = "Cincel de experto Amani",
			mx = "Cincel de experto amani",
			de = "Meißel des Amaniexperten",
			fr = "Burin d’expertise amani",
			it = "Scalpello dell'Esperto Amani",
			pt = "Cinzel do Especialista Amani",
			ru = "Резец аманийского эксперта",
			ko = "아마니 전문가의 끌",
			cn = "阿曼尼专家的凿子",
			tw = "阿曼尼專家的鑿子",
		},
	},
	[525909] = {
		readable = "Glimmering Void Pearl",
		model = 5309795,
		text = {
			en = "Glimmering Void Pearl",
			es = "Perla del Vacío de luz trémula",
			mx = "Perla del Vacío resplandeciente",
			de = "Schimmernde Leerenperle",
			fr = "Perle du Vide scintillante",
			it = "Perla del Vuoto Luccicante",
			pt = "Pérola do Caos Cintilante",
			ru = "Мерцающая жемчужина Бездны",
			ko = "일렁거리는 공허 진주",
			cn = "闪光的虚空珍珠",
			tw = "微光虛無珍珠",
		},
	},
	[525910] = {
		readable = "Solid Ore Punchers",
		model = 7377919,
		text = {
			en = "Solid Ore Punchers",
			es = "Perforadores de mineral macizo",
			mx = "Perforadoras de mineral sólido",
			de = "Massive Erzstanzer",
			fr = "Poinçons à minerai massif",
			it = "Punzonatrici per Minerale Solido",
			pt = "Perfuradores de Minérios Sólidos",
			ru = "Цельнолитые перчатки рудобоя",
			ko = "온전한 광석 천공기",
			cn = "牢固矿石击穿器",
			tw = "堅固的礦石打洞機",
		},
	},
	[525911] = {
		readable = "Lost Voidstorm Satchel",
		model = 6701013,
		text = {
			en = "Lost Voidstorm Satchel",
			es = "Bolsa de la Tormenta del Vacío perdida",
			mx = "Bolsón de la Tormenta del Vacío perdido",
			de = "Verlorene Leerensturmsichel",
			fr = "Sacoche perdue de la tempête du Vide",
			it = "Borsa della Tempesta del Vuoto Perduta",
			pt = "Algibeira da Tempestade do Caos Perdida",
			ru = "Потерянная сумка из Бури Бездны",
			ko = "잃어버린 공허폭풍 주머니",
			cn = "失落的虚影风暴小包",
			tw = "遺失的虛無風暴背袋",
		},
	},
	[525912] = {
		readable = "Spelunker's Lucky Charm",
		model = 6212423,
		text = {
			en = "Spelunker's Lucky Charm",
			es = "Talismán de la suerte de espeleólogo",
			mx = "Amuleto de la suerte de espeleólogo",
			de = "Glücksbringer des Höhlenforschers",
			fr = "Porte-bonheur de spéléologie",
			it = "Amuleto Fortunato dello Speleologo",
			pt = "Patuá da Sorte do Espeleologista",
			ru = "Спелеологический талисман на удачу",
			ko = "동굴탐험가의 행운부",
			cn = "探洞者的好运符",
			tw = "洞穴探勘者的幸運符",
		},
	},
	[525913] = {
		readable = "Miner's Guide to Voidstorm",
		model = 6025929,
		text = {
			en = "Miner's Guide to Voidstorm",
			es = "Guía de minería de la Tormenta del Vacío",
			mx = "Guía de la Tormenta del Vacío para mineros",
			de = "Bergmannsleitfaden für den Leerensturm",
			fr = "Guide de survie : comment exploiter la tempête du Vide",
			it = "Guida del Minatore alla Tempesta del Vuoto",
			pt = "Guia Rumo à Tempestade do Caos do Minerador",
			ru = "Руководство шахтера по Буре Бездны",
			ko = "광부의 공허폭풍 안내서",
			cn = "矿工的虚影风暴指南",
			tw = "礦工的虛無風暴指南",
		},
	},
	[525914] = {
		readable = "Artisan's Considered Order",
		model = 6025933,
		text = {
			en = "Artisan's Considered Order",
			es = "Pedido pendiente de artesano",
			mx = "Orden considerada de artesano",
			de = "Bedachter Auftrag des Kunsthandwerkers",
			fr = "Commande précieuse d’artisanat",
			it = "Ordine Ragionato dell'Artigiano",
			pt = "Pedido Analisado do Artífice",
			ru = "Пересмотренное пособие ремесленника",
			ko = "장인이 고려한 주문서",
			cn = "[Artisan's Considered Order]",
			tw = "工匠的待考慮訂單",
		},
	},
	[525915] = {
		readable = "Haranir Leatherworking Knife",
		model = 6693152,
		text = {
			en = "Haranir Leatherworking Knife",
			es = "Cuchillo de peletería haranir",
			mx = "Cuchillo de peletería haranir",
			de = "Lederverarbeitungsmesser der Haranir",
			fr = "Couteau de travail du cuir haranir",
			it = "Coltello da Conciatura degli Haranir",
			-- TODO: pt = "",
			ru = "Харанирский нож кожевника",
			ko = "하라니르 가죽세공용 칼",
			cn = "哈籁尼尔制皮刀",
			tw = "哈拉尼爾製皮小刀",
		},
	},
	[525916] = {
		readable = "Haranir Leatherworking Mallet",
		model = 6693153,
		text = {
			en = "Haranir Leatherworking Mallet",
			es = "Marra de peletería haranir",
			mx = "Mazo de peletería haranir",
			de = "Lederverarbeitungsschlägel der Haranir",
			fr = "Maillet de travail du cuir haranir",
			it = "Mazzuolo da Conciatura degli Haranir",
			-- TODO: pt = "",
			ru = "Харанирская колотушка кожевника",
			ko = "하라니르 가죽세공용 망치",
			cn = "哈籁尼尔制皮槌",
			tw = "哈拉尼爾製皮木槌",
		},
	},
	[525917] = {
		readable = "Patterns: Beyond the Void",
		model = 5975122,
		text = {
			en = "Patterns: Beyond the Void",
			es = "Patrones: más allá del Vacío",
			mx = "[Patterns: Beyond the Void]",
			de = "Muster: Jenseits der Leere",
			fr = "Motifs tirés du Vide",
			it = "Modelli: Oltre il Vuoto",
			pt = "Moldes: Além do Caos",
			ru = "Выкройки: за гранью Бездны",
			ko = "도안: 공허 저 너머로",
			cn = "图样：虚空彼岸",
			tw = "圖樣：虛無之外",
		},
	},
	[525918] = {
		readable = "Bundle of Tanner's Trinkets",
		model = 6212421,
		text = {
			en = "Bundle of Tanner's Trinkets",
			es = "Fardo de abalorios de peletero",
			mx = "Conjunto de baratijas de curtidor",
			de = "Bündel der Schmuckstücke des Gerbers",
			fr = "Bouquet de trésors de travail du cuir",
			it = "Mucchio di Monili del Tannatore",
			pt = "Pacote de Berloques do Curtumeiro",
			ru = "Сверток мелочей дубильщика",
			ko = "무두장이 장신구 묶음",
			cn = "[Bundle of Tanner's Trinkets]",
			tw = "一捆製皮匠的飾品",
		},
	},
})
do ObjectDB[objectID] = objectData; end
