local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[587913] = {
		readable = "Shabby Stockpile",
		model = 1715105,
		text = {
			en = "Shabby Stockpile",
			es = "Reservas desgastadas",
			mx = "Reservas deterioradas",
			de = "Schäbiger Vorrat",
			fr = "Réserve minable",
			it = "Scorte Malandate",
			pt = "Reserva Gasta",
			ru = "Скудный склад",
			ko = "허름한 비축품",
			cn = "破旧的物资",
			tw = "寒酸的儲物箱",
		},
	},
	[591054] = {
		readable = "Gift of the Cycle",
		model = 6730919,
		text = {
			en = "Gift of the Cycle",
			es = "Don del ciclo",
			mx = "Regalo del ciclo",
			de = "Geschenk des Kreislaufs",
			fr = "Don du cycle",
			it = "Dono del Ciclo",
			pt = "Presente do Ciclo",
			ru = "Дар цикла",
			-- TODO: ko = "",
			cn = "轮回的礼物",
			tw = "循環之賜",
		},
	},
	[612932] = {
		readable = "Ransacked Heirloom",
		model = 6866514,
		text = {
			en = "Ransacked Heirloom",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[613517] = {
		readable = "Tome of Polymorph",
		model = 6081188,
		text = {
			en = "Tome of Polymorph",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[614503] = {
		readable = "Crab Trap",
		model = 3857153,
		text = {
			en = "Crab Trap",
			es = "Trampa para cangrejos",
			mx = "Trampa para cangrejos",
			de = "Krabbenfalle",
			fr = "Piège à crabes",
			it = "Trappola per Granchi",
			pt = "Armadilha de Caranguejo",
			ru = "Крабовая ловушка",
			-- TODO: ko = "",
			cn = "捕蟹笼",
			tw = "螃蟹陷阱",
		},
	},
	[617852] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Cofre robusto",
			mx = "Cofre robusto",
			de = "Robuste Truhe",
			fr = "Coffre solide",
			it = "Cassa Resistente",
			pt = "Baú Resistente",
			ru = "Прочный сундук",
			ko = "튼튼한 상자",
			-- TODO: cn = "",
			tw = "結實的箱子",
		},
	},
	[618290] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Cofre robusto",
			mx = "Cofre robusto",
			de = "Robuste Truhe",
			fr = "Coffre solide",
			it = "Cassa Resistente",
			pt = "Baú Resistente",
			ru = "Прочный сундук",
			ko = "튼튼한 상자",
			-- TODO: cn = "",
			tw = "結實的箱子",
		},
	},
	[618495] = {
		readable = "Nullaeus Cache",
		model = 7136759,
		text = {
			en = "Nullaeus Cache",
			es = "Alijo de Anulleus",
			-- TODO: mx = "",
			de = "Nullaeus' Truhe",
			fr = "Cache de Vidaeus",
			it = "Cassa di Nullaeus",
			pt = "Baú de Nullaeus",
			ru = "Тайник Нуллэя",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
})
do ObjectDB[objectID] = objectData; end
