
local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[572449] = {
		readable = "Corrupted Lantern",
		model = 1383910,
		text = {
			en = "Corrupted Lantern",
			es = "Farol corrupto",
			mx = "Farol corrupto",
			de = "Verderbte Laterne",
			fr = "Lanterne corrompue",
			it = "Lanterna Corrotta",
			pt = "Lanterna Corrompida",
			ru = "Оскверненный светильник",
			ko = "타락한 등불",
			cn = "腐化的灯笼",
			tw = "腐化燈籠",
		},
	},
	[572561] = {
		readable = "Crystal",
		model = 5408471,
		text = {
			en = "Crystal",
			es = "Cristal",
			de = "Kristall",
			fr = "Cristal",
			it = "Cristallo",
			pt = "Cristal",
			ru = "Кристалл",
			cn = "水晶",
			tw = "水晶",
		},
	},
	[658087] = {
		readable = "Abundantly Bountiful Heavy Trunk",
		model = 5128194,
		text = {
			en = "Abundantly Bountiful Heavy Trunk",
			es = "Baúl pesado abundantemente pródigo",
			de = "Großzügige schwere Überflusstruhe",
			fr = "Malle lourde extrêmement abondante",
			pt = "Baú Pesado de Abundância Redobrada",
			ru = "Богатый тяжелый ларь изобилия",
			ko = "넘칠 듯이 풍요로운 육중한 보관함",
			cn = "丰饶的丰裕沉重箱子",
			tw = "豐足豐碩沉重的箱子",
		},
	},
	[658088] = {
		readable = "Abundantly Bountiful Heavy Trunk",
		model = 5128194,
		text = {
			en = "Abundantly Bountiful Heavy Trunk",
			es = "Baúl pesado abundantemente pródigo",
			de = "Großzügige schwere Überflusstruhe",
			fr = "Malle lourde extrêmement abondante",
			pt = "Baú Pesado de Abundância Redobrada",
			ru = "Богатый тяжелый ларь изобилия",
			ko = "넘칠 듯이 풍요로운 육중한 보관함",
			cn = "丰饶的丰裕沉重箱子",
			tw = "豐足豐碩沉重的箱子",
		},
	},
})
do ObjectDB[objectID] = objectData; end
