local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[589205] = {
		readable = "A Lost Hunting Knife",
		model = 6252856,
		text = {
			en = "A Lost Hunting Knife",
			-- TODO: es = "",
			-- TODO: mx = "",
			de = "Ein verlorenes Jagdmesser",
			fr = "Couteau de chasse perdu",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[590801] = {
		readable = "A Rolled Up Pillow",
		model = 5161738,
		text = {
			en = "A Rolled Up Pillow",
			es = "Almohada enrollada",
			-- TODO: mx = "",
			de = "Ein zusammengerolltes Kissen",
			fr = "Oreiller enroulé",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[612038] = {
		readable = "Agitated Tome",
		model = 4556819,
		text = {
			en = "Agitated Tome",
			es = "Escrito perturbado",
			mx = "Tomo agitado",
			de = "Aufgebrachter Foliant",
			fr = "Tome agité",
			it = "Tomo Agitato",
			pt = "Tomos Agitados",
			ru = "Потревоженный фолиант",
			ko = "격랑의 마법서",
			cn = "焦躁的书籍",
			tw = "激動的典籍",
		},
	},
	[612079] = {
		readable = "Foul Carcass",
		model = 124640,
		text = {
			en = "Foul Carcass",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[612081] = {
		readable = "Foul Carcass",
		model = 124640,
		text = {
			en = "Foul Carcass",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[612270] = {
		readable = "Embedded Spear",
		model = 6935789,
		text = {
			en = "Embedded Spear",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[612282] = {
		readable = "Stolen Meat",
		model = 4254400,
		text = {
			en = "Stolen Meat",
			es = "Stolen Meat",
			mx = "Stolen Meat",
			de = "Stolen Meat",
			fr = "Stolen Meat",
			it = "Stolen Meat",
			pt = "Stolen Meat",
			ru = "Stolen Meat",
			ko = "Stolen Meat",
			cn = "Stolen Meat",
			tw = "Stolen Meat",
		},
	},
	[612891] = {
		readable = "Bloody Sack",
		model = 977078,
		text = {
			en = "Bloody Sack",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[613252] = {
		readable = "Triple-Locked Safebox",
		model = 875132,
		text = {
			en = "Triple-Locked Safebox",
			es = "Caja fuerte con triple cierre",
			mx = "Caja fuerte de triple cerrojo",
			de = "Dreifach verriegelte Truhe",
			fr = "Coffre-fort extra-fort",
			it = "Cassetta di Sicurezza con Serratura Tripla",
			pt = "Cofre com Tranca Tripla",
			ru = "Сейф с тремя замками",
		},
	},
})
do ObjectDB[objectID] = objectData; end
