local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[617534] = {
		readable = "Gilded Armillary Sphere",
		model = 6033622,
		text = {
			en = "Gilded Armillary Sphere",
			es = "Esfera armilar dorada",
			mx = "Esfera armilar dorada",
			de = "Vergoldete Armillarsphäre",
			fr = "Sphère armillaire dorée",
			it = "Sfera Armillare Dorata",
			pt = "Esfera Armilar Dourada",
			ru = "Золоченая армиллярная сфера",
			ko = "금빛 고리 구체",
			cn = "镀金浑天仪球体",
			tw = "鍍金圓球",
		},
	},
	[617659] = {
		readable = "Sealed Twilight's Blade Bounty",
		model = 5975175,
		text = {
			en = "Sealed Twilight's Blade Bounty",
			es = "Recompensa sellada de la Hoja Crepuscular",
			mx = "Botín de la Daga Crepuscular sellado",
			de = "Versiegelte Beute der Zwielichtklinge",
			fr = "Prime de la Lame du Crépuscule scellée",
			it = "Bottino Sigillato della Lama del Crepuscolo",
			pt = "Recompensa da Lâmina Crepuscular Selada",
			ru = "Запечатанное сокровище Сумеречного Клинка",
			ko = "[Sealed Twilight's Blade Bounty]",
			cn = "[Sealed Twilight's Blade Bounty]",
			tw = "[Sealed Twilight's Blade Bounty]",
		},
	},
	[617692] = {
		readable = "Crown of the Lost Queen",
		model = 3940006,
		text = {
			en = "Crown of the Lost Queen",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[617855] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Cofre robusto",
			mx = "Cofre robusto",
			de = "Robuste Truhe",
			fr = "Coffre solide",
			it = "Cassa Resistente",
			pt = "Baú Resistente",
			ru = "Прочный сундук",
			-- TODO: ko = "",
			-- TODO: cn = "",
			tw = "結實的箱子",
		},
	},
	[617881] = {
		readable = "Rookery Cache",
		model = 6017293,
		text = {
			en = "Rookery Cache",
			es = "Alijo del Grajero",
			mx = "Alijo del Corvento",
			de = "Horsttruhe",
			fr = "Cache de la colonie",
			it = "Cassa della Corveria",
			pt = "Tesouro do Viveiro",
			ru = "Тайник Гнездовья",
			-- TODO: ko = "",
			cn = "栖巢宝箱",
			tw = "培育所貯藏箱",
		},
	},
	[618016] = {
		readable = "Stellar Stash",
		model = 6210898,
		text = {
			en = "Stellar Stash",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[618111] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Cofre robusto",
			mx = "Cofre robusto",
			de = "Robuste Truhe",
			fr = "Coffre solide",
			it = "Cassa Resistente",
			pt = "Baú Resistente",
			ru = "Прочный сундук",
			-- TODO: ko = "",
			-- TODO: cn = "",
			tw = "結實的箱子",
		},
	},
	[618112] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Cofre robusto",
			mx = "Cofre robusto",
			de = "Robuste Truhe",
			fr = "Coffre solide",
			it = "Cassa Resistente",
			pt = "Baú Resistente",
			ru = "Прочный сундук",
			-- TODO: ko = "",
			-- TODO: cn = "",
			tw = "結實的箱子",
		},
	},
	[618270] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Cofre robusto",
			-- TODO: mx = "",
			de = "Robuste Truhe",
			fr = "Coffre solide",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[618272] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Cofre robusto",
			-- TODO: mx = "",
			de = "Robuste Truhe",
			fr = "Coffre solide",
			-- TODO: it = "",
		},
	},
})
do ObjectDB[objectID] = objectData; end
