local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[613758] = {
		readable = "Honored Warrior's Urn",
		model = 6870560,
		text = {
			en = "Honored Warrior's Urn",
			es = "[Honored Warrior's Urn]",
			mx = "[Honored Warrior's Urn]",
			de = "Urne des wohlwollenden Kriegers",
			fr = "Urne de combat glorieux",
			it = "[Honored Warrior's Urn]",
			pt = "[Honored Warrior's Urn]",
			ru = "[Honored Warrior's Urn]",
			ko = "[Honored Warrior's Urn]",
			cn = "[Honored Warrior's Urn]",
			tw = "[Honored Warrior's Urn]",
		},
	},
	[613760] = {
		readable = "Honored Warrior's Urn",
		model = 6870560,
		text = {
			en = "Honored Warrior's Urn",
			es = "[Honored Warrior's Urn]",
			mx = "[Honored Warrior's Urn]",
			de = "[Honored Warrior's Urn]",
			fr = "Urne de combat glorieux",
			it = "[Honored Warrior's Urn]",
			pt = "[Honored Warrior's Urn]",
			ru = "[Honored Warrior's Urn]",
			ko = "[Honored Warrior's Urn]",
			cn = "[Honored Warrior's Urn]",
			tw = "[Honored Warrior's Urn]",
		},
	},
	[613823] = {
		readable = "Ancient Runestone",
		model = 6796710,
		text = {
			en = "Ancient Runestone",
			-- TODO: es = "",
			-- TODO: mx = "",
			de = "Uralter Runenstein",
			fr = "Pierre runique ancienne",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[613827] = {
		readable = "Derelict Mural",
		model = 6715096,
		text = {
			en = "Derelict Mural",
			-- TODO: es = "",
			-- TODO: mx = "",
			de = "Heruntergekommenes Wandbild",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[613828] = {
		readable = "Forgotten Mural",
		model = 6712537,
		text = {
			en = "Forgotten Mural",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[615963] = {
		readable = "Sporespawned Cache",
		model = 5838194,
		text = {
			en = "Sporespawned Cache",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[617163] = {
		readable = "Malignant Chest",
		model = 6210898,
		text = {
			en = "Malignant Chest",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[617237] = {
		readable = "Sealed Twilight's Blade Cache",
		model = 5975175,
		text = {
			en = "Sealed Twilight's Blade Cache",
			es = "[Sealed Twilight's Blade Cache]",
			mx = "[Sealed Twilight's Blade Cache]",
			de = "Versiegeltes Lager der Zwielichtklinge",
			fr = "[Sealed Twilight's Blade Cache]",
			it = "[Sealed Twilight's Blade Cache]",
			pt = "[Sealed Twilight's Blade Cache]",
			ru = "[Sealed Twilight's Blade Cache]",
			ko = "[Sealed Twilight's Blade Cache]",
			cn = "[Sealed Twilight's Blade Cache]",
			tw = "[Sealed Twilight's Blade Cache]",
		},
	},
	[617245] = {
		readable = "Broken Armor",
		model = 1015965,
		text = {
			en = "Broken Armor",
			es = "Broken Armor",
			mx = "Broken Armor",
			de = "Broken Armor",
			fr = "Broken Armor",
			it = "Broken Armor",
			pt = "Broken Armor",
			ru = "Broken Armor",
			ko = "Broken Armor",
			cn = "Broken Armor",
			tw = "Broken Armor",
		},
	},
	[617375] = {
		readable = "Murloc-Skewered Lynxfish",
		model = 1091579,
		text = {
			en = "Murloc-Skewered Lynxfish",
			es = "[Murloc-Skewered Lynxfish]",
			mx = "Pezlince ensartado múrloc",
			de = "Luchsfischspieß nach Murlocart",
			fr = "Brochette murloc de poisson-lynx",
			it = "Pescelince Infilzato dai Murloc",
			pt = "Peixe-lince Espetado por Murlocs",
			ru = "Мурлочий шашлык из рысевки",
			ko = "[Murloc-Skewered Lynxfish]",
			cn = "[Murloc-Skewered Lynxfish]",
			tw = "[Murloc-Skewered Lynxfish]",
		},
	},
	[617432] = {
		readable = "Forgotten Ink and Quill",
		model = 6935639,
		text = {
			en = "Forgotten Ink and Quill",
			de = "Vergessene Tinte und Feder",
			es = "Tinta y pluma olvidadas",
			mx = "Tinta y pluma olvidadas",
			fr = "Encre et plume oubliées",
			it = "Penna e Inchiostro Dimenticati",
			ko = "잊힌 잉크와 깃펜",
			pt = "Tinta e Cálamo Esquecidos",
			ru = "Забытые перо и чернила",
			cn = "被遗忘的墨水和羽毛笔",
			tw = "遺忘的羽毛筆與墨水",
		},
	},
})
do ObjectDB[objectID] = objectData; end
