local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[619647] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "Punto de observación",
			mx = "Mirador",
			de = "Aussichtspunkt",
			fr = "Point de vue",
			it = "Punto Panoramico",
			pt = "Ponto de Paisagem",
			ru = "Точка обзора",
			-- TODO: ko = "",
			cn = "观景台",
			tw = "景點",
		},
	},
	[619648] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "Punto de observación",
			mx = "Mirador",
			de = "Aussichtspunkt",
			fr = "Point de vue",
			it = "Punto Panoramico",
			pt = "Ponto de Paisagem",
			ru = "Точка обзора",
			ko = "풍경 지점",
			cn = "观景台",
			tw = "景點",
		},
	},
	[619649] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "Punto de observación",
			mx = "Mirador",
			de = "Aussichtspunkt",
			fr = "Point de vue",
			it = "Punto Panoramico",
			pt = "Ponto de Paisagem",
			ru = "Точка обзора",
			ko = "풍경 지점",
			cn = "观景台",
			tw = "景點",
		},
	},
	[619650] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "Punto de observación",
			mx = "Mirador",
			de = "Aussichtspunkt",
			fr = "Point de vue",
			it = "Punto Panoramico",
			pt = "Ponto de Paisagem",
			ru = "Точка обзора",
			-- TODO: ko = "",
			cn = "观景台",
			tw = "景點",
		},
	},
	[619651] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "Punto de observación",
			mx = "Mirador",
			de = "Aussichtspunkt",
			fr = "Point de vue",
			it = "Punto Panoramico",
			pt = "Ponto de Paisagem",
			ru = "Точка обзора",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[619652] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "Punto de observación",
			mx = "Mirador",
			de = "Aussichtspunkt",
			fr = "Point de vue",
			it = "Punto Panoramico",
			pt = "Ponto de Paisagem",
			ru = "Точка обзора",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[619653] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			-- TODO: es = "",
			mx = "Mirador",
			de = "Aussichtspunkt",
			fr = "Point de vue",
			it = "Punto Panoramico",
			pt = "Ponto de Paisagem",
			ru = "Точка обзора",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[619654] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "Punto de observación",
			mx = "Mirador",
			de = "Aussichtspunkt",
			fr = "Point de vue",
			it = "Punto Panoramico",
			pt = "Ponto de Paisagem",
			ru = "Точка обзора",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[619655] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
		},
	},
})
do ObjectDB[objectID] = objectData; end
