local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[454188] = {
		readable = "Spoils of K'aresh",
		model = 5545988,
		text = {
			en = "Spoils of K'aresh",
			es = "Botín de K'aresh",
			mx = "Botín de K'aresh",
			de = "Raubgut von K'aresh",
			fr = "Trésor de K’aresh",
			it = "Spoglie di K'aresh",
			pt = "Espólios de K'aresh",
			ru = "Трофеи К'ареша",
			ko = "크아레쉬 전리품",
			cn = "卡雷什战利品",
			tw = "凱瑞西戰利品",
		},
	},
	[546729] = {
		readable = "Treasure Chest",
		model = 6017293,
		text = {
			en = "Treasure Chest",
			es = "Arqueta",
			mx = "Cofre del tesoro",
			de = "Schatztruhe",
			fr = "Coffre au trésor",
			it = "Cassa del Tesoro",
			pt = "Baú do Tesouro",
			ru = "Сундук с сокровищами",
			ko = "보물 상자",
			cn = "藏宝箱",
			tw = "寶箱",
		},
	},
	[621494] = {
		readable = "Prize Chest",
		model = 6210898,
		text = {
			en = "Prize Chest",
			es = "Cofre de premios",
			mx = "Cofre de premios",
			de = "Preistruhe",
			fr = "Coffre de récompense",
			-- TODO: it = "",
			pt = "Baú de Prêmios",
			ru = "Призовой сундук",
			ko = "경품 상자",
			cn = "奖品宝箱",
			-- TODO: tw = "",
		},
	},
	[623259] = {
		readable = "Pilfered Trunk",
		model = 5128194,
		text = {
			en = "Pilfered Trunk",
			es = "Pilfered Trunk",
			mx = "Arcón saqueado",
			de = "Stibitzte Truhe",
			fr = "Malle chapardée",
			it = "Baule Trafugato",
			pt = "Baú Furtado",
			ru = "Опустошенный ларь",
			ko = "도둑맞은 보관함",
			cn = "Pilfered Trunk",
			tw = "Pilfered Trunk",
		},
	},
})
do ObjectDB[objectID] = objectData; end
