local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[525962] = {
		readable = "Failed Experiment",
		model = 240975,
		text = {
			en = "Failed Experiment",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[525963] = {
		readable = "Pristine Potion",
		model = 4240485,
		text = {
			en = "Pristine Potion",
			es = "Poción prístina",
			-- TODO: mx = "",
			de = "Makelloser Trank",
			fr = "Potion immaculée",
			it = "Pozione Immacolata",
			pt = "Poção Impecável",
			ru = "Безупречное зелье",
			-- TODO: ko = "",
			cn = "原初药水",
			tw = "原始藥水",
		},
	},
	[525964] = {
		readable = "Measured Ladle",
		model = 6326885,
		text = {
			en = "Measured Ladle",
			-- TODO: es = "",
			-- TODO: mx = "",
			de = "Abgemessene Kelle",
			fr = "Louche graduée",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[525965] = {
		readable = "Freshly Plucked Peacebloom",
		model = 219481,
		text = {
			en = "Freshly Plucked Peacebloom",
			es = "Flor de paz recién cortada",
			-- TODO: mx = "",
			de = "Frisch gepflückte Friedensblume",
			fr = "Pacifique fraîchement cueillie",
			it = "Sbocciapace Appena Raccolto",
			pt = "Botão-da-paz Recém-arrancado",
			ru = "Свежайший мироцвет",
			-- TODO: ko = "",
			cn = "新采摘的宁神花",
			tw = "剛摘下的寧神花",
		},
	},
	[525966] = {
		readable = "Vial of Zul'Aman Oddities",
		model = 5364266,
		text = {
			en = "Vial of Zul'Aman Oddities",
			es = "[Vial of Zul'Aman Oddities]",
			mx = "[Vial of Zul'Aman Oddities]",
			de = "[Vial of Zul'Aman Oddities]",
			fr = "[Vial of Zul'Aman Oddities]",
			it = "Fiala di Stranezze di Zul'aman",
			pt = "[Vial of Zul'Aman Oddities]",
			ru = "[Vial of Zul'Aman Oddities]",
			ko = "[Vial of Zul'Aman Oddities]",
			cn = "[Vial of Zul'Aman Oddities]",
			tw = "[Vial of Zul'Aman Oddities]",
		},
	},
	[525967] = {
		readable = "Vial of Rootlands Oddities",
		model = 5364267,
		text = {
			en = "Vial of Rootlands Oddities",
			-- TODO: es = "",
			-- TODO: mx = "",
			de = "Phiole der Kuriositäten der Wurzellande",
			fr = "Fiole de curiosités des terres des Racines",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[525968] = {
		readable = "Vial of Voidstorm Oddities",
		model = 5364269,
		text = {
			en = "Vial of Voidstorm Oddities",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[525970] = {
		readable = "Bloomed Bud",
		model = 6437978,
		text = {
			en = "Bloomed Bud",
			-- TODO: es = "",
			-- TODO: mx = "",
			de = "Blühende Knospe",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[525972] = {
		readable = "Simple Leaf Pruners",
		model = 955741,
		text = {
			en = "Simple Leaf Pruners",
			es = "Podadora sencilla",
			-- TODO: mx = "",
			de = "Einfacher Blattschneider",
			fr = "Sécateur simple",
			it = "Cesoie Semplici per Fogliame",
			pt = "Tesoura de Folhas Simples",
			ru = "Простые садовые ножницы",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[525973] = {
		readable = "Lightbloom Root",
		model = 6048324,
		text = {
			en = "Lightbloom Root",
			-- TODO: es = "",
			-- TODO: mx = "",
			de = "Lichtblütenwurzel",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[525975] = {
		readable = "Harvester's Sickle",
		model = 1031834,
		text = {
			en = "Harvester's Sickle",
			es = "[Harvester's Sickle]",
			mx = "[Harvester's Sickle]",
			de = "Sichel des Ernters",
			fr = "Faucille de moisson",
			it = "[Harvester's Sickle]",
			pt = "Foice do Ceifador",
			ru = "Серп жнеца",
			ko = "[Harvester's Sickle]",
			cn = "[Harvester's Sickle]",
			tw = "[Harvester's Sickle]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
