local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[408070] = {
		readable = "Sandsparkle Clam",
		model = 196998,
		text = {
			en = "Sandsparkle Clam",
			es = "Almeja brillarena",
			-- TODO: mx = "",
			de = "Sandschimmermuschel",
			fr = "Palourde Scintisable",
			it = "Ostrica Splendisabbia",
			pt = "Marisco Reluzareia",
			ru = "Моллюск Блестящего Песка",
			-- TODO: ko = "",
			-- TODO: cn = "",
			tw = "沙耀蚌殼",
		},
	},
	[523388] = {
		readable = "Maraad's Meditation Crystal",
		model = 1108688,
		text = {
			en = "Maraad's Meditation Crystal",
			es = "Cristal de meditación de Maraad",
			mx = "Cristal de meditación de Maraad",
			de = "Maraads Meditationskristall",
			fr = "Cristal de méditation de Maraad",
			it = "Cristallo di Meditazione di Maraad",
			pt = "Cristal de Meditação do Maraad",
			ru = "Кристалл Мараада для медитации",
			ko = "마라아드의 명상 수정",
			cn = "玛尔拉德的冥想水晶",
			tw = "瑪銳德的冥想水晶",
		},
	},
	[525374] = {
		readable = "Stolen Equipment",
		model = 6733832,
		text = {
			en = "Stolen Equipment",
			es = "Equipo robado",
			mx = "Equipamiento robado",
			de = "Gestohlene Ausrüstung",
			fr = "Équipement volé",
			it = "Equipaggiamento Rubato",
			pt = "Equipamento Roubado",
			ru = "Украденное снаряжение",
			ko = "도둑맞은 장비",
			cn = "失窃的装备",
			tw = "遭竊的裝備",
		},
	},
	[525891] = {
		readable = "Amani Skinning Knife",
		model = 977082,
		text = {
			en = "Amani Skinning Knife",
			es = "Cuchillo de desuello Amani",
			mx = "Cuchillo para desollar amani",
			de = "Kürschnermesser der Amani",
			fr = "Couteau à dépecer amani",
			it = "Coltello da Scuoiatore Amani",
			pt = "Faca de Esfolamento Amani",
			ru = "Аманийский нож для снятия шкур",
			ko = "아마니 무두질용 손칼",
			cn = "阿曼尼剥皮刀",
			tw = "阿曼尼剝皮小刀",
		},
	},
	[525893] = {
		readable = "Amani Tanning Oil",
		model = 936458,
		text = {
			en = "Amani Tanning Oil",
			es = "Aceite para curtir Amani",
			mx = "Aceite para curtido amani",
			de = "Gerböl der Amani",
			fr = "Huile de tannage amani",
			it = "Olio per Tannatura degli Amani",
			pt = "Óleo de Curtimento Amani",
			ru = "Аманийское дубильное масло",
			ko = "아마니 무두질 기름",
			cn = "阿曼尼制革油",
			tw = "阿曼尼鞣製油",
		},
	},
	[525898] = {
		readable = "Artisan's Cover Comb",
		model = 7197588,
		text = {
			en = "Artisan's Cover Comb",
			es = "Peine para esquilar de artesano",
			mx = "Peine de telar de artesano",
			de = "Abdeckkamm des Kunsthandwerkers",
			fr = "Peigne d’artisanat",
			it = "Copripettine dell'Artigiano",
			pt = "Pente Coberto do Artífice",
			ru = "Чесальный гребень ремесленника",
			ko = "장인의 덮개 빗",
			cn = "工匠的布面梳",
			tw = "工匠的護髮梳",
		},
	},
	[525899] = {
		readable = "Particularly Enchanting Tablecloth",
		model = 7014302,
		text = {
			en = "Particularly Enchanting Tablecloth",
			es = "Mantel particularmente encantador",
			mx = "Mantel particularmente encantador",
			de = "Besonders bezauberndes Tischtuch",
			fr = "Nappe particulièrement envoûtante",
			it = "Tovaglia Particolarmente Incantevole",
			pt = "Toalha de Mesa Particularmente Encantadora",
			ru = "Скатерть с особыми чарами",
			ko = "강력한 마법이 부여된 탁자보",
			cn = "特意附魔的桌布",
			tw = "特別附魔的桌布",
		},
	},
	[525900] = {
		readable = "Satin Throw Pillow",
		model = 6050854,
		text = {
			en = "Satin Throw Pillow",
			es = "Cojín decorativo de satén",
			mx = "Cojín decorativo de satén",
			de = "Satinzierkissen",
			fr = "Coussin décoratif en satin",
			it = "Cuscino Decorativo di Raso",
			pt = "Almofada de Cetim",
			ru = "Сатиновая диванная подушка",
			ko = "작은 부드러운 베개",
			cn = "绸缎抱枕",
			tw = "緞質抱枕",
		},
	},
	[525901] = {
		readable = "Book of Sin'dorei Stitches",
		model = 6081188,
		text = {
			en = "Book of Sin'dorei Stitches",
			es = "Libro de costura sin'dorei",
			mx = "Libro de puntadas sin'dorei",
			de = "Buch der Sin'dorei-Nähkunst",
			fr = "Petit livre des points de couture sin’dorei",
			it = "Libro dei Punti dei Sin'dorei",
			pt = "Livro de Suturas Sin'dorei",
			ru = "Сборник син'дорайских швов",
			ko = "신도레이 바느질의 서",
			cn = "辛多雷缝线之书",
			tw = "辛多雷縫紉書",
		},
	},
	[525902] = {
		readable = "Wooden Weaving Sword",
		model = 7197586,
		text = {
			en = "Wooden Weaving Sword",
			es = "Batidor de madera",
			mx = "Espada de tejido de madera",
			de = "Hölzernes Webschwert",
			fr = "Épée de tissage en bois",
			-- TODO: it = "",
			pt = "Espada de Carpintaria",
			ru = "Деревянный ткацкий батан",
			ko = "나무 직조 검",
			cn = "木制纺织器",
			tw = "木製編織劍",
		},
	},
	[525903] = {
		readable = "Sin'dorei Outfitter's Ruler",
		model = 4323303,
		text = {
			en = "Sin'dorei Outfitter's Ruler",
			es = "Regla de sastre sin'dorei",
			mx = "Regla de estilista sin'dorei",
			de = "Lineal des Sin'dorei-Ausstatters",
			fr = "Mètre de couture sin’dorei",
			it = "Righello dello Stilista Sin'dorei",
			pt = "Régua do Provedor Sin'dorei",
			ru = "Линейка син'дорайского портного",
			ko = "신도레이 재단사의 자",
			cn = "辛多雷服装师的尺子",
			tw = "辛多雷服飾商直尺",
		},
	},
	[525904] = {
		readable = "A Really Nice Curtain",
		model = 6435039,
		text = {
			en = "A Really Nice Curtain",
			es = "Cortinilla preciosa",
			mx = "Una cortina muy bonita",
			de = "Ein richtig schöner Vorhang",
			fr = "Très beau rideau",
			it = "Tenda Molto Piacevole",
			pt = "Uma Cortina Bem Legal",
			ru = "Красивая штора",
			ko = "아주 멋진 커튼",
			cn = "绝美的窗帘",
			tw = "頂級窗簾",
		},
	},
	[525905] = {
		readable = "A Child's Stuffy",
		model = 5350798,
		text = {
			en = "A Child's Stuffy",
			es = "Peluchín",
			mx = "Un peluche de niño",
			de = "Ein Stofftier eines Kindes",
			fr = "Peluche d’enfant",
			it = "[A Child's Stuffy]",
			pt = "Uma Pelúcia de Criança",
			ru = "Детская мягкая игрушка",
			ko = "어린아이의 인형",
			cn = "儿童的填充玩具",
			tw = "孩子的玩偶",
		},
	},
})
do ObjectDB[objectID] = objectData; end
