local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[568213] = {
		readable = "Mana-Fortified Vintage",
		model = 6025944,
		text = {
			en = "Mana-Fortified Vintage",
			es = "[Mana-Fortified Vintage]",
			mx = "[Mana-Fortified Vintage]",
			de = "[Mana-Fortified Vintage]",
			fr = "[Mana-Fortified Vintage]",
			it = "[Mana-Fortified Vintage]",
			pt = "Safra Fortificada com Mana",
			ru = "[Mana-Fortified Vintage]",
			ko = "[Mana-Fortified Vintage]",
			cn = "[Mana-Fortified Vintage]",
			tw = "[Mana-Fortified Vintage]",
		},
	},
	[568214] = {
		readable = "Mana-Fortified Vintage",
		model = 6025944,
		text = {
			en = "Mana-Fortified Vintage",
			es = "[Mana-Fortified Vintage]",
			mx = "[Mana-Fortified Vintage]",
			de = "[Mana-Fortified Vintage]",
			fr = "[Mana-Fortified Vintage]",
			it = "[Mana-Fortified Vintage]",
			pt = "Safra Fortificada com Mana",
			ru = "[Mana-Fortified Vintage]",
			ko = "[Mana-Fortified Vintage]",
			cn = "[Mana-Fortified Vintage]",
			tw = "[Mana-Fortified Vintage]",
		},
	},
	[572034] = {
		readable = "Pylon Fragment",
		model = 1327768,
		text = {
			en = "Pylon Fragment",
			es = "[Pylon Fragment]",
			mx = "[Pylon Fragment]",
			de = "[Pylon Fragment]",
			fr = "[Pylon Fragment]",
			it = "[Pylon Fragment]",
			pt = "[Pylon Fragment]",
			ru = "[Pylon Fragment]",
			ko = "[Pylon Fragment]",
			cn = "[Pylon Fragment]",
			tw = "[Pylon Fragment]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
