local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[656049] = {
		readable = "Odd Smelling Crate",
		model = 6159540,
		text = {
			en = "Odd Smelling Crate",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[658801] = {
		readable = "Specimen Container",
		model = 5916193,
		text = {
			en = "Specimen Container",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[658803] = {
		readable = "Spiked Shell",
		model = 6361139,
		text = {
			en = "Spiked Shell",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
})
do ObjectDB[objectID] = objectData; end
