local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[642704] = {
		readable = "Seagull Feather",
		model = 199704,
		text = {
			en = "Seagull Feather",
			es = "Seagull Feather",
			mx = "Seagull Feather",
			de = "Seagull Feather",
			fr = "Seagull Feather",
			it = "Seagull Feather",
			pt = "Seagull Feather",
			ru = "Seagull Feather",
			ko = "Seagull Feather",
			cn = "Seagull Feather",
			tw = "Seagull Feather",
		},
	},
	[648981] = {
		readable = "Bubbling Clam",
		model = 196998,
		text = {
			en = "Bubbling Clam",
			es = "Bubbling Clam",
			mx = "Bubbling Clam",
			de = "Bubbling Clam",
			fr = "Bubbling Clam",
			it = "Bubbling Clam",
			pt = "Bubbling Clam",
			ru = "Bubbling Clam",
			ko = "Bubbling Clam",
			cn = "Bubbling Clam",
			tw = "Bubbling Clam",
		},
	},
	[649687] = {
		readable = "Soulcoiler's Trove",
		text = {
			en = "Soulcoiler's Trove",
			es = "Soulcoiler's Trove",
			mx = "Soulcoiler's Trove",
			de = "Soulcoiler's Trove",
			fr = "Soulcoiler's Trove",
			it = "Soulcoiler's Trove",
			pt = "Soulcoiler's Trove",
			ru = "Soulcoiler's Trove",
			ko = "Soulcoiler's Trove",
			cn = "Soulcoiler's Trove",
			tw = "Soulcoiler's Trove",
		},
	},
	[655978] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			mx = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
			tw = "Sturdy Chest",
		},
	},
	[655979] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			mx = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
			tw = "Sturdy Chest",
		},
	},
	[655980] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			mx = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
			tw = "Sturdy Chest",
		},
	},
	[655981] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			mx = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
			tw = "Sturdy Chest",
		},
	},
	[655982] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			mx = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
			tw = "Sturdy Chest",
		},
	},
	[655983] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			mx = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
			tw = "Sturdy Chest",
		},
	},
	[661347] = {
		readable = "Slithersoul Spoils",
		text = {
			en = "Slithersoul Spoils",
			es = "Slithersoul Spoils",
			mx = "Slithersoul Spoils",
			de = "Slithersoul Spoils",
			fr = "Slithersoul Spoils",
			it = "Slithersoul Spoils",
			pt = "Slithersoul Spoils",
			ru = "Slithersoul Spoils",
			ko = "Slithersoul Spoils",
			cn = "Slithersoul Spoils",
			tw = "Slithersoul Spoils",
		},
	},
})
do ObjectDB[objectID] = objectData; end
