local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[619656] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "Punto de observación",
			-- TODO: mx = "",
			de = "Aussichtspunkt",
			fr = "Point de vue",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[619657] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "Punto de observación",
			-- TODO: mx = "",
			de = "Aussichtspunkt",
			fr = "Point de vue",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[619658] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "Punto de observación",
			-- TODO: mx = "",
			de = "Aussichtspunkt",
			fr = "Point de vue",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[619659] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "Punto de observación",
			-- TODO: mx = "",
			de = "Aussichtspunkt",
			fr = "Point de vue",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[619660] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "Punto de observación",
			-- TODO: mx = "",
			de = "Aussichtspunkt",
			fr = "Point de vue",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[619661] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[619662] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[619663] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			-- TODO: ko = "",
			-- TODO: cn = "",
			-- TODO: tw = "",
		},
	},
	[619664] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: de = "",
		},
	},
})
do ObjectDB[objectID] = objectData; end
