local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[406895] = {
		readable = "Violet Forget-Me-Not",
		model = 4005589,
		text = {
			en = "Violet Forget-Me-Not",
			es = "Nomeolvides violeta",
			mx = "Nomeolvides violeta",
			de = "Violettes Vergissmeinnicht",
			fr = "Myosotis violet",
			it = "Violetta Nontiscordardimé",
			pt = "Não-me-esqueças Violeta",
			ru = "Фиолетовая незабудка",
			ko = "보랏빛 물망초",
			cn = "紫色的勿忘我",
			tw = "[Violet Forget-Me-Not]",
		},
	},
	[408066] = {
		readable = "Root Restoration Fruit",
		model = 4495231,
		text = {
			en = "Root Restoration Fruit",
			es = "Fruta de restauración de raíces",
			mx = "Fruta restauradora de raíces",
			de = "Wurzelwiederherstellungsfrucht",
			fr = "Fruit de restauration des racines",
			it = "Frutto della Rigenerazione delle Radici",
			pt = "Fruta de Restauração de Raiz",
			ru = "Плод восстановления корней",
			ko = "뿌리의 복원 과일",
			cn = "愈根之果",
			-- TODO: tw = "",
		},
	},
	[408130] = {
		readable = "Voluptuous Vines",
		model = 3996861,
		text = {
			en = "Voluptuous Vines",
			es = "Vides voluptuosas",
			mx = "Enredaderas voluptuosas",
			de = "Üppige Ranken",
			fr = "Vignes généreuses",
			it = "Viticci Voluttuosi",
			pt = "Vinhas Voluptuosas",
			ru = "Манящие лианы",
			ko = "풍성한 덩굴",
			cn = "舒适藤蔓",
			tw = "舒適藤蔓",
		},
	},
	[410244] = {
		readable = "Burning Ashphodel",
		model = 5245890,
		text = {
			en = "Burning Ashphodel",
			es = "Asfódelo ardiente",
			mx = "Asfóguelo en llamas",
			de = "Brennender Aschphodill",
			fr = "Cendrelle enflammée",
			it = "Asfodelo Cinereo Ardente",
			pt = "Cinzerária em Brasa",
			ru = "Горящий пепельный асфодель",
			ko = "불타는 잿빛수선화",
			cn = "燃烧的烬仙花",
			tw = "燃燒的灰燼水仙",
		},
	},
	[410764] = {
		readable = "Sample of Cinder Pollen",
		model = 902296,
		text = {
			en = "Sample of Cinder Pollen",
			es = "Muestra de polen de ceniza",
			mx = "Muestra de polen cinéreo",
			de = "Probe Glutpollen",
			fr = "Échantillon de pollen des cendres",
			it = "Campione di Polline Cinereo",
			pt = "Amostra de Pólen de Cinzas",
			ru = "Образец пепельной пыльцы",
			ko = "잿불 꽃가루 표본",
			cn = "燃烬花粉样本",
			tw = "燼火花粉樣本",
		},
	},
	[567209] = {
		readable = "Stormarion Supplies",
		model = 6391990,
		text = {
			en = "Stormarion Supplies",
			es = "Suministros de Tormentarion",
			-- TODO: mx = "",
			de = "Sturmarionvorräte",
			fr = "Fournitures de Fulgarion",
			it = "Rifornimenti di Buferion",
			pt = "Suprimentos de Tempestrião",
			ru = "Штормарионские припасы",
			ko = "스토마리온 보급품",
			cn = "斯托玛兰补给品",
			tw = "風瑪利昂補給品",
		},
	},
})
do ObjectDB[objectID] = objectData; end
