local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	
		[353010] = {
			readable = "Tribute",
			model = 3009835,
			text = {
				en = "Tribute",
				es = "Tributo",
				de = "Tribut",
				fr = "Tribut",
				it = "Tributo",
				pt = "Tributo",
				ru = "Дар",
				ko = "공물",
				cn = "供品",
			},
		},
	
		[353012] = {
			readable = "Dorin's Journal",
			model = 3533100,
			text = {
				en = "Dorin's Journal",
				es = "Diario de Dorin",
				de = "Dorins Tagebuch",
				fr = "Journal de Dorin",
				it = "Diario di Dorin",
				pt = "Diário de Dorin",
				ru = "Дневник Дорина",
				ko = "도린의 일지",
				cn = "多林的日志",
			},
		},
	
		[353017] = {
			readable = "Servant's Basic Kit",
			model = 2972426,
			text = {
				en = "Servant's Basic Kit",
				es = "Kit básico de sirviente",
				de = "Einfache Dienerausrüstung",
				fr = "Kit de serviteur de base",
				it = "Kit di Base della Servitù",
				pt = "Kit Básico de Serviçal",
				ru = "Базовый комплект слуги",
				ko = "하인의 기본 도구",
				cn = "仆从的基础工具盒",
			},
		},
	
		[353019] = {
			readable = "Silver Strongbox",
			model = 3189120,
			text = {
				en = "Silver Strongbox",
				es = "Caja fuerte de plata",
				de = "Silberne Schließkassette",
				fr = "Coffre renforcé en argent",
				it = "Forziere d'Argento",
				pt = "Caixa-forte de Prata",
				ru = "Серебряный сундучок",
				ko = "은 금고",
				cn = "白银保险箱",
			},
		},
	
		[353020] = {
			readable = "Tribute",
			model = 3009835,
			text = {
				en = "Tribute",
				es = "Tributo",
				de = "Tribut",
				fr = "Tribut",
				it = "Tributo",
				pt = "Tributo",
				ru = "Дар",
				cn = "供品",
			},
		},
	
		[353152] = {
			readable = "Drained Wildseed",
			model = 3024729,
			text = {
				en = "Drained Wildseed",
				es = "Semilla silvestre drenada",
				de = "Ausgelaugter Wildsamen",
				fr = "Graine sauvage drainée",
				it = "Semebrado Prosciugato",
				pt = "Semente Selvagem Drenada",
				ru = "Опустошенное дикое семя",
				ko = "쇠진한 야생씨앗",
				cn = "被吸干的灵种",
			},
		},
	
		[353153] = {
			readable = "Nondescript Book",
			model = 3533100,
			text = {
				en = "Nondescript Book",
				es = "Libro anodino",
				de = "Unauffälliges Buch",
				fr = "Livre quelconque",
				it = "Libro Indefinibile",
				pt = "Livro Indistinto",
				ru = "Неприметная книга",
				ko = "평범한 책",
				cn = "无特征的书",
			},
		},
	
		[353170] = {
			readable = "Place Blade",
			model = 2499906,
			text = {
				en = "Place Blade",
				es = "Colocar hoja",
				de = "Klinge platzieren",
				fr = "Placer la lame",
				it = "Piazzamento Lama",
				pt = "Colocar Lâmina",
				ru = "Разместите клинок",
				ko = "검 놓기",
				cn = "放置利刃",
			},
		},
	
		[353172] = {
			readable = "Kyrian Javelin",
			model = 3038742,
			text = {
				en = "Kyrian Javelin",
				es = "Jabalina kyriana",
				de = "Kyrianischer Wurfspeer",
				fr = "Javelot kyrian",
				it = "Giavellotto dei Kyrian",
				pt = "Zagaia Kyriana",
				ru = "Кирийский дротик",
				ko = "키리안 투창",
				cn = "格里恩标枪",
			},
		},
	
		[353177] = {
			readable = "Gurney",
			model = 3260551,
			text = {
				en = "Gurney",
				es = "Camilla",
				de = "Bahre",
				fr = "Brancard",
				it = "Lettiga",
				pt = "Maca",
				ru = "Тележка",
				ko = "들것",
				cn = "轮床",
			},
		},
	
		[353194] = {
			readable = "Pulsing Animacone",
			model = 3158888,
			text = {
				en = "Pulsing Animacone",
				es = "Bellota de ánima palpitante",
				de = "Pulsierender Animazapfen",
				fr = "Gland d’anima vibrant",
				it = "Cono d'Animum Pulsante",
				pt = "Pinha-de-ânima Pulsante",
				ru = "Пульсирующая анимашишка",
				ko = "고동치는 령방울",
				cn = "脉动的心能球果",
			},
		},
	
		[353195] = {
			readable = "Locked Door",
			model = 3059777,
			text = {
				en = "Locked Door",
				es = "Puerta cerrada",
				de = "Verschlossene Tür",
				fr = "Porte verrouillée",
				it = "Porta Chiusa",
				pt = "Porta Trancada",
				ru = "Запертая дверь",
				ko = "잠긴 문",
				cn = "锁住的门",
			},
		},
	
		[353202] = {
			readable = "Hidden Valve",
			model = 3558332,
			text = {
				en = "Hidden Valve",
				es = "Válvula oculta",
				de = "Versetcktes Ventil",
				fr = "Valve cachée",
				it = "Valvola Nascosta",
				pt = "Válvula Escondida",
				ru = "Скрытый клапан",
				ko = "숨겨진 밸브",
				cn = "隐藏的阀门",
			},
		},
	
		[353203] = {
			readable = "Cracked Crate",
			model = 3036549,
			text = {
				en = "Cracked Crate",
				es = "Cajón agrietado",
				de = "Beschädigte Kiste",
				fr = "Caisse fissurée",
				it = "Cassa Incrinata",
				pt = "Caixote Rachado",
				ru = "Ящик с трещиной",
				ko = "금이 간 상자",
				cn = "破裂的箱子",
			},
		},
	
		[353205] = {
			readable = "Silver Strongbox",
			model = 3189120,
			text = {
				en = "Silver Strongbox",
				es = "Caja fuerte de plata",
				de = "Silberne Schließkassette",
				fr = "Coffre renforcé en argent",
				it = "Forziere d'Argento",
				pt = "Caixa-forte de Prata",
				ru = "Серебряный сундучок",
				ko = "은 금고",
				cn = "白银保险箱",
			},
		},
	
		[353206] = {
			readable = "Tribute",
			model = 3009835,
			text = {
				en = "Tribute",
				es = "Tributo",
				de = "Tribut",
				fr = "Tribut",
				it = "Tributo",
				pt = "Tributo",
				ru = "Дар",
				ko = "공물",
				cn = "供品",
			},
		},
	
		[353207] = {
			readable = "Hidden Valve",
			model = 3558332,
			text = {
				en = "Hidden Valve",
				es = "Válvula oculta",
				de = "Versetcktes Ventil",
				fr = "Valve cachée",
				it = "Valvola Nascosta",
				pt = "Válvula Escondida",
				ru = "Скрытый клапан",
				ko = "숨겨진 밸브",
				cn = "隐藏的阀门",
			},
		},
	
		[353208] = {
			readable = "Mueh'zala Token",
			model = 668138,
			text = {
				en = "Mueh'zala Token",
				es = "Ficha de Mueh'zala",
				de = "Mueh'zalas Marke",
				fr = "Jeton de Mueh’zala",
				it = "Emblema di Mueh'zala",
				pt = "Ficha de Mueh'zala",
				ru = "Жетон Мве'залы",
				ko = "무에젤라의 징표",
				cn = "穆厄扎拉的符记",
			},
		},
	
		[353210] = {
			readable = "Grinchin Calligraphy Set",
			model = 3148987,
			text = {
				en = "Grinchin Calligraphy Set",
				es = "Kit de caligrafía Risamentón",
				de = "Grinskinnkalligraphieset",
				fr = "Matériel de calligraphie des Riktus",
				it = "Set da Calligrafo Grincioso",
				pt = "Conjunto de Caligrafia Grinchina",
				ru = "Гринчинский каллиграфический набор",
				ko = "그린친 붓글씨 도구",
				cn = "笑颏书法套件",
			},
		},
	
		[353214] = {
			readable = "Hanging Chain",
			model = 3491673,
			text = {
				en = "Hanging Chain",
				es = "Cadena colgante",
				de = "Hängekette",
				fr = "Chaîne suspendue",
				it = "Catene Appese",
				pt = "Corrente Pendurada",
				ru = "Висящая цепь",
				ko = "매달린 사슬",
				cn = "悬挂的锁链",
			},
		},
	
		[353231] = {
			readable = "Bonebound Chest",
			model = 3621781,
			text = {
				en = "Bonebound Chest",
				es = "Cofre vinculahueso",
				de = "Knochengebundene Kiste",
				fr = "Coffre os-lié",
				it = "Cassa Legaossa",
				pt = "Baú Ósseo",
				ru = "Укрепленный костью сундук",
				ko = "뼈결속 상자",
				cn = "骨缚宝箱",
			},
		},
	
		[353232] = {
			readable = "Bleakwood Chest",
			model = 3595030,
			text = {
				en = "Bleakwood Chest",
				es = "Cofre de leñogrís",
				de = "Kahlholzkiste",
				fr = "Coffre du bois morne",
				it = "Cassa di Legnocupo",
				pt = "Baú de Lenhavil",
				ru = "Сундук из мрачного дерева",
				ko = "귀신나무 상자",
				cn = "冷木宝箱",
			},
		},
	
		[353233] = {
			readable = "Enchanted Chest",
			model = 3522547,
			text = {
				en = "Enchanted Chest",
				es = "Cofre encantado",
				de = "Verzauberte Truhe",
				fr = "Coffre enchanté",
				it = "Cassa Incantata",
				pt = "Baú Encantado",
				ru = "Зачарованный сундук",
				ko = "마법에 걸린 상자",
				cn = "附魔宝箱",
			},
		},
	
		[353234] = {
			readable = "Gilded Chest",
			model = 3189119,
			text = {
				en = "Gilded Chest",
				es = "Cofre dorado",
				de = "Vergoldete Truhe",
				fr = "Coffre doré",
				it = "Forziere Dorato",
				pt = "Baú Dourado",
				ru = "Позолоченный сундук",
				ko = "황금빛 상자",
				cn = "镀金宝箱",
			},
		},
	
		[353237] = {
			readable = "Broken Mirror",
			model = 3095195,
			text = {
				en = "Broken Mirror",
				es = "Espejo roto",
				de = "Zerbrochener Spiegel",
				fr = "Miroir brisé",
				it = "Specchio Rotto",
				pt = "Espelho Quebrado",
				ru = "Разбитое зеркало",
				ko = "깨진 거울",
				cn = "残破的镜子",
			},
		},
	
		[353252] = {
			readable = "Silver Strongbox",
			model = 3189120,
			text = {
				en = "Silver Strongbox",
				es = "Caja fuerte de plata",
				de = "Silberne Schließkassette",
				fr = "Coffre renforcé en argent",
				it = "Forziere d'Argento",
				pt = "Caixa-forte de Prata",
				ru = "Серебряный сундучок",
				ko = "은 금고",
				cn = "白银保险箱",
			},
		},
	
		[353253] = {
			readable = "Tribute",
			model = 3009835,
			text = {
				en = "Tribute",
				es = "Tributo",
				de = "Tribut",
				fr = "Tribut",
				it = "Tributo",
				pt = "Tributo",
				ru = "Дар",
				ko = "공물",
				cn = "供品",
			},
		},
	
		[353258] = {
			readable = "Transport Pad",
			model = 3159129,
			text = {
				en = "Transport Pad",
				es = "Plataforma de transporte",
				de = "Transportplattform",
				fr = "Plateforme de transport",
				it = "Piattaforma di Trasporto",
				pt = "Plataforma de Transporte",
				ru = "Телепортационная платформа",
				ko = "순간이동 장치",
				cn = "传送器",
			},
		},
	
		[353259] = {
			readable = "Transport Pad",
			model = 3159129,
			text = {
				en = "Transport Pad",
				es = "Plataforma de transporte",
				de = "Transportplattform",
				fr = "Plateforme de transport",
				it = "Piattaforma di Trasporto",
				pt = "Plataforma de Transporte",
				ru = "Телепортационная платформа",
				ko = "순간이동 장치",
				cn = "传送器",
			},
		},
	
		[353305] = {
			readable = "Stonebreaker Mallet",
			model = 1053461,
			text = {
				en = "Stonebreaker Mallet",
				es = "Marra rompepiedras",
				de = "Steinbrecherhammer",
				fr = "Maillet brise-pierres",
				it = "Mazzuolo di Spaccapietra",
				pt = "Marreta Quebrapedra",
				ru = "Молот камнедробителя",
				ko = "바위분쇄 나무망치",
				cn = "碎石者之锤",
			},
		},
	
		[353306] = {
			readable = "Decayed Husk",
			model = 3033926,
			text = {
				en = "Decayed Husk",
				es = "Caparazón deteriorado",
				de = "Verrottete Hülle",
				fr = "Bogue putréfiée",
				it = "Guscio Decomposto",
				pt = "Carcaça Deteriorada",
				ru = "Разлагающаяся оболочка",
				ko = "부패한 껍데기",
				cn = "腐烂的躯壳",
			},
		},
	
		[353314] = {
			readable = "Silver Strongbox",
			model = 3189120,
			text = {
				en = "Silver Strongbox",
				es = "Caja fuerte de plata",
				de = "Silberne Schließkassette",
				fr = "Coffre renforcé en argent",
				it = "Forziere d'Argento",
				pt = "Caixa-forte de Prata",
				ru = "Серебряный сундучок",
				ko = "은 금고",
				cn = "白银保险箱",
			},
		},
	
		[353321] = {
			readable = "Tribute",
			model = 3009835,
			text = {
				en = "Tribute",
				es = "Tributo",
				de = "Tribut",
				fr = "Tribut",
				it = "Tributo",
				pt = "Tributo",
				ru = "Дар",
				ko = "공물",
				cn = "供品",
			},
		},
	
		[353323] = {
			readable = "Decayed Husk",
			model = 3033926,
			text = {
				en = "Decayed Husk",
				es = "Caparazón deteriorado",
				de = "Verrottete Hülle",
				fr = "Bogue putréfiée",
				it = "Guscio Decomposto",
				pt = "Carcaça Deteriorada",
				ru = "Разлагающаяся оболочка",
				ko = "부패한 껍데기",
				cn = "腐烂的躯壳",
			},
		},
	
		[353324] = {
			readable = "Decayed Husk",
			model = 3033926,
			text = {
				en = "Decayed Husk",
				es = "Caparazón deteriorado",
				de = "Verrottete Hülle",
				fr = "Bogue putréfiée",
				it = "Guscio Decomposto",
				pt = "Carcaça Deteriorada",
				ru = "Разлагающаяся оболочка",
				ko = "부패한 껍데기",
				cn = "腐烂的躯壳",
			},
		},
	
		[353325] = {
			readable = "Silver Strongbox",
			model = 3189120,
			text = {
				en = "Silver Strongbox",
				es = "Caja fuerte de plata",
				de = "Silberne Schließkassette",
				fr = "Coffre renforcé en argent",
				it = "Forziere d'Argento",
				pt = "Caixa-forte de Prata",
				ru = "Серебряный сундучок",
				ko = "은 금고",
				cn = "白银保险箱",
			},
		},
	
		[353326] = {
			readable = "Decayed Husk",
			model = 3033926,
			text = {
				en = "Decayed Husk",
				es = "Caparazón deteriorado",
				de = "Verrottete Hülle",
				fr = "Bogue putréfiée",
				it = "Guscio Decomposto",
				pt = "Carcaça Deteriorada",
				ru = "Разлагающаяся оболочка",
				ko = "부패한 껍데기",
				cn = "腐烂的躯壳",
			},
		},
	
		[353327] = {
			readable = "Decayed Husk",
			model = 3033926,
			text = {
				en = "Decayed Husk",
				es = "Caparazón deteriorado",
				de = "Verrottete Hülle",
				fr = "Bogue putréfiée",
				it = "Guscio Decomposto",
				pt = "Carcaça Deteriorada",
				ru = "Разлагающаяся оболочка",
				ko = "부패한 껍데기",
				cn = "腐烂的躯壳",
			},
		},
	
		[353328] = {
			readable = "Tribute",
			model = 3009835,
			text = {
				en = "Tribute",
				es = "Tributo",
				de = "Tribut",
				fr = "Tribut",
				it = "Tributo",
				pt = "Tributo",
				ru = "Дар",
				ko = "공물",
				cn = "供品",
			},
		},
	
		[353329] = {
			readable = "Faerie Stash",
			model = 3033637,
			text = {
				en = "Faerie Stash",
				es = "Alijo de hada",
				de = "Feenvorrat",
				fr = "Planque féerique",
				it = "Scorte dei Silfidi",
				pt = "Depósito das Fadas",
				ru = "Тайник пикси",
				ko = "페어리 보관함",
				cn = "妖精藏匿物",
			},
		},
	
		[353330] = {
			readable = "Faerie Stash",
			model = 3033637,
			text = {
				en = "Faerie Stash",
				es = "Alijo de hada",
				de = "Feenvorrat",
				fr = "Planque féerique",
				it = "Scorte dei Silfidi",
				pt = "Depósito das Fadas",
				ru = "Тайник пикси",
				ko = "페어리 보관함",
				cn = "妖精藏匿物",
			},
		},
	
		[353331] = {
			readable = "Faerie Stash",
			model = 3033637,
			text = {
				en = "Faerie Stash",
				es = "Alijo de hada",
				de = "Feenvorrat",
				fr = "Planque féerique",
				it = "Scorte dei Silfidi",
				pt = "Depósito das Fadas",
				ru = "Тайник пикси",
				ko = "페어리 보관함",
				cn = "妖精藏匿物",
			},
		},
	
		[353332] = {
			readable = "Faerie Stash",
			model = 3033637,
			text = {
				en = "Faerie Stash",
				es = "Alijo de hada",
				de = "Feenvorrat",
				fr = "Planque féerique",
				it = "Scorte dei Silfidi",
				pt = "Depósito das Fadas",
				ru = "Тайник пикси",
				ko = "페어리 보관함",
				cn = "妖精藏匿物",
			},
		},
	
		[353333] = {
			readable = "Faerie Stash",
			model = 3033637,
			text = {
				en = "Faerie Stash",
				es = "Alijo de hada",
				de = "Feenvorrat",
				fr = "Planque féerique",
				it = "Scorte dei Silfidi",
				pt = "Depósito das Fadas",
				ru = "Тайник пикси",
				ko = "페어리 보관함",
				cn = "妖精藏匿物",
			},
		},
	
		[353336] = {
			readable = "Secret Treasure",
			model = 3597238,
			text = {
				en = "Secret Treasure",
				es = "Tesoro secreto",
				de = "Geheimer Schatz",
				fr = "Trésor secret",
				it = "Tesoro Segreto",
				pt = "Tesouro Secreto",
				ru = "Спрятанное сокровище",
				ko = "비밀 보물",
				cn = "秘密财宝",
			},
		},
	
		[353340] = {
			readable = "Dusty Book",
			model = 3533100,
			text = {
				en = "Dusty Book",
				es = "Libro polvoriento",
				de = "Staubiges Buch",
				fr = "Livre poussiéreux",
				it = "Libro Impolverato",
				pt = "Livro Empoeirado",
				ru = "Пыльная книга",
				ko = "먼지투성이 책",
				cn = "积尘之书",
			},
		},
	
		[353362] = {
			readable = "Flickering Portrait",
			model = 3533102,
			text = {
				en = "Flickering Portrait",
				es = "Retrato parpadeante",
				de = "Flackerndes Porträt",
				fr = "Portrait vacillant",
				it = "Ritratto Tremolante",
				pt = "Retrato Tremeluzente",
				ru = "Мерцающий портрет",
				ko = "명멸하는 초상화",
				cn = "做小动作的肖像",
			},
		},
	
		[353363] = {
			readable = "Hidden Lever",
			model = 3229892,
			text = {
				en = "Hidden Lever",
				es = "Palanca oculta",
				de = "Versteckter Hebel",
				fr = "Levier caché",
				it = "Leva Nascosta",
				pt = "Alavanca Escondida",
				ru = "Скрытый рычаг",
				ko = "숨겨진 지렛대",
				cn = "隐藏的拉杆",
			},
		},
	
		[353364] = {
			readable = "Hidden Lever",
			model = 3229892,
			text = {
				en = "Hidden Lever",
				es = "Palanca oculta",
				de = "Versteckter Hebel",
				fr = "Levier caché",
				it = "Leva Nascosta",
				pt = "Alavanca Escondida",
				ru = "Скрытый рычаг",
				ko = "숨겨진 지렛대",
				cn = "隐藏的拉杆",
			},
		},
	
		[353365] = {
			readable = "Exit",
			model = 1352476,
			text = {
				en = "Exit",
				es = "Salida",
				de = "Ausgang",
				fr = "Quitter",
				it = "Uscita",
				pt = "Saída",
				ru = "Выйти",
				ko = "출구",
				cn = "退出",
			},
		},
	
		[353366] = {
			readable = "Exit",
			model = 1352476,
			text = {
				en = "Exit",
				es = "Salida",
				de = "Ausgang",
				fr = "Quitter",
				it = "Uscita",
				pt = "Saída",
				ru = "Выйти",
				ko = "출구",
				cn = "退出",
			},
		},
	
		[353367] = {
			readable = "Exit",
			model = 1352476,
			text = {
				en = "Exit",
				es = "Salida",
				de = "Ausgang",
				fr = "Quitter",
				it = "Uscita",
				pt = "Saída",
				ru = "Выйти",
				ko = "출구",
				cn = "退出",
			},
		},
	
		[353371] = {
			readable = "Censer of Discipline",
			model = 3073167,
			text = {
				en = "Censer of Discipline",
			},
		},
	
		[353372] = {
			readable = "Censer of Service",
			model = 3073167,
			text = {
				en = "Censer of Service",
			},
		},
	
		[353373] = {
			readable = "Censer of Faith",
			model = 3073167,
			text = {
				en = "Censer of Faith",
			},
		},
	
		[353375] = {
			readable = "Censer of Spirit",
			model = 3073167,
			text = {
				en = "Censer of Spirit",
			},
		},
	
		[353379] = {
			readable = "Crest of Ascension",
			model = 3492566,
			text = {
				en = "Crest of Ascension",
				es = "Cresta de ascensión",
				de = "Emblem des Aufstiegs",
				fr = "Écu d’Ascension",
				it = "Emblema dell'Ascensione",
				pt = "Brasão da Ascensão",
				ru = "Мастерская Перерождения",
				ko = "승천의 문장",
				cn = "晋升之巅",
			},
		},
	
		[353380] = {
			readable = "Halis's Lunch Pail",
			model = 969764,
			text = {
				en = "Halis's Lunch Pail",
				es = "Cubo de comida de Halis",
				de = "Halis' Henkelmann",
				fr = "Casse-croûte d’Halis",
				it = "Cestino del Pranzo di Halis",
				pt = "Lancheira de Halis",
				ru = "Бадья с завтраком Халиса",
				ko = "할리스의 도시락",
				cn = "哈利斯的午餐桶",
			},
		},
	
		[353381] = {
			readable = "OGRaid_Alarm_01",
			model = 895892,
			text = {
				en = "OGRaid_Alarm_01",
			},
		},
	
		[353402] = {
			readable = "Cage",
			model = 2981872,
			text = {
				en = "Cage",
				es = "Jaula",
				de = "Käfig",
				it = "Gabbia",
				pt = "Jaula",
				ru = "Клетка",
				ko = "우리",
				cn = "牢笼",
			},
		},
	
		[353403] = {
			readable = "Cage",
			model = 2981872,
			text = {
				en = "Cage",
				es = "Jaula",
				de = "Käfig",
				it = "Gabbia",
				pt = "Jaula",
				ru = "Клетка",
				ko = "우리",
				cn = "牢笼",
			},
		},
	
		[353405] = {
			readable = "Lid",
			model = 3015674,
			text = {
				en = "Lid",
				es = "Tapa",
				de = "Deckel",
				fr = "Couvercle",
				it = "Coperchio",
				pt = "Tampa",
				ru = "Крышка",
				ko = "뚜껑",
				cn = "盖子",
			},
		},
	
		[353410] = {
			readable = "Lid",
			model = 3015674,
			text = {
				en = "Lid",
				es = "Tapa",
				de = "Deckel",
				fr = "Couvercle",
				it = "Coperchio",
				pt = "Tampa",
				ru = "Крышка",
				ko = "뚜껑",
				cn = "盖子",
			},
		},
	
		[353411] = {
			readable = "Lid",
			model = 3015674,
			text = {
				en = "Lid",
				es = "Tapa",
				de = "Deckel",
				fr = "Couvercle",
				it = "Coperchio",
				pt = "Tampa",
				ru = "Крышка",
				ko = "뚜껑",
				cn = "盖子",
			},
		},
	
		[353419] = {
			readable = "Missing Eyes",
			model = 669526,
			text = {
				en = "Missing Eyes",
				es = "Ojos desaparecidos",
				de = "Fehlende Augen",
				fr = "Yeux manquants",
				it = "Occhi Mancanti",
				pt = "Olhos Perdidos",
				ru = "Пропавшие глаза",
				ko = "사라진 눈",
				cn = "丢失的眼睛",
			},
		},
	
		[353420] = {
			readable = "Stone Altar",
			model = 3595750,
			text = {
				en = "Stone Altar",
				es = "Altar de piedra",
				de = "Steinaltar",
				fr = "Autel en pierre",
				it = "Altare di Pietra",
				pt = "Altar de Pedra",
				ru = "Каменный алтарь",
				ko = "바위 제단",
				cn = "岩石祭坛",
			},
		},
	
		[353472] = {
			readable = "Radiant Sword",
			model = 3590187,
			text = {
				en = "Radiant Sword",
				es = "Espada radiante",
				de = "Strahlendes Schwert",
				fr = "Épée radieuse",
				it = "Spada Radiosa",
				pt = "Espada Radiante",
				ru = "Сияющий меч",
				ko = "찬란한 검",
				cn = "光辉之剑",
			},
		},
	
		[353473] = {
			readable = "Missing Eyes",
			model = 669526,
			text = {
				en = "Missing Eyes",
				es = "Ojos desaparecidos",
				de = "Fehlende Augen",
				fr = "Yeux manquants",
				it = "Occhi Mancanti",
				pt = "Olhos Perdidos",
				ru = "Пропавшие глаза",
				ko = "사라진 눈",
				cn = "丢失的眼睛",
			},
		},
	
		[353484] = {
			readable = "The Great Vault",
			icon = 3528423,
			model = 3308580,
			text = {
				en = "The Great Vault",
				es = "La gran cámara",
				de = "Die Große Schatzkammer",
				fr = "La grande chambre-forte",
				it = "La Gran Banca",
				pt = "Grande Cofre",
				ru = "Великое хранилище",
				ko = "위대한 금고",
				cn = "宏伟宝库",
			},
		},
	
		[353500] = {
			readable = "Silver Strongbox",
			model = 3189120,
			text = {
				en = "Silver Strongbox",
				es = "Caja fuerte de plata",
				de = "Silberne Schließkassette",
				fr = "Coffre renforcé en argent",
				it = "Forziere d'Argento",
				pt = "Caixa-forte de Prata",
				ru = "Серебряный сундучок",
				ko = "은 금고",
				cn = "白银保险箱",
			},
		},
	
		[353501] = {
			readable = "Tribute",
			model = 3009835,
			text = {
				en = "Tribute",
				es = "Tributo",
				de = "Tribut",
				fr = "Tribut",
				it = "Tributo",
				pt = "Tributo",
				ru = "Дар",
			},
		},
	
		[353503] = {
			readable = "Silver Strongbox",
			model = 3189120,
			text = {
				en = "Silver Strongbox",
				es = "Caja fuerte de plata",
				de = "Silberne Schließkassette",
				fr = "Coffre renforcé en argent",
				it = "Forziere d'Argento",
				pt = "Caixa-forte de Prata",
				ru = "Серебряный сундучок",
				ko = "은 금고",
				cn = "白银保险箱",
			},
		},
	
		[353504] = {
			readable = "Tribute",
			model = 3009835,
			text = {
				en = "Tribute",
				es = "Tributo",
				de = "Tribut",
				fr = "Tribut",
				it = "Tributo",
				pt = "Tributo",
				ru = "Дар",
				ko = "공물",
				cn = "供品",
			},
		},
	
		[353516] = {
			readable = "Silver Strongbox",
			model = 3189120,
			text = {
				en = "Silver Strongbox",
				es = "Caja fuerte de plata",
				de = "Silberne Schließkassette",
				fr = "Coffre renforcé en argent",
				it = "Forziere d'Argento",
				pt = "Caixa-forte de Prata",
				ru = "Серебряный сундучок",
				ko = "은 금고",
				cn = "白银保险箱",
			},
		},
	
		[353517] = {
			readable = "Tribute",
			model = 3009835,
			text = {
				en = "Tribute",
				es = "Tributo",
				de = "Tribut",
				fr = "Tribut",
				it = "Tributo",
				pt = "Tributo",
				ru = "Дар",
				ko = "공물",
				cn = "供品",
			},
		},
	
		[353518] = {
			readable = "Anima Gateway",
			model = 3159129,
			text = {
				en = "Anima Gateway",
				es = "Portal de ánima",
				de = "Animaportal",
				fr = "Porte d’anima",
				it = "Varco dell'Animum",
				pt = "Portal de Ânima",
				ru = "Врата анимы",
				ko = "령 관문",
				cn = "心能传送门",
			},
		},
	
		[353599] = {
			readable = "Cage",
			model = 2981872,
			text = {
				en = "Cage",
				es = "Jaula",
				de = "Käfig",
				it = "Gabbia",
				pt = "Jaula",
				ru = "Клетка",
				ko = "우리",
				cn = "牢笼",
			},
		},
	
		[353626] = {
			readable = "Locked Toolbox",
			model = 3638167,
			text = {
				en = "Locked Toolbox",
				es = "Caja de herramientas cerrada",
				de = "Verschlossener Werkzeugkasten",
				fr = "Boîte à outils verrouillée",
				it = "Cassetta degli Attrezzi Chiusa",
				pt = "Caixa de Ferramentas Trancada",
				ru = "Запертый ящик с инструментами",
				ko = "잠긴 공구상자",
				cn = "被锁住的工具箱",
			},
		},
	
		[353627] = {
			readable = "Battlefront Rations",
			model = 3638167,
			text = {
				en = "Battlefront Rations",
				es = "Raciones del frente",
				de = "Frontrationen",
				fr = "Rations de la Ligne de front",
				it = "Razioni del Fronte di Battaglia",
				pt = "Rações do Front de Batalha",
				ru = "Боевые рационы",
				ko = "최전선 전투식량",
				cn = "前线口粮",
			},
		},
	
		[353643] = {
			readable = "Silver Strongbox",
			model = 3189120,
			text = {
				en = "Silver Strongbox",
				es = "Caja fuerte de plata",
				de = "Silberne Schließkassette",
				fr = "Coffre renforcé en argent",
				it = "Forziere d'Argento",
				pt = "Caixa-forte de Prata",
				ru = "Серебряный сундучок",
				ko = "은 금고",
				cn = "白银保险箱",
			},
		},
	
		[353644] = {
			readable = "Tribute",
			model = 3009835,
			text = {
				en = "Tribute",
				es = "Tributo",
				de = "Tribut",
				fr = "Tribut",
				it = "Tributo",
				pt = "Tributo",
				ru = "Дар",
				ko = "공물",
				cn = "供品",
			},
		},
	
		[353645] = {
			readable = "Marileth's Journal",
			model = 3036573,
			text = {
				en = "Marileth's Journal",
				es = "Diario de Marileth",
				de = "Marileths Tagebuch",
				fr = "Journal de Marileth",
				it = "Diario di Marileth",
				pt = "Diário de Marileth",
				ru = "Дневник Марилета",
				ko = "메릴레트의 일지",
				cn = "马里莱斯的日志",
			},
		},
	
		[353650] = {
			readable = "Steward's Golden Chest",
			model = 3189119,
			text = {
				en = "Steward's Golden Chest",
				es = "Cofre dorado de administrador",
				de = "Goldene Truhe des Provosten",
				fr = "Coffre doré du régisseur",
				it = "Forziere Dorato del Factotum",
				pt = "Baú Dourado do Comissário",
				ru = "Золотой сундук распорядителя",
				ko = "청지기의 황금 궤짝",
				cn = "执事者的金色宝箱",
			},
		},
	
		[353652] = {
			readable = "Catalyst of Power",
			model = 3153293,
			text = {
				en = "Catalyst of Power",
				es = "Catalizador de poder",
				de = "Katalysator der Kraft",
				fr = "Catalyseur de pouvoir",
				it = "Catalizzatore del Potere",
				pt = "Catalisador do Poder",
				ru = "Катализатор силы",
				ko = "힘의 촉매",
				cn = "强能触媒",
			},
		},
	
		[353653] = {
			readable = "Catalyst of Renewal",
			model = 3153291,
			text = {
				en = "Catalyst of Renewal",
				es = "Catalizador de renovación",
				de = "Katalysator der Erneuerung",
				fr = "Catalyseur de renouveau",
				it = "Catalizzatore del Rinnovamento",
				pt = "Catalisador da Renovação",
				ru = "Катализатор обновления",
				ko = "소생의 촉매",
				cn = "复兴触媒",
			},
		},
	
		[353654] = {
			readable = "Catalyst of Might",
			model = 3153299,
			text = {
				en = "Catalyst of Might",
				es = "Catalizador de poderío",
				de = "Katalysator der Macht",
				fr = "Catalyseur de puissance",
				it = "Catalizzatore del Vigore",
				pt = "Catalisador da Força",
				ru = "Катализатор мощи",
				ko = "투지의 촉매",
				cn = "神威触媒",
			},
		},
	
		[353655] = {
			readable = "Sinstone Fragment",
			model = 655530,
			text = {
				en = "Sinstone Fragment",
				es = "Fragmento de piedra del pecado",
				de = "Sündensteinfragment",
				fr = "Fragment de stèle du vice",
				it = "Frammento di Pietra del Peccato",
				pt = "Fragmento de Pedra de Pecado",
				ru = "Фрагмент камня грехов",
				ko = "죄악석 조각",
				cn = "罪碑碎片",
			},
		},
	
		[353680] = {
			readable = "Fae Basket",
			model = 3395724,
			text = {
				en = "Fae Basket",
				es = "Cesta de sílfide",
				de = "Faekorb",
				fr = "Panier faë",
				it = "Cestino dei Silfi",
				pt = "Cesta Feéria",
				ru = "Корзина ночного народца",
				ko = "페이 바구니",
				cn = "法夜篮子",
			},
		},
	
		[353681] = {
			readable = "Lunarlight Pod",
			model = 3053305,
			text = {
				en = "Lunarlight Pod",
				es = "Vaina de luz lunar",
				de = "Mondlichtkapsel",
				fr = "Cosse de lumilune",
				it = "Baccello della Luce Lunare",
				pt = "Vagem de Lunalúmia",
				ru = "Стручок луноцвета",
				ko = "달빛 깍지",
				cn = "月光之荚",
			},
		},
	
		[353683] = {
			readable = "Lunarlight Pod",
			model = 3053305,
			text = {
				en = "Lunarlight Pod",
				es = "Vaina de luz lunar",
				de = "Mondlichtkapsel",
				fr = "Cosse de lumilune",
				it = "Baccello della Luce Lunare",
				pt = "Vagem de Lunalúmia",
				ru = "Стручок луноцвета",
				ko = "달빛 깍지",
				cn = "月光之荚",
			},
		},
	
		[353684] = {
			readable = "Lunarlight Pod",
			model = 3053305,
			text = {
				en = "Lunarlight Pod",
				es = "Vaina de luz lunar",
				de = "Mondlichtkapsel",
				fr = "Cosse de lumilune",
				it = "Baccello della Luce Lunare",
				pt = "Vagem de Lunalúmia",
				ru = "Стручок луноцвета",
				ko = "달빛 깍지",
				cn = "月光之荚",
			},
		},
	
		[353685] = {
			readable = "Lunarlight Pod",
			model = 3053305,
			text = {
				en = "Lunarlight Pod",
				es = "Vaina de luz lunar",
				de = "Mondlichtkapsel",
				fr = "Cosse de lumilune",
				it = "Baccello della Luce Lunare",
				pt = "Vagem de Lunalúmia",
				ru = "Стручок луноцвета",
				ko = "달빛 깍지",
				cn = "月光之荚",
			},
		},
	
		[353686] = {
			readable = "Lunarlight Pod",
			model = 3053305,
			text = {
				en = "Lunarlight Pod",
				es = "Vaina de luz lunar",
				de = "Mondlichtkapsel",
				fr = "Cosse de lumilune",
				it = "Baccello della Luce Lunare",
				pt = "Vagem de Lunalúmia",
				ru = "Стручок луноцвета",
				ko = "달빛 깍지",
				cn = "月光之荚",
			},
		},
	
		[353687] = {
			readable = "Broken Bell",
			model = 2839472,
			text = {
				en = "Broken Bell",
				es = "Campana rota",
				de = "Zerbrochene Glocke",
				fr = "Cloche brisée",
				it = "Campana Rotta",
				pt = "Sino Quebrado",
				ru = "Сломанный колокол",
				ko = "망가진 종",
				cn = "破损之钟",
			},
		},
	
		[353688] = {
			readable = "Broken Bell",
			model = 2839471,
			text = {
				en = "Broken Bell",
				es = "Campana rota",
				de = "Zerbrochene Glocke",
				fr = "Cloche brisée",
				it = "Campana Rotta",
				pt = "Sino Quebrado",
				ru = "Сломанный колокол",
				ko = "망가진 종",
				cn = "破损之钟",
			},
		},
	
		[353689] = {
			readable = "Broken Bell",
			model = 2839470,
			text = {
				en = "Broken Bell",
				es = "Campana rota",
				de = "Zerbrochene Glocke",
				fr = "Cloche brisée",
				it = "Campana Rotta",
				pt = "Sino Quebrado",
				ru = "Сломанный колокол",
				ko = "망가진 종",
				cn = "破损之钟",
			},
		},
	
		[353690] = {
			readable = "Skyward Bell",
			model = 2839472,
			text = {
				en = "Skyward Bell",
				es = "Campana celeste",
				de = "Himmelsglocke",
				fr = "Cloche aérienne",
				it = "Campana della Vetta",
				pt = "Sino Celestino",
				ru = "Небесный колокол",
				ko = "하늘맞이 종",
				cn = "天空之钟",
			},
		},
	
		[353691] = {
			readable = "Skyward Bell",
			model = 2839471,
			text = {
				en = "Skyward Bell",
				es = "Campana celeste",
				de = "Himmelsglocke",
				fr = "Cloche aérienne",
				it = "Campana della Vetta",
				pt = "Sino Celestino",
				ru = "Небесный колокол",
				ko = "하늘맞이 종",
				cn = "天空之钟",
			},
		},
	
		[353692] = {
			readable = "Super Happy Fun Ball",
			model = 969722,
			text = {
				en = "Super Happy Fun Ball",
				es = "Pelota superdivertida",
				de = "Megalustiger Spaßball",
				fr = "Ballon de joie enchanteresse",
				it = "Palla Super Divertente",
				pt = "Bola Divertida Superfeliz",
				ru = "Мяч радости и счастья",
				ko = "무척 신나는 놀이공",
				cn = "超级欢乐球",
			},
		},
	
		[353693] = {
			readable = "Creepy Doll",
			model = 3563973,
			text = {
				en = "Creepy Doll",
				es = "Muñeca espeluznante",
				de = "Unheimliche Puppe",
				fr = "Poupée effrayante",
				it = "Bambola Inquietante",
				pt = "Boneca Sinistra",
				ru = "Зловещая кукла",
				ko = "소름끼치는 인형",
				cn = "恐怖人偶",
			},
		},
	
		[353694] = {
			readable = "Bed Time Stories",
			model = 3448141,
			text = {
				en = "Bed Time Stories",
				es = "Cuentos para dormir",
				de = "Einschlafgeschichten",
				fr = "Contes de chevet",
				it = "Favole della Buonanotte",
				pt = "Histórias da Hora de Dormir",
				ru = "Истории на ночь",
				ko = "잠들기 전 옛날이야기",
				cn = "睡前故事",
			},
		},
	
		[353695] = {
			readable = "Drum",
			model = 3036168,
			text = {
				en = "Drum",
				es = "Tambor",
				de = "Trommel",
				fr = "Tambour",
				it = "Tamburo",
				pt = "Tambor",
				ru = "Барабан",
				ko = "북",
				cn = "鼓",
			},
		},
	
		[353696] = {
			readable = "Pan Flute",
			model = 3036154,
			text = {
				en = "Pan Flute",
				es = "Flauta de pan",
				de = "Panflöte",
				fr = "Flûte de pan",
				it = "Flauto di Pan",
				pt = "Siringe",
				ru = "Флейта Пана",
				ko = "팬플루트",
				cn = "排萧",
			},
		},
	
		[353697] = {
			readable = "Harp",
			model = 3036171,
			text = {
				en = "Harp",
				es = "Arpa",
				de = "Harfe",
				fr = "Harpe",
				it = "Arpa",
				pt = "Harpa",
				ru = "Арфа",
				ko = "하프",
				cn = "竖琴",
			},
		},
	
		[353751] = {
			readable = "Fae Basket",
			model = 3395724,
			text = {
				en = "Fae Basket",
				es = "Cesta de sílfide",
				de = "Faekorb",
				fr = "Panier faë",
				it = "Cestino dei Silfi",
				pt = "Cesta Feéria",
				ru = "Корзина ночного народца",
				ko = "페이 바구니",
				cn = "法夜篮子",
			},
		},
	
		[353760] = {
			readable = "Anima Catalyst",
			model = 3193914,
			text = {
				en = "Anima Catalyst",
				es = "Catalizador de ánima",
				de = "Animakatalysator",
				fr = "Catalyseur d’anima",
				it = "Catalizzatore d'Animum",
				pt = "Catalisador de Ânima",
				ru = "Катализатор анимы",
				ko = "령 촉매",
				cn = "心能触媒",
			},
		},
	
		[353763] = {
			readable = "Fae Basket",
			model = 3036102,
			text = {
				en = "Fae Basket",
				es = "Cesta de sílfide",
				de = "Faekorb",
				fr = "Panier faë",
				it = "Cestino dei Silfi",
				pt = "Cesta Feéria",
				ru = "Корзина ночного народца",
				ko = "페이 바구니",
				cn = "法夜篮子",
			},
		},
	
		[353765] = {
			readable = "Fae Basket",
			model = 3036101,
			text = {
				en = "Fae Basket",
				es = "Cesta de sílfide",
				de = "Faekorb",
				fr = "Panier faë",
				it = "Cestino dei Silfi",
				pt = "Cesta Feéria",
				ru = "Корзина ночного народца",
				ko = "페이 바구니",
				cn = "法夜篮子",
			},
		},
	
		[353768] = {
			readable = "Sacred Scroll",
			model = 3022977,
			text = {
				en = "Sacred Scroll",
				es = "Pergamino sagrado",
				de = "Heilige Schriftrolle",
				fr = "Parchemin sacré",
				it = "Pergamena Sacra",
				pt = "Pergaminho Sagrado",
				ru = "Священный свиток",
				ko = "신성한 두루마리",
				cn = "神圣卷轴",
			},
		},
	
		[353769] = {
			readable = "Dim Lunarlight Pod",
			model = 3053305,
			text = {
				en = "Dim Lunarlight Pod",
				es = "Vaina de luz lunar tenue",
				de = "Trübe Mondlichtkapsel",
				fr = "Cosse de lumilune terne",
				it = "Baccello della Luce Lunare Fioca",
				pt = "Vagem de Lunalúmia Mortiça",
				ru = "Тусклый стручок луноцвета",
				ko = "흐릿한 달빛 깍지",
				cn = "黯淡的月光之荚",
			},
		},
	
		[353770] = {
			readable = "Dim Lunarlight Pod",
			model = 3053305,
			text = {
				en = "Dim Lunarlight Pod",
				es = "Vaina de luz lunar tenue",
				de = "Trübe Mondlichtkapsel",
				fr = "Cosse de lumilune terne",
				it = "Baccello della Luce Lunare Fioca",
				pt = "Vagem de Lunalúmia Mortiça",
				ru = "Тусклый стручок луноцвета",
				ko = "흐릿한 달빛 깍지",
				cn = "黯淡的月光之荚",
			},
		},
	
		[353771] = {
			readable = "Dim Lunarlight Pod",
			model = 3053305,
			text = {
				en = "Dim Lunarlight Pod",
				es = "Vaina de luz lunar tenue",
				de = "Trübe Mondlichtkapsel",
				fr = "Cosse de lumilune terne",
				it = "Baccello della Luce Lunare Fioca",
				pt = "Vagem de Lunalúmia Mortiça",
				ru = "Тусклый стручок луноцвета",
				ko = "흐릿한 달빛 깍지",
				cn = "黯淡的月光之荚",
			},
		},
	
		[353772] = {
			readable = "Dim Lunarlight Pod",
			model = 3053305,
			text = {
				en = "Dim Lunarlight Pod",
				es = "Vaina de luz lunar tenue",
				de = "Trübe Mondlichtkapsel",
				fr = "Cosse de lumilune terne",
				it = "Baccello della Luce Lunare Fioca",
				pt = "Vagem de Lunalúmia Mortiça",
				ru = "Тусклый стручок луноцвета",
				ko = "흐릿한 달빛 깍지",
				cn = "黯淡的月光之荚",
			},
		},
	
		[353773] = {
			readable = "Dim Lunarlight Pod",
			model = 3053305,
			text = {
				en = "Dim Lunarlight Pod",
				es = "Vaina de luz lunar tenue",
				de = "Trübe Mondlichtkapsel",
				fr = "Cosse de lumilune terne",
				it = "Baccello della Luce Lunare Fioca",
				pt = "Vagem de Lunalúmia Mortiça",
				ru = "Тусклый стручок луноцвета",
				ko = "흐릿한 달빛 깍지",
				cn = "黯淡的月光之荚",
			},
		},
	
		[353791] = {
			readable = "Castle Strongbox",
			model = 3595030,
			text = {
				en = "Castle Strongbox",
				es = "Caja fuerte del castillo",
				de = "Schlosschließkassette",
				fr = "Coffre-fort du château",
				it = "Forziere del Castello",
				pt = "Caixa-forte do Castelo",
				ru = "Сундучок Замкового Предела",
				ko = "성채 금고",
				cn = "城堡保险箱",
			},
		},
	
		[353792] = {
			readable = "Village Strongbox",
			model = 3607335,
			text = {
				en = "Village Strongbox",
				es = "Caja fuerte de la aldea",
				de = "Dorfschließkassette",
				fr = "Coffre-fort du village",
				it = "Forziere del Villaggio",
				pt = "Caixa-forte da Vila",
				ru = "Сундучок Тихого Предела",
				ko = "촌락 금고",
				cn = "村庄保险箱",
			},
		},
	
		[353793] = {
			readable = "Parish Chest",
			model = 3607334,
			text = {
				en = "Parish Chest",
				es = "Cofre de la parroquia",
				de = "Gemeindetruhe",
				fr = "Coffre paroissial",
				it = "Cassa del Distretto",
				pt = "Baú da Paróquia",
				ru = "Сундучок молельщиков",
				ko = "교구 상자",
				cn = "教区宝箱",
			},
		},
	
		[353796] = {
			readable = "Reliquary of Remembrance",
			model = 3528929,
			text = {
				en = "Reliquary of Remembrance",
				es = "Relicario de recuerdos",
				de = "Reliquiar der Erinnerung",
				fr = "Reliquaire du souvenir",
				it = "Reliquiario della Rimembranza",
				pt = "Relicário da Lembrança",
				ru = "Реликварий воспоминаний",
				ko = "회고의 성물함",
				cn = "追忆圣匣",
			},
		},
	
		[353797] = {
			readable = "Stone Legion Supplies",
			model = 3607336,
			text = {
				en = "Stone Legion Supplies",
				es = "Suministros de la Legión Pétrea",
				de = "Vorräte der Steinlegion",
				fr = "Fournitures de la Légion de pierre",
				it = "Rifornimenti della Legione di Pietra",
				pt = "Suprimentos da Legião de Pedra",
				ru = "Припасы Каменного легиона",
				ko = "돌 군단 보급품",
				cn = "顽石军团补给品",
			},
		},
	
		[353798] = {
			readable = "Abandoned Belongings",
			model = 3154960,
			text = {
				en = "Abandoned Belongings",
				es = "Pertenencias abandonadas",
				de = "Zurückgelassene Habe",
				fr = "Effets abandonnés",
				it = "Beni Abbandonati",
				pt = "Pertences Abandonados",
				ru = "Брошенные пожитки",
				ko = "버려진 소지품",
				cn = "被抛弃的物品",
			},
		},
	
		[353799] = {
			readable = "Hopebreaker Pack",
			model = 3607333,
			text = {
				en = "Hopebreaker Pack",
				es = "Mochila de rompeesperanzas",
				de = "Hoffnungsbrecherbündel",
				fr = "Sac de brisespoir",
				it = "Zaino del Frangifede",
				pt = "Mochila de Quebrafé",
				ru = "Сумка сокрушителя надежды",
				ko = "희망파괴자의 배낭",
				cn = "灭愿者背包",
			},
		},
	
		[353807] = {
			readable = "Ancient Memorial",
			model = 3220603,
			text = {
				en = "Ancient Memorial",
				es = "Monumento antiguo",
				de = "Uraltes Denkmal",
				fr = "Monument ancien",
				it = "Monumento Antico",
				pt = "Memorial Ancestral",
				ru = "Древний мемориал",
				ko = "고대의 기념비",
				cn = "远古纪念物",
			},
		},
	
		[353817] = {
			readable = "Portal to ?",
			model = 1122549,
			text = {
				en = "Portal to ?",
				de = "Portal nach ?",
				fr = "Portail vers ?",
				it = "Portale per ?",
				ru = "Портал в неизвестность",
			},
		},
	
		[353819] = {
			readable = "Portal Out",
			model = 1122549,
			text = {
				en = "Portal Out",
				es = "Portal al exterior",
				de = "Portal nach draußen",
				fr = "Portail de sortie",
				it = "Portale d'Uscita",
				pt = "Portal de Saída",
				ru = "Портал на выход",
				ko = "바깥으로 통하는 차원문",
				cn = "外出传送门",
			},
		},
	
		[353822] = {
			readable = "Portal to Orgrimmar",
			model = 3613784,
			text = {
				en = "Portal to Orgrimmar",
				es = "Portal a Orgrimmar",
				de = "Portal nach Orgrimmar",
				fr = "Portail vers Orgrimmar",
				it = "Portale per Orgrimmar",
				pt = "Portal para Orgrimmar",
				ru = "Портал в Оргриммар",
				ko = "오그리마로 통하는 차원문",
				cn = "通往奥格瑞玛的传送门",
			},
		},
	
		[353823] = {
			readable = "Portal to Stormwind",
			model = 3613783,
			text = {
				en = "Portal to Stormwind",
				es = "Portal a Ventormenta",
				de = "Portal nach Sturmwind",
				fr = "Portail vers Hurlevent",
				it = "Portale per Roccavento",
				pt = "Portal para Ventobravo",
				ru = "Портал в Штормград",
				ko = "스톰윈드로 통하는 차원문",
				cn = "通往暴风城的传送门",
			},
		},
	
		[353824] = {
			readable = "Wild Hunt Horn",
			model = 3636396,
			text = {
				en = "Wild Hunt Horn",
				es = "Cuerno de la Cacería Salvaje",
				de = "Horn der Wilden Jagd",
				fr = "Cor de l’Hallali",
				it = "Corno della Caccia Selvaggia",
				pt = "Chifre da Caçada Selvagem",
				ru = "Рог Дикой Охоты",
				ko = "야생 사냥단 뿔피리",
				cn = "荒猎团号角",
			},
		},
	
		[353835] = {
			readable = "Anima Crystal Shard",
			model = 1345284,
			text = {
				en = "Anima Crystal Shard",
				es = "Fragmento de cristal de ánima",
				de = "Animakristallsplitter",
				fr = "Éclat de cristal d’anima",
				it = "Frammento di Cristallo d'Animum",
				pt = "Estilhaço de Cristal de Ânima",
				ru = "Осколок кристалла анимы",
				ko = "령 수정 파편",
				cn = "心能水晶碎片",
			},
		},
	
		[353848] = {
			readable = "Archival Parchment",
			model = 203430,
			text = {
				en = "Archival Parchment",
				es = "Papiro de archivo",
				de = "Archivierungspergament",
				fr = "Parchemin des archives",
				it = "Cartapecora dell'Archivio",
				pt = "Pergaminho Arquivístico",
				ru = "Архивный пергамент",
				cn = "档案羊皮纸",
			},
		},
	
		[353850] = {
			readable = "Forge Materials",
			model = 3189120,
			text = {
				en = "Forge Materials",
				es = "Materiales de forja",
				de = "Schmiedematerialien",
				fr = "Matériaux de forge",
				it = "Materiali della Forgia",
				pt = "Materiais da Forja",
				ru = "Материалы для кузни",
				ko = "제련소 재료",
				cn = "熔炉材料",
			},
		},
	
		[353861] = {
			readable = "Scroll of Teleportation",
			model = 3036652,
			text = {
				en = "Scroll of Teleportation",
				es = "Pergamino de teletransporte",
				de = "Schriftrolle der Teleportation",
				fr = "Parchemin de téléportation",
				it = "Pergamena del Teletrasporto",
				pt = "Pergaminho de Teleportação",
				ru = "Свиток телепортации",
				ko = "순간이동의 두루마리",
				cn = "传送卷轴",
			},
		},
	
		[353862] = {
			readable = "Scroll of Teleportation",
			model = 3036652,
			text = {
				en = "Scroll of Teleportation",
				es = "Pergamino de teletransporte",
				de = "Schriftrolle der Teleportation",
				fr = "Parchemin de téléportation",
				it = "Pergamena del Teletrasporto",
				pt = "Pergaminho de Teleportação",
				ru = "Свиток телепортации",
				ko = "순간이동의 두루마리",
				cn = "传送卷轴",
			},
		},
	
		[353867] = {
			readable = "Skyward Bell",
			model = 2839470,
			text = {
				en = "Skyward Bell",
				es = "Campana celeste",
				de = "Himmelsglocke",
				fr = "Cloche aérienne",
				it = "Campana della Vetta",
				pt = "Sino Celestino",
				ru = "Небесный колокол",
				ko = "하늘맞이 종",
				cn = "天空之钟",
			},
		},
	
		[353868] = {
			readable = "Hidden Hoard",
			model = 3023915,
			text = {
				en = "Hidden Hoard",
				es = "Tesoro oculto",
				de = "Versteckter Vorrat",
				fr = "Trésor caché",
				it = "Scorta Nascosta",
				pt = "Tesouro Escondido",
				ru = "Тайные сокровища",
				ko = "숨겨진 비축물",
				cn = "隐秘宝藏",
			},
		},
	
		[353869] = {
			readable = "Hidden Hoard",
			model = 3177104,
			text = {
				en = "Hidden Hoard",
				es = "Tesoro oculto",
				de = "Versteckter Vorrat",
				fr = "Trésor caché",
				it = "Scorta Nascosta",
				pt = "Tesouro Escondido",
				ru = "Тайные сокровища",
				ko = "숨겨진 비축물",
				cn = "隐秘宝藏",
			},
		},
	
		[353870] = {
			readable = "Hidden Hoard",
			model = 3023914,
			text = {
				en = "Hidden Hoard",
				es = "Tesoro oculto",
				de = "Versteckter Vorrat",
				fr = "Trésor caché",
				it = "Scorta Nascosta",
				pt = "Tesouro Escondido",
				ru = "Тайные сокровища",
				ko = "숨겨진 비축물",
				cn = "隐秘宝藏",
			},
		},
	
		[353871] = {
			readable = "Hidden Hoard",
			model = 3023913,
			text = {
				en = "Hidden Hoard",
				es = "Tesoro oculto",
				de = "Versteckter Vorrat",
				fr = "Trésor caché",
				it = "Scorta Nascosta",
				pt = "Tesouro Escondido",
				ru = "Тайные сокровища",
				ko = "숨겨진 비축물",
				cn = "隐秘宝藏",
			},
		},
	
		[353872] = {
			readable = "Hidden Hoard",
			model = 3095805,
			text = {
				en = "Hidden Hoard",
				es = "Tesoro oculto",
				de = "Versteckter Vorrat",
				fr = "Trésor caché",
				it = "Scorta Nascosta",
				pt = "Tesouro Escondido",
				ru = "Тайные сокровища",
				ko = "숨겨진 비축물",
				cn = "隐秘宝藏",
			},
		},
	
		[353873] = {
			readable = "Hidden Hoard",
			model = 3095806,
			text = {
				en = "Hidden Hoard",
				es = "Tesoro oculto",
				de = "Versteckter Vorrat",
				fr = "Trésor caché",
				it = "Scorta Nascosta",
				pt = "Tesouro Escondido",
				ru = "Тайные сокровища",
				ko = "숨겨진 비축물",
				cn = "隐秘宝藏",
			},
		},
	
		[353874] = {
			readable = "Animacone",
			model = 3158888,
			text = {
				en = "Animacone",
				es = "Bellota de ánima",
				de = "Animazapfen",
				fr = "Gland d’anima",
				it = "Cono d'Animum",
				pt = "Pinha-de-ânima",
				ru = "Анимашишка",
				ko = "령방울",
				cn = "心能球果",
			},
		},
	
		[353875] = {
			readable = "Test of Penitence",
			model = 3038198,
			text = {
				en = "Test of Penitence",
				es = "Prueba de penitencia",
				de = "Prüfung der Bußfertigkeit",
				fr = "Épreuve de pénitence",
				it = "Prova del Pentimento",
				pt = "Teste de Penitência",
				ru = "Испытание раскаянием",
				ko = "참회의 시험",
				cn = "忏悔测试",
			},
		},
	
		[353876] = {
			readable = "Virtue of Penitence",
			model = 2994771,
			text = {
				en = "Virtue of Penitence",
				es = "Virtud de penitencia",
				de = "Tugend der Bußfertigkeit",
				fr = "Vertu de pénitence",
				it = "Virtù del Pentimento",
				pt = "Virtude da Penitência",
				ru = "Добродетель раскаяния",
				ko = "참회의 미덕",
				cn = "忏悔美德",
			},
		},
	
		[353880] = {
			readable = "Burden of Penitence",
			model = 3073166,
			text = {
				en = "Burden of Penitence",
				es = "Carga de penitencia",
				de = "Bürde der Bußfertigkeit",
				fr = "Fardeau de pénitence",
				it = "Fardello del Pentimento",
				pt = "Fardo de Penitência",
				ru = "Бремя раскаяния",
				ko = "참회의 무게",
				cn = "忏悔重担",
			},
		},
	
		[353940] = {
			readable = "Gift of Vesiphone",
			model = 3189119,
			text = {
				en = "Gift of Vesiphone",
				es = "Ofrenda de Vesífone",
				de = "Gabe von Vesiphone",
				fr = "Don de Vésiphone",
				it = "Dono di Vesifone",
				pt = "Dádiva de Vesífona",
				ru = "Дар Весифоны",
				ko = "베시포네의 선물",
				cn = "薇茜弗涅之赐",
			},
		},
	
		[353941] = {
			readable = "Gift of Chyrus",
			model = 3189119,
			text = {
				en = "Gift of Chyrus",
				es = "Ofrenda de Chyrus",
				de = "Gabe von Chyrus",
				fr = "Don de Chyrus",
				it = "Dono di Chyrus",
				pt = "Dádiva de Quírus",
				ru = "Дар Хирона",
				ko = "카이러스의 선물",
				cn = "凯洛斯之赐",
			},
		},
	
		[353942] = {
			readable = "Gift of Agthia",
			model = 3189119,
			text = {
				en = "Gift of Agthia",
				es = "Ofrenda de Agthia",
				de = "Gabe von Agthia",
				fr = "Don d’Agthia",
				it = "Dono di Agthia",
				pt = "Dádiva de Agthia",
				ru = "Дар Агфии",
				ko = "아그티아의 선물",
				cn = "艾格茜娅之赐",
			},
		},
	
		[353943] = {
			readable = "Gift of Thenios",
			model = 3189119,
			text = {
				en = "Gift of Thenios",
				es = "Ofrenda de Thenios",
				de = "Gabe von Thenios",
				fr = "Don de Thénios",
				it = "Dono di Thenios",
				pt = "Dádiva de Thênios",
				ru = "Дар Тениоса",
				ko = "테니오스의 선물",
				cn = "塞尼厄斯之赐",
			},
		},
	
		[353944] = {
			readable = "Gift of Devos",
			model = 3189119,
			text = {
				en = "Gift of Devos",
				es = "Ofrenda de Devos",
				de = "Gabe von Devos",
				fr = "Don de Déva",
				it = "Dono di Devos",
				pt = "Dádiva de Devos",
				ru = "Дар Девии",
				ko = "데보스의 선물",
				cn = "德沃丝之赐",
			},
		},
	
		[353946] = {
			readable = "Spear of Kalliope",
			model = 3489755,
			text = {
				en = "Spear of Kalliope",
				es = "Lanza de Calíope",
				de = "Speer der Kalliope",
				fr = "Lance de Kalliope",
				it = "Lancia di Kalliope",
				pt = "Lança de Calíope",
				ru = "Копье Каллиопы",
				ko = "칼리오페의 창",
				cn = "卡莉娥佩之矛",
			},
		},
	
		[353947] = {
			readable = "Discarded Vial",
			model = 1305533,
			text = {
				en = "Discarded Vial",
				es = "Vial desechado",
				de = "Weggeworfene Phiole",
				fr = "Fiole abandonnée",
				it = "Fiala Scartata",
				pt = "Ampola Descartada",
				ru = "Выброшенный флакон",
				ko = "버려진 병",
				cn = "被丢弃的瓶子",
			},
		},
	
		[353948] = {
			readable = "Medallion of Desire",
			model = 3535749,
			text = {
				en = "Medallion of Desire",
				es = "Medallón de deseo",
				de = "Medaillon der Begierde",
				fr = "Médaillon du désir",
				it = "Medaglione del Desiderio",
				pt = "Medalhão do Desejo",
				ru = "Медальон Желания",
				ko = "욕망의 메달",
				cn = "欲望勋章",
			},
		},
	
		[353949] = {
			readable = "Medallion of Avarice",
			model = 3535749,
			text = {
				en = "Medallion of Avarice",
				es = "Medallón de avaricia",
				de = "Medaillon der Habsucht",
				fr = "Médaillon de l’avarice",
				it = "Medaglione dell'Avarizia",
				pt = "Medalhão da Avareza",
				ru = "Медальон Алчности",
				ko = "탐욕의 메달",
				cn = "贪婪勋章",
			},
		},
	
		[353950] = {
			readable = "Medallion of Envy",
			model = 3535749,
			text = {
				en = "Medallion of Envy",
				es = "Medallón de envidia",
				de = "Medaillon des Neids",
				fr = "Médaillon de l’envie",
				it = "Medaglione dell'Invidia",
				pt = "Medalhão da Inveja",
				ru = "Медальон Зависти",
				ko = "시기의 메달",
				cn = "嫉妒勋章",
			},
		},
	
		[353953] = {
			readable = "Medallion of Wrath",
			model = 3535749,
			text = {
				en = "Medallion of Wrath",
				es = "Medallón de cólera",
				de = "Medaillon des Zorns",
				fr = "Médaillon de la colère",
				it = "Medaglione dell'Ira",
				pt = "Medalhão da Ira",
				ru = "Медальон Гнева",
				ko = "격노의 메달",
				cn = "愤怒勋章",
			},
		},
	
		[353955] = {
			readable = "Stewart's Recipe Book",
			model = 3533100,
			text = {
				en = "Stewart's Recipe Book",
				es = "Libro de recetas de Stewart",
				de = "Supis Rezeptsammlung",
				fr = "Livre de recettes du régisseur",
				it = "Libro di Ricette di Toto",
				pt = "Livro de Receitas de Comissa",
				ru = "Книга рецептов Ясытя",
				ko = "스튜어트의 요리책",
				cn = "斯图尔特的食谱",
			},
		},
	
		[353959] = {
			readable = "Spear of Kalliope",
			model = 3489755,
			text = {
				en = "Spear of Kalliope",
				es = "Lanza de Calíope",
				de = "Speer der Kalliope",
				fr = "Lance de Kalliope",
				it = "Lancia di Kalliope",
				pt = "Lança de Calíope",
				ru = "Копье Каллиопы",
				ko = "칼리오페의 창",
				cn = "卡莉娥佩之矛",
			},
		},
	
		[353963] = {
			readable = "Bell of Purification",
			model = 2839471,
			text = {
				en = "Bell of Purification",
				es = "Campana de purificación",
				de = "Glocke der Läuterung",
				fr = "Cloche de purification",
				it = "Campana della Purificazione",
				pt = "Sino da Purificação",
				ru = "Колокол очищения",
				ko = "정화의 종",
				cn = "净化之钟",
			},
		},
	
		[353969] = {
			readable = "Anima-Infused Heartshroom",
			model = 3028729,
			text = {
				en = "Anima-Infused Heartshroom",
				es = "Champicardio imbuido de ánima",
				de = "Animaerfüllter Herzpilz",
				fr = "Cardinaire imprégné d’anima",
				it = "Cuorfungo Infuso d'Animum",
				pt = "Empachumelo Imbuído em Ânima",
				ru = "Насыщенный анимой сердцегриб",
				ko = "령이 주입된 심장버섯",
				cn = "灌注心能的心菇",
			},
		},
	
		[353975] = {
			readable = "Soul Mirror",
			model = 3070872,
			text = {
				en = "Soul Mirror",
				es = "Espejo de alma",
				de = "Seelenspiegel",
				fr = "Miroir des âmes",
				it = "Specchio dell'Anima",
				pt = "Espelho da Alma",
				ru = "Зеркало души",
				ko = "영혼 거울",
				cn = "灵魂之镜",
			},
		},
	
		[353980] = {
			readable = "9DU_NecroArena_DungeonRune_Lich01",
			model = 3603419,
			text = {
				en = "9DU_NecroArena_DungeonRune_Lich01",
			},
		},
	
		[353981] = {
			readable = "9DU_NecroArena_DungeonRune_Abom01",
			model = 3603417,
			text = {
				en = "9DU_NecroArena_DungeonRune_Abom01",
			},
		},
	
		[353982] = {
			readable = "9DU_NecroArena_DungeonRune_Warlord01",
			model = 3603418,
			text = {
				en = "9DU_NecroArena_DungeonRune_Warlord01",
			},
		},
	
		[353983] = {
			readable = "9DU_NecroArena_DungeonRune_Destroyed01",
			model = 3603420,
			text = {
				en = "9DU_NecroArena_DungeonRune_Destroyed01",
			},
		},
})
do ObjectDB[objectID] = objectData; end
