local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	
		[370078] = {
			readable = "Mawforged Weapon Rack",
			model = 3886942,
			text = {
				en = "Mawforged Weapon Rack",
				es = "Expositor de armas de Las Fauces",
				de = "Schlundgeschmiedeter Waffenständer",
				fr = "Râtelier d’armes antreforgées",
				it = "Rastrelliera delle Armi Forgiata nella Fauce",
				pt = "Cavalete de Armas Forjado na Gorja",
				ru = "Стойка с оружием Утробы",
				ko = "나락벼림 무기 선반",
				cn = "渊铸武器架",
			},
		},
	
		[370079] = {
			readable = "Mawforged Weapon Rack",
			model = 3886941,
			text = {
				en = "Mawforged Weapon Rack",
				es = "Expositor de armas de Las Fauces",
				de = "Schlundgeschmiedeter Waffenständer",
				fr = "Râtelier d’armes antreforgées",
				it = "Rastrelliera delle Armi Forgiata nella Fauce",
				pt = "Cavalete de Armas Forjado na Gorja",
				ru = "Стойка с оружием Утробы",
				ko = "나락벼림 무기 선반",
				cn = "渊铸武器架",
			},
		},
	
		[370080] = {
			readable = "Mawforged Weapon Rack",
			model = 3886943,
			text = {
				en = "Mawforged Weapon Rack",
				es = "Expositor de armas de Las Fauces",
				de = "Schlundgeschmiedeter Waffenständer",
				fr = "Râtelier d’armes antreforgées",
				it = "Rastrelliera delle Armi Forgiata nella Fauce",
				pt = "Cavalete de Armas Forjado na Gorja",
				ru = "Стойка с оружием Утробы",
				ko = "나락벼림 무기 선반",
				cn = "渊铸武器架",
			},
		},
	
		[370082] = {
			readable = "Abandoned Automa",
			model = 353152,
			text = {
				en = "Abandoned Automa",
				es = "Automa abandonado",
				de = "Zurückgelassenes Automa",
				fr = "Automa abandonné",
				it = "Automa Abbandonato",
				pt = "Automa Abandonado",
				ru = "Брошенный автом",
				ko = "버려진 자동기계",
				cn = "被遗弃的自动体",
			},
		},
	
		[370140] = {
			readable = "Damaged Jiro Stash",
			model = 4261540,
			text = {
				en = "Damaged Jiro Stash",
				es = "Alijo jiro dañado",
				de = "Beschädigter Behälter der Jiro",
				fr = "Butin jiro endommagé",
				it = "Scorte dei Jiro Danneggiate",
				pt = "Baú de Jiro Danificado",
				ru = "Поврежденный тайник джиро",
				ko = "손상된 지로 보관함",
				cn = "损坏的机若藏品",
			},
		},
	
		[370168] = {
			readable = "Portal to Oribos",
			model = 3850803,
			text = {
				en = "Portal to Oribos",
				es = "Portal a Oribos",
				de = "Portal nach Oribos",
				fr = "Portail vers Oribos",
				it = "Portale per Oribos",
				pt = "Portal para Oribos",
				ru = "Портал в Орибос",
				ko = "오리보스로 통하는 차원문",
				cn = "前往奥利波斯的传送门",
			},
		},
	
		[370177] = {
			readable = "Orb Fragments",
			model = 3923444,
			text = {
				en = "Orb Fragments",
				es = "Fragmentos de orbe",
				de = "Kugelfragmente",
				fr = "Fragments d’orbe",
				it = "Frammenti di Globo",
				pt = "Fragmentos de Orbe",
				ru = "Фрагменты сферы",
				ko = "보주 파편",
				cn = "宝珠碎片",
			},
		},
	
		[370178] = {
			readable = "Arrangement Terminal",
			model = 3923426,
			text = {
				en = "Arrangement Terminal",
				es = "Terminal de organización",
				de = "Anordnungsschaltpult",
				fr = "Terminal d’aménagement",
				it = "Terminale d'Arrangiamento",
				pt = "Terminal de Arranjos",
				ru = "Терминал распределения",
				ko = "정렬 단말기",
				cn = "编曲终端",
			},
		},
	
		[370332] = {
			readable = "Button",
			model = 4039277,
			text = {
				en = "Button",
				es = "Botón",
				de = "Knopf",
				fr = "Bouton",
				it = "Pulsante",
				pt = "Botão",
				ru = "Кнопка",
				ko = "단추",
				cn = "按钮",
			},
		},
	
		[370344] = {
			readable = "Cage",
			model = 3677218,
			text = {
				en = "Cage",
				es = "Jaula",
				de = "Käfig",
				it = "Gabbia",
				pt = "Jaula",
				ru = "Клетка",
				ko = "우리",
				cn = "牢笼",
			},
		},
	
		[370345] = {
			readable = "Cage",
			model = 3166684,
			text = {
				en = "Cage",
				es = "Jaula",
				de = "Käfig",
				it = "Gabbia",
				pt = "Jaula",
				ru = "Клетка",
				ko = "우리",
				cn = "牢笼",
			},
		},
	
		[370346] = {
			readable = "Stone Soup",
			model = 4236950,
			text = {
				en = "Stone Soup",
				es = "Sopa de piedras",
				de = "Steinsuppe",
				fr = "Soupe de cailloux",
				it = "Zuppa di Sassi",
				pt = "Sopa de Pedra",
				ru = "Каменный суп",
				ko = "돌멩이 수프",
				cn = "石头汤",
			},
		},
	
		[370352] = {
			readable = "Abandoned Automa",
			model = 353152,
			text = {
				en = "Abandoned Automa",
				es = "Automa abandonado",
				de = "Zurückgelassenes Automa",
				fr = "Automa abandonné",
				it = "Automa Abbandonato",
				pt = "Automa Abandonado",
				ru = "Брошенный автом",
				ko = "버려진 자동기계",
				cn = "被遗弃的自动体",
			},
		},
	
		[370353] = {
			readable = "Abandoned Automa",
			model = 353152,
			text = {
				en = "Abandoned Automa",
				es = "Automa abandonado",
				de = "Zurückgelassenes Automa",
				fr = "Automa abandonné",
				it = "Automa Abbandonato",
				pt = "Automa Abandonado",
				ru = "Брошенный автом",
				ko = "버려진 자동기계",
				cn = "被遗弃的自动体",
			},
		},
	
		[370388] = {
			readable = "Portal to Oribos",
			model = 3850803,
			text = {
				en = "Portal to Oribos",
				de = "Portal nach Oribos",
				ru = "Портал в Орибос",
			},
		},
	
		[370394] = {
			readable = "Hidden Equipment",
			model = 3450717,
			text = {
				en = "Hidden Equipment",
				es = "Equipo oculto",
				de = "Versteckte Ausrüstung",
				fr = "Équipement caché",
				it = "Equipaggiamento Nascosto",
				pt = "Equipamento Escondido",
				ru = "Спрятанное оборудование",
				ko = "숨겨진 장비",
				cn = "隐藏的装备",
			},
		},
	
		[370396] = {
			readable = "Precursor Placoderm School",
			model = 219406,
			text = {
				en = "Precursor Placoderm School",
				es = "Banco de placodermos ancestrales",
				de = "Ein Schwarm Urplacoderme",
				fr = "Banc de placodermes précurseurs",
				it = "Banco di Placodermi Precursori",
				pt = "Cardume de Placodermo Precursor",
				ru = "Косяк первородного плакодерма",
				ko = "선구의 판피어 떼",
				cn = "前体盾皮鱼群",
			},
		},
	
		[370397] = {
			readable = "Lush First Flower",
			model = 4218043,
			text = {
				en = "Lush First Flower",
				es = "Primera flor exuberante",
				de = "Üppige Erste Blume",
				fr = "Fondalée luxuriante",
				it = "Primo Fiore Rigoglioso",
				pt = "Primeira Flor Vistosa",
				ru = "Пышный первоцвет",
				ko = "무성한 태초의 꽃",
				cn = "繁茂的初蕊花",
			},
		},
	
		[370398] = {
			readable = "First Flower",
			model = 4080349,
			text = {
				en = "First Flower",
				es = "Primera flor",
				de = "Erste Blume",
				fr = "Fondalée",
				it = "Primo Fiore",
				pt = "Primeira Flor",
				ru = "Первоцвет",
				ko = "태초의 꽃",
				cn = "初蕊花",
			},
		},
	
		[370399] = {
			readable = "Rich Progenium Deposit",
			model = 4182225,
			text = {
				en = "Rich Progenium Deposit",
				es = "Depósito rico en progenio",
				de = "Reiches Progeniumvorkommen",
				fr = "Riche gisement de progénium",
				it = "Deposito Ricco di Progenio",
				pt = "Depósito de Progenium Abundante",
				ru = "Богатые залежи первостали",
				ko = "풍부한 창시석 광맥",
				cn = "富先磷矿脉",
			},
		},
	
		[370400] = {
			readable = "Progenium Deposit",
			model = 4182224,
			text = {
				en = "Progenium Deposit",
				es = "Depósito de progenio",
				de = "Progeniumvorkommen",
				fr = "Gisement de progénium",
				it = "Deposito di Progenio",
				pt = "Depósito de Progenium",
				ru = "Залежи первостали",
				ko = "창시석 광맥",
				cn = "先磷矿脉",
			},
		},
	
		[370401] = {
			readable = "Hidden Satchel",
			model = 3846062,
			text = {
				en = "Hidden Satchel",
				es = "Bolsa oculta",
				de = "Verstecktes Säckchen",
				fr = "Sacoche cachée",
				it = "Borsa Nascosta",
				pt = "Algibeira Escondida",
				ru = "Спрятанная сумка",
				ko = "숨겨진 주머니",
				cn = "隐藏的背包",
			},
		},
	
		[370402] = {
			readable = "Hidden Notes",
			model = 3836267,
			text = {
				en = "Hidden Notes",
				es = "Notas ocultas",
				de = "Versteckte Notizen",
				fr = "Notes cachées",
				it = "Note Nascoste",
				pt = "Anotações Escondidas",
				ru = "Спрятанные записи",
				ko = "숨겨진 기록",
				cn = "隐藏的字条",
			},
		},
	
		[370405] = {
			readable = "Orb of Transference",
			model = 4039278,
			text = {
				en = "Orb of Transference",
				es = "Orbe de transferencia",
				de = "Kugel der Übertragung",
				fr = "Orbe de transfert",
				it = "Globo del Trasferimento",
				pt = "Orbe da Transferência",
				ru = "Сфера Перенаправления",
				ko = "전이의 보주",
				cn = "转移宝珠",
			},
		},
	
		[370406] = {
			readable = "Orb of Transference",
			model = 4039278,
			text = {
				en = "Orb of Transference",
				es = "Orbe de transferencia",
				de = "Kugel der Übertragung",
				fr = "Orbe de transfert",
				it = "Globo del Trasferimento",
				pt = "Orbe da Transferência",
				ru = "Сфера Перенаправления",
				ko = "전이의 보주",
				cn = "转移宝珠",
			},
		},
	
		[370409] = {
			readable = "Slumbering Vault Lock",
			model = 3923426,
			text = {
				en = "Slumbering Vault Lock",
				es = "Cierre de la Cámara Durmiente",
				de = "Schloss des Schlummernden Gewölbes",
				fr = "Verrou du caveau Dormant",
				it = "Serratura della Cripta Dormiente",
				pt = "Tranca da Cripta Adormecida",
				ru = "Замок Дремлющего Хранилища",
				ko = "잠자는 금고 자물쇠",
				cn = "沉眠宝库之锁",
			},
		},
	
		[370412] = {
			readable = "Piled Rubble",
			model = 3937982,
			text = {
				en = "Piled Rubble",
				es = "Escombros apilados",
				de = "Aufgehäufte Trümmer",
				fr = "Décombres entassés",
				it = "Macerie Impilate",
				pt = "Destroços Empilhados",
				ru = "Груда обломков",
				ko = "쌓인 잔해",
				cn = "成堆的碎石",
			},
		},
	
		[370420] = {
			readable = "Piled Rubble",
			model = 3938541,
			text = {
				en = "Piled Rubble",
				es = "Escombros apilados",
				de = "Aufgehäufte Trümmer",
				fr = "Décombres entassés",
				it = "Macerie Impilate",
				pt = "Destroços Empilhados",
				ru = "Груда обломков",
				ko = "쌓인 잔해",
				cn = "成堆的碎石",
			},
		},
	
		[370421] = {
			readable = "Piled Rubble",
			model = 3937981,
			text = {
				en = "Piled Rubble",
				es = "Escombros apilados",
				de = "Aufgehäufte Trümmer",
				fr = "Décombres entassés",
				it = "Macerie Impilate",
				pt = "Destroços Empilhados",
				ru = "Груда обломков",
				ko = "쌓인 잔해",
				cn = "成堆的碎石",
			},
		},
	
		[370427] = {
			readable = "Conduction Remnant",
			model = 4039283,
			text = {
				en = "Conduction Remnant",
				es = "Remanente de conducción",
				de = "Leitungsüberrest",
				fr = "Vestige de conduction",
				it = "Residuo della Conduzione",
				pt = "Resquício de Condutividade",
				ru = "Обломок проводника",
				ko = "전도 잔해",
				cn = "传导残迹",
			},
		},
	
		[370449] = {
			readable = "Fractal Cypher A",
			model = 4201279,
			text = {
				en = "Fractal Cypher A",
				es = "Clave fractal A",
				de = "Fraktalchiffre A",
				fr = "Cryptogramme fractal A",
				it = "Codice Frattale A",
				pt = "Cifra Fractal A",
				ru = "Фрактальный шифр A",
				cn = "分形密文A",
			},
		},
	
		[370453] = {
			readable = "Neglected Conductor",
			model = 3923427,
			text = {
				en = "Neglected Conductor",
				es = "Conductor desatendido",
				de = "Vernachlässigter Leiter",
				fr = "Conduit délaissé",
				it = "Conduttore Trascurato",
				pt = "Condutor Negligenciado",
				ru = "Брошенный проводник",
				cn = "不起眼的导体",
			},
		},
	
		[370454] = {
			readable = "Neglected Conductor",
			model = 3923427,
			text = {
				en = "Neglected Conductor",
				es = "Conductor desatendido",
				de = "Vernachlässigter Leiter",
				fr = "Conduit délaissé",
				it = "Conduttore Trascurato",
				pt = "Condutor Negligenciado",
				ru = "Брошенный проводник",
				ko = "방치된 전도체",
				cn = "不起眼的导体",
			},
		},
	
		[370455] = {
			readable = "Neglected Conductor",
			model = 3923427,
			text = {
				en = "Neglected Conductor",
				es = "Conductor desatendido",
				de = "Vernachlässigter Leiter",
				fr = "Conduit délaissé",
				it = "Conduttore Trascurato",
				pt = "Condutor Negligenciado",
				ru = "Брошенный проводник",
				ko = "방치된 전도체",
				cn = "不起眼的导体",
			},
		},
	
		[370458] = {
			readable = "Mawsworn Cell",
			model = 3166684,
			text = {
				en = "Mawsworn Cell",
				es = "Celda jurafauces",
				de = "Schlundgebundene Zelle",
				fr = "Cellule antrelige",
				it = "Cella dei Giurafauce",
				pt = "Cela Górjura",
				ru = "Камера Верных Утробе",
				ko = "나락살이 감방",
				cn = "渊誓囚笼",
			},
		},
	
		[370466] = {
			readable = "Collected Concordances",
			model = 3923426,
			text = {
				en = "Collected Concordances",
				es = "Concordancias recogidas",
				de = "Gesammelte Konkordanzen",
				fr = "Harmoniques obtenus",
				it = "Indici Raccolti",
				pt = "Concordâncias Recolhidas",
				ru = "Свод конкордансов",
				ko = "수집한 색인",
				cn = "收集的索引台",
			},
		},
	
		[370467] = {
			readable = "Concordance Codex Dispenser",
			model = 4198154,
			text = {
				en = "Concordance Codex Dispenser",
				es = "Dispensador de códice de concordancias",
				de = "Konkordanzkodexausgabe",
				fr = "Distributeur de codex harmoniques",
				it = "Distributore di Codici di Indici",
				pt = "Distribuidor de Códices de Concordância",
				ru = "Терминал кодекса конкордансов",
				ko = "색인 전서 공급기",
				cn = "索引台法典分发器",
			},
		},
	
		[370469] = {
			readable = "Spectral Feed",
			model = 949217,
			text = {
				en = "Spectral Feed",
				es = "Pienso espectral",
				de = "Spektrales Futter",
				fr = "Céréales spectrales",
				it = "Nutrimento Spettrale",
				pt = "Alimento Espectral",
				ru = "Призрачный корм",
				cn = "幽魂饲料",
			},
		},
	
		[370492] = {
			readable = "Overloaded Protector",
			model = 353152,
			text = {
				en = "Overloaded Protector",
				es = "Protector sobrecargado",
				de = "Überladener Beschützer",
				fr = "Protecteur surchargé",
				it = "Protettore Sovraccaricato",
				pt = "Protetor Sobrecarregado",
				ru = "Перегруженный защитник",
				ko = "과부하된 수호병",
				cn = "过载的保护者",
			},
		},
	
		[370494] = {
			readable = "Toccatian Cache",
			model = 4248045,
			text = {
				en = "Toccatian Cache",
				es = "Alijo de tocata",
				de = "Toccatianische Truhe",
				fr = "Cache toccatienne",
				it = "Cassa Toccatiana",
				pt = "Baú Tocatiano",
				ru = "Токкатийский тайник",
				ko = "토카타 보관함",
				cn = "弹奏宝箱",
			},
		},
	
		[370495] = {
			readable = "Creation Catalyst Console",
			model = 3923426,
			text = {
				en = "Creation Catalyst Console",
				es = "Consola de catalizador de creación",
				de = "Schöpfungskatalysatorkonsole",
				fr = "Console de catalyseur de création",
				it = "Console del Catalizzatore della Creazione",
				pt = "Console de Catalisador de Criação",
				ru = "Консоль катализатора творения",
				ko = "창조의 촉매 장치",
				cn = "造物化生控制台",
			},
		},
	
		[370496] = {
			readable = "Rune Tile",
			model = 4196518,
			text = {
				en = "Rune Tile",
				es = "Baldosa rúnica",
				de = "Runenkachel",
				fr = "Dalle runique",
				it = "Piastrella di Rune",
				pt = "Quadrado Rúnico",
				ru = "Руническая плита",
				ko = "룬 벽돌바닥",
				cn = "符文地砖",
			},
		},
	
		[370497] = {
			readable = "Quadrangular Altar",
			model = 4223853,
			text = {
				en = "Quadrangular Altar",
				es = "Altar cuadrangular",
				de = "Viereckiger Altar",
				fr = "Autel quadrangulaire",
				it = "Altare Quadrangolare",
				pt = "Altar Quadrangular",
				ru = "Четырехугольный алтарь",
				ko = "사각 제단",
				cn = "四角之台",
			},
		},
	
		[370498] = {
			readable = "Triangular Altar",
			model = 4223854,
			text = {
				en = "Triangular Altar",
				es = "Altar triangular",
				de = "Dreieckiger Altar",
				fr = "Autel triangulaire",
				it = "Altare Triangolare",
				pt = "Altar Triangular",
				ru = "Треугольный алтарь",
				ko = "삼각 제단",
				cn = "三角之台",
			},
		},
	
		[370501] = {
			readable = "Quadrangular Object",
			model = 4224814,
			text = {
				en = "Quadrangular Object",
				es = "Objeto cuadrangular",
				de = "Viereckiges Objekt",
				fr = "Objet quadrangulaire",
				it = "Oggetto Quadrangolare",
				pt = "Objeto Quadrangular",
				ru = "Четырехугольный объект",
				ko = "사각 물체",
				cn = "四角物体",
			},
		},
	
		[370502] = {
			readable = "Triangular Object",
			model = 4224815,
			text = {
				en = "Triangular Object",
				es = "Objeto triangular",
				de = "Dreieckiges Objekt",
				fr = "Objet triangulaire",
				it = "Oggetto Triangolare",
				pt = "Objeto Triangular",
				ru = "Треугольный объект",
				ko = "삼각 물체",
				cn = "三角物体",
			},
		},
	
		[370505] = {
			readable = "Interior Locus Arrangement",
			model = 4081525,
			text = {
				en = "Interior Locus Arrangement",
				es = "Disposición del Enclave Interior",
				de = "Anordnung des Internus Locus",
				fr = "Agencement du locus intérieur",
				it = "Disposizione del Locus Interior",
				pt = "Arranjo de Lócus Interior",
				ru = "Изначальная конфигурация Локуса",
				ko = "내부 공간 정렬",
				cn = "内部位点指向",
			},
		},
	
		[370506] = {
			readable = "Locus Shift",
			model = 4224814,
			text = {
				en = "Locus Shift",
				es = "Cambio de enclave",
				de = "Locusverschiebung",
				fr = "Transfert de locus",
				it = "Cambio di Locus",
				pt = "Deslocamento de Lócus",
				ru = "Сдвиг Локуса",
				ko = "공간 변환",
				cn = "位点转换装置",
			},
		},
	
		[370507] = {
			readable = "Secundus Locus Arrangement",
			model = 4081534,
			text = {
				en = "Secundus Locus Arrangement",
				es = "Disposición del Enclave Secundus",
				de = "Anordnung des Secundus Locus",
				fr = "Agencement du locus secundus",
				it = "Disposizione del Locus Secundus",
				pt = "Arranjo de Lócus Secundus",
				ru = "Вторая конфигурация Локуса",
				ko = "제2의 공간 정렬",
				cn = "第二位点指向",
			},
		},
	
		[370508] = {
			readable = "Tertius Locus Arrangement",
			model = 4081528,
			text = {
				en = "Tertius Locus Arrangement",
				es = "Disposición del Enclave Tertius",
				de = "Anordnung des Tertius Locus",
				fr = "Agencement du locus tertius",
				it = "Disposizione del Locus Tertius",
				pt = "Arranjo de Lócus Tertius",
				ru = "Третья конфигурация Локуса",
				ko = "제3의 공간 정렬",
				cn = "第三位点指向",
			},
		},
	
		[370512] = {
			readable = "Ultimus Locus Arrangement",
			model = 4081536,
			text = {
				en = "Ultimus Locus Arrangement",
				es = "Disposición del Enclave Ultimus",
				de = "Anordnung des Ultimus Locus",
				fr = "Agencement du locus ultimus",
				it = "Disposizione del Locus Ultimus",
				pt = "Arranjo de Lócus Ultimus",
				ru = "Финальная конфигурация Локуса",
				ko = "궁극의 공간 정렬",
				cn = "最终位点指向",
			},
		},
	
		[370514] = {
			readable = "Orb Fragments",
			model = 3923443,
			text = {
				en = "Orb Fragments",
				es = "Fragmentos de orbe",
				de = "Kugelfragmente",
				fr = "Fragments d’orbe",
				it = "Frammenti di Globo",
				pt = "Fragmentos de Orbe",
				ru = "Фрагменты сферы",
				ko = "보주 파편",
				cn = "宝珠碎片",
			},
		},
	
		[370515] = {
			readable = "Orb Fragments",
			model = 3923445,
			text = {
				en = "Orb Fragments",
				es = "Fragmentos de orbe",
				de = "Kugelfragmente",
				fr = "Fragments d’orbe",
				it = "Frammenti di Globo",
				pt = "Fragmentos de Orbe",
				ru = "Фрагменты сферы",
				ko = "보주 파편",
				cn = "宝珠碎片",
			},
		},
	
		[370526] = {
			readable = "Rations",
			model = 3917383,
			text = {
				en = "Rations",
				de = "Verpflegung",
				pt = "Rações",
				ru = "Довольствие",
				ko = "휴대식량 상자",
			},
		},
	
		[370527] = {
			readable = "Weapon Rack",
			model = 4216979,
			text = {
				en = "Weapon Rack",
				de = "Waffenständer",
				fr = "Râtelier d’armes",
				pt = "Cavalete de Armas",
				ru = "Оружейная стойка",
				ko = "무기 선반",
			},
		},
	
		[370528] = {
			readable = "Crate of Warscale Armor",
			model = 3917383,
			text = {
				en = "Crate of Warscale Armor",
				de = "Kiste mit Kriegsschuppenrüstungen",
				fr = "Caisse d’armure écaille-de-guerre",
				ru = "Ящик с чешуйчатыми доспехами",
				ko = "전쟁비늘 방어구 상자",
			},
		},
})
do ObjectDB[objectID] = objectData; end
