local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	
		[243009] = {
			readable = "Horn of the Siren",
			model = 202496,
			text = {
				en = "Horn of the Siren",
				es = "Cuerno de la sirena",
				de = "Horn der Sirene",
				fr = "Cor des sirènes",
				it = "Corno della Sirena",
				pt = "Chifre da Sirena",
				ru = "Рог сирены",
				ko = "세이렌의 뿔피리",
				cn = "海妖号角",
			},
		},
	
		[243045] = {
			readable = "Leyweavers' Dyeing Tub",
			model = 1309272,
			text = {
				en = "Leyweavers' Dyeing Tub",
				es = "Tina para teñir de tejeley",
				de = "Färbewanne des Leywebers",
				fr = "Cuve de teinture de telluriste",
				it = "Vasca di Tintura dei Tessifaglie",
				pt = "Tubo de Pigmento do Tecelão de Meridianos",
				ru = "Корыто ткача-чародея",
				ko = "지맥직공의 염료 수조",
				cn = "织魔者的染料桶",
			},
		},
	
		[243046] = {
			readable = "Leyweavers' Finishing Table",
			model = 1361711,
			text = {
				en = "Leyweavers' Finishing Table",
				es = "Mesa de retoques de tejeley",
				de = "Sticktischchen des Leywebers",
				fr = "Table de finition de telluriste",
				it = "Tavolo per Finiture dei Tessifaglie",
				pt = "Mesa de Acabamento do Tecelão de Meridianos",
				ru = "Стол ткача-чародея",
				ko = "지맥직공의 마무리 탁자",
				cn = "织魔者的精加工台",
			},
		},
	
		[243048] = {
			readable = "Leyweavers' Amber Dye",
			model = 1360809,
			text = {
				en = "Leyweavers' Amber Dye",
				es = "Tinte ámbar de tejeley",
				de = "Bernsteingelbes Färbemittel des Leywebers",
				fr = "Teinture ambrée de telluriste",
				it = "Tintura d'Ambra dei Tessifaglie",
				pt = "Pigmento de Âmbar do Tecelão de Meridianos",
				ru = "Янтарная краска ткача-чародея",
				ko = "지맥직공의 호박색 염료",
				cn = "织魔者的琥珀染料",
			},
		},
	
		[243049] = {
			readable = "Leyweavers' Silkweave",
			model = 198124,
			text = {
				en = "Leyweavers' Silkweave",
				es = "Filoseda de tejeley",
				de = "Seidengewebe des Leywebers",
				fr = "Soie tissée de telluriste",
				it = "Fildiseta dei Tessifaglie",
				pt = "Tramasseda do Tecelão de Meridianos",
				ru = "Шелковое полотно ткача-чародея",
				ko = "지맥직공의 비단매듭 옷감",
				cn = "织魔者的丝纹布",
			},
		},
	
		[243050] = {
			readable = "Leyweavers' Sharpened Spritethorns",
			model = 1353536,
			text = {
				en = "Leyweavers' Sharpened Spritethorns",
				es = "Espinas de duende afiladas de tejeley",
				de = "Geschärfte Waldgeistdornen des Leywebers",
				fr = "Lutinépines aiguisées de telluriste",
				it = "Spinette Affilate dei Tessifaglie",
				pt = "Duendespinhos Afiados do Tecelão de Meridianos",
				ru = "Наточенные шипы лесного духа ткача-чародея",
				ko = "지맥직공의 뾰족하게 만든 요마가시",
				cn = "织魔者的锋利林精棘针",
			},
		},
	
		[243052] = {
			readable = "Leyweavers' Runic Catgut",
			model = 950801,
			text = {
				en = "Leyweavers' Runic Catgut",
				es = "Tripa rúnica de tejeley",
				de = "Runenfaden aus Katgut des Leywebers",
				fr = "Boyau runique de telluriste",
				it = "Crine Runico dei Tessifaglie",
				pt = "Corda de Tripas Rúnica do Tecelão de Meridianos",
				ru = "Рунное волокно ткача-чародея",
				ko = "지맥직공의 룬 무늬 장선",
				cn = "织魔者的符文肠线",
			},
		},
	
		[243089] = {
			readable = "Kur'talos Ravencrest's Sigil",
			model = 1240767,
			text = {
				en = "Kur'talos Ravencrest's Sigil",
				es = "Sigilo de Kur'talos Cresta Cuervo",
				de = "Siegel von Kur'talos Rabenkrone",
				fr = "Cachet de Kur’talos Corvaltus",
				it = "Sigillo di Kur'talos Crinocorvo",
				pt = "Signo de Kur'talos Cristacorvo",
				ru = "Знамя Кур'талоса Гребня Ворона",
				ko = "쿠르탈로스 레이븐크레스트의 인장",
				cn = "库塔洛斯·拉文凯斯的旗帜",
			},
		},
	
		[243099] = {
			readable = "Vibrating Arcane Trap",
			model = 201014,
			text = {
				en = "Vibrating Arcane Trap",
				es = "Trampa Arcana vibrante",
				de = "Vibrierende arkane Falle",
				fr = "Piège arcanique vibrant",
				it = "Trappola Arcana Vibrante",
				pt = "Armadilha Arcana Vibrando",
				ru = "Вибрирующая чародейская ловушка",
				ko = "진동하는 비전 함정",
				cn = "魔力震荡陷阱",
			},
		},
	
		[243205] = {
			readable = "Inferno Shot",
			model = 1020152,
			text = {
				en = "Inferno Shot",
				es = "Disparo inferno",
				de = "Infernogeschoss",
				fr = "Balle infernale",
				it = "Colpo Infernale",
				pt = "Tiro Infernal",
				ru = "Инфернальный снаряд",
				ko = "지옥불 탄환",
				cn = "地狱火炮弹",
			},
		},
	
		[243215] = {
			readable = "Black Rook Cage",
			model = 195417,
			text = {
				en = "Black Rook Cage",
				es = "Jaula de Grajo Negro",
				de = "Käfig der Rabenwehr",
				fr = "Cage du Freux",
				it = "Gabbia di Corvonero",
				pt = "Jaula Corvo Negro",
				ru = "Клетка крепости Черной Ладьи",
				ko = "검은 떼까마귀 우리",
				cn = "黑鸦牢笼",
			},
		},
	
		[243227] = {
			readable = "Ravencrest Cemetery",
			model = 197817,
			text = {
				en = "Ravencrest Cemetery",
				es = "Cementerio Cresta Cuervo",
				de = "Friedhof von Haus Rabenkrone",
				fr = "Cimetière des Corvaltus",
				it = "Cimitero di Crinocorvo",
				pt = "Cemitério Cristacorvo",
				ru = "Кладбище Гребня Ворона",
				ko = "레이븐크레스트 묘지",
				cn = "拉文凯斯墓地",
			},
		},
	
		[243228] = {
			readable = "Spirit Cauldron",
			model = 219398,
			text = {
				en = "Spirit Cauldron",
				es = "Caldera de espíritus",
				de = "Geisterkessel",
				fr = "Chaudron d’esprit",
				it = "Calderone dello Spirito",
				pt = "Caldeirão Espiritual",
				ru = "Котел духов",
			},
		},
	
		[243244] = {
			readable = "Place Volatile Flare",
			model = 194822,
			text = {
				en = "Place Volatile Flare",
				es = "Colocar explosivo volátil",
				de = "Instabile Mischung platzieren",
				fr = "Placer une décoction instable",
				it = "Fialabengala Instabile",
				pt = "Colocar Sinalizador Volátil",
				ru = "Разместить нестабильную взрывчатую смесь",
				ko = "불안정한 폭발물 설치",
				cn = "放置易爆炸弹",
			},
		},
	
		[243280] = {
			readable = "Pirate Pepe",
			model = 1131795,
			text = {
				en = "Pirate Pepe",
				es = "Pepe pirata",
				de = "Pepe der Pirat",
				fr = "Pépé pirate",
				it = "Pepe Pirata",
				pt = "Pepe Pirata",
				ru = "Пепе-пират",
				ko = "해적 피프",
			},
		},
	
		[243281] = {
			readable = "Ninja Pepe",
			model = 1131797,
			text = {
				en = "Ninja Pepe",
				es = "Pepe ninja",
				de = "Pepe der Ninja",
				fr = "Pépé ninja",
				it = "Pepe Ninja",
				pt = "Pepe Ninja",
				ru = "Пепе-ниндзя",
				ko = "닌자 피프",
				cn = "忍者佩佩",
			},
		},
	
		[243282] = {
			readable = "Viking Pepe",
			model = 1131798,
			text = {
				en = "Viking Pepe",
				es = "Pepe vikingo",
				de = "Pepe der Wikinger",
				fr = "Pépé viking",
				it = "Pepe Vichingo",
				pt = "Pepe Viking",
				ru = "Пепе-викинг",
				ko = "바이킹 피프",
				cn = "维京佩佩",
			},
		},
	
		[243283] = {
			readable = "Knight Pepe",
			model = 1131783,
			text = {
				en = "Knight Pepe",
				es = "Pepe caballero",
				de = "Pepe der Ritter",
				fr = "Pépé chevalier",
				it = "Pepe Cavaliere",
				pt = "Pepe Cavaleiro",
				ru = "Пепе-рыцарь",
				ko = "기사 피프",
				cn = "骑士佩佩",
			},
		},
	
		[243290] = {
			readable = "Spoils of the Assault",
			model = 1125838,
			text = {
				en = "Spoils of the Assault",
				es = "Botín del asalto",
				de = "Raubgut",
				fr = "Butin de l’assaut",
				it = "Spoglie dell'Assalto",
				pt = "Espólio do Ataque",
				ru = "Трофеи штурма",
				ko = "공성전 전리품",
			},
		},
	
		[243308] = {
			readable = "Spoils of the Assault",
			model = 1125838,
			text = {
				en = "Spoils of the Assault",
				es = "Botín del asalto",
				de = "Raubgut",
				fr = "Butin de l’assaut",
				it = "Spoglie dell'Assalto",
				pt = "Espólio do Ataque",
				ru = "Трофеи штурма",
				ko = "공성전 전리품",
				cn = "奇袭战利品",
			},
		},
	
		[243309] = {
			readable = "Spoils of the Assault",
			model = 1125838,
			text = {
				en = "Spoils of the Assault",
				es = "Botín del asalto",
				de = "Raubgut",
				fr = "Butin de l’assaut",
				it = "Spoglie dell'Assalto",
				pt = "Espólio do Ataque",
				ru = "Трофеи штурма",
				cn = "奇袭战利品",
			},
		},
	
		[243312] = {
			readable = "Rich Blackrock Deposit",
			model = 984392,
			text = {
				en = "Rich Blackrock Deposit",
				es = "Depósito rico en roca negra",
				de = "Reiches Schwarzfelsvorkommen",
				fr = "Riche gisement de rochenoire",
				it = "Deposito Ricco di Roccianera",
				pt = "Depósito Rico de Rocha Negra",
				ru = "Богатые залежи руды Черной горы",
				ko = "풍부한 검은바위 광맥",
				cn = "富黑石矿脉",
			},
		},
	
		[243313] = {
			readable = "Blackrock Deposit",
			model = 984390,
			text = {
				en = "Blackrock Deposit",
				es = "Depósito de roca negra",
				de = "Schwarzfelsvorkommen",
				fr = "Gisement de rochenoire",
				it = "Deposito di Roccianera",
				pt = "Depósito de Rocha Negra",
				ru = "Залежи руды Черной горы",
				ko = "검은바위 광맥",
				cn = "黑石矿脉",
			},
		},
	
		[243314] = {
			readable = "True Iron Deposit",
			model = 984397,
			text = {
				en = "True Iron Deposit",
				es = "Depósito de verahierro",
				de = "Echteisenvorkommen",
				fr = "Gisement de vérifer",
				it = "Deposito di Puroferro",
				pt = "Depósito de Ferro Verdadeiro",
				ru = "Залежи истинного железа",
				ko = "순철 광맥",
				cn = "真铁矿脉",
			},
		},
	
		[243315] = {
			readable = "Rich True Iron Deposit",
			model = 984398,
			text = {
				en = "Rich True Iron Deposit",
				es = "Depósito rico en verahierro",
				de = "Reiches Echteisenvorkommen",
				fr = "Riche gisement de vérifer",
				it = "Deposito Ricco di Puroferro",
				pt = "Depósito Rico de Ferro Verdadeiro",
				ru = "Богатые залежи истинного железа",
				ko = "풍부한 순철 광맥",
				cn = "富真铁矿脉",
			},
		},
	
		[243321] = {
			readable = "Feral Stone",
			model = 1127329,
			text = {
				en = "Feral Stone",
				es = "Piedra Feral",
				de = "Stein der Wildheit",
				fr = "Pierre farouche",
				it = "Pietra Ferina",
				pt = "Pedra Feral",
				ru = "Камень силы зверя",
				ko = "야성의 돌",
				cn = "野性之石",
			},
		},
	
		[243322] = {
			readable = "Guardian Stone",
			model = 1127330,
			text = {
				en = "Guardian Stone",
				es = "Piedra guardiana",
				de = "Wächterstein",
				fr = "Pierre du gardien",
				it = "Pietra Guardiana",
				pt = "Pedra Guardiã",
				ru = "Охранный камень",
				ko = "수호자의 돌",
				cn = "守护之石",
			},
		},
	
		[243323] = {
			readable = "Balance Stone",
			model = 1127332,
			text = {
				en = "Balance Stone",
				es = "Piedra de Equilibrio",
				de = "Stein des Gleichgewichts",
				fr = "Pierre de l’équilibre",
				it = "Pietra dell'Equilibrio",
				pt = "Pedra de Equilíbrio",
				ru = "Камень баланса",
				ko = "조화의 돌",
				cn = "平衡之石",
			},
		},
	
		[243325] = {
			readable = "Felmouth Frenzy School",
			model = 219406,
			text = {
				en = "Felmouth Frenzy School",
				es = "Banco de frenesís bocaviles",
				de = "Ein Schwarm Dämonenschlundfrenzys",
				fr = "Banc de gangregoulots frénétiques",
				it = "Banco di Vildenti Frenetici",
				pt = "Cardume de Farnesim Bocavil",
				ru = "Косяк бешенки-сквернорота",
				ko = "지옥아귀 광포어 떼",
				cn = "魔口狂鱼群",
			},
		},
	
		[243334] = {
			readable = "Withered Herb",
			icon = 959842,
			model = 219480,
			text = {
				en = "Withered Herb",
				es = "Hierba marchita",
				de = "Verwelktes Kraut",
				fr = "Herbe flétrie",
				it = "Erba Avvizzita",
				pt = "Planta Murcha",
				ru = "Высохшая трава",
				ko = "시든 약초",
				cn = "干枯的草药",
			},
		},
	
		[243335] = {
			readable = "Nether Crucible",
			model = 1101712,
			text = {
				en = "Nether Crucible",
				es = "Crisol abisal",
				de = "Nethertiegel",
				fr = "Creuset du Néant",
				it = "Crogiolo Fatuo",
				pt = "Crisol Etéreo",
				ru = "Горнило Пустоты",
				ko = "황천 도가니",
				cn = "虚空坩埚",
			},
		},
	
		[243345] = {
			readable = "Black Market Chest",
			model = 629720,
			text = {
				en = "Black Market Chest",
				es = "Cofre del mercado negro",
				de = "Schwarzmarkttruhe",
				fr = "Coffre du marché noir",
				it = "Cassa del Mercato Nero",
				pt = "Baú do Mercado Negro",
				ru = "Сундук с черного рынка",
				ko = "암시장 궤짝",
			},
		},
	
		[243354] = {
			readable = "Felmouth Frenzy School",
			model = 248067,
			text = {
				en = "Felmouth Frenzy School",
				es = "Banco de frenesís bocaviles",
				de = "Ein Schwarm Dämonenschlundfrenzys",
				fr = "Banc de gangregoulots frénétiques",
				it = "Banco di Vildenti Frenetici",
				pt = "Cardume de Farnesim Bocavil",
				ru = "Косяк бешенки-сквернорота",
				ko = "지옥아귀 광포어 떼",
				cn = "魔口狂鱼群",
			},
		},
	
		[243368] = {
			readable = "Wooden Barricade",
			model = 937201,
			text = {
				en = "Wooden Barricade",
				es = "Barricada de madera",
				de = "Holzbarrikade",
				fr = "Barricade en bois",
				it = "Barricata di Legno",
				pt = "Barricada de Madeira",
				ru = "Деревянная баррикада",
				ko = "나무 방벽",
				cn = "木栅栏",
			},
		},
	
		[243386] = {
			readable = "Event: Blood Moon",
			model = 124640,
			text = {
				en = "Event: Blood Moon",
				es = "Evento: Luna sangrienta",
				de = "Ereignis: Blutmond",
				fr = "Évènement : Lune de sang",
				it = "Evento: Luna di Sangue",
				ru = "Событие: Кровавая Луна",
				ko = "이벤트: 핏빛 달",
				cn = "事件：鲜血之月",
			},
		},
	
		[243392] = {
			readable = "Alchemy Book",
			model = 985165,
			text = {
				en = "Alchemy Book",
				es = "Libro de alquimia",
				de = "Alchemiebuch",
				fr = "Livre d’alchimie",
				it = "Libro di Alchimia",
				pt = "Livro de Alquimia",
				ru = "Алхимическая книга",
			},
		},
	
		[243401] = {
			readable = "Harpy Egg",
			model = 661112,
			text = {
				en = "Harpy Egg",
				es = "Huevo de arpía",
				de = "Ei einer Harpyie",
				fr = "Œuf de Harpie",
				it = "Uovo di Arpia",
				pt = "Ovo de Harpia",
				ru = "Яйцо гарпии",
				cn = "鹰身人的蛋",
			},
		},
	
		[243402] = {
			readable = "Navarrogg's Cage",
			model = 971072,
			text = {
				en = "Navarrogg's Cage",
				es = "Jaula de Navarrogg",
				de = "Navarroggs Käfig",
				fr = "Cage de Navarrogg",
				it = "Gabbia di Navarrogg",
				pt = "Jaula de Navarrogg",
				ru = "Клетка Наваррогга",
				ko = "나바로그의 우리",
				cn = "纳瓦罗格的牢笼",
			},
		},
	
		[243405] = {
			readable = "Legion Portal",
			text = {
				en = "Legion Portal",
				es = "Portal de la Legión",
				de = "Legionsportal",
				fr = "Portail de la Légion",
				it = "Portale della Legione",
				pt = "Portal da Legião",
				ru = "Портал Легиона",
				ko = "군단 차원문",
				cn = "军团传送门",
			},
		},
	
		[243428] = {
			readable = "Felshield Ward",
			model = 1125330,
			text = {
				en = "Felshield Ward",
				es = "Resguardo de Escudo vil",
				de = "Teufelsschildzauberschutz",
				fr = "Protection d’énergie gangrenée",
				it = "Guardia di Vilscudo",
				pt = "Proteção Escudo Vil",
				ru = "Тотем щита Скверны",
				ko = "지옥방패 수호물",
				cn = "邪能防护结界",
			},
		},
	
		[243448] = {
			readable = "Dread Pod",
			text = {
				en = "Dread Pod",
				es = "Cápsula de la Legión",
				de = "Schreckenskapsel",
				fr = "Nacelle de l’effroi",
				it = "Capsula del Terrore",
				pt = "Cápsula Medonha",
				ru = "Отсек ужаса",
				ko = "공포의 탈출선",
				cn = "恐惧魔巢",
			},
		},
	
		[243454] = {
			readable = "Gilnean Heavy Explosive",
			model = 126022,
			text = {
				en = "Gilnean Heavy Explosive",
				es = "Explosivo pesado gilneano",
				de = "Schwerer gilnearischer Sprengstoff",
				fr = "Explosifs gilnéens lourds",
				it = "Esplosivo ad Alto Potenziale Gilneano",
				pt = "Explosivo Pesado Guilneano",
				ru = "Мощная гилнеасская взрывчатка",
				ko = "길니아스 고성능 폭발물",
				cn = "吉尔尼斯重磅炸药",
			},
		},
	
		[243455] = {
			readable = "Plant Explosives",
			model = 126022,
			text = {
				en = "Plant Explosives",
				es = "Poner explosivos",
				de = "Sprengstoff platzieren",
				fr = "Placer les explosifs",
				it = "Esplosivi",
				pt = "Plantar Explosivos",
				ru = "Закладывание взрывчатки",
				ko = "폭발물 설치",
			},
		},
	
		[243463] = {
			readable = "Wall",
			model = 1137968,
			text = {
				en = "Wall",
				es = "Muralla",
				de = "Mauer",
				fr = "Mur",
				it = "Muro",
				pt = "Parede",
				ru = "Стена",
				ko = "벽",
				cn = "墙",
			},
		},
	
		[243465] = {
			readable = "Dusty Boot",
			model = 955699,
			text = {
				en = "Dusty Boot",
				es = "Bota polvorienta",
				de = "Staubiger Stiefel",
				fr = "Botte poussiéreuse",
				it = "Stivali Impolverati",
				pt = "Botas Empoeiradas",
				ru = "Пыльный сапог",
				ko = "먼지투성이 장화",
				cn = "满是尘土的靴子",
			},
		},
	
		[243472] = {
			readable = "Felshield Ward",
			model = 1125330,
			text = {
				en = "Felshield Ward",
				es = "Resguardo de Escudo vil",
				de = "Teufelsschildzauberschutz",
				fr = "Protection d’énergie gangrenée",
				it = "Guardia di Vilscudo",
				pt = "Proteção Escudo Vil",
				ru = "Тотем щита Скверны",
				ko = "지옥방패 수호물",
				cn = "邪能防护结界",
			},
		},
	
		[243473] = {
			readable = "Felshield Ward",
			model = 1125330,
			text = {
				en = "Felshield Ward",
				es = "Resguardo de Escudo vil",
				de = "Teufelsschildzauberschutz",
				fr = "Protection d’énergie gangrenée",
				it = "Guardia di Vilscudo",
				pt = "Proteção Escudo Vil",
				ru = "Тотем щита Скверны",
				ko = "지옥방패 수호물",
				cn = "邪能防护结界",
			},
		},
	
		[243477] = {
			readable = "Portal to Ashran",
			model = 1036124,
			text = {
				en = "Portal to Ashran",
				es = "Portal a Ashran",
				de = "Portal nach Ashran",
				fr = "Portail vers A’shran",
				it = "Portale per Ashran",
				pt = "Portal para Ashran",
				ru = "Портал на Ашран",
				ko = "아쉬란으로 통하는 차원문",
			},
		},
	
		[243478] = {
			readable = "Portal to Ashran",
			model = 1068317,
			text = {
				en = "Portal to Ashran",
				es = "Portal a Ashran",
				de = "Portal nach Ashran",
				fr = "Portail vers A’shran",
				it = "Portale per Ashran",
				pt = "Portal para Ashran",
				ru = "Портал на Ашран",
				ko = "아쉬란으로 통하는 차원문",
				cn = "到阿什兰的传送门",
			},
		},
	
		[243479] = {
			readable = "Portal to Vol'mar",
			model = 1237455,
			text = {
				en = "Portal to Vol'mar",
				es = "Portal a Vol'mar",
				de = "Portal nach Vol'mar",
				fr = "Portail vers Vol’mar",
				it = "Portale per Vol'mar",
				pt = "Portal para Vol'mar",
				ru = "Портал в Вол'мар",
				ko = "볼마르로 통하는 차원문",
				cn = "通往沃玛尔的传送门",
			},
		},
	
		[243480] = {
			readable = "Portal to Lion's Watch",
			model = 1237456,
			text = {
				en = "Portal to Lion's Watch",
				es = "Portal a la Avanzada del León",
				de = "Portal zur Löwenwacht",
				fr = "Portail vers le guet du Lion",
				it = "Portale per il Presidio del Leone",
				pt = "Portal para a Vigília do Leão",
				ru = "Портал в Львиный дозор",
				ko = "사자의 감시터로 통하는 차원문",
				cn = "通往雄狮岗哨的传送门",
			},
		},
	
		[243511] = {
			readable = "Gorefiend Portal",
			model = 1131586,
			text = {
				en = "Gorefiend Portal",
				es = "Portal de Sanguino",
				de = "Blutschattens Portal",
				fr = "Portail de Hurlesang",
				it = "Portale di Malacarne",
				pt = "Portal de Sanguinávido",
				ru = "Портал Кровожада",
				ko = "고어핀드 차원문",
			},
		},
	
		[243512] = {
			readable = "Horde Destroyer Ship",
			model = 166432,
			text = {
				en = "Horde Destroyer Ship",
				es = "Destructor de la Horda",
				de = "Zerstörer der Horde",
				fr = "Destroyer de la Horde",
				it = "Fregata dell'Orda",
				pt = "Navio Destróier da Horda",
				ru = "Эсминец Орды",
				ko = "호드 구축함",
				cn = "部落驱逐舰",
			},
		},
	
		[243513] = {
			readable = "Horde Submarine Ship",
			model = 166432,
			text = {
				en = "Horde Submarine Ship",
				es = "Submarino de la Horda",
				de = "U-Boot der Horde",
				fr = "Sous-marin de la Horde",
				it = "Sottomarino dell'Orda",
				pt = "Navio Submarino da Horda",
				ru = "Подводная лодка Орды",
				ko = "호드 잠수함",
				cn = "部落潜水艇",
			},
		},
	
		[243515] = {
			readable = "Battleship Ship - Horde",
			model = 166432,
			text = {
				en = "Battleship Ship - Horde",
				es = "Buque de combate: Horda",
				de = "Schlachtschiff - Horde",
				fr = "Cuirassé de la Horde",
				it = "Galeone dell'Orda",
				pt = "Navio Nau de Batalha - Horda",
				ru = "Линкор – Орда",
				ko = "전함 - 호드",
				cn = "战列舰 - 部落",
			},
		},
	
		[243539] = {
			readable = "Felshard",
			model = 192011,
			text = {
				en = "Felshard",
				es = "Fragmento vil",
				de = "Teufelssplitter",
				fr = "Gangréclat",
				it = "Vilscheggia",
				pt = "Fragmento Vil",
				ru = "Осколок Скверны",
				ko = "지옥파편",
				cn = "邪能碎片",
			},
		},
	
		[243559] = {
			readable = "Statue of Liftbrul",
			model = 970109,
			text = {
				en = "Statue of Liftbrul",
				es = "Estatua de Aupabrul",
				de = "Statue von Muckibrul",
				fr = "Statue de Lèvebrouf",
				it = "Statua di Alzabrul",
				pt = "Estátua de Malhalesk",
				ru = "Статуя Штангобрула",
				ko = "리프트브룰의 석상",
				cn = "利夫布鲁的雕像",
			},
		},
	
		[243562] = {
			readable = "Crate of Khadgar's Whiskers",
			model = 310483,
			text = {
				en = "Crate of Khadgar's Whiskers",
				es = "Hojas de té de Khadgar",
				de = "Kiste mit Khadgars Schnurrbärten",
				fr = "Caisse de moustaches de Khadgar",
				it = "Cassa di Ciuffi di Khadgar",
				pt = "Caixote de Bigode-de-hadggar",
				ru = "Ящик кадгарова уса",
				ko = "카드가의 수염풀 상자",
				cn = "一箱卡德加的胡须",
			},
		},
	
		[243563] = {
			readable = "Barrel of Fish Oil",
			model = 310482,
			text = {
				en = "Barrel of Fish Oil",
				es = "Barril de aceite de pescado",
				de = "Fass mit Fischöl",
				fr = "Tonneau d’huile de poisson",
				it = "Barile di Olio di Pesce",
				pt = "Barril de Óleo de Peixe",
				ru = "Бочка с рыбьим жиром",
				ko = "생선 기름 통",
				cn = "鱼油桶",
			},
		},
	
		[243564] = {
			readable = "Basket of Dried Herbs",
			model = 341579,
			text = {
				en = "Basket of Dried Herbs",
				es = "Cesta de hierbas secas",
				de = "Korb mit getrockneten Kräutern",
				fr = "Panier d’herbes séchées",
				it = "Cestino di Erbe Essiccate",
				pt = "Cesto de Plantas Secas",
				ru = "Корзина сухих трав",
				ko = "말린 약초 바구니",
				cn = "干草药篮",
			},
		},
	
		[243566] = {
			readable = "Sargerei Warspoils",
			model = 1125838,
			text = {
				en = "Sargerei Warspoils",
				es = "Botín de guerra Sargerei",
				de = "Kriegsbeute der Sargerei",
				fr = "Butin de guerre sargereï",
				it = "Spoglie di Guerra dei Sargerei",
				pt = "Espólios de Guerra Sargerei",
				ru = "Военные трофеи саргераев",
				ko = "살게레이 전리품",
			},
		},
	
		[243567] = {
			readable = "Sargerei Warspoils",
			model = 1125838,
			text = {
				en = "Sargerei Warspoils",
				es = "Botín de guerra Sargerei",
				de = "Kriegsbeute der Sargerei",
				fr = "Butin de guerre sargereï",
				it = "Spoglie di Guerra dei Sargerei",
				pt = "Espólios de Guerra Sargerei",
				ru = "Военные трофеи саргераев",
			},
		},
	
		[243568] = {
			readable = "Sargerei Warspoils",
			model = 1125838,
			text = {
				en = "Sargerei Warspoils",
				es = "Botín de guerra Sargerei",
				de = "Kriegsbeute der Sargerei",
				fr = "Butin de guerre sargereï",
				it = "Spoglie di Guerra dei Sargerei",
				pt = "Espólios de Guerra Sargerei",
				ru = "Военные трофеи саргераев",
				cn = "萨格雷战利品",
			},
		},
	
		[243570] = {
			readable = "Shieldmaiden Idol",
			model = 1137603,
			text = {
				en = "Shieldmaiden Idol",
				es = "Ídolo de la doncella escudera",
				de = "Götze der Schildmaid",
				fr = "Idole de vierge guerrière",
				it = "Idolo delle Signore dello Scudo",
				pt = "Ídolo da Dama Escudeira",
				ru = "Идол дев щита",
				ko = "방패여전사 우상",
				cn = "女武神雕像",
			},
		},
	
		[243571] = {
			readable = "Shieldmaiden Idol",
			model = 1135364,
			text = {
				en = "Shieldmaiden Idol",
				es = "Ídolo de la doncella escudera",
				de = "Götze der Schildmaid",
				fr = "Idole de vierge guerrière",
				it = "Idolo delle Signore dello Scudo",
				pt = "Ídolo da Dama Escudeira",
				ru = "Идол дев щита",
				ko = "방패여전사 우상",
				cn = "女武神雕像",
			},
		},
	
		[243573] = {
			readable = "Shieldmaiden Idol",
			model = 1137602,
			text = {
				en = "Shieldmaiden Idol",
				es = "Ídolo de la doncella escudera",
				de = "Götze der Schildmaid",
				fr = "Idole de vierge guerrière",
				it = "Idolo delle Signore dello Scudo",
				pt = "Ídolo da Dama Escudeira",
				ru = "Идол дев щита",
				ko = "방패여전사 우상",
				cn = "女武神雕像",
			},
		},
	
		[243574] = {
			readable = "Shieldmaiden Idol",
			model = 1135324,
			text = {
				en = "Shieldmaiden Idol",
				es = "Ídolo de la doncella escudera",
				de = "Götze der Schildmaid",
				fr = "Idole de vierge guerrière",
				it = "Idolo delle Signore dello Scudo",
				pt = "Ídolo da Dama Escudeira",
				ru = "Идол дев щита",
				ko = "방패여전사 우상",
				cn = "女武神雕像",
			},
		},
	
		[243630] = {
			readable = "Doodad_6du_hellfireraid_soulportal_center001",
			model = 1131586,
			text = {
				en = "Doodad_6du_hellfireraid_soulportal_center001",
			},
		},
	
		[243631] = {
			readable = "Doodad_6du_hellfireraidl_soulportal_single004",
			model = 1131588,
			text = {
				en = "Doodad_6du_hellfireraidl_soulportal_single004",
			},
		},
	
		[243632] = {
			readable = "Doodad_6du_hellfireraidl_soulportal_single003",
			model = 1131588,
			text = {
				en = "Doodad_6du_hellfireraidl_soulportal_single003",
			},
		},
	
		[243633] = {
			readable = "Doodad_6du_hellfireraidl_soulportal_single002",
			model = 1131588,
			text = {
				en = "Doodad_6du_hellfireraidl_soulportal_single002",
			},
		},
	
		[243634] = {
			readable = "Doodad_6du_hellfireraidl_soulportal_single001",
			model = 1131588,
			text = {
				en = "Doodad_6du_hellfireraidl_soulportal_single001",
			},
		},
	
		[243636] = {
			readable = "Ledger of the Sea Wolf",
			model = 929342,
			text = {
				en = "Ledger of the Sea Wolf",
				es = "Libro del Lobo de Mar",
				de = "Buch des Seewolfs",
				fr = "Grand livre du Loup de mer",
				it = "Libro Mastro del Lupo di Mare",
				pt = "Livro Contábil do Lobo-do-mar",
				ru = "Гроссбух с \"Морского волка\"",
				ko = "바다늑대호 장부",
				cn = "海狼号账本",
			},
		},
	
		[243639] = {
			readable = "Siphoning Crystal",
			model = 370323,
			text = {
				en = "Siphoning Crystal",
				es = "Cristal de succión",
				de = "Entzugskristall",
				fr = "Cristal de siphonnage",
				it = "Cristallo Risucchiante",
				pt = "Cristal Canalizante",
				ru = "Вытягивающий кристалл",
				ko = "흡수의 수정",
			},
		},
	
		[243688] = {
			readable = "Treasure Chest",
			model = 1402238,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[243690] = {
			readable = "Bejeweled Egg",
			model = 1004785,
			text = {
				en = "Bejeweled Egg",
				es = "Huevo con joyas",
				de = "Juwelenbesetztes Ei",
				fr = "Œuf orné de joyaux",
				it = "Uovo Ingioiellato",
				pt = "Ovo Adornado com Joias",
				ru = "Яйцо с самоцветами",
				ko = "보석 박힌 새알",
				cn = "珠玉彩蛋",
			},
		},
	
		[243693] = {
			readable = "Dead Man's Chest",
			model = 446671,
			text = {
				en = "Dead Man's Chest",
				es = "Cofre de un hombre muerto",
				de = "Truhe des toten Mannes",
				fr = "Le coffre du mort",
				it = "Scrigno del Morto",
				pt = "Baú do Morto",
				ru = "Сундук мертвеца",
				cn = "亡灵宝藏",
			},
		},
	
		[243698] = {
			readable = "Glimmering Treasure Chest",
			model = 1402222,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[243699] = {
			readable = "Transport Ship",
			model = 166432,
			text = {
				en = "Transport Ship",
				es = "Transportador",
				de = "Transportschiff",
				fr = "Transporteur",
				it = "Caravella",
				pt = "Navio de Transporte",
				ru = "Транспортный корабль",
				ko = "수송선",
				cn = "运输船",
			},
		},
	
		[243700] = {
			readable = "Forsaken Battle Plans",
			model = 319550,
			text = {
				en = "Forsaken Battle Plans",
				es = "Planes de batalla de los Renegados",
				de = "Schlachtpläne der Verlassenen",
				fr = "Plans de bataille réprouvés",
				it = "Piani di Battaglia dei Reietti",
				pt = "Planos de Batalha dos Renegados",
				ru = "Военные планы Отрекшихся",
				ko = "포세이큰 전투 계획서",
				cn = "被遗忘者作战计划",
			},
		},
	
		[243701] = {
			readable = "Horde Destroyer Ship",
			model = 166432,
			text = {
				en = "Horde Destroyer Ship",
				es = "Destructor de la Horda",
				de = "Zerstörer der Horde",
				fr = "Destroyer de la Horde",
				it = "Fregata dell'Orda",
				pt = "Navio Destróier da Horda",
				ru = "Эсминец Орды",
				ko = "호드 구축함",
				cn = "部落驱逐舰",
			},
		},
	
		[243702] = {
			readable = "Alliance Destroyer Ship",
			model = 166432,
			text = {
				en = "Alliance Destroyer Ship",
				es = "Destructor de la Alianza",
				de = "Zerstörer der Allianz",
				fr = "Destroyer de l’Alliance",
				it = "Fregata dell'Alleanza",
				pt = "Navio Destróier da Aliança",
				ru = "Эсминец Альянса",
				ko = "얼라이언스 구축함",
				cn = "联盟驱逐舰",
			},
		},
	
		[243712] = {
			readable = "Fishing Supplies",
			model = 409803,
			text = {
				en = "Fishing Supplies",
				es = "Suministros de pesca",
				de = "Angelbedarf",
				fr = "Fournitures de pêche",
				it = "Forniture di Pesca",
				pt = "Suprimentos de Pesca",
				ru = "Товары для рыбной ловли",
				ko = "낚시용품",
			},
		},
	
		[243716] = {
			readable = "Helbrim's Special",
			model = 243486,
			text = {
				en = "Helbrim's Special",
				es = "Especial de Helbrim",
				de = "Helbrims Spezial",
				fr = "Spécial d’Helbrim",
				it = "Speciale di Helbrim",
				pt = "Especial de Helbrim",
				ru = "Особый рецепт Хелбрима",
			},
		},
	
		[243719] = {
			readable = "Portal to Tanaan",
			model = 1237454,
			text = {
				en = "Portal to Tanaan",
				es = "Portal a Tanaan",
				de = "Portal nach Tanaan",
				fr = "Portail vers Tanaan",
				it = "Portale per Tanaan",
				pt = "Portal para Tanaan",
				ru = "Портал в Танаан",
				cn = "到塔纳安的传送门",
			},
		},
	
		[243761] = {
			readable = "Ogre Waygate",
			model = 394808,
			text = {
				en = "Ogre Waygate",
				es = "Puerta ogra",
				de = "Ogerportal",
				fr = "Portail d’accès ogre",
				it = "Portale degli Ogre",
				pt = "Pórtico Ôgrico",
				ru = "Огрские путевые врата",
				cn = "食人魔传送门",
			},
		},
	
		[243762] = {
			readable = "Deactivated Ogre Waygate",
			model = 394808,
			text = {
				en = "Deactivated Ogre Waygate",
				es = "Puerta ogra desactivada",
				de = "Deaktiviertes Ogerportal",
				fr = "Portail d’accès ogre désactivé",
				it = "Portale degli Ogre Disattivato",
				pt = "Pórtico Ôgrico Desativado",
				ru = "Деактивированные огрские путевые врата",
				ko = "비활성화된 오우거 차원문",
				cn = "未激活的食人魔传送门",
			},
		},
	
		[243773] = {
			readable = "Treasure Chest",
			model = 1402238,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[243776] = {
			readable = "Dust Bunny",
			model = 522081,
			text = {
				en = "Dust Bunny",
				es = "Conejo de polvo",
				fr = "Lapin de poussière",
				it = "Cumulo di Polvere",
				pt = "Chumaço de Poeira",
				ru = "Пылевой кролик",
				ko = "먼지",
				cn = "烟灰野兔",
			},
		},
	
		[243794] = {
			readable = "Unrefined Draenic Crystal",
			model = 392114,
			text = {
				en = "Unrefined Draenic Crystal",
				es = "Cristal draénico sin refinar",
				de = "Unbearbeiteter Draeneikristall",
				fr = "Cristal draenique non raffiné",
				it = "Cristallo Draenoriano Grezzo",
				pt = "Cristal Draenoriano Bruto",
				ru = "Неограненный дренорский кристалл",
				ko = "정제하지 않은 드레나이 수정",
				cn = "德拉诺水晶原石",
			},
		},
	
		[243796] = {
			readable = "Suspiciously Glowing Chest",
			model = 953811,
			text = {
				en = "Suspiciously Glowing Chest",
				es = "Cofre sospechosamente resplandeciente",
				de = "Verdächtig leuchtende Truhe",
				fr = "Coffre anormalement brillant",
				it = "Scrigno Luccicante Sospetto",
				pt = "Baú com Brilho Suspeito",
				ru = "Подозрительно светящийся сундук",
				ko = "미심쩍게 빛나는 궤짝",
				cn = "可疑的发光宝箱",
			},
		},
	
		[243798] = {
			readable = "A Steamy Jewelry Box",
			model = 1100065,
			text = {
				en = "A Steamy Jewelry Box",
				es = "El joyero tórrido",
				de = "Ein dampfendes Schmuckkästchen",
				fr = "Boîte à bijoux torride",
				it = "Scrigno di Gioielli Romantico",
				pt = "Porta-joias Fumegante",
				ru = "Запотевший сундучок с драгоценностями",
				ko = "야한 보석 상자",
				cn = "潮湿的珠宝盒",
				tw = "一個煽情的珠寶盒",
			},
		},
	
		[243801] = {
			readable = "Powered Console",
			model = 1256327,
			text = {
				en = "Powered Console",
				es = "Consola activada",
				de = "Aktive Konsole",
				fr = "Console alimentée en énergie",
				it = "Console Attiva",
				pt = "Console Energizado",
				ru = "Подключенная панель управления",
				ko = "전원이 켜진 장치",
				cn = "充能的控制台",
			},
		},
	
		[243802] = {
			readable = "Powered Console",
			model = 1256327,
			text = {
				en = "Powered Console",
				es = "Consola activada",
				de = "Aktive Konsole",
				fr = "Console alimentée en énergie",
				it = "Console Attiva",
				pt = "Console Energizado",
				ru = "Подключенная панель управления",
				ko = "전원이 켜진 장치",
				cn = "充能的控制台",
			},
		},
	
		[243808] = {
			readable = "Unpowered Console",
			model = 1256327,
			text = {
				en = "Unpowered Console",
				es = "Consola desactivada",
				de = "Inaktive Konsole",
				fr = "Console non alimentée",
				it = "Console Disattiva",
				pt = "Console Desenergizado",
				ru = "Отключенная панель управления",
				ko = "전원이 꺼진 장치",
				cn = "没有能量的控制台",
			},
		},
	
		[243814] = {
			readable = "Unpowered Console",
			model = 1256327,
			text = {
				en = "Unpowered Console",
				es = "Consola desactivada",
				de = "Inaktive Konsole",
				fr = "Console non alimentée",
				it = "Console Disattiva",
				pt = "Console Desenergizado",
				ru = "Отключенная панель управления",
				ko = "전원이 꺼진 장치",
				cn = "没有能量的控制台",
			},
		},
	
		[243817] = {
			readable = "Powered Console",
			model = 243957,
			text = {
				en = "Powered Console",
				es = "Consola activada",
				de = "Aktive Konsole",
				fr = "Console alimentée en énergie",
				it = "Console Attiva",
				pt = "Console Energizado",
				ru = "Подключенная панель управления",
				ko = "전원이 켜진 장치",
				cn = "充能的控制台",
			},
		},
	
		[243819] = {
			readable = "Yotnar's Left Arm",
			model = 1327766,
			text = {
				en = "Yotnar's Left Arm",
				es = "Brazo izquierdo de Yotnar",
				de = "Yotnars linker Arm",
				fr = "Bras gauche de Yotnar",
				it = "Braccio Sinistro di Yotnar",
				pt = "Braço Esquerdo de Yotnar",
				ru = "Левая рука Йотнара",
				ko = "요트나르의 왼팔",
				cn = "尤特纳的左臂",
			},
		},
	
		[243820] = {
			readable = "Yotnar's Right Arm",
			model = 1381303,
			text = {
				en = "Yotnar's Right Arm",
				es = "Brazo derecho de Yotnar",
				de = "Yotnars rechter Arm",
				fr = "Bras droit de Yotnar",
				it = "Braccio Destro di Yotnar",
				pt = "Braço Direito de Yotnar",
				ru = "Правая рука Йотнара",
				ko = "요트나르의 오른팔",
				cn = "尤特纳的右臂",
			},
		},
	
		[243822] = {
			readable = "Yotnar's Right Foot",
			model = 1381302,
			text = {
				en = "Yotnar's Right Foot",
				es = "Pie derecho de Yotnar",
				de = "Yotnars rechter Fuß",
				fr = "Pied droit de Yotnar",
				it = "Piede Destro di Yotnar",
				pt = "Pé Direito de Yotnar",
				ru = "Правая нога Йотнара",
				ko = "요트나르의 오른발",
				cn = "尤特纳的右脚",
			},
		},
	
		[243823] = {
			readable = "Yotnar's  Left Foot",
			model = 1327764,
			text = {
				en = "Yotnar's  Left Foot",
				es = "Pie izquierdo de Yotnar",
				de = "Yotnars linker Fuß",
				fr = "Pied gauche de Yotnar",
				it = "Piede Sinistro di Yotnar",
				pt = "Pé Esquerdo de Yotnar",
				ru = "Левая нога Йотнара",
				ko = "요트나르의 왼발",
				cn = "尤特纳的左脚",
			},
		},
	
		[243836] = {
			readable = "Yotnar's Head",
			model = 1327765,
			text = {
				en = "Yotnar's Head",
				es = "Cabeza de Yotnar",
				de = "Kopf von Yotnar",
				fr = "Tête de Yotnar",
				it = "Testa di Yotnar",
				pt = "Cabeça de Yotnar",
				ru = "Голова Йотнара",
				ko = "요트나르의 머리",
				cn = "尤特纳的脑袋",
			},
		},
	
		[243840] = {
			readable = "Mightstone Banner",
			model = 1280842,
			text = {
				en = "Mightstone Banner",
				es = "Estandarte Piedra de Poderío",
				de = "Machtsteinbanner",
				fr = "Bannière pierre-puissance",
				it = "Stendardo di Pietragrossa",
				pt = "Estandarte de Megalito",
				ru = "Знамя племени Камня Силы",
				ko = "막돌 깃발",
				cn = "巨石战旗",
			},
		},
	
		[243841] = {
			readable = "Bloodtotem Standard",
			model = 1255657,
			text = {
				en = "Bloodtotem Standard",
				es = "Estandarte Tótem Sangriento",
				de = "Standarte des Bluttotemstamms",
				fr = "Étendard totem-de-sang",
				it = "Stendardo dei Totem Sanguinario",
				pt = "Estandarte dos Totem de Sangue",
				ru = "Штандарт племени Кровавого Тотема",
				ko = "핏빛토템 상징물",
				cn = "鲜血图腾图腾柱",
			},
		},
	
		[243842] = {
			readable = "Tideskorn Banner",
			model = 1132168,
			text = {
				en = "Tideskorn Banner",
				es = "Estandarte Mareskorn",
				de = "Banner der Wellenskorn",
				fr = "Bannière des Mörgestran",
				it = "Stendardo degli Abiskorn",
				pt = "Estandarte Mareskárnio",
				ru = "Волнскорнское знамя",
				ko = "타이드스코른 깃발",
				cn = "蔑魔战旗",
			},
		},
	
		[243845] = {
			readable = "Demonic Runestone",
			model = 1122446,
			text = {
				en = "Demonic Runestone",
				es = "Piedra rúnica demoníaca",
				de = "Dämonischer Runenstein",
				fr = "Pierre runique démoniaque",
				it = "Pietra Runica Demoniaca",
				pt = "Pedra Rúnica Demoníaca",
				ru = "Демонический рунический камень",
				ko = "악마의 룬석",
				cn = "恶魔符文石",
			},
		},
	
		[243852] = {
			readable = "Radiating Apexis Shard",
			model = 975539,
			text = {
				en = "Radiating Apexis Shard",
				es = "Fragmento apexis radiante",
				de = "Strahlender Apexissplitter",
				fr = "Éclat apogide rayonnant",
				it = "Scheggia Apexis Irradiante",
				pt = "Estilhaço Apexis Radiante",
				ru = "Лучащийся апекситовый осколок",
				ko = "빛을 발하는 에펙시스 결정",
				cn = "辐光埃匹希斯碎片",
			},
		},
	
		[243855] = {
			readable = "Bubbling Cauldron",
			model = 526866,
			text = {
				en = "Bubbling Cauldron",
				es = "Caldera burbujeante",
				de = "Blubbernder Kessel",
				fr = "Chaudron bouillonnant",
				it = "Calderone Ribollente",
				pt = "Caldeirão Borbulhante",
				ru = "Бурлящий котел",
				ko = "끓고 있는 가마솥",
				cn = "沸腾的大锅",
			},
		},
	
		[243859] = {
			readable = "Ley Dust Trail",
			model = 1096712,
			text = {
				en = "Ley Dust Trail",
				es = "Rastro de polvo ley",
				de = "Leystaubspur",
				fr = "Traînée de poussière tellurique",
				pt = "Trilha de Pó do Meridiano",
				ru = "След пыли силы",
				ko = "지맥 가루 흔적",
			},
		},
	
		[243860] = {
			readable = "Gleaming Draenic Chest",
			model = 1062118,
			text = {
				en = "Gleaming Draenic Chest",
				es = "Cofre draénico reluciente",
				de = "Schimmernde Draeneikiste",
				fr = "Coffre draenique resplendissant",
				it = "Scrigno Lucente Draenoriano",
				pt = "Baú Draneico Reluzente",
				ru = "Блестящий дренорский сундук",
				ko = "빛나는 드레나이 궤짝",
				cn = "发光的德莱尼宝箱",
			},
		},
	
		[243873] = {
			readable = "Legion Portal",
			model = 1125327,
			text = {
				en = "Legion Portal",
				es = "Portal de la Legión",
				de = "Legionsportal",
				fr = "Portail de la Légion",
				it = "Portale della Legione",
				pt = "Portal da Legião",
				ru = "Портал Легиона",
				ko = "군단 차원문",
				cn = "军团传送门",
			},
		},
	
		[243878] = {
			readable = "Arrow",
			model = 593816,
			text = {
				en = "Arrow",
				es = "Flecha",
				de = "Pfeil",
				fr = "Flèche",
				it = "Freccia",
				pt = "Flecha",
				ru = "Стрела",
				cn = "箭",
			},
		},
	
		[243893] = {
			readable = "Doodad_7HM_HighMountain_Elevator001",
			model = 1240388,
			text = {
				en = "Doodad_7HM_HighMountain_Elevator001",
				cn = "占位符",
			},
		},
	
		[243894] = {
			readable = "Doodad_7HM_HighMountain_Elevator002",
			model = 1240388,
			text = {
				en = "Doodad_7HM_HighMountain_Elevator002",
				cn = "占位符",
			},
		},
	
		[243899] = {
			readable = "Broken Ley Flame Burner",
			model = 528625,
			text = {
				en = "Broken Ley Flame Burner",
				es = "Quemador de llama ley roto",
				de = "Kaputter Leyflammenbrenner",
				fr = "Brûle-flamme tellurique cassé",
				pt = "Queimador de Chama de Meridiano Quebrado",
				ru = "Сломанная силовая горелка",
				ko = "부서진 지맥불길 가열기",
			},
		},
	
		[243905] = {
			readable = "Holding Cage",
			model = 195415,
			text = {
				en = "Holding Cage",
				es = "Jaula de contención",
				de = "Sammelkäfig",
				fr = "Cage de détention",
				it = "Gabbia",
				pt = "Jaula de Captura",
				ru = "Большая клетка",
				ko = "감금 우리",
				cn = "囚笼",
			},
		},
	
		[243911] = {
			readable = "Snow Mound",
			icon = 132387,
			model = 196993,
			text = {
				en = "Snow Mound",
				es = "Montículo de nieve",
				de = "Schneehügel",
				fr = "Monticule de neige",
				it = "Mucchio di Neve",
				pt = "Monte de Neve",
				ru = "Сугроб",
				ko = "눈더미",
				cn = "雪堆",
			},
		},
	
		[243935] = {
			readable = "Alliance Destroyer Ship",
			model = 166432,
			text = {
				en = "Alliance Destroyer Ship",
				es = "Destructor de la Alianza",
				de = "Zerstörer der Allianz",
				fr = "Destroyer de l’Alliance",
				it = "Fregata dell'Alleanza",
				pt = "Navio Destróier da Aliança",
				ru = "Эсминец Альянса",
				ko = "얼라이언스 구축함",
				cn = "联盟驱逐舰",
			},
		},
	
		[243938] = {
			readable = "Naval Equipment Blueprint: Blast Furnace",
			model = 203431,
			text = {
				en = "Naval Equipment Blueprint: Blast Furnace",
				es = "Plano de equipo naval: Horno de fundición",
				de = "Marineausstattungsbauplan: Heizkessel",
				fr = "Plan d’équipement naval : haut-fourneau",
				it = "Progetto: Caldaia Potenziata",
				pt = "Diagrama de Equipamento Naval: Fornalha Explosiva",
				ru = "Чертеж корабельного оборудования: горнило",
				ko = "해상 장비 도면: 강한 가열로",
				cn = "海军装备图纸：高能炉",
			},
		},
	
		[243952] = {
			readable = "Twisted Root",
			model = 1121896,
			text = {
				en = "Twisted Root",
				es = "Raíz retorcida",
				de = "Entstellte Wurzel",
				fr = "Racine tordue",
				it = "Radice Corrotta",
				pt = "Raiz Retorcida",
				ru = "Зараженный порчей корень",
				ko = "뒤틀린 뿌리",
				cn = "扭曲根茎",
			},
		},
	
		[243953] = {
			readable = "Twisted Root",
			model = 1121909,
			text = {
				en = "Twisted Root",
				es = "Raíz retorcida",
				de = "Entstellte Wurzel",
				fr = "Racine tordue",
				it = "Radice Corrotta",
				pt = "Raiz Retorcida",
				ru = "Зараженный порчей корень",
				ko = "뒤틀린 뿌리",
				cn = "扭曲根茎",
			},
		},
	
		[243954] = {
			readable = "Twisted Root",
			model = 1125295,
			text = {
				en = "Twisted Root",
				es = "Raíz retorcida",
				de = "Entstellte Wurzel",
				fr = "Racine tordue",
				it = "Radice Corrotta",
				pt = "Raiz Retorcida",
				ru = "Зараженный порчей корень",
				ko = "뒤틀린 뿌리",
				cn = "扭曲根茎",
			},
		},
	
		[243961] = {
			readable = "Horde Destroyer Ship",
			model = 166432,
			text = {
				en = "Horde Destroyer Ship",
				es = "Destructor de la Horda",
				de = "Zerstörer der Horde",
				fr = "Destroyer de la Horde",
				it = "Fregata dell'Orda",
				pt = "Navio Destróier da Horda",
				ru = "Эсминец Орды",
				ko = "호드 구축함",
				cn = "部落驱逐舰",
			},
		},
	
		[243965] = {
			readable = "Illidari Banner",
			model = 1101693,
			text = {
				en = "Illidari Banner",
				es = "Estandarte Illidari",
				de = "Banner der Illidari",
				fr = "Bannière illidari",
				it = "Stendardo degli Illidari",
				pt = "Estandarte Illidari",
				ru = "Знамя иллидари",
				ko = "일리다리 깃발",
				cn = "伊利达雷战旗",
			},
		},
	
		[243967] = {
			readable = "Illidari Banner",
			model = 1101693,
			text = {
				en = "Illidari Banner",
				es = "Estandarte Illidari",
				de = "Banner der Illidari",
				fr = "Bannière illidari",
				it = "Stendardo degli Illidari",
				pt = "Estandarte Illidari",
				ru = "Знамя иллидари",
				ko = "일리다리 깃발",
				cn = "伊利达雷战旗",
			},
		},
	
		[243968] = {
			readable = "Illidari Banner",
			model = 1101693,
			text = {
				en = "Illidari Banner",
				es = "Estandarte Illidari",
				de = "Banner der Illidari",
				fr = "Bannière illidari",
				it = "Stendardo degli Illidari",
				pt = "Estandarte Illidari",
				ru = "Знамя иллидари",
				ko = "일리다리 깃발",
				cn = "伊利达雷战旗",
			},
		},
	
		[243969] = {
			readable = "Ancient Anvil",
			model = 1315223,
			text = {
				en = "Ancient Anvil",
				es = "Yunque antiguo",
				de = "Uralter Amboss",
				fr = "Enclume antique",
				it = "Incudine Antica",
				pt = "Bigorna Anciã",
				ru = "Древняя наковальня",
				ko = "고대 모루",
				cn = "上古铁砧",
			},
		},
	
		[243971] = {
			readable = "Chains of Resistance",
			model = 875607,
			text = {
				en = "Chains of Resistance",
				es = "Cadenas de resistencia",
				de = "Ketten des Widerstandes",
				fr = "Chaînes de résistance",
				it = "Catene della Resistenza",
				pt = "Correntes de Resistência",
				ru = "Цепи сопротивления",
				ko = "저항의 사슬",
			},
		},
	
		[243972] = {
			readable = "Wheel of Fortitude",
			model = 1131720,
			text = {
				en = "Wheel of Fortitude",
				es = "Rueda de fortaleza",
				de = "Rad der Seelenstärke",
				fr = "Roue de robustesse",
				it = "Ruota della Fermezza",
				pt = "Roda da Fortitude",
				ru = "Колесо стойкости",
				ko = "인내의 바퀴",
			},
		},
	
		[243973] = {
			readable = "Rod of Bearing",
			model = 1131724,
			text = {
				en = "Rod of Bearing",
				es = "Vara de vigor",
				de = "Kursrute",
				fr = "Bâtonnet d’orientation",
				it = "Verga del Portamento",
				pt = "Bastão de Tolerância",
				ru = "Жезл выносливости",
				ko = "감내의 막대",
			},
		},
	
		[243993] = {
			readable = "Gate of the Candleking",
			model = 982136,
			text = {
				en = "Gate of the Candleking",
				es = "Puerta del rey de las velas",
				de = "Tor des Kerzenkönigs",
				fr = "Porte du Roi des bougies",
				it = "Cancello del Re delle Candele",
				pt = "Portão do Toma-vela",
				ru = "Врата Свечного короля",
				ko = "양초왕의 관문",
				cn = "蜡烛大王的大门",
			},
		},
})
do ObjectDB[objectID] = objectData; end
