local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	
		[373433] = {
			readable = "Field Anima Diverter",
			model = 4039280,
			text = {
				en = "Field Anima Diverter",
				es = "Desviador de ánima de campo",
				de = "Feldanimaumleiter",
				fr = "Déviateur d’anima portable",
				it = "Deviatore d'Animum da Campo",
				pt = "Desviador de Ânima de Campo",
				ru = "Переносной анимаотвод",
				ko = "현장 령 전환기",
				cn = "野战心能转移器",
			},
		},
	
		[373434] = {
			readable = "Field Anima Diverter",
			model = 4039280,
			text = {
				en = "Field Anima Diverter",
				es = "Desviador de ánima de campo",
				de = "Feldanimaumleiter",
				fr = "Déviateur d’anima portable",
				it = "Deviatore d'Animum da Campo",
				pt = "Desviador de Ânima de Campo",
				ru = "Переносной анимаотвод",
				ko = "현장 령 전환기",
				cn = "野战心能转移器",
			},
		},
	
		[373437] = {
			readable = "Pungent Blobfish Cluster",
			model = 219406,
			text = {
				en = "Pungent Blobfish Cluster",
				es = "Banco de peces mancha acres",
				de = "Stinkender Blobfischschwarm",
				fr = "Banc de poissons-blob âcres",
				pt = "Cardume de Baiacu Pungente",
				ru = "Косяк едких рыб-капель",
				ko = "자극적인 방울고기 무리",
				cn = "刺鼻的团豚群",
			},
		},
	
		[373438] = {
			readable = "Coilclutch Vine",
			model = 376277,
			text = {
				en = "Coilclutch Vine",
				es = "Vid garraespiral",
				de = "Spiralkrallententakel",
				fr = "Liane serre-pelote",
				pt = "Cirro-mola",
				ru = "Пружинная лоза",
				ko = "감줄마수 덩굴",
				cn = "旋握藤蔓",
			},
		},
	
		[373439] = {
			readable = "Flipper Fish School",
			model = 219406,
			text = {
				en = "Flipper Fish School",
				es = "Banco de peces aletones",
				de = "Ein Schwarm Flossenfische",
				fr = "Banc de nectalies",
				pt = "Cardume de Nadadeira",
				ru = "Стая плавунцов",
				ko = "파닥이 고기 떼",
				cn = "跳跳鱼群",
			},
		},
	
		[373440] = {
			readable = "Eternal Water",
			model = 353152,
			text = {
				en = "Eternal Water",
				es = "Agua eterna",
				de = "Äonenwasser",
				fr = "Eau éternelle",
				it = "Acqua Eterna",
				pt = "Água Eterna",
				ru = "Извечная вода",
				cn = "永恒之水",
			},
		},
	
		[373441] = {
			readable = "Aurelid Cluster",
			model = 219406,
			text = {
				en = "Aurelid Cluster",
				de = "Aurelidenschwarm",
				fr = "Groupe d’aurélidés",
				pt = "Aglomerado de Aurelídeos",
				ru = "Рой аурелидов",
				ko = "원시해파리 군집",
				cn = "元水母群",
			},
		},
	
		[373443] = {
			readable = "Firim's Portal",
			model = 359120,
			text = {
				en = "Firim's Portal",
				es = "Portal de Firim",
				de = "Firims Portal",
				fr = "Portail de Firim",
				it = "Portale di Firim",
				pt = "Portal de Firim",
				ru = "Портал Фирима",
				ko = "피림의 차원문",
				cn = "菲历姆的传送门",
			},
		},
	
		[373460] = {
			readable = "Fae Net",
			model = 3489771,
			text = {
				en = "Fae Net",
				de = "Faenetz",
				fr = "Filet faë",
				pt = "Rede Feéria",
				ru = "Волшебная сеть",
				cn = "法夜之网",
			},
		},
	
		[373461] = {
			readable = "Chromatic Rosid",
			model = 3581349,
			text = {
				en = "Chromatic Rosid",
				es = "Rósida cromática",
				de = "Chromatischer Rosid",
				fr = "Rosides chromatiques",
				it = "Roside Cromatica",
				pt = "Rosídeo Cromático",
				ru = "Многоцветный розид",
				ko = "오색 원시장미",
				cn = "多彩元蔷薇",
			},
		},
	
		[373463] = {
			readable = "Progenitor Relic",
			model = 4039280,
			text = {
				en = "Progenitor Relic",
				es = "Reliquia de progenitor",
				de = "Progenitorrelikt",
				fr = "Relique des Progéniteurs",
				it = "Reliquia dei Progenitori",
				pt = "Relíquia do Progenitor",
				ru = "Реликвия Прародителей",
				ko = "창시자 유물",
				cn = "元尊圣物",
			},
		},
	
		[373466] = {
			readable = "Catalyzed Apple",
			model = 4201287,
			text = {
				en = "Catalyzed Apple",
				es = "Manzana catalizada",
				de = "Katalysierter Apfel",
				fr = "Pomme catalysée",
				it = "Mela Catalizzata",
				pt = "Maçã Catalisada",
				ru = "Катализированное яблоко",
				ko = "촉매화된 사과",
				cn = "化生苹果",
			},
		},
	
		[373471] = {
			readable = "Mezzonic Cache",
			model = 4248046,
			text = {
				en = "Mezzonic Cache",
				es = "Alijo mezzónico",
				de = "Mezzonische Truhe",
				fr = "Cache mezzonique",
				it = "Cassa Mezzonica",
				pt = "Baú Mezônico",
				ru = "Меццонийский тайник",
				ko = "메조 보관함",
				cn = "中音宝箱",
			},
		},
	
		[373472] = {
			readable = "Glissandian Cache",
			model = 4248047,
			text = {
				en = "Glissandian Cache",
				es = "Alijo glissandiano",
				de = "Glissandische Truhe",
				fr = "Cache glissandienne",
				it = "Cassa Glissandiana",
				pt = "Baú Glissandiano",
				ru = "Глиссандрийский тайник",
				ko = "글리산도 보관함",
				cn = "滑音宝箱",
			},
		},
	
		[373473] = {
			readable = "Fugueal Cache",
			model = 4248048,
			text = {
				en = "Fugueal Cache",
				es = "Alijo de fuga",
				de = "Fugalische Truhe",
				fr = "Cache fuguéale",
				it = "Cassa Fuguelica",
				pt = "Baú Fugueal",
				ru = "Фугийский тайник",
				ko = "푸가 보관함",
				cn = "赋格宝箱",
			},
		},
	
		[373474] = {
			readable = "Cantaric Cache",
			model = 4248049,
			text = {
				en = "Cantaric Cache",
				es = "Alijo cantárico",
				de = "Kantarische Truhe",
				fr = "Cache cantabilienne",
				it = "Cassa Cantarica",
				pt = "Baú Cantárico",
				ru = "Кантарийский тайник",
				ko = "노래의 보관함",
				cn = "声乐宝箱",
			},
		},
	
		[373479] = {
			readable = "Sacred Relic",
			model = 4039282,
			text = {
				en = "Sacred Relic",
				es = "Reliquia sagrada",
				de = "Heiliges Relikt",
				fr = "Relique sacrée",
				it = "Reliquia Sacra",
				pt = "Relíquia Sagrada",
				ru = "Священная реликвия",
				ko = "신성한 유물",
				cn = "神圣圣物",
			},
		},
	
		[373482] = {
			readable = "Bolstering Spheroid",
			model = 166432,
			text = {
				en = "Bolstering Spheroid",
				es = "Esferoide reforzador",
				de = "Anstachelnde Sphäre",
				fr = "Sphéroïde de renforcement",
				it = "Sferoide di Rinforzo",
				pt = "Esferoide Encorajador",
				ru = "Усиливающая сфера",
				ko = "강화 회전체",
				cn = "强固球状体",
			},
		},
	
		[373483] = {
			readable = "Challenger's Cache",
			model = 1314905,
			text = {
				en = "Challenger's Cache",
				es = "Alijo de contendiente",
				de = "Schatz des Herausforderers",
				fr = "Cache de prétendant",
				it = "Cassa dello Sfidante",
				pt = "Baú do Desafiante",
				ru = "Тайник претендента",
				ko = "도전자의 보관함",
				cn = "挑战者的箱子",
			},
		},
	
		[373484] = {
			readable = "Challenger's Cache",
			model = 1314905,
			text = {
				en = "Challenger's Cache",
				es = "Alijo de contendiente",
				de = "Schatz des Herausforderers",
				fr = "Cache de prétendant",
				it = "Cassa dello Sfidante",
				pt = "Baú do Desafiante",
				ru = "Тайник претендента",
				ko = "도전자의 보관함",
				cn = "挑战者的箱子",
			},
		},
	
		[373485] = {
			readable = "Enigmatic Scrolls",
			model = 3836266,
			text = {
				en = "Enigmatic Scrolls",
				es = "Pergaminos enigmáticos",
				de = "Rätselhafte Schriftrollen",
				fr = "Parchemins énigmatiques",
				it = "Pergamene Enigmatiche",
				pt = "Pergaminhos Enigmáticos",
				ru = "Загадочные свитки",
				ko = "수수께끼의 두루마리",
				cn = "神秘卷轴",
			},
		},
	
		[373494] = {
			readable = "Fractal Cypher B",
			model = 4201279,
			text = {
				en = "Fractal Cypher B",
				es = "Clave fractal B",
				de = "Fraktalchiffre B",
				fr = "Cryptogramme fractal B",
				it = "Codice Frattale B",
				pt = "Cifra Fractal B",
				ru = "Фрактальный шифр B",
				cn = "分形密文B",
			},
		},
	
		[373495] = {
			readable = "Fractal Cypher C",
			model = 4201279,
			text = {
				en = "Fractal Cypher C",
				es = "Clave fractal C",
				de = "Fraktalchiffre C",
				fr = "Cryptogramme fractal C",
				it = "Codice Frattale C",
				pt = "Cifra Fractal C",
				ru = "Фрактальный шифр C",
				cn = "分形密文C",
			},
		},
	
		[373496] = {
			readable = "Sample Container",
			model = 3565798,
			text = {
				en = "Sample Container",
				es = "Contenedor de muestras",
				de = "Probenbehälter",
				fr = "Récipient pour échantillons",
				it = "Contenitore per Campioni",
				pt = "Recipiente da Amostra",
				ru = "Резервуар для проб",
				ko = "견본 용기",
				cn = "样品容器",
			},
		},
	
		[373497] = {
			readable = "Mawsteel Shard",
			model = 4253903,
			text = {
				en = "Mawsteel Shard",
				es = "Esquirla de acero de Las Fauces",
				de = "Schlundstahlsplitter",
				fr = "Éclat d’antracier",
				it = "Scheggia di Fauciacciaio",
				pt = "Estilhaço de Aço-da-gorja",
				ru = "Осколок стали Утробы",
				ko = "나락강철 조각",
				cn = "渊钢碎片",
			},
		},
	
		[373501] = {
			readable = "Catalyst Wards Lock",
			model = 3923426,
			text = {
				en = "Catalyst Wards Lock",
				es = "Cierre de los Distritos Catalizadores",
				de = "Schloss der Katalysatorstationen",
				fr = "Verrou des champs Catalyseurs",
				it = "Serratura delle Protezioni Catalizzatrici",
				pt = "Tranca da Zona de Catalisação",
				ru = "Замок Двора Катализатора",
				ko = "촉매의 성역 자물쇠",
				cn = "化生之庭的锁",
			},
		},
	
		[373503] = {
			readable = "Repository Console",
			model = 4198154,
			text = {
				en = "Repository Console",
				es = "Consola de repositorio",
				de = "Repositoriumskonsole",
				fr = "Console de dépôt",
				it = "Console del Deposito",
				pt = "Console Repositório",
				ru = "Консоль репозитория",
				ko = "보관소 제어장치",
				cn = "贮藏所控制台",
			},
		},
	
		[373505] = {
			readable = "Targeting Relic",
			model = 4039286,
			text = {
				en = "Targeting Relic",
				es = "Reliquia seleccionadora",
				de = "Zielrelikt",
				fr = "Relique de ciblage",
				it = "Reliquia della Mira",
				pt = "Relíquia Alvo",
				ru = "Реликвия-указатель",
				ko = "목표 선택 유물",
				cn = "定位圣物",
			},
		},
	
		[373506] = {
			readable = "Bloomthorn Barrier",
			model = 4285702,
			text = {
				en = "Bloomthorn Barrier",
				es = "Barrera florespina",
				de = "Blühdornbarriere",
				fr = "Barrière florépine",
				it = "Barriera Sbocciaspina",
				pt = "Barreira Florespinho",
				ru = "Преграда из колючих цветов",
				ko = "만개가시 방벽",
				cn = "花棘屏障",
			},
		},
	
		[373507] = {
			readable = "Catalyst Wards Lock",
			model = 3923426,
			text = {
				en = "Catalyst Wards Lock",
				es = "Cierre de los Distritos Catalizadores",
				de = "Schloss der Katalysatorstationen",
				fr = "Verrou des champs Catalyseurs",
				it = "Serratura delle Protezioni Catalizzatrici",
				pt = "Tranca das Proteções do Catalisador",
				ru = "Замок Двора Катализатора",
				ko = "촉매의 성역 자물쇠",
				cn = "化生之庭的锁",
			},
		},
	
		[373514] = {
			readable = "Mawsteel Shard",
			model = 4253903,
			text = {
				en = "Mawsteel Shard",
				es = "Esquirla de acero de Las Fauces",
				de = "Schlundstahlsplitter",
				fr = "Éclat d’antracier",
				it = "Scheggia di Fauciacciaio",
				pt = "Estilhaço de Aço-da-gorja",
				ru = "Осколок стали Утробы",
				ko = "나락강철 조각",
				cn = "渊钢碎片",
			},
		},
	
		[373517] = {
			readable = "Place Shard",
			model = 3615456,
			text = {
				en = "Place Shard",
				es = "Colocar fragmento",
				de = "Splitter platzieren",
				fr = "Placer l’éclat",
				it = "Piazzamento Scheggia",
				pt = "Colocar Estilhaço",
				ru = "Установить осколок",
				ko = "조각 놓기",
				cn = "放置碎片",
			},
		},
	
		[373519] = {
			readable = "Restoration Matrix",
			model = 3923432,
			text = {
				en = "Restoration Matrix",
				es = "Matriz de restauración",
				de = "Wiederherstellungsmatrix",
				fr = "Matrice de restauration",
				it = "Matrice di Rigenerazione",
				pt = "Matriz de Restauração",
				ru = "Матрица восстановления",
				ko = "복원 행렬",
				cn = "修复矩阵",
			},
		},
	
		[373521] = {
			readable = "Emergency Broker Portal",
			model = 3540722,
			text = {
				en = "Emergency Broker Portal",
				es = "Portal de emergencia de los Especuladores",
				de = "Mittlernotportal",
				fr = "Portail de secours des négociants",
				it = "Portale degli Alienatori d'Emergenza",
				pt = "Portal de Emergência do Corretor",
				ru = "Аварийный портал брокеров",
				ko = "비상용 중개자 차원문",
				cn = "紧急掮灵传送门",
			},
		},
	
		[373525] = {
			readable = "Place Shard",
			model = 3615457,
			text = {
				en = "Place Shard",
				es = "Colocar fragmento",
				de = "Splitter platzieren",
				fr = "Placer l’éclat",
				it = "Piazzamento Scheggia",
				pt = "Colocar Estilhaço",
				ru = "Установить осколок",
				ko = "조각 놓기",
				cn = "放置碎片",
			},
		},
	
		[373526] = {
			readable = "Place Shard",
			model = 3615458,
			text = {
				en = "Place Shard",
				es = "Colocar fragmento",
				de = "Splitter platzieren",
				fr = "Placer l’éclat",
				it = "Piazzamento Scheggia",
				pt = "Colocar Estilhaço",
				ru = "Установить осколок",
				ko = "조각 놓기",
				cn = "放置碎片",
			},
		},
	
		[373527] = {
			readable = "Place Shard",
			model = 3615459,
			text = {
				en = "Place Shard",
				es = "Colocar fragmento",
				de = "Splitter platzieren",
				fr = "Placer l’éclat",
				it = "Piazzamento Scheggia",
				pt = "Colocar Estilhaço",
				ru = "Установить осколок",
				ko = "조각 놓기",
				cn = "放置碎片",
			},
		},
	
		[373529] = {
			readable = "Tranquil Concordance",
			model = 4198153,
			text = {
				en = "Tranquil Concordance",
				es = "Concordancia tranquila",
				de = "Stille Konkordanz",
				fr = "Harmonique serein",
				it = "Indice Tranquillo",
				pt = "Concordância Tranquila",
				ru = "Безмятежный конкорданс",
				ko = "평온의 색인",
				cn = "宁静索引台",
			},
		},
	
		[373533] = {
			readable = "Mawsteel Shard",
			model = 4253903,
			text = {
				en = "Mawsteel Shard",
				es = "Esquirla de acero de Las Fauces",
				de = "Schlundstahlsplitter",
				fr = "Éclat d’antracier",
				it = "Scheggia di Fauciacciaio",
				pt = "Estilhaço de Aço-da-gorja",
				ru = "Осколок стали Утробы",
				ko = "나락강철 조각",
				cn = "渊钢碎片",
			},
		},
	
		[373534] = {
			readable = "Mawsteel Shard",
			model = 4253903,
			text = {
				en = "Mawsteel Shard",
				es = "Esquirla de acero de Las Fauces",
				de = "Schlundstahlsplitter",
				fr = "Éclat d’antracier",
				it = "Scheggia di Fauciacciaio",
				pt = "Estilhaço de Aço-da-gorja",
				ru = "Осколок стали Утробы",
				ko = "나락강철 조각",
				cn = "渊钢碎片",
			},
		},
	
		[373535] = {
			readable = "Lore Stone Fragment",
			model = 4196520,
			text = {
				en = "Lore Stone Fragment",
				es = "Fragmento de piedra de conocimiento",
				de = "Wissenssteinfragment",
				fr = "Fragment de pierre référentielle",
				it = "Frammento di Pietra della Storia",
				pt = "Fragmento da Pedra da História",
				ru = "Фрагмент камня знаний",
				ko = "지식의 돌 조각",
				cn = "知识之石碎片",
			},
		},
	
		[373536] = {
			readable = "Tranquil Concordance",
			model = 4198153,
			text = {
				en = "Tranquil Concordance",
				es = "Concordancia tranquila",
				de = "Stille Konkordanz",
				fr = "Harmonique serein",
				it = "Indice Tranquillo",
				pt = "Concordância Tranquila",
				ru = "Безмятежный конкорданс",
				ko = "평온의 색인",
				cn = "宁静索引台",
			},
		},
	
		[373537] = {
			readable = "Tranquil Concordance",
			model = 4198153,
			text = {
				en = "Tranquil Concordance",
				es = "Concordancia tranquila",
				de = "Stille Konkordanz",
				fr = "Harmonique serein",
				it = "Indice Tranquillo",
				pt = "Concordância Tranquila",
				ru = "Безмятежный конкорданс",
				ko = "평온의 색인",
				cn = "宁静索引台",
			},
		},
	
		[373543] = {
			readable = "Library Vault",
			model = 4196523,
			text = {
				en = "Library Vault",
				es = "Cámara de la biblioteca",
				de = "Bibliotheksarchiv",
				fr = "Caveau de la bibliothèque",
				it = "Scrigno della Biblioteca",
				pt = "Cripta da Biblioteca",
				ru = "Хранилище библиотеки",
				ko = "도서관 금고",
				cn = "图书馆宝箱",
			},
		},
	
		[373544] = {
			readable = "Tablet",
			model = 4178677,
			text = {
				en = "Tablet",
				es = "Tablilla",
				de = "Tafel",
				fr = "Tablette",
				it = "Tavoletta",
				pt = "Tabuleta",
				ru = "Табличка",
				ko = "서판",
				cn = "石板",
			},
		},
	
		[373545] = {
			readable = "Tablet",
			model = 4178676,
			text = {
				en = "Tablet",
				es = "Tablilla",
				de = "Tafel",
				fr = "Tablette",
				it = "Tavoletta",
				pt = "Tabuleta",
				ru = "Табличка",
				ko = "서판",
				cn = "石板",
			},
		},
	
		[373546] = {
			readable = "Tablet",
			model = 4178677,
			text = {
				en = "Tablet",
				es = "Tablilla",
				de = "Tafel",
				fr = "Tablette",
				it = "Tavoletta",
				pt = "Tabuleta",
				ru = "Табличка",
				ko = "서판",
				cn = "石板",
			},
		},
	
		[373547] = {
			readable = "Tablet",
			model = 4178676,
			text = {
				en = "Tablet",
				es = "Tablilla",
				de = "Tafel",
				fr = "Tablette",
				it = "Tavoletta",
				pt = "Tabuleta",
				ru = "Табличка",
				ko = "서판",
				cn = "石板",
			},
		},
	
		[373548] = {
			readable = "Template Archive",
			model = 4198154,
			text = {
				en = "Template Archive",
				es = "Archivo de plantilla",
				de = "Vorlagenarchiv",
				fr = "Modèle d’archive",
				it = "Archivio dei Progetti",
				pt = "Arquivo Modelo",
				ru = "Архив образцов",
				ko = "형판 보관소",
				cn = "模板档案",
			},
		},
	
		[373551] = {
			readable = "Orb",
			model = 4226692,
			text = {
				en = "Orb",
				es = "Orbe",
				de = "Kugel",
				fr = "Orbe",
				it = "Globo",
				pt = "Orbe",
				ru = "Сфера",
				ko = "보주",
				cn = "宝珠",
			},
		},
	
		[373553] = {
			readable = "Tranquil Concordance",
			model = 4196518,
			text = {
				en = "Tranquil Concordance",
				es = "Teletransportador",
				de = "Teleporter",
				fr = "Téléporteur",
				it = "Teletrasporto",
				pt = "Teleportador",
				ru = "Телепорт",
				ko = "순간이동기",
				cn = "传送器",
			},
		},
	
		[373554] = {
			readable = "Tranquil Concordance",
			model = 4198153,
			text = {
				en = "Tranquil Concordance",
				es = "Concordancia tranquila",
				de = "Stille Konkordanz",
				fr = "Harmonique serein",
				it = "Indice Tranquillo",
				pt = "Concordância Tranquila",
				ru = "Безмятежный конкорданс",
				ko = "평온의 색인",
				cn = "宁静索引台",
			},
		},
	
		[373561] = {
			readable = "Forgotten Proto-Vault",
			model = 4196523,
			text = {
				en = "Forgotten Proto-Vault",
				es = "Protocámara olvidada",
				de = "Vergessenes Protoarchiv",
				fr = "Proto-chambre oubliée",
				it = "Proto-Cripta Dimenticata",
				pt = "Protocripta Esquecida",
				ru = "Забытое протохранилище",
				ko = "잊힌 금고 원형",
				cn = "遗忘的原型宝库",
			},
		},
	
		[373562] = {
			readable = "Excitable Concordance",
			model = 4198153,
			text = {
				en = "Excitable Concordance",
				es = "Concordancia excitable",
				de = "Erregbare Konkordanz",
				fr = "Harmonique fébrile",
				it = "Indice Emozionante",
				pt = "Concordância Excêntrica",
				ru = "Волнующий конкорданс",
				ko = "격앙의 색인",
				cn = "可激发的索引台",
			},
		},
	
		[373563] = {
			readable = "Mercurial Concordance",
			model = 4198153,
			text = {
				en = "Mercurial Concordance",
				es = "Concordancia voluble",
				de = "Wechselhafte Konkordanz",
				fr = "Harmonique changeant",
				it = "Indice Mercuriale",
				pt = "Concordância Mercurial",
				ru = "Оживленный конкорданс",
				ko = "변덕의 색인",
				cn = "善变索引台",
			},
		},
	
		[373568] = {
			readable = "Provis Cache",
			model = 4196523,
			text = {
				en = "Provis Cache",
				es = "Alijo de Provis cerrado",
				de = "Verschlossene Provistruhe",
				fr = "Cache verrouillée de Provis",
				it = "Cassa di Provis Chiusa",
				pt = "Depósito Provis Trancado",
				ru = "Запертый тайник провиза",
				ko = "잠긴 공급지 보관함",
				cn = "锁住的供给扇区宝箱",
			},
		},
	
		[373569] = {
			readable = "Catalyst Barrier Console",
			model = 3923426,
			text = {
				en = "Catalyst Barrier Console",
				es = "Consola de barrera catalizadora",
				de = "Katalysatorbarrierenkonsole",
				fr = "Console de la barrière catalytique",
				it = "Console della Barriera Catalizzatrice",
				pt = "Console de Barreira do Catalisador",
				ru = "Консоль барьера катализатора",
				ko = "촉매 방벽 장치",
				cn = "化生屏障控制台",
			},
		},
	
		[373570] = {
			readable = "Catalyst Barrier Console",
			model = 3923426,
			text = {
				en = "Catalyst Barrier Console",
				es = "Consola de barrera catalizadora",
				de = "Katalysatorbarrierenkonsole",
				fr = "Console de la barrière catalytique",
				it = "Console della Barriera Catalizzatrice",
				pt = "Console de Barreira do Catalisador",
				ru = "Консоль барьера катализатора",
				ko = "촉매 방벽 장치",
				cn = "化生屏障控制台",
			},
		},
	
		[373576] = {
			readable = "Sensory Synchronizer",
			model = 3605387,
			text = {
				en = "Sensory Synchronizer",
				es = "Sincronizador sensorial",
				de = "Sensorischer Synchronisierer",
				fr = "Synchroniseur sensoriel",
				it = "Sincronizzatore Sensoriale",
				pt = "Sincronizador Sensorial",
				ru = "Сенсорный синхронизатор",
				ko = "감각 동기화 장치",
				cn = "感官同步器",
			},
		},
	
		[373577] = {
			readable = "Firim's Portal",
			model = 3311515,
			text = {
				en = "Firim's Portal",
				es = "Portal de Firim",
				de = "Firims Portal",
				fr = "Portail de Firim",
				it = "Portale di Firim",
				pt = "Portal de Firim",
				ru = "Портал Фирима",
				ko = "피림의 차원문",
				cn = "菲历姆的传送门",
			},
		},
	
		[373579] = {
			readable = "Prying Eye Discovery",
			model = 4039282,
			text = {
				en = "Prying Eye Discovery",
				es = "Descubrimiento de ojo fisgón",
				de = "Entdeckung des Spürauges",
				fr = "Découverte d’œil indiscret",
				it = "Scoperta dell'Occhio Indiscreto",
				pt = "Descoberta do Olho Perscrutador",
				ru = "Находка любопытных",
				ko = "감시 기계의 발견물",
				cn = "窥探之眼的发现",
			},
		},
	
		[373580] = {
			readable = "Tranquil Concordance",
			model = 4198153,
			text = {
				en = "Tranquil Concordance",
				es = "Concordancia tranquila",
				de = "Stille Konkordanz",
				fr = "Harmonique serein",
				it = "Indice Tranquillo",
				pt = "Concordância Tranquila",
				ru = "Безмятежный конкорданс",
				ko = "평온의 색인",
				cn = "宁静索引台",
			},
		},
	
		[373581] = {
			readable = "Excitable Concordance",
			model = 4198153,
			text = {
				en = "Excitable Concordance",
				es = "Concordancia excitable",
				de = "Erregbare Konkordanz",
				fr = "Harmonique fébrile",
				it = "Indice Emozionante",
				pt = "Concordância Excêntrica",
				ru = "Волнующий конкорданс",
				ko = "격앙의 색인",
				cn = "可激发的索引台",
			},
		},
	
		[373582] = {
			readable = "Mercurial Concordance",
			model = 4198153,
			text = {
				en = "Mercurial Concordance",
				es = "Concordancia voluble",
				de = "Wechselhafte Konkordanz",
				fr = "Harmonique changeant",
				it = "Indice Mercuriale",
				pt = "Concordância Mercurial",
				ru = "Оживленный конкорданс",
				ko = "변덕의 색인",
				cn = "善变索引台",
			},
		},
	
		[373583] = {
			readable = "Tranquil Concordance",
			model = 4198153,
			text = {
				en = "Tranquil Concordance",
				es = "Concordancia tranquila",
				de = "Stille Konkordanz",
				fr = "Harmonique serein",
				it = "Indice Tranquillo",
				pt = "Concordância Tranquila",
				ru = "Безмятежный конкорданс",
				ko = "평온의 색인",
				cn = "宁静索引台",
			},
		},
	
		[373584] = {
			readable = "Excitable Concordance",
			model = 4198153,
			text = {
				en = "Excitable Concordance",
				es = "Concordancia excitable",
				de = "Erregbare Konkordanz",
				fr = "Harmonique fébrile",
				it = "Indice Emozionante",
				pt = "Concordância Excêntrica",
				ru = "Волнующий конкорданс",
				ko = "격앙의 색인",
				cn = "可激发的索引台",
			},
		},
	
		[373585] = {
			readable = "Mercurial Concordance",
			model = 4198153,
			text = {
				en = "Mercurial Concordance",
				es = "Concordancia voluble",
				de = "Wechselhafte Konkordanz",
				fr = "Harmonique changeant",
				it = "Indice Mercuriale",
				pt = "Concordância Mercurial",
				ru = "Оживленный конкорданс",
				ko = "변덕의 색인",
				cn = "善变索引台",
			},
		},
	
		[373586] = {
			readable = "Tranquil Concordance",
			model = 4198153,
			text = {
				en = "Tranquil Concordance",
				es = "Concordancia tranquila",
				de = "Stille Konkordanz",
				fr = "Harmonique serein",
				it = "Indice Tranquillo",
				pt = "Concordância Tranquila",
				ru = "Безмятежный конкорданс",
				ko = "평온의 색인",
				cn = "宁静索引台",
			},
		},
	
		[373587] = {
			readable = "Excitable Concordance",
			model = 4198153,
			text = {
				en = "Excitable Concordance",
				es = "Concordancia excitable",
				de = "Erregbare Konkordanz",
				fr = "Harmonique fébrile",
				it = "Indice Emozionante",
				pt = "Concordância Excêntrica",
				ru = "Волнующий конкорданс",
				ko = "격앙의 색인",
				cn = "可激发的索引台",
			},
		},
	
		[373588] = {
			readable = "Mercurial Concordance",
			model = 4198153,
			text = {
				en = "Mercurial Concordance",
				es = "Concordancia voluble",
				de = "Wechselhafte Konkordanz",
				fr = "Harmonique changeant",
				it = "Indice Mercuriale",
				pt = "Concordância Mercurial",
				ru = "Оживленный конкорданс",
				ko = "변덕의 색인",
				cn = "善变索引台",
			},
		},
	
		[373592] = {
			readable = "Ancient Waystone",
			model = 4288526,
			text = {
				en = "Ancient Waystone",
				es = "Piedra de puerta ancestral",
				de = "Uralter Portalstein",
				fr = "Pierre d’accès antique",
				it = "Pietra di Transito Antica",
				pt = "Pedra de Pórtico Antiga",
				ru = "Древний путевой камень",
				ko = "고대 차원석",
				cn = "远古道标石",
			},
		},
	
		[373594] = {
			readable = "Primus Locus Arrangement",
			model = 4081532,
			text = {
				en = "Primus Locus Arrangement",
				es = "Disposición del Enclave Primus",
				de = "Anordnung des Primus Locus",
				fr = "Agencement du locus primus",
				it = "Disposizione del Locus Primus",
				pt = "Arranjo de Lócus Primus",
				ru = "Первая конфигурация Локуса",
				ko = "제1의 공간 정렬",
				cn = "第一位点指向",
			},
		},
	
		[373595] = {
			readable = "Brazier of Progressive Power",
			model = 3038198,
			text = {
				en = "Brazier of Progressive Power",
				de = "Kohlenpfanne der fortschreitenden Macht",
				it = "Braciere del Potere Progressivo",
				pt = "Braseiro do Poder Progressivo",
				ru = "Жаровня растущей мощи",
			},
		},
	
		[373597] = {
			readable = "Brazier of Progressive Power",
			model = 2994771,
			text = {
				en = "Brazier of Progressive Power",
				es = "Blandón de poder progresivo",
				de = "Kohlenpfanne der fortschreitenden Macht",
				fr = "Brasero de puissance progressive",
				it = "Braciere del Potere Progressivo",
				pt = "Braseiro do Poder Progressivo",
				ru = "Жаровня растущей мощи",
				ko = "진취적인 힘의 화로",
			},
		},
	
		[373614] = {
			readable = "Quartus Locus Arrangement",
			model = 4081533,
			text = {
				en = "Quartus Locus Arrangement",
				es = "Disposición del Enclave Quartus",
				de = "Anordnung des Quartus Locus",
				fr = "Agencement du locus quartus",
				it = "Disposizione del Locus Quartus",
				pt = "Arranjo de Lócus Quartus",
				ru = "Четвертая конфигурация Локуса",
				ko = "제4의 공간 정렬",
				cn = "第四位点指向",
			},
		},
	
		[373615] = {
			readable = "Quintus Locus Arrangement",
			model = 4081527,
			text = {
				en = "Quintus Locus Arrangement",
				es = "Disposición del Enclave Quintus",
				de = "Anordnung des Quintus Locus",
				fr = "Agencement du locus quintus",
				it = "Disposizione del Locus Quintus",
				pt = "Arranjo de Lócus Quintus",
				ru = "Пятая конфигурация Локуса",
				ko = "제5의 공간 정렬",
				cn = "第五位点指向",
			},
		},
	
		[373616] = {
			readable = "Ripening Nectar",
			model = 4080351,
			text = {
				en = "Ripening Nectar",
				es = "Néctar en maduración",
				de = "Reifender Nektar",
				fr = "Nectar mûrissant",
				it = "Nettare in Maturazione",
				pt = "Néctar do Amadurecimento",
				ru = "Поспевающий нектар",
				ko = "숙성된 감로",
				cn = "成熟中的蜜露",
			},
		},
	
		[373618] = {
			readable = "Ingress Phrase",
			model = 4267689,
			text = {
				en = "Ingress Phrase",
				es = "Frase de acceso",
				de = "Losung",
				fr = "Formule d’accès",
				it = "Frase d'Ingresso",
				pt = "Frase de Ingresso",
				ru = "Слова доступа",
				ko = "입장의 구절",
				cn = "准入短语",
			},
		},
	
		[373621] = {
			readable = "Suspiciously Angry Vault",
			model = 4198154,
			text = {
				en = "Suspiciously Angry Vault",
				es = "Cámara sospechosamente enfadada",
				de = "Verdächtig wütender Tresor",
				fr = "Coffre étrangement remonté",
				it = "Cripta Sospettosamente Arrabbiata",
				pt = "Cripta Suspeitamente Furiosa",
				ru = "Подозрительно рассерженное хранилище",
				ko = "수상하게 성난 금고",
				cn = "可疑之怒宝箱",
			},
		},
	
		[373648] = {
			readable = "Empowered Key",
			model = 3948802,
			text = {
				en = "Empowered Key",
				es = "Llave potenciada",
				de = "Ermächtigter Schlüssel",
				fr = "Clé renforcée",
				it = "Chiave Potenziata",
				pt = "Chave Potencializada",
				ru = "Усиленный ключ",
				ko = "강화된 열쇠",
				cn = "强化钥匙",
			},
		},
	
		[373649] = {
			readable = "Ingress Phrase",
			model = 4267690,
			text = {
				en = "Ingress Phrase",
				es = "Frase de acceso",
				de = "Losung",
				fr = "Formule d’accès",
				it = "Frase d'Ingresso",
				pt = "Frase de Ingresso",
				ru = "Слова доступа",
				ko = "입장의 구절",
				cn = "准入短语",
			},
		},
	
		[373650] = {
			readable = "Empowered Key",
			model = 3948800,
			text = {
				en = "Empowered Key",
				es = "Llave potenciada",
				de = "Ermächtigter Schlüssel",
				fr = "Clé renforcée",
				it = "Chiave Potenziata",
				pt = "Chave Potencializada",
				ru = "Усиленный ключ",
				ko = "강화된 열쇠",
				cn = "强化钥匙",
			},
		},
	
		[373651] = {
			readable = "Empowered Key",
			model = 3948799,
			text = {
				en = "Empowered Key",
				es = "Llave potenciada",
				de = "Ermächtigter Schlüssel",
				fr = "Clé renforcée",
				it = "Chiave Potenziata",
				pt = "Chave Potencializada",
				ru = "Усиленный ключ",
				ko = "강화된 열쇠",
				cn = "强化钥匙",
			},
		},
	
		[373678] = {
			readable = "Shield Conduit",
			model = 3591258,
			text = {
				en = "Shield Conduit",
				es = "Conducto de escudo",
				de = "Schildleitung",
				fr = "Pylône de protection",
				it = "Condotto dello Scudo",
				pt = "Conduíte de Escudo",
				ru = "Проводник щита",
				ko = "보호막 도관",
				cn = "护盾导体",
			},
		},
	
		[373679] = {
			readable = "Shield Conduit",
			model = 3591258,
			text = {
				en = "Shield Conduit",
				es = "Conducto de escudo",
				de = "Schildleitung",
				fr = "Pylône de protection",
				it = "Condotto dello Scudo",
				pt = "Conduíte de Escudo",
				ru = "Проводник щита",
				ko = "보호막 도관",
				cn = "护盾导体",
			},
		},
	
		[373680] = {
			readable = "Shield Conduit",
			model = 3591258,
			text = {
				en = "Shield Conduit",
				es = "Conducto de escudo",
				de = "Schildleitung",
				fr = "Pylône de protection",
				it = "Condotto dello Scudo",
				pt = "Conduíte de Escudo",
				ru = "Проводник щита",
				ko = "보호막 도관",
				cn = "护盾导体",
			},
		},
	
		[373681] = {
			readable = "Shield Conduit",
			model = 3591258,
			text = {
				en = "Shield Conduit",
				es = "Conducto de escudo",
				de = "Schildleitung",
				fr = "Pylône de protection",
				it = "Condotto dello Scudo",
				pt = "Conduíte de Escudo",
				ru = "Проводник щита",
				ko = "보호막 도관",
				cn = "护盾导体",
			},
		},
	
		[373961] = {
			readable = "Rune Tile",
			model = 4196518,
			text = {
				en = "Rune Tile",
				es = "Baldosa rúnica",
				de = "Runenkachel",
				fr = "Dalle runique",
				it = "Piastrella di Rune",
				pt = "Quadrado Rúnico",
				ru = "Руническая плита",
				ko = "룬 벽돌바닥",
				cn = "符文地砖",
			},
		},
	
		[373962] = {
			readable = "Rune Tile",
			model = 4196518,
			text = {
				en = "Rune Tile",
				es = "Baldosa rúnica",
				de = "Runenkachel",
				fr = "Dalle runique",
				it = "Piastrella di Rune",
				pt = "Quadrado Rúnico",
				ru = "Руническая плита",
				ko = "룬 벽돌바닥",
				cn = "符文地砖",
			},
		},
	
		[373963] = {
			readable = "Rune Tile",
			model = 4196518,
			text = {
				en = "Rune Tile",
				es = "Baldosa rúnica",
				de = "Runenkachel",
				fr = "Dalle runique",
				it = "Piastrella di Rune",
				pt = "Quadrado Rúnico",
				ru = "Руническая плита",
				ko = "룬 벽돌바닥",
				cn = "符文地砖",
			},
		},
	
		[373964] = {
			readable = "Rune Tile",
			model = 4196518,
			text = {
				en = "Rune Tile",
				es = "Baldosa rúnica",
				de = "Runenkachel",
				fr = "Dalle runique",
				it = "Piastrella di Rune",
				pt = "Quadrado Rúnico",
				ru = "Руническая плита",
				ko = "룬 벽돌바닥",
				cn = "符文地砖",
			},
		},
	
		[373965] = {
			readable = "Rune Tile",
			model = 4196518,
			text = {
				en = "Rune Tile",
				es = "Baldosa rúnica",
				de = "Runenkachel",
				fr = "Dalle runique",
				it = "Piastrella di Rune",
				pt = "Quadrado Rúnico",
				ru = "Руническая плита",
				ko = "룬 벽돌바닥",
				cn = "符文地砖",
			},
		},
})
do ObjectDB[objectID] = objectData; end
