local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	
		[242037] = {
			readable = "Wall Lamp",
			model = 194470,
			text = {
				en = "Wall Lamp",
				es = "Farol de pared",
				de = "Wandlampe",
				fr = "Lampe murale",
				it = "Lampione da Muro",
				pt = "Lâmpada de Parede",
				ru = "Настенный светильник",
				ko = "벽 등불",
				cn = "壁灯",
			},
		},
	
		[242038] = {
			readable = "Wall Lamp",
			model = 194470,
			text = {
				en = "Wall Lamp",
				es = "Farol de pared",
				de = "Wandlampe",
				fr = "Lampe murale",
				it = "Lampione da Muro",
				pt = "Lâmpada de Parede",
				ru = "Настенный светильник",
				ko = "벽 등불",
				cn = "壁灯",
			},
		},
	
		[242040] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
	
		[242043] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
	
		[242047] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
	
		[242052] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
	
		[242118] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
	
		[242123] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
	
		[242125] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
	
		[242131] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
	
		[242169] = {
			readable = "Wall Lamp",
			model = 194470,
			text = {
				en = "Wall Lamp",
				es = "Farol de pared",
				de = "Wandlampe",
				fr = "Lampe murale",
				it = "Lampione da Muro",
				pt = "Lâmpada de Parede",
				ru = "Настенный светильник",
				ko = "벽 등불",
				cn = "壁灯",
			},
		},
	
		[242170] = {
			readable = "Wall Lamp",
			model = 194470,
			text = {
				en = "Wall Lamp",
				es = "Farol de pared",
				de = "Wandlampe",
				fr = "Lampe murale",
				it = "Lampione da Muro",
				pt = "Lâmpada de Parede",
				ru = "Настенный светильник",
				ko = "벽 등불",
				cn = "壁灯",
			},
		},
	
		[242176] = {
			readable = "Wall Lamp",
			model = 194470,
			text = {
				en = "Wall Lamp",
				es = "Farol de pared",
				de = "Wandlampe",
				fr = "Lampe murale",
				it = "Lampione da Muro",
				pt = "Lâmpada de Parede",
				ru = "Настенный светильник",
				ko = "벽 등불",
				cn = "壁灯",
			},
		},
	
		[242177] = {
			readable = "Wall Lamp",
			model = 194470,
			text = {
				en = "Wall Lamp",
				es = "Farol de pared",
				de = "Wandlampe",
				fr = "Lampe murale",
				it = "Lampione da Muro",
				pt = "Lâmpada de Parede",
				ru = "Настенный светильник",
				ko = "벽 등불",
				cn = "壁灯",
			},
		},
	
		[242202] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
	
		[242215] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
	
		[242223] = {
			readable = "Wall Lamp",
			model = 194470,
			text = {
				en = "Wall Lamp",
				es = "Farol de pared",
				de = "Wandlampe",
				fr = "Lampe murale",
				it = "Lampione da Muro",
				pt = "Lâmpada de Parede",
				ru = "Настенный светильник",
				ko = "벽 등불",
				cn = "壁灯",
			},
		},
	
		[242224] = {
			readable = "Wall Lamp",
			model = 194470,
			text = {
				en = "Wall Lamp",
				es = "Farol de pared",
				de = "Wandlampe",
				fr = "Lampe murale",
				it = "Lampione da Muro",
				pt = "Lâmpada de Parede",
				ru = "Настенный светильник",
				ko = "벽 등불",
				cn = "壁灯",
			},
		},
	
		[242225] = {
			readable = "Wall Lamp",
			model = 194470,
			text = {
				en = "Wall Lamp",
				es = "Farol de pared",
				de = "Wandlampe",
				fr = "Lampe murale",
				it = "Lampione da Muro",
				pt = "Lâmpada de Parede",
				ru = "Настенный светильник",
				ko = "벽 등불",
				cn = "壁灯",
			},
		},
	
		[242226] = {
			readable = "Wall Lamp",
			model = 194470,
			text = {
				en = "Wall Lamp",
				es = "Farol de pared",
				de = "Wandlampe",
				fr = "Lampe murale",
				it = "Lampione da Muro",
				pt = "Lâmpada de Parede",
				ru = "Настенный светильник",
				ko = "벽 등불",
				cn = "壁灯",
			},
		},
	
		[242227] = {
			readable = "Wall Lamp",
			model = 194470,
			text = {
				en = "Wall Lamp",
				es = "Farol de pared",
				de = "Wandlampe",
				fr = "Lampe murale",
				it = "Lampione da Muro",
				pt = "Lâmpada de Parede",
				ru = "Настенный светильник",
				ko = "벽 등불",
				cn = "壁灯",
			},
		},
	
		[242228] = {
			readable = "Wall Lamp",
			model = 194470,
			text = {
				en = "Wall Lamp",
				es = "Farol de pared",
				de = "Wandlampe",
				fr = "Lampe murale",
				it = "Lampione da Muro",
				pt = "Lâmpada de Parede",
				ru = "Настенный светильник",
				ko = "벽 등불",
				cn = "壁灯",
			},
		},
	
		[242229] = {
			readable = "Wall Lamp",
			model = 194470,
			text = {
				en = "Wall Lamp",
				es = "Farol de pared",
				de = "Wandlampe",
				fr = "Lampe murale",
				it = "Lampione da Muro",
				pt = "Lâmpada de Parede",
				ru = "Настенный светильник",
				ko = "벽 등불",
				cn = "壁灯",
			},
		},
	
		[242230] = {
			readable = "Wall Lamp",
			model = 194470,
			text = {
				en = "Wall Lamp",
				es = "Farol de pared",
				de = "Wandlampe",
				fr = "Lampe murale",
				it = "Lampione da Muro",
				pt = "Lâmpada de Parede",
				ru = "Настенный светильник",
				ko = "벽 등불",
				cn = "壁灯",
			},
		},
	
		[242233] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
	
		[242234] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
	
		[242235] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
	
		[242242] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[242249] = {
			readable = "Partially Mined Apexis Crystal",
			model = 975539,
			text = {
				en = "Partially Mined Apexis Crystal",
				es = "Cristal apexis parcialmente extraído",
				de = "Teilweise abgebauter Apexiskristall",
				fr = "Cristal apogide partiellement miné",
				it = "Cristallo Apexis Parzialmente Estratto",
				pt = "Cristal Apexis Parcialmente Extraído",
				ru = "Частично выкопанный апекситовый кристалл",
				ko = "반쯤 발굴된 에펙시스 수정",
				cn = "挖过的埃匹希斯水晶",
			},
		},
	
		[242250] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[242275] = {
			readable = "Nightmare Totem",
			model = 1113720,
			text = {
				en = "Nightmare Totem",
				es = "Tótem de la Pesadilla",
				de = "Alptraumtotem",
				fr = "Totem du Cauchemar",
				it = "Totem dell'Incubo",
				pt = "Totem do Pesadelo",
				ru = "Тотем Кошмара",
				ko = "악몽의 토템",
				cn = "梦魇图腾",
			},
		},
	
		[242325] = {
			readable = "Ley Portal",
			model = 166523,
			text = {
				en = "Ley Portal",
				es = "Portal Ley",
				de = "Leyportal",
				fr = "Portail tellurique",
				it = "Portale della Faglia",
				pt = "Portal Meridional",
				ru = "Силовой портал",
				ko = "지맥 차원문",
				cn = "魔网传送门",
			},
		},
	
		[242326] = {
			readable = "Ley Portal",
			model = 166523,
			text = {
				en = "Ley Portal",
				es = "Portal Ley",
				de = "Leyportal",
				fr = "Portail tellurique",
				it = "Portale della Faglia",
				pt = "Portal Meridional",
				ru = "Силовой портал",
				ko = "지맥 차원문",
				cn = "魔网传送门",
			},
		},
	
		[242328] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[242346] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[242350] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[242380] = {
			readable = "Volatile Flare",
			model = 194822,
			text = {
				en = "Volatile Flare",
				es = "Explosivo volátil",
				de = "Instabile Mischung",
				fr = "Décoction instable",
				it = "Fialabengala Instabile",
				pt = "Archote Volátil",
				ru = "Нестабильная взрывчатая смесь",
				ko = "불안정한 폭발물",
			},
		},
	
		[242404] = {
			readable = "Fancy Darkmoon Feast",
			model = 1021192,
			text = {
				en = "Fancy Darkmoon Feast",
				es = "Festín lujoso de la Luna Negra",
				de = "Opulentes Dunkelmond-Festmahl",
				fr = "Festin de Sombrelune fastueux",
				it = "Banchetto Fantasia di Lunacupa",
				pt = "Banquete Chique de Negraluna",
				ru = "Изысканное пиршество Новолуния",
				cn = "暗月豪华大餐",
			},
		},
	
		[242405] = {
			readable = "Sugar-Crusted Fish Feast",
			model = 643924,
			text = {
				en = "Sugar-Crusted Fish Feast",
				es = "Festín de pescado recubierto de azúcar",
				de = "Zuckerglasiertes Fischfestmahl",
				fr = "Festin de poisson en croûte de sucre",
				it = "Banchetto di Pesce in Crosta",
				pt = "Banquete de Frutos do Mar Açucarado",
				ru = "Угощение из засахаренной рыбы",
				ko = "설탕 범벅 생선 잔치",
				cn = "焦糖鱼宴",
			},
		},
	
		[242410] = {
			readable = "Rin'thissa's Summoning Stone",
			model = 1042820,
			text = {
				en = "Rin'thissa's Summoning Stone",
				es = "Roca de invocación de Rin'thissa",
				de = "Rin'thissas Beschwörungsstein",
				fr = "Pierre d’invocation de Rin’thissa",
				it = "Pietra d'Evocazione di Rin'thissa",
				pt = "Pedra de Evocação de Rin'thissa",
				ru = "Камень призыва Рин'тиссы",
				ko = "린티사의 소환석",
				cn = "琳蒂萨的召唤石",
			},
		},
	
		[242411] = {
			readable = "Lyrelle's Summoning Stone",
			model = 1042748,
			text = {
				en = "Lyrelle's Summoning Stone",
				es = "Roca de invocación de Lyrelle",
				de = "Lyrelles Beschwörungsstein",
				fr = "Pierre d’invocation de Lyrelle",
				it = "Pietra d'Evocazione di Lyrelle",
				pt = "Pedra de Evocação de Lyrelle",
				ru = "Камень призыва Лирель",
				ko = "라이렐의 소환석",
				cn = "莱瑞勒的召唤石",
			},
		},
	
		[242412] = {
			readable = "Ondri's Summoning Stone",
			model = 1042749,
			text = {
				en = "Ondri's Summoning Stone",
				es = "Roca de invocación de Ondri",
				de = "Ondris Beschwörungsstein",
				fr = "Pierre d’invocation d’Ondri",
				it = "Pietra d'Evocazione di Ondri",
				pt = "Pedra de Evocação de Ondri",
				ru = "Камень призыва Ондри",
				ko = "온드리의 소환석",
				cn = "昂德里的召唤石",
			},
		},
	
		[242446] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[242449] = {
			readable = "Barrel of Corn",
			model = 323296,
			text = {
				en = "Barrel of Corn",
				es = "Barril de maíz",
				de = "Getreidefass",
				fr = "Tonneau de maïs",
				it = "Barile di Granoturco",
				pt = "Barril de Milho",
				ru = "Бочка с кукурузой",
				ko = "옥수수 통",
				cn = "玉米桶",
			},
		},
	
		[242450] = {
			readable = "Blessed Bow",
			model = 1122448,
			text = {
				en = "Blessed Bow",
				es = "Arco bendito",
				de = "Gesegneter Bogen",
				fr = "Arc béni",
				it = "Arco Benedetto",
				pt = "Arco Abençoado",
				ru = "Благословенный лук",
				ko = "축복받은 활",
				cn = "神佑之弓",
			},
		},
	
		[242469] = {
			readable = "Acherus Waygate",
			model = 244267,
			text = {
				en = "Acherus Waygate",
				es = "Puerta de Acherus",
				de = "Tor von Acherus",
				fr = "Portail d’accès d’Achérus",
				it = "Portale di Acherus",
				pt = "Pórtico de Áquerus",
				ru = "Врата на Акерус",
			},
		},
	
		[242491] = {
			readable = "Alliance Destroyer Ship",
			model = 166432,
			text = {
				en = "Alliance Destroyer Ship",
				es = "Destructor de la Alianza",
				de = "Zerstörer der Allianz",
				fr = "Destroyer de l’Alliance",
				it = "Fregata dell'Alleanza",
				pt = "Destróier da Aliança (Navio)",
				ru = "Эсминец Альянса",
				ko = "얼라이언스 구축함",
				cn = "联盟驱逐舰",
			},
		},
	
		[242502] = {
			readable = "Hilt of Frostmourne",
			model = 1355113,
			text = {
				en = "Hilt of Frostmourne",
				es = "Empuñadura de la Agonía de Escarcha",
				de = "Frostgrams Heft",
				fr = "Garde de Deuillegivre",
				it = "Elsa di Gelidanima",
				pt = "Cabo de Gélido Lamento",
				ru = "Рукоять Ледяной Скорби",
				cn = "霜之哀伤剑柄",
			},
		},
	
		[242518] = {
			readable = "Barnacle-Covered Bag",
			model = 987264,
			text = {
				en = "Barnacle-Covered Bag",
				es = "Bolsa cubierta de percebes",
				de = "Muschelüberwucherte Tasche",
				fr = "Sac couvert de bigorneaux",
				it = "Sacca Ricoperta di Conchiglie",
				pt = "Bolsa Coberta de Cracas",
				ru = "Покрытая рачками сумка",
				ko = "따개비로 뒤덮인 주머니",
				cn = "长满藤壶的袋子",
			},
		},
	
		[242519] = {
			readable = "Suspicious Mound",
			model = 367849,
			text = {
				en = "Suspicious Mound",
				es = "Montículo sospechoso",
				de = "Verdächtiger Erdhaufen",
				fr = "Monticule suspicieux",
				it = "Mucchio Sospetto",
				pt = "Monturo Suspeito",
				ru = "Подозрительный холм",
				ko = "수상쩍은 흙더미",
				cn = "可疑的土堆",
			},
		},
	
		[242520] = {
			readable = "Crystallized Note",
			model = 305393,
			text = {
				en = "Crystallized Note",
				es = "Nota cristalizada",
				de = "Kristallisierte Notiz",
				fr = "Note cristallisée",
				it = "Nota Cristallizzata",
				pt = "Bilhete Cristalizado",
				ru = "Записка в кристалле",
				ko = "결정화된 쪽지",
				cn = "水晶便笺",
			},
		},
	
		[242521] = {
			readable = "Disturbed Dirt",
			model = 204112,
			text = {
				en = "Disturbed Dirt",
				es = "Tierra removida",
				de = "Bewegte Erde",
				fr = "Poussière dérangée",
				it = "Polvere Smossa",
				pt = "Poeira Revolvida",
				ru = "Потревоженная почва",
				ko = "흐트러진 흙",
				cn = "翻动过的泥土",
			},
		},
	
		[242522] = {
			readable = "Silas' Secret Stash",
			model = 446677,
			text = {
				en = "Silas' Secret Stash",
				es = "Alijo secreto de Silas",
				de = "Silas' Geheimversteck",
				fr = "Planque secrète de Silas",
				it = "Scorte Segrete di Silas",
				pt = "Tesouro Escondido de Silas",
				ru = "Тайник Сайласа",
				ko = "실라스의 비밀 상자",
				cn = "希拉斯的秘密宝箱",
			},
		},
	
		[242551] = {
			readable = "Alliance Submarine Ship",
			model = 166432,
			text = {
				en = "Alliance Submarine Ship",
				es = "Submarino de la Alianza",
				de = "U-Boot der Allianz",
				fr = "Sous-marin de l'Alliance",
				it = "Sottomarino dell'Alleanza",
				pt = "Submarino da Aliança (Navio)",
				ru = "Подводная лодка Альянса",
				ko = "얼라이언스 잠수함",
				cn = "联盟潜水艇",
			},
		},
	
		[242574] = {
			readable = "Teleportation Crystal",
			model = 1118050,
			text = {
				en = "Teleportation Crystal",
				es = "Cristal de teletransporte",
				de = "Teleportationskristall",
				fr = "Cristal de téléportation",
				it = "Cristallo di Teletrasporto",
				pt = "Cristal de Teleporte",
				ru = "Кристалл телепортации",
				ko = "순간이동 수정",
				cn = "传送水晶",
			},
		},
	
		[242575] = {
			readable = "Teleportation Crystal",
			model = 1118050,
			text = {
				en = "Teleportation Crystal",
				es = "Cristal de teletransporte",
				de = "Teleportationskristall",
				fr = "Cristal de téléportation",
				it = "Cristallo di Teletrasporto",
				pt = "Cristal de Teleporte",
				ru = "Кристалл телепортации",
				ko = "순간이동 수정",
				cn = "传送水晶",
			},
		},
	
		[242625] = {
			readable = "Transport Ship",
			model = 166432,
			text = {
				en = "Transport Ship",
				es = "Transportador",
				de = "Transportschiff",
				fr = "Transporteur",
				it = "Caravella",
				pt = "Transporte (Navio)",
				ru = "Транспортный корабль",
				ko = "수송선",
				cn = "运输船",
			},
		},
	
		[242626] = {
			readable = "Battleship Ship - Alliance",
			model = 166432,
			text = {
				en = "Battleship Ship - Alliance",
				es = "Buque de combate: Alianza",
				de = "Schlachtschiff - Allianz",
				fr = "Cuirassé de l’Alliance",
				it = "Galeone dell'Alleanza",
				pt = "Navio Nau de Batalha - Aliança",
				ru = "Линкор – Альянс",
				ko = "전함 - 얼라이언스",
				cn = "战列舰 - 联盟",
			},
		},
	
		[242628] = {
			readable = "Carrier Ship",
			model = 166432,
			text = {
				en = "Carrier Ship",
				es = "Portanaves",
				de = "Träger",
				fr = "Porte-nefs",
				it = "Portaerei",
				pt = "Porta-aeronaus (Navio)",
				ru = "Авианосец",
				ko = "항공모함",
				cn = "航母",
			},
		},
	
		[242633] = {
			readable = "Tanithria's Silkweave",
			model = 1284869,
			text = {
				en = "Tanithria's Silkweave",
				es = "Filoseda de Tanithria",
				de = "Tanithrias Seidengewebe",
				fr = "Soie tissée de Tanithria",
				it = "Fildiseta di Tanithria",
				pt = "Tramasseda de Tanithria",
				ru = "Шелковое полотно Танитрии",
				ko = "타니스리아의 비단매듭 옷감",
			},
		},
	
		[242634] = {
			readable = "Tanithria's Thread",
			model = 950799,
			text = {
				en = "Tanithria's Thread",
				es = "Hilo de Tanithria",
				de = "Tanithrias Faden",
				fr = "Fil de Tanithria",
				it = "Filo di Tanithria",
				pt = "Fio de Tanithria",
				ru = "Нить Танитрии",
				ko = "타니스리아의 실",
			},
		},
	
		[242636] = {
			readable = "Tanithria's Purple Dye",
			model = 528633,
			text = {
				en = "Tanithria's Purple Dye",
				es = "Tinte morado de Tanithria",
				de = "Tanithrias violetter Farbstoff",
				fr = "Teinture pourpre de Tanithria",
				it = "Tintura Viola di Tanithria",
				pt = "Pigmento Roxo de Tanithria",
				ru = "Лиловая краска Танитрии",
				ko = "타니스리아의 자색 염료",
				cn = "坦妮瑟娅的紫色染料",
			},
		},
	
		[242637] = {
			readable = "Tanithria's Blue Dye",
			model = 528619,
			text = {
				en = "Tanithria's Blue Dye",
				es = "Tinte azul de Tanithria",
				de = "Tanithrias blauer Farbstoff",
				fr = "Teinture bleue de Tanithria",
				it = "Tintura Blu di Tanithria",
				pt = "Pigmento Azul de Tanithria",
				ru = "Синяя краска Танитрии",
				ko = "타니스리아의 청색 염료",
				cn = "坦妮瑟娅的蓝色染料",
			},
		},
	
		[242638] = {
			readable = "Tanithria's Red Dye",
			model = 243422,
			text = {
				en = "Tanithria's Red Dye",
				es = "Tinte rojo de Tanithria",
				de = "Tanithrias roter Farbstoff",
				fr = "Teinture rouge de Tanithria",
				it = "Tintura Rossa di Tanithria",
				pt = "Pigmento Vermelho de Tanithria",
				ru = "Красная краска Танитрии",
				ko = "타니스리아의 적색 염료",
				cn = "坦妮瑟娅的红色染料",
			},
		},
	
		[242639] = {
			readable = "Tanithria's Green Dye",
			model = 191826,
			text = {
				en = "Tanithria's Green Dye",
				es = "Tinte verde de Tanithria",
				de = "Tanithrias grüner Farbstoff",
				fr = "Teinture verte de Tanithria",
				it = "Tintura Verde di Tanithria",
				pt = "Pigmento Verde de Tanithria",
				ru = "Зеленая краска Танитрии",
				ko = "타니스리아의 녹색 염료",
				cn = "坦妮瑟娅的绿色染料",
			},
		},
	
		[242640] = {
			readable = "Tanithria's Finishing Table",
			model = 1336618,
			text = {
				en = "Tanithria's Finishing Table",
				es = "Mesa de retoques de Tanithria",
				de = "Tanithrias Sticktischchen",
				fr = "Table de finition de Tanithria",
				it = "Tavolo per Finiture di Tanithria",
				pt = "Mesa de Finalização de Tanithria",
				ru = "Стол Танитрии",
				ko = "타니스리아의 마무리 탁자",
				cn = "坦妮瑟娅的精加工台",
			},
		},
	
		[242641] = {
			readable = "Tanithria's Dyeing Tub",
			model = 588545,
			text = {
				en = "Tanithria's Dyeing Tub",
				es = "Tina para teñir de Tanithria",
				de = "Tanithrias Färbewanne",
				fr = "Cuve de teinture de Tanithria",
				it = "Vasca di Tintura di Tanithria",
				pt = "Tubo de Pigmento de Tanithria",
				ru = "Корыто Танитрии",
				ko = "타니스리아의 염료 수조",
				cn = "坦妮瑟娅的染料桶",
			},
		},
	
		[242642] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[242643] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[242644] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[242645] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[242646] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[242647] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[242649] = {
			readable = "Fel-Tainted Apexis Formation",
			model = 975539,
			text = {
				en = "Fel-Tainted Apexis Formation",
				es = "Formación apexis contaminada de energía vil",
				de = "Teufelsbesudelte Apexisformation",
				fr = "Formation apogide gangrenée",
				it = "Formazione Apexis Vilcorrotta",
				pt = "Formação Apexis com Mácula Vil",
				ru = "Пласт оскверненных апекситовых кристаллов",
				ko = "지옥 마력에 물든 에펙시스 결정체",
				cn = "被邪能污染的埃匹希斯晶体",
			},
		},
	
		[242657] = {
			readable = "Lyndras' Runic Catgut",
			model = 950801,
			text = {
				en = "Lyndras' Runic Catgut",
				es = "Tripa rúnica de Lyndras",
				de = "Lyndras' Runenfaden aus Katgut",
				fr = "Boyau runique de Lyndras",
				it = "Crine Runico di Lyndras",
				pt = "Corda de Tripas Rúnica de Lyndras",
				ru = "Рунное волокно Линдраса",
				ko = "린드라스의 룬 무늬 장선",
				cn = "林达斯的符文肠线",
			},
		},
	
		[242658] = {
			readable = "Lyndras' Finishing Table",
			model = 1096883,
			text = {
				en = "Lyndras' Finishing Table",
				es = "Mesa de retoques de Lyndras",
				de = "Lyndras' Sticktischchen",
				fr = "Table de finition de Lyndras",
				it = "Tavolo per Finiture di Lyndras",
				pt = "Mesa de Acabamento de Lyndras",
				ru = "Стол Линдраса",
				ko = "린드라스의 마무리 탁자",
				cn = "林达斯的精加工台",
			},
		},
	
		[242660] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[242662] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[242663] = {
			readable = "Small Treasure Chest",
			model = 979397,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[242664] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[242665] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[242666] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[242667] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[242668] = {
			readable = "Glimmering Treasure Chest",
			model = 1349622,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[242669] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[242670] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[242671] = {
			readable = "Glimmering Treasure Chest",
			model = 1349622,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[242673] = {
			readable = "Engraved Shield",
			model = 1326777,
			text = {
				en = "Engraved Shield",
				es = "Escudo grabado",
				de = "Gravierter Schild",
				fr = "Bouclier gravé",
				it = "Scudo Inciso",
				pt = "Escudo Entalhado",
				ru = "Чеканный щит",
				ko = "문양이 새겨진 방패",
				cn = "雕饰盾牌",
			},
		},
	
		[242675] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[242678] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[242683] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[242686] = {
			readable = "Tanithria's Sharpened Spritethorns",
			model = 950767,
			text = {
				en = "Tanithria's Sharpened Spritethorns",
				es = "Espinas de duende afiladas de Tanithria",
				de = "Tanithrias geschärfte Waldgeistdornen",
				fr = "Lutinépines aiguisées de Tanithria",
				it = "Spinette Affilate di Tanithria",
				pt = "Duendespinhos Afiados de Tanithria",
				ru = "Наточенные шипы лесного духа Танитрии",
				ko = "타니스리아의 뾰족하게 만든 요마가시",
				cn = "坦妮瑟娅的锋利林精棘针",
			},
		},
	
		[242959] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[242987] = {
			readable = "Jailer Cage",
			model = 1125322,
			text = {
				en = "Jailer Cage",
				es = "Jaula del carcelero",
				de = "Wärterkäfig",
				fr = "Cage de geôlier",
				it = "Gabbia del Carceriere",
				pt = "Jaula do Carcereiro",
				ru = "Клетка тюремщика",
				ko = "간수 우리",
				cn = "狱卒的牢笼",
			},
		},
	
		[242989] = {
			readable = "Jailer Cage",
			model = 1125322,
			text = {
				en = "Jailer Cage",
				es = "Jaula del carcelero",
				de = "Wärterkäfig",
				fr = "Cage de geôlier",
				it = "Gabbia del Carceriere",
				pt = "Jaula do Carcereiro",
				ru = "Клетка тюремщика",
				ko = "간수 우리",
				cn = "狱卒的牢笼",
			},
		},
	
		[242990] = {
			readable = "Jailer Cage",
			model = 1125322,
			text = {
				en = "Jailer Cage",
				es = "Jaula del carcelero",
				de = "Wärterkäfig",
				fr = "Cage de geôlier",
				it = "Gabbia del Carceriere",
				pt = "Jaula do Carcereiro",
				ru = "Клетка тюремщика",
				ko = "간수 우리",
				cn = "狱卒的牢笼",
			},
		},
	
		[242994] = {
			readable = "Eyir's Helm",
			model = 243081,
			text = {
				en = "Eyir's Helm",
				es = "Yelmo de Eyir",
				de = "Eyirs Helm",
				fr = "Heaume d’Eyir",
				it = "Elmo di Eyir",
				pt = "Elmo de Eyir",
				ru = "Шлем Эйир",
				ko = "에이르의 투구",
				cn = "艾尔之盔",
			},
		},
	
		[242995] = {
			readable = "Eyir's Pauldron",
			model = 658109,
			text = {
				en = "Eyir's Pauldron",
				es = "Espaldar de Eyir",
				de = "Eyirs Schulterstücke",
				fr = "Espauliers d’Eyir",
				it = "Spallacci di Eyir",
				pt = "Espaldares de Eyir",
				ru = "Наплечье Эйир",
				ko = "에이르의 견갑",
				cn = "艾尔肩胄",
			},
		},
	
		[242996] = {
			readable = "Eyir's Shield",
			model = 1326699,
			text = {
				en = "Eyir's Shield",
				es = "Escudo de Eyir",
				de = "Eyirs Schild",
				fr = "Bouclier d’Eyir",
				it = "Scudo di Eyir",
				pt = "Escudo de Eyir",
				ru = "Щит Эйир",
				ko = "에이르의 방패",
				cn = "艾尔之盾",
			},
		},
	
		[242998] = {
			readable = "Eyir's Spear",
			model = 1327089,
			text = {
				en = "Eyir's Spear",
				es = "Lanza de Eyir",
				de = "Eyirs Speer",
				fr = "Lance d’Eyir",
				it = "Lancia di Eyir",
				pt = "Lança de Eyir",
				ru = "Копье Эйир",
				ko = "에이르의 창",
				cn = "艾尔之矛",
			},
		},
})
do ObjectDB[objectID] = objectData; end
