local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	
		[354036] = {
			readable = "Vesper of Loyalty",
			model = 3164976,
			text = {
				en = "Vesper of Loyalty",
				es = "Campana de vísperas de lealtad",
				de = "Vesperglocke der Loyalität",
				fr = "Bourdon de loyauté",
				it = "Vespro della Lealtà",
				pt = "Véspera da Lealdade",
				ru = "Колокол Верности",
				ko = "충성의 기도용 종",
				cn = "忠诚暮钟",
			},
		},
	
		[354038] = {
			readable = "Vesper of Purity",
			model = 3164976,
			text = {
				en = "Vesper of Purity",
				es = "Campana de vísperas de pureza",
				de = "Vesperglocke der Reinheit",
				fr = "Bourdon de pureté",
				it = "Vespro della Purezza",
				pt = "Véspera da Pureza",
				ru = "Колокол Чистоты",
				ko = "순수의 기도용 종",
				cn = "纯洁暮钟",
			},
		},
	
		[354041] = {
			readable = "Aspirant's Chest",
			model = 3189120,
			text = {
				en = "Aspirant's Chest",
				es = "Cofre de aspirante",
				de = "Truhe des Aspiranten",
				fr = "Coffre d’aspirant",
				it = "Cassa dell'Aspirante",
				pt = "Baú do Aspirante",
				ru = "Сундук претендента",
				ko = "열망자의 상자",
				cn = "候选者的宝箱",
			},
		},
	
		[354052] = {
			readable = "Victor's Chest",
			model = 3189119,
			text = {
				en = "Victor's Chest",
				es = "Cofre de Victor",
				de = "Truhe des Siegers",
				fr = "Coffre du vainqueur",
				it = "Cassa della Vittoria",
				pt = "Baú do Vencedor",
				ru = "Сундук победителя",
				ko = "승자의 상자",
				cn = "胜者的宝箱",
			},
		},
	
		[354059] = {
			readable = "Weapon Rack",
			model = 3038743,
			text = {
				en = "Weapon Rack",
				es = "Expositor de armas",
				de = "Waffenregal",
				fr = "Râtelier d’armes",
				it = "Rastrelliera delle Armi",
				pt = "Cavalete de Armas",
				ru = "Оружейная стойка",
				ko = "무기 선반",
				cn = "武器架",
			},
		},
	
		[354075] = {
			readable = "Blank Parchment",
			model = 3152067,
			text = {
				en = "Blank Parchment",
				es = "Papiro en blanco",
				de = "Leeres Pergament",
				fr = "Parchemin vierge",
				it = "Cartapecora Vuota",
				pt = "Pergaminho em Branco",
				ru = "Чистый лист пергамента",
				ko = "빈 양피지",
				cn = "空白的羊皮纸",
			},
		},
	
		[354076] = {
			readable = "Beginner's Guide To Polearms",
			model = 1354763,
			text = {
				en = "Beginner's Guide To Polearms",
				es = "Guía de armas de asta para principiantes",
				de = "Anfängerleitfaden der Stangenwaffen",
				fr = "Initiation au maniement des armes d’hast",
				it = "Guida Introduttiva alle Armi ad Asta",
				pt = "Armas de Haste para Principiantes",
				ru = "\"Древковое оружие: руководство для новичка\"",
				ko = "초보자용 장창 지침서",
				cn = "长柄武器新手指南",
			},
		},
	
		[354077] = {
			readable = "Pretend To Win",
			model = 1354763,
			text = {
				en = "Pretend To Win",
				es = "Fingir la victoria",
				de = "Den Sieg vortäuschen",
				fr = "Comment faire semblant de gagner",
				it = "Fingere di Vincere",
				pt = "Fingir para Vencer",
				ru = "\"Притворство ради победы\"",
				ko = "승자 흉내",
				cn = "假装胜利",
			},
		},
	
		[354079] = {
			readable = "Scorchshroom",
			model = 2913344,
			text = {
				en = "Scorchshroom",
				es = "Champicante",
				de = "Sengpilz",
				fr = "Champyro",
				it = "Ardifungo",
				pt = "Cinzelo",
				ru = "Жарогриб",
				ko = "그을음버섯",
				cn = "灼菇",
			},
		},
	
		[354080] = {
			readable = "Smokeshroom",
			model = 2973068,
			text = {
				en = "Smokeshroom",
				es = "Champiñumo",
				de = "Rauchpilz",
				fr = "Fumorille",
				it = "Fumfungo",
				pt = "Fumelo",
				ru = "Дымогриб",
				ko = "연기버섯",
				cn = "烟菇",
			},
		},
	
		[354081] = {
			readable = "Scorchshroom Clump",
			model = 2908062,
			text = {
				en = "Scorchshroom Clump",
				es = "Terrón de champicantes",
				de = "Sengpilzgruppe",
				fr = "Grappe de champyros",
				it = "Ammasso di Ardifunghi",
				pt = "Penca de Cinzelos",
				ru = "Кучка жарогрибов",
				ko = "그을음버섯 무리",
				cn = "灼菇丛",
			},
		},
	
		[354082] = {
			readable = "Smokeshroom Clump",
			model = 2973069,
			text = {
				en = "Smokeshroom Clump",
				es = "Terrón de champiñumos",
				de = "Rauchpilzgruppe",
				fr = "Grappe de fumorilles",
				it = "Ammasso di Fumfunghi",
				pt = "Penca de Fumelos",
				ru = "Кучка дымогрибов",
				ko = "연기버섯 무리",
				cn = "烟菇丛",
			},
		},
	
		[354083] = {
			readable = "Shardshroom",
			model = 2976327,
			text = {
				en = "Shardshroom",
				es = "Chamfragmento",
				de = "Splitterpilz",
				fr = "Éclactaire",
				it = "Cocciofungo",
				pt = "Fragmelo",
				ru = "Острогриб",
				ko = "조각버섯",
				cn = "碎菇",
			},
		},
	
		[354085] = {
			readable = "Volatile Substance",
			model = 166655,
			text = {
				en = "Volatile Substance",
				es = "Sustancia volátil",
				de = "Instabile Substanz",
				fr = "Substance instable",
				it = "Sostanza Instabile",
				pt = "Substância Volátil",
				ru = "Нестабильная субстанция",
				ko = "불안정한 물질",
				cn = "不稳定的物质",
			},
		},
	
		[354094] = {
			readable = "Bell of Purification",
			model = 2839471,
			text = {
				en = "Bell of Purification",
				es = "Campana de purificación",
				de = "Glocke der Läuterung",
				fr = "Cloche de purification",
				it = "Campana della Purificazione",
				pt = "Sino da Purificação",
				ru = "Колокол очищения",
				ko = "정화의 종",
				cn = "净化之钟",
			},
		},
	
		[354095] = {
			readable = "Vesper of Wisdom",
			model = 3164976,
			text = {
				en = "Vesper of Wisdom",
				es = "Campana de vísperas de sabiduría",
				de = "Vesperglocke der Weisheit",
				fr = "Bourdon de sagesse",
				it = "Vespro della Saggezza",
				pt = "Véspera da Sabedoria",
				ru = "Колокол Мудрости",
				ko = "지혜의 기도용 종",
				cn = "智慧暮钟",
			},
		},
	
		[354096] = {
			readable = "Vesper of Humility",
			model = 3164976,
			text = {
				en = "Vesper of Humility",
				es = "Campana de vísperas de humildad",
				de = "Vesperglocke der Demut",
				fr = "Bourdon d’humilité",
				it = "Vespro dell'Umiltà",
				pt = "Véspera da Humildade",
				ru = "Колокол Смирения",
				ko = "겸손의 기도용 종",
				cn = "谦逊暮钟",
			},
		},
	
		[354097] = {
			readable = "Vesper of Courage",
			model = 2839465,
			text = {
				en = "Vesper of Courage",
				es = "Campana de vísperas del coraje",
				de = "Vesperglocke des Mutes",
				fr = "Bourdon de courage",
				it = "Vespro del Coraggio",
				pt = "Véspera da Coragem",
				ru = "Колокол Отваги",
				ko = "용기의 기도용 종",
				cn = "勇气暮钟",
			},
		},
	
		[354105] = {
			readable = "Scorchshroom Snack",
			model = 2913344,
			text = {
				en = "Scorchshroom Snack",
				es = "Tentempié de champicante",
				de = "Sengpilzleckerei",
				fr = "Champyro à croquer",
				it = "Spuntino di Ardifungo",
				pt = "Aperitivo de Cinzelo",
				ru = "Жареный жарогриб",
				ko = "그을음버섯 간식",
				cn = "灼菇点心",
			},
		},
	
		[354108] = {
			readable = "Stoneborn Satchel",
			model = 878854,
			text = {
				en = "Stoneborn Satchel",
				es = "Bolsa de natopiedra",
				de = "Steingeborenensäckchen",
				fr = "Sacoche vive-pierre",
				it = "Borsa dei Litogeni",
				pt = "Algibeira de Litonato",
				ru = "Сумка камнерожденных",
				ko = "돌숨결 주머니",
				cn = "石裔背包",
			},
		},
	
		[354109] = {
			readable = "Stoneborn Satchel",
			model = 878854,
			text = {
				en = "Stoneborn Satchel",
				es = "Bolsa de natopiedra",
				de = "Steingeborenensäckchen",
				fr = "Sacoche vive-pierre",
				it = "Borsa dei Litogeni",
				pt = "Algibeira de Litonato",
				ru = "Сумка камнерожденных",
				ko = "돌숨결 주머니",
				cn = "石裔背包",
			},
		},
	
		[354110] = {
			readable = "Stoneborn Satchel",
			model = 878854,
			text = {
				en = "Stoneborn Satchel",
				es = "Bolsa de natopiedra",
				de = "Steingeborenensäckchen",
				fr = "Sacoche vive-pierre",
				it = "Borsa dei Litogeni",
				pt = "Algibeira de Litonato",
				ru = "Сумка камнерожденных",
				ko = "돌숨결 주머니",
				cn = "石裔背包",
			},
		},
	
		[354111] = {
			readable = "Stoneborn Satchel",
			model = 878854,
			text = {
				en = "Stoneborn Satchel",
				es = "Bolsa de natopiedra",
				de = "Steingeborenensäckchen",
				fr = "Sacoche vive-pierre",
				it = "Borsa dei Litogeni",
				pt = "Algibeira de Litonato",
				ru = "Сумка камнерожденных",
				ko = "돌숨결 주머니",
				cn = "石裔背包",
			},
		},
	
		[354112] = {
			readable = "Stoneborn Satchel",
			model = 878854,
			text = {
				en = "Stoneborn Satchel",
				es = "Bolsa de natopiedra",
				de = "Steingeborenensäckchen",
				fr = "Sacoche vive-pierre",
				it = "Borsa dei Litogeni",
				pt = "Algibeira de Litonato",
				ru = "Сумка камнерожденных",
				ko = "돌숨결 주머니",
				cn = "石裔背包",
			},
		},
	
		[354113] = {
			readable = "Stoneborn Satchel",
			model = 878854,
			text = {
				en = "Stoneborn Satchel",
				es = "Bolsa de natopiedra",
				de = "Steingeborenensäckchen",
				fr = "Sacoche vive-pierre",
				it = "Borsa dei Litogeni",
				pt = "Algibeira de Litonato",
				ru = "Сумка камнерожденных",
				ko = "돌숨결 주머니",
				cn = "石裔背包",
			},
		},
	
		[354114] = {
			readable = "Stoneborn Satchel",
			model = 878854,
			text = {
				en = "Stoneborn Satchel",
				es = "Bolsa de natopiedra",
				de = "Steingeborenensäckchen",
				fr = "Sacoche vive-pierre",
				it = "Borsa dei Litogeni",
				pt = "Algibeira de Litonato",
				ru = "Сумка камнерожденных",
				ko = "돌숨결 주머니",
				cn = "石裔背包",
			},
		},
	
		[354115] = {
			readable = "Pugilist's Prize",
			model = 1306557,
			text = {
				en = "Pugilist's Prize",
				es = "Premio de púgil",
				de = "Preis des Faustkämpfers",
				fr = "Trophée de pugiliste",
				it = "Premio del Pugile",
				pt = "Prêmio do Pugilista",
				ru = "Награда бойца",
				cn = "拳手的奖励",
			},
		},
	
		[354116] = {
			readable = "Pugilist's Prize",
			model = 1306556,
			text = {
				en = "Pugilist's Prize",
				es = "Premio de púgil",
				de = "Preis des Faustkämpfers",
				fr = "Trophée de pugiliste",
				it = "Premio del Pugile",
				pt = "Prêmio do Pugilista",
				ru = "Награда бойца",
				ko = "싸움꾼의 전리품",
				cn = "拳手的奖励",
			},
		},
	
		[354121] = {
			readable = "Pugilist's Prize",
			model = 1254446,
			text = {
				en = "Pugilist's Prize",
				es = "Premio de púgil",
				de = "Preis des Faustkämpfers",
				fr = "Trophée de pugiliste",
				it = "Premio del Pugile",
				pt = "Prêmio do Pugilista",
				ru = "Награда бойца",
				ko = "싸움꾼의 전리품",
				cn = "拳手的奖励",
			},
		},
	
		[354122] = {
			readable = "Pugilist's Prize",
			model = 1255202,
			text = {
				en = "Pugilist's Prize",
				es = "Premio de púgil",
				de = "Preis des Faustkämpfers",
				fr = "Trophée de pugiliste",
				it = "Premio del Pugile",
				pt = "Prêmio do Pugilista",
				ru = "Награда бойца",
				ko = "싸움꾼의 전리품",
				cn = "拳手的奖励",
			},
		},
	
		[354123] = {
			readable = "Pugilist's Prize",
			model = 987264,
			text = {
				en = "Pugilist's Prize",
				es = "Premio de púgil",
				de = "Preis des Faustkämpfers",
				fr = "Trophée de pugiliste",
				it = "Premio del Pugile",
				pt = "Prêmio do Pugilista",
				ru = "Награда бойца",
				ko = "싸움꾼의 전리품",
				cn = "拳手的奖励",
			},
		},
	
		[354128] = {
			readable = "Maldraxxian Throwing Axe",
			model = 3528404,
			text = {
				en = "Maldraxxian Throwing Axe",
				es = "Hacha arrojadiza maldraxxi",
				de = "Maldraxxische Wurfaxt",
				fr = "Hache de jet maldraxxi",
				it = "Ascia da Lancio di Maldraxxus",
				pt = "Machado de Arremesso Maldraxxi",
				ru = "Малдраксийский метательный топор",
				ko = "말드락시 투척용 도끼",
				cn = "玛卓克萨斯飞斧",
			},
		},
	
		[354132] = {
			readable = "Stage Light",
			model = 3542680,
			text = {
				en = "Stage Light",
				es = "Luz de escenario",
				de = "Bühnenlicht",
				fr = "Projecteur",
				it = "Luce del Palco",
				pt = "Luz de Palco",
				ru = "Дежурный свет",
				ko = "무대 조명",
				cn = "舞台灯光",
			},
		},
	
		[354133] = {
			readable = "Flame of Devotion",
			model = 2994772,
			text = {
				en = "Flame of Devotion",
				es = "Llama de devoción",
				de = "Flamme der Hingabe",
				fr = "Flamme de dévotion",
				it = "Fiamma della Devozione",
				pt = "Chama da Devoção",
				ru = "Пламя преданности",
				ko = "헌신의 불꽃",
				cn = "奉献之火",
			},
		},
	
		[354134] = {
			readable = "Stage Prop",
			model = 2981870,
			text = {
				en = "Stage Prop",
				es = "Atrezo de escenario",
				de = "Bühnenrequisite",
				fr = "Accessoire de scène",
				it = "Arredi del Palco",
				pt = "Objeto de Cena",
				ru = "Сценические декорации",
				ko = "무대 소도구",
				cn = "舞台道具",
			},
		},
	
		[354135] = {
			readable = "Brazier of Devotion",
			model = 3038198,
			text = {
				en = "Brazier of Devotion",
				es = "Blandón de devoción",
				de = "Kohlenpfanne der Hingabe",
				fr = "Brasero de dévotion",
				it = "Braciere della Devozione",
				pt = "Braseiro da Devoção",
				ru = "Жаровня преданности",
				ko = "헌신의 화로",
				cn = "奉献火盆",
			},
		},
	
		[354150] = {
			readable = "Rune of Might",
			model = 3307173,
			text = {
				en = "Rune of Might",
				es = "Runa de poderío",
				de = "Rune der Macht",
				fr = "Rune de puissance",
				it = "Runa del Vigore",
				pt = "Runa de Poder",
				ru = "Руна мощи",
				ko = "힘의 룬",
				cn = "力量符文",
			},
		},
	
		[354153] = {
			readable = "Agthia's Flame",
			model = 2994772,
			text = {
				en = "Agthia's Flame",
				es = "Llama de Agthia",
				de = "Agthias Flamme",
				fr = "Flamme d’Agthia",
				it = "Fiamma di Agthia",
				pt = "Chama de Agthia",
				ru = "Пламя Агфии",
				ko = "아그티아의 불꽃",
				cn = "艾格茜娅的火焰",
			},
		},
	
		[354154] = {
			readable = "Bone Spike",
			model = 3036636,
			text = {
				en = "Bone Spike",
				es = "Púa ósea",
				de = "Knochenstachel",
				fr = "Pointe d’os",
				it = "Aculeo Osseo",
				pt = "Espigão Ósseo",
				ru = "Костяной шип",
				ko = "뼈 가시",
				cn = "骨刺",
			},
		},
	
		[354155] = {
			readable = "Bone Spike",
			model = 3036637,
			text = {
				en = "Bone Spike",
				es = "Púa ósea",
				de = "Knochenstachel",
				fr = "Pointe d’os",
				it = "Aculeo Osseo",
				pt = "Espigão Ósseo",
				ru = "Костяной шип",
				ko = "뼈 가시",
				cn = "骨刺",
			},
		},
	
		[354156] = {
			readable = "Bone Spike",
			model = 3036638,
			text = {
				en = "Bone Spike",
				es = "Púa ósea",
				de = "Knochenstachel",
				fr = "Pointe d’os",
				it = "Aculeo Osseo",
				pt = "Espigão Ósseo",
				ru = "Костяной шип",
				ko = "뼈 가시",
				cn = "骨刺",
			},
		},
	
		[354162] = {
			readable = "Path of Courage",
			model = 3038199,
			text = {
				en = "Path of Courage",
				es = "El camino del coraje",
				de = "Weg des Mutes",
				fr = "La voie du courage",
				it = "Via del Coraggio",
				pt = "O Caminho da Coragem",
				ru = "Путь Отваги",
				ko = "용기의 길",
				cn = "勇气之路",
			},
		},
	
		[354163] = {
			readable = "Conspicuous Crate",
			model = 198158,
			text = {
				en = "Conspicuous Crate",
				es = "Cajón llamativo",
				de = "Auffällige Kiste",
				fr = "Caisse voyante",
				it = "Cassa Notevole",
				pt = "Caixote Evidente",
				ru = "Подозрительный ящик",
				cn = "显眼的箱子",
			},
		},
	
		[354164] = {
			readable = "Noxious Barrel",
			model = 3036556,
			text = {
				en = "Noxious Barrel",
				es = "Barrica nociva",
				de = "Giftiges Fass",
				fr = "Tonneau nauséabond",
				it = "Barile Nocivo",
				pt = "Barril Nóxio",
				ru = "Ядовитая бочка",
				ko = "유독성 통",
				cn = "剧毒之桶",
			},
		},
	
		[354167] = {
			readable = "Path of Courage",
			model = 3038199,
			text = {
				en = "Path of Courage",
				es = "El camino del coraje",
				de = "Weg des Mutes",
				fr = "La voie du courage",
				it = "Via del Coraggio",
				pt = "O Caminho da Coragem",
				ru = "Путь Отваги",
				ko = "용기의 길",
				cn = "勇气之路",
			},
		},
	
		[354169] = {
			readable = "Path of Courage",
			model = 3038199,
			text = {
				en = "Path of Courage",
				es = "El camino del coraje",
				de = "Weg des Mutes",
				fr = "La voie du courage",
				it = "Via del Coraggio",
				pt = "O Caminho da Coragem",
				ru = "Путь Отваги",
				ko = "용기의 길",
				cn = "勇气之路",
			},
		},
	
		[354171] = {
			readable = "Path of Courage",
			model = 3038199,
			text = {
				en = "Path of Courage",
				es = "El camino del coraje",
				de = "Weg des Mutes",
				fr = "La voie du courage",
				it = "Via del Coraggio",
				pt = "O Caminho da Coragem",
				ru = "Путь Отваги",
				ko = "용기의 길",
				cn = "勇气之路",
			},
		},
	
		[354173] = {
			readable = "Ansel's Lucky Violin",
			model = 238586,
			text = {
				en = "Ansel's Lucky Violin",
				es = "Violín de la suerte de Ansel",
				de = "Ansels Glücksgeige",
				fr = "Violon porte-bonheur d’Ansel",
				it = "Violino Fortunato di Ansel",
				pt = "Violino Pé-quente de Ansel",
				ru = "Счастливая скрипка Анселя",
				ko = "안셀의 행운의 바이올린",
				cn = "安塞尔的幸运小提琴",
			},
		},
	
		[354174] = {
			readable = "Chiu's Lute",
			model = 192080,
			text = {
				en = "Chiu's Lute",
				es = "Laúd de Chiu",
				de = "Chius Laute",
				fr = "Luth de Chu",
				it = "Liuto di Chiu",
				pt = "Alaúde de Chiu",
				ru = "Лютня Чиу",
				ko = "치우의 류트",
				cn = "邱的琵琶",
			},
		},
	
		[354175] = {
			readable = "Cache of the Ascended",
			model = 3189119,
			text = {
				en = "Cache of the Ascended",
				es = "Alijo de los Ascendidos",
				de = "Vorrat der Aufgestiegenen",
				fr = "Cache des transcendés",
				it = "Cassa dell'Ascensione",
				pt = "Baú dos Ascendidos",
				ru = "Тайник перерожденных",
				ko = "승천자의 보관함",
				cn = "晋升宝箱",
			},
		},
	
		[354185] = {
			readable = "House Iremoore Formal Wear",
			model = 3607335,
			text = {
				en = "House Iremoore Formal Wear",
				es = "Atuendo formal de la casa Inquina",
				de = "Förmliche Kleidung des Hauses Zornmeer",
				fr = "Tenue formelle de la maison Irebrande",
				pt = "Traje Formal da Casa Iracunda",
				ru = "Церемониальные одежды дома Айрмур",
			},
		},
	
		[354186] = {
			readable = "Stoneborn Satchel",
			model = 878854,
			text = {
				en = "Stoneborn Satchel",
				es = "Bolsa de natopiedra",
				de = "Steingeborenensäckchen",
				fr = "Sacoche vive-pierre",
				it = "Borsa dei Litogeni",
				pt = "Algibeira de Litonato",
				ru = "Сумка камнерожденных",
				ko = "돌숨결 주머니",
				cn = "石裔背包",
			},
		},
	
		[354187] = {
			readable = "Stoneborn Satchel",
			model = 878854,
			text = {
				en = "Stoneborn Satchel",
				es = "Bolsa de natopiedra",
				de = "Steingeborenensäckchen",
				fr = "Sacoche vive-pierre",
				it = "Borsa dei Litogeni",
				pt = "Algibeira de Litonato",
				ru = "Сумка камнерожденных",
				ko = "돌숨결 주머니",
				cn = "石裔背包",
			},
		},
	
		[354188] = {
			readable = "Stoneborn Satchel",
			model = 878854,
			text = {
				en = "Stoneborn Satchel",
				es = "Bolsa de natopiedra",
				de = "Steingeborenensäckchen",
				fr = "Sacoche vive-pierre",
				it = "Borsa dei Litogeni",
				pt = "Algibeira de Litonato",
				ru = "Сумка камнерожденных",
				ko = "돌숨결 주머니",
				cn = "石裔背包",
			},
		},
	
		[354189] = {
			readable = "Stoneborn Satchel",
			model = 878854,
			text = {
				en = "Stoneborn Satchel",
				es = "Bolsa de natopiedra",
				de = "Steingeborenensäckchen",
				fr = "Sacoche vive-pierre",
				it = "Borsa dei Litogeni",
				pt = "Algibeira de Litonato",
				ru = "Сумка камнерожденных",
				ko = "돌숨결 주머니",
				cn = "石裔背包",
			},
		},
	
		[354190] = {
			readable = "Stoneborn Satchel",
			model = 878854,
			text = {
				en = "Stoneborn Satchel",
				es = "Bolsa de natopiedra",
				de = "Steingeborenensäckchen",
				fr = "Sacoche vive-pierre",
				it = "Borsa dei Litogeni",
				pt = "Algibeira de Litonato",
				ru = "Сумка камнерожденных",
				ko = "돌숨결 주머니",
				cn = "石裔背包",
			},
		},
	
		[354191] = {
			readable = "Stoneborn Satchel",
			model = 878854,
			text = {
				en = "Stoneborn Satchel",
				es = "Bolsa de natopiedra",
				de = "Steingeborenensäckchen",
				fr = "Sacoche vive-pierre",
				it = "Borsa dei Litogeni",
				pt = "Algibeira de Litonato",
				ru = "Сумка камнерожденных",
				ko = "돌숨결 주머니",
				cn = "石裔背包",
			},
		},
	
		[354192] = {
			readable = "Stoneborn Satchel",
			model = 878854,
			text = {
				en = "Stoneborn Satchel",
				es = "Bolsa de natopiedra",
				de = "Steingeborenensäckchen",
				fr = "Sacoche vive-pierre",
				it = "Borsa dei Litogeni",
				pt = "Algibeira de Litonato",
				ru = "Сумка камнерожденных",
				ko = "돌숨결 주머니",
				cn = "石裔背包",
			},
		},
	
		[354193] = {
			readable = "Stoneborn Satchel",
			model = 878854,
			text = {
				en = "Stoneborn Satchel",
				es = "Bolsa de natopiedra",
				de = "Steingeborenensäckchen",
				fr = "Sacoche vive-pierre",
				it = "Borsa dei Litogeni",
				pt = "Algibeira de Litonato",
				ru = "Сумка камнерожденных",
				ko = "돌숨결 주머니",
				cn = "石裔背包",
			},
		},
	
		[354194] = {
			readable = "Cage",
			model = 3160242,
			text = {
				en = "Cage",
				es = "Jaula",
				de = "Käfig",
				it = "Gabbia",
				pt = "Jaula",
				ru = "Клетка",
				ko = "우리",
				cn = "牢笼",
			},
		},
	
		[354200] = {
			readable = "Note What Says Where You Put The Key",
			model = 3152066,
			text = {
				en = "Note What Says Where You Put The Key",
				es = "Nota que indica dónde has dejado la llave",
				de = "Notiz über wo du den Schlüssel hingepackt hast",
				fr = "Mémo sur la cachette de la clé",
				it = "Note sulla Posizione della Chiave",
				pt = "Bilhete Onde Você Diz Onde Botou a Chave",
				ru = "Записка, в которой сказано, где должен быть ключ",
				ko = "열쇠 위치가 적힌 쪽지",
				cn = "写着你把钥匙放在哪里的笔记",
			},
		},
	
		[354201] = {
			readable = "Dragon Plume",
			model = 199706,
			text = {
				en = "Dragon Plume",
				es = "Pluma de dragón",
				de = "Drachenfeder",
				fr = "Plume de dragon",
				it = "Piuma di Drago",
				pt = "Pluma de Dragão",
				ru = "Драконье перо",
				ko = "용의 깃털",
				cn = "巨龙飞羽",
			},
		},
	
		[354202] = {
			readable = "Abandoned Stockpile",
			model = 3023914,
			text = {
				en = "Abandoned Stockpile",
				es = "Reservas abandonadas",
				de = "Verlassener Vorrat",
				fr = "Réserves abandonnées",
				it = "Scorte Abbandonate",
				pt = "Reserva Abandonada",
				ru = "Брошенный ящик",
				ko = "버려진 비품",
				cn = "被遗弃的物资",
			},
		},
	
		[354205] = {
			readable = "Forsworn Barrier Source",
			model = 3220603,
			text = {
				en = "Forsworn Barrier Source",
				es = "Fuente de la barrera abjurante",
				de = "Barrierenquelle der Verschmähten",
				fr = "Source de la barrière désavouée",
				it = "Fonte della Barriera degli Indegni",
				pt = "Origem de Barreira Perjura",
				ru = "Источник энергии для барьера раскольников",
				ko = "이탈자 방벽 원천",
				cn = "弃誓者屏障之源",
			},
		},
	
		[354206] = {
			readable = "Greedstone",
			model = 2839690,
			text = {
				en = "Greedstone",
				es = "Piedra de la avaricia",
				de = "Gierstein",
				fr = "Pierre de cupidité",
				it = "Pietravida",
				pt = "Pedra da Ganância",
				ru = "Камень алчности",
				ko = "탐욕석",
				cn = "贪婪之石",
			},
		},
	
		[354208] = {
			readable = "Stolen Equipment",
			model = 3189120,
			text = {
				en = "Stolen Equipment",
				es = "Equipo robado",
				de = "Gestohlene Ausrüstung",
				fr = "Équipement volé",
				it = "Equipaggiamento Rubato",
				pt = "Equipamento Roubado",
				ru = "Украденное снаряжение",
				ko = "도둑맞은 장비",
				cn = "失窃的装备",
			},
		},
	
		[354211] = {
			readable = "Greed's Reward",
			model = 3595030,
			text = {
				en = "Greed's Reward",
				es = "Recompensa de avaricia",
				de = "Belohnung der Gier",
				fr = "Récompense de la cupidité",
				it = "Ricompensa dell'Avidità",
				pt = "Recompensa da Cobiça",
				ru = "Награда алчности",
				ko = "탐욕의 보상",
				cn = "贪婪的奖励",
			},
		},
	
		[354213] = {
			readable = "Lost Disciple's Notes",
			model = 3045971,
			text = {
				en = "Lost Disciple's Notes",
				es = "Notas perdidas de discípulo",
				de = "Notizen des verlorenen Jüngers",
				fr = "Notes du disciple disparu",
				it = "Note del Discepolo Perduto",
				pt = "Anotações do Discípulo Perdido",
				ru = "Записки пропавшего послушника",
				ko = "잃어버린 사도의 쪽지",
				cn = "失落信徒笔记",
			},
		},
	
		[354214] = {
			readable = "Larion Tamer's Harness",
			model = 1019643,
			text = {
				en = "Larion Tamer's Harness",
				es = "Arnés de domador de lariones",
				de = "Harnisch des Larionbändigers",
				fr = "Harnais de dresseur de volion",
				it = "Bardatura del Domatore di Larion",
				pt = "Arnês de Domador de Lariões",
				ru = "Упряжь укротителя ларионов",
				ko = "깃사자 조련사의 고삐",
				cn = "翼狮训练者的挽具",
			},
		},
	
		[354215] = {
			readable = "Forsworn Barrier Source",
			model = 3220603,
			text = {
				en = "Forsworn Barrier Source",
				es = "Fuente de la barrera abjurante",
				de = "Barrierenquelle der Verschmähten",
				fr = "Source de la barrière désavouée",
				it = "Fonte della Barriera degli Indegni",
				pt = "Origem de Barreira Perjura",
				ru = "Источник энергии для барьера раскольников",
				ko = "이탈자 방벽 원천",
				cn = "弃誓者屏障之源",
			},
		},
	
		[354216] = {
			readable = "Forsworn Barrier Source",
			model = 3220603,
			text = {
				en = "Forsworn Barrier Source",
				es = "Fuente de la barrera abjurante",
				de = "Barrierenquelle der Verschmähten",
				fr = "Source de la barrière désavouée",
				it = "Fonte della Barriera degli Indegni",
				pt = "Origem de Barreira Perjura",
				ru = "Источник энергии для барьера раскольников",
				ko = "이탈자 방벽 원천",
				cn = "弃誓者屏障之源",
			},
		},
	
		[354275] = {
			readable = "Experimental Construct Part",
			model = 3197319,
			text = {
				en = "Experimental Construct Part",
				es = "Pieza de ensamblaje experimental",
				de = "Experimentelles Konstruktteil",
				fr = "Pièce d’assemblage expérimental",
				it = "Parte di Costrutto Sperimentale",
				pt = "Peça de Constructo Experimental",
				ru = "Часть экспериментального кадавра",
				ko = "실험용 피조물 부위",
				cn = "实验型构造体部件",
			},
		},
	
		[354279] = {
			readable = "Unstable Construct Anima",
			model = 3154869,
			text = {
				en = "Unstable Construct Anima",
				es = "Ánima de ensamblaje inestable",
				de = "Instabile Konstruktanima",
				fr = "Anima d’assemblage instable",
				it = "Animum per Costrutti Instabile",
				pt = "Constructo de Ânima Instável",
				ru = "Анима нестабильного голиафа",
				ko = "불안정한 피조물 령",
				cn = "不稳定的构造体心能",
			},
		},
	
		[354283] = {
			readable = "Mercia's Legacy: Chapter One",
			model = 3045972,
			text = {
				en = "Mercia's Legacy: Chapter One",
				es = "El legado de Mercia: Capítulo uno",
				de = "Mercias Vermächtnis: Kapitel eins",
				fr = "L’héritage de Mercia : chapitre I",
				it = "Retaggio di Mercia: Capitolo Uno",
				pt = "Legado de Mércia: Capítulo Um",
				ru = "Наследие Милосерды: глава первая",
				ko = "메르시아의 유산: 제1장",
				cn = "梅希娅的传承：第一章",
			},
		},
	
		[354284] = {
			readable = "Mercia's Legacy: Chapter Two",
			model = 3045975,
			text = {
				en = "Mercia's Legacy: Chapter Two",
				es = "El legado de Mercia: Capítulo dos",
				de = "Mercias Vermächtnis: Kapitel zwei",
				fr = "L’héritage de Mercia : chapitre II",
				it = "Retaggio di Mercia: Capitolo Due",
				pt = "Legado de Mércia: Capítulo Dois",
				ru = "Наследие Милосерды: глава вторая",
				ko = "메르시아의 유산: 제2장",
				cn = "梅希娅的传承：第二章",
			},
		},
	
		[354285] = {
			readable = "Mercia's Legacy: Chapter Three",
			model = 3022977,
			text = {
				en = "Mercia's Legacy: Chapter Three",
				es = "El legado de Mercia: Capítulo tres",
				de = "Mercias Vermächtnis: Kapitel drei",
				fr = "L’héritage de Mercia : chapitre III",
				it = "Retaggio di Mercia: Capitolo Tre",
				pt = "Legado de Mércia: Capítulo Três",
				ru = "Наследие Милосерды: глава третья",
				ko = "메르시아의 유산: 제3장",
				cn = "梅希娅的传承：第三章",
			},
		},
	
		[354286] = {
			readable = "Mercia's Legacy: Chapter Four",
			model = 3045972,
			text = {
				en = "Mercia's Legacy: Chapter Four",
				es = "El legado de Mercia: Capítulo cuatro",
				de = "Mercias Vermächtnis: Kapitel vier",
				fr = "L’héritage de Mercia : chapitre IV",
				it = "Retaggio di Mercia: Capitolo Quattro",
				pt = "Legado de Mércia: Capítulo Quatro",
				ru = "Наследие Милосерды: глава четвертая",
				ko = "메르시아의 유산: 제4장",
				cn = "梅希娅的传承：第四章",
			},
		},
	
		[354287] = {
			readable = "Mercia's Legacy: Chapter Five",
			model = 3045975,
			text = {
				en = "Mercia's Legacy: Chapter Five",
				es = "El legado de Mercia: Capítulo cinco",
				de = "Mercias Vermächtnis: Kapitel fünf",
				fr = "L’héritage de Mercia : chapitre V",
				it = "Retaggio di Mercia: Capitolo Cinque",
				pt = "Legado de Mércia: Capítulo Cinco",
				ru = "Наследие Милосерды: глава пятая",
				ko = "메르시아의 유산: 제5장",
				cn = "梅希娅的传承：第五章",
			},
		},
	
		[354288] = {
			readable = "Mercia's Legacy: Chapter Six",
			model = 3022977,
			text = {
				en = "Mercia's Legacy: Chapter Six",
				es = "El legado de Mercia: Capítulo seis",
				de = "Mercias Vermächtnis: Kapitel sechs",
				fr = "L’héritage de Mercia : chapitre VI",
				it = "Retaggio di Mercia: Capitolo Sei",
				pt = "Legado de Mércia: Capítulo Seis",
				ru = "Наследие Милосерды: глава шестая",
				ko = "메르시아의 유산: 제6장",
				cn = "梅希娅的传承：第六章",
			},
		},
	
		[354289] = {
			readable = "Windsmith's Tools",
			model = 3040704,
			text = {
				en = "Windsmith's Tools",
				es = "Herramientas de forjador de vientos",
				de = "Werkzeuge des Windschmieds",
				fr = "Outils de Forgevent",
				it = "Attrezzi del Forgiavento",
				pt = "Ferramentas do Forjaventos",
				ru = "Инструменты кузнеца ветра",
				ko = "바람장인의 도구",
				cn = "风匠的工具",
			},
		},
	
		[354467] = {
			readable = "Mercia's Legacy: Chapter Seven",
			model = 3022977,
			text = {
				en = "Mercia's Legacy: Chapter Seven",
				es = "El legado de Mercia: Capítulo siete",
				de = "Mercias Vermächtnis: Kapitel sieben",
				fr = "L’héritage de Mercia : chapitre VII",
				it = "Retaggio di Mercia: Capitolo Sette",
				pt = "Legado de Mércia: Capítulo Sete",
				ru = "Наследие Милосерды: глава седьмая",
				ko = "메르시아의 유산: 제7장",
				cn = "梅希娅的传承：第七章",
			},
		},
	
		[354470] = {
			readable = "Explosive Strength",
			model = 3036709,
			text = {
				en = "Explosive Strength",
				es = "Fuerza explosiva",
				de = "Explosive Stärke",
				fr = "Force explosive",
				it = "Forza Esplosiva",
				pt = "Força Explosiva",
				ru = "Взрывная сила",
				ko = "폭발적인 힘",
				cn = "爆破之力",
			},
		},
	
		[354645] = {
			readable = "Lost Satchel",
			model = 977074,
			text = {
				en = "Lost Satchel",
				es = "Bolsa perdida",
				de = "Verlorenes Säckchen",
				fr = "Sacoche perdue",
				it = "Borsa Perduta",
				pt = "Algibeira Perdida",
				ru = "Потерянная сумка",
				ko = "잃어버린 주머니",
				cn = "失落小包",
			},
		},
	
		[354646] = {
			readable = "Ancient Cloudfeather Egg",
			model = 975361,
			text = {
				en = "Ancient Cloudfeather Egg",
				es = "Huevo de plumanube antiguo",
				de = "Uraltes Wolkenfederei",
				fr = "Œuf de plume-des-nuées ancien",
				it = "Antico Uovo di Piumanube",
				pt = "Ovo de Penuvem Ancestral",
				ru = "Древнее яйцо облачного бегуна",
				ko = "고대 구름깃털 알",
				cn = "远古云羽之卵",
			},
		},
	
		[354647] = {
			readable = "Hearty Dragon Plume",
			model = 199704,
			text = {
				en = "Hearty Dragon Plume",
				es = "Pluma de dragón recia",
				de = "Lebhafte Drachenfeder",
				fr = "Plume de dragon vigoureuse",
				it = "Piuma di Drago Vigorosa",
				pt = "Pluma Robusta de Dragão",
				ru = "Крепкое драконье перо",
				ko = "온화한 용의 깃털",
				cn = "健壮巨龙飞羽",
			},
		},
	
		[354648] = {
			readable = "Darkreach Supplies",
			model = 2029167,
			text = {
				en = "Darkreach Supplies",
				es = "Suministros de Alcance Oscuro",
				de = "Dunkelvorstoßvorräte",
				fr = "Fournitures sombres-confins",
				it = "Rifornimenti di Poggioscuro",
				pt = "Suprimentos da Extensão Sombria",
				ru = "Припасы Темного Края",
				ko = "어둠마루 보급품",
				cn = "暗临之地补给品",
			},
		},
	
		[354649] = {
			readable = "Relic Hoard",
			model = 3189119,
			text = {
				en = "Relic Hoard",
				es = "Tesoro de reliquias",
				de = "Reliktschatz",
				fr = "Cache de reliques",
				it = "Scorta di Reliquie",
				pt = "Monte de Relíquias",
				ru = "Сундук Деми",
				ko = "유물 비축물",
				cn = "囤积的圣物",
			},
		},
	
		[354650] = {
			readable = "Dreamsong Heart",
			model = 3255405,
			text = {
				en = "Dreamsong Heart",
				es = "Corazón de Cantosueño",
				de = "Traumsangherz",
				fr = "Cœur chanterêve",
				it = "Cuore di Cantonirico",
				pt = "Coração do Cantonírio",
				ru = "Сердце Песни Сна",
				ko = "꿈결노래 심장",
				cn = "梦歌之心",
			},
		},
	
		[354651] = {
			readable = "Enchanted Dreamcatcher",
			model = 3036126,
			text = {
				en = "Enchanted Dreamcatcher",
				es = "Atrapasueños encantado",
				de = "Verzauberter Traumfänger",
				fr = "Capturêve enchanté",
				it = "Acchiappasogni Incantato",
				pt = "Apanhador de Sonhos Encantado",
				ru = "Зачарованный ловец слов",
				ko = "마력 깃든 꿈잡이",
				cn = "魔法捕梦网",
			},
		},
	
		[354652] = {
			readable = "Faerie Trove",
			model = 3036103,
			text = {
				en = "Faerie Trove",
				es = "Tesoro de hada",
				de = "Feenschatz",
				fr = "Trésor féerique",
				it = "Collezione dei Silfidi",
				pt = "Tesouro Feério",
				ru = "Тайник пикси",
				ko = "페어리의 보물",
				cn = "妖精宝藏",
			},
		},
	
		[354657] = {
			readable = "Medallion of Dominion",
			model = 3535749,
			text = {
				en = "Medallion of Dominion",
				es = "Medallón de dominio",
				de = "Medaillon der Herrschaft",
				fr = "Médaillon de la domination",
				it = "Medaglione del Dominio",
				pt = "Medalhão do Domínio",
				ru = "Медальон Господства",
				ko = "지배의 메달",
				cn = "统御勋章",
			},
		},
	
		[354658] = {
			readable = "Sinstone",
			model = 2835342,
			text = {
				en = "Sinstone",
				es = "Piedra del pecado",
				de = "Sündenstein",
				fr = "Stèle du vice",
				it = "Pietra del Peccato",
				pt = "Pedra de Pecado",
				ru = "Камень грехов",
				ko = "죄악석",
				cn = "罪碑",
			},
		},
	
		[354662] = {
			readable = "Elusive Faerie Cache",
			model = 3522547,
			text = {
				en = "Elusive Faerie Cache",
				es = "Alijo de hada esquiva",
				de = "Schwer zu findende Feentruhe",
				fr = "Cache féerique insaisissable",
				it = "Scrigno Elusivo dei Silfidi",
				pt = "Baú Esquivo das Fadas",
				ru = "Хитрый тайник пикси",
				ko = "교묘한 페어리 보관함",
				cn = "隐蔽的妖精宝箱",
			},
		},
	
		[354665] = {
			readable = "Faerie Lamp",
			model = 3036106,
			text = {
				en = "Faerie Lamp",
				es = "Farol de hada",
				de = "Feenlampe",
				fr = "Lampe faë",
				it = "Lampada dei Silfidi",
				pt = "Lâmpada das Fadas",
				ru = "Волшебная лампа",
				ko = "페어리 등불",
				cn = "妖精灯笼",
			},
		},
	
		[354685] = {
			readable = "Flame of Oblivion",
			model = 3160240,
			text = {
				en = "Flame of Oblivion",
				es = "Llama del olvido",
				de = "Flamme des Vergessens",
				fr = "Flamme de l’oubli",
				it = "Fiamma dell'Oblio",
				pt = "Chama do Oblívio",
				ru = "Пламя забвения",
				ko = "망각의 불꽃",
				cn = "湮灭火焰",
			},
		},
	
		[354694] = {
			readable = "9DU_Bwonsamdidungeon_GlowPaint05",
			model = 3591363,
			text = {
				en = "9DU_Bwonsamdidungeon_GlowPaint05",
				ko = "9DU_브원삼디던전_발광지점05",
			},
		},
	
		[354848] = {
			readable = "Fragile Humility Scroll",
			model = 3045976,
			text = {
				en = "Fragile Humility Scroll",
				es = "Pergamino de humildad frágil",
				de = "Brüchige Schriftrolle der Demut",
				fr = "Parchemin d’humilité fragile",
				it = "Pergamena dell'Umiltà Fragile",
				pt = "Pergaminho da Humildade Frágil",
				ru = "Хрупкий свиток смирения",
				ko = "바스러질 듯한 겸손의 두루마리",
				cn = "脆弱的谦逊卷轴",
			},
		},
	
		[354849] = {
			readable = "Aspirant's Belongings",
			model = 3189120,
			text = {
				en = "Aspirant's Belongings",
				es = "Pertenencias de aspirante",
				de = "Habseligkeiten des Aspiranten",
				fr = "Possessions d’aspirant",
				it = "Effetti Personali dell'Aspirante",
				pt = "Pertences do Aspirante",
				ru = "Вещи претендента",
				ko = "열망자의 소지품",
				cn = "候选者的所有物",
			},
		},
	
		[354852] = {
			readable = "Sprouting Growth",
			model = 973262,
			text = {
				en = "Sprouting Growth",
				es = "Crecimiento floreciente",
				de = "Sprießender Auswuchs",
				fr = "Pousse germée",
				it = "Crescita Germogliante",
				pt = "Crescimento Brotante",
				ru = "Тянущийся росток",
				ko = "싹트는 증식물",
				cn = "出芽增生",
			},
		},
	
		[354853] = {
			readable = "Sprouting Growth",
			model = 973262,
			text = {
				en = "Sprouting Growth",
				es = "Crecimiento floreciente",
				de = "Sprießender Auswuchs",
				fr = "Pousse germée",
				it = "Crescita Germogliante",
				pt = "Crescimento Brotante",
				ru = "Тянущийся росток",
				ko = "싹트는 증식물",
				cn = "出芽增生",
			},
		},
	
		[354855] = {
			readable = "Lever",
			model = 3229893,
			text = {
				en = "Lever",
				es = "Palanca",
				de = "Hebel",
				fr = "Levier",
				it = "Leva",
				pt = "Alavanca",
				ru = "Рычаг",
				ko = "조작 막대",
				cn = "拉杆",
			},
		},
	
		[354856] = {
			readable = "Slime-Coated Crate",
			model = 3193905,
			text = {
				en = "Slime-Coated Crate",
				es = "Cajón cubierto de baba",
				de = "Schleimbedeckte Kiste",
				fr = "Caisse couverte de vase",
				it = "Cassa Coperta di Poltiglia",
				pt = "Caixote Coberto de Visgo",
				ru = "Покрытый слизью ящик",
				ko = "점액으로 뒤덮인 상자",
				cn = "软泥覆盖的箱子",
			},
		},
	
		[354858] = {
			readable = "Portal",
			model = 3613913,
			text = {
				en = "Portal",
				fr = "Portail",
				it = "Portale",
				ru = "Портал",
				ko = "차원문",
				cn = "传送门",
			},
		},
	
		[354859] = {
			readable = "Worthy Aspirant's Cache",
			model = 3189120,
			text = {
				en = "Worthy Aspirant's Cache",
				es = "Alijo de aspirante digno",
				de = "Truhe der würdigen Aspirantin",
				fr = "Cache d’aspirant méritant",
				it = "Scrigno dell'Aspirante Degno",
				pt = "Baú do Aspirante Valoroso",
				ru = "Тайник достойного претендента",
				ko = "가치 있는 열망자의 보관함",
				cn = "合格的候选者的宝箱",
			},
		},
	
		[354911] = {
			readable = "Swollen Anima Seed",
			model = 3158888,
			text = {
				en = "Swollen Anima Seed",
				es = "Semilla de ánima hinchada",
				de = "Aufgequollener Animasamen",
				fr = "Graine d’anima gonflée",
				it = "Seme dell'Animum Rigonfio",
				pt = "Semente de Ânima Inchada",
				ru = "Набухшее анимасемя",
				ko = "부풀어 오른 령 씨앗",
				cn = "鼓胀的心能之种",
			},
		},
	
		[354920] = {
			readable = "Discarded Phalynx Core",
			model = 3073142,
			text = {
				en = "Discarded Phalynx Core",
				es = "Núcleo de falince descartado",
				de = "Ausgemusterter Phalynxkern",
				fr = "Noyau de phalynx abandonné",
				it = "Nucleo di Falince Scartato",
				pt = "Núcleo de Falince Descartado",
				ru = "Выброшенное ядро анимапарда",
				ko = "버려진 스라수호기 핵",
				cn = "被遗弃的灵豹之核",
			},
		},
	
		[354937] = {
			readable = "Pain Conduit",
			model = 3581362,
			text = {
				en = "Pain Conduit",
				es = "Conducto de dolor",
				de = "Schmerzleitung",
				fr = "Intermédiaire de souffrance",
				it = "Condotto del Dolore",
				pt = "Conduto de Dor",
				ru = "Проводник боли",
				ko = "고통의 도관",
				cn = "痛苦导管",
			},
		},
	
		[354972] = {
			readable = "Challenger's Cache",
			model = 1314905,
			text = {
				en = "Challenger's Cache",
				es = "Alijo de contendiente",
				de = "Schatz des Herausforderers",
				fr = "Cache de prétendant",
				it = "Cassa dello Sfidante",
				pt = "Baú do Desafiante",
				ru = "Тайник претендента",
				ko = "도전자의 보관함",
				cn = "挑战者的箱子",
			},
		},
	
		[354985] = {
			readable = "Challenger's Cache",
			model = 1314905,
			text = {
				en = "Challenger's Cache",
				es = "Alijo de contendiente",
				de = "Schatz des Herausforderers",
				fr = "Cache de prétendant",
				it = "Cassa dello Sfidante",
				pt = "Baú do Desafiante",
				ru = "Тайник претендента",
				ko = "도전자의 보관함",
				cn = "挑战者的箱子",
			},
		},
	
		[354986] = {
			readable = "Challenger's Cache",
			model = 1314905,
			text = {
				en = "Challenger's Cache",
				es = "Alijo de contendiente",
				de = "Schatz des Herausforderers",
				fr = "Cache de prétendant",
				it = "Cassa dello Sfidante",
				pt = "Baú do Desafiante",
				ru = "Тайник претендента",
				ko = "도전자의 보관함",
				cn = "挑战者的箱子",
			},
		},
	
		[354987] = {
			readable = "Challenger's Cache",
			model = 1314905,
			text = {
				en = "Challenger's Cache",
				es = "Alijo de contendiente",
				de = "Schatz des Herausforderers",
				fr = "Cache de prétendant",
				it = "Cassa dello Sfidante",
				pt = "Baú do Desafiante",
				ru = "Тайник претендента",
				ko = "도전자의 보관함",
				cn = "挑战者的箱子",
			},
		},
	
		[354988] = {
			readable = "Challenger's Cache",
			model = 1314905,
			text = {
				en = "Challenger's Cache",
				es = "Alijo de contendiente",
				de = "Schatz des Herausforderers",
				fr = "Cache de prétendant",
				it = "Cassa dello Sfidante",
				pt = "Baú do Desafiante",
				ru = "Тайник претендента",
				ko = "도전자의 보관함",
				cn = "挑战者的箱子",
			},
		},
	
		[354989] = {
			readable = "Challenger's Cache",
			model = 1314905,
			text = {
				en = "Challenger's Cache",
				es = "Alijo de contendiente",
				de = "Schatz des Herausforderers",
				fr = "Cache de prétendant",
				it = "Cassa dello Sfidante",
				pt = "Baú do Desafiante",
				ru = "Тайник претендента",
				ko = "도전자의 보관함",
				cn = "挑战者的箱子",
			},
		},
	
		[354990] = {
			readable = "Challenger's Cache",
			model = 1314905,
			text = {
				en = "Challenger's Cache",
				es = "Alijo de contendiente",
				de = "Schatz des Herausforderers",
				fr = "Cache de prétendant",
				it = "Cassa dello Sfidante",
				pt = "Baú do Desafiante",
				ru = "Тайник претендента",
				ko = "도전자의 보관함",
				cn = "挑战者的箱子",
			},
		},
	
		[354991] = {
			readable = "Challenger's Cache",
			model = 1314905,
			text = {
				en = "Challenger's Cache",
				es = "Alijo de contendiente",
				de = "Schatz des Herausforderers",
				fr = "Cache de prétendant",
				it = "Cassa dello Sfidante",
				pt = "Baú do Desafiante",
				ru = "Тайник претендента",
				ko = "도전자의 보관함",
				cn = "挑战者的箱子",
			},
		},
})
do ObjectDB[objectID] = objectData; end
