local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	
		[244000] = {
			readable = "Saris' Hammer",
			model = 395302,
			text = {
				en = "Saris' Hammer",
				es = "Martillo de Saris",
				fr = "Marteau de Saris",
				it = "Martello di Saris",
				pt = "Martelo de Saris",
				ru = "Молот Сариса",
				ko = "사리스의 망치",
				cn = "萨里斯之锤",
			},
		},
	
		[244001] = {
			readable = "Saris' Research",
			model = 1146908,
			text = {
				en = "Saris' Research",
				es = "Investigación de Saris",
				de = "Saris' Aufzeichnungen",
				fr = "Recherches de Saris",
				it = "Ricerche di Saris",
				pt = "Pesquisa de Saris",
				ru = "Исследования Сариса",
				ko = "사리스의 연구",
				cn = "萨里斯的研究笔记",
			},
		},
	
		[244335] = {
			readable = "Ritual Circle",
			model = 986958,
			text = {
				en = "Ritual Circle",
				es = "Círculo ritual",
				de = "Ritualkreis",
				fr = "Cercle rituel",
				it = "Circolo del Rituale",
				pt = "Círculo Ritual",
				ru = "Ритуальный круг",
				ko = "의식 진",
				cn = "仪式圆环",
			},
		},
	
		[244336] = {
			readable = "Ritual Circle",
			model = 986958,
			text = {
				en = "Ritual Circle",
				es = "Círculo ritual",
				de = "Ritualkreis",
				fr = "Cercle rituel",
				it = "Circolo del Rituale",
				pt = "Círculo Ritual",
				ru = "Ритуальный круг",
				ko = "의식 진",
				cn = "仪式圆环",
			},
		},
	
		[244337] = {
			readable = "Ritual Circle",
			model = 986958,
			text = {
				en = "Ritual Circle",
				es = "Círculo ritual",
				de = "Ritualkreis",
				fr = "Cercle rituel",
				it = "Circolo del Rituale",
				pt = "Círculo Ritual",
				ru = "Ритуальный круг",
				ko = "의식 진",
				cn = "仪式圆环",
			},
		},
	
		[244419] = {
			readable = "Eagle Egg",
			model = 661112,
			text = {
				en = "Eagle Egg",
				es = "Huevo de águila",
				de = "Adlerei",
				fr = "Œuf d’aigle",
				it = "Uova di Aquila",
				pt = "Ovo de Águia",
				ru = "Орлиное яйцо",
			},
		},
	
		[244429] = {
			readable = "Totally Safe Treasure Chest",
			model = 446677,
			text = {
				en = "Totally Safe Treasure Chest",
				es = "Arqueta totalmente segura",
				de = "Vollkommen sichere Schatztruhe",
				fr = "Coffre au trésor dénué de tout danger",
				it = "Cassa del Tesoro Totalmente Sicura",
				pt = "Baú do Tesouro Totalmente Seguro",
				ru = "Совершенно безопасный сундук с сокровищами",
				ko = "전적으로 안전한 보물 상자",
				cn = "完全安全的宝箱",
			},
		},
	
		[244431] = {
			readable = "Maelstrom Pillar",
			model = 987009,
			text = {
				en = "Maelstrom Pillar",
				es = "Pilar de La Vorágine",
				de = "Mahlstromsäule",
				fr = "Pilier du Maelström",
				it = "Pilastro del Maelstrom",
				pt = "Pilar da Voragem",
				ru = "Столп Водоворота",
			},
		},
	
		[244439] = {
			readable = "Legion Communicator",
			model = 1125326,
			text = {
				en = "Legion Communicator",
				es = "Comunicador de la Legión",
				de = "Legionskommunikator",
				fr = "Communicateur de la Légion",
				it = "Comunicatore della Legione",
				pt = "Comunicador da Legião",
				ru = "Переговорное устройство Легиона",
				ko = "군단 통신기",
				cn = "军团联络器",
			},
		},
	
		[244440] = {
			readable = "Legion Communicator",
			model = 1125326,
			text = {
				en = "Legion Communicator",
				es = "Comunicador de la Legión",
				de = "Legionskommunikator",
				fr = "Communicateur de la Légion",
				it = "Comunicatore della Legione",
				pt = "Comunicador da Legião",
				ru = "Переговорное устройство Легиона",
				ko = "군단 통신기",
				cn = "军团联络器",
			},
		},
	
		[244441] = {
			readable = "Legion Communicator",
			model = 1125326,
			text = {
				en = "Legion Communicator",
				es = "Comunicador de la Legión",
				de = "Legionskommunikator",
				fr = "Communicateur de la Légion",
				it = "Comunicatore della Legione",
				pt = "Comunicador da Legião",
				ru = "Переговорное устройство Легиона",
				ko = "군단 통신기",
				cn = "军团联络器",
			},
		},
	
		[244446] = {
			readable = "Actually Safe Treasure Chest",
			model = 446677,
			text = {
				en = "Actually Safe Treasure Chest",
				es = "Arqueta segura de verdad",
				de = "Tatsächlich sichere Schatztruhe",
				fr = "Coffre au trésor vraiment sans danger",
				it = "Cassa del Tesoro Molto Sicura",
				pt = "Baú do Tesouro Realmente Seguro",
				ru = "Абсолютно безопасный сундук с сокровищами",
				ko = "정말로 안전한 보물 상자",
			},
		},
	
		[244447] = {
			readable = "White Murloc Egg",
			model = 202737,
			text = {
				en = "White Murloc Egg",
				es = "Huevo de múrloc blanco",
				de = "Weißes Murlocei",
				fr = "Œuf de Murloc blanc",
				it = "Uovo di Murloc Bianco",
				pt = "Ovo de Murloc Branco",
				ru = "Белое яйцо мурлока",
				cn = "白色鱼人卵",
			},
		},
	
		[244449] = {
			readable = "Reflective Mirror",
			model = 1269560,
			text = {
				en = "Reflective Mirror",
				es = "Espejo reflectante",
				de = "Glänzender Spiegel",
				fr = "Miroir réfléchissant",
				it = "Specchio Riflettente",
				pt = "Espelho",
				ru = "Отражающее зеркало",
				ko = "반사의 거울",
				cn = "反射镜",
			},
		},
	
		[244450] = {
			readable = "Rune of Reformation",
			model = 984707,
			text = {
				en = "Rune of Reformation",
				es = "Runa de reformación",
				de = "Rune der Erneuerung",
				fr = "Rune de palingénésie",
				it = "Runa della Riformazione",
				pt = "Runa da Reforma",
				ru = "Руна преобразования",
				ko = "재구성의 룬",
				cn = "重组符文",
			},
		},
	
		[244453] = {
			readable = "Cullen's Scouting Report",
			model = 936441,
			text = {
				en = "Cullen's Scouting Report",
				es = "Informe de exploración de Cullen",
				de = "Cullens Späherreport",
				fr = "Rapport de reconnaissance de Cullen",
				it = "Rapporto Esplorativo di Cullen",
				pt = "Relatório de Patrulha de Cullen",
				ru = "Разведданные Куллен",
				ko = "쿨렌의 정찰 보고서",
				cn = "库伦的侦察报告",
			},
		},
	
		[244454] = {
			readable = "Molted Plume",
			model = 243425,
			text = {
				en = "Molted Plume",
				es = "Pluma de muda",
				de = "Gemauserte Feder",
				fr = "Plume perdue",
				pt = "Pluma Largada",
				ru = "Линялое оперение",
			},
		},
	
		[244455] = {
			readable = "Pool of Judgment",
			model = 1310776,
			text = {
				en = "Pool of Judgment",
				es = "Poza del juicio",
				de = "Becken des Urteils",
				fr = "Bassin du Jugement",
				it = "Fonte del Giudizio",
				pt = "Águas do Julgamento",
				ru = "Источник Правосудия",
				ko = "심판의 웅덩이",
				cn = "审判之池",
			},
		},
	
		[244457] = {
			readable = "Spitefeather's Rock",
			model = 1121351,
			text = {
				en = "Spitefeather's Rock",
				es = "Roca de Plumarrencor",
				de = "Hassfeders Felsen",
				fr = "Rocher de Plumépris",
				it = "Roccia di Piumaperfida",
				pt = "Pedra do Penatroz",
				ru = "Камень Злобного Пера",
				ko = "원한깃털의 바위",
				cn = "怨羽的栖岩",
			},
		},
	
		[244460] = {
			readable = "Shard Caller Idol",
			model = 1141734,
			text = {
				en = "Shard Caller Idol",
				es = "Ídolo de invocador de fragmentos",
				de = "Scherbenrufergötze",
				fr = "Idole du mande-éclat",
				it = "Idolo dell'Invocatore di Cristalli",
				pt = "Ídolo Chama-astilha",
				ru = "Призывающий осколки идол",
				ko = "파편 소환사 우상",
				cn = "碎片召唤者雕像",
			},
		},
	
		[244463] = {
			readable = "Shard Caller Idol",
			model = 1141734,
			text = {
				en = "Shard Caller Idol",
				es = "Ídolo de invocador de fragmentos",
				de = "Scherbenrufergötze",
				fr = "Idole du mande-éclat",
				it = "Idolo dell'Invocatore di Cristalli",
				pt = "Ídolo Chama-astilha",
				ru = "Призывающий осколки идол",
				ko = "파편 소환사 우상",
				cn = "碎片召唤者雕像",
			},
		},
	
		[244466] = {
			readable = "Fel Portal",
			model = 1268729,
			text = {
				en = "Fel Portal",
				es = "Portal vil",
				de = "Teufelsportal",
				fr = "Gangreportail",
				it = "Vilportale",
				pt = "Portal Vil",
				ru = "Портал Скверны",
				ko = "지옥 차원문",
				cn = "邪能传送门",
			},
		},
	
		[244472] = {
			readable = "Icecrown Bonepile 02",
			model = 342585,
			text = {
				en = "Icecrown Bonepile 02",
				it = "Mucchio d'Ossa della Corona di Ghiaccio",
				cn = "冰冠堡垒骨堆",
			},
		},
	
		[244473] = {
			readable = "Thunder Totem Stolen Goods",
			icon = 134344,
			model = 979119,
			text = {
				en = "Thunder Totem Stolen Goods",
				es = "Bienes robados de los Tótem del Trueno",
				de = "Gestohlene Güter aus Donnertotem",
				fr = "Marchandises de Totem-du-Tonnerre volées",
				it = "Beni Rubati di Totem del Fulmine",
				pt = "Itens Roubados dos Totem do Trovão",
				ru = "Украденные припасы Громового Тотема",
				ko = "천둥 토템 도난당한 물품",
				cn = "雷霆图腾失窃货物",
			},
		},
	
		[244494] = {
			readable = "Treasure Chest",
			model = 1402238,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[244499] = {
			readable = "Potion of Fel Protection",
			model = 243486,
			text = {
				en = "Potion of Fel Protection",
				es = "Poción de protección vil",
				de = "Teufelsschutztrank",
				fr = "Potion de protection gangrenée",
				it = "Pozione della Vilprotezione",
				pt = "Poção de Proteção Vil",
				ru = "Зелье защиты Скверны",
			},
		},
	
		[244510] = {
			readable = "Portal to Dalaran",
			model = 244119,
			text = {
				en = "Portal to Dalaran",
				es = "Portal a Dalaran",
				de = "Portal nach Dalaran",
				fr = "Portail vers Dalaran",
				it = "Portale per Dalaran",
				pt = "Portal para Dalaran",
				ru = "Портал в Даларан",
				ko = "달라란으로 통하는 차원문",
				cn = "通往达拉然的传送门",
			},
		},
	
		[244513] = {
			readable = "Jar of Spiders",
			model = 203911,
			text = {
				en = "Jar of Spiders",
				es = "Jarra de arañas",
				de = "Glas mit Spinnen",
				fr = "Bocal d’araignées",
				it = "Barattolo di Ragni",
				pt = "Jarro de Aranhas",
				ru = "Банка с пауками",
			},
		},
	
		[244519] = {
			readable = "Treasure Chest",
			model = 1402238,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[244555] = {
			readable = "Mysterious Dust",
			model = 533091,
			text = {
				en = "Mysterious Dust",
				es = "Polvo misterioso",
				de = "Geheimnisvoller Staub",
				fr = "Poussière mystérieuse",
				it = "Polvere Misteriosa",
				pt = "Poeira Misteriosa",
				ru = "Таинственная пыль",
			},
		},
	
		[244556] = {
			readable = "Portal to Dalaran",
			model = 244119,
			text = {
				en = "Portal to Dalaran",
				es = "Portal a Dalaran",
				de = "Portal nach Dalaran",
				fr = "Portail vers Dalaran",
				it = "Portale per Dalaran",
				pt = "Portal para Dalaran",
				ru = "Портал в Даларан",
				ko = "달라란으로 통하는 차원문",
				cn = "通往达拉然的传送门",
			},
		},
	
		[244559] = {
			readable = "Helya's Altar",
			model = 189280,
			text = {
				en = "Helya's Altar",
				es = "Altar de Helya",
				de = "Helyas Altar",
				fr = "Autel de Helya",
				it = "Altare di Helya",
				pt = "Altar de Helya",
				ru = "Алтарь Хелии",
				ko = "헬리아의 제단",
				cn = "海拉的祭坛",
			},
		},
	
		[244564] = {
			readable = "Altar",
			model = 800839,
			text = {
				en = "Altar",
				fr = "Autel",
				it = "Altare",
				ru = "Алтарь",
				ko = "제단",
				cn = "祭坛",
			},
		},
	
		[244565] = {
			readable = "Kvaldir Spoils",
			model = 987255,
			text = {
				en = "Kvaldir Spoils",
				es = "Botín Kvaldir",
				de = "Kriegsbeute der Kvaldir",
				fr = "Butin kvaldir",
				it = "Spoglie Kvaldir",
				pt = "Espólios Kvaldir",
				ru = "Добыча квалдиров",
				ko = "크발디르 전리품",
				cn = "克瓦迪尔战利品",
			},
		},
	
		[244567] = {
			readable = "Portal to The Skyfire",
			model = 197051,
			text = {
				en = "Portal to The Skyfire",
				es = "Portal a El Abrasacielos",
				de = "Portal zur Himmelsfeuer",
				fr = "Portail vers le Brûleciel",
				it = "Portale per la Fuoco Celeste",
				pt = "Portal para o Celesfogo",
				ru = "Портал на \"Небесный огонь\"",
				ko = "하늘불꽃호로 통하는 차원문",
				cn = "通往天火号的传送门",
			},
		},
	
		[244568] = {
			readable = "Spooky Pepe",
			model = 1246563,
			text = {
				en = "Spooky Pepe",
				es = "Pepe espeluznante",
				de = "Schauriger Pepe",
				fr = "Pépé épouvantable",
				it = "Pepe Spettrale",
				pt = "Pepe Assustador",
				ru = "Зловещий Пепе",
				ko = "으스스한 피프",
				cn = "幽灵佩佩",
			},
		},
	
		[244571] = {
			readable = "Portal to The Dark Lady's Fleet",
			model = 197047,
			text = {
				en = "Portal to The Dark Lady's Fleet",
				es = "Portal a la flota de la Dama Oscura",
				de = "Portal zur Flotte der Dunklen Fürstin",
				fr = "Portail vers la flotte de la Dame noire",
				it = "Portale per la Flotta della Dama Oscura",
				pt = "Portal para a Frota da Dama Sombria",
				ru = "Портал к флоту Темной Госпожи",
				ko = "어둠의 여왕의 함대로 통하는 차원문",
				cn = "通往黑暗女王舰队的传送门",
			},
		},
	
		[244573] = {
			readable = "Blight Sample",
			model = 194843,
			text = {
				en = "Blight Sample",
				es = "Muestra de añublo",
				de = "Seuchenprobe",
				fr = "Échantillon de chancre",
				pt = "Amostra de Praga",
				ru = "Образец гнили",
			},
		},
	
		[244578] = {
			readable = "Alchemical Flame",
			model = 304792,
			text = {
				en = "Alchemical Flame",
				es = "Llama alquímica",
				de = "Alchemistische Flamme",
				fr = "Flamme alchimique",
				it = "Fiamma Alchemica",
				pt = "Chama Alquímica",
				ru = "Алхимическое пламя",
				ko = "연금술 불꽃",
				cn = "炼金烈焰",
			},
		},
	
		[244579] = {
			readable = "Spellbound Insulation",
			model = 579122,
			text = {
				en = "Spellbound Insulation",
				es = "Aislante vinculado",
				de = "Bezauberte Isolierung",
				fr = "Isolant envoûté",
				it = "Isolamento Magico",
				pt = "Isolamento Enfeitiçado",
				ru = "Зачарованная изоляция",
				ko = "주문결속 차단제",
				cn = "缚法隔离层",
			},
		},
	
		[244581] = {
			readable = "Decommissioned Calefactor",
			model = 309721,
			text = {
				en = "Decommissioned Calefactor",
				es = "Calefactor descatalogado",
				de = "Stillgelegte Heizung",
				fr = "Radiateur hors d’usage",
				it = "Calefactor Smantellato",
				pt = "Calefador Desativado",
				ru = "Списанный нагреватель",
				ko = "폐기된 가열기",
				cn = "报废的加热器",
			},
		},
	
		[244588] = {
			readable = "Warden Cell",
			model = 1118869,
			text = {
				en = "Warden Cell",
				es = "Celda de celador",
				de = "Zelle der Wächterinnen",
				fr = "Cellule du gardien",
				it = "Cella delle Custodi",
				pt = "Cela da Guardiã",
				ru = "Камера Стражей",
				ko = "감시관의 수용실",
				cn = "守望者牢笼",
			},
		},
	
		[244597] = {
			readable = "Underbelly Hoard",
			model = 629720,
			text = {
				en = "Underbelly Hoard",
				es = "Tesoro de Los Bajos Fondos",
				de = "Hort der Schattenseite",
				fr = "Trésor des Entrailles",
				it = "Bottino dei Sotterranei",
				pt = "Tesouro dos Esgotos",
				ru = "Сокровищница Клоаки",
				ko = "마법의 뒤안길 보물",
				cn = "下水道宝箱",
			},
		},
	
		[244598] = {
			readable = "Underbelly Cache",
			model = 1100065,
			text = {
				en = "Underbelly Cache",
				es = "Alijo de Los Bajos Fondos",
				de = "Vorrat der Schattenseite",
				fr = "Cache des Entrailles",
				it = "Cassa dei Sotterranei",
				pt = "Esconderijo dos Esgotos",
				ru = "Тайник Клоаки",
				ko = "마법의 뒤안길 보관함",
				cn = "下水道箱子",
			},
		},
	
		[244599] = {
			readable = "Underbelly Spoils",
			model = 979397,
			text = {
				en = "Underbelly Spoils",
				es = "Botín de Los Bajos Fondos",
				de = "Beute der Schattenseite",
				fr = "Butin des Entrailles",
				it = "Spoglie dei Sotterranei",
				pt = "Espólios dos Esgotos",
				ru = "Трофеи Клоаки",
				ko = "마법의 뒤안길 전리품",
				cn = "下水道战利品",
			},
		},
	
		[244601] = {
			readable = "Spire Stabilizer",
			model = 1243753,
			text = {
				en = "Spire Stabilizer",
				es = "Estabilizador de púa",
				de = "Pfeilerstabilisator",
				fr = "Stabilisateur de flèche",
				it = "Stabilizzatore della Spira",
				pt = "Estabilizador da Torre",
				ru = "Стабилизатор шпиля",
				ko = "첨탑 안정기",
				cn = "尖塔稳定器",
			},
		},
	
		[244604] = {
			readable = "Spire Stabilizer",
			model = 1243753,
			text = {
				en = "Spire Stabilizer",
				es = "Estabilizador de púa",
				de = "Pfeilerstabilisator",
				fr = "Stabilisateur de flèche",
				it = "Stabilizzatore della Spira",
				pt = "Estabilizador da Torre",
				ru = "Стабилизатор шпиля",
				ko = "첨탑 안정기",
				cn = "尖塔稳定器",
			},
		},
	
		[244625] = {
			readable = "Cup",
			model = 1102409,
			text = {
				en = "Cup",
				es = "Taza",
				de = "Tasse",
				fr = "Coupe",
				it = "Coppa",
				pt = "Taça",
				ru = "Чаша",
				ko = "컵",
				cn = "杯子",
			},
		},
	
		[244628] = {
			readable = "Taurson's Prize",
			model = 446677,
			text = {
				en = "Taurson's Prize",
				es = "Premio de Taurson",
				de = "Taursons Preis",
				fr = "Prix de Taurson",
				it = "Premio di Taurson",
				pt = "Prêmio de Taurson",
				ru = "Приз Таурсона",
				ko = "타우르슨의 상품",
				cn = "陶森的奖品",
			},
		},
	
		[244638] = {
			readable = "Well of Souls",
			model = 1125333,
			text = {
				en = "Well of Souls",
				es = "Pozo de Almas",
				de = "Brunnen der Seelen",
				fr = "Puits des âmes",
				it = "Pozzo delle Anime",
				pt = "Poço das Almas",
				ru = "Колодец душ",
				ko = "영혼샘",
				cn = "灵魂之井",
			},
		},
	
		[244644] = {
			readable = "Warden's Ascent",
			model = 1241135,
			text = {
				en = "Warden's Ascent",
				es = "Ascenso de celador",
				de = "Aufstieg der Wächterin",
				fr = "Ascenseur de gardien",
				it = "Ascesa della Custode",
				pt = "Encosta do Guardião",
				ru = "Лифт стража",
				ko = "감시관의 승강기",
				cn = "守望者升降梯",
			},
		},
	
		[244646] = {
			readable = "Horde Supplies",
			model = 199101,
			text = {
				en = "Horde Supplies",
				es = "Suministros de la Horda",
				de = "Vorräte der Horde",
				fr = "Fournitures de la Horde",
				it = "Provviste dell'Orda",
				pt = "Suprimentos da Horda",
				ru = "Припасы Орды",
			},
		},
	
		[244651] = {
			readable = "Steamy Romance Novel",
			model = 198017,
			text = {
				en = "Steamy Romance Novel",
				es = "Novela romántica tórrida",
				de = "Schlüpfriger Romantikschmöker",
				fr = "Roman d’amour torride",
				it = "Romanzo Rosa",
				pt = "Romance Apimentado",
				ru = "Скабрезный любовный роман",
				ko = "야한 연애 소설",
				cn = "催人泪下的言情小说",
			},
		},
	
		[244667] = {
			readable = "Abandoned Fishing Pole",
			model = 243299,
			text = {
				en = "Abandoned Fishing Pole",
				es = "Caña de pescar abandonada",
				de = "Liegen gelassene Angelrute",
				fr = "Canne à pêche abandonnée",
				it = "Canna da Pesca Abbandonata",
				pt = "Vara de Pescar Abandonada",
				ru = "Забытая удочка",
				ko = "버려진 낚싯대",
				cn = "被遗弃的鱼竿",
			},
		},
	
		[244669] = {
			readable = "Finalize Obliterum Forge",
			model = 1003197,
			text = {
				en = "Finalize Obliterum Forge",
				es = "Forja de obliterum terminada",
				de = "Stellt die Obliterumschmiede fertig",
				fr = "Finaliser la Forge à oblitérium",
				pt = "Finalizar Forja de Obliterum",
				ru = "Завершить создание Горна аннигиляции",
			},
		},
	
		[244678] = {
			readable = "|cFFFFFFFFStep 8:|r Page 5555",
			icon = 1505961,
			model = 305393,
			text = {
				en = "|cFFFFFFFFStep 8:|r Page 5555",
				es = "|cFFFFFFFFStep 8:|r Página 5555",
				de = "|cFFFFFFFFSchritt 8:|r Seite 5555",
				fr = "|cFFFFFFFFÉtape 8:|r Page 5555",
				it = "|cFFFFFFFFStep 8:|r Pagina 5.555",
				pt = "|cFFFFFFFFStep 8:|r Página 5555",
				ru = "|cFFFFFFFFШаг 8:|r Страница 5555",
				ko = "[Page 5555]",
				cn = "|cFFFFFFFF第8步:|r 第5555页",
			},
		},
	
		[244679] = {
			readable = "Hearthstone Card",
			model = 191946,
			text = {
				en = "Hearthstone Card",
				es = "Carta de Hearthstone",
				de = "Hearthstone-Karte",
				fr = "Carte de Hearthstone",
				it = "Carta di Hearthstone",
				pt = "Card de Hearthstone",
				ru = "Карта Hearthstone",
			},
		},
	
		[244689] = {
			readable = "Small Treasure Chest",
			icon = 308482,
			model = 1349995,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[244690] = {
			readable = "Sand Dune",
			model = 1282165,
			text = {
				en = "Sand Dune",
				es = "Duna de arena",
				de = "Sanddüne",
				fr = "Dune de sable",
				it = "Duna di Sabbia",
				pt = "Duna",
				ru = "Песчаная дюна",
				ko = "모래 언덕",
				cn = "沙丘",
			},
		},
	
		[244691] = {
			readable = "Small Treasure Chest",
			icon = 308482,
			model = 1349995,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[244692] = {
			readable = "Small Treasure Chest",
			icon = 308482,
			model = 1349995,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[244694] = {
			readable = "Small Treasure Chest",
			icon = 308482,
			model = 1349995,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[244697] = {
			readable = "Battle-Mender's Dressing",
			model = 243298,
			text = {
				en = "Battle-Mender's Dressing",
				es = "Vestido de ensalmador de batalla",
				de = "Verband des Schlachtheilers",
				fr = "Pansement de soigneur de bataille",
				pt = "Vestimentas do Reparador de Batalha",
				ru = "Одеяние боевого лекаря",
			},
		},
	
		[244698] = {
			readable = "Small Treasure Chest",
			icon = 308482,
			model = 1349995,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[244699] = {
			readable = "Small Treasure Chest",
			icon = 308482,
			model = 1349995,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[244700] = {
			readable = "Small Treasure Chest",
			icon = 308482,
			model = 1349995,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[244701] = {
			readable = "Small Treasure Chest",
			icon = 308482,
			model = 1349995,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[244703] = {
			readable = "Nether Circle",
			model = 986958,
			text = {
				en = "Nether Circle",
				es = "Círculo abisal",
				de = "Netherzirkel",
				fr = "Cercle du Néant",
				it = "Portale della Distorsione Fatua",
				pt = "Círculo Etéreo",
				ru = "Круг Пустоты",
				ko = "황천 마법진",
				cn = "虚空法阵",
			},
		},
	
		[244704] = {
			readable = "Tideskorn Banner",
			model = 1132168,
			text = {
				en = "Tideskorn Banner",
				es = "Estandarte Mareskorn",
				de = "Banner der Wellenskorn",
				fr = "Bannière des Mörgestran",
				it = "Stendardo degli Abiskorn",
				pt = "Estandarte Mareskárnio",
				ru = "Волнскорнское знамя",
				ko = "타이드스코른 깃발",
				cn = "蔑魔战旗",
			},
		},
	
		[244705] = {
			readable = "Crystallized Fel Ward",
			model = 1125330,
			text = {
				en = "Crystallized Fel Ward",
				es = "Resguardo vil cristalizado",
				de = "Kristallisierter Teufelszauberschutz",
				fr = "Gangreprotection cristallisée",
				it = "Vilguardia Cristallizzata",
				pt = "Proteção de Cristalização Vil",
				ru = "Кристаллизованный оберег Скверны",
				ko = "지옥 수호물 결정",
				cn = "晶化邪能结界",
			},
		},
	
		[244706] = {
			readable = "Fel Power Rune",
			model = 1282689,
			text = {
				en = "Fel Power Rune",
				es = "Runa de poder vil",
				de = "Teufelskraftrune",
				fr = "Rune de puissance gangrenée",
				it = "Runa del Vilpotere",
				pt = "Runa de Poder Vil",
				ru = "Руна мощи Скверны",
				ko = "지옥의 힘 룬",
				cn = "邪能符文",
			},
		},
	
		[244708] = {
			readable = "Watcher's Journal",
			model = 1005460,
			text = {
				en = "Watcher's Journal",
				es = "Diario de vigía",
				de = "Tagebuch des Beobachters",
				fr = "Journal de guetteur",
				it = "Diario del Guardiano",
				pt = "Diário do Vigilante",
				ru = "Дневник дозорного",
				ko = "감시자의 일지",
				cn = "守护者的日志",
			},
		},
	
		[244717] = {
			readable = "Sten's Log",
			model = 936378,
			text = {
				en = "Sten's Log",
				es = "Cuaderno de Sten",
				de = "Stens Logbuch",
				fr = "Journal de Sten",
				it = "Diario di Sten",
				pt = "Registro de Sten",
				ru = "Записи Стена",
				ko = "스텐의 기록",
				cn = "斯坦的日志",
			},
		},
	
		[244718] = {
			readable = "Sigrid's Journal",
			model = 929342,
			text = {
				en = "Sigrid's Journal",
				es = "Diario de Sigrid",
				de = "Sigrids Tagebuch",
				fr = "Journal de Sigrid",
				it = "Diario di Sigrid",
				pt = "Diário de Sigrid",
				ru = "Дневник Сигрид",
				ko = "시그리드의 일지",
				cn = "希格里德的日志",
			},
		},
	
		[244719] = {
			readable = "Kjell's Requisition",
			model = 943682,
			text = {
				en = "Kjell's Requisition",
				es = "Requisa de Kjell",
				de = "Kjells Materialliste",
				fr = "Réquisition de Kjell",
				it = "Confisca di Kjell",
				pt = "Requisição de Kjell",
				ru = "Запрос Кьелла",
				ko = "키엘의 요청서",
				cn = "柯吉尔的清单",
			},
		},
	
		[244720] = {
			readable = "Halvir's Roster",
			model = 936435,
			text = {
				en = "Halvir's Roster",
				es = "Registro de Halvir",
				de = "Halvirs Dienstplan",
				fr = "Liste de Halvir",
				it = "Elenco di Halvir",
				pt = "Cronograma de Halvir",
				ru = "Реестр Халвира",
				ko = "할비르의 명부",
				cn = "哈维尔的名册",
			},
		},
	
		[244729] = {
			readable = "Nether Circle",
			model = 986958,
			text = {
				en = "Nether Circle",
				es = "Círculo abisal",
				de = "Netherzirkel",
				fr = "Cercle du Néant",
				it = "Portale della Distorsione Fatua",
				pt = "Círculo Etéreo",
				ru = "Круг Пустоты",
				ko = "황천 마법진",
				cn = "虚空法阵",
			},
		},
	
		[244730] = {
			readable = "Nether Circle",
			model = 986958,
			text = {
				en = "Nether Circle",
				es = "Círculo abisal",
				de = "Netherzirkel",
				fr = "Cercle du Néant",
				it = "Portale della Distorsione Fatua",
				pt = "Círculo Etéreo",
				ru = "Круг Пустоты",
				ko = "황천 마법진",
				cn = "虚空法阵",
			},
		},
	
		[244731] = {
			readable = "Nether Circle",
			model = 986958,
			text = {
				en = "Nether Circle",
				es = "Círculo abisal",
				de = "Netherzirkel",
				fr = "Cercle du Néant",
				it = "Portale della Distorsione Fatua",
				pt = "Círculo Etéreo",
				ru = "Круг Пустоты",
				ko = "황천 마법진",
				cn = "虚空法阵",
			},
		},
	
		[244733] = {
			readable = "Nether Circle",
			model = 986958,
			text = {
				en = "Nether Circle",
				es = "Círculo abisal",
				de = "Netherzirkel",
				fr = "Cercle du Néant",
				it = "Portale della Distorsione Fatua",
				pt = "Círculo Etéreo",
				ru = "Круг Пустоты",
				ko = "황천 마법진",
				cn = "虚空法阵",
			},
		},
	
		[244740] = {
			readable = "Baric's Ritual Essence",
			model = 942868,
			text = {
				en = "Baric's Ritual Essence",
				es = "Esencia de ritual de Baric",
				de = "Barics Ritualessenz",
				fr = "Essence rituelle de Baric",
				it = "Fonte del Rituale di Baric",
				pt = "Essência Ritual de Baric",
				ru = "Эссенция ритуала Барика",
			},
		},
	
		[244741] = {
			readable = "Baric's Ritual Essence",
			model = 942868,
			text = {
				en = "Baric's Ritual Essence",
				es = "Esencia de ritual de Baric",
				de = "Barics Ritualessenz",
				fr = "Essence rituelle de Baric",
				it = "Fonte del Rituale di Baric",
				pt = "Essência Ritual de Baric",
				ru = "Эссенция ритуала Барика",
			},
		},
	
		[244742] = {
			readable = "Baric's Ritual Essence",
			model = 942868,
			text = {
				en = "Baric's Ritual Essence",
				es = "Esencia de ritual de Baric",
				de = "Barics Ritualessenz",
				fr = "Essence rituelle de Baric",
				it = "Fonte del Rituale di Baric",
				pt = "Essência Ritual de Baric",
				ru = "Эссенция ритуала Барика",
			},
		},
	
		[244744] = {
			readable = "Tome of the Ancients",
			model = 1324674,
			text = {
				en = "Tome of the Ancients",
				es = "Tomo de los ancianos",
				de = "Foliant der Ahnen",
				fr = "Tome des anciens",
				it = "Tomo degli Antichi",
				pt = "Tomo dos Antigos",
				ru = "Фолиант Древних",
				ko = "고대의 고서",
				cn = "古树宝典",
			},
		},
	
		[244774] = {
			readable = "Aethril",
			model = 1391548,
			text = {
				en = "Aethril",
				ru = "Айтрил",
				ko = "에이트릴",
				cn = "安瑟瑞尔花",
			},
		},
	
		[244775] = {
			readable = "Dreamleaf",
			model = 1369688,
			text = {
				en = "Dreamleaf",
				es = "Frondasueño",
				de = "Traumlaub",
				fr = "Songefeuille",
				it = "Erbonirica",
				pt = "Folha-de-sonho",
				ru = "Грезолист",
				ko = "꿈잎사귀",
				cn = "入梦叶",
			},
		},
	
		[244776] = {
			readable = "Dreamleaf",
			model = 1370949,
			text = {
				en = "Dreamleaf",
				es = "Frondasueño",
				de = "Traumlaub",
				fr = "Songefeuille",
				it = "Erbonirica",
				pt = "Folha-de-sonho",
				ru = "Грезолист",
				ko = "꿈잎사귀",
				cn = "入梦叶",
			},
		},
	
		[244777] = {
			readable = "Fjarnskaggl",
			model = 1282724,
			text = {
				en = "Fjarnskaggl",
				ru = "Фьярнскаггл",
				ko = "피아른스카글",
				cn = "夏斯卡格草",
			},
		},
	
		[244778] = {
			readable = "Starlight Rose",
			model = 1357601,
			text = {
				en = "Starlight Rose",
				es = "Rosa luz estelar",
				de = "Sternlichtrose",
				fr = "Rose lumétoile",
				it = "Rosa Lucestellare",
				pt = "Rosa-da-luz-estelar",
				ru = "Звездная роза",
				ko = "별빛 장미",
				cn = "星光玫瑰",
			},
		},
	
		[244779] = {
			readable = "Ancient Vrykul Rune Tablet",
			model = 1355115,
			text = {
				en = "Ancient Vrykul Rune Tablet",
				es = "Tablilla rúnica vrykul antigua",
				de = "Uralte Runentafel der Vrykul",
				fr = "Ancienne tablette runique vrykule",
				it = "Tavoletta Runica Antica dei Vrykul",
				pt = "Tabuleta Rúnica Vraikal Antiga",
				ru = "Древняя покрытая рунами врайкульская табличка",
				ko = "고대 브리쿨 룬 석판",
				cn = "古代维库符文石板",
			},
		},
	
		[244786] = {
			readable = "Felwort",
			model = 1284877,
			text = {
				en = "Felwort",
				es = "Matojo vil",
				de = "Teufelswurz",
				fr = "Gangrèche",
				it = "Vilpianta",
				pt = "Maltevil",
				ru = "Зверобой Скверны",
			},
		},
	
		[244794] = {
			readable = "Astral Gate to the Maelstrom",
			model = 1386694,
			text = {
				en = "Astral Gate to the Maelstrom",
				es = "Portal astral a La Vorágine",
				de = "Astraltor zum Mahlstrom",
				fr = "Porte astrale menant au Maelström",
				it = "Varco Astrale del Maelstrom",
				pt = "Portal Ancestral para Voragem",
				ru = "Астральные врата к Водовороту",
			},
		},
	
		[244818] = {
			readable = "Tur'xoran's Summoning Stone",
			model = 1042820,
			text = {
				en = "Tur'xoran's Summoning Stone",
				es = "Roca de invocación de Tur'xoran",
				de = "Tur'xorans Beschwörungsstein",
				fr = "Pierre d’invocation de Tur’xoran",
				it = "Pietra d'Evocazione di Tur'xoran",
				pt = "Pedra de Evocação Tur'xoran",
				ru = "Камень призыва Тур'ксорана",
				ko = "투르조란의 소환석",
				cn = "图索兰的召唤石",
			},
		},
	
		[244824] = {
			readable = "Leather Shipment",
			model = 950767,
			text = {
				en = "Leather Shipment",
				es = "Envío de cuero",
				de = "Lederlieferung",
				fr = "Cargaison de cuir",
				it = "Carico di Cuoio",
				pt = "Carregamento de Couro",
				ru = "Груз кожи",
				ko = "가죽 제품",
				cn = "制皮货物",
			},
		},
	
		[244828] = {
			readable = "The Fjarnskaggl Fjormula",
			model = 929342,
			text = {
				en = "The Fjarnskaggl Fjormula",
				es = "La fjormula fjarnskaggl",
				de = "Die Fjarnskaggl-Fjormel",
				fr = "La formule du fjarnskaggl",
				it = "Formula di Fjarnskaggl",
				pt = "A Fjórmula de Fjarnskaggl",
				ru = "Фьормула фьярнскаггла",
				ko = "피아른스카글 비방",
				cn = "夏斯卡格草配方",
			},
		},
	
		[244829] = {
			readable = "The Tangled Beard",
			model = 936378,
			text = {
				en = "The Tangled Beard",
				es = "La barba enredada",
				de = "Der verknotete Bart",
				fr = "La Barbe hirsute",
				it = "Barba Aggrovigliata",
				pt = "A Barba Emaranhada",
				ru = "Спутанная борода",
				ko = "뒤엉킨 수염",
				cn = "纠缠的根须",
			},
		},
	
		[244830] = {
			readable = "Herblore of the Ancients",
			model = 1005457,
			text = {
				en = "Herblore of the Ancients",
				es = "Saber herbáceo de los ancestros",
				de = "Kräuterwissen der Uralten",
				fr = "Encyclopédie des plantes des Anciens",
				it = "Storia dell'Erbalismo degli Antichi",
				pt = "História das Ervas dos Anciãos",
				ru = "Древнее учение о травничестве",
				ko = "고대 약초론",
				cn = "古代草药录",
			},
		},
	
		[244836] = {
			readable = "The Fjarnskaggl Fjormula",
			model = 929342,
			text = {
				en = "The Fjarnskaggl Fjormula",
				es = "La fjormula fjarnskaggl",
				de = "Die Fjarnskaggl-Fjormel",
				fr = "La formule du fjarnskaggl",
				it = "Formula di Fjarnskaggl",
				pt = "A Fjórmula de Fjarnskaggl",
				ru = "Фьормула фьярнскаггла",
				ko = "피아른스카글 비방",
				cn = "夏斯卡格草配方",
			},
		},
	
		[244837] = {
			readable = "The Tangled Beard",
			model = 936378,
			text = {
				en = "The Tangled Beard",
				es = "La barba enredada",
				de = "Der verknotete Bart",
				fr = "La Barbe hirsute",
				it = "Barba Aggrovigliata",
				pt = "A Barba Emaranhada",
				ru = "Спутанная борода",
				ko = "뒤엉킨 수염",
				cn = "纠缠的根须",
			},
		},
	
		[244838] = {
			readable = "Herblore of the Ancients",
			model = 1005457,
			text = {
				en = "Herblore of the Ancients",
				es = "Saber herbáceo de los ancestros",
				de = "Kräuterwissen der Uralten",
				fr = "Encyclopédie des plantes des Anciens",
				it = "Storia dell'Erbalismo degli Antichi",
				pt = "História das Ervas dos Anciãos",
				ru = "Древнее учение о травничестве",
				ko = "고대 약초론",
				cn = "古代草药录",
			},
		},
	
		[244841] = {
			readable = "Eagle Egg",
			model = 661112,
			text = {
				en = "Eagle Egg",
				es = "Huevo de águila",
				de = "Adlerei",
				fr = "Œuf d’aigle",
				it = "Uova di Aquila",
				pt = "Ovo de Águia",
				ru = "Орлиное яйцо",
			},
		},
	
		[244844] = {
			readable = "Wind-Worn Cairn",
			model = 195405,
			text = {
				en = "Wind-Worn Cairn",
				es = "Hito desgastado por el viento",
				de = "Verwitterter Steinhaufen",
				fr = "Cairn usé par le vent",
				it = "Tumulo Consumato dal Vento",
				ru = "Обветренная груда камней",
				ko = "바람에 닳은 돌무덤",
			},
		},
	
		[244850] = {
			readable = "Pile of Herbs",
			model = 255235,
			text = {
				en = "Pile of Herbs",
				es = "Montón de hierbas",
				de = "Kräuterhaufen",
				fr = "Tas de plantes",
				it = "Mucchio di Erbe",
				pt = "Monte de Ervas",
				ru = "Куча травы",
				ko = "약초 더미",
				cn = "一堆草药",
			},
		},
	
		[244853] = {
			readable = "Tharillon's Stash",
			model = 942843,
			text = {
				en = "Tharillon's Stash",
				es = "Alijo de Tharillon",
				de = "Tharillons geheimer Vorrat",
				fr = "Planque de Tharillon",
				it = "Scorte di Tharillon",
				pt = "Esconderijo de Tharillon",
				ru = "Тайник Тариллона",
				ko = "타릴론의 보관함",
				cn = "塔里隆的储物箱",
			},
		},
	
		[244854] = {
			readable = "Unfinished Steamy Romance Novel",
			model = 948845,
			text = {
				en = "Unfinished Steamy Romance Novel",
				es = "Novela romántica tórrida sin terminar",
				de = "Unfertiger schlüpfriger Romantikschmöker",
				fr = "Roman d’amour torride inachevé",
				it = "Romanzo Rosa Incompiuto",
				pt = "Romance Apimentado Inacabado",
				ru = "Недописанный скабрезный любовный роман",
				ko = "쓰다 만 야한 연애 소설",
				cn = "催人泪下的言情小说（未完本）",
			},
		},
	
		[244867] = {
			readable = "Fish Barrel",
			model = 1097383,
			text = {
				en = "Fish Barrel",
				es = "Barril de pescado",
				de = "Fass mit Fischen",
				fr = "Tonneau de poissons",
				it = "Barile di Pesce",
				pt = "Barril de Peixes",
				ru = "Бочка с рыбой",
				ko = "물고기 통",
				cn = "鱼桶",
			},
		},
	
		[244872] = {
			readable = "Spear",
			model = 1140790,
			text = {
				en = "Spear",
				es = "Lanza",
				de = "Speer",
				fr = "Lance",
				it = "Lancia",
				pt = "Lança",
				ru = "Копье",
				ko = "창",
				cn = "矛",
			},
		},
	
		[244874] = {
			readable = "Portal to Suramar",
			model = 1406078,
			text = {
				en = "Portal to Suramar",
				es = "Portal a Suramar",
				de = "Portal nach Suramar",
				fr = "Portail vers Suramar",
				it = "Portale per Suramar",
				pt = "Portal para Suramar",
				ru = "Портал в Сурамар",
				ko = "수라마르로 통하는 차원문",
				cn = "通往苏拉玛的传送门",
			},
		},
	
		[244883] = {
			readable = "Unfinished Steamy Romance Novel",
			model = 948845,
			text = {
				en = "Unfinished Steamy Romance Novel",
				es = "Novela romántica tórrida sin terminar",
				de = "Unfertiger schlüpfriger Romantikschmöker",
				fr = "Roman d’amour torride inachevé",
				it = "Romanzo Rosa Incompiuto",
				pt = "Romance Apimentado Inacabado",
				ru = "Недописанный скабрезный любовный роман",
				ko = "쓰다 만 야한 연애 소설",
				cn = "催人泪下的言情小说（未完本）",
			},
		},
	
		[244887] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[244899] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[244901] = {
			readable = "Treasure Chest",
			model = 1402264,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[244902] = {
			readable = "Treasure Chest",
			model = 1402264,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[244903] = {
			readable = "Treasure Chest",
			model = 1402264,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[244904] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[244905] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[244909] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[244912] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[244913] = {
			readable = "Treasure Chest",
			model = 1402264,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[244916] = {
			readable = "Jailer Cage",
			model = 1125322,
			text = {
				en = "Jailer Cage",
				es = "Jaula del carcelero",
				de = "Wärterkäfig",
				fr = "Cage de geôlier",
				it = "Gabbia del Carceriere",
				pt = "Jaula do Carcereiro",
				ru = "Клетка тюремщика",
				ko = "간수 우리",
				cn = "狱卒的牢笼",
			},
		},
	
		[244917] = {
			readable = "Treasure Chest",
			model = 1402264,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[244921] = {
			readable = "Fertile Soil",
			model = 605596,
			text = {
				en = "Fertile Soil",
				es = "Tierra fértil",
				de = "Fruchtbare Erde",
				fr = "Terre fertile",
				it = "Suolo Fertile",
				pt = "Solo Fértil",
				ru = "Плодородная почва",
				ko = "비옥한 흙",
			},
		},
	
		[244923] = {
			readable = "Lever",
			model = 897186,
			text = {
				en = "Lever",
				es = "Palanca",
				de = "Hebel",
				fr = "Levier",
				it = "Leva",
				pt = "Alavanca",
				ru = "Рычаг",
				ko = "지렛대",
				cn = "拉杆",
			},
		},
	
		[244928] = {
			readable = "Glimmering Treasure Chest",
			model = 1402270,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[244935] = {
			readable = "Dry Timber",
			model = 1103597,
			text = {
				en = "Dry Timber",
				es = "Madera seca",
				de = "Trockenes Holz",
				fr = "Bois sec",
				it = "Tronco Secco",
				pt = "Lenha Seca",
				ru = "Сухая древесина",
				ko = "마른 나무",
				cn = "干木材",
			},
		},
	
		[244940] = {
			readable = "Prison Runestone",
			model = 1139506,
			text = {
				en = "Prison Runestone",
				es = "Piedra rúnica de prisión",
				de = "Gefängnisrunenstein",
				fr = "Prison de pierres runiques",
				it = "Prigione di Pietra Runica",
				pt = "Pedra Rúnica da Prisão",
				ru = "Тюремный рунический камень",
				ko = "감옥 룬석",
			},
		},
	
		[244950] = {
			readable = "Dusty Rug",
			model = 243124,
			text = {
				en = "Dusty Rug",
				es = "Alfombra polvorienta",
				de = "Staubiger Teppich",
				fr = "Carpette poussiéreuse",
				it = "Tappeto Polveroso",
				pt = "Tapete Empoeirado",
				ru = "Пыльный коврик",
				ko = "더러운 양탄자",
				cn = "布满灰尘的毯子",
			},
		},
	
		[244965] = {
			readable = "Sheddle's Chest",
			icon = 1001980,
			model = 979397,
			text = {
				en = "Sheddle's Chest",
				es = "Cofre de Sheddle",
				de = "Gussis Truhe",
				fr = "Coffre de Sheddle",
				it = "Cassa di Sheddle",
				pt = "Baú de Sheddle",
				ru = "Сундук Шеддла",
				ko = "쉐들의 상자",
				cn = "西德尔的箱子",
			},
		},
	
		[244981] = {
			readable = "Inkbinder's Spike",
			model = 979112,
			text = {
				en = "Inkbinder's Spike",
				es = "Punta del vinculador de tinta",
				de = "Tintenbinderspieß",
				fr = "Plume de lieur-d’encre",
				it = "Punta del Tatuatore",
				pt = "Espeto do Passatinta",
				ru = "Шип краскоплета",
				ko = "잉크결속사의 촉",
				cn = "缚墨者的尖刺",
			},
		},
	
		[244983] = {
			readable = "Dirty Pocketwatch",
			model = 243239,
			text = {
				en = "Dirty Pocketwatch",
				es = "Reloj de bolsillo sucio",
				de = "Schmutzige Taschenuhr",
				fr = "Montre de gousset sale",
				it = "Orologio da Tasca Sporco",
				pt = "Relógio de Bolso Sujo",
				ru = "Грязные карманные часы",
				ko = "더러운 회중시계",
				cn = "肮脏的怀表",
			},
		},
	
		[244985] = {
			readable = "Tome of Fel Secrets",
			model = 1323497,
			text = {
				en = "Tome of Fel Secrets",
				es = "Escrito de secretos viles",
				de = "Foliant der Dämonengeheimnisse",
				fr = "Tome des secrets gangrenés",
				it = "Tomo dei Vilsegreti",
				pt = "Tomo dos Segredos Vis",
				ru = "Фолиант тайн Скверны",
				ko = "지옥 비밀의 일지",
				cn = "邪魔之秘魔典",
			},
		},
	
		[244986] = {
			readable = "Legion Portal",
			model = 986958,
			text = {
				en = "Legion Portal",
				es = "Portal de la Legión",
				de = "Legionsportal",
				fr = "Portail de la Légion",
				it = "Portale della Legione",
				pt = "Portal da Legião",
				ru = "Портал Легиона",
				ko = "군단 차원문",
				cn = "军团传送门",
			},
		},
	
		[244994] = {
			readable = "Weapon Rack",
			model = 1240667,
			text = {
				en = "Weapon Rack",
				es = "Expositor de armas",
				de = "Waffenständer",
				fr = "Râtelier d’armes",
				it = "Rastrelliera delle Armi",
				pt = "Cavalete de Armas",
				ru = "Оружейная стойка",
				ko = "무기 선반",
				cn = "武器架",
			},
		},
	
		[244995] = {
			readable = "Weapon Rack",
			model = 1240702,
			text = {
				en = "Weapon Rack",
				es = "Expositor de armas",
				de = "Waffenständer",
				fr = "Râtelier d’armes",
				it = "Rastrelliera delle Armi",
				pt = "Cavalete de Armas",
				ru = "Оружейная стойка",
				ko = "무기 선반",
				cn = "武器架",
			},
		},
})
do ObjectDB[objectID] = objectData; end
