local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	
		[241031] = {
			readable = "Dread-Captain's Saber",
			model = 199446,
			text = {
				en = "Dread-Captain's Saber",
				es = "Sable de la capitana aterradora",
				de = "Säbel des Schreckenskapitäns",
				fr = "Sabre de capitaine de l’effroi",
				it = "Sciabola del Capitano del Terrore",
				pt = "Sabre da Capitã Medonha",
				ru = "Сабля жуткого капитана",
				ko = "공포선장의 사브르",
				cn = "恐怖船长的军刀",
			},
		},
	
		[241032] = {
			readable = "Plague-Tipped Arrow",
			model = 242884,
			text = {
				en = "Plague-Tipped Arrow",
				es = "Flecha con punta apestada",
				de = "Verseuchter Pfeil",
				fr = "Pointe de flèche trempée de peste",
				it = "Freccia con Punta di Piaga",
				pt = "Flecha com Peste na Ponta",
				ru = "Стрела с чумным наконечником",
				ko = "역병 촉 화살",
				cn = "染疫箭支",
			},
		},
	
		[241036] = {
			readable = "Alliance Banner",
			model = 1021317,
			text = {
				en = "Alliance Banner",
				es = "Estandarte de la Alianza",
				de = "Allianzbanner",
				fr = "Bannière de l’Alliance",
				it = "Stendardo dell'Alleanza",
				pt = "Estandarte da Aliança",
				ru = "Знамя Альянса",
				ko = "얼라이언스 깃발",
			},
		},
	
		[241117] = {
			readable = "The Black Candle",
			model = 199809,
			text = {
				en = "The Black Candle",
				es = "Vela negra",
				de = "Die schwarze Kerze",
				fr = "Bougie noire",
				it = "Candela Nera",
				pt = "A Vela Negra",
				ru = "Черная свеча",
				ko = "검은 초",
			},
		},
	
		[241118] = {
			readable = "The Tome of Protection",
			model = 965217,
			text = {
				en = "The Tome of Protection",
				es = "Escrito sobre Protección",
				de = "Der Foliant des Schutzes",
				fr = "Tome de protection",
				it = "Tomo della Protezione",
				pt = "O Tomo da Proteção",
				ru = "Фолиант защиты",
				ko = "보호의 고서",
			},
		},
	
		[241119] = {
			readable = "The Shadowblade",
			model = 942577,
			text = {
				en = "The Shadowblade",
				es = "Hoja de las Sombras",
				de = "Die Schattenklinge",
				fr = "Lame-de-l’ombre",
				it = "Lamaombra",
				pt = "A Umbralâmina",
				ru = "Теневой клинок",
				ko = "그림자칼날",
			},
		},
	
		[241121] = {
			readable = "Portal to Moonwillow Peak",
			model = 166523,
			text = {
				en = "Portal to Moonwillow Peak",
				es = "Portal a Pico Sauce Lunar",
				de = "Portal zum Mondweidengipfel",
				fr = "Portail vers le pic du Saule-Lunaire",
				it = "Portale per il Picco dei Salici Lunari",
				pt = "Portal para Pico do Salgueiro-da-lua",
				ru = "Портал на пик Лунной Ивы.",
				ko = "달빛버들 봉우리로 통하는 차원문",
			},
		},
	
		[241124] = {
			readable = "Drained Infernal Core",
			model = 166412,
			text = {
				en = "Drained Infernal Core",
				es = "Núcleo infernal drenado",
				de = "Entladener Kern einer Höllenbestie",
				fr = "Noyau infernal drainé",
				it = "Nucleo Infernale Prosciugato",
				pt = "Núcleo Infernal Drenado",
				ru = "Истощенное ядро инфернала",
				ko = "고갈된 지옥핵",
				cn = "枯竭的恶魔之核",
			},
		},
	
		[241127] = {
			readable = "Unguarded Thistleleaf Treasure",
			model = 196989,
			text = {
				en = "Unguarded Thistleleaf Treasure",
				es = "Tesoro Hojacardo sin vigilancia",
				de = "Unbewachter Distelblattschatz",
				fr = "Trésor de chardofeuille sans surveillance",
				it = "Tesoro degli Sferzafoglie Incustodito",
				pt = "Tesouro Folhacardo Desprotegido",
				ru = "Неохраняемые сокровища племени Листа Чертополоха",
				ko = "주인 없는 엉겅퀴잎 보물",
				cn = "无人看守的蓟叶宝藏",
			},
		},
	
		[241128] = {
			readable = "Unguarded Thistleleaf Treasure",
			icon = 1542847,
			model = 196989,
			text = {
				en = "Unguarded Thistleleaf Treasure",
				es = "Tesoro Hojacardo sin vigilancia",
				de = "Unbewachter Distelblattschatz",
				fr = "Trésor de chardofeuille sans surveillance",
				it = "Tesoro degli Sferzafoglie Incustodito",
				pt = "Tesouro Folhacardo Desprotegido",
				ru = "Неохраняемые сокровища племени Листа Чертополоха",
				ko = "주인 없는 엉겅퀴잎 보물",
				cn = "无人看守的蓟叶宝藏",
			},
		},
	
		[241130] = {
			readable = "Blackrock Grapple",
			model = 1014233,
			text = {
				en = "Blackrock Grapple",
				es = "Gancho Roca Negra",
				de = "Schwarzfelsgreifer",
				fr = "Grappin rochenoire",
				it = "Cannone dei Roccianera",
				pt = "Gancho da Rocha Negra",
				ru = "Крюк Черной горы",
				ko = "검은바위 갈고리",
			},
		},
	
		[241146] = {
			readable = "Treasure Chest",
			model = 1402264,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[241147] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[241148] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[241149] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[241150] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[241151] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[241152] = {
			readable = "Treasure Chest",
			model = 1402264,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[241153] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[241154] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[241155] = {
			readable = "Treasure Chest",
			model = 1402264,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[241180] = {
			readable = "Treasure Chest",
			model = 1402264,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[241206] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[241207] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[241208] = {
			readable = "Treasure Chest",
			model = 1402264,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[241212] = {
			readable = "Treasure Chest",
			model = 1402264,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[241213] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[241216] = {
			readable = "Treasure Chest",
			model = 1402264,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[241267] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[241272] = {
			readable = "Treasure Chest",
			model = 1402264,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[241275] = {
			readable = "Skyfire Medical Supplies",
			model = 199636,
			text = {
				en = "Skyfire Medical Supplies",
				es = "Suministros médicos de El Abrasacielos",
				de = "Medizinische Vorräte der Himmelsfeuer",
				fr = "Fournitures médicales du Brûleciel",
				it = "Forniture Mediche della Fuoco Celeste",
				pt = "Suprimentos Médicos do Celesfogo",
				ru = "Медикаменты с \"Небесного огня\"",
				ko = "하늘불꽃호 의약품",
				cn = "天火号医疗补给品",
			},
		},
	
		[241278] = {
			readable = "Skyfire Rations",
			model = 950782,
			text = {
				en = "Skyfire Rations",
				es = "Raciones de El Abrasacielos",
				de = "Verpflegung der Himmelsfeuer",
				fr = "Rations du Brûleciel",
				it = "Razioni della Fuoco Celeste",
				pt = "Rações do Celesfogo",
				ru = "Паек с \"Небесного огня\"",
				ko = "하늘불꽃호 군용 식량",
				cn = "天火号口粮",
			},
		},
	
		[241279] = {
			readable = "Intact Thorignir Egg",
			model = 351241,
			text = {
				en = "Intact Thorignir Egg",
				es = "Huevo de Thorignir intacto",
				de = "Intaktes Ei der Thorignir",
				fr = "Œuf de thorignir intact",
				it = "Uovo di Thorignir Intatto",
				pt = "Ovo de Thorignir Intacto",
				ru = "Неповрежденное яйцо торигнира",
				ko = "온전한 토리그니르 알",
				cn = "完整的托林尼尔龙蛋",
			},
		},
	
		[241280] = {
			readable = "Treasure Chest",
			model = 1402264,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[241283] = {
			readable = "Rage Potion",
			model = 775412,
			text = {
				en = "Rage Potion",
				es = "Poción de ira",
				de = "Wuttrank",
				fr = "Potion de rage",
				it = "Pozione della Rabbia",
				pt = "Poção de Raiva",
				ru = "Зелье ярости",
				ko = "분노의 물약",
				cn = "怒气药水",
			},
		},
	
		[241293] = {
			readable = "Rope Ladder",
			model = 198421,
			text = {
				en = "Rope Ladder",
				es = "Escala de cuerda",
				de = "Strickleiter",
				fr = "Échelle de corde",
				it = "Scala di Corda",
				pt = "Escada de Corda",
				ru = "Веревочная лестница",
				ko = "밧줄 사다리",
			},
		},
	
		[241307] = {
			readable = "Rope Ladder",
			model = 198421,
			text = {
				en = "Rope Ladder",
				es = "Escala de cuerda",
				de = "Strickleiter",
				fr = "Échelle de corde",
				it = "Scala di Corda",
				pt = "Escada de Corda",
				ru = "Веревочная лестница",
				ko = "밧줄 사다리",
				cn = "绳梯",
			},
		},
	
		[241308] = {
			readable = "Rope Ladder",
			model = 198421,
			text = {
				en = "Rope Ladder",
				es = "Escala de cuerda",
				de = "Strickleiter",
				fr = "Échelle de corde",
				it = "Scala di Corda",
				pt = "Escada de Corda",
				ru = "Веревочная лестница",
				ko = "밧줄 사다리",
				cn = "绳梯",
			},
		},
	
		[241309] = {
			readable = "Rope Ladder",
			model = 198421,
			text = {
				en = "Rope Ladder",
				es = "Escala de cuerda",
				de = "Strickleiter",
				fr = "Échelle de corde",
				it = "Scala di Corda",
				pt = "Escada de Corda",
				ru = "Веревочная лестница",
				ko = "밧줄 사다리",
				cn = "绳梯",
			},
		},
	
		[241310] = {
			readable = "Rope Ladder",
			model = 198421,
			text = {
				en = "Rope Ladder",
				es = "Escala de cuerda",
				de = "Strickleiter",
				fr = "Échelle de corde",
				it = "Scala di Corda",
				pt = "Escada de Corda",
				ru = "Веревочная лестница",
				ko = "밧줄 사다리",
			},
		},
	
		[241419] = {
			readable = "Alard's Whetstone",
			model = 929433,
			text = {
				en = "Alard's Whetstone",
				es = "Piedra de afilar de Alard",
				de = "Alards Wetzstein",
				fr = "Pierre à aiguiser d’Alard",
				it = "Cote di Alard",
				pt = "Amolador de Alard",
				ru = "Точильный камень Аларда",
				ko = "알라드의 숫돌",
				cn = "奥拉尔德的磨石",
			},
		},
	
		[241428] = {
			readable = "Detonator",
			model = 979393,
			text = {
				en = "Detonator",
				es = "Detonador",
				de = "Zünder",
				fr = "Détonateur",
				it = "Detonatore",
				pt = "Detonador",
				ru = "Детонатор",
			},
		},
	
		[241429] = {
			readable = "Dragon-Blood Brew",
			model = 311947,
			text = {
				en = "Dragon-Blood Brew",
				es = "Brebaje de sangre de dragón",
				de = "Drachenblutgebräu",
				fr = "Breuvage sang-de-dragon",
				it = "Bevanda di Sangue di Drago",
				pt = "Cerveja de Sangue de Dragão",
				ru = "Напиток из драконьей крови",
				ko = "용혈주",
				cn = "龙血佳酿",
			},
		},
	
		[241431] = {
			readable = "Bottle of Netherblade Oil",
			model = 243415,
			text = {
				en = "Bottle of Netherblade Oil",
				es = "Botella de aceite de filo abisal",
				de = "Flasche voll Netherklingenöl",
				fr = "Bouteille d’huile de Lame-Néant",
				it = "Bottiglia di Olio di Lamafatua",
				pt = "Garrafa de Óleo de Aço Etéreo",
				ru = "Бутыль с маслом Клинка Пустоты",
				ko = "황천칼날 기름 병",
				cn = "一瓶灵刃之油",
			},
		},
	
		[241433] = {
			readable = "Forgotten Sack",
			model = 523211,
			text = {
				en = "Forgotten Sack",
				es = "Saco olvidado",
				de = "Vergessener Sack",
				fr = "Sac oublié",
				it = "Sacca Dimenticata",
				pt = "Saco Esquecido",
				ru = "Забытый мешок",
				ko = "잊혀진 자루",
				cn = "被遗忘的袋子",
			},
		},
	
		[241434] = {
			readable = "Lodged Hunting Spear",
			icon = 135128,
			model = 943686,
			text = {
				en = "Lodged Hunting Spear",
				es = "Lanza de caza atascada",
				de = "Verkeilter Jagdspeer",
				fr = "Lance de chasse plantée",
				it = "Lancia da Caccia Impiantata",
				pt = "Lança de Caça Alojada",
				ru = "Застрявшее охотничье копье",
				ko = "꽂힌 사냥용 창",
				cn = "倒伏的狩猎长矛",
			},
		},
	
		[241435] = {
			readable = "Greenhoof's Anvil",
			model = 893036,
			text = {
				en = "Greenhoof's Anvil",
				es = "Yunque de Pezuñaverde",
				de = "Grünhufs Amboss",
				fr = "Enclume de Sabot-Vert",
				it = "Incudine degli Zoccolo Verde",
				pt = "Bigorna de Casco Verde",
				ru = "Наковальня Зеленого Копыта",
				ko = "그린후프의 모루",
				cn = "绿蹄的铁砧",
			},
		},
	
		[241436] = {
			readable = "Greenhoof's Forge",
			model = 893049,
			text = {
				en = "Greenhoof's Forge",
				es = "Forja de Pezuñaverde",
				de = "Grünhufs Schmiede",
				fr = "Forge de Sabot-Vert",
				it = "Forgia degli Zoccolo Verde",
				pt = "Forja de Casco Verde",
				ru = "Горн Зеленого Копыта",
				ko = "그린후프의 가열로",
				cn = "绿蹄的熔炉",
			},
		},
	
		[241443] = {
			readable = "G-X3 Telemetry Beacon",
			model = 337602,
			text = {
				en = "G-X3 Telemetry Beacon",
				es = "Baliza telemétrica G-X3",
				de = "Telemetrieantenne G-X3",
				fr = "Balise télémétrique G-X3",
				it = "Trasmettitore Telemetrico di G-X3",
				pt = "Sinalizador Telemétrico G-X3",
				ru = "Телеметрический маяк Г-Х3",
				ko = "G-X3 원격 신호기",
				cn = "G-X3遥测信标",
			},
		},
	
		[241444] = {
			readable = "Pentangulate-o-tron 2000",
			model = 411841,
			text = {
				en = "Pentangulate-o-tron 2000",
				es = "Pentagramatrón 2000",
				de = "Pentangulier-o-Tron 2000",
				fr = "Rectangulat-o-tron 2000",
				it = "Pentangolatron 2000",
				pt = "Pentagulotron 2000",
				ru = "\"Пентагулотрон-2000\"",
				ko = "마력통제기 2000",
			},
		},
	
		[241448] = {
			readable = "Shortfuse Special",
			model = 254423,
			text = {
				en = "Shortfuse Special",
				es = "Especialidad de Plomocorto",
				de = "Schnellzünd Spezial",
				fr = "Spécialité de Courtemèche",
				it = "Speciale di Micciacorta",
				pt = "Especial Paviocurto",
				ru = "Спецвзрыватор",
			},
		},
	
		[241449] = {
			readable = "Blackfang Island Cache",
			model = 875603,
			text = {
				en = "Blackfang Island Cache",
				es = "Alijo de la Isla Colmillo Negro",
				de = "Schatz der Schwarzfanginsel",
				fr = "Cache de l’île des Crocs-Noirs",
				it = "Cassa dell'Isola degli Artiglionero",
				pt = "Tesouro da Ilha Presanegra",
				ru = "Островные припасы племени Черного Клыка",
				cn = "黑齿岛宝箱",
			},
		},
	
		[241450] = {
			readable = "Crystallized Fel Spike",
			icon = 1135365,
			model = 202751,
			text = {
				en = "Crystallized Fel Spike",
				es = "Púa vil cristalizada",
				de = "Kristallisierter Teufelsstachel",
				fr = "Pointe gangrenée cristallisée",
				it = "Vilspina Cristallizzata",
				pt = "Espeto Vil Cristalizado",
				ru = "Кристаллический шип Скверны",
				cn = "晶化邪能尖刺",
			},
		},
	
		[241453] = {
			readable = "Alard's Forge",
			model = 1302572,
			text = {
				en = "Alard's Forge",
				es = "Forja de Alard",
				de = "Alards Schmiede",
				fr = "Forge d’Alard",
				it = "Forgia di Alard",
				pt = "Forja de Alard",
				ru = "Кузнечный горн Аларда",
				ko = "알라드의 가열로",
				cn = "奥拉尔德的熔炉",
			},
		},
	
		[241460] = {
			readable = "Climbing Treads",
			model = 1005465,
			text = {
				en = "Climbing Treads",
				es = "Botines de escalada",
				de = "Kletterschuhe",
				fr = "Bottines d’escalade",
				it = "Stivaletti da Arrampicata",
				pt = "Botinas de Escalada",
				ru = "Горные ботфорты",
				ko = "등산 신발",
				cn = "登山鞋",
			},
		},
	
		[241462] = {
			readable = "Oiled Cloak",
			model = 198148,
			text = {
				en = "Oiled Cloak",
				es = "Capa aceitada",
				de = "Gefetteter Umhang",
				fr = "Cape huilée",
				it = "Mantello Cerato",
				pt = "Manto Oleado",
				ru = "Промасленный плащ",
				ko = "기름 묻은 망토",
			},
		},
	
		[241470] = {
			readable = "General Lena Stormpike",
			model = 199987,
			text = {
				en = "General Lena Stormpike",
				es = "General Lena Pico Tormenta",
				de = "Kriegsherrin Lena Sturmlanze",
				fr = "Général Léna Foudrepique",
				it = "Generale Lena Piccatonante",
				pt = "General Lena Lançatroz",
				ru = "Генерал Лена Грозовая Вершина",
				ko = "장군 레나 스톰파이크",
				cn = "莱娜·雷矛将军",
			},
		},
	
		[241472] = {
			readable = "Stolen Treasure Cache",
			model = 878867,
			text = {
				en = "Stolen Treasure Cache",
				es = "Alijo de tesoro robado",
				de = "Gestohlene Schatztruhe",
				fr = "Cache de trésors volés",
				it = "Cassa di Tesori Rubati",
				pt = "Baú do Tesouro Roubado",
				ru = "Украденный сундук с сокровищами",
				ko = "도둑맞은 보물 보관함",
				cn = "失窃的宝箱",
			},
		},
	
		[241504] = {
			readable = "Polished Crystal",
			model = 942849,
			text = {
				en = "Polished Crystal",
				es = "Cristal pulido",
				de = "Polierter Kristall",
				fr = "Cristal poli",
				it = "Cristallo Lucidato",
				pt = "Cristal Polido",
				ru = "Отполированный кристалл",
				ko = "연마한 수정",
				cn = "抛光水晶",
			},
		},
	
		[241507] = {
			readable = "Ironbound Crate",
			model = 878880,
			text = {
				en = "Ironbound Crate",
				es = "Cajón reforzado con hierro",
				de = "Eisenbeschlagene Kiste",
				fr = "Caisse bardée de fer",
				it = "Cassa Rinforzata",
				pt = "Caixote Férreo",
				ru = "Окованный железом ящик",
				ko = "무쇠결속 상자",
				cn = "铁箍箱子",
			},
		},
	
		[241511] = {
			readable = "Alard's Anvil",
			model = 929334,
			text = {
				en = "Alard's Anvil",
				es = "Yunque de Alard",
				de = "Alards Amboss",
				fr = "Enclume d’Alard",
				it = "Incudine di Alard",
				pt = "Bigorna de Alard",
				ru = "Наковальня Аларда",
				ko = "알라드의 모루",
				cn = "奥拉尔德的铁砧",
			},
		},
	
		[241512] = {
			readable = "Alard's Quenching Trough",
			model = 929428,
			text = {
				en = "Alard's Quenching Trough",
				es = "Recipiente para templar de Alard",
				de = "Alards Löschwanne",
				fr = "Baquet de trempage d’Alard",
				it = "Vasca da Tempratura di Alard",
				pt = "Cuba de Resfriamento de Alard",
				ru = "Лохань Аларда",
				ko = "알라드의 담금질 통",
				cn = "奥拉尔德的淬火水槽",
			},
		},
	
		[241513] = {
			readable = "Alard's Workbench",
			model = 929452,
			text = {
				en = "Alard's Workbench",
				es = "Banco de trabajo de Alard",
				de = "Alards Werkbank",
				fr = "Établi d’Alard",
				it = "Tavolo da Lavoro di Alard",
				pt = "Bancada de Alard",
				ru = "Верстак Аларда",
				ko = "알라드의 작업대",
				cn = "奥拉尔德的工作台",
			},
		},
	
		[241517] = {
			readable = "Mysterious Fruit",
			model = 940110,
			text = {
				en = "Mysterious Fruit",
				es = "Fruta misteriosa",
				de = "Mysteriöse Frucht",
				fr = "Fruit mystérieux",
				it = "Frutto Misterioso",
				pt = "Fruta Misteriosa",
				ru = "Таинственный фрукт",
				ko = "수수께끼의 열매",
				cn = "神秘水果",
			},
		},
	
		[241518] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[241521] = {
			readable = "Snake Charmer's Flute",
			icon = 133942,
			model = 522113,
			text = {
				en = "Snake Charmer's Flute",
				es = "Flauta de encantador de serpientes",
				de = "Schlangenbeschwörerflöte",
				fr = "Flûte du charmeur de serpents",
				it = "Flauto dell'Incantatore di Serpenti",
				pt = "Flauta do Encantador de Serpentes",
				ru = "Флейта заклинателя змей",
				cn = "驯蛇人的笛子",
			},
		},
	
		[241522] = {
			readable = "The Perfect Blossom",
			icon = 876365,
			model = 1119130,
			text = {
				en = "The Perfect Blossom",
				es = "La flor perfecta",
				de = "Die perfekte Blüte",
				fr = "Bourgeon parfait",
				it = "Bocciolo Perfetto",
				pt = "A Flor Perfeita",
				ru = "Идеальный цветок",
				ko = "완벽한 꽃송이",
				cn = "完美之花",
			},
		},
	
		[241523] = {
			readable = "Felbloom",
			model = 1102782,
			text = {
				en = "Felbloom",
				es = "Brotevil",
				de = "Teufelsblume",
				fr = "Gangrenelle",
				it = "Vilbocciolo",
				pt = "Brotovil",
				ru = "Сквернолист",
				ko = "지옥 독초",
				cn = "邪能花",
			},
		},
	
		[241524] = {
			readable = "Pale Removal Equipment",
			model = 953811,
			text = {
				en = "Pale Removal Equipment",
				es = "Equipo de eliminación de pálidos",
				de = "Fahlenjägerausrüstung",
				fr = "Équipement d’extermination des blafards",
				it = "Equipaggiamento per Rimozione Pallidi",
				pt = "Equipamento de Remoção de Pálidos",
				ru = "Снаряжение для устранения бледнокожих",
				ko = "창백한 오크 제거 장치",
				cn = "反白鬼设备",
			},
		},
	
		[241528] = {
			readable = "Horn of the Helmouth",
			model = 1062215,
			text = {
				en = "Horn of the Helmouth",
				es = "Cuerno Boca Infernal",
				de = "Horn des Höllenschlunds",
				fr = "Cor de l’embouchure de Hel",
				it = "Corno degli Helmunn",
				pt = "Trompa da Boca do Inferno",
				ru = "Рог Адской Пасти",
				ko = "지옥어귀의 뿔피리",
				cn = "冥口号角",
			},
		},
	
		[241529] = {
			readable = "Looted Treasures",
			model = 953811,
			text = {
				en = "Looted Treasures",
				es = "Tesoros despojados",
				de = "Geplünderte Schätze",
				fr = "Trésors pillés",
				it = "Tesori Depredati",
				pt = "Tesouros Saqueados",
				ru = "Награбленные сокровища",
				ko = "전리품",
				cn = "抢来的战利品",
			},
		},
	
		[241533] = {
			readable = "Forgotten Champion's Blade",
			icon = 135326,
			model = 148079,
			text = {
				en = "Forgotten Champion's Blade",
				es = "Filo de Campeón olvidado",
				de = "Vergessene Klinge eines Champions",
				fr = "Lame du champion oublié",
				it = "Lama del Campione Dimenticato",
				pt = "Lâmina do Campeão Esquecido",
				ru = "Клинок позабытого воина",
				cn = "被遗忘的勇士之剑",
			},
		},
	
		[241535] = {
			readable = "Bleakthorn",
			model = 1110228,
			text = {
				en = "Bleakthorn",
				es = "Zarzasombría",
				de = "Kahldorn",
				fr = "Pâlépine",
				it = "Spinatetra",
				pt = "Espinhoalvo",
				ru = "Жесткошип",
				ko = "황폐의 가시덩굴",
				cn = "荒芜荆棘",
			},
		},
	
		[241536] = {
			readable = "Moongrass",
			model = 1112473,
			text = {
				en = "Moongrass",
				es = "Hierbaluna",
				de = "Mondgras",
				fr = "Herbe de lune",
				it = "Erbaluna",
				pt = "Grama da Lua",
				ru = "Лунная трава",
				ko = "달잔디",
				cn = "月光苔",
			},
		},
	
		[241537] = {
			readable = "Chaos Clover",
			model = 1112472,
			text = {
				en = "Chaos Clover",
				es = "Trébol del caos",
				de = "Chaosklee",
				fr = "Trèfle du chaos",
				it = "Trifoglio del Caos",
				pt = "Trevo do Caos",
				ru = "Клевер Хаоса",
				ko = "혼돈의 토끼풀",
				cn = "混乱苜蓿",
			},
		},
	
		[241538] = {
			readable = "Doom Shroom",
			model = 1102807,
			text = {
				en = "Doom Shroom",
				es = "Seta de calamidad",
				de = "Verdammnispilz",
				fr = "Champignon funeste",
				it = "Fungo della Rovina",
				pt = "Cogumelo da Ruína",
				ru = "Роковой гриб",
				ko = "파멸의 버섯",
				cn = "毁灭蘑菇",
			},
		},
	
		[241557] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[241558] = {
			readable = "Treasure Chest",
			model = 1402264,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[241560] = {
			readable = "Bleeding Hollow Warchest",
			model = 953811,
			text = {
				en = "Bleeding Hollow Warchest",
				es = "Cofre de guerra de los Foso Sangrante",
				de = "Kriegsvorrat des Blutenden Auges",
				fr = "Coffre de guerre de l’Orbite-Sanglante",
				it = "Cassa da Guerra dei Guerci Insanguinati",
				pt = "Baú de Guerra dos Olhos Sangrentos",
				ru = "Сундук с трофеями клана Кровавой Глазницы",
				ko = "피눈물 전쟁상자",
				cn = "血环战场储物箱",
			},
		},
	
		[241561] = {
			readable = "Jewel of the Fallen Star",
			model = 980090,
			text = {
				en = "Jewel of the Fallen Star",
				es = "Joya de la estrella caída",
				de = "Juwel des gefallenen Sterns",
				fr = "Joyau de l’étoile tombée",
				it = "Gioiello della Stella Caduta",
				pt = "Joia da Estrela Caída",
				ru = "Самоцвет упавшей звезды",
				ko = "떨어진 별의 보석",
				cn = "坠星珠宝",
			},
		},
	
		[241562] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[241563] = {
			readable = "Censer of Torment",
			icon = 237275,
			model = 1064382,
			text = {
				en = "Censer of Torment",
				es = "Incensario de tormento",
				de = "Weihrauchschwenker der Pein",
				fr = "Encensoir de tourment",
				it = "Incensiere del Tormento",
				pt = "Turíbulo da Tormenta",
				ru = "Курительница мучений",
				ko = "고문의 향로",
				cn = "苦难熏炉",
			},
		},
	
		[241564] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[241565] = {
			readable = "Looted Bleeding Hollow Treasure",
			icon = 134051,
			model = 523213,
			text = {
				en = "Looted Bleeding Hollow Treasure",
				es = "Tesoro de los Foso Sangrante despojado",
				de = "Beuteschatz des Blutenden Auges",
				fr = "Trésor de l’Orbite-Sanglante pillé",
				it = "Tesoro dei Guerci Insanguinati Depredato",
				pt = "Tesouro dos Olhos Sangrentos Saqueado",
				ru = "Награбленные сокровища клана Кровавой Глазницы",
				ko = "약탈한 피눈물 보물",
				cn = "抢来的血环宝藏",
			},
		},
	
		[241566] = {
			readable = "Rune Etched Femur",
			icon = 133718,
			model = 969729,
			text = {
				en = "Rune Etched Femur",
				es = "Fémur con runas grabadas",
				de = "Runenverzierter Oberschenkelknochen",
				fr = "Fémur gravé de runes",
				it = "Femore Runico",
				pt = "Fêmur com Runa Gravada",
				ru = "Испещренная рунами бедренная кость",
				ko = "룬새김 다리뼈",
				cn = "铭文腿骨",
			},
		},
	
		[241567] = {
			readable = "He Who Shall Not Be Named",
			model = 603502,
			text = {
				en = "He Who Shall Not Be Named",
				es = "El que no debe ser nombrado",
				de = "Er, dessen Name nicht genannt werden darf",
				fr = "Celui dont on ne doit pas prononcer le nom",
				it = "Innominato",
				pt = "O Que Não É Nomeado",
				ru = "Тот, Кого Нельзя Называть",
				ko = "이름을 불러서는 안 되는 그 사람",
				cn = "天谴之人",
			},
		},
	
		[241568] = {
			readable = "Offering Shrine",
			model = 200925,
			text = {
				en = "Offering Shrine",
				es = "Cuenco para ofrendas",
				de = "Opferschrein",
				fr = "Sanctuaire à offrandes",
				it = "Santuario dell'Offerta",
				pt = "Altar de Oferenda",
				ru = "Чаша для даров",
				ko = "공물 제단",
				cn = "祭坛",
			},
		},
	
		[241586] = {
			readable = "Engraved Headstone",
			model = 364632,
			text = {
				en = "Engraved Headstone",
				es = "Lápida grabada",
				de = "Gravierter Grabstein",
				fr = "Pierre de tombe gravée",
				it = "Lapide Incisa",
				pt = "Lápide Entalhada",
				ru = "Резное надгробие",
				ko = "조각이 새겨진 묘비",
				cn = "雕花墓碑",
			},
		},
	
		[241587] = {
			readable = "Engraved Headstone",
			model = 364632,
			text = {
				en = "Engraved Headstone",
				es = "Lápida grabada",
				de = "Gravierter Grabstein",
				fr = "Pierre de tombe gravée",
				it = "Lapide Incisa",
				pt = "Lápide Entalhada",
				ru = "Резное надгробие",
				ko = "조각이 새겨진 묘비",
				cn = "雕花墓碑",
			},
		},
	
		[241598] = {
			readable = "Fel Crystal",
			model = 338495,
			text = {
				en = "Fel Crystal",
				es = "Cristal vil",
				de = "Teufelskristall",
				fr = "Gangrecristal",
				it = "Vilcristallo",
				pt = "Cristal Vil",
				ru = "Кристалл Скверны",
			},
		},
	
		[241599] = {
			readable = "Strange Fruit",
			icon = 645344,
			model = 196317,
			text = {
				en = "Strange Fruit",
				es = "Fruta extraña",
				de = "Merkwürdige Frucht",
				fr = "Fruit étrange",
				it = "Frutto Strano",
				pt = "Fruta Estranha",
				ru = "Странный фрукт",
				ko = "이상한 열매",
				cn = "奇怪的水果",
			},
		},
	
		[241600] = {
			readable = "Discarded Helm",
			icon = 1036487,
			model = 645601,
			text = {
				en = "Discarded Helm",
				es = "Yelmo desechado",
				de = "Weggeworfener Helm",
				fr = "Heaume abandonné",
				it = "Elmo Scartato",
				pt = "Elmo Descartado",
				ru = "Выброшенный шлем",
				cn = "被遗弃的头盔",
			},
		},
	
		[241601] = {
			readable = "Scout's Belongings",
			icon = 133633,
			model = 936417,
			text = {
				en = "Scout's Belongings",
				es = "Pertenencias de explorador",
				de = "Hab und Gut eines Spähers",
				fr = "Effets personnels de l’éclaireur",
				it = "Beni dell'Esploratore",
				pt = "Pertences do Batedor",
				ru = "Вещи разведчика",
				cn = "斥候的财物",
			},
		},
	
		[241602] = {
			readable = "Forgotten Iron Horde Supplies",
			model = 878880,
			text = {
				en = "Forgotten Iron Horde Supplies",
				es = "Suministros de la Horda de Hierro olvidados",
				de = "Vergessene Vorräte der Eisernen Horde",
				fr = "Fournitures de la Horde de Fer oubliées",
				it = "Forniture dell'Orda di Ferro Dimenticate",
				pt = "Suprimentos Esquecidos da Horda de Ferro",
				ru = "Забытые припасы Железной Орды",
				ko = "잊혀진 강철 호드 보급품",
				cn = "被遗忘的钢铁部落补给品",
			},
		},
	
		[241605] = {
			readable = "Crystalized Essence of the Elements",
			icon = 132783,
			model = 190803,
			text = {
				en = "Crystalized Essence of the Elements",
				es = "Esencia de los elementos cristalizada",
				de = "Kristallisierte Essenz der Elemente",
				fr = "Essence des éléments cristallisée",
				it = "Essenza degli Elementi Cristallizzata",
				pt = "Essência dos Elementos Cristalizada",
				ru = "Кристаллическая сущность стихий",
				ko = "결정화된 원소의 정수",
				cn = "晶化元素精华",
			},
		},
	
		[241606] = {
			readable = "Loose Soil",
			model = 189528,
			text = {
				en = "Loose Soil",
				es = "Suelo blando",
				de = "Lockere Erde",
				fr = "Terre meuble",
				it = "Terreno Smosso",
				pt = "Terra Solta",
				ru = "Рыхлая земля",
				ko = "대충 덮인 흙더미",
			},
		},
	
		[241607] = {
			readable = "Broken Reliquary",
			model = 984644,
			text = {
				en = "Broken Reliquary",
				es = "Relicario roto",
				de = "Zertrümmertes Reliquiar",
				fr = "Reliquaire brisé",
				it = "Reliquiario Rotto",
				pt = "Relicário Quebrado",
				ru = "Разбитый реликварий",
				ko = "부서진 성물함",
				cn = "破损的圣物匣",
			},
		},
	
		[241610] = {
			readable = "Dread Barracks",
			text = {
				en = "Dread Barracks",
				es = "Cuartel aterrador",
				de = "Schreckenskaserne",
				fr = "Caserne de l’effroi",
				it = "Caserma del Terrore",
				pt = "Quartel Medonho",
				ru = "Казармы ужаса",
				ko = "공포의 병영",
				cn = "恐惧兵营",
			},
		},
	
		[241611] = {
			readable = "Ritual of the Bleeding Hollow",
			model = 1109027,
			text = {
				en = "Ritual of the Bleeding Hollow",
				es = "Ritual de los Foso Sangrante",
				de = "Ritual des Blutenden Auges",
				fr = "Rituel de l’Orbite-Sanglante",
				it = "Rituale dei Guerci Insanguinati",
				pt = "Ritual dos Olhos Sangrentos",
				ru = "Ритуал Кровавой Глазницы",
				ko = "피눈물 의식의 진",
				cn = "血环仪式",
			},
		},
	
		[241612] = {
			readable = "Battlefield Rations",
			model = 198232,
			text = {
				en = "Battlefield Rations",
				es = "Raciones del campo de batalla",
				de = "Schlachtfeldrationen",
				fr = "Rations de champ de bataille",
				it = "Razioni da Campo",
				pt = "Rações do Campo de Batalha",
				ru = "Боевой паек",
				ko = "전투식량",
				cn = "战地口粮",
			},
		},
	
		[241626] = {
			readable = "Sand-Encrusted Egg",
			model = 796657,
			text = {
				en = "Sand-Encrusted Egg",
				es = "Huevo con arena incrustada",
				de = "Sandverkrustetes Ei",
				fr = "Œuf incrusté de sable",
				it = "Uovo Incrostato di Sabbia",
				pt = "Ovo Incrustado de Areia",
				ru = "Покрытое песком яйцо",
				ko = "모래에 덮인 알",
				cn = "沾满沙砾的蛋",
			},
		},
	
		[241633] = {
			readable = "Small Metal Scrap",
			model = 1021464,
			text = {
				en = "Small Metal Scrap",
				es = "Trozo de metal pequeño",
				de = "Kleines Altmetallteil",
				fr = "Petit morceau de ferraille",
				it = "Pezzi Piccoli di Metallo",
				pt = "Sucata de Metal Pequena",
				ru = "Мелкие металлические обломки",
				ko = "소형 금속 조각",
				cn = "小型金属碎片",
			},
		},
	
		[241634] = {
			readable = "Medium Metal Scrap",
			model = 1021468,
			text = {
				en = "Medium Metal Scrap",
				es = "Trozo de metal mediano",
				de = "Mittleres Altmetallteil",
				fr = "Morceau de ferraille moyen",
				it = "Pezzi Medi di Metallo",
				pt = "Sucata de Metal Média",
				ru = "Средние металлические обломки",
				ko = "중형 금속 조각",
				cn = "中型金属碎片",
			},
		},
	
		[241635] = {
			readable = "Large Metal Scrap",
			model = 1021470,
			text = {
				en = "Large Metal Scrap",
				es = "Trozo de metal grande",
				de = "Großes Altmetallteil",
				fr = "Grand morceau de ferraille",
				it = "Pezzi Grossi di Metallo",
				pt = "Sucata de Metal Grande",
				ru = "Крупные металлические обломки",
				ko = "대형 금속 조각",
				cn = "大型金属碎片",
			},
		},
	
		[241638] = {
			readable = "Stareye's Orders",
			model = 1124093,
			text = {
				en = "Stareye's Orders",
				es = "Órdenes de Ojo de Estrella",
				de = "Sternauges Befehle",
				fr = "Ordres d’Astrevue",
				it = "Ordini di Mirastelle",
				pt = "Ordens de Olhestela",
				ru = "Приказы Звездного Глаза",
				ko = "스타아이의 명령서",
			},
		},
	
		[241639] = {
			readable = "Warden's Glaive",
			model = 1118880,
			text = {
				en = "Warden's Glaive",
				es = "Guja de la celadora",
				de = "Wächterinnengleve",
				fr = "Glaive de Gardienne",
				it = "Lama della Custode",
				pt = "Glaive da Guardiã",
				ru = "Глефа Стража",
				ko = "감시관의 글레이브",
				cn = "守望者的战刃",
			},
		},
	
		[241641] = {
			readable = "Foxflower",
			model = 1303238,
			text = {
				en = "Foxflower",
				es = "Flor de raposa",
				de = "Fuchsblume",
				fr = "Vulpille",
				it = "Fiorvolpe",
				pt = "Flor-de-raposa",
				ru = "Лисоцвет",
				ko = "여우꽃",
				cn = "狐尾花",
			},
		},
	
		[241642] = {
			readable = "Tanaan Blood Orange",
			model = 960878,
			text = {
				en = "Tanaan Blood Orange",
				es = "Naranja sanguina de Tanaan",
				de = "Tanaanblutorange",
				fr = "Orange sanguine de Tanaan",
				it = "Arancia Rossa di Tanaan",
				pt = "Laranja Sangrenta de Tanaan",
				ru = "Танаанский кровавый апельсин",
				ko = "타나안의 핏빛 오렌지",
				cn = "塔纳安血橙",
			},
		},
	
		[241656] = {
			readable = "Overgrown Relic",
			icon = 1542847,
			model = 985187,
			text = {
				en = "Overgrown Relic",
				es = "Reliquia desmesurada",
				de = "Überwuchertes Relikt",
				fr = "Relique recouverte par la végétation",
				it = "Reliquia Ipertrofica",
				pt = "Relíquia Gigante",
				ru = "Заросшая реликвия",
				ko = "식물에 뒤덮인 유물",
				cn = "巨型遗物",
			},
		},
	
		[241657] = {
			readable = "Jeweled Arakkoa Effigy",
			model = 194083,
			text = {
				en = "Jeweled Arakkoa Effigy",
				es = "Efigie arakkoa con joyas",
				de = "Juwelenbesetzte Arakkoaeffigie",
				fr = "Effigie arakkoa ornée de joyaux",
				it = "Effige degli Arakkoa Ingioiellata",
				pt = "Efígie Arakkoa Decorada",
				ru = "Украшенная самоцветами фигурка араккоа",
				ko = "보석이 박힌 아라코아 입상",
				cn = "鸦人嵌宝雕像",
			},
		},
	
		[241659] = {
			readable = "Grappling Hook and Rope",
			model = 1019643,
			text = {
				en = "Grappling Hook and Rope",
				es = "Gancho y cuerda",
				de = "Greifhaken mit Seil",
				fr = "Grappin et corde",
				it = "Rampino",
				pt = "Gancho e Corda de Escalada",
				ru = "Веревка с крюком",
				ko = "갈고리와 밧줄",
				cn = "绳钩",
			},
		},
	
		[241664] = {
			readable = "Borrowed Enchanted Spyglass",
			icon = 463555,
			model = 1052603,
			text = {
				en = "Borrowed Enchanted Spyglass",
				es = "Catalejo encantado \"prestado\"",
				de = "\"Geborgtes\" verzaubertes Fernglas",
				fr = "Longue-vue enchantée « empruntée »",
				it = "Cannocchiale Incantato \"Prestato\"",
				pt = "Luneta Encantada \"Emprestada\"",
				ru = "\"Одолженная\" заколдованная подзорная труба",
				ko = "\"빌린\" 마법 망원경",
				cn = "“借来”的魔法望远镜",
			},
		},
	
		[241665] = {
			readable = "Treasure Chest",
			model = 1402264,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[241666] = {
			readable = "Mysterious Corrupted Obelisk",
			model = 1002900,
			text = {
				en = "Mysterious Corrupted Obelisk",
				es = "Obelisco corrupto misterioso",
				de = "Mysteriöser verderbter Obelisk",
				fr = "Mystérieux obélisque corrompu",
				it = "Obelisco Misterioso Corrotto",
				pt = "Obeslico Corrompido Misterioso",
				ru = "Таинственный оскверненный Обелиск",
				ko = "수수께끼의 타락한 방첨탑",
				cn = "神秘的腐化方尖碑",
			},
		},
	
		[241667] = {
			readable = "Felsmith Forge",
			model = 1101704,
			text = {
				en = "Felsmith Forge",
				es = "Forja de herrero vil",
				de = "Esse des Teufelsschmieds",
				fr = "Gangreforge",
				it = "Forgia del Vilfabbro",
				pt = "Forja de Ferreiro Vil",
				ru = "Горн кузнеца Скверны",
				ko = "지옥대장간 가열로",
				cn = "邪能工匠熔炉",
			},
		},
	
		[241668] = {
			readable = "Felsmith Anvil",
			model = 1101690,
			text = {
				en = "Felsmith Anvil",
				es = "Yunque de herrero vil",
				de = "Amboss des Teufelsschmieds",
				fr = "Enclume de gangreforge",
				it = "Incudine della Vilforgiatura",
				pt = "Bigorna de Ferreiro Vil",
				ru = "Наковальня кузнеца Скверны",
				ko = "지옥대장간 모루",
				cn = "邪能工匠铁砧",
			},
		},
	
		[241669] = {
			readable = "Siege Equipment Blueprints",
			model = 929405,
			text = {
				en = "Siege Equipment Blueprints",
				es = "Planos de equipo de asedio",
				de = "Baupläne für Belagerungswaffen",
				fr = "Plan d’équipement de siège",
				it = "Progetti per Mezzi d'Assedio",
				pt = "Diagramas de Equipamento de Cerco",
				ru = "Чертежи осадной техники",
				ko = "공성 장비 도면",
				cn = "攻城装备图纸",
			},
		},
	
		[241670] = {
			readable = "Felsmith Workbench",
			model = 1101717,
			text = {
				en = "Felsmith Workbench",
				es = "Banco de trabajo de herrero vil",
				de = "Werkbank des Teufelsschmieds",
				fr = "Établi de gangreforge",
				it = "Tavolo da Lavoro del Vilfabbro",
				pt = "Bancada de Ferreiro Vil",
				ru = "Верстак кузнеца Скверны",
				ko = "지옥대장간 작업대",
				cn = "邪能工匠工作台",
			},
		},
	
		[241671] = {
			readable = "Forgotten Shard of the Cipher",
			icon = 132873,
			model = 193423,
			text = {
				en = "Forgotten Shard of the Cipher",
				es = "Fragmento de la clave olvidado",
				de = "Vergessener Splitter der Litanei",
				fr = "Fragment de formule oublié",
				it = "Frammento di Cifrario Dimenticato",
				pt = "Fragmento da Cifra Esquecido",
				ru = "Утерянная часть Кода",
				ko = "잊혀진 암호 조각",
				cn = "被遗忘的秘文碎片",
			},
		},
	
		[241673] = {
			readable = "Looted Bleeding Hollow Treasure",
			model = 196990,
			text = {
				en = "Looted Bleeding Hollow Treasure",
				es = "Tesoro de los Foso Sangrante despojado",
				de = "Beuteschatz des Blutenden Auges",
				fr = "Trésor de l’Orbite-Sanglante pillé",
				it = "Tesoro dei Guerci Insanguinati Depredato",
				pt = "Tesouro dos Olhos Sangrentos Saqueado",
				ru = "Награбленные сокровища клана Кровавой Глазницы",
				ko = "약탈한 피눈물 보물",
				cn = "抢来的血环宝藏",
			},
		},
	
		[241674] = {
			readable = "Skull of the Mad Chief",
			icon = 1325308,
			model = 1097379,
			text = {
				en = "Skull of the Mad Chief",
				es = "Cráneo del jefe loco",
				de = "Schädel des irren Häuptlings",
				fr = "Crâne du chef fou",
				it = "Teschio del Capo Pazzo",
				pt = "Crânio do Chefe Louco",
				ru = "Череп сумасшедшего вождя",
				ko = "미친 족장의 해골",
				cn = "疯狂酋长之颅",
			},
		},
	
		[241680] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[241682] = {
			readable = "Dry Harpy Nest",
			model = 1115926,
			text = {
				en = "Dry Harpy Nest",
				es = "Nido de arpías seco",
				de = "Trockenes Harpyiennest",
				fr = "Nid de Harpies sec",
				it = "Nido di Arpie Secco",
				pt = "Ninho de Harpias Seco",
				ru = "Сухое гнездо гарпий",
				ko = "마른 하피 둥지",
				cn = "干燥的鹰身人巢穴",
			},
		},
	
		[241690] = {
			readable = "Felsmith Quenching Trough",
			model = 1101712,
			text = {
				en = "Felsmith Quenching Trough",
				es = "Recipiente para templar de herrero vil",
				de = "Löschwanne des Teufelsschmieds",
				fr = "Baquet de trempage de gangreforge",
				it = "Vasca da Tempratura del Vilfabbro",
				pt = "Cuba de Resfriamento de Ferreiro Vil",
				ru = "Лохань кузнеца Скверны",
				ko = "지옥대장간 담금질 통",
				cn = "邪能工匠淬火水槽",
			},
		},
	
		[241692] = {
			readable = "Axe of the Weeping Wolf",
			icon = 531359,
			model = 592070,
			text = {
				en = "Axe of the Weeping Wolf",
				es = "Hacha del lobo sollozante",
				de = "Axt des wimmernden Wolfs",
				fr = "Hache du loup hurlant",
				it = "Ascia del Lupo Piangente",
				pt = "Machado do Lobo Lastimoso",
				ru = "Топор плачущего волка",
				ko = "우는 늑대의 도끼",
				cn = "哀狼之斧",
			},
		},
	
		[241699] = {
			readable = "Spoils of War",
			model = 196989,
			text = {
				en = "Spoils of War",
				es = "Botín de guerra",
				de = "Kriegsbeute",
				fr = "Butin de guerre",
				it = "Spoglie di Guerra",
				pt = "Espólios de Guerra",
				ru = "Трофеи войны",
				ko = "전쟁의 전리품",
				cn = "战争横财",
			},
		},
	
		[241712] = {
			readable = "Ironbeard's Treasure",
			model = 446673,
			text = {
				en = "Ironbeard's Treasure",
				es = "Tesoro de Barbaférrea",
				de = "Eisenbarts Schatz",
				fr = "Trésor de Barbe-de-Fer",
				it = "Tesoro di Barbaferro",
				pt = "Tesouro do Barba de Ferro",
				ru = "Сокровище Железноборода",
				ko = "아이언비어드의 보물",
				cn = "铁须的宝藏",
			},
		},
	
		[241713] = {
			readable = "The Eye of Grannok",
			icon = 134127,
			model = 243033,
			text = {
				en = "The Eye of Grannok",
				es = "El ojo de Grannok",
				de = "Das Auge von Grannok",
				fr = "Œil de Grannok",
				it = "Occhio di Grannok",
				pt = "O Olho de Grannok",
				ru = "Око Граннока",
				ko = "그란노크의 눈",
				cn = "格兰诺克之眼",
			},
		},
	
		[241714] = {
			readable = "Stashed Iron Sea Booty",
			model = 196989,
			text = {
				en = "Stashed Iron Sea Booty",
				es = "Botín del Mar de Hierro oculto",
				de = "Eingelagerte Seebeute der Eisernen Horde",
				fr = "Butin planqué de la mer de Fer",
				it = "Bottino Segreto del Mare di Ferro",
				pt = "Pilhagem Escondida do Mar de Ferro",
				ru = "Спрятанные трофеи Железного моря",
				ko = "강철해 노획물 보관함",
				cn = "隐藏的铁海宝藏",
			},
		},
	
		[241715] = {
			readable = "Stashed Iron Sea Booty",
			model = 446677,
			text = {
				en = "Stashed Iron Sea Booty",
				es = "Botín del Mar de Hierro oculto",
				de = "Eingelagerte Seebeute der Eisernen Horde",
				fr = "Butin planqué de la mer de Fer",
				it = "Bottino Segreto del Mare di Ferro",
				pt = "Pilhagem Escondida do Mar de Ferro",
				ru = "Спрятанные трофеи Железного моря",
				ko = "강철해 노획물 보관함",
				cn = "隐藏的铁海宝藏",
			},
		},
	
		[241716] = {
			readable = "Stashed Iron Sea Booty",
			model = 196987,
			text = {
				en = "Stashed Iron Sea Booty",
				es = "Botín del Mar de Hierro oculto",
				de = "Eingelagerte Seebeute der Eisernen Horde",
				fr = "Butin planqué de la mer de Fer",
				it = "Bottino Segreto del Mare di Ferro",
				pt = "Pilhagem Escondida do Mar de Ferro",
				ru = "Спрятанные трофеи Железного моря",
				ko = "강철해 노획물 보관함",
				cn = "隐藏的铁海宝藏",
			},
		},
	
		[241717] = {
			readable = "Glimmering Treasure Chest",
			model = 1402270,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Cofre del tesoro reluciente",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[241718] = {
			readable = "Ironbeard's Treasure",
			model = 446673,
			text = {
				en = "Ironbeard's Treasure",
				es = "Tesoro de Barbaférrea",
				de = "Eisenbarts Schatz",
				fr = "Trésor de Barbe-de-Fer",
				it = "Tesoro di Barbaferro",
				pt = "Tesouro do Barba de Ferro",
				ru = "Сокровище Железноборода",
				ko = "아이언비어드의 보물",
			},
		},
	
		[241721] = {
			readable = "Glimmering Treasure Chest",
			model = 1402270,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[241725] = {
			readable = "Tanaan Planning Map",
			model = 979431,
			text = {
				en = "Tanaan Planning Map",
				es = "Mapa de planes de Tanaan",
				de = "Taktische Karte von Tanaan",
				fr = "Carte de préparation de guerre de Tanaan",
				it = "Mappa dei Piani di Tanaan",
				pt = "Mapa de Planejamento de Tanaan",
				ru = "Танаанская карта боевых действий",
				ko = "타나안 전투 계획 지도",
				cn = "塔纳安计划图",
			},
		},
	
		[241726] = {
			readable = "Leystone Deposit",
			icon = 1394960,
			model = 1244489,
			text = {
				en = "Leystone Deposit",
				es = "Depósito de piedra Ley",
				de = "Leysteinvorkommen",
				fr = "Gisement de tellurium",
				it = "Deposito di Fagliaroccia",
				pt = "Depósito de Espinho do Meridiano",
				ru = "Залежи силового камня",
				ko = "지맥석 광맥",
				cn = "魔石矿脉",
			},
		},
	
		[241728] = {
			readable = "Elixir of Reckless Power",
			model = 340089,
			text = {
				en = "Elixir of Reckless Power",
				es = "Elixir de poder temerario",
				de = "Elixier der tollkühnen Macht",
				fr = "Élixir de puissance téméraire",
				it = "Elisir del Potere Incauto",
				pt = "Elixir do Poder Irresponsável",
				ru = "Эликсир безрассудной силы",
				ko = "무모한 힘의 비약",
				cn = "鲁莽能量药剂",
			},
		},
	
		[241741] = {
			readable = "Weapon Rack",
			model = 1240666,
			text = {
				en = "Weapon Rack",
				es = "Expositor de armas",
				de = "Waffenständer",
				fr = "Râtelier d’armes",
				it = "Rastrelliera delle Armi",
				pt = "Cavalete de Armas",
				ru = "Оружейная стойка",
				ko = "무기 선반",
				cn = "武器架",
			},
		},
	
		[241742] = {
			readable = "Book of Zyzzix",
			icon = 460694,
			model = 965217,
			text = {
				en = "Book of Zyzzix",
				es = "Libro de Zyzzix",
				de = "Buch von Zyzzix",
				fr = "Livre de Zyzzix",
				it = "Libro di Zyzzix",
				pt = "Livro de Zyzzix",
				ru = "Книга Зиззикса",
				ko = "지직스의 책",
				cn = "茨兹克的书",
			},
		},
	
		[241743] = {
			readable = "Felslate Deposit",
			icon = 1394961,
			model = 1244487,
			text = {
				en = "Felslate Deposit",
				es = "Depósito de pizarra vil",
				de = "Teufelsschiefervorkommen",
				fr = "Gisement de gangreschiste",
				it = "Deposito di Vilardesia",
				pt = "Depósito de Vilardósia",
				ru = "Залежи сланца Скверны",
				ko = "지옥판암 광맥",
				cn = "邪能页岩矿脉",
			},
		},
	
		[241745] = {
			readable = "Fel-Drenched Satchel",
			icon = 348526,
			model = 878856,
			text = {
				en = "Fel-Drenched Satchel",
				es = "Cartera envilecida",
				de = "Teufelsdurchtränkter Beutel",
				fr = "Sacoche imprégnée d’énergie gangrenée",
				it = "Sacchetto Vilinzuppato",
				pt = "Bolsa Envolta em Vilania",
				ru = "Пропитанная Скверной сумка",
				ko = "지옥 마력에 물든 가방",
				cn = "被邪能侵蚀的背包",
			},
		},
	
		[241751] = {
			readable = "Legion Gateway Activator",
			model = 1138112,
			text = {
				en = "Legion Gateway Activator",
				es = "Activador del portal de la Legión",
				de = "Toraktivator der Legion",
				fr = "Activateur de porte de la Légion",
				it = "Attivatore del Varco della Legione",
				pt = "Ativador do Portal da Legião",
				ru = "Активатор врат Легиона",
				ko = "군단 관문 가동 장치",
				cn = "军团传送门激活器",
			},
		},
	
		[241756] = {
			readable = "Legion Gateway Activator",
			model = 1138112,
			text = {
				en = "Legion Gateway Activator",
				es = "Activador del portal de la Legión",
				de = "Toraktivator der Legion",
				fr = "Activateur de porte de la Légion",
				it = "Attivatore del Varco della Legione",
				pt = "Ativador do Portal da Legião",
				ru = "Активатор врат Легиона",
				ko = "군단 관문 가동 장치",
				cn = "军团传送门激活器",
			},
		},
	
		[241757] = {
			readable = "Legion Gateway Activator",
			model = 1138112,
			text = {
				en = "Legion Gateway Activator",
				es = "Activador del portal de la Legión",
				de = "Toraktivator der Legion",
				fr = "Activateur de porte de la Légion",
				it = "Attivatore del Varco della Legione",
				pt = "Ativador do Portal da Legião",
				ru = "Активатор врат Легиона",
				ko = "군단 관문 가동 장치",
				cn = "军团传送门激活器",
			},
		},
	
		[241760] = {
			readable = "Sacrificial Blade",
			icon = 801017,
			model = 326812,
			text = {
				en = "Sacrificial Blade",
				es = "Hoja de sacrificio",
				de = "Opferklinge",
				fr = "Lame sacrificielle",
				it = "Lama Sacrificale",
				pt = "Lâmina de Sacrifício",
				ru = "Жертвенный клинок",
				ko = "제물용 칼",
				cn = "献祭之刃",
			},
		},
	
		[241764] = {
			readable = "Stashed Bleeding Hollow Loot",
			model = 953811,
			text = {
				en = "Stashed Bleeding Hollow Loot",
				es = "Botín de los Foso Sangrante oculto",
				de = "Eingelagerte Beute des Blutenden Auges",
				fr = "Butin planqué de l’Orbite-Sanglante",
				it = "Bottino Segreto dei Guerci Insanguinati",
				pt = "Saque Escondido dos Olhos Sangrentos",
				ru = "Припрятанная добыча клана Кровавой Глазницы",
				ko = "피눈물 전리품 보관함",
				cn = "隐藏的血环战利品",
			},
		},
	
		[241767] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[241770] = {
			readable = "Sea-kissed Scroll",
			model = 985170,
			text = {
				en = "Sea-kissed Scroll",
				es = "Pergamino besado por el mar",
				de = "Meerwasserdurchtränkte Schriftrolle",
				fr = "Parchemin bercé par les flots",
				it = "Pergamena Baciata dal Mare",
				pt = "Pergaminho Beijado pelo Mar",
				ru = "Омытый морем свиток",
				ko = "바다의 입맞춤을 받은 두루마리",
				cn = "防潮卷轴",
			},
		},
	
		[241772] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[241773] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[241775] = {
			readable = "Brazier of Awakening",
			model = 978597,
			text = {
				en = "Brazier of Awakening",
				es = "Blandón de Despertar",
				de = "Kohlenbecken des Erwachens",
				fr = "Brasero de l’Éveil",
				it = "Braciere del Risveglio",
				pt = "Braseiro do Despertar",
				ru = "Жаровня пробуждения",
				ko = "각성의 화로",
				cn = "觉醒火盆",
			},
		},
	
		[241778] = {
			readable = "Colborn's Cage",
			model = 195417,
			text = {
				en = "Colborn's Cage",
				es = "Jaula de Colborn",
				de = "Colborns Käfig",
				fr = "Cage de Colborn",
				it = "Gabbia di Colborn",
				pt = "Jaula de Colnato",
				ru = "Клетка Кольборна",
				ko = "콜본의 우리",
				cn = "科本的牢笼",
			},
		},
	
		[241835] = {
			readable = "Bleeding Hollow Mushroom Stash",
			icon = 252179,
			model = 902292,
			text = {
				en = "Bleeding Hollow Mushroom Stash",
				es = "Alijo de champiñones de los Foso Sangrante",
				de = "Pilzvorrat des Blutenden Auges",
				fr = "Planque de champignons de l’Orbite-Sanglante",
				it = "Scorta di Funghi dei Guerci Insanguinati",
				pt = "Esconderijo de Cogumelos dos Olhos Sangrentos",
				ru = "Запасы грибов клана Кровавой Глазницы",
				ko = "피눈물 버섯 통",
				cn = "血环蘑菇桶",
			},
		},
	
		[241838] = {
			readable = "Disturbed Earth",
			model = 605598,
			text = {
				en = "Disturbed Earth",
				es = "Tierra perturbada",
				de = "Aufgewühlte Erde",
				fr = "Sol dérangé",
				it = "Terra Disturbata",
				pt = "Terra Perturbada",
				ru = "Потревоженная земля",
				ko = "파헤쳐진 흙",
				cn = "翻动过的土地",
			},
		},
	
		[241840] = {
			readable = "Rune-Carved Tablet",
			model = 194086,
			text = {
				en = "Rune-Carved Tablet",
				es = "Tablilla grabada con runas",
				de = "Runengemeißelte Tafel",
				fr = "Tablette gravée de runes",
				it = "Tavoletta con Rune Incise",
				pt = "Tabuleta Entalhada de Runas",
				ru = "Украшенная рунами скрижаль",
				ko = "룬이 새겨진 석판",
				cn = "刻满符文的石板",
			},
		},
	
		[241841] = {
			readable = "Looted Mystical Staff",
			icon = 134344,
			model = 238839,
			text = {
				en = "Looted Mystical Staff",
				es = "Bastón místico despojado",
				de = "Geplünderter mystischer Stab",
				fr = "Bâton mystique pillé",
				it = "Bastone Mistico Depredato",
				pt = "Cajado Místico Saqueado",
				ru = "Трофейный таинственный посох",
				ko = "약탈한 수수께끼의 지팡이",
				cn = "抢来的神秘法杖",
			},
		},
	
		[241847] = {
			readable = "The Commander's Shield",
			icon = 134955,
			model = 929409,
			text = {
				en = "The Commander's Shield",
				es = "Escudo del Comandante",
				de = "Der Schild des Kommandanten",
				fr = "Bouclier du commandant",
				it = "Scudo del Comandante",
				pt = "O Escudo do Comandante",
				ru = "Командирский щит",
				ko = "사령관의 방패",
				cn = "指挥官的盾牌",
			},
		},
	
		[241848] = {
			readable = "Dazzling Rod",
			icon = 134923,
			model = 244252,
			text = {
				en = "Dazzling Rod",
				es = "Vara deslumbrante",
				de = "Schillernde Rute",
				fr = "Bâtonnet éblouissant",
				it = "Verga Abbagliante",
				pt = "Bastão Ofuscante",
				ru = "Палочка-ослеплялочка",
				ko = "번쩍이는 막대",
				cn = "炫目之杖",
			},
		},
	
		[241849] = {
			readable = "Ritual Stone",
			model = 1139506,
			text = {
				en = "Ritual Stone",
				es = "Piedra ritual",
				de = "Ritualstein",
				fr = "Pierre rituelle",
				it = "Pietra Rituale",
				pt = "Pedra Ritualística",
				ru = "Ритуальный камень",
				ko = "의식용 돌",
				cn = "仪式石",
			},
		},
	
		[241853] = {
			readable = "Exhumer's Journal",
			model = 968424,
			text = {
				en = "Exhumer's Journal",
				es = "Diario del exhumador",
				de = "Exhumierertagebuch",
				fr = "Journal de l’exhumeur",
				it = "Diario di un Esumatore",
				pt = "Diário da Exumadora",
				ru = "Дневник эксгуматора",
				ko = "발굴자의 일지",
				cn = "掘墓者的日记",
			},
		},
	
		[241864] = {
			readable = "Offering Bowl",
			model = 850842,
			text = {
				en = "Offering Bowl",
				es = "Cuenco para ofrendas",
				de = "Opferschale",
				fr = "Bol à offrandes",
				it = "Scodella delle Offerte",
				pt = "Bacia de Oferenda",
				ru = "Жертвенная чаша",
				ko = "제기",
				cn = "供品之碗",
			},
		},
	
		[241866] = {
			readable = "Soulthorn",
			model = 1237525,
			text = {
				en = "Soulthorn",
				es = "Espina de alma",
				de = "Seelenkappe",
				fr = "Chapesprit",
				it = "Cappello d'Anima",
				pt = "Espinho das Almas",
				ru = "Душевик",
				ko = "영혼고깔",
				cn = "幽魂棘",
			},
		},
	
		[241868] = {
			readable = "Offering Bowl",
			model = 850842,
			text = {
				en = "Offering Bowl",
				es = "Cuenco para ofrendas",
				de = "Opferschale",
				fr = "Bol à offrandes",
				it = "Scodella delle Offerte",
				pt = "Bacia de Oferenda",
				ru = "Жертвенная чаша",
				ko = "제기",
				cn = "供品之碗",
			},
		},
	
		[241869] = {
			readable = "Offering Bowl",
			model = 850842,
			text = {
				en = "Offering Bowl",
				es = "Cuenco para ofrendas",
				de = "Opferschale",
				fr = "Bol à offrandes",
				it = "Scodella delle Offerte",
				pt = "Bacia de Oferenda",
				ru = "Жертвенная чаша",
				ko = "제기",
				cn = "供品之碗",
			},
		},
	
		[241870] = {
			readable = "Ashildir's Bones",
			model = 955870,
			text = {
				en = "Ashildir's Bones",
				es = "Huesos de Ashildir",
				de = "Ashildirs Knochen",
				fr = "Ossements d’Ashildir",
				it = "Ossa di Ashildir",
				pt = "Ossos de Ashildir",
				ru = "Кости Ашильдир",
				ko = "아쉴디르의 뼈",
				cn = "艾希迪尔之骨",
			},
		},
	
		[241871] = {
			readable = "Ashildir's Bones",
			model = 955864,
			text = {
				en = "Ashildir's Bones",
				es = "Huesos de Ashildir",
				de = "Ashildirs Knochen",
				fr = "Ossements d’Ashildir",
				it = "Ossa di Ashildir",
				pt = "Ossos de Ashildir",
				ru = "Кости Ашильдир",
				ko = "아쉴디르의 뼈",
				cn = "艾希迪尔之骨",
			},
		},
	
		[241872] = {
			readable = "Ashildir's Bones",
			model = 955866,
			text = {
				en = "Ashildir's Bones",
				es = "Huesos de Ashildir",
				de = "Ashildirs Knochen",
				fr = "Ossements d’Ashildir",
				it = "Ossa di Ashildir",
				pt = "Ossos de Ashildir",
				ru = "Кости Ашильдир",
				ko = "아쉴디르의 뼈",
				cn = "艾希迪尔之骨",
			},
		},
	
		[241873] = {
			readable = "Ashildir's Bones",
			model = 955858,
			text = {
				en = "Ashildir's Bones",
				es = "Huesos de Ashildir",
				de = "Ashildirs Knochen",
				fr = "Ossements d’Ashildir",
				it = "Ossa di Ashildir",
				pt = "Ossos de Ashildir",
				ru = "Кости Ашильдир",
				ko = "아쉴디르의 뼈",
				cn = "艾希迪尔之骨",
			},
		},
	
		[241874] = {
			readable = "Ashildir's Bones",
			model = 797854,
			text = {
				en = "Ashildir's Bones",
				es = "Huesos de Ashildir",
				de = "Ashildirs Knochen",
				fr = "Ossements d’Ashildir",
				it = "Ossa di Ashildir",
				pt = "Ossos de Ashildir",
				ru = "Кости Ашильдир",
				ko = "아쉴디르의 뼈",
				cn = "艾希迪尔之骨",
			},
		},
	
		[241877] = {
			readable = "Offering Bowl",
			model = 850842,
			text = {
				en = "Offering Bowl",
				es = "Cuenco para ofrendas",
				de = "Opferschale",
				fr = "Bol à offrandes",
				it = "Scodella delle Offerte",
				pt = "Bacia de Oferenda",
				ru = "Жертвенная чаша",
				ko = "제기",
				cn = "供品之碗",
			},
		},
	
		[241901] = {
			readable = "Cleave Thunderhill's Cage",
			model = 195415,
			text = {
				en = "Cleave Thunderhill's Cage",
				es = "Jaula de Cleave Lomatrueno",
				de = "Spalt Donnerhügels Käfig",
				fr = "Cage de Fendard Tonne-Colline",
				pt = "Jaula de Cutila Montrovão",
				ru = "Клетка Клива Громохолма",
				ko = "클리브 썬더힐의 우리",
				cn = "克里夫·雷山的牢笼",
			},
		},
	
		[241902] = {
			readable = "Gentle Rosh's Cage",
			model = 195415,
			text = {
				en = "Gentle Rosh's Cage",
				es = "Jaula de Rosh el Gentil",
				de = "Käfig vom sanftmütigen Rosh",
				fr = "Cage de Rosh l’affable",
				it = "Gabbia di Rosh il Gentile",
				pt = "Jaula de Rosh Gentil",
				ru = "Клетка Добряка Роша",
				ko = "온화한 로쉬의 우리",
				cn = "文雅的洛什的牢笼",
			},
		},
	
		[241905] = {
			readable = "Grace the Green's Cage",
			model = 195415,
			text = {
				en = "Grace the Green's Cage",
				es = "Jaula de Graciela la Glauca",
				de = "Käfig von Grazia der Grünen",
				fr = "Cage de Grâce la Verte",
				it = "Grazia della Gabbia Verde",
				pt = "Jaula de Graça, a Verde",
				ru = "Клетка Грейс Зеленой",
				ko = "초록의 그레이스의 우리",
				cn = "绿皮格蕾丝的牢笼",
			},
		},
	
		[241908] = {
			readable = "Prince's Plunder",
			model = 446671,
			text = {
				en = "Prince's Plunder",
				es = "Botín del Príncipe",
				de = "Beute des Prinzen",
				fr = "Butin du prince",
				it = "Bottino del Principe",
				pt = "Pilhagem do Príncipe",
				ru = "Трофеи принца",
				ko = "왕자의 약탈품",
				cn = "王子的战利品",
			},
		},
	
		[241909] = {
			readable = "Skrog Weapons",
			model = 1122160,
			text = {
				en = "Skrog Weapons",
				es = "Armas de skrog",
				de = "Skrogwaffen",
				fr = "Armes skrogs",
				it = "Armi di Skrog",
				pt = "Armas de Skrog",
				ru = "Оружие скрогов",
				ko = "거인 무기",
				cn = "海巨人武器",
			},
		},
	
		[241912] = {
			readable = "Exposed Ley Crystal",
			model = 1108688,
			text = {
				en = "Exposed Ley Crystal",
			},
		},
	
		[241913] = {
			readable = "Exposed Ley Crystal",
			model = 1108689,
			text = {
				en = "Exposed Ley Crystal",
			},
		},
	
		[241943] = {
			readable = "Wall Lamp",
			model = 194470,
			text = {
				en = "Wall Lamp",
				es = "Farol de pared",
				de = "Wandlampe",
				fr = "Lampe murale",
				it = "Lampione da Muro",
				pt = "Lâmpada de Parede",
				ru = "Настенный светильник",
				ko = "벽 등불",
				cn = "壁灯",
			},
		},
	
		[241944] = {
			readable = "Wall Lamp",
			model = 194470,
			text = {
				en = "Wall Lamp",
				es = "Farol de pared",
				de = "Wandlampe",
				fr = "Lampe murale",
				it = "Lampione da Muro",
				pt = "Lâmpada de Parede",
				ru = "Настенный светильник",
				ko = "벽 등불",
				cn = "壁灯",
			},
		},
	
		[241945] = {
			readable = "Wall Lamp",
			model = 194470,
			text = {
				en = "Wall Lamp",
				es = "Farol de pared",
				de = "Wandlampe",
				fr = "Lampe murale",
				it = "Lampione da Muro",
				pt = "Lâmpada de Parede",
				ru = "Настенный светильник",
				ko = "벽 등불",
				cn = "壁灯",
			},
		},
	
		[241946] = {
			readable = "Wall Lamp",
			model = 194470,
			text = {
				en = "Wall Lamp",
				es = "Farol de pared",
				de = "Wandlampe",
				fr = "Lampe murale",
				it = "Lampione da Muro",
				pt = "Lâmpada de Parede",
				ru = "Настенный светильник",
				ko = "벽 등불",
				cn = "壁灯",
			},
		},
	
		[241947] = {
			readable = "Wall Lamp",
			model = 194470,
			text = {
				en = "Wall Lamp",
				es = "Farol de pared",
				de = "Wandlampe",
				fr = "Lampe murale",
				it = "Lampione da Muro",
				pt = "Lâmpada de Parede",
				ru = "Настенный светильник",
				ko = "벽 등불",
				cn = "壁灯",
			},
		},
	
		[241948] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
	
		[241949] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
	
		[241950] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
	
		[241951] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
	
		[241952] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
	
		[241968] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
	
		[241969] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
	
		[241970] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
	
		[241971] = {
			readable = "Lamp",
			model = 194468,
			text = {
				en = "Lamp",
				es = "Farola",
				de = "Lampe",
				fr = "Lampe",
				it = "Lampada",
				pt = "Lâmpada",
				ru = "Светильник",
				ko = "등불",
				cn = "路灯",
			},
		},
})
do ObjectDB[objectID] = objectData; end
