local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	
		[245005] = {
			readable = "Tome of Blighted Implements",
			model = 1125315,
			text = {
				en = "Tome of Blighted Implements",
				es = "Escrito sobre artilugios malditos",
				de = "Foliant der verseuchten Instrumente",
				fr = "Grimoire des reliques interdites",
				it = "Tomo degli Strumenti della Rovina",
				pt = "Tomo dos Implementos Pestilentos",
				ru = "Фолиант орудий погибели",
				ko = "황폐화 도구의 고서",
			},
		},
	
		[245039] = {
			readable = "Tales of the Hunt",
			model = 1323641,
			text = {
				en = "Tales of the Hunt",
				es = "Historias de la caza",
				de = "Legenden der Jagd",
				fr = "Contes de la chasse",
				it = "Racconti di Caccia",
				pt = "Contos da Caça",
				ru = "Сказания об охоте",
				ko = "사냥 이야기",
				cn = "狩猎传说",
			},
		},
	
		[245054] = {
			readable = "Hammer of Khaz'goroth",
			model = 1140310,
			text = {
				en = "Hammer of Khaz'goroth",
				es = "Martillo de Khaz'goroth",
				de = "Hammer von Khaz'goroth",
				fr = "Marteau de Khaz’goroth",
				it = "Martello di Khaz'goroth",
				pt = "Martelo de Khaz'goroth",
				ru = "Молот Каз'горота",
				ko = "카즈고로스의 망치",
				cn = "卡兹格罗斯之锤",
			},
		},
	
		[245095] = {
			readable = "Reflective Portal",
			model = 1031604,
			text = {
				en = "Reflective Portal",
				es = "Portal reflectante",
				de = "Reflexionsportal",
				fr = "Portail réfléchissant",
				it = "Specchio Interdimensionale",
				pt = "Portal Reflexivo",
				ru = "Отражающий портал",
				ko = "회고의 차원문",
			},
		},
	
		[245102] = {
			readable = "Lever",
			model = 1243753,
			text = {
				en = "Lever",
				es = "Palanca",
				de = "Hebel",
				fr = "Levier",
				it = "Leva",
				pt = "Alavanca",
				ru = "Рычаг",
				ko = "지렛대",
				cn = "拉杆",
			},
		},
	
		[245108] = {
			readable = "Copper Vein",
			model = 219514,
			text = {
				en = "Copper Vein",
				es = "Filón de cobre",
				de = "Kupferader",
				fr = "Filon de cuivre",
				it = "Vena di Rame",
				pt = "Veio de Cobre",
				ru = "Медная жила",
				ko = "구리 광맥",
				cn = "铜矿脉",
			},
		},
	
		[245112] = {
			readable = "Tome of Fel Secrets",
			model = 1125315,
			text = {
				en = "Tome of Fel Secrets",
				es = "Escrito de secretos viles",
				de = "Foliant der Dämonengeheimnisse",
				fr = "Tome des secrets gangrenés",
				it = "Tomo dei Vilsegreti",
				pt = "Tomo dos Segredos Vis",
				ru = "Фолиант тайн Скверны",
				ko = "지옥 비밀의 일지",
				cn = "邪魔之秘魔典",
			},
		},
	
		[245125] = {
			readable = "Jung's Special Brew",
			model = 521686,
			text = {
				en = "Jung's Special Brew",
				es = "Brebaje especial de Jung",
				de = "Jungs Spezialgebräu",
				fr = "Cuvée spéciale de Jung",
				it = "Birra Speciale di Jung",
				pt = "Beberagem Especial de Jung",
				ru = "Особый отвар Цзюна",
				ko = "정의 특별주",
				cn = "老蒋特酿",
			},
		},
	
		[245126] = {
			readable = "Crystallized Ancient Mana",
			model = 1108690,
			text = {
				en = "Crystallized Ancient Mana",
				es = "Maná antiguo cristalizado",
				de = "Kristallisiertes uraltes Mana",
				fr = "Mana ancestral cristallisé",
				it = "Mana Antico Cristallizzato",
				pt = "Mana Ancestral Cristalizado",
				ru = "Кристаллизованная древняя мана",
				ko = "고대 마나 결정",
				cn = "晶化远古魔力",
			},
		},
	
		[245158] = {
			readable = "Weapon Rack",
			model = 200608,
			text = {
				en = "Weapon Rack",
				es = "Expositor de armas",
				de = "Waffenständer",
				fr = "Râtelier d’armes",
				it = "Rastrelliera delle Armi",
				pt = "Cavalete de Armas",
				ru = "Оружейная стойка",
				cn = "武器架",
			},
		},
	
		[245171] = {
			readable = "Agnes' Skinning Knife",
			model = 936407,
			text = {
				en = "Agnes' Skinning Knife",
				es = "Cuchillo de desuello de Agnes",
				de = "Agnes' Kürschnermesser",
				fr = "Couteau à dépecer d’Agnès",
				it = "Coltello da Scuoiatore di Agnes",
				pt = "Faca de Esfolamento de Agnes",
				ru = "Нож Агнес для снятия шкур",
				ko = "아그네스의 무두질용 손칼",
				cn = "艾格尼丝的剥皮小刀",
			},
		},
	
		[245186] = {
			readable = "Clump of Cliffthorn Twigs",
			model = 1097788,
			text = {
				en = "Clump of Cliffthorn Twigs",
				es = "Montón de ramitas de riscoespina",
				de = "Büschel Klippendornzweige",
				fr = "Touffe de ronces des falaises",
				it = "Mucchio di Rupespina",
				pt = "Amontoado de Gravetos Espinhascos",
				ru = "Связка ветвей скалошипа",
				ko = "벼랑가시 가지 더미",
				cn = "一根悬崖棘树枝",
			},
		},
	
		[245188] = {
			readable = "Mystic Bonfire",
			model = 200899,
			text = {
				en = "Mystic Bonfire",
				es = "Hoguera mística",
				de = "Mystisches Feuer",
				fr = "Feu de joie mystique",
				it = "Falò Mistico",
				pt = "Fogueira Mística",
				ru = "Костер мистиков",
				ko = "신비의 화톳불",
			},
		},
	
		[245198] = {
			readable = "Black Rook Armor",
			model = 1246938,
			text = {
				en = "Black Rook Armor",
				es = "Armadura de Grajo Negro",
				de = "Rabenwehrrüstung",
				fr = "Armure du Freux",
				it = "Armatura di Corvonero",
				pt = "Armadura Corvo Negro",
				ru = "Доспехи крепости Черной Ладьи",
				ko = "검은 떼까마귀 방어구",
				cn = "黑鸦护甲",
			},
		},
	
		[245199] = {
			readable = "Drogbar Stash",
			model = 1131729,
			text = {
				en = "Drogbar Stash",
				es = "Alijo drógbar",
				de = "Vorrat der Drogbar",
				fr = "Planque de Drogbar",
				it = "Scorte dei Drogbar",
				pt = "Esconderijo Drogbar",
				ru = "Тайник дрогбаров",
				ko = "드로그바 보관함",
			},
		},
	
		[245201] = {
			readable = "Leyota's Legacy",
			model = 1338688,
			text = {
				en = "Leyota's Legacy",
				es = "Legado de Leyota",
				de = "Leyotas Erbe",
				fr = "Héritage de Leyota",
				it = "Retaggio di Leyota",
				pt = "Legado de Leyota",
				ru = "Наследие Лейоты",
				ko = "레요타의 유산",
				cn = "丽约塔的遗产",
			},
		},
	
		[245203] = {
			readable = "Revelation of Garhan",
			model = 1338945,
			text = {
				en = "Revelation of Garhan",
				es = "Revelación de Garhan",
				de = "Garhans Offenbarung",
				fr = "Révélation de Garhan",
				it = "Rivelazione di Garhan",
				pt = "Revelação de Garhan",
				ru = "Откровение Гархана",
				ko = "가르한의 가르침",
				cn = "加汗的启示",
			},
		},
	
		[245204] = {
			readable = "Caruk the Simple",
			model = 1345313,
			text = {
				en = "Caruk the Simple",
				es = "Caruk el Sencillo",
				de = "Caruk der Einfältige",
				fr = "Caruk le Simple",
				it = "Caruk il Semplice",
				pt = "Caruk, o Simples",
				ru = "Карук Простак",
				ko = "단순한 자 카루크",
				cn = "没头脑的卡鲁克",
			},
		},
	
		[245210] = {
			readable = "Disarmed Treasure Chest",
			model = 1100065,
			text = {
				en = "Disarmed Treasure Chest",
				es = "Arqueta desarmada",
				de = "Entschärfte Schatztruhe",
				fr = "Coffre au trésor désarmé",
				it = "Cassa del Tesoro Disattivata",
				pt = "Baú do Tesouro Desarmado",
				ru = "Обезвреженный сундук с сокровищами",
			},
		},
	
		[245212] = {
			readable = "Magic Harpoon",
			model = 874421,
			text = {
				en = "Magic Harpoon",
				es = "Arpón mágico",
				de = "Magische Harpune",
				fr = "Harpon magique",
				it = "Arpione Magico",
				pt = "Arpão Mágico",
				ru = "Магический гарпун",
			},
		},
	
		[245214] = {
			readable = "Bilgewater Special",
			model = 254419,
			text = {
				en = "Bilgewater Special",
			},
		},
	
		[245216] = {
			readable = "|cFFFFFFFFStep 3:|r Page 161",
			icon = 1505961,
			model = 305393,
			text = {
				en = "|cFFFFFFFFStep 3:|r Page 161",
				es = "|cFFFFFFFFStep 3:|r Página 161",
				de = "|cFFFFFFFFSchritt 3:|r Seite 161",
				fr = "|cFFFFFFFFÉtape 3:|r Page 161",
				it = "|cFFFFFFFFStep 3:|r Pagina 161",
				pt = "|cFFFFFFFFStep 3:|r Página 161",
				ru = "|cFFFFFFFFШаг 3:|r Страница 161",
				ko = "|cFFFFFFFFStep 3:|r 161쪽",
				cn = "|cFFFFFFFF第3步:|r 第161页",
			},
		},
	
		[245221] = {
			readable = "Crate of Mail Armor",
			model = 987255,
			text = {
				en = "Crate of Mail Armor",
				es = "Cajón de armaduras de malla",
				de = "Kiste mit Kettenrüstungen",
				fr = "Caisse d’armure en maille",
				it = "Cassa di Armature di Maglia",
				pt = "Caixote de Armaduras de Malha",
				ru = "Ящик с кольчужными доспехами",
				ko = "쇠사슬 갑옷 상자",
				cn = "一箱锁甲",
			},
		},
	
		[245230] = {
			readable = "Scale of Deathwing",
			model = 381037,
			text = {
				en = "Scale of Deathwing",
				es = "Escama de Alamuerte",
				de = "Schuppe von Todesschwinge",
				fr = "Écaille d’Aile de mort",
				it = "Scaglia di Alamorte",
				pt = "Escama de Asa da Morte",
				ru = "Чешуйка Смертокрыла",
				ko = "데스윙의 비늘",
				cn = "死亡之翼的鳞片",
			},
		},
	
		[245232] = {
			readable = "Ending Treasure Chest",
			model = 1100065,
			text = {
				en = "Ending Treasure Chest",
				es = "Arqueta final",
				de = "Endschatztruhe",
				fr = "Coffre au trésor de fin",
				it = "Cassa del Tesoro Duratura",
				pt = "Baú do Tesouro Final",
				ru = "Сундук с остатками сокровищ",
				ko = "끝 있는 보물 상자",
				cn = "残余的宝箱",
			},
		},
	
		[245234] = {
			readable = "Barrier Control",
			model = 1243753,
			text = {
				en = "Barrier Control",
				es = "Control de barrera",
				de = "Barrierensteuerung",
				fr = "Commande de la barrière",
				it = "Cristallo di Controllo della Barriera",
				pt = "Controle de Barreira",
				ru = "Активатор барьера",
				ko = "방벽 제어기",
				cn = "屏障控制器",
			},
		},
	
		[245236] = {
			readable = "Encyclopedia Botanica",
			model = 1124088,
			text = {
				en = "Encyclopedia Botanica",
				es = "Enciclopedia botánica",
				de = "Encyclopaedia Botanica",
				it = "Enciclopedia Botanica",
				pt = "Enciclopédia Botânica",
				ru = "\"Энциклопедия ботаники\"",
				ko = "식물 대백과사전",
				cn = "植物百科大全",
			},
		},
	
		[245238] = {
			readable = "Sanctum Crystal",
			model = 1243753,
			text = {
				en = "Sanctum Crystal",
				es = "Cristal del Sagrario",
				de = "Sanktumskristall",
				fr = "Cristal de sanctum",
				it = "Cristallo del Santuario",
				pt = "Cristal do Santuário",
				ru = "Кристалл святилища",
				ko = "성소 수정",
				cn = "秘殿水晶",
			},
		},
	
		[245241] = {
			readable = "Wisdom of Lohfal",
			model = 874409,
			text = {
				en = "Wisdom of Lohfal",
				es = "Sabiduría de Lohfal",
				de = "Lohfals Weisheit",
				fr = "Sagesse de Lohfal",
				it = "Saggezza di Lohfal",
				pt = "Sabedoria de Lohfal",
				ru = "Мудрость Лофала",
				ko = "로팔의 지혜",
			},
		},
	
		[245245] = {
			readable = "Vengeful Warglaive",
			model = 1101705,
			text = {
				en = "Vengeful Warglaive",
				es = "Guja de guerra vengativa",
				de = "Rachsüchtige Kriegsgleve",
				fr = "Glaive de guerre vengeur",
				it = "Lama da Guerra Vendicativa",
				pt = "Glaive de Guerra Vingativa",
				ru = "Мстительный боевой клинок",
				ko = "복수의 전투검",
				cn = "复仇战刃",
			},
		},
	
		[245254] = {
			readable = "Wisdom of Halewa",
			model = 950748,
			text = {
				en = "Wisdom of Halewa",
				es = "Sabiduría de Halewa",
				de = "Halewas Weisheit",
				fr = "Sagesse d’Halewa",
				it = "Saggezza di Halewa",
				pt = "Sabedoria de Halewa",
				ru = "Мудрость Халевы",
				ko = "할레와의 지혜",
				cn = "海勒瓦的智慧",
			},
		},
	
		[245274] = {
			readable = "Wisdom of Torgrul",
			model = 950920,
			text = {
				en = "Wisdom of Torgrul",
				es = "Sabiduría de Torgrul",
				de = "Torgruls Weisheit",
				fr = "Sagesse de Torgrul",
				it = "Saggezza di Torgrul",
				pt = "Sabedoria de Torgrul",
				ru = "Мудрость Торгрула",
				ko = "톨그룰의 지혜",
				cn = "托古尔的智慧",
			},
		},
	
		[245286] = {
			readable = "Crystalline Cat Figurine",
			icon = 454045,
			model = 192711,
			text = {
				en = "Crystalline Cat Figurine",
				es = "Figurilla de gato cristalina",
				de = "Kristallkatzenstatuette",
				fr = "Figurine de chat en cristal",
				it = "Statuetta Felina Cristallina",
				pt = "Estatueta de Gato Cristalina",
				ru = "Кристальная статуэтка кошки",
				ko = "수정 호랑이 조각상",
				cn = "水晶猫咪雕像",
			},
		},
	
		[245287] = {
			readable = "Wisdom of Garuu",
			model = 950920,
			text = {
				en = "Wisdom of Garuu",
				es = "Sabiduría de Garuu",
				de = "Garuus Weisheit",
				fr = "Sagesse de Garuu",
				it = "Saggezza di Garuu",
				pt = "Sabedoria de Garuu",
				ru = "Мудрость Гаруу",
				ko = "가루의 지혜",
				cn = "贾鲁的智慧",
			},
		},
	
		[245290] = {
			readable = "Mystic Bonfire",
			model = 200899,
			text = {
				en = "Mystic Bonfire",
				es = "Hoguera mística",
				de = "Mystisches Feuer",
				fr = "Feu de joie mystique",
				it = "Falò Mistico",
				pt = "Fogueira Mística",
				ru = "Костер мистиков",
				ko = "신비의 화톳불",
			},
		},
	
		[245316] = {
			readable = "Small Treasure Chest",
			icon = 308482,
			model = 1349995,
			text = {
				en = "Small Treasure Chest",
				es = "Cofre del tesoro pequeño",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[245321] = {
			readable = "Katarine's Cage",
			model = 1118155,
			text = {
				en = "Katarine's Cage",
				es = "Jaula de Katarine",
				de = "Katarines Käfig",
				fr = "Cage de Katarine",
				it = "Gabbia di Katarine",
				pt = "Jaula de Catarina",
				ru = "Клетка Катарины",
				ko = "카타린의 우리",
				cn = "卡特琳的笼子",
			},
		},
	
		[245324] = {
			readable = "Rich Leystone Deposit",
			model = 1244490,
			text = {
				en = "Rich Leystone Deposit",
				es = "Depósito rico en piedra Ley",
				de = "Reiches Leysteinvorkommen",
				fr = "Riche gisement de tellurium",
				it = "Deposito Ricco di Fagliaroccia",
				pt = "Depósito Rico de Pedra de Meridiano",
				ru = "Богатые залежи силового камня",
				ko = "풍부한 지맥석 광맥",
				cn = "富魔石矿脉",
			},
		},
	
		[245325] = {
			readable = "Rich Felslate Deposit",
			model = 1244488,
			text = {
				en = "Rich Felslate Deposit",
				es = "Depósito rico en pizarra vil",
				de = "Reiches Teufelsschiefervorkommen",
				fr = "Riche gisement de gangreschiste",
				it = "Deposito Ricco di Vilardesia",
				pt = "Depósito Rico de Vilardósia",
				ru = "Богатые залежи сланца Скверны",
				ko = "풍부한 지옥판암 광맥",
				cn = "富邪能页岩矿脉",
			},
		},
	
		[245327] = {
			readable = "Kel'danath's Notes",
			model = 1365480,
			text = {
				en = "Kel'danath's Notes",
				es = "Notas de Kel'danath",
				de = "Kel'danaths Notizen",
				fr = "Notes de Kel’danath",
				it = "Note di Kel'danath",
				pt = "Notas de Kel'danath",
				ru = "Записи Кел'даната",
				ko = "켈다나스의 기록",
				cn = "凯尔丹纳斯的笔记",
			},
		},
	
		[245328] = {
			readable = "Enchanted Scroll",
			icon = 1500882,
			model = 1365480,
			text = {
				en = "Enchanted Scroll",
				es = "Pergamino encantado",
				de = "Verzauberte Schriftrolle",
				fr = "Parchemin enchanté",
				it = "Pergamena Incantata",
				pt = "Pergaminho Encantado",
				ru = "Зачарованный свиток",
				ko = "마력 깃든 두루마리",
				cn = "附魔卷轴",
			},
		},
	
		[245340] = {
			readable = "Throne of Ordering Around",
			model = 961712,
			text = {
				en = "Throne of Ordering Around",
				es = "Trono de mandar mucho",
				de = "Thron der Rumkommandiererei",
				fr = "Trône du donneur d’ordres",
				it = "Trono degli Ordini",
				pt = "Trono do Eu que Mando",
				ru = "Трон помыкания",
				ko = "이래라저래라 왕좌",
				cn = "指挥之座",
			},
		},
	
		[245345] = {
			readable = "Small Treasure Chest",
			icon = 308482,
			model = 1349995,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[245346] = {
			readable = "Powder Keg",
			model = 197464,
			text = {
				en = "Powder Keg",
				es = "Tonel de pólvora",
				de = "Pulverfass",
				fr = "Baril de poudre",
				pt = "Barril de Pólvora",
				ru = "Бочонок с порохом",
			},
		},
	
		[245350] = {
			readable = "Shipwrecked Supplies",
			model = 198168,
			text = {
				en = "Shipwrecked Supplies",
				es = "Suministros del naufragio",
				de = "Gestrandete Versorgungsgüter",
				fr = "Fournitures naufragées",
				it = "Rifornimenti Naufragati",
				pt = "Suprimentos Naufragados",
				ru = "Припасы с затонувшего корабля",
				cn = "船难物资",
			},
		},
	
		[245357] = {
			readable = "Candleking's Special Candle",
			model = 199809,
			text = {
				en = "Candleking's Special Candle",
				es = "Vela especial del rey de las velas",
				de = "Spezialkerze des Kerzenkönigs",
				fr = "Bougie spéciale du roi des bougies",
				it = "Candela Speciale del Re delle Candele",
				pt = "Vela Especial do Rei da Vela",
				ru = "Особая свеча для Свечного короля",
				ko = "양초왕의 특별 양초",
				cn = "蜡烛大王的特制蜡烛",
			},
		},
	
		[245358] = {
			readable = "Light in the Darkness",
			model = 1267047,
			text = {
				en = "Light in the Darkness",
				es = "Luz en la oscuridad",
				de = "Licht im Dunkeln",
				fr = "Lumière dans les ténèbres",
				it = "Luce nell'Oscurità",
				pt = "Luz nas Trevas",
				ru = "Свет во тьме",
				ko = "어둠 속의 빛",
				cn = "黑暗中的光明",
			},
		},
	
		[245359] = {
			readable = "Striding with the Sunwalkers",
			model = 1267049,
			text = {
				en = "Striding with the Sunwalkers",
				es = "Paseo con los Caminasol",
				de = "Der mit den Sonnenläufern rennt",
				fr = "Voyage avec les marche-soleil",
				it = "Camminare con i Campioni del Sole",
				pt = "Caminhando com os Andarilhos do Sol",
				ru = "\"Прогулки со Служителями Солнца\"",
				ko = "태양길잡이와 함께 걸으며",
				cn = "与逐日者同行",
			},
		},
	
		[245361] = {
			readable = "Valarjar Spoils",
			model = 446677,
			text = {
				en = "Valarjar Spoils",
				es = "Botín Valarjar",
				de = "Schätze der Valarjar",
				fr = "Butin des Valarjar",
				it = "Spoglie dei Valarjar",
				pt = "Espólios Valarjares",
				ru = "Трофеи валарьяров",
				ko = "발라리아르 전리품",
				cn = "瓦拉加尔战利品",
			},
		},
	
		[245368] = {
			readable = "Namha's Tanning Mixture",
			model = 243422,
			text = {
				en = "Namha's Tanning Mixture",
				es = "Mezcla de curtido de Namha",
				de = "Namhas Gerbstoffmischung",
				fr = "Mixture de tannage de Namha",
				it = "Mistura da Tannatura di Namha",
				pt = "Mistura de Curtimento de Namha",
				ru = "Дубильный раствор Намхи",
				ko = "남하의 무두질 혼합물",
				cn = "娜穆的制皮合剂",
			},
		},
	
		[245379] = {
			readable = "Highlord Tirion Fordring",
			model = 199987,
			text = {
				en = "Highlord Tirion Fordring",
				es = "Alto señor Tirion Vadín",
				de = "Hochlord Tirion Fordring",
				fr = "Généralissime Tirion Fordring",
				it = "Gran Signore Tirion Fordring",
				pt = "Grão-lorde Tirion Fordring",
				ru = "Верховный лорд Тирион Фордринг",
				ko = "대영주 티리온 폴드링",
				cn = "大领主提里奥·弗丁",
			},
		},
	
		[245380] = {
			readable = "General Turalyon",
			model = 199987,
			text = {
				en = "General Turalyon",
				fr = "Général Turalyon",
				it = "Generale Turalyon",
				ru = "Генерал Туралион",
				ko = "투랄리온 장군",
				cn = "图拉扬将军",
			},
		},
	
		[245381] = {
			readable = "Uther the Lightbringer",
			model = 199987,
			text = {
				en = "Uther the Lightbringer",
				es = "Uther el Iluminado",
				de = "Uther der Lichtbringer",
				fr = "Uther le Porteur de Lumière",
				it = "Uther l'Araldo della Luce",
				pt = "Uther, o Arauto da Luz",
				ru = "Утер Светоносный",
				ko = "빛의 수호자 우서",
				cn = "光明使者乌瑟尔",
			},
		},
	
		[245382] = {
			readable = "Lady Mara Fordragon",
			model = 199987,
			text = {
				en = "Lady Mara Fordragon",
				es = "Lady Mara Fordragón",
				fr = "Dame Mara Fordragon",
				it = "Dama Mara Domadraghi",
				ru = "Леди Мара Фордрагон",
				ko = "여군주 마라 폴드라곤",
				cn = "玛拉·弗塔根",
			},
		},
	
		[245383] = {
			readable = "Krohm Dawnhammer",
			model = 199987,
			text = {
				en = "Krohm Dawnhammer",
				es = "Krohm Albamartillo",
				de = "Krohm Morgenhammer",
				fr = "Krohm Aubemarteau",
				it = "Krohm Mazzasolare",
				pt = "Krohm Albamalho",
				ru = "Кром Молот Рассвета",
				ko = "크롬 돈해머",
				cn = "克罗姆·黎明之锤",
			},
		},
	
		[245384] = {
			readable = "Highlord Alexandros Mograine",
			model = 199987,
			text = {
				en = "Highlord Alexandros Mograine",
				es = "Alto señor Alexandros Mograine",
				de = "Hochlord Alexandros Mograine",
				fr = "Généralissime Alexandros Mograine",
				it = "Gran Signore Alexandros Mograine",
				pt = "Grão-lorde Alexandros Mograine",
				ru = "Верховный лорд Александрос Могрейн",
				ko = "대영주 알렉산드로스 모그레인",
				cn = "大领主亚历山德罗斯·莫格莱尼",
			},
		},
	
		[245385] = {
			readable = "Vindicator Maraad",
			model = 199987,
			text = {
				en = "Vindicator Maraad",
				es = "Vindicador Maraad",
				de = "Verteidiger Maraad",
				fr = "Redresseur de torts Maraad",
				it = "Vendicatore Maraad",
				pt = "Vindicante Maraad",
				ru = "Воздаятель Мараад",
				ko = "구원자 마라아드",
				cn = "守备官玛尔拉德",
			},
		},
	
		[245471] = {
			readable = "Legion Chest",
			model = 1125838,
			text = {
				en = "Legion Chest",
				fr = "Coffre de la Légion",
			},
		},
	
		[245479] = {
			readable = "Battered Chest",
			icon = 132594,
			model = 446677,
			text = {
				en = "Battered Chest",
				es = "Cofre maltrecho",
				de = "Ramponierte Truhe",
				fr = "Coffre endommagé",
				it = "Cassa Danneggiata",
				pt = "Baú Desgastado",
				ru = "Побитый сундук",
				ko = "찌그러진 궤짝",
				cn = "破损的箱子",
				tw = "破損的箱子",
			},
		},
	
		[245483] = {
			readable = "Tidestone Shard",
			model = 1134484,
			text = {
				en = "Tidestone Shard",
				es = "Fragmento de la Piedramar",
				de = "Splitter des Gezeitensteins",
				fr = "Éclat de la Pierre-des-Marées",
				it = "Frammento della Pietra delle Maree",
				pt = "Estilhaço da Pedramar",
				ru = "Осколок Приливного Камня",
				ko = "해일석 조각",
				cn = "潮汐之石碎片",
			},
		},
	
		[245484] = {
			readable = "Tidestone Shard",
			model = 1134485,
			text = {
				en = "Tidestone Shard",
				es = "Fragmento de la Piedramar",
				de = "Splitter des Gezeitensteins",
				fr = "Éclat de la Pierre-des-Marées",
				it = "Frammento della Pietra delle Maree",
				pt = "Estilhaço da Pedramar",
				ru = "Осколок Приливного Камня",
				ko = "해일석 조각",
				cn = "潮汐之石碎片",
			},
		},
	
		[245485] = {
			readable = "Tidestone Shard",
			model = 1134487,
			text = {
				en = "Tidestone Shard",
				es = "Fragmento de la Piedramar",
				de = "Splitter des Gezeitensteins",
				fr = "Éclat de la Pierre-des-Marées",
				it = "Frammento della Pietra delle Maree",
				pt = "Estilhaço da Pedramar",
				ru = "Осколок Приливного Камня",
				ko = "해일석 조각",
				cn = "潮汐之石碎片",
			},
		},
	
		[245486] = {
			readable = "Tidestone Shard",
			model = 1134488,
			text = {
				en = "Tidestone Shard",
				es = "Fragmento de la Piedramar",
				de = "Splitter des Gezeitensteins",
				fr = "Éclat de la Pierre-des-Marées",
				it = "Frammento della Pietra delle Maree",
				pt = "Estilhaço da Pedramar",
				ru = "Осколок Приливного Камня",
				ko = "해일석 조각",
				cn = "潮汐之石碎片",
			},
		},
	
		[245506] = {
			readable = "Thunderbrew Special",
			model = 198367,
			text = {
				en = "Thunderbrew Special",
				es = "Especial de brebaje de trueno",
				de = "Donnerbräu Spezial",
				fr = "Spécialité des Tonnebière",
				pt = "Especial Cervaforte",
				ru = "Громоварское особое",
			},
		},
	
		[245507] = {
			readable = "Supply Cache",
			model = 1096755,
			text = {
				en = "Supply Cache",
				es = "Alijo de suministros",
				de = "Vorrat",
				fr = "Cache de fournitures",
				it = "Cassa di Forniture",
				pt = "Caixa de Suprimentos",
				ru = "Тайник с припасами",
				ko = "보급품 상자",
				cn = "补给箱",
			},
		},
	
		[245514] = {
			readable = "Sentry",
			model = 1119129,
			text = {
				en = "Sentry",
				es = "Centinela",
				de = "Wächter",
				fr = "Sentinelle",
				it = "Sentinella",
				pt = "Sentinela",
				ru = "Часовой",
				ko = "파수기",
				cn = "哨兵",
			},
		},
	
		[245515] = {
			readable = "Sentry",
			model = 1119129,
			text = {
				en = "Sentry",
				es = "Centinela",
				de = "Wächter",
				fr = "Sentinelle",
				it = "Sentinella",
				pt = "Sentinela",
				ru = "Часовой",
				ko = "파수기",
				cn = "哨兵",
			},
		},
	
		[245516] = {
			readable = "Sentry",
			model = 1119129,
			text = {
				en = "Sentry",
				es = "Centinela",
				de = "Wächter",
				fr = "Sentinelle",
				it = "Sentinella",
				pt = "Sentinela",
				ru = "Часовой",
				ko = "파수기",
				cn = "哨兵",
			},
		},
	
		[245517] = {
			readable = "Sentry",
			model = 1119129,
			text = {
				en = "Sentry",
				es = "Centinela",
				de = "Wächter",
				fr = "Factionnaire",
				it = "Sentinella",
				pt = "Sentinela",
				ru = "Часовой",
				ko = "파수기",
				cn = "哨兵",
			},
		},
	
		[245518] = {
			readable = "Sentry",
			model = 1119129,
			text = {
				en = "Sentry",
				es = "Centinela",
				de = "Wächter",
				fr = "Sentinelle",
				it = "Sentinella",
				pt = "Sentinela",
				ru = "Часовой",
				ko = "파수기",
				cn = "哨兵",
			},
		},
	
		[245519] = {
			readable = "Sentry",
			model = 1119129,
			text = {
				en = "Sentry",
				es = "Centinela",
				de = "Wächter",
				fr = "Sentinelle",
				it = "Sentinella",
				pt = "Sentinela",
				ru = "Часовой",
				ko = "파수기",
				cn = "哨兵",
			},
		},
	
		[245520] = {
			readable = "Sentry",
			model = 1119129,
			text = {
				en = "Sentry",
				es = "Centinela",
				de = "Wächter",
				fr = "Sentinelle",
				it = "Sentinella",
				pt = "Sentinela",
				ru = "Часовой",
				ko = "파수기",
				cn = "哨兵",
			},
		},
	
		[245521] = {
			readable = "Sentry",
			model = 1119129,
			text = {
				en = "Sentry",
				es = "Centinela",
				de = "Wächter",
				fr = "Sentinelle",
				it = "Sentinella",
				pt = "Sentinela",
				ru = "Часовой",
				ko = "파수기",
				cn = "哨兵",
			},
		},
	
		[245522] = {
			readable = "Sentry",
			model = 1119129,
			text = {
				en = "Sentry",
				es = "Centinela",
				de = "Wächter",
				fr = "Sentinelle",
				it = "Sentinella",
				pt = "Sentinela",
				ru = "Часовой",
				ko = "파수기",
				cn = "哨兵",
			},
		},
	
		[245523] = {
			readable = "Sentry",
			model = 1119129,
			text = {
				en = "Sentry",
				es = "Centinela",
				de = "Wächter",
				fr = "Sentinelle",
				it = "Sentinella",
				pt = "Sentinela",
				ru = "Часовой",
				ko = "파수기",
				cn = "哨兵",
			},
		},
	
		[245524] = {
			readable = "Treasure Chest",
			model = 1402238,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[245525] = {
			readable = "Small Treasure Chest",
			model = 1402225,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[245527] = {
			readable = "Treasure Chest",
			model = 1402238,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[245528] = {
			readable = "Treasure Chest",
			model = 1402238,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[245529] = {
			readable = "Small Treasure Chest",
			model = 1402225,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[245530] = {
			readable = "Glimmering Treasure Chest",
			model = 1349622,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[245531] = {
			readable = "Treasure Chest",
			model = 1402225,
			text = {
				en = "Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "보물 상자",
				cn = "小宝箱",
			},
		},
	
		[245532] = {
			readable = "Treasure Chest",
			model = 1402238,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[245533] = {
			readable = "Treasure Chest",
			model = 1402238,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[245534] = {
			readable = "Small Treasure Chest",
			model = 1402225,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[245535] = {
			readable = "Small Treasure Chest",
			model = 1402225,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[245536] = {
			readable = "Glimmering Treasure Chest",
			model = 1402222,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[245537] = {
			readable = "Glimmering Treasure Chest",
			model = 1402222,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[245538] = {
			readable = "Small Treasure Chest",
			model = 1402225,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[245541] = {
			readable = "Small Treasure Chest",
			model = 1402225,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[245542] = {
			readable = "Treasure Chest",
			model = 1402238,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[245543] = {
			readable = "Treasure Chest",
			model = 1402238,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[245545] = {
			readable = "Small Treasure Chest",
			model = 1402225,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[245547] = {
			readable = "Small Treasure Chest",
			model = 1402225,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[245548] = {
			readable = "Treasure Chest",
			model = 1402238,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[245550] = {
			readable = "Treasure Chest",
			model = 1402238,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[245551] = {
			readable = "Small Treasure Chest",
			model = 1402225,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[245553] = {
			readable = "Treasure Chest",
			model = 1402238,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[245554] = {
			readable = "Small Treasure Chest",
			model = 1402225,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[245555] = {
			readable = "Small Treasure Chest",
			model = 1402225,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[245575] = {
			readable = "Frost Sentry",
			model = 1269714,
			text = {
				en = "Frost Sentry",
				es = "Avizor de escarcha",
				de = "Frostwächter",
				fr = "Factionnaire de givre",
				it = "Sentinella Ghiacciata",
				pt = "Sentinela de Gelo",
				ru = "Ледяной часовой",
				ko = "서리 파수기",
				cn = "冰霜哨兵",
			},
		},
	
		[245576] = {
			readable = "Frost Sentry",
			model = 1269714,
			text = {
				en = "Frost Sentry",
				es = "Avizor de escarcha",
				de = "Frostwächter",
				fr = "Factionnaire de givre",
				it = "Sentinella Ghiacciata",
				pt = "Sentinela Gélida",
				ru = "Ледяной часовой",
				ko = "서리 파수기",
				cn = "冰霜哨兵",
			},
		},
	
		[245577] = {
			readable = "Frost Sentry",
			model = 1269714,
			text = {
				en = "Frost Sentry",
				es = "Avizor de escarcha",
				de = "Frostwächter",
				fr = "Factionnaire de givre",
				it = "Sentinella Ghiacciata",
				pt = "Sentinela Gélida",
				ru = "Ледяной часовой",
				ko = "서리 파수기",
				cn = "冰霜哨兵",
			},
		},
	
		[245579] = {
			readable = "Treasure Chest",
			model = 1402238,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[245580] = {
			readable = "Small Treasure Chest",
			model = 1402225,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[245581] = {
			readable = "Small Treasure Chest",
			model = 1402225,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[245601] = {
			readable = "Small Treasure Chest",
			model = 1402225,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[245602] = {
			readable = "Treasure Chest",
			model = 1402238,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[245603] = {
			readable = "Small Treasure Chest",
			model = 1402225,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[245620] = {
			readable = "Mu'sha's Tears",
			model = 589555,
			text = {
				en = "Mu'sha's Tears",
				es = "Lágrimas de Mu'sha",
				de = "Mu'shas Tränen",
				fr = "Larmes de Mu’sha",
				it = "Lacrime di Mu'sha",
				pt = "Lágrimas de Mu'sha",
				ru = "Слезы Му'ши",
				ko = "무샤의 눈물",
				cn = "穆莎之泪",
			},
		},
	
		[245621] = {
			readable = "Bottle of Airspark",
			model = 577391,
			text = {
				en = "Bottle of Airspark",
				es = "Botella de chispa de aire",
				de = "Flasche mit Luftfunken",
				fr = "Bouteille d’étincielle",
				it = "Bottiglia di Scintillaria",
				pt = "Garrafa de Faiscaérea",
				ru = "Бутыль воздушных искр",
				ko = "공기불꽃 한 병",
				cn = "一瓶大气之火",
			},
		},
	
		[245623] = {
			readable = "Tiffany's Carving Machine",
			model = 1449412,
			text = {
				en = "Tiffany's Carving Machine",
				es = "Grabadora de Tiffany",
				de = "Tiffanys Schleifmaschine",
				fr = "Outil de taille de Tiffany",
				it = "Dispositivo di Taglio di Tiffany",
				pt = "Máquina de Gravação da Sojoia",
				ru = "Гранильный станок Тиффани",
				ko = "티파니의 세공 도구",
				cn = "蒂凡妮的切割机",
			},
		},
	
		[245650] = {
			readable = "Black Rook Cage",
			model = 195417,
			text = {
				en = "Black Rook Cage",
				es = "Jaula de Grajo Negro",
				de = "Käfig der Rabenwehr",
				fr = "Cage du Freux",
				it = "Gabbia di Corvonero",
				pt = "Jaula Corvo Negro",
				ru = "Клетка крепости Черной Ладьи",
				ko = "검은 떼까마귀 우리",
				cn = "黑鸦牢笼",
			},
		},
	
		[245661] = {
			readable = "Can of Overheated Oil",
			text = {
				en = "Can of Overheated Oil",
			},
		},
	
		[245667] = {
			readable = "Whelp Cage",
			model = 1097623,
			text = {
				en = "Whelp Cage",
				es = "Jaula de cría",
				de = "Welpenkäfig",
				fr = "Cage à dragonnet",
				it = "Gabbia dei Draghetti",
				pt = "Jaula de Filhote",
				ru = "Клетка для дракончика",
				ko = "새끼용 우리",
				cn = "幼兽牢笼",
			},
		},
	
		[245668] = {
			readable = "Whelp Cage",
			model = 1097623,
			text = {
				en = "Whelp Cage",
				es = "Jaula de cría",
				de = "Welpenkäfig",
				fr = "Cage à dragonnet",
				it = "Gabbia dei Draghetti",
				pt = "Jaula de Filhote",
				ru = "Клетка для дракончика",
				ko = "새끼용 우리",
				cn = "幼兽牢笼",
			},
		},
	
		[245669] = {
			readable = "Whelp Cage",
			model = 1097623,
			text = {
				en = "Whelp Cage",
				es = "Jaula de cría",
				de = "Welpenkäfig",
				fr = "Cage à dragonnet",
				it = "Gabbia dei Draghetti",
				pt = "Jaula de Filhote",
				ru = "Клетка для дракончика",
				ko = "새끼용 우리",
				cn = "幼兽牢笼",
			},
		},
	
		[245670] = {
			readable = "Whelp Cage",
			model = 1097623,
			text = {
				en = "Whelp Cage",
				es = "Jaula de cría",
				de = "Welpenkäfig",
				fr = "Cage à dragonnet",
				it = "Gabbia dei Draghetti",
				pt = "Jaula de Filhote",
				ru = "Клетка для дракончика",
				ko = "새끼용 우리",
				cn = "幼兽牢笼",
			},
		},
	
		[245671] = {
			readable = "Whelp Cage",
			model = 1097623,
			text = {
				en = "Whelp Cage",
				es = "Jaula de cría",
				de = "Welpenkäfig",
				fr = "Cage à dragonnet",
				it = "Gabbia dei Draghetti",
				pt = "Jaula de Filhote",
				ru = "Клетка для дракончика",
				ko = "새끼용 우리",
				cn = "幼兽牢笼",
			},
		},
	
		[245672] = {
			readable = "Whelp Cage",
			model = 1097623,
			text = {
				en = "Whelp Cage",
				es = "Jaula de cría",
				de = "Welpenkäfig",
				fr = "Cage à dragonnet",
				it = "Gabbia dei Draghetti",
				pt = "Jaula de Filhote",
				ru = "Клетка для дракончика",
				ko = "새끼용 우리",
				cn = "幼兽牢笼",
			},
		},
	
		[245676] = {
			readable = "Satyr Cage",
			model = 609081,
			text = {
				en = "Satyr Cage",
				es = "Jaula de sátiro",
				de = "Käfig der Satyrn",
				fr = "Cage à Satyre",
				it = "Gabbia dei Satiri",
				pt = "Jaula de Sátiro",
				ru = "Клетка сатиров",
				ko = "사티로스 우리",
				cn = "萨特牢笼",
			},
		},
	
		[245681] = {
			readable = "Sealed Jar",
			model = 197082,
			text = {
				en = "Sealed Jar",
				es = "Tarro sellado",
				de = "Versiegelter Krug",
				fr = "Jarre scellée",
				it = "Vaso Sigillato",
				pt = "Jarra Fechada",
				ru = "Запечатанный кувшин",
				ko = "밀폐 병",
				cn = "密封的罐子",
			},
		},
	
		[245682] = {
			readable = "Incense Bundle",
			model = 522105,
			text = {
				en = "Incense Bundle",
				es = "Fardo de incienso",
				de = "Räucherwerkbündel",
				fr = "Paquet d’encens",
				it = "Pacchetto di Incenso",
				pt = "Maço de Incenso",
				ru = "Связка благовоний",
				ko = "향 묶음",
				cn = "熏香束",
			},
		},
	
		[245688] = {
			readable = "Shattered Burial Urn",
			icon = 133748,
			model = 1110188,
			text = {
				en = "Shattered Burial Urn",
				es = "Urna funeraria destrozada",
				de = "Zerbrochene Graburne",
				fr = "Urne mortuaire brisée",
				it = "Urna Funeraria Spaccata",
				pt = "Urna Funerária Estilhaçada",
				ru = "Расколотая погребальная урна",
				ko = "조각난 유골 단지",
				cn = "碎裂的骨灰坛",
			},
		},
	
		[245690] = {
			readable = "Catriona's Jewel",
			model = 203112,
			text = {
				en = "Catriona's Jewel",
				es = "Joya de Catriona",
				de = "Catrionas Juwel",
				fr = "Joyau de Catriona",
				it = "Gioiello di Catriona",
				pt = "Joia de Catriona",
				ru = "Самоцвет Катрионы",
				ko = "카트리오나의 보석",
			},
		},
	
		[245691] = {
			readable = "Gem Chips",
			model = 984878,
			text = {
				en = "Gem Chips",
				es = "Trozos de gema",
				de = "Edelsteinsplitter",
				fr = "Éclats de gemmes",
				it = "Pezzetti di Gemma",
				pt = "Fichas de Gemas",
				ru = "Осколки самоцветов",
				ko = "보석 조각",
				cn = "宝石碎片",
			},
		},
	
		[245692] = {
			readable = "Bag of Jewels",
			model = 874403,
			text = {
				en = "Bag of Jewels",
				es = "Bolsa de joyas",
				de = "Juwelenbeutel",
				fr = "Sac de joyaux",
				it = "Sacco di Gioielli",
				pt = "Saco de Joias",
				ru = "Мешочек для драгоценностей",
				ko = "보석 자루",
			},
		},
	
		[245728] = {
			readable = "Sargerite Keystone",
			model = 1273114,
			text = {
				en = "Sargerite Keystone",
				es = "Piedra angular sargerita",
				de = "Sargeritschlüsselstein",
				fr = "Clé sargerite",
				it = "Chiave di Sargeras",
				pt = "Pedra-chave de Sarguerita",
				ru = "Саргеритовый ключ",
				ko = "살게라이트 쐐기돌",
				cn = "萨格里特钥石",
			},
		},
	
		[245785] = {
			readable = "Compass",
			model = 1133882,
			text = {
				en = "Compass",
				es = "Brújula",
				de = "Kompass",
				fr = "Boussole",
				it = "Bussola",
				pt = "Bússola",
				ru = "Компас",
				ko = "나침반",
				cn = "罗盘",
			},
		},
	
		[245786] = {
			readable = "Relic Box",
			model = 942865,
			text = {
				en = "Relic Box",
				es = "Caja de reliquias",
				de = "Reliktschatulle",
				fr = "Boîte à reliques",
				it = "Scatola delle Reliquie",
				pt = "Caixa de Relíquias",
				ru = "Ларец с реликвиями",
				ko = "유물 상자",
				cn = "圣物盒",
			},
		},
	
		[245787] = {
			readable = "Fine Boots",
			model = 936403,
			text = {
				en = "Fine Boots",
				es = "Botas magníficas",
				de = "Hochwertige Stiefel",
				fr = "Belles bottes",
				it = "Stivali Pregiati",
				pt = "Botas Boas",
				ru = "Изящные сапоги",
				ko = "고급 장화",
				cn = "精美的靴子",
			},
		},
	
		[245788] = {
			readable = "Fur Blanket",
			model = 902701,
			text = {
				en = "Fur Blanket",
				es = "Manta de piel",
				de = "Felldecke",
				fr = "Couverture en fourrure",
				it = "Lenzuolo di Pelliccia",
				pt = "Cobertor de Pele",
				ru = "Меховое покрывало",
				ko = "모피 담요",
				cn = "毛毯",
			},
		},
	
		[245789] = {
			readable = "Battered Journal",
			model = 949615,
			text = {
				en = "Battered Journal",
				es = "Diario maltrecho",
				de = "Zerfleddertes Tagebuch",
				fr = "Journal endommagé",
				it = "Diario Rovinato",
				pt = "Diário Surrado",
				ru = "Потрепанный дневник",
				ko = "닳아해진 일지",
				cn = "破碎的日记",
			},
		},
	
		[245791] = {
			readable = "Ancient Chest",
			model = 942843,
			text = {
				en = "Ancient Chest",
				es = "Cofre antiguo",
				de = "Uralte Truhe",
				fr = "Coffre ancien",
				it = "Cassa Antica",
				pt = "Baú Antigo",
				ru = "Древний сундук",
				ko = "고대 궤짝",
				cn = "古代储物箱",
			},
		},
	
		[245792] = {
			readable = "Driftwood",
			model = 1118867,
			text = {
				en = "Driftwood",
				es = "Madera a la deriva",
				de = "Treibholz",
				fr = "Bois flotté",
				it = "Ramo",
				pt = "Madeira Flutuante",
				ru = "Плавник",
				ko = "유목",
				cn = "浮木",
			},
		},
	
		[245793] = {
			readable = "Battered Journal",
			icon = 953644,
			model = 949615,
			text = {
				en = "Battered Journal",
				es = "Diario maltrecho",
				de = "Zerfleddertes Tagebuch",
				fr = "Journal endommagé",
				it = "Diario Rovinato",
				pt = "Diário Surrado",
				ru = "Потрепанный дневник",
				ko = "닳아해진 일지",
				cn = "破碎的日记",
			},
		},
	
		[245794] = {
			readable = "Compass",
			model = 1133882,
			text = {
				en = "Compass",
				es = "Brújula",
				de = "Kompass",
				fr = "Boussole",
				pt = "Bússola",
				ru = "Компас",
				ko = "나침반",
			},
		},
	
		[245843] = {
			readable = "Jabrul's Bag of Jewels",
			model = 977078,
			text = {
				en = "Jabrul's Bag of Jewels",
				es = "Bolsa de joyas de Jabrul",
				de = "Jabruls Juwelentasche",
				fr = "Sac de joyaux de Jabrouf",
				it = "Sacca di Gioielli di Jabrul",
				pt = "Saco de Joias de Jalesk",
				ru = "Мешок самоцветов Джабрула",
				ko = "자브룰의 보석 자루",
				cn = "贾布尔的珠宝袋",
			},
		},
	
		[245847] = {
			readable = "Spoils of the Worthy",
			model = 253445,
			text = {
				en = "Spoils of the Worthy",
				es = "Botín de los dignos",
				de = "Beute der Würdigen",
				fr = "Butin des méritants",
				it = "Spoglie dei Degni",
				pt = "Espólios dos Dignos",
				ru = "Трофеи достойных",
				ko = "자격 있는 자의 전리품",
				cn = "勇士的战利品",
			},
		},
	
		[245849] = {
			readable = "The Svalnguard",
			model = 1132126,
			text = {
				en = "The Svalnguard",
				es = "Guardián de Svaln",
				de = "Der Svalngard",
				fr = "Le Svalngard",
				it = "Scudo di Svaln",
				pt = "Svalngard",
				ru = "Свальнгард",
				cn = "席瓦娜的庇佑",
			},
		},
	
		[245862] = {
			readable = "Skrog Weapons",
			model = 1122159,
			text = {
				en = "Skrog Weapons",
				es = "Armas de skrog",
				de = "Skrogwaffen",
				fr = "Armes skrogs",
				it = "Armi di Skrog",
				pt = "Armas de Skrog",
				ru = "Оружие скрогов",
				ko = "거인 무기",
				cn = "海巨人武器",
			},
		},
	
		[245883] = {
			readable = "Ley Portal",
			model = 166523,
			text = {
				en = "Ley Portal",
				es = "Portal Ley",
				de = "Leyportal",
				fr = "Portail tellurique",
				it = "Portale della Faglia",
				pt = "Portal Meridional",
				ru = "Силовой портал",
				ko = "지맥 차원문",
				cn = "魔网传送门",
			},
		},
	
		[245887] = {
			readable = "Driftwood",
			model = 1258388,
			text = {
				en = "Driftwood",
				es = "Madera a la deriva",
				de = "Treibholz",
				fr = "Bois flotté",
				it = "Ramo",
				pt = "Madeira Flutuante",
				ru = "Плавник",
				ko = "유목",
				cn = "浮木",
			},
		},
	
		[245924] = {
			readable = "Tome of Blighted Implements",
			model = 1125315,
			text = {
				en = "Tome of Blighted Implements",
				es = "Escrito sobre artilugios malditos",
				de = "Foliant der verseuchten Instrumente",
				fr = "Grimoire des reliques interdites",
				it = "Tomo degli Strumenti della Rovina",
				pt = "Tomo dos Implementos Pestilentos",
				ru = "Фолиант орудий погибели",
				ko = "황폐화 도구의 고서",
				cn = "毁灭利器之书",
			},
		},
	
		[245925] = {
			readable = "Garden",
			model = 1352479,
			text = {
				en = "Garden",
				es = "Jardín",
				de = "Garten",
				fr = "Jardin",
				it = "Giardino",
				pt = "Jardim",
				ru = "Сад",
				ko = "정원",
				cn = "花园",
			},
		},
	
		[245926] = {
			readable = "Library",
			model = 1352479,
			text = {
				en = "Library",
				es = "Biblioteca",
				de = "Bibliothek",
				fr = "Bibliothèque",
				it = "Biblioteca",
				pt = "Biblioteca",
				ru = "Библиотека",
				ko = "도서관",
				cn = "图书馆",
			},
		},
	
		[245927] = {
			readable = "Warp Lab",
			model = 1352476,
			text = {
				en = "Warp Lab",
				es = "Laboratorio de distorsión",
				de = "Warplabor",
				fr = "Laboratoire dimensionnel",
				it = "Laboratorio di Distorsione",
				pt = "Laboratório Dimensional",
				ru = "Лаборатория искажений",
				ko = "차원 연구실",
				cn = "迁跃实验室",
			},
		},
	
		[245928] = {
			readable = "Workshop",
			model = 1352477,
			text = {
				en = "Workshop",
				es = "Taller",
				de = "Werkstatt",
				fr = "Atelier",
				it = "Officina",
				pt = "Oficina",
				ru = "Мастерская",
				ko = "연구소",
				cn = "工作室",
			},
		},
	
		[245931] = {
			readable = "Storage",
			model = 1352477,
			text = {
				en = "Storage",
				es = "Almacenamiento",
				de = "Lager",
				fr = "Remise",
				it = "Magazzino",
				pt = "Armazenamento",
				ru = "Склад",
				cn = "储藏室",
			},
		},
	
		[245932] = {
			readable = "Garden",
			model = 1352478,
			text = {
				en = "Garden",
				es = "Jardín",
				de = "Garten",
				fr = "Jardin",
				it = "Giardino",
				pt = "Jardim",
				ru = "Сад",
				ko = "정원",
				cn = "花园",
			},
		},
	
		[245934] = {
			readable = "Heart of Zin-Azshari",
			model = 537792,
			text = {
				en = "Heart of Zin-Azshari",
				es = "Corazón de Zin-Azshari",
				de = "Herz von Zin-Azshari",
				fr = "Cœur de Zin-Azshari",
				it = "Cuore di Zin-Azshari",
				pt = "Coração de Zin-Azshari",
				ru = "Сердце Зин-Азшари",
				cn = "辛艾萨莉之心",
			},
		},
	
		[245935] = {
			readable = "Adamantium Casing Scrap",
			model = 381031,
			text = {
				en = "Adamantium Casing Scrap",
				es = "Trozo de revestimiento de adamantio",
				de = "Adamantiumplattenschrott",
				fr = "Débris de coffre en adamantium",
				it = "Frammento della Copertura d'Adamantio",
				pt = "Restos de Cápsula de Adamântio",
				ru = "Обломки адамантовой брони",
				cn = "合金镀层残片",
			},
		},
	
		[245936] = {
			readable = "Adamantium Casing Scrap",
			model = 381034,
			text = {
				en = "Adamantium Casing Scrap",
				es = "Trozo de revestimiento de adamantio",
				de = "Adamantiumplattenschrott",
				fr = "Débris de coffre en adamantium",
				it = "Frammento della Copertura d'Adamantio",
				pt = "Restos de Cápsula de Adamântio",
				ru = "Обломок адамантовой брони",
				cn = "合金镀层残片",
			},
		},
	
		[245937] = {
			readable = "Adamantium Casing Scrap",
			model = 381032,
			text = {
				en = "Adamantium Casing Scrap",
				es = "Trozo de revestimiento de adamantio",
				de = "Adamantiumplattenschrott",
				fr = "Débris de coffre en adamantium",
				it = "Frammento della Copertura d'Adamantio",
				pt = "Restos de Cápsula de Adamântio",
				ru = "Обломок адамантовой брони",
				cn = "合金镀层残片",
			},
		},
	
		[245938] = {
			readable = "Adamantium Casing Scrap",
			model = 381035,
			text = {
				en = "Adamantium Casing Scrap",
				es = "Trozo de revestimiento de adamantio",
				de = "Adamantiumplattenschrott",
				fr = "Débris de coffre en adamantium",
				it = "Frammento della Copertura d'Adamantio",
				pt = "Restos de Cápsula de Adamântio",
				ru = "Обломок адамантовой брони",
				cn = "合金镀层残片",
			},
		},
	
		[245940] = {
			readable = "Fel-Infused Plate",
			model = 455589,
			text = {
				en = "Fel-Infused Plate",
				es = "Placa imbuida de vileza",
				de = "Teufelsgeladene Platte",
				fr = "Plaque gangrimprégnée",
				it = "Piastra Vilinfusa",
				pt = "Placas Vis Infusas",
				ru = "Пронизанная Скверной обшивка",
				ko = "지옥 마력이 주입된 판금",
				cn = "灌魔金属板",
			},
		},
	
		[245941] = {
			readable = "Warp Cache",
			model = 1349622,
			text = {
				en = "Warp Cache",
				es = "Alijo de distorsión",
				de = "Warpspeicher",
				fr = "Cache dimensionnelle",
				it = "Cassa Distorcente",
				pt = "Fardo Dimensional",
				ru = "Искаженный тайник",
				cn = "扭曲的箱子",
			},
		},
	
		[245942] = {
			readable = "Garden",
			model = 1352478,
			text = {
				en = "Garden",
				es = "Jardín",
				de = "Garten",
				fr = "Jardin",
				it = "Giardino",
				pt = "Jardim",
				ru = "Сад",
				ko = "정원",
				cn = "花园",
			},
		},
	
		[245943] = {
			readable = "Eye of Nashal",
			model = 1282665,
			text = {
				en = "Eye of Nashal",
				es = "Ojo de Nashal",
				de = "Auge von Nashal",
				fr = "Œil de Nashal",
				pt = "Olho de Nashal",
				ru = "Глаз Нашала",
			},
		},
	
		[245944] = {
			readable = "Eye of Nashal",
			model = 1282667,
			text = {
				en = "Eye of Nashal",
				es = "Ojo de Nashal",
				de = "Auge von Nashal",
				fr = "Œil de Nashal",
				it = "Occhio di Nashal",
				ru = "Глаз Нашала",
			},
		},
	
		[245945] = {
			readable = "Eye of Nashal",
			model = 1282669,
			text = {
				en = "Eye of Nashal",
				de = "Auge von Nashal",
				fr = "Œil de Nashal",
				it = "Occhio di Nashal",
				pt = "Olho de Nashal",
				ru = "Глаз Нашала",
			},
		},
	
		[245947] = {
			readable = "Telemetry Lab",
			model = 1352477,
			text = {
				en = "Telemetry Lab",
				es = "Laboratorio de telemetría",
				de = "Telemetrielabor",
				fr = "Laboratoire de télémétrie",
				it = "Laboratorio di Telemetria",
				pt = "Laboratório Telemétrico",
				ru = "Лаборатория телеметрии",
				ko = "원격 신호 연구실",
				cn = "遥测实验室",
			},
		},
	
		[245948] = {
			readable = "Breakfast Nook",
			model = 1352476,
			text = {
				en = "Breakfast Nook",
				es = "Rincón del desayuno",
				de = "Essecke",
				fr = "Coin petit-déjeuner",
				it = "Nicchia per la Colazione",
				pt = "Cantinho do Café",
				ru = "Столовая",
				ko = "아침 식사 장소",
				cn = "早餐区",
			},
		},
	
		[245950] = {
			readable = "Fountain",
			model = 1352477,
			text = {
				en = "Fountain",
				es = "Fuente",
				de = "Brunnen",
				fr = "Fontaine",
				it = "Fontana",
				pt = "Fonte",
				ru = "Фонтан",
				ko = "샘",
				cn = "喷泉",
			},
		},
	
		[245954] = {
			readable = "Fountain",
			model = 1352477,
			text = {
				en = "Fountain",
				es = "Fuente",
				de = "Brunnen",
				fr = "Fontaine",
				it = "Fontana",
				pt = "Fonte",
				ru = "Фонтан",
				ko = "샘",
				cn = "喷泉",
			},
		},
	
		[245960] = {
			readable = "Dragon Glass",
			model = 370350,
			text = {
				en = "Dragon Glass",
				es = "Cristal de dragón",
				de = "Drachenglas",
				fr = "Verre draconique",
				it = "Vetro di Drago",
				pt = "Vidro de Dragão",
				ru = "Драконье стекло",
			},
		},
	
		[245967] = {
			readable = "Inconspicuous Crate",
			model = 850517,
			text = {
				en = "Inconspicuous Crate",
				es = "Cajón inadvertido",
				de = "Unscheinbare Kiste",
				fr = "Caisse anodine",
				it = "Cassa Incospicua",
				pt = "Caixote Inconspícuo",
				ru = "Не вызывающий подозрений ящик",
			},
		},
	
		[245994] = {
			readable = "Ulthalesh, the Deadwind Harvester",
			model = 1346368,
			text = {
				en = "Ulthalesh, the Deadwind Harvester",
				es = "Ulthalesh, la Cosechadora Vientomuerto",
				de = "Ulthalesh, Sense der Totenwinde",
				fr = "Ulthalesh, la faux de Deuillevent",
				pt = "Ulthalesh, a Ceifadora do Vento Morto",
				ru = "Ултхалеш, Жнец Мертвого Ветра",
				ko = "울타레쉬 - 저승바람 수확기",
			},
		},
	
		[245995] = {
			readable = "Spire Stabilizer",
			model = 1243753,
			text = {
				en = "Spire Stabilizer",
				es = "Estabilizador de púa",
				de = "Pfeilerstabilisator",
				fr = "Stabilisateur de flèche",
				it = "Stabilizzatore della Spira",
				pt = "Estabilizador da Torre",
				ru = "Стабилизатор шпиля",
				ko = "첨탑 안정기",
				cn = "尖塔稳定器",
			},
		},
	
		[245996] = {
			readable = "Small Treasure Chest",
			icon = 308482,
			model = 1349995,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[245997] = {
			readable = "Portal to Darnassus",
			model = 197042,
			text = {
				en = "Portal to Darnassus",
				es = "Portal a Darnassus",
				de = "Portal nach Darnassus",
				fr = "Portail vers Darnassus",
				it = "Portale per Darnassus",
				pt = "Portal para Darnassus",
				ru = "Портал в Дарнас",
				ko = "다르나서스로 통하는 차원문",
				cn = "通往达纳苏斯的传送门",
			},
		},
	
		[245998] = {
			readable = "Portal to Ironforge",
			model = 197044,
			text = {
				en = "Portal to Ironforge",
				es = "Portal a Forjaz",
				de = "Portal nach Eisenschmiede",
				fr = "Portail vers Forgefer",
				it = "Portale per Forgiardente",
				pt = "Portal para Altaforja",
				ru = "Портал в Стальгорн",
				ko = "아이언포지로 통하는 차원문",
				cn = "通往铁炉堡的传送门",
			},
		},
	
		[245999] = {
			readable = "Portal to Thunder Bluff",
			model = 197054,
			text = {
				en = "Portal to Thunder Bluff",
				es = "Portal a Cima del Trueno",
				de = "Portal nach Donnerfels",
				fr = "Portail vers les Pitons-du-Tonnerre",
				it = "Portale per Picco del Tuono",
				pt = "Portal para Penhasco do Trovão",
				ru = "Портал в Громовой Утес",
				ko = "썬더 블러프로 통하는 차원문",
				cn = "通往雷霆崖的传送门",
			},
		},
})
do ObjectDB[objectID] = objectData; end
