local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	
		[301073] = {
			readable = "Tales of de Loa: Akunda",
			model = 1830359,
			text = {
				en = "Tales of de Loa: Akunda",
				es = "Historias de los loa: Akunda",
				de = "Legend'n der Loa: Akunda",
				fr = "Contes des Loas : Akunda",
				it = "Storie dei Loa: Akunda",
				pt = "Contos dos Loas: Akunda",
				ru = "Легенды лоа: Акунда",
				ko = "로아의 이야기: 아쿤다",
				cn = "洛阿神灵传说：阿昆达",
			},
		},
	
		[301074] = {
			readable = "Tales of de Loa: Bwonsamdi",
			model = 1726753,
			text = {
				en = "Tales of de Loa: Bwonsamdi",
				es = "Historias de los loa: Bwonsamdi",
				de = "Legend'n der Loa: Bwonsamdi",
				fr = "Contes des Loas : Bwonsamdi",
				it = "Storie dei Loa: Bwonsamdi",
				pt = "Contos dos Loas: Bwonsamdi",
				ru = "\"Легенды лоа: Бвонсамди\"",
				ko = "로아의 이야기: 브원삼디",
				cn = "洛阿神灵传说：邦桑迪",
			},
		},
	
		[301075] = {
			readable = "Tales of de Loa: Gonk",
			model = 774269,
			text = {
				en = "Tales of de Loa: Gonk",
				es = "Historias de los loa: Gonk",
				de = "Legend'n der Loa: Gonk",
				fr = "Contes des Loas : Gonk",
				it = "Storie dei Loa: Gonk",
				pt = "Contos dos Loas: Gonk",
				ru = "\"Легенды лоа: Гонк\"",
				ko = "로아의 이야기: 공크",
				cn = "洛阿神灵传说：贡克",
			},
		},
	
		[301076] = {
			readable = "Tales of de Loa: Gral",
			model = 1726769,
			text = {
				en = "Tales of de Loa: Gral",
				es = "Historias de los loa: Gral",
				de = "Legend'n der Loa: Gral",
				fr = "Contes des Loas : Gral",
				it = "Storie dei Loa: Gral",
				pt = "Contos dos Loas: Gral",
				ru = "\"Легенды лоа: Грал\"",
				ko = "로아의 이야기: 그랄",
				cn = "洛阿神灵传说：格罗尔",
			},
		},
	
		[301077] = {
			readable = "Tales of de Loa: Hir'eek",
			model = 774267,
			text = {
				en = "Tales of de Loa: Hir'eek",
				es = "Historias de los loa: Hir'eek",
				de = "Legend'n der Loa: Hir'eek",
				fr = "Contes des Loas : Hir’eek",
				it = "Storie dei Loa: Hir'eek",
				pt = "Contos dos Loas: Hir'eek",
				ru = "\"Легенды лоа: Хир'ик\"",
				ko = "로아의 이야기: 히르이크",
				cn = "洛阿神灵传说：希里克",
			},
		},
	
		[301078] = {
			readable = "Tales of de Loa: Jani",
			model = 974983,
			text = {
				en = "Tales of de Loa: Jani",
				es = "Historias de los loa: Jani",
				de = "Legend'n der Loa: Jani",
				fr = "Contes des Loas : Jani",
				it = "Storie dei Loa: Jani",
				pt = "Contos dos Loas: Jani",
				ru = "\"Легенды лоа: Джани\"",
				ko = "로아의 이야기: 자니",
				cn = "洛阿神灵传说：加尼",
			},
		},
	
		[301079] = {
			readable = "Tales of de Loa: Kimbul",
			model = 774267,
			text = {
				en = "Tales of de Loa: Kimbul",
				es = "Historias de los loa: Kimbul",
				de = "Legend'n der Loa: Kimbul",
				fr = "Contes des Loas : Kimbul",
				it = "Storie dei Loa: Kimbul",
				pt = "Contos dos Loas: Kimbul",
				ru = "\"Легенды лоа: Кимбул\"",
				ko = "로아의 이야기: 킴불",
			},
		},
	
		[301080] = {
			readable = "Tales of de Loa: Krag'wa",
			model = 1726769,
			text = {
				en = "Tales of de Loa: Krag'wa",
				es = "Historias de los loa: Krag'wa",
				de = "Legend'n der Loa: Krag'wa",
				fr = "Contes des Loas : Krag’wa",
				it = "Storie dei Loa: Krag'wa",
				pt = "Contos dos Loas: Krag'wa",
				ru = "\"Легенды лоа: Краг'ва\"",
				ko = "로아의 이야기: 크라그와",
				cn = "洛阿神灵传说：卡格瓦",
			},
		},
	
		[301081] = {
			readable = "Tales of de Loa: Pa'ku",
			model = 774271,
			text = {
				en = "Tales of de Loa: Pa'ku",
				es = "Historias de los loa: Pa'ku",
				de = "Legend'n der Loa: Pa'ku",
				fr = "Contes des Loas : Pa’ku",
				it = "Storie dei Loa: Pa'ku",
				pt = "Contos dos Loas: Pa'kul",
				ru = "\"Легенды лоа: Па'ку\"",
				ko = "로아의 이야기: 파쿠",
				cn = "洛阿神灵传说：帕库",
			},
		},
	
		[301082] = {
			readable = "Tales of de Loa: Rezan",
			model = 1726777,
			text = {
				en = "Tales of de Loa: Rezan",
				es = "Historias de los loa: Rezan",
				de = "Legend'n der Loa: Rezan",
				fr = "Contes des Loas : Rezan",
				it = "Storie dei Loa: Rezan",
				pt = "Contos dos Loas: Rezan",
				ru = "\"Легенды лоа: Резан\"",
				ko = "로아의 이야기: 레잔",
				cn = "洛阿神灵传说：莱赞",
			},
		},
	
		[301083] = {
			readable = "Tales of de Loa: Sethraliss",
			model = 1624533,
			text = {
				en = "Tales of de Loa: Sethraliss",
				es = "Historias de los loa: Sethraliss",
				de = "Legend'n der Loa: Sethraliss",
				fr = "Contes des Loas : Sephraliss",
				it = "Storie dei Loa: Sethraliss",
				pt = "Contos dos Loas: Sethraliss",
				ru = "\"Легенды лоа: Сетралисс\"",
				ko = "로아의 이야기: 세스랄리스",
			},
		},
	
		[301084] = {
			readable = "Tales of de Loa: Shadra",
			model = 1726753,
			text = {
				en = "Tales of de Loa: Shadra",
				es = "Historias de los loa: Shadra",
				de = "Legend'n der Loa: Shadra",
				fr = "Contes des Loas : Shadra",
				it = "Storie dei Loa: Shadra",
				pt = "Contos dos Loas: Shadra",
				ru = "\"Легенды лоа: Шадра\"",
				ko = "로아의 이야기: 샤드라",
				cn = "洛阿神灵传说：沙德拉",
			},
		},
	
		[301085] = {
			readable = "Tales of de Loa: Zandalar",
			model = 774269,
			text = {
				en = "Tales of de Loa: Zandalar",
				es = "Historias de los loa: Zandalar",
				de = "Legend'n der Loa: Zandalar",
				fr = "Contes des Loas : Zandalar",
				it = "Storie dei Loa: Zandalar",
				pt = "Contos dos Loas: Zandalar",
				ru = "\"Легенды лоа: Зандалар\"",
				ko = "로아의 이야기: 잔달라",
				cn = "洛阿神灵传说：赞达拉",
			},
		},
	
		[301086] = {
			readable = "Tales of de Loa: Torga",
			model = 774273,
			text = {
				en = "Tales of de Loa: Torga",
				es = "Historias de los loa: Torga",
				de = "Legend'n der Loa: Torga",
				fr = "Contes des Loas : Torga",
				it = "Storie dei Loa: Torga",
				pt = "Contos dos Loas: Torga",
				ru = "\"Легенды лоа: Торга\"",
				ko = "로아의 이야기: 토르가",
				cn = "洛阿神灵传说：托加",
			},
		},
	
		[301087] = {
			readable = "Tales of de Loa: Torcali",
			model = 774273,
			text = {
				en = "Tales of de Loa: Torcali",
				es = "Historias de los loa: Torcali",
				de = "Legend'n der Loa: Torcali",
				fr = "Contes des Loas : Torcali",
				it = "Storie dei Loa: Torcali",
				pt = "Contos dos Loas: Torcali",
				ru = "\"Легенды лоа: Торкали\"",
				ko = "로아의 이야기: 토르칼리",
				cn = "洛阿神灵传说：托卡利",
			},
		},
	
		[301296] = {
			readable = "Monument of Franclorn Forgewright",
			model = 203024,
			text = {
				en = "Monument of Franclorn Forgewright",
				es = "Monumento a Franclorn Forjador",
				de = "Denkmal für Franclorn Schmiedevater",
				fr = "Monument de Franclorn Le Forgebusier",
				it = "Monumento a Franclorn Forgiabruna",
				pt = "Monumento a Franclorn Forjífice",
				ru = "Монумент Франклорну Искуснику",
				ko = "프랑클론 포지라이트의 기념비",
				cn = "弗兰克罗恩·铸铁的雕像",
			},
		},
	
		[301544] = {
			readable = "Collision Wall",
			model = 1883494,
			text = {
				en = "Collision Wall",
				es = "Muro de colisión",
				de = "Kollisionswand",
				fr = "Mur de collision",
				it = "Muro di Collisione",
				pt = "Parede de Colisão",
				ko = "충돌 벽",
				cn = "碰撞墙",
			},
		},
	
		[302718] = {
			readable = "Heavy Chain",
			model = 315404,
			text = {
				en = "Heavy Chain",
				es = "Cadena pesada",
				de = "Schwere Kette",
				fr = "Lourde chaîne",
				it = "Catene Pesanti",
				pt = "Corrente Pesada",
				ru = "Массивная цепь",
				ko = "무거운 사슬",
			},
		},
	
		[302748] = {
			readable = "War Supply Chest",
			model = 341870,
			text = {
				en = "War Supply Chest",
				de = "Kiste mit Kriegsvorräten",
				fr = "Coffre de fournitures de guerre",
				ru = "Сундук с военными припасами",
			},
		},
	
		[302749] = {
			readable = "War Supply Chest",
			model = 341746,
			text = {
				en = "War Supply Chest",
				es = "Cofre de suministros de guerra",
				de = "Kiste mit Kriegsvorräten",
				fr = "Coffre de fournitures de guerre",
				ru = "Сундук с военными припасами",
			},
		},
	
		[302765] = {
			readable = "Smoldering Brazier",
			model = 202204,
			text = {
				en = "Smoldering Brazier",
				es = "Blandón humeante",
				de = "Schwelende Kohlenpfanne",
				fr = "Brasero fumant",
				it = "Braciere Infuocato",
				pt = "Braseiro Fumegante",
				ru = "Тлеющая жаровня",
				ko = "이글거리는 화로",
				cn = "冒烟的火盆",
			},
		},
	
		[302770] = {
			readable = "Lost Supplies",
			model = 1602311,
			text = {
				en = "Lost Supplies",
				es = "Provisiones extraviadas",
				de = "Verlorene Vorräte",
				fr = "Fournitures perdues",
				it = "Rifornimenti Perduti",
				pt = "Suprimentos Perdidos",
				ru = "Потерянные припасы",
				ko = "잃어버린 보급품",
				cn = "遗失的货物",
			},
		},
	
		[302771] = {
			readable = "Ancient Tidesage Scroll",
			model = 1931969,
			text = {
				en = "Ancient Tidesage Scroll",
				es = "Pergamino antiguo de Sabiomar",
				de = "Uralte Schriftrolle der Gezeitenweisen",
				fr = "Parchemin d’eaugure ancien",
				it = "Antica Pergamena dei Saggi delle Maree",
				pt = "Pergaminho de Sábio das Marés Ancestral",
				ru = "Древний свиток жрецов моря",
				ko = "고대 파도현자 두루마리",
				cn = "古代海潮贤者卷轴",
			},
		},
	
		[302772] = {
			readable = "Ancient Tidesage Scroll",
			model = 1931970,
			text = {
				en = "Ancient Tidesage Scroll",
				es = "Pergamino antiguo de Sabiomar",
				de = "Uralte Schriftrolle der Gezeitenweisen",
				fr = "Parchemin d’eaugure ancien",
				it = "Antica Pergamena dei Saggi delle Maree",
				pt = "Pergaminho de Sábio das Marés Ancestral",
				ru = "Древний свиток жрецов моря",
				ko = "고대 파도현자 두루마리",
				cn = "古代海潮贤者卷轴",
			},
		},
	
		[302773] = {
			readable = "Ancient Tidesage Scroll",
			model = 1931969,
			text = {
				en = "Ancient Tidesage Scroll",
				es = "Pergamino antiguo de Sabiomar",
				de = "Uralte Schriftrolle der Gezeitenweisen",
				fr = "Parchemin d’eaugure ancien",
				it = "Antica Pergamena dei Saggi delle Maree",
				pt = "Pergaminho de Sábio das Marés Ancestral",
				ru = "Древний свиток жрецов моря",
				ko = "고대 파도현자 두루마리",
				cn = "古代海潮贤者卷轴",
			},
		},
	
		[302774] = {
			readable = "Ancient Tidesage Scroll",
			model = 1931970,
			text = {
				en = "Ancient Tidesage Scroll",
				es = "Pergamino antiguo de Sabiomar",
				de = "Uralte Schriftrolle der Gezeitenweisen",
				fr = "Parchemin d’eaugure ancien",
				it = "Antica Pergamena dei Saggi delle Maree",
				pt = "Pergaminho de Sábio das Marés Ancestral",
				ru = "Древний свиток жрецов моря",
				ko = "고대 파도현자 두루마리",
				cn = "古代海潮贤者卷轴",
			},
		},
	
		[302775] = {
			readable = "Ancient Tidesage Scroll",
			model = 1931970,
			text = {
				en = "Ancient Tidesage Scroll",
				es = "Pergamino antiguo de Sabiomar",
				de = "Uralte Schriftrolle der Gezeitenweisen",
				fr = "Parchemin d’eaugure ancien",
				it = "Antica Pergamena dei Saggi delle Maree",
				pt = "Pergaminho de Sábio das Marés Ancestral",
				ru = "Древний свиток жрецов моря",
				ko = "고대 파도현자 두루마리",
				cn = "古代海潮贤者卷轴",
			},
		},
	
		[302776] = {
			readable = "Ancient Tidesage Scroll",
			model = 1931969,
			text = {
				en = "Ancient Tidesage Scroll",
				es = "Pergamino antiguo de Sabiomar",
				de = "Uralte Schriftrolle der Gezeitenweisen",
				fr = "Parchemin d’eaugure ancien",
				it = "Antica Pergamena dei Saggi delle Maree",
				pt = "Pergaminho de Sábio das Marés Ancestral",
				ru = "Древний свиток жрецов моря",
				ko = "고대 파도현자 두루마리",
				cn = "古代海潮贤者卷轴",
			},
		},
	
		[302777] = {
			readable = "Ancient Tidesage Scroll",
			model = 1931969,
			text = {
				en = "Ancient Tidesage Scroll",
				es = "Pergamino antiguo de Sabiomar",
				de = "Uralte Schriftrolle der Gezeitenweisen",
				fr = "Parchemin d’eaugure ancien",
				it = "Antica Pergamena dei Saggi delle Maree",
				pt = "Pergaminho de Sábio das Marés Ancestral",
				ru = "Древний свиток жрецов моря",
				ko = "고대 파도현자 두루마리",
				cn = "古代海潮贤者卷轴",
			},
		},
	
		[302778] = {
			readable = "Ancient Tidesage Scroll",
			model = 1931970,
			text = {
				en = "Ancient Tidesage Scroll",
				es = "Pergamino antiguo de Sabiomar",
				de = "Uralte Schriftrolle der Gezeitenweisen",
				fr = "Parchemin d’eaugure ancien",
				it = "Antica Pergamena dei Saggi delle Maree",
				pt = "Pergaminho de Sábio das Marés Ancestral",
				ru = "Древний свиток жрецов моря",
				ko = "고대 파도현자 두루마리",
				cn = "古代海潮贤者卷轴",
			},
		},
	
		[302779] = {
			readable = "Bloody Banner",
			model = 1695385,
			text = {
				en = "Bloody Banner",
				es = "Estandarte sangriento",
				de = "Blutiges Banner",
				fr = "Bannière ensanglantée",
				it = "Stendardo Insanguinato",
				pt = "Estandarte Ensanguentado",
				ru = "Кровавое знамя",
				ko = "피투성이 깃발",
				cn = "血腥旗帜",
			},
		},
	
		[302780] = {
			readable = "Rope Ladder",
			model = 198421,
			text = {
				en = "Rope Ladder",
				es = "Escala de cuerda",
				de = "Strickleiter",
				fr = "Échelle de corde",
				it = "Scala di Corda",
				pt = "Escada de Corda",
				ru = "Веревочная лестница",
				ko = "밧줄 사다리",
				cn = "绳梯",
			},
		},
	
		[302854] = {
			readable = "Portal to Boralus",
			model = 2123273,
			text = {
				en = "Portal to Boralus",
				es = "Portal a Boralus",
				de = "Portal nach Boralus",
				fr = "Portail vers Boralus",
				it = "Portale per Boralus",
				pt = "Portal para Boralus",
				ru = "Портал в Боралус",
				ko = "보랄러스로 통하는 차원문",
				cn = "通往伯拉勒斯的传送门",
			},
		},
	
		[302855] = {
			readable = "Portal to Dazar'alor",
			model = 2123281,
			text = {
				en = "Portal to Dazar'alor",
				es = "Portal a Dazar'alor",
				de = "Portal nach Dazar'alor",
				fr = "Portail vers Dazar’alor",
				it = "Portale per Dazar'alor",
				pt = "Portal para Dazar'alor",
				ru = "Портал в Дазар'алор",
				ko = "다자알로로 통하는 차원문",
				cn = "前往达萨罗的传送门",
			},
		},
	
		[302939] = {
			readable = "Intact Mudfish",
			model = 1091574,
			text = {
				en = "Intact Mudfish",
				es = "Pez de barro intacto",
				de = "Intakter Matschflosser",
				fr = "Éperlan intact",
				it = "Pescefango Intatto",
				pt = "Muçum Intacto",
				ru = "Нетронутая ильница",
				cn = "完整的泥鱼",
			},
		},
	
		[302954] = {
			readable = "Blacktooth Brawler Stash",
			model = 2123117,
			text = {
				en = "Blacktooth Brawler Stash",
				es = "Alijo de camorrista Dientenegro",
				de = "Vorratskiste der Schwarzzahnvandalen",
				fr = "Planque des Mort-aux-Dents",
				it = "Scorta del Filibustiere Dentineri",
				pt = "Depósito do Brigão Dentenegro",
				ru = "Тайник братства Чернозубых",
				ko = "검은이빨 난투꾼 보관함",
			},
		},
	
		[302955] = {
			readable = "Dusty Marine Supplies",
			model = 1806321,
			text = {
				en = "Dusty Marine Supplies",
				es = "Suministros marinos polvorientos",
				de = "Staubige Schiffsvorräte",
				fr = "Fournitures de soldat de marine poussiéreuses",
				it = "Rifornimenti del Soldato Polverosi",
				pt = "Suprimentos Navais Empoeirados",
				ru = "Пыльные корабельные припасы",
				ko = "먼지투성이 해병 보급품",
				cn = "尘封的海军物资",
			},
		},
	
		[302977] = {
			readable = "Wisp Wall",
			model = 2136113,
			text = {
				en = "Wisp Wall",
				de = "Irrwischbarriere",
				fr = "Mur de feux follets",
				ru = "Стена огоньков",
			},
		},
	
		[303016] = {
			readable = "|cFFFFFFFFStep 14:|r Ordinary Pebble XIII",
			icon = 135242,
			model = 1068320,
			text = {
				en = "|cFFFFFFFFStep 14:|r Ordinary Pebble XIII",
				es = "|cFFFFFFFFStep 14:|r Piedra corriente XIII",
				de = "|cFFFFFFFFSchritt 14:|r Gewöhnlicher Kieselstein XIII",
				fr = "|cFFFFFFFFÉtape 14:|r Caillou ordinaire XIII",
				it = "|cFFFFFFFFStep 14:|r Sasso Comune XIII",
				pt = "|cFFFFFFFFStep 14:|r Cascalho Comum XIII",
				ru = "|cFFFFFFFFШаг 14:|r Обычный камешек XIII",
				ko = "|cFFFFFFFFStep 14:|r 평범한 조약돌 XIII",
				cn = "|cFFFFFFFF第14步:|r 普通的卵石 XIII",
			},
		},
	
		[303017] = {
			readable = "|cFFFFFFFFStep 13:|r Ordinary Pebble XII",
			icon = 135242,
			model = 1068320,
			text = {
				en = "|cFFFFFFFFStep 13:|r Ordinary Pebble XII",
				es = "|cFFFFFFFFStep 13:|r Piedra corriente XII",
				de = "|cFFFFFFFFSchritt 13:|r Gewöhnlicher Kieselstein XII",
				fr = "|cFFFFFFFFÉtape 13:|r Caillou ordinaire XII",
				it = "|cFFFFFFFFStep 13:|r Sasso Comune XII",
				pt = "|cFFFFFFFFStep 13:|r Cascalho Comum XII",
				ru = "|cFFFFFFFFШаг 13:|r Обычный камешек XII",
				ko = "|cFFFFFFFFStep 13:|r 평범한 조약돌 XII",
				cn = "|cFFFFFFFF第13步:|r 普通的卵石 XII",
			},
		},
	
		[303018] = {
			readable = "|cFFFFFFFFStep 12:|r Ordinary Pebble XI",
			icon = 135242,
			model = 1068320,
			text = {
				en = "|cFFFFFFFFStep 12:|r Ordinary Pebble XI",
				es = "|cFFFFFFFFStep 12:|r Piedra corriente XI",
				de = "|cFFFFFFFFSchritt 12:|r Gewöhnlicher Kieselstein XI",
				fr = "|cFFFFFFFFÉtape 12:|r Caillou ordinaire XI",
				it = "|cFFFFFFFFStep 12:|r Sasso Comune XI",
				pt = "|cFFFFFFFFStep 12:|r Cascalho Comum XI",
				ru = "|cFFFFFFFFШаг 12:|r Обычный камешек XI",
				ko = "|cFFFFFFFFStep 12:|r 평범한 조약돌 XI",
				cn = "|cFFFFFFFF第12步:|r 普通的卵石 XI",
			},
		},
	
		[303025] = {
			readable = "Doodad_6HU_BLACKSMITH_ANVIL001",
			model = 929334,
			text = {
				en = "Doodad_6HU_BLACKSMITH_ANVIL001",
			},
		},
	
		[303026] = {
			readable = "Doodad_6HU_BLACKSMITH_ANVIL002",
			model = 929334,
			text = {
				en = "Doodad_6HU_BLACKSMITH_ANVIL002",
			},
		},
	
		[303039] = {
			readable = "Curious Grain Sack",
			model = 1305115,
			text = {
				en = "Curious Grain Sack",
				es = "Saco de grano curioso",
				de = "Seltsamer Getreidesack",
				fr = "Sac de grain étrange",
				it = "Sacco di Grano Curioso",
				pt = "Saco de Grãos Curioso",
				ru = "Странный мешок с зерном",
				ko = "이상한 곡식 자루",
				cn = "奇怪的谷物袋",
			},
		},
	
		[303072] = {
			readable = "Rope Ladder",
			model = 198421,
			text = {
				en = "Rope Ladder",
				es = "Escala de cuerda",
				de = "Strickleiter",
				fr = "Échelle de corde",
				it = "Scala di Corda",
				pt = "Escada de Corda",
				ru = "Веревочная лестница",
				ko = "밧줄 사다리",
				cn = "绳梯",
			},
		},
	
		[303142] = {
			readable = "Derek Proudmoore",
			model = 970107,
			text = {
				en = "Derek Proudmoore",
				es = "Derek Valiente",
				de = "Derek Prachtmeer",
				fr = "Derek Portvaillant",
				it = "Derek Marefiero",
				pt = "Derek Proudmore",
				ru = "Дерек Праудмур",
				ko = "데렉 프라우드무어",
				cn = "德里克·普罗德摩尔",
			},
		},
	
		[303143] = {
			readable = "Tandred Proudmoore",
			model = 970107,
			text = {
				en = "Tandred Proudmoore",
				es = "Tandred Valiente",
				de = "Tandred Prachtmeer",
				fr = "Tandred Portvaillant",
				it = "Tandred Marefiero",
				pt = "Tandred Proudmore",
				ru = "Тандред Праудмур",
				ko = "탄드레드 프라우드무어",
				cn = "坦德雷·普罗德摩尔",
			},
		},
	
		[303144] = {
			readable = "Portal to Stormwind",
			model = 197051,
			text = {
				en = "Portal to Stormwind",
				es = "Portal a Ventormenta",
				de = "Portal nach Sturmwind",
				fr = "Portail vers Hurlevent",
				it = "Portale per Roccavento",
				pt = "Portal para Ventobravo",
				ru = "Портал в Штормград",
			},
		},
	
		[303148] = {
			readable = "Soulwell",
			model = 2202403,
			text = {
				en = "Soulwell",
				es = "Pozo de alma",
				de = "Seelenbrunnen",
				fr = "Puits des âmes",
				it = "Pozzo dell'Anima",
				pt = "Poço das Almas",
				ru = "Источник душ",
				ko = "영혼의 샘",
				cn = "灵魂之井",
			},
		},
	
		[303149] = {
			readable = "Horde Banner",
			model = 999438,
			text = {
				en = "Horde Banner",
				de = "Banner der Horde",
				fr = "Bannière de la Horde",
				ru = "Знамя Орды",
			},
		},
	
		[303150] = {
			readable = "Horde Banner",
			model = 999438,
			text = {
				en = "Horde Banner",
				de = "Banner der Horde",
				fr = "Bannière de la Horde",
				ru = "Знамя Орды",
			},
		},
	
		[303151] = {
			readable = "Horde Banner",
			model = 999438,
			text = {
				en = "Horde Banner",
				de = "Banner der Horde",
				fr = "Bannière de la Horde",
				ru = "Знамя Орды",
			},
		},
	
		[303152] = {
			readable = "TOMAS GRAY",
			model = 1585657,
			text = {
				en = "TOMAS GRAY",
				de = "THOMAS GRAU",
				pt = "TOMÁS GRIS",
				ru = "ТОМАС ГРЭЙ",
				ko = "토마스 그레이",
				cn = "托马斯·格雷",
			},
		},
	
		[303153] = {
			readable = "JACOB FELSTONE",
			model = 1585657,
			text = {
				en = "JACOB FELSTONE",
				es = "JACOB PIEDRAMÁCULA",
				de = "JAKOB TEUFELSSTEIN",
				fr = "JACOB GANGREPIERRE",
				it = "JACOB VILPIETRA",
				pt = "JACÓ PEDRAVIL",
				ru = "ДЖЕЙКОБ ФЕЛСТОУН",
				ko = "제이콥 펠스톤",
				cn = "雅各布·费尔斯通",
			},
		},
	
		[303154] = {
			readable = "VELLCINDA \"ELSIE\" BENTON",
			model = 1585659,
			text = {
				en = "VELLCINDA \"ELSIE\" BENTON",
				fr = "VELLCINDA « ELSIE » BENTON",
				pt = "VELLZINDA \"ELZA\" BENTO",
				ru = "ВЕЛЛСИНДА \"ЭЛСИ\" БЕНТОН",
				ko = "벨신다 \"엘시\" 벤톤",
				cn = "“艾尔西”威尔辛达·本顿",
			},
		},
	
		[303155] = {
			readable = "PARQUAL FINTALLAS",
			model = 1585659,
			text = {
				en = "PARQUAL FINTALLAS",
				pt = "PASQUAL FINTALLAS",
				ru = "ПАРКВЕЛ ФИНТАЛЛАС",
				ko = "파쿠알 핀탈라스",
				cn = "帕科瓦·芬塔拉斯",
			},
		},
	
		[303156] = {
			readable = "JAMES FELSTONE",
			model = 1585661,
			text = {
				en = "JAMES FELSTONE",
				es = "JAMES PIEDRAMÁCULA",
				de = "JOHANNES TEUFELSSTEIN",
				fr = "JAMES GANGREPIERRE",
				it = "JAMES VILPIETRA",
				pt = "TIAGO PEDRAVIL",
				ru = "ДЖЕЙМС ФЕЛСТОУН",
				ko = "제임스 펠스톤",
				cn = "詹姆斯·费尔斯通",
			},
		},
	
		[303157] = {
			readable = "JOHN FELSTONE",
			model = 1585660,
			text = {
				en = "JOHN FELSTONE",
				es = "JOHN PIEDRAMÁCULA",
				de = "GEORG TEUFELSSTEIN",
				fr = "JOHN GANGREPIERRE",
				it = "JOHN VILPIETRA",
				pt = "JOÃO PEDRAVIL",
				ru = "ДЖОН ФЕЛСТОУН",
				ko = "존 펠스톤",
				cn = "约翰·费尔斯通",
			},
		},
	
		[303170] = {
			readable = "Curious Grain Sack",
			model = 1305115,
			text = {
				en = "Curious Grain Sack",
				es = "Saco de grano curioso",
				de = "Seltsamer Getreidesack",
				fr = "Sac de grain étrange",
				it = "Sacco di Grano Curioso",
				pt = "Saco de Grãos Curioso",
				ru = "Странный мешок с зерном",
				ko = "이상한 곡식 자루",
				cn = "奇怪的谷物袋",
			},
		},
	
		[304011] = {
			readable = "Totem of Fair Wind",
			model = 1255656,
			text = {
				en = "Totem of Fair Wind",
				es = "Tótem de viento favorable",
				de = "Totem der günstigen Winde",
				fr = "Totem de zéphyr",
				it = "Totem della Bonaccia",
				pt = "Totem de Bons Ventos",
				ru = "Тотем попутного ветра",
				ko = "순풍의 토템",
				cn = "顺风图腾",
			},
		},
	
		[304017] = {
			readable = "Horde Banner",
			model = 1032486,
			text = {
				en = "Horde Banner",
				es = "Estandarte de la Horda",
				de = "Hordebanner",
				fr = "Bannière de la Horde",
				it = "Stendardo dell'Orda",
				pt = "Estandarte da Horda",
				ru = "Знамя Орды",
				ko = "호드 깃발",
				cn = "部落军旗",
			},
		},
	
		[304020] = {
			readable = "Horde Banner",
			model = 1032486,
			text = {
				en = "Horde Banner",
				es = "Estandarte de la Horda",
				de = "Hordebanner",
				fr = "Bannière de la Horde",
				it = "Stendardo dell'Orda",
				pt = "Estandarte da Horda",
				ru = "Знамя Орды",
				ko = "호드 깃발",
				cn = "部落军旗",
			},
		},
	
		[304021] = {
			readable = "Horde Banner",
			model = 1032486,
			text = {
				en = "Horde Banner",
				es = "Estandarte de la Horda",
				de = "Hordebanner",
				fr = "Bannière de la Horde",
				it = "Stendardo dell'Orda",
				pt = "Estandarte da Horda",
				ru = "Знамя Орды",
				ko = "호드 깃발",
				cn = "部落军旗",
			},
		},
	
		[304022] = {
			readable = "Horde Banner",
			model = 1032486,
			text = {
				en = "Horde Banner",
				es = "Estandarte de la Horda",
				de = "Hordebanner",
				fr = "Bannière de la Horde",
				it = "Stendardo dell'Orda",
				pt = "Estandarte da Horda",
				ru = "Знамя Орды",
				ko = "호드 깃발",
				cn = "部落军旗",
			},
		},
	
		[304053] = {
			readable = "Neutral Banner",
			model = 200283,
			text = {
				en = "Neutral Banner",
				es = "Estandarte neutral",
				de = "Neutrales Banner",
				fr = "Bannière neutre",
				it = "Stendardo Neutrale",
				pt = "Estandarte Neutro",
				ru = "Нейтральное знамя",
				ko = "중립 깃발",
				cn = "中立旗帜",
			},
		},
	
		[304054] = {
			readable = "Horde Banner",
			model = 1032486,
			text = {
				en = "Horde Banner",
				es = "Estandarte de la Horda",
				de = "Hordebanner",
				fr = "Bannière de la Horde",
				it = "Stendardo dell'Orda",
				pt = "Estandarte da Horda",
				ru = "Знамя Орды",
				ko = "호드 깃발",
				cn = "部落旗帜",
			},
		},
	
		[304067] = {
			readable = "Engine Gearing",
			model = 950737,
			text = {
				en = "Engine Gearing",
				es = "Engranaje de motor",
				de = "Motorteile",
				fr = "Rouages de moteur",
				it = "Ingranaggio di Motore",
				pt = "Peças de Motor",
				ru = "Шестеренки двигателя",
				ko = "엔진 장치",
				cn = "引擎传动装置",
			},
		},
	
		[304068] = {
			readable = "Plague Bomb",
			model = 243601,
			text = {
				en = "Plague Bomb",
				es = "Bomba de peste",
				de = "Seuchenbombe",
				fr = "Bombe de peste",
				it = "Bomba Pestilenziale",
				pt = "Bomba Pestilenta",
				ru = "Чумная бомба",
				cn = "天灾炸弹",
			},
		},
	
		[304093] = {
			readable = "Naga Elixir",
			model = 1096618,
			text = {
				en = "Naga Elixir",
				es = "Elixir naga",
				de = "Nagaelixier",
				fr = "Élixir naga",
				it = "Elisir dei Naga",
				pt = "Elixir das Nagas",
				ru = "Эликсир наг",
				ko = "나가 비약",
				cn = "纳迦药剂",
			},
		},
	
		[304122] = {
			readable = "Naga Elixir",
			model = 1096618,
			text = {
				en = "Naga Elixir",
				es = "Elixir naga",
				de = "Nagaelixier",
				fr = "Élixir naga",
				it = "Elisir dei Naga",
				pt = "Elixir das Nagas",
				ru = "Эликсир наг",
				ko = "나가 비약",
				cn = "纳迦药剂",
			},
		},
	
		[304123] = {
			readable = "Naga Elixir",
			model = 1096618,
			text = {
				en = "Naga Elixir",
				es = "Elixir naga",
				de = "Nagaelixier",
				fr = "Élixir naga",
				it = "Elisir dei Naga",
				pt = "Elixir das Nagas",
				ru = "Эликсир наг",
				ko = "나가 비약",
				cn = "纳迦药剂",
			},
		},
	
		[304124] = {
			readable = "Plague Bomb",
			model = 243601,
			text = {
				en = "Plague Bomb",
				es = "Bomba de peste",
				de = "Seuchenbombe",
				fr = "Bombe de peste",
				it = "Bomba Pestilenziale",
				pt = "Bomba Pestilenta",
				ru = "Чумная бомба",
				cn = "天灾炸弹",
			},
		},
	
		[304164] = {
			readable = "Weapon Rack",
			model = 1096620,
			text = {
				en = "Weapon Rack",
				es = "Expositor de armas",
				de = "Waffenständer",
				fr = "Râtelier d’armes",
				it = "Rastrelliera delle Armi",
				pt = "Cavalete de Armas",
				ru = "Оружейная стойка",
				ko = "무기 선반",
				cn = "武器架",
			},
		},
	
		[304165] = {
			readable = "Darktide Orb",
			model = 1450066,
			text = {
				en = "Darktide Orb",
				es = "Orbe Marea Oscura",
				de = "Nachtflutsphäre",
				fr = "Orbe de Sombreflux",
				it = "Globo dei Foscamarea",
				pt = "Orbe Ondanegra",
				ru = "Сфера Темного Прилива",
				ko = "어둠파도 구체",
				cn = "黑潮宝珠",
			},
		},
	
		[305406] = {
			readable = "Barnacled Anchor",
			model = 1117429,
			text = {
				en = "Barnacled Anchor",
				es = "Ancla llena de percebes",
				de = "Muschelverkrusteter Anker",
				fr = "Ancre couverte de bigorneaux",
				it = "Ancora Incrostata di Conchiglie",
				pt = "Âncora Craquenta",
				ru = "Обросший ракушками якорь",
				ko = "따개비가 붙은 닻",
				cn = "长满藤壶的船锚",
			},
		},
	
		[305794] = {
			readable = "Fuel Barrel",
			model = 317157,
			text = {
				en = "Fuel Barrel",
				es = "Barril de combustible",
				de = "Treibstoffbehälter",
				fr = "Baril de carburant",
				it = "Barile di Carburante",
				pt = "Barril de Combustível",
				ru = "Бочка с топливом",
				ko = "연료 통",
				cn = "燃料桶",
			},
		},
	
		[305839] = {
			readable = "Shortfuse Special",
			model = 254423,
			text = {
				en = "Shortfuse Special",
				es = "Minimecha especial",
				de = "Schnellzünd Spezial",
				fr = "Spécialité de Courtemèche",
				it = "Speciale di Micciacorta",
				pt = "Especial Paviocurto",
				ru = "Спецвзрыватор",
				ko = "쇼트퓨즈 특제 폭탄",
				cn = "特制的短线炸药",
			},
		},
	
		[305840] = {
			readable = "Bag of Bombs",
			model = 968120,
			text = {
				en = "Bag of Bombs",
				es = "Bolsa de bombas",
				de = "Bombenbeutel",
				fr = "Sac de bombes",
				it = "Sacca di Bombe",
				pt = "Bolsa de Bombas",
				ru = "Мешок с бомбами",
				ko = "폭탄 가방",
				cn = "一袋炸弹",
			},
		},
	
		[305841] = {
			readable = "Mirjam's Marvelous Elixir",
			model = 304794,
			text = {
				en = "Mirjam's Marvelous Elixir",
				es = "Elixir maravilloso de Mirjam",
				de = "Mirjams mystisches Elixier",
				fr = "Élixir formidable de Mirjam",
				it = "Elisir Meraviglioso di Mirjam",
				pt = "Elixir Maravilhoso de Mirjam",
				ru = "Восхитительный эликсир Мирьям",
				ko = "미리암의 경이로운 비약",
			},
		},
	
		[305842] = {
			readable = "Naga Shrine",
			model = 201452,
			text = {
				en = "Naga Shrine",
				es = "Santuario naga",
				de = "Nagaschrein",
				fr = "Sanctuaire naga",
				it = "Santuario dei Naga",
				pt = "Santuário das Nagas",
				ru = "Святилище наг",
				cn = "纳迦神龛",
			},
		},
	
		[305843] = {
			readable = "Enchanted Pearl",
			model = 369232,
			text = {
				en = "Enchanted Pearl",
				es = "Perla encantada",
				de = "Verzauberte Perle",
				fr = "Perle enchantée",
				it = "Perla Incantata",
				pt = "Pérola Encantada",
				ru = "Зачарованная жемчужина",
				ko = "마력 깃든 진주",
				cn = "魔化珍珠",
			},
		},
	
		[305844] = {
			readable = "Pirate Flag",
			model = 201082,
			text = {
				en = "Pirate Flag",
				es = "Bandera pirata",
				de = "Piratenflagge",
				fr = "Drapeau pirate",
				it = "Bandiera Pirata",
				pt = "Bandeira Pirata",
				ru = "Пиратский флаг",
				ko = "해적 깃발",
			},
		},
	
		[307026] = {
			readable = "Horde Banner",
			model = 1032486,
			text = {
				en = "Horde Banner",
				es = "Estandarte de la Horda",
				de = "Hordebanner",
				fr = "Bannière de la Horde",
				it = "Stendardo dell'Orda",
				pt = "Estandarte da Horda",
				ru = "Знамя Орды",
				ko = "호드 깃발",
				cn = "部落军旗",
			},
		},
	
		[307027] = {
			readable = "War Chest",
			model = 1388069,
			text = {
				en = "War Chest",
				es = "Cofre de guerra",
				de = "Kriegskasse",
				fr = "Trésor de guerre",
				it = "Cassa da Guerra",
				pt = "Baú de Guerra",
				ru = "Трофейный сундук",
				ko = "전쟁 상자",
				cn = "战争宝箱",
			},
		},
	
		[307028] = {
			readable = "Azerite Grenades",
			model = 1984114,
			text = {
				en = "Azerite Grenades",
				es = "Granadas de azerita",
				de = "Azeritgranaten",
				fr = "Grenades d’azérite",
				it = "Granate d'Azerite",
				pt = "Granadas de Azerita",
				ru = "Азеритовые гранаты",
				ko = "아제라이트 수류탄",
				cn = "艾泽里特手榴弹",
			},
		},
	
		[307029] = {
			readable = "Blight Barrel",
			model = 194843,
			text = {
				en = "Blight Barrel",
				es = "Barril de añublo",
				de = "Seuchenfass",
				fr = "Tonneau de peste",
				it = "Barile del Morbo",
				pt = "Barril Empesteado",
				ru = "Бочка с чумой",
				cn = "魔药桶",
			},
		},
	
		[307032] = {
			readable = "Stack of Blight Barrels",
			model = 194843,
			text = {
				en = "Stack of Blight Barrels",
				es = "Montón de barriles de añublo",
				de = "Stapel Seuchenfässer",
				fr = "Pile de tonneaux de peste",
				it = "Mucchio di Barili del Morbo",
				pt = "Pilha de Barris Empesteados",
				ru = "Штабель бочек с чумой",
				cn = "一堆魔药桶",
			},
		},
	
		[307033] = {
			readable = "Timbered Box",
			model = 653706,
			text = {
				en = "Timbered Box",
				es = "Caja de madera",
				de = "Hölzerne Zelle",
				fr = "Boîte en bois",
				it = "Scatola di Legno",
				pt = "Caixa Lenhosa",
				ru = "Деревянная клетка",
			},
		},
	
		[307035] = {
			readable = "Arcane Trap",
			model = 1664979,
			text = {
				en = "Arcane Trap",
				es = "Trampa Arcana",
				de = "Arkane Falle",
				fr = "Piège arcanique",
				it = "Trappola Arcana",
				pt = "Armadilha Arcana",
				ru = "Волшебная ловушка",
				ko = "비전 덫",
				cn = "奥术陷阱",
			},
		},
	
		[307036] = {
			readable = "Naga Cage",
			model = 1965334,
			text = {
				en = "Naga Cage",
				es = "Jaula naga",
				de = "Nagakäfig",
				fr = "Cage naga",
				it = "Gabbia dei Naga",
				pt = "Jaula das Nagas",
				ru = "Клетка наг",
			},
		},
	
		[307037] = {
			readable = "Gibbet",
			model = 1097623,
			text = {
				en = "Gibbet",
				es = "Horca",
				de = "Käfig",
				fr = "Gibet",
				it = "Forca",
				pt = "Forca",
				ru = "Подвесная клетка",
			},
		},
	
		[307039] = {
			readable = "Bone Cage",
			model = 1959525,
			text = {
				en = "Bone Cage",
				es = "Jaula de huesos",
				de = "Knochenkäfig",
				fr = "Cage d’os",
				it = "Gabbia d'Ossa",
				pt = "Jaula de Ossos",
				ru = "Костяная клетка",
				cn = "骨笼",
			},
		},
	
		[307042] = {
			readable = "Stone Pile",
			model = 982120,
			text = {
				en = "Stone Pile",
				es = "Montón de piedras",
				de = "Steinhaufen",
				fr = "Tas de pierres",
				it = "Mucchio di Sassi",
				pt = "Pilha de Pedras",
				ru = "Куча камней",
				ko = "돌더미",
				cn = "石堆",
			},
		},
	
		[307066] = {
			readable = "Ocean Chest",
			model = 2120294,
			text = {
				en = "Ocean Chest",
				es = "Cofre del océano",
				de = "Ozeantruhe",
				fr = "Coffre de l’océan",
				it = "Cassa dell'Oceano",
				pt = "Baú do Oceano",
				ru = "Сундук из океана",
				ko = "바다 상자",
				cn = "海洋宝箱",
			},
		},
	
		[307068] = {
			readable = "Bounty Board",
			model = 199473,
			text = {
				en = "Bounty Board",
				es = "Tablón de recompensas",
				de = "Steckbrieftafel",
				fr = "Tableau de récompense",
				it = "Bacheca delle Taglie",
				pt = "Quadro de Recompensas",
				ru = "Доска объявлений",
			},
		},
	
		[307070] = {
			readable = "Old Footlocker",
			model = 198238,
			text = {
				en = "Old Footlocker",
				de = "Alte Schließkiste",
				fr = "Vieille cantine",
				it = "Vecchio Scrigno",
				pt = "Maleta Velha",
				ru = "Старый сундучок",
			},
		},
	
		[307091] = {
			readable = "Ominous Whispering Dagger",
			model = 1346214,
			text = {
				en = "Ominous Whispering Dagger",
				es = "Daga de susurros ominosos",
				de = "Ominöser flüsternder Dolch",
				fr = "Dague aux murmures inquiétants",
				it = "Pugnale Sussurrante Inquietante",
				pt = "Adaga Sussurrante Agourenta",
				ru = "Зловещий шепчущий кинжал",
				ko = "불길한 속삭임의 단검",
				cn = "不祥的低语之匕",
			},
		},
	
		[307265] = {
			readable = "Wanted Poster",
			icon = 134939,
			model = 199421,
			text = {
				en = "Wanted Poster",
				es = "Cartel de Se busca",
				de = "Steckbrief",
				fr = "Avis de recherche",
				it = "Manifesto dei Ricercati",
				pt = "Cartaz de Procura-se",
				ru = "Плакат \"Разыскивается\"",
				ko = "현상 수배 전단",
				cn = "通缉布告",
			},
		},
	
		[307267] = {
			readable = "The Emperor's Tomb",
			model = 200640,
			text = {
				en = "The Emperor's Tomb",
				es = "La Tumba del Emperador",
				de = "Grabmal des Imperators",
				fr = "Tombe de l’Empereur",
				it = "Tomba dell'Imperatore",
				pt = "A Tumba do Imperador",
				ru = "Гробница Императора",
				ko = "제국의 무덤",
			},
		},
	
		[307277] = {
			readable = "Old Jug",
			icon = 132798,
			model = 189821,
			text = {
				en = "Old Jug",
				es = "Vieja jarra",
				de = "Alter Henkelkrug",
				fr = "Vieille cruche",
				it = "Vecchio Fiasco",
				pt = "Velho Garrafão",
				ru = "Старый кувшин",
				ko = "낡은 단지",
				cn = "旧酒壶",
			},
		},
	
		[307307] = {
			readable = "Broken Barrel",
			icon = 132622,
			model = 199567,
			text = {
				en = "Broken Barrel",
				es = "Barrica rota",
				de = "Zerbrochenes Fass",
				fr = "Tonneau cassé",
				it = "Barile Spezzato",
				pt = "Barril Quebrado",
				ru = "Разбитая бочка",
				ko = "부서진 통",
				cn = "破损的桶",
			},
		},
	
		[307325] = {
			readable = "Wanted Poster",
			icon = 134939,
			model = 199421,
			text = {
				en = "Wanted Poster",
				es = "Cartel de Se busca",
				de = "Steckbrief",
				fr = "Avis de recherche",
				it = "Manifesto dei Ricercati",
				pt = "Cartaz de Procura-se",
				ru = "Плакат \"Разыскивается\"",
				ko = "현상 수배 전단",
				cn = "通缉布告",
			},
		},
	
		[307330] = {
			readable = "Captain's Footlocker",
			icon = 132761,
			model = 198238,
			text = {
				en = "Captain's Footlocker",
				es = "Baúl del Capitán",
				de = "Schließkiste des Kapitäns",
				fr = "Cantine du capitaine",
				it = "Scrigno del Capitano",
				ru = "Сундучок капитана",
				ko = "선장의 사물함",
				cn = "船长的手提箱",
			},
		},
	
		[307338] = {
			readable = "Fall of Gurubashi",
			model = 200640,
			text = {
				en = "Fall of Gurubashi",
				es = "La Caída de Gurubashi",
				de = "Gurubashis Untergang",
				fr = "Chute des Gurubashi",
				it = "Caduta dei Gurubashi",
				pt = "A Queda de Gurubashi",
				ru = "Падение Гурубаши",
				ko = "구루바시의 몰락",
			},
		},
	
		[307340] = {
			readable = "Locked Chest",
			model = 196979,
			text = {
				en = "Locked Chest",
				es = "Cofre cerrado",
				de = "Verschlossene Truhe",
				fr = "Coffre verrouillé",
				it = "Cassa Chiusa",
				ru = "Запертый сундук",
			},
		},
	
		[307349] = {
			readable = "Unexploded Bomb",
			model = 254422,
			text = {
				en = "Unexploded Bomb",
				es = "Bomba sin detonar",
				de = "Blindgänger",
				fr = "Bombe intacte",
				it = "Bomba Inesplosa",
				pt = "Bomba Não Detonada",
				ru = "Неразорвавшаяся бомба",
				ko = "불발 폭탄",
				cn = "未引爆的炸弹",
			},
		},
	
		[307354] = {
			readable = "Naga Cage",
			model = 1118155,
			text = {
				en = "Naga Cage",
				es = "Jaula naga",
				de = "Nagakäfig",
				fr = "Cage naga",
				it = "Gabbia dei Naga",
				pt = "Jaula das Nagas",
				ru = "Клетка наг",
				ko = "나가 우리",
			},
		},
	
		[307364] = {
			readable = "Glowing Fissure",
			model = 1847842,
			text = {
				en = "Glowing Fissure",
				es = "Fisura resplandeciente",
				de = "Leuchtender Spalt",
				fr = "Fissure luminescente",
				it = "Fessura Luminosa",
				pt = "Fenda Chamejante",
				ru = "Сияющий разлом",
				cn = "闪光裂隙",
			},
		},
	
		[307365] = {
			readable = "Volatile Slab",
			model = 197122,
			text = {
				en = "Volatile Slab",
				es = "Bloque volátil",
				de = "Unbeständiger Fels",
				fr = "Bloc instable",
				it = "Lastra Instabile",
				pt = "Laje Volátil",
				ru = "Нестабильная плита",
				cn = "爆裂石片",
			},
		},
	
		[307366] = {
			readable = "Unstable Ore",
			model = 1001689,
			text = {
				en = "Unstable Ore",
				es = "Mena inestable",
				de = "Instabiles Erz",
				fr = "Minerai instable",
				it = "Minerale Instabile",
				pt = "Minério Instável",
				ru = "Нестабильная руда",
				cn = "不稳定的矿石",
			},
		},
	
		[307367] = {
			readable = "Ritual Pillar",
			model = 1517169,
			text = {
				en = "Ritual Pillar",
				es = "Pilar ritual",
				de = "Ritualsäule",
				fr = "Pilier de rituel",
				it = "Pilastro Rituale",
				pt = "Pilar Ritual",
				ru = "Ритуальная колонна",
				ko = "의식의 기둥",
				cn = "仪式之柱",
			},
		},
	
		[307381] = {
			readable = "Glyphed Crystal",
			model = 202451,
			text = {
				en = "Glyphed Crystal",
				es = "Cristal con inscripciones",
				de = "Glyphenverzierter Kristall",
				fr = "Cristal orné de glyphes",
				it = "Cristallo con Glifi",
				pt = "Cristal com Glifos",
				ru = "Покрытый письменами кристалл",
				ko = "문자가 새겨진 수정",
				cn = "符文水晶",
			},
		},
	
		[307382] = {
			readable = "Dark Rune",
			model = 166432,
			text = {
				en = "Dark Rune",
				es = "Runa oscura",
				de = "Dunkelrune",
				fr = "Rune ténébreuse",
				it = "Runa Oscura",
				pt = "Runa Negra",
				ru = "Темная руна",
				ko = "암흑의 룬",
			},
		},
	
		[307383] = {
			readable = "Glowing Rune",
			model = 166432,
			text = {
				en = "Glowing Rune",
				es = "Runa resplandeciente",
				de = "Leuchtende Rune",
				fr = "Rune luminescente",
				it = "Runa Luminosa",
				pt = "Runa Chamejante",
				ru = "Светящаяся руна",
			},
		},
	
		[307385] = {
			readable = "Tribal Rune",
			model = 166432,
			text = {
				en = "Tribal Rune",
				es = "Runa tribal",
				de = "Stammesrune",
				fr = "Rune tribale",
				it = "Runa Tribale",
				pt = "Runa Tribal",
				ru = "Руна племени",
				ko = "부족 룬",
				cn = "部族符文",
			},
		},
	
		[307386] = {
			readable = "Vile Rune",
			model = 166432,
			text = {
				en = "Vile Rune",
				es = "Runa vil",
				de = "Abscheuliche Rune",
				fr = "Vile rune",
				it = "Runa Vile",
				pt = "Runa Torpe",
				ru = "Пагубная руна",
				ko = "사악한 룬",
				cn = "邪恶符文",
			},
		},
	
		[307387] = {
			readable = "Rune Trap",
			model = 166432,
			text = {
				en = "Rune Trap",
				es = "Trampa de runas",
				de = "Runenfalle",
				fr = "Piège à runes",
				it = "Trappola Runica",
				pt = "Armadilha Rúnica",
				ru = "Руническая ловушка",
				cn = "符文陷阱",
			},
		},
	
		[307388] = {
			readable = "Purifying Rune",
			model = 166432,
			text = {
				en = "Purifying Rune",
				es = "Runa purificadora",
				de = "Läuternde Rune",
				fr = "Rune purificatrice",
				it = "Runa Purificante",
				pt = "Runa Purificante",
				ru = "Руна очищения",
				ko = "정화 룬",
				cn = "净化符文",
			},
		},
	
		[307389] = {
			readable = "Corrupted Rift",
			model = 166432,
			text = {
				en = "Corrupted Rift",
				es = "Falla corrupta",
				de = "Verderbter Riss",
				fr = "Faille corrompue",
				it = "Fenditura Corrotta",
				pt = "Fissura Corrompida",
				ru = "Оскверненный разлом",
				ko = "타락의 균열",
				cn = "腐蚀裂隙",
			},
		},
	
		[307396] = {
			readable = "Naga War Supplies",
			model = 1096638,
			text = {
				en = "Naga War Supplies",
				es = "Suministros de guerra nagas",
				de = "Kriegsvorräte der Naga",
				fr = "Fournitures de guerre naga",
				it = "Rifornimenti di Guerra dei Naga",
				pt = "Suprimentos de Guerra das Nagas",
				ru = "Припасы наг",
				ko = "나가 전쟁 보급품",
			},
		},
	
		[307397] = {
			readable = "Naga War Supplies",
			model = 1096639,
			text = {
				en = "Naga War Supplies",
				es = "Suministros de guerra nagas",
				de = "Kriegsvorräte der Naga",
				fr = "Fournitures de guerre naga",
				it = "Rifornimenti di Guerra dei Naga",
				pt = "Suprimentos de Guerra das Nagas",
				ru = "Припасы наг",
				ko = "나가 전쟁 보급품",
			},
		},
	
		[307400] = {
			readable = "Naga War Banner",
			model = 1096324,
			text = {
				en = "Naga War Banner",
				es = "Estandarte de guerra naga",
				de = "Nagakriegsbanner",
				fr = "Bannière de guerre naga",
				it = "Stendardo di Guerra dei Naga",
				pt = "Estandarte de Guerra das Nagas",
				ru = "Боевой стяг наг",
				ko = "나가 전쟁 깃발",
			},
		},
	
		[307405] = {
			readable = "Sharpened Knife",
			model = 936407,
			text = {
				en = "Sharpened Knife",
				es = "Cuchillo afilado",
				de = "Geschärftes Messer",
				fr = "Couteau aiguisé",
				it = "Coltello Affilato",
				pt = "Faca Afiada",
				ru = "Заточенный нож",
			},
		},
	
		[307424] = {
			readable = "Remote Mine Controls",
			model = 197760,
			text = {
				en = "Remote Mine Controls",
				es = "Control remoto para minas",
				de = "Minenfernsteuerung",
				fr = "Télécommande de mine",
				it = "Controlli a Distanza delle Mine",
				pt = "Controle Remoto de Mina",
				ru = "Пульт управления минами",
				ko = "지뢰 원격 조종기",
				cn = "远程地雷控制器",
			},
		},
	
		[307425] = {
			readable = "Faithless Cache",
			model = 1602426,
			text = {
				en = "Faithless Cache",
				es = "Alijo de los infieles",
				de = "Truhe der Treulosen",
				fr = "Cache infidèle",
				it = "Cassa dei Senzafede",
				pt = "Baú dos Ímpios",
				ru = "Тайник отступников",
				ko = "부정한 보관함",
				cn = "无信者箱子",
			},
		},
	
		[307429] = {
			readable = "Stack of Blight Barrels",
			model = 194843,
			text = {
				en = "Stack of Blight Barrels",
				es = "Montón de barriles de añublo",
				de = "Stapel Seuchenfässer",
				fr = "Pile de tonneaux de peste",
				it = "Mucchio di Barili del Morbo",
				pt = "Pilha de Barris Empesteados",
				ru = "Штабель бочек с чумой",
				cn = "一堆魔药桶",
			},
		},
	
		[307434] = {
			readable = "Crawler Mine Parts",
			model = 876971,
			text = {
				en = "Crawler Mine Parts",
				es = "Piezas de mina reptadora",
				de = "Kriecherminenteile",
				fr = "Pièces de mine rampante",
				it = "Parti di Mina Strisciante",
				pt = "Peças da Mina Rastejante",
				ru = "Детали ползучей мины",
				ko = "거미 지뢰 부품",
				cn = "蛛形地雷零件",
			},
		},
	
		[307486] = {
			readable = "Azerite Chunk",
			model = 1982821,
			text = {
				en = "Azerite Chunk",
				es = "Trozo de azerita",
				de = "Azeritklumpen",
				fr = "Morceau d’azérite",
				it = "Pezzo d'Azerite",
				pt = "Pedaço de Azerita",
				ru = "Глыба азерита",
				ko = "아제라이트 덩어리",
				cn = "大块艾泽里特",
			},
		},
	
		[307487] = {
			readable = "Azerite Chunk",
			model = 1982816,
			text = {
				en = "Azerite Chunk",
				es = "Trozo de azerita",
				de = "Azeritklumpen",
				fr = "Morceau d’azérite",
				it = "Pezzo d'Azerite",
				pt = "Pedaço de Azerita",
				ru = "Глыба азерита",
				ko = "아제라이트 덩어리",
				cn = "大块艾泽里特",
			},
		},
	
		[307488] = {
			readable = "Azerite Chunk",
			model = 1982819,
			text = {
				en = "Azerite Chunk",
				es = "Trozo de azerita",
				de = "Azeritklumpen",
				fr = "Morceau d’azérite",
				it = "Pezzo d'Azerite",
				pt = "Pedaço de Azerita",
				ru = "Глыба азерита",
				ko = "아제라이트 덩어리",
				cn = "大块艾泽里特",
			},
		},
	
		[307573] = {
			readable = "Goblin Teleporter",
			model = 201026,
			text = {
				en = "Goblin Teleporter",
				es = "Teletransportador goblin",
				de = "Goblinteleporter",
				fr = "Téléporteur gobelin",
				it = "Teletrasporto Goblin",
				pt = "Teleportador Goblínico",
				ru = "Гоблинский телепорт",
				ko = "고블린 순간이동기",
				cn = "地精传送器",
			},
		},
	
		[307614] = {
			readable = "Zandalari Troll",
			model = 1590832,
			text = {
				en = "Zandalari Troll",
				es = "Trols Zandalari",
				de = "Zandalaritroll",
				fr = "Troll zandalari",
				it = "Troll Zandalari",
				pt = "Troll Zandalari",
				ru = "Зандалары",
				ko = "잔달라 트롤",
				cn = "赞达拉巨魔",
			},
		},
	
		[307619] = {
			readable = "Broken Barrel",
			model = 199567,
			text = {
				en = "Broken Barrel",
				es = "Barril roto",
				de = "Kaputtes Fass",
				fr = "Tonneau cassé",
				it = "Barile Spezzato",
				pt = "Barril Quebrado",
				ru = "Разбитая бочка",
			},
		},
	
		[307621] = {
			readable = "Jug",
			model = 189820,
			text = {
				en = "Jug",
				de = "Krug",
				fr = "Pichet",
				it = "Brocca",
				pt = "Jarra",
				ru = "Кувшин",
			},
		},
	
		[307622] = {
			readable = "Goblin Teleporter",
			model = 201026,
			text = {
				en = "Goblin Teleporter",
				es = "Teletransportador goblin",
				de = "Goblinteleporter",
				fr = "Téléporteur gobelin",
				it = "Teletrasporto Goblin",
				pt = "Teleportador Goblínico",
				ru = "Гоблинский телепорт",
				ko = "고블린 순간이동기",
				cn = "地精传送器",
			},
		},
	
		[307623] = {
			readable = "Locked Chest",
			model = 196979,
			text = {
				en = "Locked Chest",
				de = "Verschlossene Truhe",
				fr = "Coffre verrouillé",
				it = "Cassa Chiusa",
				pt = "Baú Trancado",
				ru = "Запертый сундук",
			},
		},
	
		[307673] = {
			readable = "Door to Aegrim's Study",
			model = 203075,
			text = {
				en = "Door to Aegrim's Study",
				es = "Puerta al Estudio de Aegrim",
				de = "Tür zu Aegrims Arbeitszimmer",
				fr = "Porte de l’étude d’Aegrim",
				it = "Porta dello Studio di Aegrim",
				pt = "Porta do Gabinete de Aegrim",
				ru = "Дверь в кабинет Эгрима",
				ko = "애그림의 연구실로 통하는 문",
				cn = "艾格利姆的书房的门",
			},
		},
	
		[307674] = {
			readable = "Stack of Supplies",
			model = 1984147,
			text = {
				en = "Stack of Supplies",
				es = "Montón de suministros",
				de = "Stapel mit Vorräten",
				fr = "Pile de fournitures",
				it = "Mucchio di Rifornimenti",
				pt = "Pilha de Suprimentos",
				ru = "Куча припасов",
				cn = "一堆补给",
			},
		},
	
		[307683] = {
			readable = "Azerite Bombs",
			model = 1984147,
			text = {
				en = "Azerite Bombs",
				es = "Bombas de azerita",
				de = "Azeritbomben",
				fr = "Bombes d’azérite",
				it = "Bombe d'Azerite",
				pt = "Bombas de Azerita",
				ru = "Азеритовые бомбы",
			},
		},
	
		[307748] = {
			readable = "Venture Co. Letter",
			icon = 133461,
			model = 1331239,
			text = {
				en = "Venture Co. Letter",
				es = "Carta de Ventura y Cía.",
				de = "Brief der Venture Co.",
				fr = "Lettre de la KapitalRisk",
				pt = "Carta da Empreendimentos S.A.",
				ru = "Письмо Торговой компании",
				cn = "风险投资公司函件",
			},
		},
	
		[307749] = {
			readable = "Cargo Rope",
			model = 571794,
			text = {
				en = "Cargo Rope",
				es = "Cuerda de carga",
				de = "Frachtseil",
				fr = "Corde d’amarrage",
				it = "Corda del Carico",
				pt = "Corda de Carga",
				ru = "Веревка",
				ko = "화물 밧줄",
				cn = "货物绳",
			},
		},
	
		[307750] = {
			readable = "Coiled Rope",
			model = 1019643,
			text = {
				en = "Coiled Rope",
				es = "Cuerda enrollada",
				de = "Aufgerolltes Seil",
				fr = "Corde enroulée",
				it = "Corda Arrotolata",
				pt = "Corda Enrolada",
				ru = "Свернутая веревка",
				ko = "감아놓은 밧줄",
				cn = "卷绳",
			},
		},
	
		[307777] = {
			readable = "Cargo Rope",
			model = 571796,
			text = {
				en = "Cargo Rope",
				es = "Cuerda de carga",
				de = "Frachtseil",
				fr = "Corde d’amarrage",
				it = "Corda del Carico",
				pt = "Corda de Carga",
				ru = "Веревка",
				ko = "화물 밧줄",
				cn = "货物绳",
			},
		},
	
		[307778] = {
			readable = "Large Azerite Bomb",
			model = 985362,
			text = {
				en = "Large Azerite Bomb",
				es = "Bomba de azerita grande",
				de = "Große Azeritbombe",
				fr = "Grande bombe d’azérite",
				it = "Bomba d'Azerite Grande",
				pt = "Bomba de Azerita Grande",
				ru = "Большая азеритовая бомба",
				ko = "대형 아제라이트 폭탄",
			},
		},
	
		[307829] = {
			readable = "Ornamental Golden Blade",
			model = 322941,
			text = {
				en = "Ornamental Golden Blade",
				es = "Hoja dorada decorativa",
				de = "Dekorative goldene Klinge",
				fr = "Lame dorée ornementale",
				ru = "Украшенный золотой клинок",
			},
		},
	
		[307830] = {
			readable = "Empty Supply Crate",
			model = 950137,
			text = {
				en = "Empty Supply Crate",
				es = "Cajón de suministros vacío",
				de = "Leere Vorratskiste",
				fr = "Caisse de ravitaillement vide",
				ru = "Пустой ящик из-под припасов",
			},
		},
	
		[307831] = {
			readable = "Scroll",
			model = 1355629,
			text = {
				en = "Scroll",
				es = "Pergamino",
				de = "Schriftrolle",
				fr = "Parchemin",
				ru = "Свиток",
			},
		},
	
		[307836] = {
			readable = "Twilight Ore",
			model = 984397,
			text = {
				en = "Twilight Ore",
				es = "Mena crepuscular",
				de = "Zwielichterz",
				fr = "Minerai du Crépuscule",
				it = "Minerale del Crepuscolo",
				pt = "Minério Crepuscular",
				ru = "Сумеречная руда",
				ko = "황혼의 광석",
				cn = "暮光矿石",
			},
		},
	
		[307837] = {
			readable = "Weapon Rack",
			model = 1005511,
			text = {
				en = "Weapon Rack",
				es = "Expositor de armas",
				de = "Waffenständer",
				fr = "Râtelier d’armes",
				it = "Rastrelliera delle Armi",
				pt = "Cavalete de Armas",
				ru = "Оружейная стойка",
				ko = "무기 선반",
				cn = "武器架",
			},
		},
	
		[308100] = {
			readable = "Engine Gearing",
			model = 951904,
			text = {
				en = "Engine Gearing",
				es = "Engranaje de motor",
				de = "Motorteile",
				fr = "Rouages de moteur",
				it = "Ingranaggio di Motore",
				pt = "Peças de Motor",
				ru = "Шестеренки двигателя",
				ko = "엔진 장치",
				cn = "引擎传动装置",
			},
		},
	
		[308102] = {
			readable = "Cannon Ammo",
			model = 198279,
			text = {
				en = "Cannon Ammo",
				es = "Munición para cañón",
				de = "Kanonenmunition",
				fr = "Munition de canon",
				it = "Munizione per Cannone",
				pt = "Munição de Canhão",
				ru = "Артиллерийские снаряды",
				ko = "대포 탄약",
				cn = "火炮弹药",
			},
		},
	
		[308103] = {
			readable = "Azerite Cannon Balls",
			model = 1662885,
			text = {
				en = "Azerite Cannon Balls",
				es = "Balas de cañón de azerita",
				de = "Azeritkanonenkugeln",
				fr = "Boulets de canon en azérite",
				it = "Palle di Cannone d'Azerite",
				pt = "Balas de Canhão de Azerita",
				ru = "Азеритовые пушечные ядра",
				ko = "아제라이트 포탄",
				cn = "艾泽里特炮弹",
			},
		},
	
		[308105] = {
			readable = "Dark Iron Mole Machine",
			model = 244221,
			text = {
				en = "Dark Iron Mole Machine",
				es = "Máquina topo Hierro Negro",
				de = "Maulwurfmaschine der Dunkeleisenzwerge",
				fr = "Taupe mécanique sombrefer",
				it = "Trivella dei Ferroscuro",
				pt = "Máquina Toupeira dos Ferro Negro",
				ru = "Буровая установка клана Черного Железа",
				ko = "검은무쇠 굴착기",
			},
		},
	
		[308114] = {
			readable = "Door to Old Ironforge",
			model = 203075,
			text = {
				en = "Door to Old Ironforge",
				es = "Puerta a Antigua Forjaz",
				de = "Tür zur Altstadt von Eisenschmiede",
				fr = "Porte du Vieux Forgefer",
				it = "Porta della Vecchia Forgiardente",
				pt = "Porta da Antiga Altaforja",
				ru = "Дверь в \"Старый Стальгорн\"",
				ko = "구 아이언포지로 통하는 문",
				cn = "旧铁炉堡的门",
			},
		},
	
		[308381] = {
			readable = "Alliance Cage",
			model = 653706,
			text = {
				en = "Alliance Cage",
				es = "Jaula de la Alianza",
				de = "Allianzkäfig",
				fr = "Cage de l’Alliance",
				it = "Gabbia dell'Alleanza",
				pt = "Jaula da Aliança",
				ru = "Клетка Альянса",
				ko = "얼라이언스 철창",
				cn = "联盟笼子",
			},
		},
	
		[309488] = {
			readable = "The Bloodied Glaive of Vol'jin",
			model = 1446904,
			text = {
				en = "The Bloodied Glaive of Vol'jin",
				es = "Guja ensangrentada de Vol'jin",
				de = "Vol'jins blutige Gleve",
				fr = "Glaive de Vol’jin ensanglanté",
				pt = "A Glaive Ensanguentada de Vol'jin",
				ru = "Окровавленный боевой клинок Вол'джина",
			},
		},
	
		[309495] = {
			readable = "The Bloodied Glaive of Vol'jin",
			model = 1982882,
			text = {
				en = "The Bloodied Glaive of Vol'jin",
				es = "Guja ensangrentada de Vol'jin",
				de = "Vol'jins blutige Gleve",
				fr = "Glaive de Vol’jin ensanglanté",
				it = "Lama Insanguinata di Vol'jin",
				pt = "A Glaive Ensanguentada de Vol'jin",
				ru = "Окровавленный боевой клинок Вол'джина",
			},
		},
	
		[309497] = {
			readable = "Pile of Disenchanted Metal",
			model = 955847,
			text = {
				en = "Pile of Disenchanted Metal",
				es = "Montón de metal desencantado",
				de = "Haufen entzaubertes Metall",
				fr = "Pile de métal désenchanté",
				it = "Mucchio di Metallo Disincantato",
				pt = "Pilha de Metal Desencantado",
				ru = "Груда потускневшего металла",
			},
		},
	
		[309498] = {
			readable = "Armor Stand",
			model = 197910,
			text = {
				en = "Armor Stand",
				es = "Portaarmaduras",
				de = "Rüstungsständer",
				fr = "Présentoir à armure",
				it = "Supporto per Armatura",
				pt = "Estande de Armaduras",
				ru = "Стойка для доспехов",
				cn = "护甲架",
			},
		},
	
		[309499] = {
			readable = "Tool Barrel",
			model = 950119,
			text = {
				en = "Tool Barrel",
				es = "Barril de herramientas",
				de = "Fass mit Werkzeug",
				fr = "Tonneau à outils",
				it = "Barile di Attrezzi",
				pt = "Barril de Ferramentas",
				ru = "Бочка с инструментами",
				ko = "도구 통",
				cn = "工具桶",
			},
		},
	
		[309505] = {
			readable = "Void Stone",
			model = 2387306,
			text = {
				en = "Void Stone",
				es = "Piedra del Vacío",
				de = "Leerenstein",
				fr = "Pierre de Vide",
				pt = "Pedra do Caos",
				ru = "Камень Бездны",
				ko = "공허의 돌",
				cn = "虚空石",
			},
		},
	
		[309520] = {
			readable = "Naga War Banner",
			model = 1096324,
			text = {
				en = "Naga War Banner",
				es = "Estandarte de guerra naga",
				de = "Nagakriegsbanner",
				fr = "Bannière de guerre naga",
				it = "Stendardo di Guerra dei Naga",
				pt = "Estandarte de Guerra das Nagas",
				ru = "Боевой стяг наг",
				ko = "나가 전쟁 깃발",
			},
		},
	
		[309521] = {
			readable = "Naga War Supplies",
			model = 1096638,
			text = {
				en = "Naga War Supplies",
				es = "Suministros de guerra nagas",
				de = "Kriegsvorräte der Naga",
				fr = "Fournitures de guerre naga",
				it = "Rifornimenti di Guerra dei Naga",
				pt = "Suprimentos de Guerra das Nagas",
				ru = "Припасы наг",
				ko = "나가 전쟁 보급품",
			},
		},
	
		[309522] = {
			readable = "Naga Cage",
			model = 1118155,
			text = {
				en = "Naga Cage",
				es = "Jaula naga",
				de = "Nagakäfig",
				fr = "Cage naga",
				it = "Gabbia dei Naga",
				pt = "Jaula das Nagas",
				ru = "Клетка наг",
				ko = "나가 우리",
			},
		},
	
		[309561] = {
			readable = "Naga War Banner",
			model = 1096324,
			text = {
				en = "Naga War Banner",
				es = "Estandarte de guerra naga",
				de = "Nagakriegsbanner",
				fr = "Bannière de guerre naga",
				pt = "Estandarte de Guerra das Nagas",
				ru = "Боевой стяг наг",
				ko = "나가 전쟁 깃발",
			},
		},
	
		[309562] = {
			readable = "Naga War Supplies",
			model = 1096638,
			text = {
				en = "Naga War Supplies",
				es = "Suministros de guerra nagas",
				de = "Kriegsvorräte der Naga",
				fr = "Fournitures de guerre naga",
				pt = "Suprimentos de Guerra das Nagas",
				ru = "Припасы наг",
				ko = "나가 전쟁 보급품",
			},
		},
	
		[309563] = {
			readable = "Naga Cage",
			model = 1118155,
			text = {
				en = "Naga Cage",
				es = "Jaula naga",
				de = "Nagakäfig",
				fr = "Cage naga",
				pt = "Jaula das Nagas",
				ru = "Клетка наг",
				ko = "나가 우리",
			},
		},
	
		[309564] = {
			readable = "Remnant of the Earthen Ritual",
			model = 1282673,
			text = {
				en = "Remnant of the Earthen Ritual",
				es = "Remanente del ritual de la tierra",
				de = "Überrest des Rituals der Irdenen",
				fr = "Reste du rituel terrestre",
				it = "Resti del Rituale Terrigeno",
				pt = "Resquício do Ritual Terrano",
				ru = "Остаток от ритуала земельников",
				ko = "대지 의식의 잔여물",
				cn = "土灵仪式的残留物",
			},
		},
	
		[309572] = {
			readable = "Antique Telescope",
			model = 985340,
			text = {
				en = "Antique Telescope",
				es = "Telescopio antiguo",
				de = "Antikes Teleskop",
				fr = "Télescope ancien",
				it = "Antico Telescopio",
				pt = "Telescópio Arcaico",
				ru = "Старинный телескоп",
				ko = "골동품 망원경",
				cn = "古董望远镜",
			},
		},
	
		[309589] = {
			readable = "Azerite Shield",
			model = 1630836,
			text = {
				en = "Azerite Shield",
				es = "Escudo de azerita",
				de = "Azeritschild",
				fr = "Bouclier d’azérite",
				it = "Scudo d'Azerite",
				pt = "Escudo de Azerita",
				ru = "Азеритовый щит",
			},
		},
	
		[309657] = {
			readable = "Gunpowder Keg",
			model = 1662881,
			text = {
				en = "Gunpowder Keg",
				es = "Barril de pólvora",
				de = "Schießpulverfass",
				fr = "Baril de poudre à canon",
				it = "Barile di Polvere da Sparo",
				pt = "Barrilete de Pólvora",
				ru = "Бочонок с порохом",
				ko = "화약통",
			},
		},
	
		[309693] = {
			readable = "Naga Cage",
			model = 1118155,
			text = {
				en = "Naga Cage",
				es = "Jaula naga",
				de = "Nagakäfig",
				fr = "Cage naga",
				it = "Gabbia dei Naga",
				pt = "Jaula das Nagas",
				ru = "Клетка наг",
				ko = "나가 우리",
			},
		},
	
		[309697] = {
			readable = "Naga War Banner",
			model = 1096324,
			text = {
				en = "Naga War Banner",
				es = "Estandarte de guerra naga",
				de = "Nagakriegsbanner",
				fr = "Bannière de guerre naga",
				it = "Stendardo di Guerra dei Naga",
				pt = "Estandarte de Guerra das Nagas",
				ru = "Боевой стяг наг",
				ko = "나가 전쟁 깃발",
			},
		},
	
		[309706] = {
			readable = "Seaweed",
			model = 1282723,
			text = {
				en = "Seaweed",
				es = "Algas",
				de = "Seetang",
				fr = "Algue",
				it = "Alga Marina",
				pt = "Algas Marinhas",
				ru = "Водоросли",
			},
		},
	
		[309799] = {
			readable = "Horde Cage",
			model = 195415,
			text = {
				en = "Horde Cage",
				es = "Jaula de la Horda",
				de = "Hordenkäfig",
				fr = "Cage de la Horde",
				it = "Gabbia dell'Orda",
				pt = "Jaula da Horda",
				ru = "Клетка Орды",
				ko = "호드 철창",
				cn = "部落牢笼",
			},
		},
	
		[309821] = {
			readable = "Shred-Master Mk1",
			model = 2036186,
			text = {
				en = "Shred-Master Mk1",
				es = "Supertrituradora Mk1",
				de = "Schreddermeister Mk1",
				fr = "Déchiket-tout Mod. I",
				it = "Tritatutto V1",
				pt = "Retalhomestre 1.0",
				ru = "\"Утиль-жеватор-1\"",
				ko = "만능분쇄기 마크1",
			},
		},
	
		[309881] = {
			readable = "Pile of Wood",
			model = 198389,
			text = {
				en = "Pile of Wood",
				es = "Montón de madera",
				de = "Holzhaufen",
				fr = "Tas de bois",
				it = "Pila di Legna",
				pt = "Pilha de Madeira",
				ru = "Груда древесины",
				ko = "목재 더미",
				cn = "一堆木头",
			},
		},
	
		[309884] = {
			readable = "Plaque",
			model = 358381,
			text = {
				en = "Plaque",
				es = "Placa",
				de = "Plakette",
				ru = "Табличка",
			},
		},
	
		[309886] = {
			readable = "Engine Gearing",
			model = 950737,
			text = {
				en = "Engine Gearing",
				es = "Engranaje de motor",
				de = "Motorteile",
				fr = "Rouages de moteur",
				it = "Ingranaggio di Motore",
				pt = "Peças de Motor",
				ru = "Шестеренки двигателя",
				ko = "엔진 장치",
				cn = "引擎传动装置",
			},
		},
	
		[309893] = {
			readable = "Naga Cage",
			model = 1118155,
			text = {
				en = "Naga Cage",
				es = "Jaula naga",
				de = "Nagakäfig",
				fr = "Cage naga",
				it = "Gabbia dei Naga",
				pt = "Jaula das Nagas",
				ru = "Клетка наг",
				ko = "나가 우리",
				cn = "纳迦牢笼",
			},
		},
	
		[309894] = {
			readable = "Naga War Banner",
			model = 1096324,
			text = {
				en = "Naga War Banner",
				es = "Estandarte de guerra naga",
				de = "Nagakriegsbanner",
				fr = "Bannière de guerre naga",
				it = "Stendardo di Guerra dei Naga",
				pt = "Estandarte de Guerra das Nagas",
				ru = "Боевой стяг наг",
				ko = "나가 전쟁 깃발",
				cn = "纳迦战旗",
			},
		},
	
		[309895] = {
			readable = "Naga War Supplies",
			model = 1096638,
			text = {
				en = "Naga War Supplies",
				es = "Suministros de guerra nagas",
				de = "Kriegsvorräte der Naga",
				fr = "Fournitures de guerre naga",
				it = "Rifornimenti di Guerra dei Naga",
				pt = "Suprimentos de Guerra das Nagas",
				ru = "Припасы наг",
				ko = "나가 전쟁 보급품",
				cn = "纳迦战争物资",
			},
		},
	
		[309896] = {
			readable = "Sef Iwen's Remains",
			model = 204086,
			text = {
				en = "Sef Iwen's Remains",
				de = "Sef Iwens Überreste",
				fr = "Restes de Sef Iwen",
				it = "Resti di Sef Iwen",
				pt = "Restos Mortais de Sef Iwen",
				ru = "Останки Сеф Ивен",
			},
		},
	
		[309901] = {
			readable = "Bundle of Hard Wood",
			model = 198389,
			text = {
				en = "Bundle of Hard Wood",
				de = "Bündel Hartholz",
				fr = "Fagot de bois dur",
				it = "Ciocco di Legno Duro",
				pt = "Fardo de Madeira de Lei",
				ru = "Вязанка твердой древесины",
			},
		},
	
		[309914] = {
			readable = "Plaque",
			model = 970107,
			text = {
				en = "Plaque",
				es = "Placa",
				de = "Plakette",
				it = "Placca",
				pt = "Placa",
				ru = "Табличка",
			},
		},
	
		[309915] = {
			readable = "Reward Glow",
			model = 1003206,
			text = {
				en = "Reward Glow",
				es = "Resplandor de recompensa",
				de = "Belohnungsleuchten",
				fr = "Lueur de récompense",
				it = "Luccichio della Ricompensa",
				pt = "Brilho de Recompensa",
				ru = "Сияние награды",
				ko = "보상 반짝임",
				cn = "奖赏光芒",
			},
		},
	
		[309916] = {
			readable = "Mekkatorque's Battle Plans",
			model = 949619,
			text = {
				en = "Mekkatorque's Battle Plans",
				es = "Planes de batalla de Mekkatorque",
				de = "Mekkadrills Schlachtpläne",
				fr = "Plans de bataille de Mekkanivelle",
				it = "Piani di Battaglia di Gelbin Meccatork",
				pt = "Planos de Batalha do Mekkatorque",
				ru = "Военные планы Меггакрута",
				ko = "멕카토크의 전투 계획서",
			},
		},
	
		[309925] = {
			readable = "Fuel Barrel",
			model = 317157,
			text = {
				en = "Fuel Barrel",
				es = "Barril de combustible",
				de = "Treibstoffbehälter",
				fr = "Baril de carburant",
				it = "Barile di Carburante",
				pt = "Barril de Combustível",
				ru = "Бочка с топливом",
				ko = "연료 통",
				cn = "燃料桶",
			},
		},
})
do ObjectDB[objectID] = objectData; end
