local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	
		[350064] = {
			readable = "Battered Scrollcase",
			model = 3022977,
			text = {
				en = "Battered Scrollcase",
				es = "Estuche de pergaminos maltrecho",
				de = "Lädierter Schriftrollenbehälter",
				fr = "Étui à parchemin endommagé",
				it = "Custodia di Pergamene Rovinata",
				pt = "Estojo de Pergaminhos Surrado",
				ru = "Потрепанный тубус",
				ko = "닳아해진 두루마리함",
				cn = "破损的卷轴盒",
			},
		},
	
		[350065] = {
			readable = "Creased Scroll",
			model = 3022978,
			text = {
				en = "Creased Scroll",
				es = "Pergamino arrugado",
				de = "Zerknitterte Schriftrolle",
				fr = "Parchemin froissé",
				it = "Pergamena Stropicciata",
				pt = "Pergaminho Vincado",
				ru = "Мятый свиток",
				ko = "접힌 두루마리",
				cn = "折皱卷轴",
			},
		},
	
		[350066] = {
			readable = "Dusty Scroll Bundle",
			model = 3045971,
			text = {
				en = "Dusty Scroll Bundle",
				es = "Fardo de pergaminos polvoriento",
				de = "Staubiges Schriftrollenbündel",
				fr = "Paquet de parchemins poussiéreux",
				it = "Fascio di Pergamene Impolverate",
				pt = "Pacote de Pergaminhos Empoeirados",
				ru = "Связка пыльных свитков",
				ko = "먼지투성이 두루마리 묶음",
				cn = "一捆尘封的卷轴",
			},
		},
	
		[350067] = {
			readable = "Tattered Scroll",
			model = 3045973,
			text = {
				en = "Tattered Scroll",
				es = "Pergamino ajado",
				de = "Zerfledderte Schriftrolle",
				fr = "Parchemin en lambeaux",
				it = "Pergamena Lacera",
				pt = "Pergaminho Esfarrapado",
				ru = "Изорванный свиток",
				ko = "너덜너덜한 두루마리",
				cn = "破烂的卷轴",
			},
		},
	
		[350074] = {
			readable = "Construct Parts",
			model = 3036721,
			text = {
				en = "Construct Parts",
				es = "Piezas de ensamblaje",
				de = "Konstruktteile",
				fr = "Membres d’assemblage",
				it = "Pezzi di Costrutti",
				pt = "Peças do Constructo",
				ru = "Части кадавров",
				ko = "피조물 부위",
				cn = "构造体部件",
			},
		},
	
		[350082] = {
			readable = "Rich Elethium Deposit",
			model = 3669080,
			text = {
				en = "Rich Elethium Deposit",
				es = "Depósito rico en eletio",
				de = "Reiches Elethiumvorkommen",
				fr = "Riche gisement d’éléthium",
				it = "Deposito Ricco di Elezio",
				pt = "Depósito de Elétio Abundante",
				ru = "Богатые залежи элетия",
				ko = "풍부한 엘레튬 광맥",
				cn = "富阴铁矿脉",
			},
		},
	
		[350083] = {
			readable = "Bonfire",
			model = 194762,
			text = {
				en = "Bonfire",
				es = "Fogata",
				de = "Feuer",
				fr = "Feu de joie",
				it = "Falò",
				pt = "Fogueira",
				ru = "Костер",
				ko = "장작불",
				cn = "篝火",
			},
		},
	
		[350084] = {
			readable = "Rich Sinvyr Deposit",
			model = 3605309,
			text = {
				en = "Rich Sinvyr Deposit",
				es = "Depósito rico en sinvyr",
				de = "Reiches Sinvyrvorkommen",
				fr = "Riche gisement de vicevyr",
				it = "Deposito Ricco di Peccavyr",
				pt = "Depósito de Pecavyr Abundante",
				ru = "Богатые залежи греховира",
				ko = "풍부한 신비르 광맥",
				cn = "富罪钒矿脉",
			},
		},
	
		[350085] = {
			readable = "Rich Oxxein Deposit",
			model = 3594761,
			text = {
				en = "Rich Oxxein Deposit",
				es = "Depósito rico en oxxeína",
				de = "Reiches Oxxeinvorkommen",
				fr = "Riche gisement d’oxxéine",
				it = "Deposito Ricco di Oxeina",
				pt = "Depósito de Oxxeína Abundante",
				ru = "Богатые залежи оксеина",
				ko = "풍부한 옥세인 광맥",
				cn = "富髓硫矿脉",
			},
		},
	
		[350086] = {
			readable = "Rich Solenium Deposit",
			model = 3725531,
			text = {
				en = "Rich Solenium Deposit",
				es = "Depósito rico en solenio",
				de = "Reiches Soleniumvorkommen",
				fr = "Riche gisement de solénium",
				it = "Deposito Ricco di Solenio",
				pt = "Depósito de Solênio Abundante",
				ru = "Богатые залежи соленита",
				ko = "풍부한 솔레늄 광맥",
				cn = "富珀银矿脉",
			},
		},
	
		[350087] = {
			readable = "Rich Phaedrum Deposit",
			model = 3532322,
			text = {
				en = "Rich Phaedrum Deposit",
				es = "Depósito rico en faedro",
				de = "Reiches Phaedrumvorkommen",
				fr = "Riche gisement de phædrum",
				it = "Deposito Ricco di Fedrio",
				pt = "Depósito de Faedro Abundante",
				ru = "Богатые залежи федрита",
				ko = "풍부한 페이드럼 광맥",
				cn = "富炽钴矿脉",
			},
		},
	
		[350765] = {
			readable = "Flickering Candle",
			model = 3456971,
			text = {
				en = "Flickering Candle",
				es = "Vela titilante",
				de = "Flackernde Kerze",
				fr = "Bougie vacillante",
				it = "Candela Tremolante",
				pt = "Vela Tremeluzente",
				ru = "Мерцающая свеча",
				ko = "깜박이는 양초",
				cn = "摇曳的蜡烛",
			},
		},
	
		[350773] = {
			readable = "Bonewrought Prison",
			model = 3040289,
			text = {
				en = "Bonewrought Prison",
				es = "Prisión huesoforjado",
				de = "Knochengefertigtes Gefängnis",
				fr = "Prison modelée d’os",
				it = "Prigione di Ossabattute",
				pt = "Prisão Forjada em Ossos",
				ru = "Костяная тюрьма",
				ko = "뼈다지 감옥",
				cn = "骨锻牢笼",
			},
		},
	
		[350776] = {
			readable = "Anima Conductor",
			model = 3204690,
			text = {
				en = "Anima Conductor",
				es = "Conductor de ánima",
				de = "Animaleiter",
				fr = "Conducteur d’anima",
				it = "Conduttore d'Animum",
				pt = "Condutor de Ânima",
				ru = "Проводник анимы",
				ko = "령 전도체",
				cn = "心能导流器",
			},
		},
	
		[350777] = {
			readable = "Anima Conductor",
			model = 3158890,
			text = {
				en = "Anima Conductor",
				es = "Conductor de ánima",
				de = "Animaleiter",
				fr = "Conducteur d’anima",
				it = "Conduttore d'Animum",
				pt = "Condutor de Ânima",
				ru = "Проводник анимы",
				ko = "령 전도체",
				cn = "心能导流器",
			},
		},
	
		[350778] = {
			readable = "Siege Ballista",
			model = 3504348,
			text = {
				en = "Siege Ballista",
				es = "Balista de asedio",
				de = "Belagerungsballiste",
				fr = "Baliste de siège",
				it = "Balista d'Assedio",
				pt = "Balestra de Cerco",
				ru = "Осадная баллиста",
				ko = "공성 쇠뇌",
				cn = "攻城弩炮",
			},
		},
	
		[350796] = {
			readable = "Thick Cocoon",
			model = 123285,
			text = {
				en = "Thick Cocoon",
				es = "Crisálida gruesa",
				de = "Dicker Kokon",
				fr = "Cocon épais",
				it = "Bozzolo Spesso",
				pt = "Casulo Espesso",
				ru = "Плотный кокон",
				ko = "두꺼운 고치",
				cn = "厚实的茧",
			},
		},
	
		[350802] = {
			readable = "Web Sealed Chest",
			model = 2123117,
			text = {
				en = "Web Sealed Chest",
				es = "Cofre sellado con telarañas",
				de = "Gespinstversiegelte Truhe",
				fr = "Coffre scellé par de la toile",
				it = "Cassa Sigillata con le Ragnatele",
				pt = "Baú Lacrado com Teia",
				ru = "Опутанный паутиной сундук",
				ko = "거미줄로 뒤덮인 상자",
				cn = "蛛网密封的箱子",
			},
		},
	
		[350803] = {
			readable = "Harpy Totem",
			model = 1115947,
			text = {
				en = "Harpy Totem",
				es = "Tótem de arpía",
				de = "Harpyientotem",
				fr = "Totem de Harpie",
				it = "Totem delle Arpie",
				pt = "Totem de Harpia",
				ru = "Тотем гарпий",
				ko = "하피 토템",
				cn = "鹰身人图腾",
			},
		},
	
		[350804] = {
			readable = "Broken Harp",
			model = 3036171,
			text = {
				en = "Broken Harp",
				es = "Arpa rota",
				de = "Zerbrochene Harfe",
				fr = "Harpe cassée",
				it = "Arpa Rotta",
				pt = "Harpa Partida",
				ru = "Сломанная арфа",
				ko = "부서진 하프",
				cn = "损坏的竖琴",
			},
		},
	
		[350805] = {
			readable = "Necrotic Extractor",
			model = 3058262,
			text = {
				en = "Necrotic Extractor",
				es = "Extractor necrótico",
				de = "Nekrotischer Extraktor",
				fr = "Extracteur nécrotique",
				it = "Estrattore Necrotico",
				pt = "Extrator Necrótico",
				ru = "Некротический экстрактор",
				ko = "괴저 추출기",
				cn = "通灵提取器",
			},
		},
	
		[350806] = {
			readable = "Necrotic Extractor",
			model = 3058263,
			text = {
				en = "Necrotic Extractor",
				es = "Extractor necrótico",
				de = "Nekrotischer Extraktor",
				fr = "Extracteur nécrotique",
				it = "Estrattore Necrotico",
				pt = "Extrator Necrótico",
				ru = "Некротический экстрактор",
				ko = "괴저 추출기",
				cn = "通灵提取器",
			},
		},
	
		[350807] = {
			readable = "Necrotic Extractor",
			model = 3058264,
			text = {
				en = "Necrotic Extractor",
				es = "Extractor necrótico",
				de = "Nekrotischer Extraktor",
				fr = "Extracteur nécrotique",
				it = "Estrattore Necrotico",
				pt = "Extrator Necrótico",
				ru = "Некротический экстрактор",
				ko = "괴저 추출기",
				cn = "通灵提取器",
			},
		},
	
		[350808] = {
			readable = "Necrotic Extractor",
			model = 3067410,
			text = {
				en = "Necrotic Extractor",
				es = "Extractor necrótico",
				de = "Nekrotischer Extraktor",
				fr = "Extracteur nécrotique",
				it = "Estrattore Necrotico",
				pt = "Extrator Necrótico",
				ru = "Некротический экстрактор",
				ko = "괴저 추출기",
				cn = "通灵提取器",
			},
		},
	
		[350810] = {
			readable = "Necrotic Extractor",
			model = 3036644,
			text = {
				en = "Necrotic Extractor",
				es = "Extractor necrótico",
				de = "Nekrotischer Extraktor",
				fr = "Extracteur nécrotique",
				it = "Estrattore Necrotico",
				pt = "Extrator Necrótico",
				ru = "Некротический экстрактор",
				ko = "괴저 추출기",
				cn = "通灵提取器",
			},
		},
	
		[350811] = {
			readable = "Silk Shooter",
			model = 588301,
			text = {
				en = "Silk Shooter",
				es = "Disparador de seda",
				de = "Seidenverschießer",
				fr = "Lance-soie",
				it = "Lanciatore di Seta",
				pt = "Disparador de Seda",
				ru = "Выстрел шелком",
				ko = "명주실 발사기",
				cn = "粘丝发射器",
			},
		},
	
		[350813] = {
			readable = "Rusted Chains",
			model = 875601,
			text = {
				en = "Rusted Chains",
				es = "Cadenas oxidadas",
				de = "Verrostete Ketten",
				fr = "Chaînes rouillées",
				it = "Catene Arrugginite",
				ru = "Ржавые цепи",
				ko = "녹슨 사슬",
				cn = "锈蚀锁链",
				tw = "生鏽鎖鍊",
			},
		},
	
		[350814] = {
			readable = "Old Spring",
			model = 199701,
			text = {
				en = "Old Spring",
				es = "Muelle viejo",
				de = "Alte Feder",
				fr = "Vieux ressort",
				it = "Vecchia Molla",
				ru = "Старая пружина",
				ko = "낡은 용수철",
				cn = "旧弹簧",
				tw = "舊彈簧",
			},
		},
	
		[350815] = {
			readable = "Necrotic Extractor",
			model = 3036645,
			text = {
				en = "Necrotic Extractor",
				es = "Extractor necrótico",
				de = "Nekrotischer Extraktor",
				fr = "Extracteur nécrotique",
				it = "Estrattore Necrotico",
				pt = "Extrator Necrótico",
				ru = "Некротический экстрактор",
				ko = "괴저 추출기",
				cn = "通灵提取器",
			},
		},
	
		[350816] = {
			readable = "Necrotic Extractor",
			model = 3058265,
			text = {
				en = "Necrotic Extractor",
				es = "Extractor necrótico",
				de = "Nekrotischer Extraktor",
				fr = "Extracteur nécrotique",
				it = "Estrattore Necrotico",
				pt = "Extrator Necrótico",
				ru = "Некротический экстрактор",
				ko = "괴저 추출기",
				cn = "通灵提取器",
			},
		},
	
		[350817] = {
			readable = "Necrotic Extractor",
			model = 3067409,
			text = {
				en = "Necrotic Extractor",
				es = "Extractor necrótico",
				de = "Nekrotischer Extraktor",
				fr = "Extracteur nécrotique",
				it = "Estrattore Necrotico",
				pt = "Extrator Necrótico",
				ru = "Некротический экстрактор",
				ko = "괴저 추출기",
				cn = "通灵提取器",
			},
		},
	
		[350886] = {
			readable = "Raw Silkstrider Silk",
			model = 608905,
			text = {
				en = "Raw Silkstrider Silk",
				es = "Seda de zancaseda sin refinar",
				de = "Unverarbeitete Seidenschreiterseide",
				fr = "Soie de trottesoie brute",
				it = "Seta di Passosetoso Grezza",
				pt = "Seda de Pé-de-seda Bruta",
				ru = "Нити шелкоброда",
				ko = "비단성큼걸이 명주",
				cn = "丝行者的生丝",
			},
		},
	
		[350888] = {
			readable = "Cache of the Paragons",
			model = 3189120,
			text = {
				en = "Cache of the Paragons",
				es = "Alijo de los dechados",
				de = "Truhe der Paragons",
				fr = "Cache des parangons",
				it = "Cassa degli Eletti",
				pt = "Baú dos Paragões",
				ru = "Тайник идеалов",
				ko = "용장의 보관함",
				cn = "圣杰宝箱",
			},
		},
	
		[350889] = {
			readable = "Cache of the Archon",
			model = 3189120,
			text = {
				en = "Cache of the Archon",
				es = "Alijo de la Arconte",
				de = "Truhe der Archon",
				fr = "Cache de l’archonte",
				it = "Cassa dell'Arconte",
				pt = "Baú da Arconte",
				ru = "Тайник Архонта",
				ko = "집정관의 보관함",
				cn = "执政官宝箱",
			},
		},
	
		[350922] = {
			readable = "Maldracite Core",
			model = 3307174,
			text = {
				en = "Maldracite Core",
				es = "Núcleo de maldracita",
				de = "Maldrazitkern",
				fr = "Noyau de maldracite",
				it = "Nucleo di Maldracite",
				pt = "Núcleo de Maldracita",
				ru = "Малдрацитовое ядро",
				cn = "玛卓西特之核",
			},
		},
	
		[350947] = {
			readable = "Tasty Offering",
			model = 3152405,
			text = {
				en = "Tasty Offering",
				es = "Ofrenda sabrosa",
				de = "Schmackhafte Opfergabe",
				fr = "Offrande délicieuse",
				it = "Offerta Deliziosa",
				pt = "Oferenda Gostosa",
				ru = "Вкусное подношение",
				ko = "맛있는 공물",
				cn = "美味的祭品",
			},
		},
	
		[350951] = {
			readable = "Pulsing Gorm Eggs",
			model = 3164508,
			text = {
				en = "Pulsing Gorm Eggs",
				es = "Huevos de gorm palpitantes",
				de = "Pulsierende Gormeier",
				fr = "Œufs de gorm vibrants",
				it = "Uova Pulsanti di Gorm",
				pt = "Ovos de Gorm Pulsantes",
				ru = "Пульсирующие яйца гормов",
				ko = "고동치는 게걸충 알",
				cn = "脉动的戈姆之卵",
			},
		},
	
		[350952] = {
			readable = "Pulsing Gorm Egg",
			model = 3164507,
			text = {
				en = "Pulsing Gorm Egg",
				es = "Huevo de gorm palpitante",
				de = "Pulsierendes Gormei",
				fr = "Œuf de gorm vibrant",
				it = "Uovo Pulsante di Gorm",
				pt = "Ovo de Gorm Pulsante",
				ru = "Пульсирующее яйцо горма",
				ko = "고동치는 게걸충 알",
				cn = "脉动的戈姆之卵",
			},
		},
	
		[350972] = {
			readable = "Cell Portcullis Chain",
			model = 2432195,
			text = {
				en = "Cell Portcullis Chain",
				es = "Cadena del rastrillo de la celda",
				de = "Zellenfallgatterkette",
				fr = "Chaîne de herse de cellule",
				it = "Catena della Saracinesca della Cella",
				pt = "Corrente da Ponte Levadiça da Cela",
				ru = "Цепь опускной решетки в камере",
				ko = "감방 창살문 사슬",
				cn = "牢房闸门之链",
			},
		},
	
		[350978] = {
			readable = "Queen's Conservatory Cache",
			icon = 1394946,
			model = 3522547,
			text = {
				en = "Queen's Conservatory Cache",
				es = "Alijo del Invernadero de la Reina",
				de = "Truhe des Konservatoriums der Königin",
				fr = "Cache du jardin d’hiver de la Reine",
				it = "Cassa del Vivaio della Regina",
				pt = "Tesouro do Conservatório da Rainha",
				ru = "Тайник королевского зимнего сада",
				ko = "여왕의 정원 보관함",
				cn = "女王的温室宝箱",
			},
		},
	
		[350979] = {
			readable = "Anima Gateway",
			model = 3159129,
			text = {
				en = "Anima Gateway",
				es = "Portal de ánima",
				de = "Animaportal",
				fr = "Porte d’anima",
				it = "Varco dell'Animum",
				pt = "Portal de Ânima",
				ru = "Врата анимы",
				ko = "령 관문",
				cn = "心能传送门",
			},
		},
	
		[350980] = {
			readable = "Anima Gateway",
			model = 3159129,
			text = {
				en = "Anima Gateway",
				es = "Portal de ánima",
				de = "Animaportal",
				fr = "Porte d’anima",
				it = "Varco dell'Animum",
				pt = "Portal de Ânima",
				ru = "Врата анимы",
				ko = "령 관문",
				cn = "心能传送门",
			},
		},
	
		[350997] = {
			readable = "Pile of Loam",
			model = 204112,
			text = {
				en = "Pile of Loam",
				es = "Montón de marga",
				de = "Lehmhaufen",
				fr = "Tas de terreau",
				it = "Pila di Terriccio",
				pt = "Pilha de Greda",
				ru = "Куча компоста",
				ko = "흙 무더기",
				cn = "一堆壤土",
			},
		},
	
		[350998] = {
			readable = "Old Grimoire",
			model = 965217,
			text = {
				en = "Old Grimoire",
				es = "Grimorio viejo",
				de = "Altes Grimoire",
				fr = "Vieux grimoire",
				it = "Vecchio Grimorio",
				pt = "Grimório Velho",
				ru = "Древний гримуар",
				ko = "오래된 고서",
			},
		},
})
do ObjectDB[objectID] = objectData; end
