local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	
		[233002] = {
			readable = "Ogron Boulder Pile",
			model = 937281,
			text = {
				en = "Ogron Boulder Pile",
				es = "Montón de rocas ogrones",
				de = "Haufen von Ogronfelsen",
				fr = "Pile de rochers ogrons",
				it = "Mucchio di Macigni degli Ogron",
				pt = "Pilha de Pedregulhos Ogron",
				ru = "Куча огронских валунов",
				ko = "오그론 바위 더미",
				cn = "独眼魔巨石堆",
			},
		},
	
		[233004] = {
			readable = "Prisoner Cage",
			model = 609081,
			text = {
				en = "Prisoner Cage",
				es = "Jaula de prisionero",
				de = "Gefangenenkäfig",
				fr = "Cage à prisonnier",
				it = "Gabbia del Prigioniero",
				pt = "Jaula de Prisioneiros",
				ru = "Клетка заключенного",
				ko = "포로 우리",
				cn = "囚笼",
			},
		},
	
		[233005] = {
			readable = "Bloodmaul Cache",
			model = 446675,
			text = {
				en = "Bloodmaul Cache",
				es = "Alijo Machacasangre",
				de = "Schatz der Blutschläger",
				fr = "Cache de la Masse-Sanglante",
				it = "Cassa dei Magliorosso",
				pt = "Baú do Malho Sangrento",
				ru = "Тайник Кровавого Молота",
				ko = "피망치 상자",
				cn = "血槌宝箱",
			},
		},
	
		[233008] = {
			readable = "Nest",
			model = 191835,
			text = {
				en = "Nest",
				es = "Nido",
				fr = "Nid",
				it = "Nido",
				pt = "Ninho",
				ru = "Гнездо",
				ko = "둥지",
				cn = "巢穴",
			},
		},
	
		[233009] = {
			readable = "Auchindoun Window 1",
			model = 1005020,
			text = {
				en = "Auchindoun Window 1",
				it = "Finestra di Auchindoun 1",
				pt = "Auchindoun - Janela 1",
				ko = "아킨둔 창문 1",
				cn = "奥金顿窗户",
			},
		},
	
		[233010] = {
			readable = "Auchindoun Window 2",
			model = 1005017,
			text = {
				en = "Auchindoun Window 2",
				it = "Finestra di Auchindoun 2",
				pt = "Auchindoun - Janela 2",
				ko = "아킨둔 창문 2",
				cn = "奥金顿窗户",
			},
		},
	
		[233015] = {
			readable = "Exit the Shadowlands",
			model = 197017,
			text = {
				en = "Exit the Shadowlands",
				es = "Salir de la Tierra de las Sombras",
				de = "Schattenlande verlassen",
				fr = "Quitter l’Ombreterre",
				it = "Uscita dalle Terretetre",
				pt = "Sair das Terras Sombrias",
				ru = "Выход из Темных Земель",
			},
		},
	
		[233028] = {
			readable = "Tears of the Vale",
			model = 253441,
			text = {
				en = "Tears of the Vale",
				es = "Lágrimas del Valle",
				de = "Tränen des Tals",
				fr = "Larmes du val",
				it = "Lacrime della Vallata",
				pt = "Lágrimas do Vale",
				ru = "Слезы Дола",
			},
		},
	
		[233029] = {
			readable = "Vault of Forbidden Treasures",
			model = 253445,
			text = {
				en = "Vault of Forbidden Treasures",
				es = "Alijo de tesoros prohibidos",
				de = "Tresor der verbotenen Schätze",
				fr = "Caveau des trésors interdits",
				it = "Scrigno di Tesori Proibiti",
				pt = "Cofre de Tesouros Proibidos",
				ru = "Хранилище запретных сокровищ",
			},
		},
	
		[233030] = {
			readable = "Unlocked Stockpile of Pandaren Spoils",
			model = 915531,
			text = {
				en = "Unlocked Stockpile of Pandaren Spoils",
				es = "Reserva desprotegida del botín pandaren",
				de = "Entsicherte Titanentruhe mit Pandarenschätzen",
				fr = "Coffre de butin de Pandarie déverrouillé",
				it = "Scorte Dissigillate di Reliquie dei Pandaren",
				pt = "Reserva Destrancada de Tesouros Pandarênicos",
				ru = "Неохраняемый запас пандаренских трофеев",
			},
		},
	
		[233032] = {
			readable = "Mountain Climber's Pack",
			model = 878854,
			text = {
				en = "Mountain Climber's Pack",
				es = "Mochila de montañero",
				de = "Beutel des Bergsteigers",
				fr = "Sac à dos d’alpiniste",
				it = "Zaino dello Scalatore",
				pt = "Mochila de Alpinista",
				ru = "Набор покорителя гор",
				ko = "산악 등반가의 배낭",
				cn = "登山者的包裹",
			},
		},
	
		[233033] = {
			readable = "Steamwheedle Supplies",
			model = 878856,
			text = {
				en = "Steamwheedle Supplies",
				es = "Suministros de Bonvapor",
				de = "Dampfdruckvorräte",
				fr = "Ravitaillement de Gentepression",
				it = "Rifornimenti degli Spargifumo",
				pt = "Suprimentos de Bondebico",
				ru = "Припасы Хитрой Шестеренки",
				ko = "스팀휘들 보급품",
				cn = "热砂补给品",
			},
		},
	
		[233034] = {
			readable = "Steamwheedle Supplies",
			model = 977078,
			text = {
				en = "Steamwheedle Supplies",
				es = "Suministros de Bonvapor",
				de = "Dampfdruckvorräte",
				fr = "Ravitaillement de Gentepression",
				it = "Rifornimenti degli Spargifumo",
				pt = "Suprimentos de Bondebico",
				ru = "Припасы Хитрой Шестеренки",
				ko = "스팀휘들 보급품",
				cn = "热砂补给品",
			},
		},
	
		[233035] = {
			readable = "Barrel of Harvested Toxin",
			model = 243599,
			text = {
				en = "Barrel of Harvested Toxin",
				es = "Barrica de toxinas recolectadas",
				de = "Fass mit gewonnenem Toxin",
				fr = "Tonneau de toxine récoltée",
				it = "Barile di Tossine",
				pt = "Barril de Toxina Colhida",
				ru = "Бочка с ядом",
				ko = "독소 채집통",
			},
		},
	
		[233036] = {
			readable = "Mysterious Artifact",
			model = 194083,
			text = {
				en = "Mysterious Artifact",
				es = "Artefacto misterioso",
				de = "Mysteriöses Artefakt",
				fr = "Artéfact mystérieux",
				it = "Manufatto Misterioso",
				pt = "Artefato Misterioso",
				ru = "Загадочный артефакт",
			},
		},
	
		[233044] = {
			readable = "Fungus-Covered Chest",
			model = 196989,
			text = {
				en = "Fungus-Covered Chest",
				es = "Cofre cubierto de hongos",
				de = "Pilzbedeckte Truhe",
				fr = "Coffre couvert de moisissures",
				it = "Cassa Ricoperta di Funghi",
				pt = "Baú Coberto de Fungo",
				ru = "Заплесневелый сундук",
				ko = "곰팡이투성이 궤짝",
				cn = "长满真菌的宝箱",
			},
		},
	
		[233046] = {
			readable = "Drained Fungal Heart",
			model = 1064195,
			text = {
				en = "Drained Fungal Heart",
				es = "Corazón de hongos drenado",
				de = "Ausgelaugtes Fungusherz",
				fr = "Cœur fongique drainé",
				it = "Cuore Fungino Prosciugato",
				pt = "Coração Fúngico Drenado",
				ru = "Высохшее грибное сердце",
				ko = "바싹 마른 버섯 심장",
				cn = "脱水的真菌之心",
			},
		},
	
		[233048] = {
			readable = "Brilliant Dreampetal",
			model = 987197,
			text = {
				en = "Brilliant Dreampetal",
				es = "Pétalo de ensueño luminoso",
				de = "Leuchtende Traumblüte",
				fr = "Fronderêve brillant",
				it = "Petalonirico Lucente",
				pt = "Pétala do Sonho Brilhante",
				ru = "Бриллиантовый мечтоцвет",
				ko = "반짝이는 꿈결꽃",
				cn = "闪亮的梦境花瓣",
			},
		},
	
		[233052] = {
			readable = "Steamwheedle Supplies",
			model = 950767,
			text = {
				en = "Steamwheedle Supplies",
				es = "Suministros de Bonvapor",
				de = "Dampfdruckvorräte",
				fr = "Ravitaillement de Gentepression",
				it = "Rifornimenti degli Spargifumo",
				pt = "Suprimentos de Bondebico",
				ru = "Припасы Хитрой Шестеренки",
				ko = "스팀휘들 보급품",
				cn = "热砂补给品",
			},
		},
	
		[233053] = {
			readable = "Ancient Reliquary",
			model = 199748,
			text = {
				en = "Ancient Reliquary",
				es = "Relicario antiguo",
				de = "Uraltes Reliquiar",
				fr = "Relique ancienne",
				it = "Reliquiario Antico",
				pt = "Relicário Antigo",
				ru = "Древний реликварий",
			},
		},
	
		[233056] = {
			readable = "Mark of the Shadowmoon",
			model = 1031064,
			text = {
				en = "Mark of the Shadowmoon",
				es = "Marca de los Sombraluna",
				de = "Mal des Schattenmonds",
				fr = "Marque des Ombrelunes",
				it = "Marchio dei Torvaluna",
				pt = "Marca da Lua Negra",
				ru = "Знак клана Призрачной Луны",
				ko = "어둠달의 징표",
				cn = "影月之印",
			},
		},
	
		[233057] = {
			readable = "Mark of the Bleeding Hollow",
			model = 1031063,
			text = {
				en = "Mark of the Bleeding Hollow",
				es = "Marca de los Foso Sangrante",
				de = "Mal des Blutenden Auges",
				fr = "Marque de l'Orbite-Sanglante",
				it = "Marchio dei Guerci Insanguinati",
				pt = "Marca dos Olhos Sangrentos",
				ru = "Знак клана Кровавой Глазницы",
				ko = "피눈물의 징표",
				cn = "血环之印",
			},
		},
	
		[233073] = {
			readable = "Syth's Bookcase",
			model = 972299,
			text = {
				en = "Syth's Bookcase",
				es = "Mueble para libros de Syth",
				de = "Syths Bücherregal",
				fr = "Bibliothèque de Syth",
				it = "Libreria di Syth",
				pt = "Estante de Syth",
				ru = "Книжный шкаф Сита",
				ko = "시스의 책장",
				cn = "塞斯的书柜",
			},
		},
	
		[233077] = {
			readable = "Maladaar's Focusing Lens",
			model = 201638,
			text = {
				en = "Maladaar's Focusing Lens",
				es = "Lente de enfoque de Maladaar",
				de = "Maladaars Fokuslinse",
				fr = "Lentille de focalisation de Maladaar",
				it = "Lenti di Maladaar",
				pt = "Lentes Focalizadoras de Maladaar",
				ru = "Фокусирующая линза Маладаара",
				ko = "말라다르의 집중 렌즈",
			},
		},
	
		[233079] = {
			readable = "Appropriated Warsong Supplies",
			model = 850517,
			text = {
				en = "Appropriated Warsong Supplies",
				es = "Suministros Grito de Guerra adueñados",
				de = "Requirierte Vorräte des Kriegshymnenklans",
				fr = "Fournitures chanteguerres soustraites",
				it = "Rifornimenti Confiscati dei Cantaguerra",
				pt = "Suprimentos do Brado Guerreiro Apropriados",
				ru = "Конфискованные припасы клана Песни Войны",
				cn = "偷来的战歌补给品",
			},
		},
	
		[233081] = {
			readable = "Large Plot",
			text = {
				en = "Large Plot",
				es = "Parcela grande",
				de = "Großer Bauplatz",
				fr = "Grand terrain",
				it = "Lotto Grande",
				pt = "Terreno Grande",
				ru = "Большой участок",
				ko = "대형 공터",
				cn = "大型空地",
			},
		},
	
		[233083] = {
			readable = "Small Plot",
			text = {
				en = "Small Plot",
				es = "Parcela pequeña",
				de = "Kleiner Bauplatz",
				fr = "Petit terrain",
				it = "Lotto Piccolo",
				pt = "Terreno Pequeno",
				ru = "Маленький участок",
				ko = "소형 공터",
				cn = "小型空地",
			},
		},
	
		[233098] = {
			readable = "Arena Elevator",
			model = 1006533,
			text = {
				en = "Arena Elevator",
				es = "Ascensor de la arena",
				de = "Arenaaufzug",
				fr = "Ascenseur de l’arène",
				it = "Ascensore dell'Arena",
				pt = "Elevador da Arena",
				ru = "Подъемник арены",
				ko = "투기장 승강기",
				cn = "竞技场升降梯",
			},
		},
	
		[233099] = {
			readable = "Wanted Poster",
			model = 979435,
			text = {
				en = "Wanted Poster",
				es = "Cartel de Se busca",
				de = "Steckbrief",
				fr = "Avis de recherche",
				it = "Manifesto dei Ricercati",
				pt = "Cartaz de Procura-se",
				ru = "Плакат \"Разыскивается\"",
				ko = "현상 수배 전단",
			},
		},
	
		[233100] = {
			readable = "Wanted Poster",
			model = 970055,
			text = {
				en = "Wanted Poster",
				es = "Cartel de Se busca",
				de = "Steckbrief",
				fr = "Avis de recherche",
				it = "Manifesto dei Ricercati",
				pt = "Cartaz de Procura-se",
				ru = "Плакат \"Разыскивается\"",
				ko = "현상 수배 전단",
			},
		},
	
		[233101] = {
			readable = "Sunken Fishing Boat",
			model = 574913,
			text = {
				en = "Sunken Fishing Boat",
				es = "Barco de pesca hundido",
				de = "Versunkenes Fischerboot",
				fr = "Bateau de pêche coulé",
				it = "Nave da Pesca Affondata",
				pt = "Barco de Pesca Afundado",
				ru = "Затонувшая рыбацкая лодка",
				ko = "가라앉은 낚싯배",
				cn = "沉没的渔船",
			},
		},
	
		[233102] = {
			readable = "Demonic Portal",
			model = 986958,
			text = {
				en = "Demonic Portal",
				es = "Portal demoníaco",
				de = "Dämonisches Portal",
				fr = "Portail démoniaque",
				it = "Portale Demoniaco",
				pt = "Portal do Demônio",
				ru = "Демонический портал",
				ko = "악마의 차원문",
				cn = "恶魔之门",
			},
		},
	
		[233103] = {
			readable = "Warsong Lockbox",
			model = 1005490,
			text = {
				en = "Warsong Lockbox",
				es = "Arcón Grito de Guerra",
				de = "Schließkassette des Kriegshymnenklans",
				fr = "Coffret chanteguerre",
				it = "Scrigno dei Cantaguerra",
				pt = "Caixinha do Brado Guerreiro",
				ru = "Сейф клана Песни Войны",
				ko = "전쟁노래 금고",
				cn = "战歌保险箱",
			},
		},
	
		[233104] = {
			readable = "Stasis Rune",
			model = 1064385,
			text = {
				en = "Stasis Rune",
				es = "Runa de estasis",
				de = "Stasisrune",
				fr = "Rune de stase",
				it = "Runa di Stasi",
				pt = "Runa da Estase",
				ru = "Руна стазиса",
				ko = "정지장 룬",
				cn = "静滞符文",
			},
		},
	
		[233107] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[233113] = {
			readable = "Warsong Spear",
			model = 874421,
			text = {
				en = "Warsong Spear",
				es = "Lanza Grito de Guerra",
				de = "Speer des Kriegshymnenklans",
				fr = "Lance chanteguerre",
				it = "Lancia dei Cantaguerra",
				pt = "Lança do Brado Guerreiro",
				ru = "Копье клана Песни Войны",
				ko = "전쟁노래 창",
				cn = "战歌长矛",
			},
		},
	
		[233117] = {
			readable = "Frostweed",
			model = 1006584,
			text = {
				en = "Frostweed",
				es = "Verbesina",
				de = "Frostwurz",
				fr = "Givrelette",
				it = "Erba del Gelo",
				pt = "Erválgida",
				ru = "Морозноцвет",
				ko = "서리풀",
				cn = "寒霜草",
			},
		},
	
		[233126] = {
			readable = "Shadowmoon Treasure",
			model = 512025,
			text = {
				en = "Shadowmoon Treasure",
				es = "Tesoro de Sombraluna",
				de = "Schattenmondschatzkiste",
				fr = "Trésor d’Ombrelune",
				it = "Tesoro dei Torvaluna",
				pt = "Tesouro da Lua Negra",
				ru = "Сокровища Призрачной Луны",
				ko = "어둠달 보물",
				cn = "影月宝藏",
			},
		},
	
		[233132] = {
			readable = "Freshwater Clam",
			model = 196998,
			text = {
				en = "Freshwater Clam",
				es = "Almeja de agua dulce",
				de = "Süßwassermuschel",
				fr = "Palourde d’eau douce",
				it = "Mollusco d'Acqua Dolce",
				pt = "Marisco de Água Doce",
				ru = "Пресноводный моллюск",
				ko = "민물조개",
				cn = "淡水蛤蜊",
			},
		},
	
		[233134] = {
			readable = "Golden Kaliri Egg",
			model = 199227,
			text = {
				en = "Golden Kaliri Egg",
				es = "Huevo de kaliri dorado",
				de = "Goldkaliriei",
				fr = "Œuf de kaliri doré",
				it = "Uovo di Kaliri Dorato",
				pt = "Ovo de Kaliri Dourado",
				ru = "Яйцо золотой калири",
				ko = "황금빛 칼리리 알",
				cn = "金色卡利鸟蛋",
			},
		},
	
		[233135] = {
			readable = "Warsong Cache",
			model = 953811,
			text = {
				en = "Warsong Cache",
				es = "Alijo Grito de Guerra",
				de = "Schatz des Kriegshymnenklans",
				fr = "Cache chanteguerre",
				it = "Cassa dei Cantaguerra",
				pt = "Baú do Brado Guerreiro",
				ru = "Тайник клана Песни Войны",
				cn = "战歌宝箱",
			},
		},
	
		[233137] = {
			readable = "Burning Blade Cache",
			icon = 1125255,
			model = 953811,
			text = {
				en = "Burning Blade Cache",
				es = "Alijo del clan Filo Ardiente",
				de = "Schatz der Brennenden Klinge",
				fr = "Cache de la Lame-Ardente",
				it = "Cassa delle Lame Ardenti",
				pt = "Baú da Lâmina Ardente",
				ru = "Тайник клана Пылающего Клинка",
				ko = "불타는 칼날단 보관함",
				cn = "火刃宝箱",
			},
		},
	
		[233138] = {
			readable = "Hardened Thornvine",
			model = 1022436,
			text = {
				en = "Hardened Thornvine",
				es = "Viñaespina endurecida",
				de = "Verhärtete Dornranke",
				fr = "Roncevigne durcie",
				it = "Vignaspina Rinforzata",
				pt = "Vinhespinho Endurecido",
				ru = "Затвердевшая шипастая лоза",
				ko = "굳어진 덩굴가시",
				cn = "硬化棘藤",
			},
		},
	
		[233139] = {
			readable = "Ancient Titan Chest",
			model = 200953,
			text = {
				en = "Ancient Titan Chest",
				es = "Cofre titánico antiguo",
				de = "Uralte Titanentruhe",
				fr = "Coffre de Titan ancien",
				it = "Antica Cassa dei Titani",
				pt = "Baú Titânico Antigo",
				ru = "Древний сундук титанов",
				ko = "고대 티탄 궤짝",
				cn = "上古泰坦宝箱",
			},
		},
	
		[233147] = {
			readable = "Submerged Battery",
			model = 309918,
			text = {
				en = "Submerged Battery",
				es = "Batería sumergida",
				de = "Versunkene Batterie",
				fr = "Batterie submergée",
				it = "Batteria Sommersa",
				pt = "Pilha Submersa",
				ru = "Намокшая батарейка",
				ko = "물에 잠긴 전지",
				cn = "浸水的电池",
			},
		},
	
		[233149] = {
			readable = "Laughing Skull Cache",
			model = 874403,
			text = {
				en = "Laughing Skull Cache",
				es = "Alijo Riecráneos",
				de = "Schatz des Lachenden Schädels",
				fr = "Cache du Crâne-Ricanant",
				it = "Cassa dei Teschio Ridente",
				pt = "Tesouro Gargaveira",
				ru = "Тайник клана Веселого Черепа",
				ko = "웃는 해골 보관함",
				cn = "嘲颅包裹",
			},
		},
	
		[233157] = {
			readable = "Abu'gar's Vitality",
			text = {
				en = "Abu'gar's Vitality",
			},
		},
	
		[233179] = {
			readable = "Goblin Explosives Plunger",
			model = 343855,
			text = {
				en = "Goblin Explosives Plunger",
				es = "Detonador de explosivos goblin",
				de = "Zünder für Goblinsprengstoff",
				fr = "Détonateur d’explosif gobelin",
				it = "Detonatore di Esplosivi dei Goblin",
				pt = "Detonador de Explosivos Goblínico",
				ru = "Гоблинская подрывная машинка",
				ko = "고블린 폭탄 격발기",
				cn = "地精炸弹起爆器",
			},
		},
	
		[233180] = {
			readable = "Iron Horde Bonfire",
			model = 877914,
			text = {
				en = "Iron Horde Bonfire",
				es = "Fogata de la Horda de Hierro",
				de = "Feuer der Eisernen Horde",
				fr = "Feu de joie de la Horde de Fer",
				it = "Falò dell'Orda di Ferro",
				pt = "Fogueira da Horda de Ferro",
				ru = "Большой костер Железной Орды",
				ko = "강철 호드 화톳불",
				cn = "钢铁部落篝火",
			},
		},
	
		[233185] = {
			readable = "Hastily-Written Note",
			model = 936411,
			text = {
				en = "Hastily-Written Note",
				es = "Nota escrita de forma apresurada",
				de = "Hastig geschriebene Nachricht",
				fr = "Note écrite à la hâte",
				it = "Appunto Scritto di Fretta",
				pt = "Bilhete Apressado",
				ru = "Торопливо написанная записка",
				ko = "휘갈겨 쓴 쪽지",
				cn = "匆忙书写的字条",
			},
		},
	
		[233186] = {
			readable = "Garrison Building Barn V3",
			text = {
				en = "Garrison Building Barn V3",
				it = "Edificio Guarnigione - Stalla V3",
				pt = "Prédio do Celeiro da Guarnição V3",
				ko = "외양간 V3",
			},
		},
	
		[233188] = {
			readable = "Garrison Building Horde Barn V3",
			text = {
				en = "Garrison Building Horde Barn V3",
				it = "Edificio Guarnigione dell'Orda - Stalla V3",
				pt = "Prédio do Celeiro da Guarnição da Horda V3",
				ko = "호드 외양간",
			},
		},
	
		[233189] = {
			readable = "Garrison Building Trading Post V3",
			text = {
				en = "Garrison Building Trading Post V3",
				it = "Edificio Guarnigione - Emporio V3",
				pt = "Prédio do Posto Comercial da Guarnição V3",
				ko = "교역소",
			},
		},
	
		[233201] = {
			readable = "Horde Flag",
			model = 200299,
			text = {
				en = "Horde Flag",
				es = "Bandera de la Horda",
				de = "Flagge der Horde",
				fr = "Drapeau de la Horde",
				it = "Bandiera dell'Orda",
				pt = "Bandeira da Horda",
				ru = "Флаг Орды",
				ko = "호드 깃발",
			},
		},
	
		[233202] = {
			readable = "Horde Flag",
			model = 200299,
			text = {
				en = "Horde Flag",
				es = "Bandera de la Horda",
				de = "Flagge der Horde",
				fr = "Drapeau de la Horde",
				it = "Bandiera dell'Orda",
				pt = "Bandeira da Horda",
				ru = "Флаг Орды",
				ko = "호드 깃발",
			},
		},
	
		[233203] = {
			readable = "Horde Flag",
			model = 200299,
			text = {
				en = "Horde Flag",
				es = "Bandera de la Horda",
				de = "Flagge der Horde",
				fr = "Drapeau de la Horde",
				it = "Bandiera dell'Orda",
				pt = "Bandeira da Horda",
				ru = "Флаг Орды",
				ko = "호드 깃발",
			},
		},
	
		[233206] = {
			readable = "Abandoned Cargo",
			icon = 132761,
			model = 875382,
			text = {
				en = "Abandoned Cargo",
				es = "Cargamento abandonado",
				de = "Zurückgelassene Fracht",
				fr = "Chargement abandonné",
				it = "Merce Abbandonata",
				pt = "Carga Abandonada",
				ru = "Брошенный груз",
				ko = "버려진 화물",
				cn = "被遗弃的货箱",
			},
		},
	
		[233218] = {
			readable = "Adventurer's Pack",
			icon = 133633,
			model = 936417,
			text = {
				en = "Adventurer's Pack",
				es = "Mochila de aventurero",
				de = "Bündel eines Abenteurers",
				fr = "Sac à dos de l’aventurier",
				it = "Zaino dell'Avventuriero",
				pt = "Kit do Aventureiro",
				ru = "Сумка искателя приключений",
				ko = "모험가 배낭",
				cn = "冒险者的包裹",
			},
		},
	
		[233222] = {
			readable = "Blademaster Sword",
			model = 969886,
			text = {
				en = "Blademaster Sword",
				es = "Espada de maestro de espadas",
				de = "Schwert des Klingenmeisters",
				fr = "Epée de maître-lame",
				it = "Spada del Maestro di Spade",
				pt = "Espada do Mestre de Espadas",
				ru = "Меч мастера клинка",
				ko = "검귀의 칼",
				cn = "剑圣长剑",
			},
		},
	
		[233224] = {
			readable = "Neka's Poison Flask",
			model = 972295,
			text = {
				en = "Neka's Poison Flask",
				es = "Frasco de veneno de Neka",
				de = "Nekas Giftfläschchen",
				fr = "Flacon de poison de Neka",
				it = "Fiasca di Veleno di Neka",
				pt = "Frasco de Veneno de Neka",
				ru = "Флакон яда Неки",
			},
		},
	
		[233227] = {
			readable = "Overseer Struk's Shield",
			model = 879820,
			text = {
				en = "Overseer Struk's Shield",
				es = "Escudo de la sobrestante Struk",
				de = "Schild von Aufseherin Struk",
				fr = "Bouclier du surveillant Struk",
				it = "Scudo del Sovrintendente Struk",
				pt = "Escudo do Feitor Struk",
				ru = "Щит надзирательницы Струк",
			},
		},
	
		[233228] = {
			readable = "Aitokk's Axe",
			model = 1005449,
			text = {
				en = "Aitokk's Axe",
				es = "Hacha de Aitokk",
				de = "Aitokks Axt",
				fr = "Hache d’Aitokk",
				it = "Ascia di Aitokk",
				pt = "Machado de Aitokk",
				ru = "Топор Айтокка",
			},
		},
	
		[233229] = {
			readable = "Shadow Council Tome of Curses",
			model = 916185,
			text = {
				en = "Shadow Council Tome of Curses",
				es = "Escrito de las maldiciones del Consejo de la Sombra",
				de = "Fluchfoliant des Schattenrats",
				fr = "Tome des malédictions du Conseil des ombres",
				it = "Tomo delle Maledizioni del Concilio dell'Ombra",
				pt = "Tomo de Maldições do Concílio das Sombras",
				ru = "Фолиант проклятий Совета Теней",
				ko = "어둠의 의회 저주의 고서",
			},
		},
	
		[233235] = {
			readable = "Abandoned Fishing Rod",
			model = 243299,
			text = {
				en = "Abandoned Fishing Rod",
				es = "Caña de pescar abandonada",
				de = "Liegen gelassene Angelrute",
				fr = "Canne à pêche abandonnée",
				it = "Bastone da Pesca Abbandonato",
				pt = "Vara de Pescar Abandonada",
				ru = "Брошенная удочка",
				ko = "버려진 낚싯대",
				cn = "被遗弃的鱼竿",
			},
		},
	
		[233241] = {
			readable = "Glowing Cave Mushroom",
			model = 838776,
			text = {
				en = "Glowing Cave Mushroom",
				es = "Champiñón de cueva resplandeciente",
				de = "Leuchtender Höhlenpilz",
				fr = "Champignon luminescent de la caverne",
				it = "Fungo di Caverna Luminoso",
				pt = "Cogumelo da Caverna Brilhante",
				ru = "Сияющий пещерный гриб",
				ko = "빛나는 동굴 버섯",
				cn = "发光的洞穴蘑菇",
			},
		},
	
		[233248] = {
			readable = "Finalize Garrison Plot",
			model = 1003206,
			text = {
				en = "Finalize Garrison Plot",
				es = "Finalizar parcela de la ciudadela",
				de = "Garnisonsgebäude fertigstellen",
				fr = "Valider la construction",
				it = "Finalizzazione Lotto della Guarnigione",
				pt = "Finalizar Terreno da Guarnição",
				ru = "Завершение строительства",
				ko = "주둔지 건물 건설 완료",
			},
		},
	
		[233249] = {
			readable = "Finalize Garrison Plot",
			model = 1003206,
			text = {
				en = "Finalize Garrison Plot",
				es = "Finalizar parcela de la ciudadela",
				de = "Garnisonsgebäude fertigstellen",
				fr = "Valider la construction",
				it = "Finalizzazione Lotto della Guarnigione",
				pt = "Finalizar Terreno da Guarnição",
				ru = "Завершение строительства",
				ko = "주둔지 건물 건설 완료",
				cn = "完成要塞空地建造",
			},
		},
	
		[233250] = {
			readable = "Finalize Garrison Plot",
			model = 1003197,
			text = {
				en = "Finalize Garrison Plot",
				es = "Finalizar parcela de la ciudadela",
				de = "Garnisonsgebäude fertigstellen",
				fr = "Valider la construction",
				it = "Finalizzazione Lotto della Guarnigione",
				pt = "Finalizar Terreno da Guarnição",
				ru = "Завершение строительства",
				ko = "주둔지 건물 건설 완료",
			},
		},
	
		[233251] = {
			readable = "Finalize Garrison Plot",
			model = 1003197,
			text = {
				en = "Finalize Garrison Plot",
				es = "Finalizar parcela de la ciudadela",
				de = "Garnisonsgebäude fertigstellen",
				fr = "Valider la construction",
				it = "Finalizzazione Lotto della Guarnigione",
				pt = "Finalizar Terreno da Guarnição",
				ru = "Завершение строительства",
				ko = "주둔지 건물 건설 완료",
			},
		},
	
		[233263] = {
			readable = "Blessing of the Wolf",
			icon = 442737,
			model = 200024,
			text = {
				en = "Blessing of the Wolf",
				es = "Piedra de chamán",
				de = "Schamanenstein",
				fr = "Pierre chamanique",
				it = "Pietra Sciamanica",
				pt = "Pedra Xamânica",
				ru = "Камень шаманов",
				ko = "주술석",
				cn = "萨满之石",
			},
		},
	
		[233266] = {
			readable = "Garrison Building Horde Mill V3",
			text = {
				en = "Garrison Building Horde Mill V3",
				it = "Edificio Guarnigione dell'Orda - Segheria V3",
				pt = "Prédio do Moinho da Guarnição da Horda V3",
				ko = "호드 제재소",
			},
		},
	
		[233267] = {
			readable = "Garrison Building Mill V3",
			text = {
				en = "Garrison Building Mill V3",
				it = "Edificio Guarnigione - Segheria V3",
				pt = "Prédio do Moinho da Guarnição V3",
				ko = "제재소",
			},
		},
	
		[233268] = {
			readable = "Gem-Encrusted Bloodmaul Jewelry Box",
			model = 253445,
			text = {
				en = "Gem-Encrusted Bloodmaul Jewelry Box",
				es = "Joyero incrustado de gemas Machacasangre",
				de = "Juwelenbesetzte Schmuckschatulle der Blutschläger",
				fr = "Boîte à bijoux de la Masse-Sanglante incrustée de gemmes",
				it = "Scrigno di Gioielli Incrostato dei Magliorosso",
				pt = "Porta-joias Incrustado de Gemas do Malho Sangrento",
				ru = "Украшенная самоцветами шкатулка для драгоценностей клана Кровавого Молота",
				ko = "보석 박힌 피망치 보석 상자",
				cn = "镶满宝石的血槌珠宝盒",
			},
		},
	
		[233280] = {
			readable = "Stoneshamble Basilisk",
			model = 166432,
			text = {
				en = "Stoneshamble Basilisk",
				es = "Basilisco Arrastrapiedras",
				de = "Steinschlurferbasilisk",
				fr = "Basilic traîne-pierre",
				it = "Basilisco Scuotipietre",
				pt = "Basilisco Arrastapedra",
				ru = "Камнелапый василиск",
				ko = "바위가죽 바실리스크",
				cn = "履岩蜥蜴",
			},
		},
	
		[233282] = {
			readable = "Refreshment Table",
			model = 3004389,
			text = {
				en = "Refreshment Table",
				es = "Mesa de refrigerio",
				de = "Gedeckter Tisch",
				fr = "Table à rafraîchissements",
				it = "Tavolo del Rinfresco",
				pt = "Mesa de Refeição",
				ru = "Стол с яствами",
				ko = "원기 회복의 식탁",
				cn = "餐桌",
			},
		},
	
		[233284] = {
			readable = "Shackle",
			model = 191879,
			text = {
				en = "Shackle",
				es = "Grillete",
				de = "Fesseln",
				fr = "Entrave",
				it = "Catene",
				pt = "Agrilhoar",
				ru = "Оковы",
				ko = "족쇄",
				cn = "镣铐",
			},
		},
	
		[233285] = {
			readable = "Portal to Stormshield Stronghold",
			model = 1020713,
			text = {
				en = "Portal to Stormshield Stronghold",
				es = "Portal al Bastión Escudo de Tormenta",
				de = "Portal zur Sturmschildfeste",
				fr = "Portail vers le bastion de Bouclier-des-Tempêtes",
				it = "Portale per la Roccaforte di Scudo del Vento",
				pt = "Portal para a Bastilha Escudo Tonante",
				ru = "Портал в крепость Преграды Ветров",
				cn = "通往暴风之盾堡垒的传送门",
			},
		},
	
		[233291] = {
			readable = "Command Board",
			model = 429104,
			text = {
				en = "Command Board",
				es = "Tablón de mando",
				de = "Kommandotafel",
				fr = "Tableau de commandement",
				it = "Bacheca degli Ordini",
				pt = "Quadro de Comando",
				ru = "Доска приказов",
				ko = "명령 게시판",
				cn = "指令板",
			},
		},
	
		[233296] = {
			readable = "Ancient Ogre Hoard Jar",
			model = 189815,
			text = {
				en = "Ancient Ogre Hoard Jar",
				es = "Tarro antiguo ogro oculto",
				de = "Uralter Ogerschatztopf",
				fr = "Ancienne jarre de trésor ogre",
				it = "Antica Anfora del Tesoro degli Ogre",
				pt = "Jarro do Tesouro Ôgrico Antigo",
				ru = "Кувшин из древнего хранилища огров",
				ko = "고대 오우거 단지",
				cn = "古代食人魔储物罐",
			},
		},
	
		[233308] = {
			readable = "Shackle",
			model = 191879,
			text = {
				en = "Shackle",
				es = "Grillete",
				de = "Fesseln",
				fr = "Entrave",
				it = "Catene",
				pt = "Agrilhoar",
				ru = "Оковы",
				ko = "족쇄",
				cn = "镣铐",
			},
		},
	
		[233310] = {
			readable = "Pristine Lily",
			model = 463996,
			text = {
				en = "Pristine Lily",
				es = "Lirio prístino",
				de = "Makellose Lilie",
				fr = "Lys en parfait état",
				it = "Giglio Intatto",
				pt = "Lírio Impecável",
				ru = "Безупречная лилия",
				ko = "온전한 백합",
			},
		},
	
		[233317] = {
			readable = "Shackle",
			model = 191879,
			text = {
				en = "Shackle",
				es = "Grillete",
				de = "Fesseln",
				fr = "Entrave",
				it = "Catene",
				pt = "Agrilhoar",
				ru = "Оковы",
				ko = "족쇄",
				cn = "镣铐",
			},
		},
	
		[233339] = {
			readable = "Goren Crystals",
			model = 166432,
			text = {
				en = "Goren Crystals",
				es = "Cristales goren",
				de = "Gorenkristalle",
				fr = "Cristaux gorens",
				it = "Cristalli dei Goren",
				pt = "Cristais Goren",
				ru = "Кристаллы горенов",
				ko = "고렌 수정",
				cn = "鬣蜥人水晶",
			},
		},
	
		[233349] = {
			readable = "Warsong Outrider Orders",
			model = 985172,
			text = {
				en = "Warsong Outrider Orders",
				es = "Órdenes de escolta Grito de Guerra",
				de = "Befehle der Kriegshymnenvorhut",
				fr = "Ordres aux voltigeurs chanteguerres",
				it = "Ordini per i Predoni Cantaguerra",
				pt = "Ordens do Pioneiro Brado Guerreiro",
				ru = "Приказы всадникам Песни Войны",
				ko = "전쟁노래 척후병 명령서",
			},
		},
	
		[233350] = {
			readable = "Warsong Command Brief",
			model = 985172,
			text = {
				en = "Warsong Command Brief",
				es = "Informe de mando Grito de Guerra",
				de = "Marschbefehl des Kriegshymnenklans",
				fr = "Ordres au commandement chanteguerre",
				it = "Direttive dei Cantaguerra",
				pt = "Breve Comando do Brado Guerreiro",
				ru = "Распоряжения для командования Песни Войны",
				ko = "전쟁노래 사령관 지령",
				cn = "战歌指令简报",
			},
		},
	
		[233351] = {
			readable = "Mixed Unit Tactics",
			model = 985172,
			text = {
				en = "Mixed Unit Tactics",
				es = "Tácticas de unidades mezcladas",
				de = "Taktiken gemischter Truppen",
				fr = "Tactiques d’unités combinées",
				it = "Tattiche Miste",
				pt = "Tática de Unidades Mistas",
				ru = "Тактические планы",
				ko = "혼합 병력 전술",
				cn = "混合单位战术",
			},
		},
	
		[233356] = {
			readable = "Abandoned Chest",
			model = 219372,
			text = {
				en = "Abandoned Chest",
				es = "Cofre abandonado",
				de = "Zurückgelassene Truhe",
				fr = "Coffre abandonné",
				it = "Forziere Abbandonato",
				pt = "Baú Abandonado",
				ru = "Брошенный сундук",
				ko = "버려진 궤짝",
				cn = "被遗弃的箱子",
			},
		},
	
		[233364] = {
			readable = "Aromatic Incense",
			model = 522113,
			text = {
				en = "Aromatic Incense",
				es = "Incienso aromático",
				de = "Wohlriechender Weihrauch",
				fr = "Encens aromatique",
				it = "Incenso Aromatico",
				pt = "Incenso Aromático",
				ru = "Вороньи благовонья",
				ko = "향기로운 향",
			},
		},
	
		[233369] = {
			readable = "Nazgrel's Cage",
			model = 971072,
			text = {
				en = "Nazgrel's Cage",
				es = "Jaula de Nazgrel",
				de = "Nazgrels Käfig",
				fr = "Cage de Nazgrel",
				it = "Gabbia di Nazgrel",
				pt = "Jaula de Nazgrel",
				ru = "Клетка Назгрела",
				ko = "나즈그렐의 우리",
				cn = "纳兹格雷尔的牢笼",
			},
		},
	
		[233382] = {
			readable = "The Eye of Anzu",
			model = 191830,
			text = {
				en = "The Eye of Anzu",
				es = "El ojo de Anzu",
				de = "Das Auge von Anzu",
				fr = "Oeil d’Anzu",
				it = "Occhio di Anzu",
				pt = "O Olho de Anzu",
				ru = "Глаз Анзу",
				ko = "안주의 눈",
			},
		},
	
		[233383] = {
			readable = "Sacred Feathers",
			model = 199704,
			text = {
				en = "Sacred Feathers",
				es = "Plumas sagradas",
				de = "Heilige Federn",
				fr = "Plumes sacrées",
				it = "Piume Sacre",
				pt = "Plumas Sagradas",
				ru = "Священные перья",
				ko = "신성한 깃털",
			},
		},
	
		[233384] = {
			readable = "Cauldron of Power",
			model = 985294,
			text = {
				en = "Cauldron of Power",
				fr = "Chaudron de puissance",
				ru = "Котел силы",
			},
		},
	
		[233385] = {
			readable = "Scroll of the Ravens",
			model = 968334,
			text = {
				en = "Scroll of the Ravens",
				es = "Pergamino de los cuervos",
				de = "Schriftrolle der Raben",
				fr = "Parchemin des Corbeaux",
				it = "Pergamena dei Corvi",
				pt = "Pergaminho dos Corvos",
				ru = "Свиток Воронов",
				ko = "까마귀의 두루마리",
			},
		},
	
		[233388] = {
			readable = "Blessed Waters",
			model = 972295,
			text = {
				en = "Blessed Waters",
				es = "Agua bendita",
				de = "Geheiligtes Wasser",
				fr = "Eaux bénites",
				it = "Acqua Benedetta",
				pt = "Água Benta",
				ru = "Благословенные воды",
				ko = "축복받은 물",
			},
		},
	
		[233389] = {
			readable = "Nether Beacon",
			model = 192702,
			text = {
				en = "Nether Beacon",
				es = "Baliza abisal",
				de = "Nethersignal",
				fr = "Balise du Néant",
				it = "Faro Fatuo",
				pt = "Sinalizador Etéreo",
				ru = "Маяк Пустоты",
			},
		},
	
		[233391] = {
			readable = "Weaponization Orders",
			model = 929342,
			text = {
				en = "Weaponization Orders",
				es = "Órdenes de armamentización",
				de = "Gronnkontrollbefehle",
				fr = "Ordres d’armement",
				it = "Ordini sugli Armamenti",
				pt = "Ordens de Armamento",
				ru = "Приказы по вооружению",
				ko = "무기화 명령서",
				cn = "武器装配员的命令",
			},
		},
	
		[233432] = {
			readable = "Iron Horde Supply Crate",
			model = 878880,
			text = {
				en = "Iron Horde Supply Crate",
				es = "Cajón de suministros de la Horda de Hierro",
				de = "Vorratskiste der Eisernen Horde",
				fr = "Caisse de fournitures de la Horde de Fer",
				it = "Cassa di Rifornimenti dell'Orda di Ferro",
				pt = "Caixote de Suprimentos da Horda de Ferro",
				ru = "Ящик с припасами Железной Орды",
				ko = "강철 호드 보급품 상자",
				cn = "钢铁部落补给箱",
			},
		},
	
		[233438] = {
			readable = "Ogre Cage",
			model = 971072,
			text = {
				en = "Ogre Cage",
				es = "Jaula ogra",
				de = "Ogerkäfig",
				fr = "Cage ogre",
				it = "Gabbia degli Ogre",
				pt = "Jaula de Ogro",
				ru = "Огрская клетка",
				ko = "오우거 우리",
				cn = "食人魔笼子",
			},
		},
	
		[233452] = {
			readable = "A Pile of Dirt",
			model = 189528,
			text = {
				en = "A Pile of Dirt",
				es = "Un montón de tierra",
				de = "Ein Haufen Dreck",
				fr = "Un tas de terre",
				it = "Mucchio di Terra",
				pt = "Monte de Terra",
				ru = "Куча грязи",
				ko = "흙 더미",
				cn = "一堆泥土",
			},
		},
	
		[233453] = {
			readable = "Goren Egg",
			model = 974969,
			text = {
				en = "Goren Egg",
				es = "Huevo de goren",
				de = "Gorenei",
				fr = "Œuf de goren",
				it = "Uovo di Goren",
				pt = "Ovo de Goren",
				ru = "Яйцо горена",
				ko = "고렌 알",
				cn = "鬣蜥人的蛋",
			},
		},
	
		[233454] = {
			readable = "Ogre Locker",
			model = 953811,
			text = {
				en = "Ogre Locker",
				es = "Baúl ogro",
				de = "Ogerschließkiste",
				fr = "Cantine ogre",
				it = "Medaglione degli Ogre",
				pt = "Baú Ôgrico",
				ru = "Огрский сундук",
				ko = "오우거 사물함",
				cn = "食人魔柜子",
			},
		},
	
		[233455] = {
			readable = "Aged Stone Container",
			model = 446679,
			text = {
				en = "Aged Stone Container",
				es = "Contenedor de piedra envejecida",
				de = "Abgenutzte Steintruhe",
				fr = "Vieux caveau en pierre",
				it = "Contenitore di Pietra Vecchio",
				pt = "Recipiente de Pedra Antigo",
				ru = "Древний каменный сундук",
				ko = "오래된 돌 단지",
				cn = "古老的石质容器",
			},
		},
	
		[233457] = {
			readable = "Adventurer's Staff",
			icon = 135144,
			model = 605629,
			text = {
				en = "Adventurer's Staff",
				es = "Bastón del aventurero",
				de = "Stab eines Abenteurers",
				fr = "Bâton de l’aventurier",
				it = "Bastone dell'Avventuriero",
				pt = "Cajado do Aventureiro",
				ru = "Посох искателя приключений",
				ko = "모험가 지팡이",
				cn = "冒险者的法杖",
			},
		},
	
		[233485] = {
			readable = "Mine",
			text = {
				en = "Mine",
				es = "Mina",
				it = "Miniera",
				pt = "Mina",
				ru = "Рудник",
				ko = "광산",
				cn = "矿井",
			},
		},
	
		[233492] = {
			readable = "Elemental Offering",
			model = 197063,
			text = {
				en = "Elemental Offering",
				es = "Ofrenda elemental",
				de = "Opfergabe an die Elemente",
				fr = "Offrande élémentaire",
				it = "Offerta Elementale",
				pt = "Oferenda Elemental",
				ru = "Подношение духам стихий",
				ko = "정령 공물",
				cn = "元素祭品",
			},
		},
	
		[233493] = {
			readable = "Mine",
			text = {
				en = "Mine",
				es = "Mina",
				it = "Miniera",
				pt = "Mina",
				ru = "Рудник",
				ko = "광산",
				cn = "矿井",
			},
		},
	
		[233499] = {
			readable = "Adventurer's Sack",
			model = 987264,
			text = {
				en = "Adventurer's Sack",
				es = "Bolsa del aventurero",
				de = "Tasche eines Abenteurers",
				fr = "Sac de l’aventurier",
				it = "Sacca dell'Avventuriero",
				pt = "Mochila do Aventureiro",
				ru = "Сума искателя приключений",
				ko = "모험가 자루",
				cn = "冒险者的袋子",
			},
		},
	
		[233501] = {
			readable = "Mysterious Petrified Pod",
			model = 193027,
			text = {
				en = "Mysterious Petrified Pod",
				es = "Vaina petrificada misteriosa",
				de = "Mysteriöse versteinerte Schote",
				fr = "Mystérieuse cosse pétrifiée",
				it = "Baccello Misterioso Pietrificato",
				pt = "Vagem Petrificada Misteriosa",
				ru = "Таинственный окаменевший стручок",
				ko = "수수께끼의 석화된 씨앗",
				cn = "神秘的石化豆荚",
			},
		},
	
		[233504] = {
			readable = "Remains of Grimnir Ashpick",
			model = 197145,
			text = {
				en = "Remains of Grimnir Ashpick",
				es = "Restos de Grimnir Ashpick",
				de = "Überreste von Grimnir Aschpick",
				fr = "Cadavre de Grimnir Cendrepioche",
				it = "Resti di Grimnir Piccacinerea",
				pt = "Restos de Grimnir Cinzafura",
				ru = "Останки Гримнира Пеплоруба",
				ko = "그림니르 애쉬픽의 유해",
				cn = "格里米尔·灰签的遗骸",
			},
		},
	
		[233505] = {
			readable = "Unknown Petrified Egg",
			model = 200964,
			text = {
				en = "Unknown Petrified Egg",
				es = "Huevo petrificado desconocido",
				de = "Unbekanntes versteinertes Ei",
				fr = "Œuf pétrifié non identifié",
				it = "Uovo Pietrificato Sconosciuto",
				pt = "Ovo Petrificado Desconhecido",
				ru = "Неопознанное окаменевшее яйцо",
				ko = "알려지지 않은 석화된 알",
				cn = "未知的石化之蛋",
			},
		},
	
		[233506] = {
			readable = "Abu'gar's Missing Reel",
			model = 984264,
			text = {
				en = "Abu'gar's Missing Reel",
			},
		},
	
		[233507] = {
			readable = "Forgotten Ogre Cache",
			model = 971467,
			text = {
				en = "Forgotten Ogre Cache",
				es = "Alijo ogro olvidado",
				de = "Vergessenes Ogerversteck",
				fr = "Cache ogre oubliée",
				it = "Cassa degli Ogre Dimenticata",
				pt = "Depósito Ôgrico Esquecido",
				ru = "Позабытый огрский тайник",
				ko = "잊혀진 오우거 보관함",
				cn = "被遗忘的食人魔文物",
			},
		},
	
		[233510] = {
			readable = "Redtooth Necklace",
			model = 987178,
			text = {
				en = "Redtooth Necklace",
				es = "Collar de dientes rojos",
				de = "Rotzahnkette",
				fr = "Collier dent-rouge",
				it = "Collana di Denterosso",
				pt = "Colar de Presa-vermelha",
				ru = "Ожерелье с красным зубом",
			},
		},
	
		[233511] = {
			readable = "Adventurer's Pack",
			icon = 133633,
			model = 936417,
			text = {
				en = "Adventurer's Pack",
				es = "Mochila de aventurero",
				de = "Bündel eines Abenteurers",
				fr = "Sac à dos de l’aventurier",
				it = "Zaino dell'Avventuriero",
				pt = "Kit do Aventureiro",
				ru = "Сумка искателя приключений",
				ko = "모험가 배낭",
				cn = "冒险者的包裹",
			},
		},
	
		[233513] = {
			readable = "Forgotten Skull Cache",
			model = 196707,
			text = {
				en = "Forgotten Skull Cache",
				es = "Alijo de cráneos olvidado",
				de = "Vergessenes Schädelversteck",
				fr = "Cache de crânes oubliée",
				it = "Cassa di Teschi Dimenticata",
				pt = "Depósito da Caveira Esquecido",
				ru = "Позабытый тайник с черепами",
				ko = "잊혀진 해골 보관함",
				cn = "被遗忘的嘲颅文物",
			},
		},
	
		[233516] = {
			readable = "Ogre Bust",
			model = 971467,
			text = {
				en = "Ogre Bust",
				es = "Busto de ogro",
				de = "Ogerbüste",
				fr = "Buste d’Ogre",
				it = "Busto di Ogre",
				pt = "Busto de Ogro",
				ru = "Бюст огра",
			},
		},
	
		[233520] = {
			readable = "Remains of Explorer Engineer Toldirk Ashlamp",
			model = 197145,
			text = {
				en = "Remains of Explorer Engineer Toldirk Ashlamp",
				es = "Restos del explorador ingeniero Toldirk Ashlamp",
				de = "Überreste von Erkunder und Ingenieur Toldirk Aschenlampe",
				fr = "Cadavre de l’ingexplorateur Toldirk Lampacendre",
				it = "Resti dell'Ingegnere Esploratore Toldirk Lumecinereo",
				pt = "Restos do Explorador Engenheiro Toldirk Cinzalampa",
				ru = "Останки инженера-исследователя Толдрика Пеплосвета",
				ko = "탐험가 겸 기계공학자 톨더크 애쉬램프의 유해",
				cn = "探测工程师托德卡·灰灯的遗骸",
			},
		},
	
		[233521] = {
			readable = "Warsong Supplies",
			model = 977078,
			text = {
				en = "Warsong Supplies",
				es = "Suministros Grito de Guerra",
				de = "Vorräte des Kriegshymnenklans",
				fr = "Fournitures chanteguerres",
				it = "Rifornimenti dei Cantaguerra",
				pt = "Suprimentos do Brado Guerreiro",
				ru = "Припасы клана Песни Войны",
				ko = "전쟁노래 보급품",
				cn = "战歌补给品",
			},
		},
	
		[233522] = {
			readable = "Obsidian Crystal Formation",
			model = 937012,
			text = {
				en = "Obsidian Crystal Formation",
				es = "Formación de cristal de obsidiana",
				de = "Obsidiankristallformation",
				fr = "Formation de cristaux d’obsidienne",
				it = "Formazione di Cristalli d'Obsidio",
				pt = "Formação de Cristais de Obsidiana",
				ru = "Образование из кристаллов обсидиана",
				ko = "흑요석 수정 결정체",
				cn = "黑曜水晶岩",
			},
		},
	
		[233523] = {
			readable = "Mysterious Petrified Pod",
			model = 193027,
			text = {
				en = "Mysterious Petrified Pod",
				es = "Vaina petrificada misteriosa",
				de = "Mysteriöse versteinerte Schote",
				fr = "Mystérieuse cosse pétrifiée",
				it = "Baccello Misterioso Pietrificato",
				pt = "Vagem Petrificada Misteriosa",
				ru = "Таинственный окаменевший стручок",
				ko = "수수께끼의 석화된 씨앗",
				cn = "神秘的石化豆荚",
			},
		},
	
		[233524] = {
			readable = "Unknown Petrified Egg",
			model = 200964,
			text = {
				en = "Unknown Petrified Egg",
				es = "Huevo petrificado desconocido",
				de = "Unbekanntes versteinertes Ei",
				fr = "Œuf pétrifié non identifié",
				it = "Uovo Pietrificato Sconosciuto",
				pt = "Ovo Petrificado Desconhecido",
				ru = "Неопознанное окаменевшее яйцо",
				ko = "알려지지 않은 석화된 알",
				cn = "未知的石化之蛋",
			},
		},
	
		[233525] = {
			readable = "Botani Essence Seed",
			model = 588947,
			text = {
				en = "Botani Essence Seed",
				es = "Semilla de esencia botani",
				de = "Essenzsamen der Botani",
				fr = "Graine d’essence de botani",
				it = "Seme dell'Essenza dei Botani",
				pt = "Semente da Essência de Botani",
				ru = "Семя сущности ботани",
				ko = "신록 정수 씨앗",
				cn = "木精精华之种",
			},
		},
	
		[233526] = {
			readable = "Ancient Titan Chest",
			model = 200953,
			text = {
				en = "Ancient Titan Chest",
				es = "Cofre titánico antiguo",
				de = "Uralte Titanentruhe",
				fr = "Coffre de Titan ancien",
				it = "Antica Cassa dei Titani",
				pt = "Baú Titânico Antigo",
				ru = "Древний сундук титанов",
				ko = "고대 티탄 궤짝",
				cn = "上古泰坦宝箱",
			},
		},
	
		[233532] = {
			readable = "Bone-Carved Dagger",
			icon = 454058,
			model = 146081,
			text = {
				en = "Bone-Carved Dagger",
				es = "Daga de hueso tallado",
				de = "Geschnitzter Knochendolch",
				fr = "Dague gravée en os",
				it = "Pugnale d'Osso Intagliato",
				pt = "Adaga Esculpida em Osso",
				ru = "Вырезанный из кости кинжал",
				ko = "뼈를 깎아 만든 단검",
				cn = "骨质匕首",
			},
		},
	
		[233539] = {
			readable = "Genedar Debris",
			model = 193781,
			text = {
				en = "Genedar Debris",
				es = "Restos del Xenedar",
				de = "Trümmer der Genedar",
				fr = "Débris du Génédar",
				it = "Detriti della Genedar",
				pt = "Destroços de Genedar",
				ru = "Обломки \"Генедара\"",
				ko = "제네다르 파편",
				cn = "吉尼达尔残骸",
			},
		},
	
		[233549] = {
			readable = "Genedar Debris",
			model = 874639,
			text = {
				en = "Genedar Debris",
				es = "Restos del Xenedar",
				de = "Trümmer der Genedar",
				fr = "Débris du Génédar",
				it = "Detriti della Genedar",
				pt = "Destroços de Genedar",
				ru = "Обломки \"Генедара\"",
				ko = "제네다르 파편",
				cn = "吉尼达尔残骸",
			},
		},
	
		[233550] = {
			readable = "Unknown Petrified Egg",
			model = 200964,
			text = {
				en = "Unknown Petrified Egg",
				es = "Huevo petrificado desconocido",
				de = "Unbekanntes versteinertes Ei",
				fr = "Œuf pétrifié non identifié",
				it = "Uovo Pietrificato Sconosciuto",
				pt = "Ovo Petrificado Desconhecido",
				ru = "Неопознанное окаменевшее яйцо",
				ko = "알려지지 않은 석화된 알",
				cn = "未知的石化之蛋",
			},
		},
	
		[233551] = {
			readable = "Genedar Debris",
			model = 193782,
			text = {
				en = "Genedar Debris",
				es = "Restos del Xenedar",
				de = "Trümmer der Genedar",
				fr = "Débris du Génédar",
				it = "Detriti della Genedar",
				pt = "Destroços de Genedar",
				ru = "Обломки \"Генедара\"",
				ko = "제네다르 파편",
				cn = "吉尼达尔残骸",
			},
		},
	
		[233552] = {
			readable = "Aged Stone Container",
			model = 446679,
			text = {
				en = "Aged Stone Container",
				es = "Contenedor de piedra envejecida",
				de = "Abgenutzte Steintruhe",
				fr = "Vieux caveau en pierre",
				it = "Contenitore di Pietra Vecchio",
				pt = "Recipiente de Pedra Antigo",
				ru = "Древний каменный сундук",
				ko = "오래된 돌 단지",
				cn = "古老的石质容器",
			},
		},
	
		[233553] = {
			readable = "Boulder Pile",
			model = 937281,
			text = {
				en = "Boulder Pile",
				es = "Montón de rocas",
				de = "Haufen Steine",
				fr = "Pile de rochers",
				it = "Mucchio di Macigni",
				pt = "Pilha de Pedregulhos",
				ru = "Груда валунов",
				ko = "바위 더미",
				cn = "巨石堆",
			},
		},
	
		[233554] = {
			readable = "Purpletooth Necklace",
			model = 987179,
			text = {
				en = "Purpletooth Necklace",
				es = "Collar de dientes púrpuras",
				de = "Kette aus violetten Zähnen",
				fr = "Collier dent-violette",
				it = "Collana di Denteviola",
				pt = "Colar de Presa-roxa",
				ru = "Ожерелье с фиолетовым зубом",
			},
		},
	
		[233555] = {
			readable = "Genedar Debris",
			model = 874639,
			text = {
				en = "Genedar Debris",
				es = "Restos del Xenedar",
				de = "Trümmer der Genedar",
				fr = "Débris du Génédar",
				it = "Detriti della Genedar",
				pt = "Destroços de Genedar",
				ru = "Обломки \"Генедара\"",
				ko = "제네다르 파편",
				cn = "吉尼达尔残骸",
			},
		},
	
		[233557] = {
			readable = "Genedar Debris",
			model = 193781,
			text = {
				en = "Genedar Debris",
				es = "Restos del Xenedar",
				de = "Trümmer der Genedar",
				fr = "Débris du Génédar",
				it = "Detriti della Genedar",
				pt = "Destroços de Genedar",
				ru = "Обломки \"Генедара\"",
				ko = "제네다르 파편",
				cn = "吉尼达尔残骸",
			},
		},
	
		[233558] = {
			readable = "Mysterious Petrified Pod",
			model = 193027,
			text = {
				en = "Mysterious Petrified Pod",
				es = "Vaina petrificada misteriosa",
				de = "Mysteriöse versteinerte Schote",
				fr = "Mystérieuse cosse pétrifiée",
				it = "Baccello Misterioso Pietrificato",
				pt = "Vagem Petrificada Misteriosa",
				ru = "Таинственный окаменевший стручок",
				ko = "수수께끼의 석화된 씨앗",
				cn = "神秘的石化豆荚",
			},
		},
	
		[233559] = {
			readable = "Forgotten Skull Cache",
			model = 196707,
			text = {
				en = "Forgotten Skull Cache",
				es = "Alijo de cráneos olvidado",
				de = "Vergessenes Schädelversteck",
				fr = "Cache de crânes oubliée",
				it = "Cassa di Teschi Dimenticata",
				pt = "Depósito da Caveira Esquecido",
				ru = "Позабытый тайник с черепами",
				ko = "잊혀진 해골 보관함",
				cn = "被遗忘的嘲颅文物",
			},
		},
	
		[233560] = {
			readable = "Fragment of Oshu'gun",
			icon = 132781,
			model = 196306,
			text = {
				en = "Fragment of Oshu'gun",
				es = "Fragmento de Oshu'gun",
				de = "Oshu'gunfragment",
				fr = "Fragment d’Oshu’gun",
				it = "Frammento di Oshu'gun",
				pt = "Fragmento de Oshu'gun",
				ru = "Осколок Ошу'гуна",
				ko = "오슈군의 조각",
				cn = "沃舒古碎片",
			},
		},
	
		[233561] = {
			readable = "Pokkar's Thirteenth Axe",
			icon = 132409,
			model = 879808,
			text = {
				en = "Pokkar's Thirteenth Axe",
				es = "Hacha número trece de Pokkar",
				de = "Pokkars dreizehnte Axt",
				fr = "Treizième hache de Pokhar",
				it = "Tredicesima Ascia di Pokkar",
				pt = "Décimo Terceiro Machado de Pokkar",
				ru = "Тринадцатый топор Поккара",
				ko = "폭카르의 열세 번째 도끼",
				cn = "波卡尔的第十三把斧子",
			},
		},
	
		[233566] = {
			readable = "Ashmaul Clam",
			model = 196998,
			text = {
				en = "Ashmaul Clam",
				es = "Almeja Machacabrasas",
				de = "Muschel der Aschehämmer",
				fr = "Palourde cognecendre",
				it = "Bivalve dei Mazzacinerea",
				pt = "Marisco Cinzamalho",
				ru = "Моллюск Молота Ашрана",
			},
		},
	
		[233580] = {
			readable = "First Trial of the Wolfrider",
			model = 985170,
			text = {
				en = "First Trial of the Wolfrider",
				es = "La primera prueba del jinete de lobos",
				de = "Erste Prüfung des Wolfsreiters",
				fr = "Première épreuve du chevaucheur de loup",
				it = "Prima Prova del Cavalcalupi",
				pt = "Primeiro Teste do Cavalgante de Lobo",
				ru = "Первое испытание наездника на волке",
				ko = "늑대기수의 첫 번째 시험",
			},
		},
	
		[233593] = {
			readable = "Polished Saberon Skull",
			icon = 236946,
			model = 979954,
			text = {
				en = "Polished Saberon Skull",
				es = "Calavera de sablerón pulida",
				de = "Polierter Saberonschädel",
				fr = "Crâne de sabron poli",
				it = "Teschio di Saberon Lucidato",
				pt = "Crânio de Saberon Polido",
				ru = "Отполированный череп саблерона",
				ko = "광택나는 서슬니 해골",
				cn = "抛光的刃牙虎人颅骨",
			},
		},
	
		[233594] = {
			readable = "Thukmar's Research",
			model = 929342,
			text = {
				en = "Thukmar's Research",
				es = "Investigación de Thukmar",
				de = "Thukmars Aufzeichnungen",
				fr = "Recherches de Thukmar",
				it = "Appunti di Thukmar",
				pt = "Pesquisa de Thukmar",
				ru = "Сведения Тукмара",
				ko = "투크말의 연구 일지",
				cn = "图卡玛的研究成果",
			},
		},
	
		[233596] = {
			readable = "Complimentary Continental Mana Buffet",
			model = 200954,
			text = {
				en = "Complimentary Continental Mana Buffet",
				es = "Bufé continental de maná de obsequio",
				de = "Üppiges Manabuffet",
				fr = "Buffet de mana continental gratuit",
				it = "Banchetto al Mana Omaggio",
				pt = "Bufê de Mana Continental Grátis",
				ru = "Бесплатный континентальный фуршет из маны",
				ko = "대륙풍 마나 차림상",
				cn = "免费的大陆法力餐",
			},
		},
	
		[233598] = {
			readable = "Elemental Shackles",
			icon = 135033,
			model = 523381,
			text = {
				en = "Elemental Shackles",
				es = "Grilletes elementales",
				de = "Elementarfesseln",
				fr = "Chaînes élémentaires",
				it = "Manette Elementali",
				pt = "Grilhões Elementais",
				ru = "Оковы стихий",
				ko = "정령 족쇄",
				cn = "元素镣铐",
			},
		},
	
		[233599] = {
			readable = "Poison Barrel",
			model = 243600,
			text = {
				en = "Poison Barrel",
				es = "Barril de veneno",
				de = "Giftfass",
				fr = "Tonneau de poison",
				it = "Barile di Veleno",
				pt = "Barril de Veneno",
				ru = "Бочонок с ядом",
				ko = "맹독 통",
				cn = "毒药桶",
			},
		},
	
		[233600] = {
			readable = "Portal to Ashran",
			model = 1036124,
			text = {
				en = "Portal to Ashran",
				es = "Portal a Ashran",
				de = "Portal nach Ashran",
				fr = "Portail vers A’shran",
				it = "Portale per Ashran",
				pt = "Portal para Ashran",
				ru = "Портал на Ашран",
				ko = "아쉬란으로 통하는 차원문",
				cn = "到阿什兰的传送门",
			},
		},
	
		[233601] = {
			readable = "Final Trial of the Wolfrider",
			model = 985172,
			text = {
				en = "Final Trial of the Wolfrider",
				es = "Prueba final del jinete de lobos",
				de = "Letzte Prüfung des Wolfsreiters",
				fr = "Dernière épreuve du chevaucheur de loup",
				it = "Prova Finale del Cavalcalupi",
				pt = "Teste Final do Cavalgante de Lobo",
				ru = "Последнее испытание наездника на волке",
				ko = "늑대기수의 마지막 시험",
				cn = "狼骑兵的最后试炼",
			},
		},
	
		[233604] = {
			readable = "Small Timber",
			model = 848995,
			text = {
				en = "Small Timber",
				es = "Madera pequeña",
				de = "Kleiner Baum",
				fr = "Petit arbre",
				it = "Tronco Piccolo",
				pt = "Lenho Pequeno",
				ru = "Небольшое дерево",
				ko = "작은 나무",
				cn = "小型木料",
			},
		},
	
		[233610] = {
			readable = "Portal to Ashran",
			model = 1036124,
			text = {
				en = "Portal to Ashran",
				es = "Portal a Ashran",
				de = "Portal nach Ashran",
				fr = "Portail vers A’shran",
				it = "Portale per Ashran",
				pt = "Portal para Ashran",
				ru = "Портал на Ашран",
				ko = "아쉬란으로 통하는 차원문",
				cn = "到阿什兰的传送门",
			},
		},
	
		[233611] = {
			readable = "Highmaul Sledge",
			icon = 133040,
			model = 875670,
			text = {
				en = "Highmaul Sledge",
				es = "Almádena de Ogrópolis",
				de = "Hochfelshammer",
				fr = "Merlin de Cognefort",
				it = "Martello degli Altomaglio",
				pt = "Marreta do Malho Imponente",
				ru = "Кувалда Верховного Молота",
				ko = "높은망치 해머",
				cn = "悬槌大锤",
			},
		},
	
		[233613] = {
			readable = "Telaar Defender Shield",
			icon = 134994,
			model = 922572,
			text = {
				en = "Telaar Defender Shield",
				es = "Escudo defensor de Telaar",
				de = "Verteidigungsschild von Telaar",
				fr = "Bouclier de défenseur de Telaar",
				it = "Scudo da Difesa di Telaar",
				pt = "Escudo do Defensor Telaar",
				ru = "Щит телаарского поборника",
				ko = "텔라아르 수호자 방패",
				cn = "塔拉防御护盾",
			},
		},
	
		[233615] = {
			readable = "Portal to Talador",
			model = 1036133,
			text = {
				en = "Portal to Talador",
				es = "Portal a Talador",
				de = "Portal nach Talador",
				fr = "Portail vers Talador",
				it = "Portale per Talador",
				pt = "Portal para Talador",
				ru = "Портал в Таладор",
				ko = "탈라도르로 통하는 차원문",
				cn = "到塔拉多的传送门",
			},
		},
	
		[233617] = {
			readable = "Portal to Gorgrond",
			model = 1036125,
			text = {
				en = "Portal to Gorgrond",
				es = "Portal a Gorgrond",
				de = "Portal nach Gorgrond",
				fr = "Portail vers Gorgrond",
				it = "Portale per Gorgrond",
				pt = "Portal para Gorgrond",
				ru = "Портал в Горгронд",
				ko = "고르그론드로 통하는 차원문",
				cn = "到戈尔隆德的传送门",
			},
		},
	
		[233618] = {
			readable = "Ogre Beads",
			model = 987178,
			text = {
				en = "Ogre Beads",
				es = "Abalorios de ogro",
				de = "Ogerperlen",
				fr = "Perles ogres",
				it = "Catenina degli Ogre",
				pt = "Miçangas Ôgricas",
				ru = "Огрские бусы",
				ko = "오우거 구슬",
				cn = "食人魔念珠",
			},
		},
	
		[233619] = {
			readable = "Portal to Nagrand",
			model = 1036126,
			text = {
				en = "Portal to Nagrand",
				es = "Portal a Nagrand",
				de = "Portal nach Nagrand",
				fr = "Portail vers Nagrand",
				it = "Portale per Nagrand",
				pt = "Portal para Nagrand",
				ru = "Портал в Награнд",
				ko = "나그란드로 통하는 차원문",
				cn = "到纳格兰的传送门",
			},
		},
	
		[233621] = {
			readable = "Second Trial of the Wolfrider",
			model = 985170,
			text = {
				en = "Second Trial of the Wolfrider",
				es = "Segunda prueba del jinete de lobos",
				de = "Zweite Prüfung des Wolfsreiters",
				fr = "Deuxième épreuve du chevaucheur de loup",
				it = "Seconda Prova del Cavalcalupi",
				pt = "Segundo Teste do Cavalgante de Lobo",
				ru = "Второе испытание наездника на волке",
				ko = "늑대기수의 두 번째 시험",
				cn = "狼骑兵的第二个试炼",
			},
		},
	
		[233623] = {
			readable = "Adventurer's Pouch",
			model = 977078,
			text = {
				en = "Adventurer's Pouch",
				es = "Faltriquera de aventurero",
				de = "Beutel eines Abenteurers",
				fr = "Bourse de l’aventurier",
				it = "Borsa dell'Avventuriero",
				pt = "Bolsa do Aventureiro",
				ru = "Кисет искателя приключений",
				cn = "冒险者的钱袋",
			},
		},
	
		[233626] = {
			readable = "Grizzlemaw's Bonepile",
			model = 376264,
			text = {
				en = "Grizzlemaw's Bonepile",
				es = "Montón de huesos de Fauceparda",
				de = "Grauschlunds Knochenhaufen",
				fr = "Pile d’os de Grisegueule",
				it = "Mucchio d'Ossa di Faucebigia",
				pt = "Pilha de Ossos de Bocaina Velha",
				ru = "Кость Седоморда",
				ko = "회색구렁일족 뼈무덤",
				cn = "灰喉的骨头堆",
			},
		},
	
		[233628] = {
			readable = "Portal to Warspear Outpost",
			model = 1020715,
			text = {
				en = "Portal to Warspear Outpost",
				es = "Portal a la Avanzada Lanza de Guerra",
				de = "Portal zum Vorposten des Kriegsspeers",
				fr = "Portail vers l’avant-poste de Fer-de-Lance",
				it = "Portale per l'Avamposto di Lancia da Guerra",
				pt = "Portal para o Posto Avançado Lança de Guerra",
				ru = "Портал на аванпост Копья Войны",
				cn = "通往战争之矛岗哨的传送门",
			},
		},
	
		[233633] = {
			readable = "Unused Wood Pile",
			model = 943615,
			text = {
				en = "Unused Wood Pile",
				es = "Montón de madera sin usar",
				de = "Unangetasteter Holzstapel",
				fr = "Pile de bois inutilisé",
				it = "Pila di Legna Inutilizzata",
				pt = "Pilha de Lenha Não Utilizada",
				ru = "Неиспользуемая куча дерева",
				ko = "사용하지 않은 목재 더미",
				cn = "闲置的木材堆",
			},
		},
	
		[233634] = {
			readable = "Timber",
			model = 848997,
			text = {
				en = "Timber",
				es = "Madera",
				de = "Baum",
				fr = "Arbre",
				it = "Tronco Medio",
				pt = "Lenho",
				ru = "Дерево",
				ko = "나무",
				cn = "木料",
			},
		},
	
		[233635] = {
			readable = "Large Timber",
			model = 848999,
			text = {
				en = "Large Timber",
				es = "Madera grande",
				de = "Großer Baum",
				fr = "Grand arbre",
				it = "Tronco Grande",
				pt = "Lenho Grande",
				ru = "Большое дерево",
				ko = "커다란 나무",
				cn = "大型木料",
			},
		},
	
		[233641] = {
			readable = "Watertight Bag",
			model = 977078,
			text = {
				en = "Watertight Bag",
				es = "Bolsa hermética",
				de = "Wasserdichter Sack",
				fr = "Sac étanche",
				it = "Borsa a Tenuta Stagna",
				pt = "Bolsa à Prova D'água",
				ru = "Водонепроницаемая сумка",
				ko = "물이 새지 않는 가방",
				cn = "防水袋",
			},
		},
	
		[233642] = {
			readable = "Abu'Gar's Favorite Lure",
			model = 251883,
			text = {
				en = "Abu'Gar's Favorite Lure",
			},
		},
	
		[233645] = {
			readable = "Warsong Helm",
			icon = 669453,
			model = 979242,
			text = {
				en = "Warsong Helm",
				es = "Yelmo Grito de Guerra",
				de = "Helm des Kriegshymnenklans",
				fr = "Heaume chanteguerre",
				it = "Elmo dei Cantaguerra",
				pt = "Elmo do Brado Guerreiro",
				ru = "Шлем клана Песни Войны",
				ko = "전쟁노래 투구",
				cn = "战歌头盔",
			},
		},
	
		[233649] = {
			readable = "Gambler's Purse",
			model = 987264,
			text = {
				en = "Gambler's Purse",
				es = "Bolsa de apostador",
				de = "Beutel des Glücksspielers",
				fr = "Bourse du parieur",
				it = "Borsellino dello Scommettitore",
				pt = "Bolsa do Jogador",
				ru = "Кошель игрока",
				ko = "도박꾼의 주머니",
				cn = "赌徒的钱袋",
			},
		},
	
		[233650] = {
			readable = "Adventurer's Mace",
			icon = 133481,
			model = 922568,
			text = {
				en = "Adventurer's Mace",
				es = "Maza de aventurero",
				de = "Streitkolben eines Abenteurers",
				fr = "Masse de l’aventurier",
				it = "Mazza dell'Avventuriero",
				pt = "Maça do Aventureiro",
				ru = "Палица искателя приключений",
				ko = "모험가 철퇴",
				cn = "冒险者的钉锤",
			},
		},
	
		[233651] = {
			readable = "Lost Pendant",
			icon = 648537,
			model = 242727,
			text = {
				en = "Lost Pendant",
				es = "Colgante perdido",
				de = "Verlorener Anhänger",
				fr = "Pendentif perdu",
				it = "Pendente Perduto",
				pt = "Pingente Perdido",
				ru = "Потерянная подвеска",
				ko = "잃어버린 펜던트",
				cn = "遗失的吊坠",
			},
		},
	
		[233658] = {
			readable = "Adventurer's Pouch",
			model = 977078,
			text = {
				en = "Adventurer's Pouch",
				es = "Faltriquera de aventurero",
				de = "Beutel eines Abenteurers",
				fr = "Bourse de l’aventurier",
				it = "Borsa dell'Avventuriero",
				pt = "Bolsa do Aventureiro",
				ru = "Кисет искателя приключений",
				ko = "모험가 주머니",
				cn = "冒险者的钱袋",
			},
		},
	
		[233664] = {
			readable = "Master Surveyor",
			model = 446003,
			text = {
				en = "Master Surveyor",
				es = "Teodolito maestro",
				de = "Meistervermesser",
				fr = "Niveau de géomètre",
				it = "Postazione di Controllo",
				pt = "Inspetor Mestre",
				ru = "\"Главный обозреватель\"",
				ko = "\"한눈에\" 관측 장치",
				cn = "监理视察镜",
			},
		},
	
		[233696] = {
			readable = "Important Exploration Supplies",
			model = 307721,
			text = {
				en = "Important Exploration Supplies",
				es = "Suministros de exploración importantes",
				de = "Wichtige Expeditionsvorräte",
				fr = "Fournitures d’exploration importantes",
				it = "Importanti Rifornimenti per Esplorazioni",
				pt = "Suprimentos de Exploração Importantes",
				ru = "Важные припасы исследователя",
				ko = "탐사용 주요 보급품",
				cn = "重要的探索补给",
			},
		},
	
		[233697] = {
			readable = "Saberon Stash",
			model = 200417,
			text = {
				en = "Saberon Stash",
				es = "Alijo de sablerón",
				de = "Saberonvorrat",
				fr = "Planque de sabron",
				it = "Cassa dei Saberon",
				pt = "Esconderijo Saberon",
				ru = "Клад саблерона",
				ko = "서슬니 보관함",
				cn = "刃牙虎人储物箱",
			},
		},
	
		[233715] = {
			readable = "Goldtoe's Plunder",
			model = 446671,
			text = {
				en = "Goldtoe's Plunder",
				es = "Botín de Dedo Dorado",
				de = "Goldzehs Plündergut",
				fr = "Butin d’Orpion",
				it = "Bottino di Ditodorato",
				pt = "Saque de Dedouro.",
				ru = "Трофеи Золотопалого",
				cn = "金趾的战利品",
			},
		},
	
		[233741] = {
			readable = "Goldtoe's Journal",
			model = 949619,
			text = {
				en = "Goldtoe's Journal",
				es = "Diario de Dedo Dorado",
				de = "Goldzehs Tagebuch",
				fr = "Journal d’Orpion",
				it = "Diario di Ditodorato",
				pt = "Diário de Dedouro",
				ru = "Дневник Золотопалого",
			},
		},
	
		[233757] = {
			readable = "Crucible",
			model = 948321,
			text = {
				en = "Crucible",
				es = "Crisol",
				de = "Tiegel",
				fr = "Creuset",
				it = "Crogiolo",
				pt = "Crisol",
				ru = "Тигель",
				ko = "도가니",
				cn = "坩埚",
			},
		},
	
		[233758] = {
			readable = "Crucible",
			model = 948321,
			text = {
				en = "Crucible",
				es = "Crisol",
				de = "Tiegel",
				fr = "Creuset",
				it = "Crogiolo",
				pt = "Crisol",
				ru = "Тигель",
				ko = "도가니",
				cn = "坩埚",
			},
		},
	
		[233759] = {
			readable = "Crucible",
			model = 1019660,
			text = {
				en = "Crucible",
				es = "Crisol",
				de = "Tiegel",
				fr = "Creuset",
				it = "Crogiolo",
				pt = "Crisol",
				ru = "Тигель",
				ko = "도가니",
				cn = "坩埚",
			},
		},
	
		[233768] = {
			readable = "Pale Elixir",
			model = 892744,
			text = {
				en = "Pale Elixir",
				es = "Elixir pálido",
				de = "Elixier der Fahlen",
				fr = "Élixir de blafard",
				it = "Elisir dei Pallidi",
				pt = "Eixir Pálido",
				ru = "Эликсир бледнокожих",
				ko = "어슴푸레 빛나는 비약",
				cn = "白鬼药剂",
			},
		},
	
		[233769] = {
			readable = "Decorated Headstone",
			model = 190635,
			text = {
				en = "Decorated Headstone",
				es = "Lápida decorada",
				de = "Geschmückter Grabstein",
				fr = "Pierre tombale décorée",
				it = "Lapide Adorna",
				pt = "Lápide Decorada",
				ru = "Резное надгробие",
				cn = "华丽的墓碑",
			},
		},
	
		[233770] = {
			readable = "Decorated Headstone",
			model = 190635,
			text = {
				en = "Decorated Headstone",
				es = "Lápida decorada",
				de = "Geschmückter Grabstein",
				fr = "Pierre tombale décorée",
				it = "Lapide Adorna",
				pt = "Lápide Decorada",
				ru = "Резное надгробие",
			},
		},
	
		[233773] = {
			readable = "Bag of Herbs",
			model = 902296,
			text = {
				en = "Bag of Herbs",
				es = "Bolsa de hierbas",
				de = "Beutel voller Kräuter",
				fr = "Sac d’herbes",
				it = "Sacca di Erbe",
				pt = "Saco de Ervas",
				ru = "Мешок трав",
				ko = "약초 가방",
				cn = "一袋草药",
			},
		},
	
		[233775] = {
			readable = "Engine Access",
			model = 930127,
			text = {
				en = "Engine Access",
				es = "Acceso al motor",
				de = "Antriebskessel",
				fr = "Accès au moteur",
				it = "Accesso al Motore",
				pt = "Acesso ao Motor",
				ru = "Моторный люк",
				ko = "엔진 접근",
				cn = "引擎访问权限",
			},
		},
	
		[233791] = {
			readable = "Power Core",
			model = 964216,
			text = {
				en = "Power Core",
				es = "Núcleo de energía",
				de = "Energiekern",
				fr = "Noyau d’énergie",
				it = "Nucleo Energetico",
				pt = "Núcleo de Força",
				ru = "Сердечник",
				ko = "마력 핵",
				cn = "能源核心",
			},
		},
	
		[233792] = {
			readable = "Pile of Rubble",
			icon = 135236,
			model = 656602,
			text = {
				en = "Pile of Rubble",
				es = "Montón de escombros",
				de = "Trümmerhaufen",
				fr = "Pile de débris",
				it = "Mucchio di Macerie",
				pt = "Pilha de Destroços",
				ru = "Груда обломков",
				ko = "돌 무더기",
				cn = "一堆碎石",
			},
		},
	
		[233797] = {
			readable = "Iron Mooring",
			model = 353152,
			text = {
				en = "Iron Mooring",
				es = "Anclaje de la Horda de Hierro",
				de = "Eiserner Vertäupfahl",
				fr = "Amarres de Fer",
				it = "Ormeggio di Ferro",
				pt = "Plataforma de Lançamento de Ferro",
				ru = "Крепкая швартовка",
				ko = "강철 사슬",
			},
		},
	
		[233803] = {
			readable = "Forgotten Trinket",
			model = 191860,
			text = {
				en = "Forgotten Trinket",
				es = "Abalorio olvidado",
				de = "Vergessenes Schmuckstück",
				fr = "Bijou oublié",
				it = "Monile Dimenticato",
				pt = "Berloque Esquecido",
				ru = "Забытая безделушка",
				ko = "잊혀진 장신구",
				cn = "被遗忘的法器",
			},
		},
	
		[233805] = {
			readable = "Spiced Barbed Trout",
			model = 189088,
			text = {
				en = "Spiced Barbed Trout",
				es = "Trucha espinosa con especias",
				de = "Gewürzte Stachelforelle",
				fr = "Truite épineuse épicée",
				it = "Trota Marmorata Speziata",
				pt = "Truta Barbada Picante",
				ru = "Шипастая форель с пряностями",
				ko = "매콤한 미늘 송어 구이",
			},
		},
	
		[233814] = {
			readable = "Burning Blade Locker",
			model = 953811,
			text = {
				en = "Burning Blade Locker",
				es = "Baúl del clan Filo Ardiente",
				de = "Truhe der Brennenden Klinge",
				fr = "Cantine de la Lame-Ardente",
				it = "Baule delle Lame Ardenti",
				pt = "Cofre da Lâmina Ardente",
				ru = "Сундук клана Пылающего Клинка",
				ko = "불타는 칼날단 사물함",
			},
		},
	
		[233815] = {
			readable = "Burning Blade Locker",
			model = 953811,
			text = {
				en = "Burning Blade Locker",
				es = "Baúl del clan Filo Ardiente",
				de = "Truhe der Brennenden Klinge",
				fr = "Cantine de la Lame-Ardente",
				it = "Baule delle Lame Ardenti",
				pt = "Cofre da Lâmina Ardente",
				ru = "Сундук клана Пылающего Клинка",
				ko = "불타는 칼날단 사물함",
				cn = "火刃宝箱",
			},
		},
	
		[233818] = {
			readable = "Ogre Remains",
			model = 950025,
			text = {
				en = "Ogre Remains",
				es = "Restos de ogro",
				de = "Überreste eines Ogers",
				fr = "Restes d’ogres",
				it = "Resti di Ogre",
				pt = "Restos de Ogro",
				ru = "Останки огра",
				ko = "오우거 유해",
				cn = "食人魔的残骸",
			},
		},
	
		[233824] = {
			readable = "Lost Artifact",
			model = 1003171,
			text = {
				en = "Lost Artifact",
				es = "Artefacto perdido",
				de = "Verlorenes Artefakt",
				fr = "Artéfact perdu",
				it = "Manufatto Perduto",
				pt = "Artefato Perdido",
				ru = "Потерянный артефакт",
				ko = "잃어버린 유물",
				cn = "失落的神器",
			},
		},
	
		[233832] = {
			readable = "Lumber Mill Work Order",
			model = 950137,
			text = {
				en = "Lumber Mill Work Order",
				es = "Pedido del aserradero",
				de = "Arbeitsauftrag des Sägewerks",
				fr = "Commande de la scierie",
				it = "Produzione della Segheria",
				pt = "Ordem de Serviço da Serraria",
				ru = "Заказ с лесопилки",
				ko = "제재소 제품",
				cn = "伐木场产品订单",
			},
		},
	
		[233839] = {
			readable = "Crucible",
			model = 1020886,
			text = {
				en = "Crucible",
				es = "Crisol",
				de = "Tiegel",
				fr = "Creuset",
				it = "Crogiolo",
				pt = "Crisol",
				ru = "Тигель",
				ko = "도가니",
				cn = "坩埚",
			},
		},
	
		[233841] = {
			readable = "Hanging Iron Star",
			model = 1020288,
			text = {
				en = "Hanging Iron Star",
				es = "Estrella de hierro colgante",
				de = "Hängender eiserner Stern",
				fr = "Étoile de Fer suspendue",
				it = "Pirostella Appesa",
				pt = "Estrela de Ferro Pendurada",
				ru = "Подвешенная железная звезда",
				ko = "매달린 강철의 별",
				cn = "悬挂式钢铁之星",
			},
		},
	
		[233843] = {
			readable = "Azerothian Rose",
			model = 254740,
			text = {
				en = "Azerothian Rose",
				es = "Rosa de Azeroth",
				de = "Azerothische Rose",
				fr = "Rose d’Azeroth",
				it = "Rosa Azerotiana",
				pt = "Rosa Azerothiana",
				ru = "Азеротская роза",
			},
		},
	
		[233899] = {
			readable = "XD-57 \"Bullseye\" Guided Rocket Kit",
			model = 953811,
			text = {
				en = "XD-57 \"Bullseye\" Guided Rocket Kit",
				es = "Equipo de cohete guiado \"Diana\" XD-57",
				de = "Baukasten für Lenkrakete XD-57 \"Volltreffer\"",
				fr = "Kit de fusée à guidage thermique XD-57 « Dans le mille »",
				it = "Kit per Razzo Guidato XD-57 \"Occhio di Falco\"",
				pt = "Kit de Míssil Teleguiado \"Namoscas\" XD-57",
				ru = "Самонаводящаяся ракета XD-57 \"Яблочко\"",
				ko = "XD-57 \"백발백중\" 유도 로켓 조립 도구",
				cn = "XD-57“标靶”跟踪导弹工具箱",
			},
		},
	
		[233900] = {
			readable = "\"Skyterror\" Personal Delivery System",
			model = 254420,
			text = {
				en = "\"Skyterror\" Personal Delivery System",
				es = "Sistema de reparto personal \"Aterracielos\"",
				de = "Personentransportsystem \"Himmelsschreck\"",
				fr = "Système de déplacement personnel « Terreur-du-ciel »",
				it = "Sistema di Consegne Personale \"Terrore dei Cieli\"",
				pt = "Sistema de Entregas \"Celesterror\"",
				ru = "Персональная система доставки \"Ужас небес\"",
				ko = "\"하늘공포\" 개인 배달 시스템",
				cn = "“空中霸王”级私人运输系统",
			},
		},
	
		[233901] = {
			readable = "GG-117 Micro-Jetpack",
			model = 334368,
			text = {
				en = "GG-117 Micro-Jetpack",
				es = "Micromochila cohete GG-117",
				de = "Mikrojetpack GG-117",
				fr = "Micro-réacteur dorsal GG-117",
				it = "Micro-Zaino a Reazione GG-117",
				pt = "Minipropulsor GG-117",
				ru = "Реактивный ранец \"GG-117 микро\"",
				ko = "GG-117 초소형 로켓추진기",
			},
		},
	
		[233917] = {
			readable = "Femur of Improbability",
			model = 376266,
			text = {
				en = "Femur of Improbability",
				es = "Fémur de improbabilidad",
				de = "Femur der Unwahrscheinlichkeit",
				fr = "Fémur d’improbabilité",
				it = "Femore dell'Improbabilità",
				pt = "Fêmur da Improbabilidade",
				ru = "Странная бедренная кость",
				ko = "비현실성의 다리뼈",
				cn = "稀有腿骨",
			},
		},
	
		[233922] = {
			readable = "Small Timber",
			model = 984075,
			text = {
				en = "Small Timber",
				es = "Madera pequeña",
				de = "Kleiner Baum",
				fr = "Petit arbre",
				it = "Tronco Piccolo",
				pt = "Lenho Pequeno",
				ru = "Небольшое дерево",
				ko = "작은 나무",
				cn = "小型木料",
			},
		},
	
		[233950] = {
			readable = "Blackhand's Crucible",
			model = 948323,
			text = {
				en = "Blackhand's Crucible",
				es = "Crisol de Puño Negro",
				de = "Schwarzfausts Schmelztiegel",
				fr = "Creuset de Main-Noire",
				it = "Crogiolo di Manonera",
				pt = "Crisol do Mão Negra",
				ru = "Тигель Чернорука",
				ko = "블랙핸드의 도가니",
				cn = "黑手的熔炉",
			},
		},
	
		[233951] = {
			readable = "Blackhand's Crucible",
			model = 948323,
			text = {
				en = "Blackhand's Crucible",
				es = "Crisol de Puño Negro",
				de = "Schwarzfausts Schmelztiegel",
				fr = "Creuset de Main-Noire",
				it = "Crogiolo di Manonera",
				pt = "Crisol do Mão Negra",
				ru = "Тигель Чернорука",
				ko = "블랙핸드의 도가니",
				cn = "黑手的熔炉",
			},
		},
	
		[233952] = {
			readable = "Blackhand's Crucible",
			model = 948323,
			text = {
				en = "Blackhand's Crucible",
				es = "Crisol de Puño Negro",
				de = "Schwarzfausts Schmelztiegel",
				fr = "Creuset de Main-Noire",
				it = "Crogiolo di Manonera",
				pt = "Crisol do Mão Negra",
				ru = "Тигель Чернорука",
				ko = "블랙핸드의 도가니",
				cn = "黑手的熔炉",
			},
		},
	
		[233953] = {
			readable = "Blackhand's Crucible",
			model = 948323,
			text = {
				en = "Blackhand's Crucible",
				es = "Crisol de Puño Negro",
				de = "Schwarzfausts Schmelztiegel",
				fr = "Creuset de Main-Noire",
				it = "Crogiolo di Manonera",
				pt = "Crisol do Mão Negra",
				ru = "Тигель Чернорука",
				ko = "블랙핸드의 도가니",
				cn = "黑手的熔炉",
			},
		},
	
		[233954] = {
			readable = "Blackhand's Crucible",
			model = 948323,
			text = {
				en = "Blackhand's Crucible",
				es = "Crisol de Puño Negro",
				de = "Schwarzfausts Schmelztiegel",
				fr = "Creuset de Main-Noire",
				it = "Crogiolo di Manonera",
				pt = "Crisol do Mão Negra",
				ru = "Тигель Чернорука",
				ko = "블랙핸드의 도가니",
				cn = "黑手的熔炉",
			},
		},
	
		[233956] = {
			readable = "Bloody Blade",
			model = 969884,
			text = {
				en = "Bloody Blade",
				es = "Hoja ensangrentada",
				de = "Blutige Klinge",
				fr = "Lame ensanglantée",
				it = "Lama Insanguinata",
				pt = "Lâmina Sangrenta",
				ru = "Кровавый клинок",
				ko = "피투성이 칼",
				cn = "染血利刃",
			},
		},
	
		[233957] = {
			readable = "Garrison Building Under Construction V1",
			text = {
				en = "Garrison Building Under Construction V1",
				de = "Garnisonsgebäude im Bau V1",
				it = "Edificio Guarnigione - in Costruzione V1",
				pt = "Prédio da Guarnição em Construção V1",
				ru = "Недостроенное здание гарнизона 1-го уровня",
				ko = "주둔지 건물 건설 중 V1",
			},
		},
	
		[233958] = {
			readable = "Garrison Building Under Construction V1",
			text = {
				en = "Garrison Building Under Construction V1",
				de = "Garnisonsgebäude im Bau V1",
				it = "Edificio Guarnigione - in Costruzione V1",
				pt = "Prédio da Guarnição em Construção V1",
				ru = "Недостроенное здание гарнизона 1-го уровня",
				ko = "주둔지 건물 건설 중 V1",
			},
		},
	
		[233973] = {
			readable = "Bounty of the Elements",
			model = 446679,
			text = {
				en = "Bounty of the Elements",
				es = "Recompensa de los elementos",
				de = "Güte der Elemente",
				fr = "Butin des éléments",
				it = "Bottino degli Elementi",
				pt = "Recompensa dos Elementos",
				ru = "Награда духов стихий",
				ko = "정령의 전리품",
				cn = "元素的宝藏",
			},
		},
	
		[233975] = {
			readable = "Rooby's Roo",
			model = 1011411,
			text = {
				en = "Rooby's Roo",
				es = "Roosca de Rooby",
				de = "Scubis Du-Du",
				fr = "Roubie Rou",
				it = "Regalino di Rooby",
				pt = "Buu do Scruby",
				ru = "Руби Ру",
				ko = "루비의 응가",
				cn = "鲁比的洛洛",
			},
		},
	
		[233978] = {
			readable = "Green Hills of Stranglethorn",
			model = 936378,
			text = {
				en = "Green Hills of Stranglethorn",
				es = "Las verdes colinas de Tuercespina",
				de = "Die Grünen Hügel des Schlingendorntals",
				fr = "Les vertes collines de Strangleronce",
				it = "Verdi Colline di Rovotorto",
				pt = "Grande Espinhaço: Veredas",
				ru = "Зеленые холмы Тернистой долины",
				ko = "가시덤불 골짜기의 푸른 언덕",
				cn = "荆棘谷的青山",
			},
		},
	
		[233996] = {
			readable = "Old Wanted Poster",
			model = 199424,
			text = {
				en = "Old Wanted Poster",
				es = "Cartel viejo de Se busca",
				de = "Alter Steckbrief",
				fr = "Vieil avis de recherche",
				it = "Vecchio Manifesto dei Ricercati",
				pt = "Cartaz de Procura-se Antigo",
				ru = "Старый плакат \"Разыскивается\"",
				cn = "旧通缉布告",
			},
		},
	
		[233997] = {
			readable = "Small Note",
			model = 936413,
			text = {
				en = "Small Note",
				es = "Nota pequeña",
				de = "Kleiner Zettel",
				fr = "Petite note",
				it = "Piccola Annotazione",
				pt = "Mensagem Pequena",
				ru = "Маленькая записка",
				cn = "小纸条",
			},
		},
	
		[233998] = {
			readable = "Portal to Ashran: Stormshield",
			model = 1020713,
			text = {
				en = "Portal to Ashran: Stormshield",
				ru = "Портал в Ашран: Преграда Ветров",
			},
		},
})
do ObjectDB[objectID] = objectData; end
