local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	
		[351335] = {
			readable = "Herbert's Spellbook",
			model = 936380,
			text = {
				en = "Herbert's Spellbook",
				de = "Herberts Zauberbuch",
				fr = "Grimoire d’Herbert",
				ru = "Книга заклинаний Герберта",
			},
		},
	
		[351340] = {
			readable = "Zerekriss, Maldraxxus",
			model = 3517396,
			text = {
				en = "Zerekriss, Maldraxxus",
				ru = "\"Зерекрисс\", Малдраксус",
				ko = "제레크리스 - 말드락서스",
				cn = "泽雷克利斯，玛卓克萨斯",
			},
		},
	
		[351343] = {
			readable = "Nurakkir, House of Eyes",
			model = 3517398,
			text = {
				en = "Nurakkir, House of Eyes",
				es = "Nurakkir, Casa de los Ojos",
				de = "Nurakkir, Haus der Augen",
				fr = "Nurakkir, maison des Yeux",
				it = "Nurakkir, Casata degli Occhi",
				pt = "Nurakkir, Casa dos Olhos",
				ru = "\"Нураккир\", дом Глаз",
				ko = "누락키르 - 눈의 의회",
				cn = "努拉基尔，锐眼密院",
			},
		},
	
		[351344] = {
			readable = "Exoramas, House of Rituals",
			model = 3517399,
			text = {
				en = "Exoramas, House of Rituals",
				es = "Exoramas, Casa de los Rituales",
				de = "Exoramas, Haus der Rituale",
				fr = "Exoramas, maison des Rituels",
				it = "Exoramas, Casata dei Rituali",
				pt = "Exoramas, Casa dos Rituais",
				ru = "Экзорамас, дом Ритуалов",
				ko = "엑소라마스 - 의식의 의회",
				cn = "埃索拉玛斯，祭仪密院",
			},
		},
	
		[351346] = {
			readable = "Sixfold Recluse, House of Constructs",
			model = 3517397,
			text = {
				en = "Sixfold Recluse, House of Constructs",
				es = "Reclusa de Seisvueltas, Casa de los Ensamblajes",
				de = "Sechsbeinpass, Haus der Konstrukte",
				fr = "Retraite Sextuple, maison des Assemblages",
				it = "Eremo Svenfold, Casata dei Costrutti",
				pt = "Remanso de Seis, Casa dos Constructos",
				ru = "Прибежище Шестикрата, дом Кадавров",
				ko = "식스폴드의 은둔지 - 피조물의 의회",
				cn = "六叠的隐居处，造物密院",
			},
		},
	
		[351348] = {
			readable = "Battered Weapon",
			model = 3036595,
			text = {
				en = "Battered Weapon",
				es = "Arma maltrecha",
				de = "Ramponierte Waffe",
				fr = "Arme endommagée",
				it = "Arma Rovinata",
				pt = "Arma Surrada",
				ru = "Видавшее виды оружие",
				ko = "낡은 무기",
				cn = "破旧的武器",
			},
		},
	
		[351419] = {
			readable = "Seat of the Primus",
			model = 3511089,
			text = {
				en = "Seat of the Primus",
				es = "Trono del Prelado",
				de = "Sitz des Primus",
				fr = "Siège du Primat",
				it = "Seggio del Primus",
				pt = "Trono do Prócer",
				ru = "Престол Примаса",
				ko = "시초자의 권좌",
				cn = "兵主之座",
			},
		},
	
		[351421] = {
			readable = "Seat of the Primus",
			model = 3511089,
			text = {
				en = "Seat of the Primus",
				es = "Trono del Prelado",
				de = "Sitz des Primus",
				fr = "Siège du Primat",
				it = "Seggio del Primus",
				pt = "Trono do Prócer",
				ru = "Престол Примаса",
				ko = "시초자의 권좌",
				cn = "兵主之座",
			},
		},
	
		[351423] = {
			readable = "Necrotic Altar",
			model = 1139506,
			text = {
				en = "Necrotic Altar",
				de = "Nekrotischer Altar",
				fr = "Autel nécrotique",
				pt = "Altar Necrótico",
				ru = "Некротический алтарь",
				ko = "괴저의 제단",
			},
		},
	
		[351425] = {
			readable = "Discarded Harp",
			model = 3036171,
			text = {
				en = "Discarded Harp",
				es = "Arpa desechada",
				de = "Weggeworfene Harfe",
				fr = "Harpe abandonnée",
				it = "Arpa Scartata",
				pt = "Harpa Descartada",
				ru = "Брошенная арфа",
				ko = "버려진 하프",
				cn = "丢弃的竖琴",
			},
		},
	
		[351426] = {
			readable = "Withering Hemlock",
			model = 1784467,
			text = {
				en = "Withering Hemlock",
				es = "Cicuta marchita",
				de = "Verdorrender Schierling",
				fr = "Ciguë flétrie",
				it = "Cicuta Secca",
				pt = "Cicuta Murcha",
				ru = "Иссохший болиголов",
				ko = "메마른 독미나리",
			},
		},
	
		[351427] = {
			readable = "Very Large Silk Bundle",
			model = 608905,
			text = {
				en = "Very Large Silk Bundle",
				es = "Fardo de seda muy grande",
				de = "Sehr großes Seidenbündel",
				fr = "Très gros paquet de soie",
				it = "Fascio di Seta Davvero Grande",
				pt = "Pacote de Seda Enorme",
				ru = "Очень большая куча шелка",
				ko = "아주 큰 비단 꾸러미",
				cn = "超大的一捆丝",
			},
		},
	
		[351431] = {
			readable = "Cage of Humility",
			model = 2981868,
			text = {
				en = "Cage of Humility",
				es = "Jaula de humildad",
				de = "Käfig der Demut",
				fr = "Cage d’humilité",
				it = "Gabbia dell'Umiltà",
				pt = "Jaula da Humildade",
				ru = "Клетка смирения",
				ko = "겸손의 우리",
				cn = "谦逊牢笼",
			},
		},
	
		[351467] = {
			readable = "Faded Epitaph",
			model = 3036585,
			text = {
				en = "Faded Epitaph",
				es = "Epitafio desgastado",
				de = "Verblasste Inschrift",
				fr = "Épitaphe effacée",
				it = "Epitaffio Sbiadito",
				pt = "Epitáfio Esmaecido",
				ru = "Полустертая эпитафия",
				ko = "빛바랜 묘비",
				cn = "风化的碑铭",
			},
		},
	
		[351469] = {
			readable = "Death Blossom",
			model = 3501537,
			text = {
				en = "Death Blossom",
				es = "Estrella mortal",
				de = "Todesblüte",
				fr = "Fatalée",
				it = "Bocciolo di Morte",
				pt = "Botão-da-morte",
				ru = "Смертоцвет",
				ko = "죽음의 꽃",
				cn = "绽亡花",
			},
		},
	
		[351470] = {
			readable = "Death Blossom",
			model = 3501540,
			text = {
				en = "Death Blossom",
				es = "Estrella mortal",
				de = "Todesblüte",
				fr = "Fatalée",
				it = "Bocciolo di Morte",
				pt = "Botão-da-morte",
				ru = "Смертоцвет",
				ko = "죽음의 꽃",
				cn = "绽亡花",
			},
		},
	
		[351471] = {
			readable = "Death Blossom",
			model = 3501539,
			text = {
				en = "Death Blossom",
				es = "Estrella mortal",
				de = "Todesblüte",
				fr = "Fatalée",
				it = "Bocciolo di Morte",
				pt = "Botão-da-morte",
				ru = "Смертоцвет",
				ko = "죽음의 꽃",
				cn = "绽亡花",
			},
		},
	
		[351473] = {
			readable = "Droplets of Anima",
			model = 3187918,
			text = {
				en = "Droplets of Anima",
				es = "Gotas de ánima",
				de = "Animatröpfchen",
				fr = "Gouttelettes d’anima",
				it = "Goccioline d'Animum",
				pt = "Gotículas de Ânima",
				ru = "Остатки анимы",
				ko = "령 물방울",
				cn = "心能液滴",
			},
		},
	
		[351474] = {
			readable = "Faded Epitaph",
			model = 3036583,
			text = {
				en = "Faded Epitaph",
				es = "Epitafio desgastado",
				de = "Verblasste Inschrift",
				fr = "Épitaphe effacée",
				it = "Epitaffio Sbiadito",
				pt = "Epitáfio Esmaecido",
				ru = "Полустертая эпитафия",
				ko = "빛바랜 묘비",
				cn = "风化的碑铭",
			},
		},
	
		[351476] = {
			readable = "Ogre Runestone",
			model = 1116038,
			text = {
				en = "Ogre Runestone",
				es = "Piedra rúnica ogra",
				de = "Ogerrunenstein",
				fr = "Pierre runique ogre",
				it = "Pietra Runica degli Ogre",
				pt = "Pedra Rúnica Ôgrica",
				ru = "Огрский рунический камень",
				ko = "오우거 룬석",
			},
		},
	
		[351477] = {
			readable = "Catapult",
			model = 920781,
			text = {
				en = "Catapult",
				es = "Catapulta",
				de = "Katapult",
				fr = "Catapulte",
				it = "Catapulta",
				pt = "Catapulta",
				ru = "Катапульта",
				ko = "투석기",
			},
		},
	
		[351478] = {
			readable = "Faded Epitaph",
			model = 3036576,
			text = {
				en = "Faded Epitaph",
				es = "Epitafio desgastado",
				de = "Verblasste Inschrift",
				fr = "Épitaphe effacée",
				it = "Epitaffio Sbiadito",
				pt = "Epitáfio Esmaecido",
				ru = "Полустертая эпитафия",
				ko = "빛바랜 묘비",
				cn = "风化的碑铭",
			},
		},
	
		[351479] = {
			readable = "Faded Epitaph",
			model = 3038200,
			text = {
				en = "Faded Epitaph",
				es = "Epitafio desgastado",
				de = "Verblasste Inschrift",
				fr = "Épitaphe effacée",
				it = "Epitaffio Sbiadito",
				pt = "Epitáfio Esmaecido",
				ru = "Полустертая эпитафия",
				ko = "빛바랜 묘비",
				cn = "风化的碑铭",
			},
		},
	
		[351481] = {
			readable = "Jammed Door",
			model = 3059793,
			text = {
				en = "Jammed Door",
				es = "Puerta atascada",
				de = "Blockierte Tür",
				fr = "Porte bloquée",
				it = "Porta Bloccata",
				pt = "Porta Emperrada",
				ru = "Заклинившая дверь",
				ko = "고장 난 문",
				cn = "卡住的门",
			},
		},
	
		[351487] = {
			readable = "Secret Treasure",
			model = 3597238,
			text = {
				en = "Secret Treasure",
				es = "Tesoro secreto",
				de = "Geheimer Schatz",
				fr = "Trésor secret",
				it = "Tesoro Segreto",
				pt = "Tesouro Secreto",
				ru = "Спрятанное сокровище",
				ko = "비밀 보물",
				cn = "秘密财宝",
			},
		},
	
		[351540] = {
			readable = "Secret Treasure",
			model = 3597238,
			text = {
				en = "Secret Treasure",
				es = "Tesoro secreto",
				de = "Geheimer Schatz",
				fr = "Trésor secret",
				it = "Tesoro Segreto",
				pt = "Tesouro Secreto",
				ru = "Спрятанное сокровище",
				ko = "비밀 보물",
				cn = "秘密财宝",
			},
		},
	
		[351541] = {
			readable = "Secret Treasure",
			model = 3597238,
			text = {
				en = "Secret Treasure",
				es = "Tesoro secreto",
				de = "Geheimer Schatz",
				fr = "Trésor secret",
				it = "Tesoro Segreto",
				pt = "Tesouro Secreto",
				ru = "Спрятанное сокровище",
				ko = "비밀 보물",
				cn = "秘密财宝",
			},
		},
	
		[351542] = {
			readable = "Secret Treasure",
			model = 3597238,
			text = {
				en = "Secret Treasure",
				es = "Tesoro secreto",
				de = "Geheimer Schatz",
				fr = "Trésor secret",
				it = "Tesoro Segreto",
				pt = "Tesouro Secreto",
				ru = "Спрятанное сокровище",
				ko = "비밀 보물",
				cn = "秘密财宝",
			},
		},
	
		[351543] = {
			readable = "Secret Treasure",
			model = 3597238,
			text = {
				en = "Secret Treasure",
				es = "Tesoro secreto",
				de = "Geheimer Schatz",
				fr = "Trésor secret",
				it = "Tesoro Segreto",
				pt = "Tesouro Secreto",
				ru = "Спрятанное сокровище",
				ko = "비밀 보물",
				cn = "秘密财宝",
			},
		},
	
		[351544] = {
			readable = "Secret Treasure",
			model = 3597238,
			text = {
				en = "Secret Treasure",
				es = "Tesoro secreto",
				de = "Geheimer Schatz",
				fr = "Trésor secret",
				it = "Tesoro Segreto",
				pt = "Tesouro Secreto",
				ru = "Спрятанное сокровище",
				ko = "비밀 보물",
				cn = "秘密财宝",
			},
		},
	
		[351545] = {
			readable = "Secret Treasure",
			model = 3597238,
			text = {
				en = "Secret Treasure",
				es = "Tesoro secreto",
				de = "Geheimer Schatz",
				fr = "Trésor secret",
				it = "Tesoro Segreto",
				pt = "Tesouro Secreto",
				ru = "Спрятанное сокровище",
				ko = "비밀 보물",
				cn = "秘密财宝",
			},
		},
	
		[351708] = {
			readable = "Drust Totem",
			model = 3160243,
			text = {
				en = "Drust Totem",
				es = "Tótem Drust",
				de = "Drusttotem",
				fr = "Totem drust",
				it = "Totem dei Drust",
				pt = "Totem Drusto",
				ru = "Тотем друстов",
				ko = "드러스트 토템",
				cn = "德鲁斯特图腾",
			},
		},
	
		[351716] = {
			readable = "Lost Cryptkeeper's Ring",
			model = 3148983,
			text = {
				en = "Lost Cryptkeeper's Ring",
				es = "Anillo del guardacriptas perdido",
				de = "Verlorener Grufthüterring",
				fr = "Anneau égaré du gardien de la crypte",
				it = "Anello Perduto del Custode della Cripta",
				pt = "Anel do Guardião da Cripta Perdido",
				ru = "Потерянное кольцо хранителя склепа",
				ko = "잃어버린 묘지지기의 반지",
				cn = "地穴看守者丢失的戒指",
			},
		},
	
		[351718] = {
			readable = "Standing Rock",
			model = 1517169,
			text = {
				en = "Standing Rock",
				es = "Roca vertical",
				de = "Aufrechter Stein",
				fr = "Rocher fiché dans le sol",
				it = "Roccia Ferma",
				pt = "Rocha Erguida",
				ru = "Монолит",
				ko = "비석",
				cn = "立岩",
			},
		},
	
		[351720] = {
			readable = "Beacon of Invocation",
			model = 3220604,
			text = {
				en = "Beacon of Invocation",
				es = "Señal de invocación",
				de = "Leuchtfeuer der Anrufung",
				fr = "Balise d’invocation",
				it = "Segnalatore dell'Invocazione",
				pt = "Luz de Invocação",
				ru = "Взывающий маяк",
				ko = "기원의 신호기",
				cn = "祈咒道标",
			},
		},
	
		[351722] = {
			readable = "Mawforged Lock",
			model = 3609723,
			text = {
				en = "Mawforged Lock",
				es = "Cerradura de Las Fauces",
				de = "Schlundgeschmiedetes Schloss",
				fr = "Verrou antreforgé",
				it = "Serratura Forgiata nella Fauce",
				pt = "Tranca Forjada na Gorja",
				ru = "Кованый в Утробе замок",
				ko = "나락벼림 자물쇠",
				cn = "渊铸之锁",
			},
		},
	
		[351728] = {
			readable = "Quivering Gorm Egg",
			model = 3164507,
			text = {
				en = "Quivering Gorm Egg",
				es = "Huevo de gorm tembloroso",
				de = "Zitterndes Gormei",
				fr = "Œuf de gorm frémissant",
				it = "Uovo di Gorm Tremolante",
				pt = "Ovo de Gorm Tremelicante",
				ru = "Подрагивающее яйцо горма",
				ko = "떨리는 게걸충 알",
				cn = "颤动的戈姆之卵",
			},
		},
	
		[351730] = {
			readable = "Darkhaven Supply Carriage",
			model = 3068531,
			text = {
				en = "Darkhaven Supply Carriage",
				es = "Carruaje de suministros de Refugioscuro",
				de = "Versorgungskutsche von Dunkelhafen",
				fr = "Calèche de fournitures de Sombrehavre",
				it = "Carrozza di Rifornimenti di Lidoscuro",
				pt = "Carruagem de Suprimentos do Retiro Sombrio",
				ru = "Экипаж с припасами из Темного Приюта",
				ko = "어둠안식처 보급 마차",
				cn = "暗湾补给车",
			},
		},
	
		[351732] = {
			readable = "Ward of Purity",
			model = 3220603,
			text = {
				en = "Ward of Purity",
				es = "Resguardo de la pureza",
				de = "Schutz der Reinheit",
				fr = "Sceau de la pureté",
				it = "Protezione della Purezza",
				pt = "Guarda da Pureza",
				ru = "Оберег храма Чистоты",
				ko = "순수의 수호물",
				cn = "纯洁结界",
			},
		},
	
		[351733] = {
			readable = "Ward of Humility",
			model = 3220603,
			text = {
				en = "Ward of Humility",
				es = "Resguardo de la humildad",
				de = "Schutz der Demut",
				fr = "Sceau de l’humilité",
				it = "Protezione dell'Umiltà",
				pt = "Guarda da Humildade",
				ru = "Оберег храма Смирения",
				ko = "겸손의 수호물",
				cn = "谦逊结界",
			},
		},
	
		[351734] = {
			readable = "Ward of Courage",
			model = 3220603,
			text = {
				en = "Ward of Courage",
				es = "Resguardo del valor",
				de = "Schutz des Mutes",
				fr = "Sceau du courage",
				it = "Protezione del Coraggio",
				pt = "Guarda da Coragem",
				ru = "Оберег храма Отваги",
				ko = "용기의 수호물",
				cn = "勇气结界",
			},
		},
	
		[351735] = {
			readable = "Ward of Loyalty",
			model = 3220603,
			text = {
				en = "Ward of Loyalty",
				es = "Resguardo de la lealtad",
				de = "Schutz der Loyalität",
				fr = "Sceau de la loyauté",
				it = "Protezione della Lealtà",
				pt = "Guarda da Lealdade",
				ru = "Оберег храма Верности",
				ko = "충성의 수호물",
				cn = "忠诚结界",
			},
		},
	
		[351736] = {
			readable = "Ward of Wisdom",
			model = 3220603,
			text = {
				en = "Ward of Wisdom",
				es = "Resguardo de la sabiduría",
				de = "Schutz der Weisheit",
				fr = "Sceau de la sagesse",
				it = "Protezione della Saggezza",
				pt = "Guarda da Sabedoria",
				ru = "Оберег храма Мудрости",
				ko = "지혜의 수호물",
				cn = "智慧结界",
			},
		},
	
		[351746] = {
			readable = "Manor Supply Carriage",
			model = 3068531,
			text = {
				en = "Manor Supply Carriage",
				es = "Carruaje de suministros de la mansión",
				de = "Versorgungskutsche des Anwesens",
				fr = "Calèche de fournitures du manoir",
				it = "Carrozza di Rifornimenti del Maniero",
				pt = "Carruagem de Suprimentos da Mansão",
				ru = "Экипаж с припасами из поместья",
				ko = "저택 보급 마차",
				cn = "庄园补给车",
			},
		},
	
		[351754] = {
			readable = "Mawforged Lock",
			model = 3609723,
			text = {
				en = "Mawforged Lock",
				es = "Cerradura de Las Fauces",
				de = "Schlundgeschmiedetes Schloss",
				fr = "Verrou antreforgé",
				it = "Serratura Forgiata nella Fauce",
				pt = "Tranca Forjada na Gorja",
				ru = "Кованый в Утробе замок",
				ko = "나락벼림 자물쇠",
				cn = "渊铸之锁",
			},
		},
	
		[351755] = {
			readable = "Quivering Gorm Eggs",
			model = 3164508,
			text = {
				en = "Quivering Gorm Eggs",
				es = "Huevos de gorm temblorosos",
				de = "Zitternde Gormeier",
				fr = "Œufs de gorm frémissants",
				it = "Uova di Gorm Tremolanti",
				pt = "Ovos de Gorm Tremelicantes",
				ru = "Подрагивающая кладка гормов",
				ko = "떨리는 게걸충 알",
				cn = "颤动的戈姆之卵",
			},
		},
	
		[351761] = {
			readable = "Mawsteel Cage",
			model = 3677218,
			text = {
				en = "Mawsteel Cage",
				es = "Jaula de acero de Las Fauces",
				de = "Schlundstahlkäfig",
				fr = "Cage en antracier",
				it = "Gabbia di Fauciacciaio",
				pt = "Jaula de Aço da Gorja",
				ru = "Клетка из стали Утробы",
				ko = "나락강철 우리",
				cn = "渊钢牢笼",
			},
		},
	
		[351763] = {
			readable = "Rubbish Pile",
			model = 3546734,
			text = {
				en = "Rubbish Pile",
				es = "Montón de basura",
				de = "Müllhaufen",
				fr = "Pile de déchets",
				it = "Mucchio di Spazzatura",
				pt = "Pilha de Entulho",
				ru = "Куча мусора",
				ko = "쓰레기 더미",
				cn = "垃圾堆",
			},
		},
	
		[351873] = {
			readable = "Unfinished Blade",
			model = 3580273,
			text = {
				en = "Unfinished Blade",
				es = "Hoja inacabada",
				de = "Unvollendete Klinge",
				fr = "Lame inachevée",
				it = "Lama Incompiuta",
				pt = "Lâmina Inacabada",
				ru = "Недоделанный клинок",
				ko = "미완성 검",
				cn = "未完成的利刃",
			},
		},
	
		[351874] = {
			readable = "Wanted: Enforcer Kristof",
			model = 3166135,
			text = {
				en = "Wanted: Enforcer Kristof",
				es = "Se busca: Déspota Kristof",
				de = "Gesucht: Vollstrecker Kristoff",
				fr = "Avis de recherche : massacreur Kristof",
				it = "Ricercato: Esecutore Kristoff",
				pt = "Procura-se: Impositor Kristof",
				ru = "Разыскивается: каратель Кристоф",
				ko = "현상 수배: 집행자 크리스토프",
				cn = "通缉：执行者克里斯托弗",
			},
		},
	
		[351877] = {
			readable = "Domination Lock",
			model = 3947708,
			text = {
				en = "Domination Lock",
				es = "Cerradura de dominación",
				de = "Herrschaftsschloss",
				fr = "Verrou de domination",
				it = "Lucchetto del Dominio",
				pt = "Tranca da Dominação",
				ru = "Замок Господства",
				ko = "지배의 자물쇠",
				cn = "统御之锁",
			},
		},
	
		[351884] = {
			readable = "Depleted Anima Well",
			model = 3056535,
			text = {
				en = "Depleted Anima Well",
				es = "Pozo de ánima agotado",
				de = "Erschöpfte Animaquelle",
				fr = "Puits d’anima vide",
				it = "Pozzo d'Animum Esaurito",
				pt = "Poço de Ânima Vazio",
				ru = "Истощенный колодец анимы",
				ko = "고갈된 령의 샘",
				cn = "枯竭的心能之井",
			},
		},
	
		[351885] = {
			readable = "Wanted: Aggregate of Doom",
			model = 3166135,
			text = {
				en = "Wanted: Aggregate of Doom",
				es = "Se busca: Agregado de fatalidad",
				de = "Gesucht: Aggregat des Unheils",
				fr = "Avis de recherche : Concrétion de fatalité",
				it = "Ricercato: Aggregato della Rovina",
				pt = "Procura-se: Agregado da Ruína",
				ru = "Разыскивается: Агрегат Рока",
				ko = "현상 수배: 파멸의 응집체",
				cn = "通缉：聚合末日",
			},
		},
	
		[351886] = {
			readable = "Wanted: Duke Anton",
			model = 3166135,
			text = {
				en = "Wanted: Duke Anton",
				es = "Se busca: duque Anton",
				de = "Gesucht: Herzog Anton",
				fr = "Avis de recherche : duc Anton",
				it = "Ricercato: Duca Anton",
				pt = "Procura-se: Duque Anton",
				ru = "Разыскивается: герцог Антон",
				ko = "현상 수배: 공작 안톤",
				cn = "通缉：安东公爵",
			},
		},
	
		[351887] = {
			readable = "Wanted: Lord Darion",
			model = 3166135,
			text = {
				en = "Wanted: Lord Darion",
				es = "Se busca: lord Darion",
				de = "Gesucht: Lord Darion",
				fr = "Avis de recherche : seigneur Darion",
				it = "Ricercato: Sire Darion",
				pt = "Procura-se: Lorde Dárion",
				ru = "Разыскивается: лорд Дарион",
				ko = "현상 수배: 다리온 경",
				cn = "通缉：达里安勋爵",
			},
		},
	
		[351888] = {
			readable = "Wanted: Summoner Marcelis",
			model = 3166135,
			text = {
				en = "Wanted: Summoner Marcelis",
				es = "Se busca: invocador Marcelis",
				de = "Gesucht: Beschwörer Marcelis",
				fr = "Avis de recherche : invocateur Marcélis",
				it = "Ricercato: Evocatore Marcelis",
				pt = "Procura-se: Evocador Marcelis",
				ru = "Разыскивается: призыватель Марцелис",
				ko = "현상 수배: 소환사 마르셀리스",
				cn = "通缉：召唤师玛尔瑟力斯",
			},
		},
	
		[351889] = {
			readable = "Wanted: The Pale Doom",
			model = 3166135,
			text = {
				en = "Wanted: The Pale Doom",
				es = "Se busca: Condenación Pálida",
				de = "Gesucht: Der fahle Schrecken",
				fr = "Avis de recherche : le Fléau blafard",
				it = "Ricercata: La Rovina Pallida",
				pt = "Procura-se: A Ruína Pálida",
				ru = "Разыскивается: Бледный Рок",
				ko = "현상 수배: 창백파멸",
				cn = "通缉：苍白末日",
			},
		},
	
		[351917] = {
			readable = "Interrogator's Cage",
			model = 195415,
			text = {
				en = "Interrogator's Cage",
				es = "Jaula de interrogador",
				de = "Käfig des Verhörmeisters",
				fr = "Cage de l’interrogateur",
				it = "Gabbia dell'Interrogatore",
				pt = "Jaula de Interrogação",
				ru = "Клетка дознавателя",
				ko = "심문관의 우리",
				cn = "审讯者的牢笼",
			},
		},
	
		[351933] = {
			readable = "Scroll of Teleportation",
			model = 3036652,
			text = {
				en = "Scroll of Teleportation",
				es = "Pergamino de teletransporte",
				de = "Schriftrolle der Teleportation",
				fr = "Parchemin de téléportation",
				it = "Pergamena del Teletrasporto",
				pt = "Pergaminho de Teleportação",
				ru = "Свиток телепортации",
				ko = "순간이동의 두루마리",
				cn = "传送卷轴",
			},
		},
	
		[351937] = {
			readable = "Mushroom Ring",
			model = 3543717,
			text = {
				en = "Mushroom Ring",
				es = "Anillo de champiñón",
				de = "Pilzring",
				fr = "Cercle de champignons",
				it = "Anello di Funghi",
				pt = "Círculo de Cogumelos",
				ru = "Грибное кольцо",
				ko = "버섯 고리",
				cn = "蘑菇环",
			},
		},
	
		[351948] = {
			readable = "Forgotten Chest",
			model = 3597238,
			text = {
				en = "Forgotten Chest",
				es = "Cofre olvidado",
				de = "Vergessene Truhe",
				fr = "Coffre oublié",
				it = "Cassa Dimenticata",
				pt = "Baú Esquecido",
				ru = "Позабытый сундук",
				ko = "잊힌 상자",
				cn = "被遗忘的宝箱",
			},
		},
	
		[351956] = {
			readable = "Sinstone of Revendreth",
			model = 3534289,
			text = {
				en = "Sinstone of Revendreth",
				es = "Piedra del pecado de Revendreth",
				de = "Sündenstein von Revendreth",
				fr = "Stèle du vice de Revendreth",
				it = "Pietra del Peccato di Revendreth",
				pt = "Pedra de Pecado de Revendreth",
				ru = "Ревендретский камень грехов",
				ko = "레벤드레스의 죄악석",
				cn = "雷文德斯罪碑",
			},
		},
	
		[351980] = {
			readable = "Misplaced Supplies",
			model = 1254446,
			text = {
				en = "Misplaced Supplies",
				es = "Suministros extraviados",
				de = "Verlegte Vorräte",
				fr = "Fournitures égarées",
				it = "Rifornimenti Smarriti",
				pt = "Suprimentos Deslocados",
				ru = "Потерянные припасы",
				ko = "엉뚱한 곳에 놓인 보급품",
				cn = "遗失的补给",
			},
		},
})
do ObjectDB[objectID] = objectData; end
