local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	
		[250080] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[250081] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[250082] = {
			readable = "Eye of Amun'thul",
			model = 795929,
			text = {
				en = "Eye of Amun'thul",
				es = "Ojo de Aman'thul",
				de = "Auge von Amun'thul",
				fr = "Œil d’Aman’Thul",
				it = "Occhio di Aman'thul",
				pt = "Olho de Amun'thul",
				ru = "Глаз Аман'тула",
				ko = "아만툴의 눈",
				cn = "阿曼苏尔之眼",
			},
		},
	
		[250083] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[250084] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[250085] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[250086] = {
			readable = "Cask of Arcwine",
			model = 1360746,
			text = {
				en = "Cask of Arcwine",
				es = "Tonel de vino de arco",
				de = "Fass Arkwein",
				fr = "Fût d’arquevin",
				it = "Botte di Arcavino",
				pt = "Barril de Vinho Arcano",
				ru = "Бочонок чародейского вина",
				ko = "비전주 통",
				cn = "一桶魔力酒",
			},
		},
	
		[250087] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[250088] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[250089] = {
			readable = "Doodad_7VR_Vrykul_ElevatorPlatform001",
			model = 1242721,
			text = {
				en = "Doodad_7VR_Vrykul_ElevatorPlatform001",
				cn = "占位符",
			},
		},
	
		[250090] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[250091] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[250092] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[250093] = {
			readable = "Idol of the Claw",
			model = 1257783,
			text = {
				en = "Idol of the Claw",
				es = "Ídolo de la zarpa",
				de = "Götze der Klaue",
				fr = "Idole de la Griffe",
				it = "Idolo dell'Unghia",
				pt = "Ídolo da Garra",
				ru = "Идол Когтя",
				ko = "발톱의 우상",
				cn = "利爪神像",
			},
		},
	
		[250095] = {
			readable = "Idol of the Paw",
			model = 1257796,
			text = {
				en = "Idol of the Paw",
				es = "Ídolo de la garra",
				de = "Götze der Pranke",
				fr = "Idole de la Patte",
				it = "Idolo della Zampa",
				pt = "Ídolo da Pata",
				ru = "Идол Лапы",
				ko = "발바닥의 우상",
				cn = "熊掌神像",
			},
		},
	
		[250096] = {
			readable = "Idol of the Moon",
			model = 1109130,
			text = {
				en = "Idol of the Moon",
				es = "Ídolo de la Luna",
				de = "Götze des Mondes",
				fr = "Idole de la Lune",
				it = "Idolo della Luna",
				pt = "Ídolo da Lua",
				ru = "Идол Луны",
				ko = "달의 우상",
				cn = "月亮神像",
			},
		},
	
		[250097] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[250098] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[250102] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[250103] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[250104] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[250106] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[250107] = {
			readable = "Glimmering Treasure Chest",
			model = 1349622,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[250108] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[250109] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[250113] = {
			readable = "Doodad_Dalaran_LampWall17",
			model = 194470,
			text = {
				en = "Doodad_Dalaran_LampWall17",
				cn = "占位符",
			},
		},
	
		[250121] = {
			readable = "Doodad_Dalaran_Lamppost08",
			model = 194468,
			text = {
				en = "Doodad_Dalaran_Lamppost08",
				cn = "占位符",
			},
		},
	
		[250122] = {
			readable = "Doodad_Dalaran_Lamppost09",
			model = 194468,
			text = {
				en = "Doodad_Dalaran_Lamppost09",
				cn = "占位符",
			},
		},
	
		[250220] = {
			readable = "Malformed Abyssal",
			model = 1319078,
			text = {
				en = "Malformed Abyssal",
				es = "Abisal deforme",
				de = "Deformierter Abyssal",
				fr = "Abyssal déformé",
				it = "Abissale Deforme",
				pt = "Abissal Deformado",
				ru = "Бесформенный абиссал",
				ko = "기이한 심연불정령",
				cn = "畸形深渊魔",
			},
		},
	
		[250221] = {
			readable = "Houndstooth Hauberk",
			model = 1319080,
			text = {
				en = "Houndstooth Hauberk",
				es = "Camisote Dientejauría",
				de = "Hundebisshalsberge",
				fr = "Haubert en dent de molosse",
				it = "Usbergo di Dentemastino",
				pt = "Cota de Galgodente",
				ru = "Хауберк из зубов гончих",
				ko = "사냥개이빨 갑옷",
				cn = "犬牙锁子甲",
			},
		},
	
		[250222] = {
			readable = "Flayed-Skin Chronicle",
			model = 1319077,
			text = {
				en = "Flayed-Skin Chronicle",
				es = "Crónica de piel despellejada",
				de = "Auf Haut geschriebene Chronik",
				fr = "Chronique en peau écorchée",
				it = "Cronache dalla Copertina Rovinata",
				pt = "Diário de Pele Arrancada",
				ru = "Хроника на содранной коже",
				ko = "벗겨진 피부에 기록된 연대기",
				cn = "剥皮编年史",
			},
		},
	
		[250223] = {
			readable = "Imp's Cup",
			model = 1319061,
			text = {
				en = "Imp's Cup",
				es = "Taza de diablillo",
				de = "Wichtelkelch",
				fr = "Coupe de diablotin",
				it = "Coppa dell'Imp",
				pt = "Taça de Diabrete",
				ru = "Чаша беса",
				ko = "임프의 잔",
				cn = "小鬼之杯",
			},
		},
	
		[250224] = {
			readable = "Orb of Inner Chaos",
			model = 1319079,
			text = {
				en = "Orb of Inner Chaos",
				es = "Orbe de caos interior",
				de = "Kugel des inneren Chaos",
				fr = "Orbe de chaos intérieur",
				it = "Globo del Caos Interiore",
				pt = "Orbe do Caos Interior",
				ru = "Сфера внутреннего хаоса",
				ko = "내면의 혼돈 보주",
				cn = "混沌心灵宝珠",
			},
		},
	
		[250225] = {
			readable = "Violetglass Vessel",
			model = 1319056,
			text = {
				en = "Violetglass Vessel",
				es = "Vasija de cristal violeta",
				de = "Violettglasgefäß",
				fr = "Récipient en verre violet",
				it = "Vaso di Vetro Viola",
				pt = "Recipiente Vidroleta",
				ru = "Сосуд из фиолетового стекла",
				ko = "보라유리 단지",
				cn = "紫色琉璃器皿",
			},
		},
	
		[250226] = {
			readable = "Nobleman's Letter Opener",
			model = 1319060,
			text = {
				en = "Nobleman's Letter Opener",
				es = "Abridor de cartas de noble",
				de = "Brieföffner eines Adligen",
				fr = "Coupe-papier de noble",
				it = "Tagliacarte del Nobiluomo",
				pt = "Abridor de Cartas de Nobre",
				ru = "Аристократический ножик для разрезания бумаги",
				ko = "귀족의 지칼",
				cn = "贵族拆信刀",
			},
		},
	
		[250227] = {
			readable = "Inert Leystone Charm",
			model = 1319057,
			text = {
				en = "Inert Leystone Charm",
				es = "Talismán de piedra Ley inerte",
				de = "Inaktiver Leysteinglücksbringer",
				fr = "Charme en tellurium inerte",
				it = "Talismano di Fagliaroccia Inerte",
				pt = "Patuá de Pedra de Meridiano Inerte",
				ru = "Амулет из инертного силового камня",
				ko = "마력을 잃은 지맥석 부적",
				cn = "惰性魔石护符",
			},
		},
	
		[250228] = {
			readable = "Pre-War Highborne Tapestry",
			model = 1319059,
			text = {
				en = "Pre-War Highborne Tapestry",
				es = "Tapiz de los Altonato anterior a la guerra",
				de = "Vorkriegswandschmuck der Hochgeborenen",
				fr = "Tapisserie bien-née d’avant-guerre",
				it = "Arazzo degli Alti Nobili Anteguerra",
				pt = "Tapeçaria Altaneira de Antes da Guerra",
				ru = "Довоенный гобелен высокорожденных",
				ko = "전쟁 전 명가 벽걸이",
				cn = "战前上层精灵挂毯",
			},
		},
	
		[250229] = {
			readable = "Quietwine Vial",
			model = 1319058,
			text = {
				en = "Quietwine Vial",
				es = "Vial de vinomudo",
				de = "Stillrebenphiole",
				fr = "Fiole de mort-boyaux",
				it = "Fiala di Vinsilente",
				pt = "Frasco de Vinho do Silêncio",
				ru = "Склянка с мировином",
				ko = "침묵포도주 병",
				cn = "鸩酒酒瓶",
			},
		},
	
		[250230] = {
			readable = "Stonewood Bow",
			model = 1319085,
			text = {
				en = "Stonewood Bow",
				es = "Arco de madera de piedra",
				de = "Steinholzbogen",
				fr = "Arc en bois de pierre",
				it = "Arco di Pietralegno",
				pt = "Arco Petralenha",
				ru = "Лук Каменного леса",
				ko = "돌나무 활",
				cn = "石木长弓",
			},
		},
	
		[250231] = {
			readable = "Trailhead Drum",
			model = 1319081,
			text = {
				en = "Trailhead Drum",
				es = "Tambor de senda",
				de = "Trommel des Aufbruchs",
				fr = "Tambour de début de piste",
				it = "Tamburo dell'Iniziazione",
				pt = "Tambor de Trilha",
				ru = "Первый барабан",
				ko = "길잡이 북",
				cn = "启程之鼓",
			},
		},
	
		[250232] = {
			readable = "Moosebone Fish-Hook",
			model = 1319082,
			text = {
				en = "Moosebone Fish-Hook",
				es = "Anzuelo de hueso de alce",
				de = "Angelhaken aus Elchknochen",
				fr = "Hameçon en os d’élan",
				it = "Amo di Osso d'Alce",
				pt = "Anzol de Osso de Alce",
				ru = "Рыболовный крючок из лосиной кости",
				ko = "엘크뼈 낚싯바늘",
				cn = "鹿骨鱼钩",
			},
		},
	
		[250233] = {
			readable = "Drogbar Gem-Roller",
			model = 1319084,
			text = {
				en = "Drogbar Gem-Roller",
				es = "Pulegemas drógbar",
				de = "Edelsteinschleifer der Drogbar",
				fr = "Roule-gemme drogbar",
				it = "Buratto dei Drogbar",
				pt = "Realejo Drogbar",
				ru = "Дрогбарская камнедробилка",
				ko = "드로그바 보석 세공기",
				cn = "卓格巴尔宝石滚筒",
			},
		},
	
		[250234] = {
			readable = "Hand-Smoothed Pyrestone",
			model = 1319083,
			text = {
				en = "Hand-Smoothed Pyrestone",
				es = "Piropiedra alisada a mano",
				de = "Handgeschliffener Pyrostein",
				fr = "Pyrolithe polie à la main",
				it = "Pietrapira Lisciata a Mano",
				pt = "Lumepedra Polida à Mão",
				ru = "Отшлифованный вручную огнекамень",
				ko = "손으로 연마한 열화석",
				cn = "手工打磨的焚石",
			},
		},
	
		[250238] = {
			readable = "Gondola",
			model = 1273836,
			text = {
				en = "Gondola",
				es = "Góndola",
				de = "Gondel",
				fr = "Gondole",
				pt = "Gôndola",
				ru = "Гондола",
				ko = "나룻배",
				cn = "贡多拉",
			},
		},
	
		[250239] = {
			readable = "Bottle of Arcwine",
			model = 1360809,
			text = {
				en = "Bottle of Arcwine",
				es = "Botella de vino de arco",
				de = "Flasche Arkwein",
				fr = "Bouteille d’arquevin",
				it = "Bottiglia di Arcavino",
				pt = "Garrafa de Vinho Arcano",
				ru = "Бутылка чародейского вина",
				ko = "비전주 병",
				cn = "一瓶魔力酒",
			},
		},
	
		[250240] = {
			readable = "Bottle of Arcwine",
			model = 1360808,
			text = {
				en = "Bottle of Arcwine",
				es = "Botella de vino de arco",
				de = "Flasche Arkwein",
				fr = "Bouteille d’arquevin",
				it = "Bottiglia di Arcavino",
				pt = "Garrafa de Vinho Arcano",
				ru = "Бутылка чародейского вина",
				ko = "비전주 병",
				cn = "一瓶魔力酒",
			},
		},
	
		[250257] = {
			readable = "Empowered Nether Crucible",
			model = 1101712,
			text = {
				en = "Empowered Nether Crucible",
				es = "Crisol abisal potenciado",
				de = "Mächtiger Nethertiegel",
				fr = "Creuset du Néant surpuissant",
				it = "Crogiolo Fatuo Potenziato",
				pt = "Crisol Etéreo Potencializado",
				ru = "Заряженное горнило Пустоты",
				ko = "강화된 황천 도가니",
				cn = "强化虚空坩埚",
			},
		},
	
		[250263] = {
			readable = "Weapon Rack",
			model = 200608,
			text = {
				en = "Weapon Rack",
				es = "Expositor de armas",
				de = "Waffenständer",
				fr = "Râtelier d’armes",
				it = "Rastrelliera delle Armi",
				pt = "Cavalete de Armas",
				ru = "Оружейная стойка",
			},
		},
	
		[250265] = {
			readable = "Legion Cage",
			model = 1125322,
			text = {
				en = "Legion Cage",
				es = "Jaula de la Legión",
				de = "Käfig der Legion",
				fr = "Cage de la Légion",
				it = "Gabbia della Legione",
				pt = "Jaula da Legião",
				ru = "Клетка Легиона",
				ko = "군단 우리",
				cn = "军团牢笼",
			},
		},
	
		[250266] = {
			readable = "Legion Cage",
			model = 1248970,
			text = {
				en = "Legion Cage",
				es = "Jaula de la Legión",
				de = "Käfig der Legion",
				fr = "Cage de la Légion",
				it = "Gabbia della Legione",
				pt = "Jaula da Legião",
				ru = "Клетка Легиона",
				cn = "军团牢笼",
			},
		},
	
		[250267] = {
			readable = "Felsurge Egg",
			model = 915963,
			text = {
				en = "Felsurge Egg",
				es = "Huevo de Ondavil",
				de = "Teufelssogei",
				fr = "Œuf gangreflux",
				it = "Uovo di Vilchelicero",
				pt = "Ovo de Surtovil",
				ru = "Наполненное Скверной яйцо",
				ko = "지옥쇄도 알",
				cn = "邪涌蛛卵",
			},
		},
	
		[250269] = {
			readable = "Legion Portal",
			model = 1122549,
			text = {
				en = "Legion Portal",
				es = "Portal de la Legión",
				de = "Legionsportal",
				fr = "Portail de la Légion",
				it = "Portale della Legione",
				pt = "Portal da Legião",
				ru = "Портал Легиона",
				ko = "군단 차원문",
				cn = "军团传送门",
			},
		},
	
		[250270] = {
			readable = "Legion Portal",
			model = 1122549,
			text = {
				en = "Legion Portal",
				es = "Portal de la Legión",
				de = "Legionsportal",
				fr = "Portail de la Légion",
				it = "Portale della Legione",
				pt = "Portal da Legião",
				ru = "Портал Легиона",
				ko = "군단 차원문",
				cn = "军团传送门",
			},
		},
	
		[250280] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250281] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250282] = {
			readable = "Seaweed",
			model = 1121210,
			text = {
				en = "Seaweed",
				es = "Algas",
				de = "Seetang",
				fr = "Algue",
				it = "Alga Marina",
				pt = "Algas Marinhas",
				ru = "Водоросли",
				ko = "해초",
				cn = "海草",
			},
		},
	
		[250284] = {
			readable = "Driftwood",
			model = 1092285,
			text = {
				en = "Driftwood",
				es = "Madera a la deriva",
				de = "Treibholz",
				fr = "Bois flotté",
				it = "Ramo",
				pt = "Madeira Flutuante",
				ru = "Плавник",
				ko = "유목",
				cn = "浮木",
			},
		},
	
		[250285] = {
			readable = "Driftwood",
			model = 1092284,
			text = {
				en = "Driftwood",
				es = "Madera a la deriva",
				de = "Treibholz",
				fr = "Bois flotté",
				it = "Ramo",
				pt = "Madeira Flutuante",
				ru = "Плавник",
				ko = "유목",
				cn = "浮木",
			},
		},
	
		[250286] = {
			readable = "Seaweed",
			model = 1121148,
			text = {
				en = "Seaweed",
				es = "Algas",
				de = "Seetang",
				fr = "Algue",
				it = "Alga Marina",
				pt = "Algas Marinhas",
				ru = "Водоросли",
				ko = "해초",
				cn = "海草",
			},
		},
	
		[250287] = {
			readable = "Seaweed",
			model = 1121182,
			text = {
				en = "Seaweed",
				es = "Algas",
				de = "Seetang",
				fr = "Algue",
				it = "Alga Marina",
				pt = "Algas Marinhas",
				ru = "Водоросли",
				ko = "해초",
				cn = "海草",
			},
		},
	
		[250288] = {
			readable = "Speckled Pearl",
			model = 338524,
			text = {
				en = "Speckled Pearl",
				es = "Perla moteada",
				de = "Gesprenkelte Perle",
				fr = "Perle mouchetée",
				it = "Perla Screziata",
				pt = "Pérola Manchada",
				ru = "Крапчатая жемчужина",
				ko = "점박이 진주",
				cn = "斑点珍珠",
			},
		},
	
		[250289] = {
			readable = "Clam",
			model = 369232,
			text = {
				en = "Clam",
				es = "Almeja",
				de = "Muschel",
				fr = "Palourde",
				it = "Bivalve",
				pt = "Marisco",
				ru = "Моллюск",
				ko = "조개",
				cn = "蛤蜊",
			},
		},
	
		[250290] = {
			readable = "Clam",
			model = 369233,
			text = {
				en = "Clam",
				es = "Almeja",
				de = "Muschel",
				fr = "Palourde",
				it = "Bivalve",
				pt = "Marisco",
				ru = "Моллюск",
				ko = "조개",
				cn = "蛤蜊",
			},
		},
	
		[250291] = {
			readable = "Clam",
			model = 369234,
			text = {
				en = "Clam",
				es = "Almeja",
				de = "Muschel",
				fr = "Palourde",
				it = "Bivalve",
				pt = "Marisco",
				ru = "Моллюск",
				ko = "조개",
				cn = "蛤蜊",
			},
		},
	
		[250295] = {
			readable = "Old Campfire",
			model = 219237,
			text = {
				en = "Old Campfire",
				es = "Hoguera antigua",
				de = "Altes Lagerfeuer",
				fr = "Vieux feu de camp",
				it = "Fuoco da Campo Vecchio",
				pt = "Velha Fogueira de Acampamento",
				ru = "Старое кострище",
				cn = "古老的营火",
			},
		},
	
		[250361] = {
			readable = "Sabotaged Portal Stabilizer",
			model = 1243752,
			text = {
				en = "Sabotaged Portal Stabilizer",
				es = "Estabilizador de portal saboteado",
				de = "Sabotierter Portalstabilisator",
				fr = "Stabilisateur de portail saboté",
				it = "Stabilizzatore del Portale Sabotato",
				pt = "Estabilizador do Portal Sabotado",
				ru = "Модифицированный стабилизатор портала",
			},
		},
	
		[250362] = {
			readable = "Sythorne's Podium",
			model = 1361714,
			text = {
				en = "Sythorne's Podium",
				es = "Podio de Sythorne",
				de = "Sythornes Podium",
				fr = "Podium de Sythorne",
				it = "Leggio di Spinorn",
				pt = "Púlpito de Espyculus",
				ru = "Стол Сифорна",
				ko = "사이톤의 책상",
				cn = "塞索尼的讲台",
			},
		},
	
		[250364] = {
			readable = "Broken Sword",
			model = 955705,
			text = {
				en = "Broken Sword",
				es = "Espada rota",
				de = "Zerbrochenes Schwert",
				fr = "Épée cassée",
				it = "Spada Rotta",
				pt = "Espada Quebrada",
				ru = "Сломанный меч",
				cn = "断剑",
			},
		},
	
		[250367] = {
			readable = "Broken Statue",
			model = 1327766,
			text = {
				en = "Broken Statue",
				es = "Estatua rota",
				de = "Kaputte Statue",
				fr = "Statue brisée",
				it = "Statua Rotta",
				pt = "Estátua Quebrada",
				ru = "Разбитая статуя",
				cn = "破碎的雕像",
			},
		},
	
		[250369] = {
			readable = "Carelessly Dropped Note",
			model = 936411,
			text = {
				en = "Carelessly Dropped Note",
				es = "Nota olvidada",
				de = "Achtlos fallengelassene Notiz",
				fr = "Note jetée négligemment",
				it = "Nota Persa Distrattamente",
				pt = "Anotação Largada Descuidadamente",
				ru = "Неосторожно оброненная записка",
				cn = "不小心遗失的纸条",
			},
		},
	
		[250372] = {
			readable = "Courtship Rituals of the Skrog",
			model = 1367405,
			text = {
				en = "Courtship Rituals of the Skrog",
				es = "Rituales de cortejo del skrog",
				de = "Balzrituale der Skrog",
				fr = "Rites de séduction des Skrogs",
				it = "Rituali di Corteggiamento degli Skrog",
				pt = "Rituais de Cortejo dos Skrog",
				ru = "Брачные ритуалы скрогов",
				ko = "거인의 구애 행동",
				cn = "海巨人求偶仪式",
			},
		},
	
		[250373] = {
			readable = "Encyclopedia Azsunica (K-M)",
			model = 1367406,
			text = {
				en = "Encyclopedia Azsunica (K-M)",
				es = "Enciclopedia Azsúnica (K-M)",
				de = "Encyclopaedia Azsunica (K-M)",
				it = "Enciclopedia di Azsuna (K-M)",
				pt = "Enciclopédia Azsúnica (K-M)",
				ru = "Азсунская энциклопедия (К-М)",
				ko = "아즈스나 백과사전 (ㅋ-ㅌ)",
				cn = "阿苏纳大百科（K-M）",
			},
		},
	
		[250374] = {
			readable = "Draconic Compendium, Volume III",
			model = 1124088,
			text = {
				en = "Draconic Compendium, Volume III",
				es = "Compendio dracónico: volumen III",
				de = "Drakonisches Kompendium, Band III",
				fr = "Compendium draconique, volume III",
				it = "Compendio Draconico: Volume III",
				pt = "Compêndio Dracônico, Volume III",
				ru = "Справочник по драконам, том III",
				ko = "용의 전서 - 제3권",
				cn = "龙语纲要第三卷",
			},
		},
	
		[250375] = {
			readable = "Dimensional Anchor",
			model = 1243753,
			text = {
				en = "Dimensional Anchor",
				es = "Ancla dimensional",
				de = "Dimensionsanker",
				fr = "Ancre dimensionnelle",
				it = "Ancora Dimensionale",
				pt = "Âncora Dimensional",
				ru = "Пространственный якорь",
				ko = "차원 수정",
				cn = "次元锚",
			},
		},
	
		[250378] = {
			readable = "Seal of the Tides",
			model = 1358996,
			text = {
				en = "Seal of the Tides",
				es = "Sello de las mareas",
				de = "Siegel der Gezeiten",
				fr = "Sceau des marées",
				it = "Sigillo delle Maree",
				pt = "Selo das Marés",
				ru = "Печать приливов",
				ko = "파도의 인장",
				cn = "潮汐封印",
			},
		},
	
		[250379] = {
			readable = "High Potency Coil",
			model = 1354920,
			text = {
				en = "High Potency Coil",
				es = "Bobina de alta potencia",
				de = "Hochenergetische Spule",
				fr = "Bobine à haute puissance",
				it = "Bobina ad Alta Frequenza",
				pt = "Bobina de Alta Potência",
				ru = "Змеевик высокой мощности",
				ko = "고전위 감줄",
				cn = "高能线圈",
			},
		},
	
		[250380] = {
			readable = "Low Potency Coil",
			model = 1354920,
			text = {
				en = "Low Potency Coil",
				es = "Bobina de baja potencia",
				de = "Niederenergetische Spule",
				fr = "Bobine à faible puissance",
				it = "Bobina a Bassa Potenza",
				pt = "Bobina de Baixa Potência",
				ru = "Змеевик низкой мощности",
				ko = "저전위 감줄",
				cn = "低能线圈",
			},
		},
	
		[250381] = {
			readable = "High Switch",
			model = 1354951,
			text = {
				en = "High Switch",
				es = "Interruptor alto",
				de = "Hochenergetisches Relais",
				fr = "Interrupteur haut",
				it = "Scambio Alto",
				pt = "Interruptor Alto",
				ru = "Переключатель потока высокой мощности",
				ko = "고전위 스위치",
				cn = "高能开关",
			},
		},
	
		[250382] = {
			readable = "Low Switch",
			model = 1354951,
			text = {
				en = "Low Switch",
				es = "Interruptor bajo",
				de = "Niederenergetisches Relais",
				fr = "Interrupteur bas",
				it = "Interruttore Basso",
				pt = "Interruptor Baixo",
				ru = "Переключатель потока низкой мощности",
				ko = "저전위 스위치",
				cn = "低能开关",
			},
		},
	
		[250383] = {
			readable = "Moonshade Relic",
			icon = 1416160,
			model = 1321134,
			text = {
				en = "Moonshade Relic",
				es = "Reliquia Sombra Lunar",
				de = "Mondschattenrelikt",
				fr = "Relique de Lunombrage",
				it = "Reliquia di Ombraluna",
				pt = "Relíquia de Sombraluna",
				ru = "Реликвия обители Лунной Тени",
				ko = "달그늘 성물",
				cn = "月影圣物",
			},
		},
	
		[250386] = {
			readable = "Fangs of Ashamane",
			model = 353152,
			text = {
				en = "Fangs of Ashamane",
				es = "Colmillos de Crinceniza",
				de = "Fänge von Ashamane",
				fr = "Crocs d’Ashamane",
				it = "Zanne di Grigiomanto",
				pt = "Presas de Ashamane",
				ru = "Клыки Пеплошкурой",
				ko = "아샤메인의 송곳니",
				cn = "阿莎曼之牙",
			},
		},
	
		[250408] = {
			readable = "Costume Chest: Dalaran Citizens",
			model = 1371004,
			text = {
				en = "Costume Chest: Dalaran Citizens",
				es = "Cofre de trajes: ciudadanos de Dalaran",
				de = "Kostümtruhe: Einwohner von Dalaran",
				fr = "Malle à costumes : citoyens de Dalaran",
				it = "Cassa di Vestiti: Cittadini di Dalaran",
				pt = "Baú de Fantasias: Cidadãos de Dalaran",
				ru = "Сундук с одеждой: жители Даларана",
			},
		},
	
		[250412] = {
			readable = "Portal to Archmage Vargoth's Retreat",
			model = 244119,
			text = {
				en = "Portal to Archmage Vargoth's Retreat",
				es = "Portal al Reposo del archimago Vargoth",
				de = "Portal zu Erzmagier Vargoths Rückzugsort",
				fr = "Portail vers la retraite de l’archimage Vargoth",
				it = "Portale per lo Studio dell'Arcimago Vargoth",
				pt = "Portal para o Retiro do Arquimago Vargoth",
				ru = "Портал в покои верховного мага Варгота",
				cn = "通往大法师瓦格斯的居所的传送门",
			},
		},
	
		[250413] = {
			readable = "Oren's Prized Possessions",
			model = 1327188,
			text = {
				en = "Oren's Prized Possessions",
				es = "Posesiones preciadas de Oren",
				de = "Orens größter Schatz",
				fr = "Biens les plus précieux d’Oren",
				it = "Beni Preziosi di Oren",
				pt = "Posses Queridas de Oren",
				ru = "Ценные вещи Орена",
			},
		},
	
		[250416] = {
			readable = "An Intern's Journal",
			model = 244162,
			text = {
				en = "An Intern's Journal",
				es = "Diario de un becario",
				de = "Tagebuch eines Praktikanten",
				fr = "Journal d’un stagiaire",
				it = "Diario dello Stagista",
				pt = "Diário de Estagiário",
				ru = "Дневник интерна",
				ko = "수습생의 일지",
				cn = "实习生的日志",
			},
		},
	
		[250417] = {
			readable = "Archmage Vargoth's Journal",
			model = 1365452,
			text = {
				en = "Archmage Vargoth's Journal",
				es = "Diario del archimago Vargoth",
				de = "Erzmagier Vargoths Notizen",
				fr = "Journal de l’archimage Vargoth",
				it = "Diario dell'Arcimago Vargoth",
				pt = "Diário do Arquimago Vargoth",
				ru = "Дневник верховного мага Варгота",
				ko = "대마법사 바르고스의 일지",
				cn = "大法师瓦格斯的日志",
			},
		},
	
		[250418] = {
			readable = "Thorium Manifold Lever",
			model = 201061,
			text = {
				en = "Thorium Manifold Lever",
				es = "Palanca de colector de torio",
				de = "Thoriumverteilerhebel",
				fr = "Levier de tubulure en thorium",
				it = "Leva del Collettore di Torio",
				pt = "Alavanca Agregada de Tório",
				ru = "Ториевый мульти-рычаг",
				ko = "토륨 다기관 지렛대",
				cn = "瑟银歧管操纵杆",
			},
		},
	
		[250419] = {
			readable = "Flux Containment Release Lever",
			model = 201061,
			text = {
				en = "Flux Containment Release Lever",
				es = "Palanca de apertura de contención de flujo",
				de = "Fluxeindämmungsventilhebel",
				fr = "Levier de trop-plein du flux",
				it = "Leva di Rilascio del Contenimento del Flusso",
				pt = "Alavanca de Liberação da Contenção de Fluxo",
				ru = "Спусковой рычаг сдерживателя потока",
				ko = "유체 격납 개방 지렛대",
				cn = "流密度释放杆",
			},
		},
	
		[250420] = {
			readable = "Hydro-Sync Router",
			model = 197760,
			text = {
				en = "Hydro-Sync Router",
				es = "Enrutador de sincronización hidráulica",
				de = "Hydro-Synchro-Verteiler",
				fr = "Routeur d’hydrosynchronisation",
				it = "Router Idrosincronizzato",
				pt = "Roteador de Sincronia Hídrica",
				ru = "Гидросинхронный маршрутизатор",
				ko = "수력동기화 중계 장치",
				cn = "水力同步路由器",
			},
		},
	
		[250421] = {
			readable = "Antimatter Storage Energizer",
			model = 200936,
			text = {
				en = "Antimatter Storage Energizer",
				es = "Energizador de almacenamiento de antimateria",
				de = "Antimateriespeicherlader",
				fr = "Alimentation des conteneurs d’antimatière",
				it = "Energizzatore del Magazzino Antimateria",
				pt = "Carregador de Estoque de Antimatéria",
				ru = "Зарядник хранилища антиматерии",
				ko = "반물질 저장 집중기",
				cn = "反物质存储增能器",
			},
		},
	
		[250424] = {
			readable = "Loose Rock",
			model = 1266186,
			text = {
				en = "Loose Rock",
				es = "Roca suelta",
				de = "Lockeres Gestein",
				fr = "Rocher mobile",
				it = "Roccia Allentata",
				pt = "Pedra Solta",
				ru = "Шаткий камень",
				ko = "바위 덩어리",
				cn = "松动的岩石",
			},
		},
	
		[250426] = {
			readable = "Animal Cage",
			model = 609083,
			text = {
				en = "Animal Cage",
				es = "Jaula para animales",
				de = "Tierkäfig",
				fr = "Cage à animal",
				it = "Gabbia per Animali",
				pt = "Jaula de Animal",
				ru = "Звериная клетка",
			},
		},
	
		[250427] = {
			readable = "Squallhunter Egg",
			model = 200964,
			text = {
				en = "Squallhunter Egg",
				es = "Huevo de cazaborrascas",
				de = "Sturmjägerei",
				fr = "Œuf de chasse-grain",
				it = "Uovo di Cacciaturbini",
				pt = "Ovo de Caçador Guinchante",
				ru = "Яйцо шквального охотника",
				ko = "돌풍사냥꾼 알",
				cn = "猎风龙蛋",
			},
		},
	
		[250429] = {
			readable = "Hunk of Foul Smelling Meat",
			model = 337610,
			text = {
				en = "Hunk of Foul Smelling Meat",
				es = "Trozo de carne de olor fétido",
				de = "Übelriechender Fleischbrocken",
				fr = "Gros tas de viande avariée",
				it = "Pezzo di Carne Puzzolente",
				pt = "Naco de Carne Mal-Cheirosa",
				ru = "Кусок вонючего мяса",
				ko = "고약한 냄새가 나는 고깃덩어리",
				cn = "一块恶臭的肉",
			},
		},
	
		[250432] = {
			readable = "Unstable Riftstone",
			model = 192712,
			text = {
				en = "Unstable Riftstone",
				es = "Piedra de falla inestable",
				de = "Instabiler Rissstein",
				fr = "Pierre de faille instable",
				it = "Roccia della Spaccatura Instabile",
				pt = "Pedra de Fenda Instável",
				ru = "Нестабильный камень разлома",
				ko = "불안정한 균열석",
				cn = "不稳定的裂隙石",
			},
		},
	
		[250433] = {
			readable = "Felforge",
			model = 1243754,
			text = {
				en = "Felforge",
				es = "Forja vil",
				de = "Teufelsschmiede",
				fr = "Gangreforge",
				it = "Vilforgia",
				pt = "Forjavil",
				ru = "Кузня Скверны",
				ko = "지옥가열로",
				cn = "邪能熔炉",
			},
		},
	
		[250445] = {
			readable = "Mountain Berries",
			model = 1246513,
			text = {
				en = "Mountain Berries",
				es = "Bayas de montaña",
				de = "Bergbeeren",
				fr = "Baies des montagnes",
				it = "Bacche di Montagna",
				pt = "Frutinhas da Montanha",
				ru = "Горные ягоды",
			},
		},
	
		[250447] = {
			readable = "Grimoire of Damnation",
			model = 1319077,
			text = {
				en = "Grimoire of Damnation",
				es = "Grimorio de condenación",
				de = "Grimoire der Verdammten",
				fr = "Grimoire de la damnation",
				it = "Libro Arcano della Dannazione",
				pt = "Grimório da Danação",
				ru = "Гримуар Проклятых",
				ko = "파멸의 흑마법서",
				cn = "诅咒魔典",
			},
		},
	
		[250448] = {
			readable = "Imp in a Jar",
			model = 201051,
			text = {
				en = "Imp in a Jar",
				es = "Diablillo en un tarro",
				de = "Wichtel im Glas",
				fr = "Diablotin en bouteille",
				it = "Imp in un Vaso",
				pt = "Diabrete numa Jarra",
				ru = "Бес в кувшине",
				ko = "단지 안에 든 임프",
				cn = "瓶中的小鬼",
			},
		},
	
		[250534] = {
			readable = "Word of the Conclave",
			model = 1322315,
			text = {
				en = "Word of the Conclave",
				es = "Palabra del Cónclave",
				de = "Wort der Konklave",
				fr = "Paroles du Conclave",
				it = "Parola del Conclave",
				pt = "Palavra do Conclave",
				ru = "История Конклава",
				ko = "비밀결사의 말씀",
				cn = "教团箴言",
			},
		},
	
		[250536] = {
			readable = "Intact Greatstag Antler",
			model = 948562,
			text = {
				en = "Intact Greatstag Antler",
				es = "Cornamenta de gran venado intacta",
				de = "Intaktes Großhirschgeweih",
				fr = "Ramure intacte de grand cerf",
				it = "Corna Intatte di Cervo Maestoso",
				pt = "Chifre de Grande Cervo Intacto",
				ru = "Неповрежденный рог большого оленя",
				ko = "온전한 큰사슴 뿔",
				cn = "完整的雄鹿鹿角",
			},
		},
	
		[250541] = {
			readable = "Treasure Chest",
			model = 1402238,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[250542] = {
			readable = "Old Scrap of Paper",
			model = 936411,
			text = {
				en = "Old Scrap of Paper",
				es = "Tira de papel antigua",
				de = "Alter Papierfetzen",
				fr = "Vieux morceau de papier",
				it = "Vecchio Pezzo di Carta",
				pt = "Pedaço de Papel Antigo",
				ru = "Древний клочок бумаги",
				cn = "一张旧纸",
			},
		},
	
		[250544] = {
			readable = "The Manastorm Decision",
			model = 1005455,
			text = {
				en = "The Manastorm Decision",
				es = "La decisión de Tormenta de Maná",
				de = "Die Manasturmentscheidung",
				fr = "Le choix de Tempête-de-Mana",
				it = "La Decisione di Manalampo",
				pt = "A Decisão de Manavento",
				ru = "\"Решимость Манашторма\"",
				cn = "法力风暴的决意",
			},
		},
	
		[250545] = {
			readable = "The Hunter of Mages",
			model = 1367404,
			text = {
				en = "The Hunter of Mages",
				es = "El cazador de magos",
				de = "Der Magierjäger",
				fr = "Le chasseur de mages",
				it = "Cacciatore di Maghi",
				pt = "O Caçador de Magos",
				ru = "\"Истребитель магов\"",
				cn = "法师猎手",
			},
		},
	
		[250546] = {
			readable = "Forgotten Missive",
			model = 936411,
			text = {
				en = "Forgotten Missive",
				es = "Misiva olvidada",
				de = "Vergessene Nachricht",
				fr = "Missive oubliée",
				it = "Missiva Dimenticata",
				pt = "Carta Esquecida",
				ru = "Позабытое послание",
				cn = "被遗忘的文件",
			},
		},
	
		[250548] = {
			readable = "Hammer of Khaz'goroth",
			model = 1140310,
			text = {
				en = "Hammer of Khaz'goroth",
				es = "Martillo de Khaz'goroth",
				de = "Hammer von Khaz'goroth",
				fr = "Marteau de Khaz’goroth",
				it = "Martello di Khaz'goroth",
				pt = "Martelo de Khaz'goroth",
				ru = "Молот Каз'горота",
				ko = "카즈고로스의 망치",
				cn = "卡兹格罗斯之锤",
			},
		},
	
		[250549] = {
			readable = "Old Journal",
			model = 949613,
			text = {
				en = "Old Journal",
				es = "Viejo diario",
				de = "Altes Tagebuch",
				fr = "Vieux journal",
				it = "Vecchio Diario",
				pt = "Diário Antigo",
				ru = "Старый дневник",
				cn = "旧日记",
			},
		},
	
		[250552] = {
			readable = "Locked Cage",
			model = 1248970,
			text = {
				en = "Locked Cage",
				es = "Jaula cerrada",
				de = "Verschlossener Käfig",
				fr = "Cage verrouillée",
				it = "Gabbia Chiusa",
				pt = "Jaula Trancada",
				ru = "Запертая клетка",
				ko = "잠긴 우리",
				cn = "锁住的牢笼",
			},
		},
	
		[250560] = {
			readable = "Legion Banner",
			model = 1303842,
			text = {
				en = "Legion Banner",
				es = "Estandarte de la Legión",
				de = "Banner der Legion",
				fr = "Bannière de la Légion",
				it = "Stendardo della Legione",
				pt = "Estandarte da Legião",
				ru = "Знамя Легиона",
				ko = "군단 깃발",
				cn = "军团旗帜",
			},
		},
	
		[250575] = {
			readable = "Portal to the Vault",
			model = 244119,
			text = {
				en = "Portal to the Vault",
				es = "Portal a la Cámara",
				de = "Portal zum Gewölbe",
				fr = "Portail menant au caveau",
				it = "Portale per la Camera Blindata",
				pt = "Portal para a Câmara",
				ru = "Портал в хранилище",
				cn = "通往地窟的传送门",
			},
		},
	
		[250576] = {
			readable = "Powerful Mana Gem",
			model = 1282671,
			text = {
				en = "Powerful Mana Gem",
				es = "Gema de maná poderosa",
				de = "Machtvoller Manaedelstein",
				fr = "Gemme de mana puissante",
				it = "Potente Gemma di Mana",
				pt = "Gema de Mana Poderosa",
				ru = "Мощный самоцвет маны",
				ko = "강력한 마나석",
				cn = "强能法力宝石",
			},
		},
	
		[250581] = {
			readable = "Nightborn Chest",
			model = 1349622,
			text = {
				en = "Nightborn Chest",
				es = "Cofre Nocheterna",
				de = "Truhe der Nachtgeborenen",
				fr = "Coffre sacrenuit",
				it = "Cassa dei Nobili Oscuri",
				pt = "Baú dos Filhos da Noite",
				ru = "Сундук ночнорожденных",
				ko = "나이트본 상자",
				cn = "夜之子箱子",
			},
		},
	
		[250587] = {
			readable = "Bucket of Blue Paint",
			model = 197644,
			text = {
				en = "Bucket of Blue Paint",
				es = "Cubo de pintura azul",
				de = "Eimer mit blauer Farbe",
				fr = "Seau de peinture bleue",
				it = "Secchio di Vernice Blu",
				pt = "Balde de Tinta Azul",
				ru = "Ведро синей краски",
				ko = "암청색 도료가 든 양동이",
				cn = "一桶蓝色颜料",
			},
		},
	
		[250588] = {
			readable = "Bucket of Green Paint",
			model = 197644,
			text = {
				en = "Bucket of Green Paint",
				es = "Cubo de pintura verde",
				de = "Eimer mit grüner Farbe",
				fr = "Seau de peinture verte",
				it = "Secchio di Vernice Verde",
				pt = "Balde de Tinta Verde",
				ru = "Ведро зеленой краски",
				ko = "담녹색 도료가 든 양동이",
				cn = "一桶绿色颜料",
			},
		},
	
		[250589] = {
			readable = "Bucket of Teal Paint",
			model = 197644,
			text = {
				en = "Bucket of Teal Paint",
				es = "Cubo de pintura cian",
				de = "Eimer mit graublauer Farbe",
				fr = "Seau de peinture turquoise",
				it = "Secchio di Vernice Verde Acqua",
				pt = "Balde de Tinta Turquesa",
				ru = "Ведро зеленовато-голубой краски",
				ko = "청록색 도료가 든 양동이",
				cn = "一桶青色颜料",
			},
		},
	
		[250590] = {
			readable = "Bucket of Grey Paint",
			model = 197644,
			text = {
				en = "Bucket of Grey Paint",
				es = "Cubo de pintura gris",
				de = "Eimer mit grauer Farbe",
				fr = "Seau de peinture grise",
				it = "Secchio di Vernice Grigia",
				pt = "Balde de Tinta Cinza",
				ru = "Ведро серой краски",
				ko = "암회색 도료가 든 양동이",
				cn = "一桶灰色颜料",
			},
		},
	
		[250591] = {
			readable = "A Study of Hexes",
			model = 1124087,
			text = {
				en = "A Study of Hexes",
				es = "Un estudio sobre maleficios",
				de = "Eine Studie zu Verhexungen",
				fr = "Étude des maléfices",
				it = "Studio sulle Maledizioni",
				pt = "Um Estudo de Bagatas",
				ru = "Трактат о сглазах",
			},
		},
	
		[250592] = {
			readable = "Healing with Arcana",
			model = 1124089,
			text = {
				en = "Healing with Arcana",
				es = "Sanar con magia Arcana",
				de = "Heilen mit Arkana",
				fr = "La guérison par les Arcanes",
				it = "Curare con la Magia Arcana",
				pt = "Cura com Arcanismo",
				ru = "Лечение тайной магией",
			},
		},
	
		[250593] = {
			readable = "Tash'irel's Edict",
			model = 1124084,
			text = {
				en = "Tash'irel's Edict",
				es = "Edicto de Tash'irel",
				de = "Tash'irels Erlass",
				fr = "Édit de Tash’irel",
				it = "Editto di Tash'irel",
				pt = "Édito de Tash'irel",
				ru = "Эдикт Таш'иреля",
			},
		},
	
		[250594] = {
			readable = "Hearty Haunch",
			model = 198232,
			text = {
				en = "Hearty Haunch",
				es = "Anca suculenta",
				de = "Herzhafte Keule",
				fr = "Cuissot dodu",
				it = "Cosciotto Polposo",
				pt = "Pernil Carnudo",
				ru = "Сочный окорок",
			},
		},
	
		[250600] = {
			readable = "Ritual Notes",
			model = 1367405,
			text = {
				en = "Ritual Notes",
				es = "Notas de ritual",
				de = "Ritualnotizen",
				fr = "Notes de rituel",
				it = "Note sul Rituale",
				pt = "Anotações do Ritual",
				ru = "Записи о ритуале",
				ko = "의식 기록",
				cn = "仪式记录",
			},
		},
	
		[250602] = {
			readable = "Functional Ward",
			model = 194471,
			text = {
				en = "Functional Ward",
				es = "Resguardo operativo",
				de = "Funktionierender Zauberschutz",
				fr = "Protection fonctionnelle",
				it = "Protezione Attiva",
				pt = "Proteção Funcional",
				ru = "Действующий оберег",
				ko = "작동하는 수호물",
				cn = "运转的结界",
			},
		},
	
		[250603] = {
			readable = "Curiously Charged Ring",
			model = 433636,
			text = {
				en = "Curiously Charged Ring",
				es = "Anillo de carga curiosa",
				de = "Seltsam geladener Ring",
				fr = "Anneau curieusement chargé",
				it = "Anello Stranamente Carico",
				pt = "Anel Curiosamente Carregado",
				ru = "Кольцо со странным зарядом",
				ko = "기묘한 기운을 발하는 반지",
				cn = "神奇的充能戒指",
			},
		},
	
		[250606] = {
			readable = "Asgrim the Dreadkiller",
			model = 1132275,
			text = {
				en = "Asgrim the Dreadkiller",
				es = "Asgrim el Mataterrador",
				de = "Asgrim der Schreckenstöter",
				fr = "Asgrim le Tueur de l’effroi",
				it = "Asgrim il Macellaio del Terrore",
				pt = "Asgrim, o Algoz Medonho",
				ru = "Азгрим Смертоубийца",
				ko = "공포살해자 아스그림",
				cn = "亡灵杀手艾斯格里姆",
			},
		},
	
		[250607] = {
			readable = "Hakkap One-leg",
			model = 1132275,
			text = {
				en = "Hakkap One-leg",
				es = "Hakkap Una Pierna",
				de = "Hakkap Einbein",
				fr = "Hakkap Unijambe",
				it = "Hakkap Monogamba",
				pt = "Hakka, o Coxo",
				ru = "Хаккап Одноногий",
				ko = "외다리 하캅",
				cn = "“独腿”哈卡普",
			},
		},
	
		[250609] = {
			readable = "Teleporter Pad",
			model = 1416747,
			text = {
				en = "Teleporter Pad",
				es = "Plataforma de teletransportador",
				de = "Teleportationsplattform",
				fr = "Plateforme du téléporteur",
				it = "Piattaforma di Teletrasporto",
				pt = "Plataforma de Teleporte",
				ru = "Площадка телепортера",
				ko = "순간이동기 장치",
				cn = "传送台",
			},
		},
	
		[250611] = {
			readable = "Ritual Focusing Crystal",
			model = 1108689,
			text = {
				en = "Ritual Focusing Crystal",
				es = "Cristal de enfoque de ritual",
				de = "Ritualfokuskristall",
				fr = "Cristal de focalisation de rituel",
				it = "Cristallo Focalizzante Rituale",
				pt = "Cristal de Concentração de Ritual",
				ru = "Ритуальный фокусирующий кристалл",
				ko = "의식 집중의 수정",
				cn = "仪式聚焦水晶",
			},
		},
	
		[250612] = {
			readable = "Snaggle's Note",
			model = 936419,
			text = {
				en = "Snaggle's Note",
				es = "Nota de Snaggle",
				de = "Schnackis Notiz",
				fr = "Lavrille",
				it = "Nota di Snag",
				pt = "Bilhete de Snégol",
				ru = "Записка Шестихвата",
				ko = "스내글의 쪽지",
			},
		},
	
		[250638] = {
			readable = "Ruined Switch",
			model = 1352478,
			text = {
				en = "Ruined Switch",
				es = "Interruptor estropeado",
				de = "Alter Schalter",
				fr = "Interrupteur endommagé",
				it = "Pulsante Rovinato",
				pt = "Interruptor Destruído",
				ru = "Сломанный переключатель",
				ko = "망가진 작동 장치",
				cn = "损坏的开关",
			},
		},
	
		[250639] = {
			readable = "Orb Light",
			model = 1352478,
			text = {
				en = "Orb Light",
				es = "Luz de orbe",
				de = "Kugellicht",
				fr = "Lumière de l’orbe",
				it = "Globo di Luce",
				pt = "Luz do Orbe",
				ru = "Сфера Света",
				ko = "보주 빛",
				cn = "宝珠之光",
			},
		},
	
		[250640] = {
			readable = "Orb Light",
			model = 1352478,
			text = {
				en = "Orb Light",
				es = "Luz de orbe",
				de = "Kugellicht",
				fr = "Lumière de l’orbe",
				it = "Globo di Luce",
				pt = "Luz do Orbe",
				ru = "Сфера Света",
				ko = "보주 빛",
				cn = "宝珠之光",
			},
		},
	
		[250641] = {
			readable = "Ruined Switch",
			model = 1352478,
			text = {
				en = "Ruined Switch",
				es = "Interruptor estropeado",
				de = "Alter Schalter",
				fr = "Interrupteur endommagé",
				it = "Pulsante Rovinato",
				pt = "Interruptor Destruído",
				ru = "Сломанный переключатель",
				ko = "망가진 작동 장치",
				cn = "损坏的开关",
			},
		},
	
		[250642] = {
			readable = "Shimmering Whorl",
			model = 603833,
			text = {
				en = "Shimmering Whorl",
				es = "Espiral fulgurante",
				de = "Schimmernder Wirbel",
				fr = "Volute chatoyante",
				it = "Spirale Scintillante",
				pt = "Redemoinho Cintilante",
				ru = "Мерцающий вихрь",
				ko = "희미하게 빛나는 소용돌이",
				cn = "发光的漩涡",
			},
		},
	
		[250648] = {
			readable = "Trollbane's Tomb",
			model = 364645,
			text = {
				en = "Trollbane's Tomb",
				es = "Tumba de Aterratrols",
				de = "Trollbanns Grabmal",
				fr = "Tombeau de Trollemort",
				it = "Tomba del Cacciatroll",
				pt = "Tumba de Matatroll",
				ru = "Могила Троллебоя",
				ko = "트롤베인의 무덤",
				cn = "托尔贝恩的墓室",
			},
		},
	
		[250650] = {
			readable = "Witherbark Supplies",
			model = 658167,
			text = {
				en = "Witherbark Supplies",
				es = "Suministros Secacorteza",
				de = "Vorräte der Bleichborken",
				fr = "Provisions fanécorces",
				it = "Forniture degli Scorzasecca",
				pt = "Suprimentos Cascasseca",
				ru = "Припасы племени Сухокожих",
			},
		},
	
		[250651] = {
			readable = "Skyfire Stone",
			model = 196687,
			text = {
				en = "Skyfire Stone",
				es = "Piedra Abrasacielos",
				de = "Himmelsfeuerstein",
				fr = "Pierre du Brûleciel",
				pt = "Pedra Celesfogo",
				ru = "Камень \"Небесного Огня\"",
			},
		},
	
		[250661] = {
			readable = "Pest-Be-Gone Bomb",
			model = 166564,
			text = {
				en = "Pest-Be-Gone Bomb",
				es = "Bomba no-más-peste",
				de = "\"Ab die Pest\"-Bombe",
				fr = "Bombe pesticide",
				pt = "Bomba Antipragas",
				ru = "Инсектицидная бомба",
			},
		},
	
		[250666] = {
			readable = "Seal of the Earth",
			model = 1358996,
			text = {
				en = "Seal of the Earth",
				es = "Sello de la tierra",
				de = "Siegel der Erde",
				fr = "Sceau de la terre",
				it = "Sigillo della Terra",
				pt = "Selo da Terra",
				ru = "Печать земли",
				ko = "땅의 인장",
				cn = "大地封印",
			},
		},
	
		[250667] = {
			readable = "Seal of the Sky",
			model = 1358996,
			text = {
				en = "Seal of the Sky",
				es = "Sello del cielo",
				de = "Siegel des Himmels",
				fr = "Sceau du ciel",
				it = "Sigillo del Cielo",
				pt = "Selo do Céu",
				ru = "Печать неба",
				ko = "하늘의 인장",
				cn = "天空封印",
			},
		},
	
		[250671] = {
			readable = "Notes on the Veiled Hand",
			text = {
				en = "Notes on the Veiled Hand",
			},
		},
	
		[250677] = {
			readable = "Empowered Nether Crucible",
			model = 1101712,
			text = {
				en = "Empowered Nether Crucible",
				es = "Crisol abisal potenciado",
				de = "Mächtiger Nethertiegel",
				fr = "Creuset du Néant surpuissant",
				it = "Crogiolo Fatuo Potenziato",
				pt = "Crisol Etéreo Potencializado",
				ru = "Заряженное горнило Пустоты",
			},
		},
	
		[250678] = {
			readable = "Blood of the Innocent",
			model = 1063313,
			text = {
				en = "Blood of the Innocent",
				es = "Sangre del inocente",
				de = "Blut des Unschuldigen",
				fr = "Sang des innocents",
				it = "Sangue dell'Innocente",
				pt = "Sangue do Inocente",
				ru = "Кровь невинных",
				ko = "무고한 희생자의 피",
				cn = "无辜者的鲜血",
			},
		},
	
		[250679] = {
			readable = "Frenzied Fish",
			model = 219406,
			text = {
				en = "Frenzied Fish",
				es = "Peces demenciados",
				de = "Rasende Fische",
				fr = "Poisson frénétique",
				it = "Banco di Pesci Frenetici",
				pt = "Peixe Frenético",
				ru = "Обезумевшая рыба",
				cn = "发狂的鱼",
			},
		},
	
		[250680] = {
			readable = "Frenzied Fish",
			model = 219406,
			text = {
				en = "Frenzied Fish",
				es = "Peces demenciados",
				de = "Rasende Fische",
				fr = "Poisson frénétique",
				it = "Banco di Pesci Frenetici",
				pt = "Peixe Frenético",
				ru = "Обезумевшая рыба",
				cn = "发狂的鱼",
			},
		},
	
		[250681] = {
			readable = "Frenzied Fish",
			model = 219406,
			text = {
				en = "Frenzied Fish",
				es = "Peces demenciados",
				de = "Rasende Fische",
				fr = "Poisson frénétique",
				it = "Banco di Pesci Frenetici",
				pt = "Peixe Frenético",
				ru = "Обезумевшая рыба",
				cn = "发狂的鱼",
			},
		},
	
		[250682] = {
			readable = "Skull of the Innocent",
			model = 985300,
			text = {
				en = "Skull of the Innocent",
				es = "Cráneo del inocente",
				de = "Schädel des Unschuldigen",
				fr = "Crâne d’un innocent",
				it = "Teschio dell'Innocente",
				pt = "Crânio do Inocente",
				ru = "Череп невинного",
				ko = "무고한 희생자의 해골",
				cn = "无辜者的颅骨",
			},
		},
	
		[250696] = {
			readable = "Legends of the Earth",
			model = 198016,
			text = {
				en = "Legends of the Earth",
				es = "Leyendas de la Tierra",
				de = "Legenden der Erde",
				fr = "Légendes de la Terre",
				it = "Leggende della Terra",
				pt = "Lendas da Terra",
				ru = "Легенды Земли",
				ko = "대지의 전설",
				cn = "大地传说",
			},
		},
	
		[250720] = {
			readable = "Hero's Call Board",
			icon = 1863940,
			model = 429102,
			text = {
				en = "Hero's Call Board",
				es = "Tablero de ¡Se busca héroe!",
				de = "Heldenaufruf",
				fr = "Tableau de l’appel des héros",
				it = "Bacheca degli Eroi",
				pt = "Mural do Chamado ao Heroísmo",
				ru = "Доска объявлений для героев",
				ko = "영웅의 부름 게시판",
				cn = "英雄的召唤布告牌",
				tw = "英雄召喚告示板",
			},
		},
	
		[250800] = {
			readable = "Waters of Farseeing",
			model = 201115,
			text = {
				en = "Waters of Farseeing",
				es = "Aguas de Clarividencia",
				de = "Wasser der Weitsicht",
				fr = "Eaux de longue-vision",
				it = "Acque della Lungimiranza",
				pt = "Águas da Vidência",
				ru = "Воды предвидения",
				ko = "통찰력의 물",
				cn = "先知之水",
			},
		},
	
		[250804] = {
			readable = "Hero's Call Board",
			icon = 1863940,
			model = 429102,
			text = {
				en = "Hero's Call Board",
				es = "Tablero de ¡Se busca héroe!",
				de = "Heldenaufruf",
				fr = "Tableau de l’appel des héros",
				it = "Bacheca degli Eroi",
				pt = "Mural do Chamado ao Heroísmo",
				ru = "Доска объявлений для героев",
				ko = "영웅의 부름 게시판",
				cn = "英雄的召唤布告牌",
				tw = "英雄召喚告示板",
			},
		},
	
		[250824] = {
			readable = "Platform",
			model = 1083607,
			text = {
				en = "Platform",
				es = "Plataforma",
				de = "Plattform",
				fr = "Plateforme",
				it = "Piattaforma",
				pt = "Plataforma",
				ru = "Платформа",
				ko = "연단",
				cn = "平台",
			},
		},
	
		[250866] = {
			readable = "Parachute",
			model = 534613,
			text = {
				en = "Parachute",
				es = "Paracaídas",
				de = "Fallschirm",
				it = "Paracadute",
				pt = "Paraquedas",
				ru = "Парашют",
				ko = "낙하산",
				cn = "降落伞",
			},
		},
	
		[250867] = {
			readable = "Keg of Spicy Grog",
			model = 531027,
			text = {
				en = "Keg of Spicy Grog",
				es = "Barril de grog picante",
				de = "Fass mit Gewürzgrog",
				fr = "Tonneau de grog épicé",
				it = "Barile di Grog Speziato",
				pt = "Barril de Trago Picante",
				ru = "Бочонок пряного грога",
				ko = "톡 쏘는 그로그주가 든 통",
				cn = "一桶香料烈酒",
			},
		},
	
		[250872] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250878] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250879] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250880] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250886] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250887] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250888] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250889] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250891] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250892] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250894] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250895] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250896] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250897] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250898] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250900] = {
			readable = "Summoning Troops",
			model = 166432,
			text = {
				en = "Summoning Troops",
				es = "Invocar tropas",
				de = "Beschwört Trupps",
				fr = "Invocation de soldats",
				it = "Evocazione Truppe",
				pt = "Evocando Tropas",
				ru = "Призыв отрядов",
				ko = "병력 소환",
				cn = "召唤部队",
			},
		},
	
		[250901] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250903] = {
			readable = "Large Ceremonial Drum",
			model = 1318778,
			text = {
				en = "Large Ceremonial Drum",
				es = "Tambor ceremonial grande",
				de = "Große zeremonielle Trommel",
				fr = "Grand tambour de cérémonie",
				it = "Tamburo Cerimoniale Grosso",
				pt = "Tambor Cerimonial Grande",
				ru = "Большой ритуальный барабан",
				ko = "큰 의식용 북",
			},
		},
	
		[250904] = {
			readable = "Medium Ceremonial Drum",
			model = 1318477,
			text = {
				en = "Medium Ceremonial Drum",
				es = "Tambor ceremonial mediano",
				de = "Mittelgroße zeremonielle Trommel",
				fr = "Tambour de cérémonie moyen",
				it = "Tamburo Cerimoniale Medio",
				pt = "Tambor Cerimonial Médio",
				ru = "Средний ритуальный барабан",
				ko = "중간 크기 의식용 북",
			},
		},
	
		[250905] = {
			readable = "Small Ceremonial Drum",
			model = 1319055,
			text = {
				en = "Small Ceremonial Drum",
				es = "Tambor ceremonial pequeño",
				de = "Kleine zeremonielle Trommel",
				fr = "Petit tambour de cérémonie",
				it = "Tamburo Cerimoniale Piccolo",
				pt = "Tambor Cerimonial Pequeno",
				ru = "Малый ритуальный барабан",
				ko = "작은 의식용 북",
			},
		},
	
		[250906] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250907] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250909] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250910] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250911] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
				cn = "训练部队",
			},
		},
	
		[250912] = {
			readable = "Summoning Troops",
			model = 166432,
			text = {
				en = "Summoning Troops",
				es = "Invocar tropas",
				de = "Beschwört Trupps",
				fr = "Invocation de soldats",
				it = "Evocazione Truppe",
				pt = "Evocando Tropas",
				ru = "Призыв отрядов",
				ko = "병력 소환",
			},
		},
	
		[250913] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
			},
		},
	
		[250914] = {
			readable = "Summoning Troops",
			model = 166432,
			text = {
				en = "Summoning Troops",
				es = "Invocar tropas",
				de = "Beschwört Trupps",
				fr = "Invocation de soldats",
				it = "Evocazione Truppe",
				pt = "Evocando Tropas",
				ru = "Призыв отрядов",
				ko = "병력 소환",
			},
		},
	
		[250916] = {
			readable = "Highmountain Brazier",
			model = 536000,
			text = {
				en = "Highmountain Brazier",
				es = "Blandón de Monte Alto",
				de = "Hochbergkohlenpfanne",
				fr = "Brasero de Haut-Roc",
				it = "Braciere di Alto Monte",
				pt = "Braseiro de Alta Montanha",
				ru = "Жаровня Крутогорья",
				ko = "높은산 화로",
				cn = "至高岭火盆",
			},
		},
	
		[250978] = {
			readable = "Highmountain Brazier",
			model = 536000,
			text = {
				en = "Highmountain Brazier",
				es = "Blandón de Monte Alto",
				de = "Hochbergkohlenpfanne",
				fr = "Brasero de Haut-Roc",
				it = "Braciere di Alto Monte",
				pt = "Braseiro de Alta Montanha",
				ru = "Жаровня Крутогорья",
				ko = "높은산 화로",
				cn = "至高岭火盆",
			},
		},
	
		[250979] = {
			readable = "Highmountain Brazier",
			model = 536000,
			text = {
				en = "Highmountain Brazier",
				es = "Blandón de Monte Alto",
				de = "Hochbergkohlenpfanne",
				fr = "Brasero de Haut-Roc",
				it = "Braciere di Alto Monte",
				pt = "Braseiro de Alta Montanha",
				ru = "Жаровня Крутогорья",
				ko = "높은산 화로",
				cn = "至高岭火盆",
			},
		},
	
		[250984] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[250985] = {
			readable = "Treasure Chest",
			model = 1402263,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[250987] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[250990] = {
			readable = "Crate of Ancient Relics",
			model = 310483,
			text = {
				en = "Crate of Ancient Relics",
				es = "Cajón de reliquias antiguas",
				de = "Kiste mit uralten Relikten",
				fr = "Caisse de reliques anciennes",
				it = "Cassa di Reliquie Antiche",
				pt = "Caixote de Relíquias Ancestrais",
				ru = "Ящик с древними реликвиями",
				ko = "고대 유물 상자",
				cn = "一箱古代圣物",
			},
		},
	
		[250991] = {
			readable = "Spell Barrier",
			model = 1368936,
			text = {
				en = "Spell Barrier",
				es = "Barrera de hechizos",
				de = "Zauberbarriere",
				fr = "Barrière de sorts",
				it = "Barriera Magica",
				pt = "Barreira de Feitiço",
				ru = "Чародейский барьер",
				ko = "주문 장벽",
				cn = "法术屏障",
			},
		},
	
		[250993] = {
			readable = "Grimoire of Arcane Ways",
			model = 191946,
			text = {
				en = "Grimoire of Arcane Ways",
				es = "Grimorio de arte Arcano",
				de = "Grimoire der arkanen Herangehensweisen",
				fr = "Grimoire de la voie des Arcanes",
				it = "Grimorio delle Vie Arcane",
				pt = "Grimório dos Caminhos Arcanos",
				ru = "Гримуар тайных путей",
			},
		},
	
		[250994] = {
			readable = "Highmountain Brazier",
			model = 536000,
			text = {
				en = "Highmountain Brazier",
				es = "Blandón de Monte Alto",
				de = "Hochbergkohlenpfanne",
				fr = "Brasero de Haut-Roc",
				it = "Braciere di Alto Monte",
				pt = "Braseiro de Alta Montanha",
				ru = "Жаровня Крутогорья",
				ko = "높은산 화로",
				cn = "至高岭火盆",
			},
		},
	
		[250996] = {
			readable = "Highmountain Brazier",
			model = 536000,
			text = {
				en = "Highmountain Brazier",
				es = "Blandón de Monte Alto",
				de = "Hochbergkohlenpfanne",
				fr = "Brasero de Haut-Roc",
				it = "Braciere di Alto Monte",
				pt = "Braseiro de Alta Montanha",
				ru = "Жаровня Крутогорья",
				ko = "높은산 화로",
				cn = "至高岭火盆",
			},
		},
	
		[250997] = {
			readable = "Gateway to the Black Temple",
			model = 1413577,
			text = {
				en = "Gateway to the Black Temple",
				es = "Portal al Templo Oscuro",
				de = "Tor zum Schwarzen Tempel",
				fr = "Portail vers le Temple noir",
				it = "Varco per il Tempio Nero",
				pt = "Portal para o Templo Negro",
				ru = "Врата в Черный храм",
			},
		},
})
do ObjectDB[objectID] = objectData; end
