local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	
		[251007] = {
			readable = "Crate of Ancient Relics",
			model = 310483,
			text = {
				en = "Crate of Ancient Relics",
				es = "Cajón de reliquias antiguas",
				de = "Kiste mit uralten Relikten",
				fr = "Caisse de reliques anciennes",
				it = "Cassa di Reliquie Antiche",
				pt = "Caixote de Relíquias Ancestrais",
				ru = "Ящик с древними реликвиями",
				ko = "고대 유물 상자",
				cn = "一箱古代圣物",
			},
		},
	
		[251008] = {
			readable = "Ancient Dreyrgrot Tablet",
			model = 1355115,
			text = {
				en = "Ancient Dreyrgrot Tablet",
				es = "Tablilla de Dreyrgrot antigua",
				de = "Uralte Schrifttafel von Dreyrgrot",
				fr = "Tablette antique de Dreyrgrot",
				it = "Antica Tavoletta di Dreyrgrot",
				pt = "Tabuleta Ancestral de Dreyrgrot",
				ru = "Древняя табличка Кровавого грота",
				ko = "고대 드레위르그로트 석판",
				cn = "上古戴尔格特石板",
			},
		},
	
		[251016] = {
			readable = "Smoke Bombs",
			model = 1305538,
			text = {
				en = "Smoke Bombs",
				es = "Bombas de humo",
				de = "Rauchbomben",
				fr = "Bombes fumigènes",
				it = "Bombe Fumogene",
				pt = "Bombas de Fumaça",
				ru = "Дымовые бомбы",
				ko = "연막탄",
				cn = "烟雾弹",
			},
		},
	
		[251020] = {
			readable = "Teleportation Pad",
			model = 252934,
			text = {
				en = "Teleportation Pad",
				es = "Plataforma de teletransporte",
				de = "Teleportationsplattform",
				fr = "Plateforme de téléportation",
				pt = "Plataforma de Teleporte",
				ru = "Площадка телепортера",
			},
		},
	
		[251021] = {
			readable = "Medical Supply Crate",
			model = 199636,
			text = {
				en = "Medical Supply Crate",
				es = "Cajón de suministros médicos",
				de = "Kiste mit medizinischen Versorgungsgütern",
				fr = "Caisse de fournitures médicales",
				it = "Cassa di Rifornimenti Medici",
				pt = "Caixote de Suprimentos Médicos",
				ru = "Ящик с медикаментами",
				ko = "의약 보급품 상자",
				cn = "医疗物资箱",
			},
		},
	
		[251022] = {
			readable = "Medical Supply Crate",
			model = 199636,
			text = {
				en = "Medical Supply Crate",
				es = "Cajón de suministros médicos",
				de = "Kiste mit medizinischen Versorgungsgütern",
				fr = "Caisse de fournitures médicales",
				it = "Cassa di Rifornimenti Medici",
				pt = "Caixote de Suprimentos Médicos",
				ru = "Ящик с медикаментами",
				ko = "의약 보급품 상자",
				cn = "医疗物资箱",
			},
		},
	
		[251023] = {
			readable = "Medical Supply Crate",
			model = 199636,
			text = {
				en = "Medical Supply Crate",
				es = "Cajón de suministros médicos",
				de = "Kiste mit medizinischen Versorgungsgütern",
				fr = "Caisse de fournitures médicales",
				it = "Cassa di Rifornimenti Medici",
				pt = "Caixote de Suprimentos Médicos",
				ru = "Ящик с медикаментами",
				ko = "의약 보급품 상자",
				cn = "医疗物资箱",
			},
		},
	
		[251027] = {
			readable = "Hanging Rope",
			model = 897673,
			text = {
				en = "Hanging Rope",
				es = "Cuerda colgante",
				de = "Herabhängendes Seil",
				fr = "Corde pendante",
				it = "Corda per Salire",
				pt = "Corda Pendurada",
				ru = "Свисающий канат",
				ko = "매달린 밧줄",
				cn = "悬挂的绳索",
			},
		},
	
		[251031] = {
			readable = "Highmountain Brazier",
			model = 536000,
			text = {
				en = "Highmountain Brazier",
				es = "Blandón de Monte Alto",
				de = "Hochbergkohlenpfanne",
				fr = "Brasero de Haut-Roc",
				it = "Braciere di Alto Monte",
				pt = "Braseiro de Alta Montanha",
				ru = "Жаровня Крутогорья",
				ko = "높은산 화로",
				cn = "至高岭火盆",
			},
		},
	
		[251032] = {
			readable = "Armoire",
			icon = 442732,
			model = 1368709,
			text = {
				en = "Armoire",
				es = "Ropero",
				de = "Schrank",
				it = "Comò",
				pt = "Armário",
				ru = "Комод",
				ko = "장식장",
				cn = "衣橱",
			},
		},
	
		[251034] = {
			readable = "Stack of Arcane Tomes",
			model = 1365459,
			text = {
				en = "Stack of Arcane Tomes",
				es = "Montón de escritos Arcanos",
				de = "Stapel arkaner Folianten",
				fr = "Pile de tomes des Arcanes",
				it = "Mucchio di Tomi Arcani",
				pt = "Pilha de Tomos Arcanos",
				ru = "Стопка чародейских фолиантов",
				ko = "비전 고서 더미",
				cn = "一堆魔法书籍",
			},
		},
	
		[251035] = {
			readable = "Private Correspondence",
			model = 1367068,
			text = {
				en = "Private Correspondence",
				es = "Correspondencia privada",
				de = "Privatkorrespondenz",
				fr = "Correspondance privée",
				it = "Corrispondenza Privata",
				pt = "Correspondência Particular",
				ru = "Частная корреспонденция",
				ko = "사적인 서신",
				cn = "私人信件",
			},
		},
	
		[251046] = {
			readable = "Basket of Clothing",
			model = 1353526,
			text = {
				en = "Basket of Clothing",
				es = "Cesta de ropa",
				de = "Korb voller Kleider",
				fr = "Panière de linge",
				it = "Cesto di Vestiti",
				pt = "Cesto de Roupas",
				ru = "Корзина с бельем",
				ko = "옷가지가 든 바구니",
				cn = "一篮衣服",
			},
		},
	
		[251047] = {
			readable = "Fal'adora Beacon",
			model = 1368866,
			text = {
				en = "Fal'adora Beacon",
				es = "Baliza de Fal'adora",
				de = "Signalgeber von Fal'adora",
				fr = "Balise de Fal’adora",
				it = "Faro di Fal'adora",
				pt = "Sinalizador de Fal'adora",
				ru = "Маяк Фал'адоры",
				ko = "팔라도라 신호 장치",
				cn = "法尔多拉道标",
			},
		},
	
		[251048] = {
			readable = "Matrix Punchograph 3005-E",
			model = 201022,
			text = {
				en = "Matrix Punchograph 3005-E",
				es = "Perforágrafo Matriz 3005-E",
				de = "Matrizenlochkart-o-mat 3005-E",
				fr = "Matrice d’encodage 3005-E",
				it = "Perforatrice per Matrici 3005-E",
				pt = "Batepôntico de Matriz 3005-A",
				ru = "Матричный перфограф 3005-E",
				ko = "행렬 천공기록기 3005-E",
				cn = "矩阵式打孔计算机3005-E",
			},
		},
	
		[251049] = {
			readable = "Ebonchill",
			model = 1346360,
			text = {
				en = "Ebonchill",
				es = "Ébano Glacial",
				de = "Schwarzfrost",
				fr = "Frissébène",
				it = "Gelonero",
				pt = "Ébano Gélido",
				ru = "Полярная Ночь",
				cn = "黑檀之寒",
			},
		},
	
		[251051] = {
			readable = "Portal Out of Eredar Realm",
			model = 533202,
			text = {
				en = "Portal Out of Eredar Realm",
				es = "Portal al exterior del reino eredar",
				de = "Portal aus dem Reich der Eredar",
				fr = "Portail menant hors du royaume érédar",
				it = "Portale d'Uscita dal Reame degli Eredar",
				ru = "Портал из мира эредаров",
				cn = "离开艾瑞达世界的传送门",
			},
		},
	
		[251052] = {
			readable = "Protected Treasure Chest",
			model = 446679,
			text = {
				en = "Protected Treasure Chest",
				es = "Arqueta protegida",
				de = "Geschützte Schatztruhe",
				fr = "Coffre au trésor protégé",
				it = "Cassa del Tesoro Protetta",
				pt = "Baú do Tesouro Protegido",
				ru = "Защищенный сундук с сокровищами",
				ko = "보호된 보물 상자",
				cn = "受保护的宝箱",
			},
		},
	
		[251065] = {
			readable = "Gateway to the Fel Hammer",
			model = 1413577,
			text = {
				en = "Gateway to the Fel Hammer",
				es = "Portal al Martillo Vil",
				de = "Portal zur Teufelshammer",
				fr = "Porte vers le Marteau gangrené",
				it = "Varco per la Vilmartello",
				pt = "Portal para o Martelo Vil",
				ru = "Врата на \"Молот Скверны\"",
			},
		},
	
		[251105] = {
			readable = "Portal out of the Vault",
			model = 244119,
			text = {
				en = "Portal out of the Vault",
				es = "Portal al exterior de la Cámara",
				de = "Portal aus dem Gewölbe",
				fr = "Portail menant hors du caveau",
				it = "Portale d'Uscita dalle Segrete",
				pt = "Portal para sair do cofre pessoal",
				ru = "Портал из хранилища",
				ko = "금고에서 나가는 차원문",
				cn = "离开金库的传送门",
			},
		},
	
		[251107] = {
			readable = "The Kingslayers",
			model = 353152,
			text = {
				en = "The Kingslayers",
				es = "Matarreyes",
				de = "Die Königsmörder",
				fr = "Les Régicides",
				it = "Lame Sterminatrici di Re",
				pt = "Os Regicidas",
				ru = "Убийцы Королей",
				ko = "국왕 시해자",
				cn = "弑君者",
			},
		},
	
		[251113] = {
			readable = "Ancient Highborne Tome",
			model = 1365450,
			text = {
				en = "Ancient Highborne Tome",
				es = "Tomo Altonato antiguo",
				de = "Uralter Foliant der Hochgeborenen",
				fr = "Tome des Bien-nés ancien",
				it = "Antico Tomo degli Alti Nobili",
				pt = "Tomo Altaneiro Ancestral",
				ru = "Древний фолиант высокорожденных",
				ko = "명가 고서",
				cn = "古代上层精灵书籍",
			},
		},
	
		[251114] = {
			readable = "Ancient Highborne Tome",
			model = 1365450,
			text = {
				en = "Ancient Highborne Tome",
				es = "Tomo Altonato antiguo",
				de = "Uralter Foliant der Hochgeborenen",
				fr = "Tome des Bien-nés ancien",
				it = "Antico Tomo degli Alti Nobili",
				pt = "Tomo Altaneiro Ancestral",
				ru = "Древний фолиант высокорожденных",
				ko = "명가 고서",
				cn = "古代上层精灵书籍",
			},
		},
	
		[251115] = {
			readable = "Ancient Highborne Tome",
			model = 1365450,
			text = {
				en = "Ancient Highborne Tome",
				es = "Tomo Altonato antiguo",
				de = "Uralter Foliant der Hochgeborenen",
				fr = "Tome des Bien-nés ancien",
				pt = "Tomo Altaneiro Ancestral",
				ru = "Древний фолиант высокорожденных",
				ko = "명가 고서",
				cn = "古代上层精灵书籍",
			},
		},
	
		[251116] = {
			readable = "Boat to Dalaran",
			model = 190104,
			text = {
				en = "Boat to Dalaran",
				es = "Barco a Dalaran",
				de = "Boot nach Dalaran",
				fr = "Bateau vers Dalaran",
				it = "Nave per Dalaran",
				pt = "Barco para Dalaran",
				ru = "Лодка в Даларан",
				cn = "到达拉然的船只",
			},
		},
	
		[251117] = {
			readable = "Ancient Highborne Tome",
			model = 1365450,
			text = {
				en = "Ancient Highborne Tome",
				es = "Tomo Altonato antiguo",
				de = "Uralter Foliant der Hochgeborenen",
				fr = "Tome des Bien-nés ancien",
				it = "Antico Tomo degli Alti Nobili",
				pt = "Tomo Altaneiro Ancestral",
				ru = "Древний фолиант высокорожденных",
				ko = "명가 고서",
				cn = "古代上层精灵书籍",
			},
		},
	
		[251118] = {
			readable = "Ancient Highborne Tome",
			model = 1365450,
			text = {
				en = "Ancient Highborne Tome",
				es = "Tomo Altonato antiguo",
				de = "Uralter Foliant der Hochgeborenen",
				fr = "Tome des Bien-nés ancien",
				it = "Antico Tomo degli Alti Nobili",
				pt = "Tomo Altaneiro Ancestral",
				ru = "Древний фолиант высокорожденных",
				ko = "명가 고서",
			},
		},
	
		[251119] = {
			readable = "Ancient Highborne Tome",
			model = 1365450,
			text = {
				en = "Ancient Highborne Tome",
				es = "Tomo Altonato antiguo",
				de = "Uralter Foliant der Hochgeborenen",
				fr = "Tome des Bien-nés ancien",
				it = "Antico Tomo degli Alti Nobili",
				pt = "Tomo Altaneiro Ancestral",
				ru = "Древний фолиант высокорожденных",
				ko = "명가 고서",
			},
		},
	
		[251120] = {
			readable = "Ancient Highborne Tome",
			model = 1365450,
			text = {
				en = "Ancient Highborne Tome",
				es = "Tomo Altonato antiguo",
				de = "Uralter Foliant der Hochgeborenen",
				fr = "Tome des Bien-nés ancien",
				it = "Antico Tomo degli Alti Nobili",
				pt = "Tomo Altaneiro Ancestral",
				ru = "Древний фолиант высокорожденных",
				ko = "명가 고서",
				cn = "古代上层精灵书籍",
			},
		},
	
		[251121] = {
			readable = "Ancient Highborne Tome",
			model = 1365450,
			text = {
				en = "Ancient Highborne Tome",
				es = "Tomo Altonato antiguo",
				de = "Uralter Foliant der Hochgeborenen",
				fr = "Tome des Bien-nés ancien",
				it = "Antico Tomo degli Alti Nobili",
				pt = "Tomo Altaneiro Ancestral",
				ru = "Древний фолиант высокорожденных",
				ko = "명가 고서",
				cn = "古代上层精灵书籍",
			},
		},
	
		[251122] = {
			readable = "Ancient Highborne Tome",
			model = 1365450,
			text = {
				en = "Ancient Highborne Tome",
				es = "Tomo Altonato antiguo",
				de = "Uralter Foliant der Hochgeborenen",
				fr = "Tome des Bien-nés ancien",
				it = "Antico Tomo degli Alti Nobili",
				pt = "Tomo Altaneiro Ancestral",
				ru = "Древний фолиант высокорожденных",
				ko = "명가 고서",
			},
		},
	
		[251123] = {
			readable = "Portal to Dalaran",
			model = 244119,
			text = {
				en = "Portal to Dalaran",
				es = "Portal a Dalaran",
				de = "Portal nach Dalaran",
				fr = "Portail vers Dalaran",
				it = "Portale per Dalaran",
				pt = "Portal para Dalaran",
				ru = "Портал в Даларан",
				ko = "달라란으로 통하는 차원문",
				cn = "通往达拉然的传送门",
			},
		},
	
		[251124] = {
			readable = "Glimmering Treasure Chest",
			model = 1349622,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[251125] = {
			readable = "Highmountain Brazier",
			model = 536000,
			text = {
				en = "Highmountain Brazier",
				es = "Blandón de Monte Alto",
				de = "Hochbergkohlenpfanne",
				fr = "Brasero de Haut-Roc",
				it = "Braciere di Alto Monte",
				pt = "Braseiro de Alta Montanha",
				ru = "Жаровня Крутогорья",
				ko = "높은산 화로",
				cn = "至高岭火盆",
			},
		},
	
		[251128] = {
			readable = "A Note",
			model = 936411,
			text = {
				en = "A Note",
				es = "Una nota",
				de = "Ein Notizzettel",
				fr = "Une note",
				it = "Nota",
				pt = "Uma Nota",
				ru = "Записка",
				ko = "쪽지",
				cn = "一张纸条",
			},
		},
	
		[251129] = {
			readable = "Frostrune Scroll",
			model = 198452,
			text = {
				en = "Frostrune Scroll",
				es = "Pergamino de runa de Escarcha",
				de = "Frostrunenschriftrolle",
				fr = "Parchemin de rune de givre",
				it = "Pergamena della Runa del Gelo",
				pt = "Pergaminho da Runa de Gelo",
				ru = "Свиток руны льда",
				ko = "서리룬 두루마리",
				cn = "霜符卷轴",
			},
		},
	
		[251144] = {
			readable = "Scorchrune Scroll",
			model = 198454,
			text = {
				en = "Scorchrune Scroll",
				es = "Pergamino de runa agostada",
				de = "Versengungsrunenschriftrolle",
				fr = "Parchemin de rune de brûlure",
				it = "Pergamena della Runa del Fuoco",
				pt = "Pergaminho da Runa Calcinante",
				ru = "Свиток обжигающей руны",
				ko = "불꽃룬 두루마리",
				cn = "烫符卷轴",
			},
		},
	
		[251145] = {
			readable = "Leyrune Scroll",
			model = 198451,
			text = {
				en = "Leyrune Scroll",
				es = "Pergamino de runa Ley",
				de = "Leyrunenschriftrolle",
				fr = "Parchemin de rune tellurique",
				it = "Pergamena della Runa di Faglia",
				pt = "Pergaminho da Runa do Meridiano",
				ru = "Свиток силовой руны",
				ko = "지맥룬 두루마리",
				cn = "魔符卷轴",
			},
		},
	
		[251153] = {
			readable = "Ancient Highborn Scroll of Escape",
			model = 1365481,
			text = {
				en = "Ancient Highborn Scroll of Escape",
				es = "Pergamino de huida Altonato antiguo",
				de = "Uralte Schriftrolle der Hochgeborenen",
				fr = "Parchemin d’évasion de Bien-né ancien",
				it = "Antica Pergamena della Fuga degli Alti Nobili",
				pt = "Pergaminho Ancestral do Altaneiro da Fuga",
				ru = "Древний свиток побега высокорожденных",
				ko = "탈출의 고대 명가 두루마리",
				cn = "古代上层精灵逃生卷轴",
			},
		},
	
		[251154] = {
			readable = "Ancient Highborn Scroll of Escape",
			model = 1365481,
			text = {
				en = "Ancient Highborn Scroll of Escape",
				es = "Pergamino de huida Altonato antiguo",
				de = "Uralte Schriftrolle der Hochgeborenen",
				fr = "Parchemin d’évasion de Bien-né ancien",
				it = "Antica Pergamena della Fuga degli Alti Nobili",
				pt = "Pergaminho Ancestral do Altaneiro da Fuga",
				ru = "Древний свиток побега высокорожденных",
				ko = "탈출의 고대 명가 두루마리",
				cn = "古代上层精灵逃生卷轴",
			},
		},
	
		[251155] = {
			readable = "Fel Blood",
			model = 984595,
			text = {
				en = "Fel Blood",
				es = "Sangre vil",
				de = "Teufelsblut",
				fr = "Gangresang",
				it = "Vilsangue",
				pt = "Sangue Vil",
				ru = "Оскверненная кровь",
				ko = "지옥 피",
				cn = "魔血",
			},
		},
	
		[251168] = {
			readable = "Ephemeral Crystal",
			icon = 458245,
			model = 942442,
			text = {
				en = "Ephemeral Crystal",
				es = "Cristal efímero",
				de = "Flüchtiger Kristall",
				fr = "Cristal éphémère",
				it = "Cristallo Effimero",
				pt = "Cristal Efêmero",
				ru = "Эфемерный кристалл",
				ko = "찰나의 수정",
				cn = "瞬灭水晶",
			},
		},
	
		[251173] = {
			readable = "Forbidden Tome",
			model = 1323497,
			text = {
				en = "Forbidden Tome",
				es = "Escrito prohibido",
				de = "Verbotener Foliant",
				fr = "Tome interdit",
				it = "Tomo Dimenticato",
				pt = "Tomo Proibido",
				ru = "Запретный фолиант",
				ko = "금단의 고서",
				cn = "禁忌魔典",
			},
		},
	
		[251176] = {
			readable = "Legion Portal",
			model = 1268729,
			text = {
				en = "Legion Portal",
				es = "Portal de la Legión",
				de = "Legionsportal",
				fr = "Portail de la Légion",
				it = "Portale della Legione",
				pt = "Portal da Legião",
				ru = "Портал Легиона",
			},
		},
	
		[251178] = {
			readable = "Arcane Portal",
			model = 197017,
			text = {
				en = "Arcane Portal",
				es = "Portal Arcano",
				de = "Arkanes Portal",
				fr = "Portail des Arcanes",
				it = "Portale Arcano",
				pt = "Portal Arcano",
				ru = "Чародейский портал",
			},
		},
	
		[251179] = {
			readable = "Legion Portal",
			model = 1125327,
			text = {
				en = "Legion Portal",
				es = "Portal de la Legión",
				de = "Legionsportal",
				fr = "Portail de la Légion",
				it = "Portale della Legione",
				pt = "Portal da Legião",
				ru = "Портал Легиона",
			},
		},
	
		[251180] = {
			readable = "Felblaze Oil",
			model = 1305541,
			text = {
				en = "Felblaze Oil",
				es = "Aceite de llamarada vil",
				de = "Teufelslohenöl",
				fr = "Huile du Brasier infernal",
				it = "Olio di Vilfiamma",
				pt = "Óleo Brasavil",
				ru = "Масло пламени Скверны",
				ko = "지옥화염 기름",
				cn = "邪焰油膏",
			},
		},
	
		[251181] = {
			readable = "Azure Ore",
			model = 219418,
			text = {
				en = "Azure Ore",
				es = "Mena azur",
				de = "Azurerz",
				fr = "Minerai azur",
				it = "Minerale Azzurro",
				pt = "Minério Lazúli",
				ru = "Лазурная руда",
				cn = "蔚蓝矿石",
			},
		},
	
		[251182] = {
			readable = "Scrying Orb",
			model = 125825,
			text = {
				en = "Scrying Orb",
				es = "Orbe de visión",
				de = "Seherkugel",
				fr = "Orbe de divination",
				it = "Sfera della Chiaroveggenza",
				pt = "Orbe de Vidência",
				ru = "Гадальный шар",
				ko = "수정구",
				cn = "占卜宝珠",
			},
		},
	
		[251183] = {
			readable = "Ephemeral Crystal",
			model = 942442,
			text = {
				en = "Ephemeral Crystal",
				es = "Cristal efímero",
				de = "Flüchtiger Kristall",
				fr = "Cristal éphémère",
				it = "Cristallo Effimero",
				pt = "Cristal Efêmero",
				ru = "Эфемерный кристалл",
				ko = "찰나의 수정",
				cn = "瞬灭水晶",
			},
		},
	
		[251185] = {
			readable = "Ephemeral Crystal",
			model = 942442,
			text = {
				en = "Ephemeral Crystal",
				es = "Cristal efímero",
				de = "Flüchtiger Kristall",
				fr = "Cristal éphémère",
				it = "Cristallo Effimero",
				pt = "Cristal Efêmero",
				ru = "Эфемерный кристалл",
				ko = "찰나의 수정",
				cn = "瞬灭水晶",
			},
		},
	
		[251186] = {
			readable = "Ephemeral Crystal",
			model = 942442,
			text = {
				en = "Ephemeral Crystal",
				es = "Cristal efímero",
				de = "Flüchtiger Kristall",
				fr = "Cristal éphémère",
				it = "Cristallo Effimero",
				pt = "Cristal Efêmero",
				ru = "Эфемерный кристалл",
				ko = "찰나의 수정",
				cn = "瞬灭水晶",
			},
		},
	
		[251187] = {
			readable = "Ephemeral Crystal",
			model = 942442,
			text = {
				en = "Ephemeral Crystal",
				es = "Cristal efímero",
				de = "Flüchtiger Kristall",
				fr = "Cristal éphémère",
				it = "Cristallo Effimero",
				pt = "Cristal Efêmero",
				ru = "Эфемерный кристалл",
				ko = "찰나의 수정",
				cn = "瞬灭水晶",
			},
		},
	
		[251188] = {
			readable = "Wicked-Looking Spear",
			model = 874421,
			text = {
				en = "Wicked-Looking Spear",
				es = "Lanza de aspecto maligno",
				de = "Tückisch aussehender Speer",
				fr = "Lance menaçante",
				it = "Lancia dall'Aspetto Malvagio",
				pt = "Lança de Aspecto Perverso",
				ru = "Жуткое копье",
				ko = "위험해 보이는 창",
				cn = "狰狞的长矛",
			},
		},
	
		[251189] = {
			readable = "Plate of Leftovers",
			model = 996178,
			text = {
				en = "Plate of Leftovers",
				es = "Plato de sobras",
				de = "Teller mit Essensresten",
				fr = "Assiette de restes",
				it = "Piatto di Avanzi",
				pt = "Prato de Sobras",
				ru = "Тарелка с объедками",
				ko = "잔반 접시",
				cn = "一盘剩菜",
			},
		},
	
		[251190] = {
			readable = "Containment Field",
			model = 1408528,
			text = {
				en = "Containment Field",
				es = "Campo de contención",
				de = "Eindämmungsfeld",
				fr = "Champ de confinement",
				it = "Campo di Contenimento",
				pt = "Campo de Contenção",
				ru = "Сдерживающее поле",
				ko = "억제장",
				cn = "压制力场",
			},
		},
	
		[251191] = {
			readable = "Ancient Bones",
			model = 192653,
			text = {
				en = "Ancient Bones",
				es = "Huesos antiguos",
				de = "Uralte Knochen",
				fr = "Os antiques",
				it = "Ossa Antiche",
				pt = "Ossos Antigos",
				ru = "Древний скелет",
			},
		},
	
		[251195] = {
			readable = "Keg of Armor Polish",
			model = 929379,
			text = {
				en = "Keg of Armor Polish",
				es = "Barril de abrillantador para armaduras",
				de = "Fass mit Rüstungspolitur",
				fr = "Baril de cire pour armure",
				it = "Barile di Lucido per Armature",
				pt = "Barril de Graxa para Polir Armadura",
				ru = "Бочка полироля для доспехов",
				ko = "방어구 연마제 통",
				cn = "盔甲打磨桶",
			},
		},
	
		[251209] = {
			readable = "Frosted Doughnut",
			model = 243039,
			text = {
				en = "Frosted Doughnut",
				es = "Rosquilla glaseada",
				de = "Glasierter Donut",
				fr = "Beignet glacé",
				it = "Ciambella Glassata",
				pt = "Rosquinha com Cobertura",
				ru = "Замороженный пончик",
				ko = "당의를 입힌 도넛",
				cn = "糖霜甜甜圈",
			},
		},
	
		[251210] = {
			readable = "Crystal Ball",
			model = 243033,
			text = {
				en = "Crystal Ball",
				es = "Bola de cristal",
				de = "Kristallkugel",
				fr = "Boule de cristal",
				it = "Sfera di Cristallo",
				pt = "Bola de Cristal",
				ru = "Хрустальный шар",
				ko = "수정구",
				cn = "水晶球",
			},
		},
	
		[251211] = {
			readable = "Well-worn Scroll",
			model = 1365480,
			text = {
				en = "Well-worn Scroll",
				es = "Pergamino desgastado",
				de = "Abgenutzte Schriftrolle",
				fr = "Parchemin très usé",
				it = "Pergamena Consumata",
				pt = "Pergaminho Bem Gasto",
				ru = "Потрепанный свиток",
				ko = "낡은 두루마리",
				cn = "古旧的卷轴",
			},
		},
	
		[251212] = {
			readable = "Magical Tome",
			model = 1368284,
			text = {
				en = "Magical Tome",
				es = "Tomo mágico",
				de = "Magischer Foliant",
				fr = "Tome magique",
				it = "Tomo Magico",
				pt = "Tomo Mágico",
				ru = "Магический фолиант",
				ko = "마법의 고서",
				cn = "魔法书籍",
			},
		},
	
		[251216] = {
			readable = "Prison Cage",
			model = 306265,
			text = {
				en = "Prison Cage",
				es = "Jaula de prisión",
				de = "Gefängniskäfig",
				fr = "Cage de prison",
				it = "Gabbia della Prigione",
				pt = "Jaula de Prisão",
				ru = "Тюремная клетка",
			},
		},
	
		[251217] = {
			readable = "Highmountain Brazier",
			model = 536000,
			text = {
				en = "Highmountain Brazier",
				es = "Blandón de Monte Alto",
				de = "Hochbergkohlenpfanne",
				fr = "Brasero de Haut-Roc",
				it = "Braciere di Alto Monte",
				pt = "Braseiro de Alta Montanha",
				ru = "Жаровня Крутогорья",
				ko = "높은산 화로",
				cn = "至高岭火盆",
			},
		},
	
		[251218] = {
			readable = "Rollo's Runestone",
			model = 1139506,
			text = {
				en = "Rollo's Runestone",
				es = "Piedra rúnica de Rolo",
				de = "Rollos Runenstein",
				fr = "Pierre runique de Rollo",
				it = "Pietra Runica di Rollo",
				pt = "Pedra Rúnica de Rollo",
				ru = "Рунический камень Ролло",
				ko = "롤로의 룬석",
				cn = "罗洛的符文石",
			},
		},
	
		[251219] = {
			readable = "Cage",
			model = 1097623,
			text = {
				en = "Cage",
				es = "Jaula",
				de = "Käfig",
				it = "Gabbia",
				pt = "Jaula",
				ru = "Клетка",
				ko = "우리",
				cn = "牢笼",
			},
		},
	
		[251220] = {
			readable = "Ragnar's Runestone",
			model = 1139506,
			text = {
				en = "Ragnar's Runestone",
				es = "Piedra rúnica de Ragnar",
				de = "Ragnars Runenstein",
				fr = "Pierre runique de Ragnar",
				it = "Pietra Runica di Ragnar",
				pt = "Pedra Rúnica de Ragnar",
				ru = "Рунический камень Рагнара",
				ko = "라그나르의 룬석",
				cn = "拉格纳的符文石",
			},
		},
	
		[251221] = {
			readable = "Floki's Runestone",
			model = 1139506,
			text = {
				en = "Floki's Runestone",
				es = "Piedra rúnica de Floki",
				de = "Flokis Runenstein",
				fr = "Pierre runique de Floki",
				it = "Pietra Runica di Floki",
				pt = "Pedra Rúnica de Floki",
				ru = "Рунический камень Флоки",
				ko = "플로키의 룬석",
				cn = "弗洛奇的符文石",
			},
		},
	
		[251233] = {
			readable = "Light-Infused Crystals",
			model = 875120,
			text = {
				en = "Light-Infused Crystals",
				es = "Cristales imbuidos de luz",
				de = "Lichterfüllte Kristalle",
				fr = "Cristaux imprégnés de lumière",
				it = "Cristalli Infusi di Luce",
				pt = "Cristais Infusos em Luz",
				ru = "Насыщенные Светом кристаллы",
				ko = "빛이 주입된 수정",
				cn = "电能水晶",
			},
		},
	
		[251234] = {
			readable = "Light-Infused Crystals",
			model = 875122,
			text = {
				en = "Light-Infused Crystals",
				es = "Cristales imbuidos de luz",
				de = "Lichterfüllte Kristalle",
				fr = "Cristaux imprégnés de lumière",
				it = "Cristalli Infusi di Luce",
				pt = "Cristais Infusos em Luz",
				ru = "Насыщенные Светом кристаллы",
				ko = "빛이 주입된 수정",
				cn = "电能水晶",
			},
		},
	
		[251235] = {
			readable = "Light-Infused Crystals",
			model = 875124,
			text = {
				en = "Light-Infused Crystals",
				es = "Cristales imbuidos de luz",
				de = "Lichterfüllte Kristalle",
				fr = "Cristaux imprégnés de lumière",
				it = "Cristalli Infusi di Luce",
				pt = "Cristais Infusos em Luz",
				ru = "Насыщенные Светом кристаллы",
				ko = "빛이 주입된 수정",
				cn = "电能水晶",
			},
		},
	
		[251250] = {
			readable = "Baked Fish",
			model = 643924,
			text = {
				en = "Baked Fish",
				es = "Pescado horneado",
				de = "Backfisch",
				fr = "Poisson cuit",
				it = "Pesce Arrosto",
				pt = "Peixe Assado",
				ru = "Запеченная рыба",
				ko = "구운 생선",
				cn = "烤鱼",
			},
		},
	
		[251251] = {
			readable = "Baked Fowl",
			model = 643992,
			text = {
				en = "Baked Fowl",
				es = "Ave horneada",
				de = "Geflügelbraten",
				fr = "Volaille cuite",
				it = "Pollo Arrosto",
				pt = "Ave Assada",
				ru = "Запеченная дичь",
				ko = "새 구이",
				cn = "烤鸡",
			},
		},
	
		[251252] = {
			readable = "Dumplings",
			model = 643878,
			text = {
				en = "Dumplings",
				es = "Empanadillas",
				de = "Klößchen",
				fr = "Raviolis",
				it = "Ravioli",
				pt = "Bolinhos",
				ru = "Кнедлики",
				ko = "만두",
				cn = "饺子",
			},
		},
	
		[251253] = {
			readable = "Fried Rice",
			model = 643884,
			text = {
				en = "Fried Rice",
				es = "Arroz frito",
				de = "Gebratener Reis",
				fr = "Riz poêlé",
				it = "Riso Fritto",
				pt = "Arroz Frito",
				ru = "Жареный рис",
				ko = "볶음밥",
				cn = "炒饭",
			},
		},
	
		[251254] = {
			readable = "Grilled Fish",
			model = 642790,
			text = {
				en = "Grilled Fish",
				es = "Pescado a la parrilla",
				de = "Gegrillter Fisch",
				fr = "Poisson grillé",
				it = "Pesce alla Griglia",
				pt = "Peixe Grelhado",
				ru = "Жареная на гриле рыба",
				ko = "생선 숯불구이",
				cn = "烤鱼",
			},
		},
	
		[251255] = {
			readable = "Ribs",
			model = 642792,
			text = {
				en = "Ribs",
				es = "Costillas",
				de = "Rippchen",
				fr = "Côtelettes",
				it = "Costolette",
				pt = "Costelas",
				ru = "Ребрышки",
				ko = "갈비",
				cn = "肋排",
			},
		},
	
		[251257] = {
			readable = "Tideskorn Harpoon Launcher",
			model = 124328,
			text = {
				en = "Tideskorn Harpoon Launcher",
				es = "Lanzarpones de Mareskorn",
				de = "Harpunenschleuder der Wellenskorn",
				fr = "Lance-harpon mörgestran",
				it = "Lancia Arpioni degli Abiskorn",
				pt = "Lançador de Arpões Mareskárnio",
				ru = "Волнскорнская гарпунная пушка",
				ko = "타이드스코른 작살 발사대",
				cn = "蔑潮鱼叉发射器",
			},
		},
	
		[251258] = {
			readable = "Arcane Portal",
			model = 197017,
			text = {
				en = "Arcane Portal",
				es = "Portal Arcano",
				de = "Arkanes Portal",
				fr = "Portail des Arcanes",
				it = "Portale Arcano",
				pt = "Portal Arcano",
				ru = "Чародейский портал",
			},
		},
	
		[251260] = {
			readable = "Arcane Portal",
			model = 197017,
			text = {
				en = "Arcane Portal",
				es = "Portal Arcano",
				de = "Arkanes Portal",
				fr = "Portail des Arcanes",
				it = "Portale Arcano",
				pt = "Portal Arcano",
				ru = "Чародейский портал",
			},
		},
	
		[251261] = {
			readable = "Arcane Portal",
			model = 197017,
			text = {
				en = "Arcane Portal",
				es = "Portal Arcano",
				de = "Arkanes Portal",
				fr = "Portail des Arcanes",
				it = "Portale Arcano",
				pt = "Portal Arcano",
				ru = "Чародейский портал",
			},
		},
	
		[251262] = {
			readable = "Portal to Violet Hold",
			model = 244119,
			text = {
				en = "Portal to Violet Hold",
				es = "Portal a Bastión Violeta",
				de = "Portal zur Violetten Festung",
				fr = "Portail vers le fort Pourpre",
				it = "Portale per la Terrazza Violacea",
				pt = "Portal para o Castelo Violeta",
				ru = "Портал в Аметистовую крепость",
				cn = "通往紫罗兰监狱的传送门",
			},
		},
	
		[251263] = {
			readable = "Arcane Portal",
			model = 197017,
			text = {
				en = "Arcane Portal",
				es = "Portal Arcano",
				de = "Arkanes Portal",
				fr = "Portail des Arcanes",
				it = "Portale Arcano",
				pt = "Portal Arcano",
				ru = "Чародейский портал",
			},
		},
	
		[251264] = {
			readable = "Summoning Troops",
			model = 166432,
			text = {
				en = "Summoning Troops",
				es = "Invocar tropas",
				de = "Beschwört Trupps",
				fr = "Invocation de soldats",
				it = "Evocazione Truppe",
				pt = "Evocando Tropas",
				ru = "Призыв отрядов",
				ko = "병력 소환",
			},
		},
	
		[251265] = {
			readable = "Summoning Troops",
			model = 166432,
			text = {
				en = "Summoning Troops",
				es = "Invocar tropas",
				de = "Beschwört Trupps",
				fr = "Invocation de soldats",
				it = "Evocazione Truppe",
				pt = "Evocando Tropas",
				ru = "Призыв отрядов",
				ko = "병력 소환",
			},
		},
	
		[251271] = {
			readable = "Shriektalon Totem",
			model = 198960,
			text = {
				en = "Shriektalon Totem",
				es = "Tótem Garfalarido",
				de = "Kreischklauentotem",
				fr = "Totem serre-hurlante",
				it = "Totem Strillartigli",
				pt = "Totem Guinchagarra",
				ru = "Тотем Визжащего Когтя",
				ko = "절규발톱 토템",
				cn = "啸爪图腾",
			},
		},
	
		[251272] = {
			readable = "Fearfeather Totem",
			model = 198961,
			text = {
				en = "Fearfeather Totem",
				es = "Tótem Plumaterror",
				de = "Angstfedertotem",
				fr = "Totem plume-de-peur",
				it = "Totem Dilaniapiume",
				pt = "Totem Plumedonho",
				ru = "Тотем Жуткого Пера",
				ko = "공포깃털 토템",
				cn = "恐羽图腾",
			},
		},
	
		[251273] = {
			readable = "Reaverbeak Totem",
			model = 198962,
			text = {
				en = "Reaverbeak Totem",
				es = "Tótem Picoatracador",
				de = "Häscherschnabeltotem",
				fr = "Totem bec-saccageur",
				it = "Totem Razziabecchi",
				pt = "Totem Destruirrostro",
				ru = "Тотем Яростного Клюва",
				ko = "약탈부리 토템",
				cn = "掠喙图腾",
			},
		},
	
		[251286] = {
			readable = "Illidari Gateway",
			model = 1413577,
			text = {
				en = "Illidari Gateway",
				es = "Portal Illidari",
				de = "Illidaritor",
				fr = "Porte illidari",
				it = "Varco degli Illidari",
				pt = "Portal Illidari",
				ru = "Врата иллидари",
				ko = "일리다리 관문",
				cn = "伊利达雷传送门",
			},
		},
	
		[251287] = {
			readable = "Massive Azsunian Pearl",
			model = 338524,
			text = {
				en = "Massive Azsunian Pearl",
				es = "Perla de Azsuna enorme",
				de = "Riesige Azsunaperle",
				fr = "Énorme perle azsunienne",
				it = "Enorme Perla di Azsuna",
				pt = "Pérola Azsuniana Imensa",
				ru = "Крупная азсунская жемчужина",
			},
		},
	
		[251288] = {
			readable = "Gravestone",
			model = 1140779,
			text = {
				en = "Gravestone",
				es = "Lápida",
				de = "Grabstein",
				fr = "Pierre tombale",
				it = "Lapide",
				pt = "Lápide",
				ru = "Могильный камень",
				ko = "묘비",
				cn = "墓碑",
			},
		},
	
		[251290] = {
			readable = "Arcane Portal",
			model = 197017,
			text = {
				en = "Arcane Portal",
				es = "Portal Arcano",
				de = "Arkanes Portal",
				fr = "Portail des Arcanes",
				it = "Portale Arcano",
				pt = "Portal Arcano",
				ru = "Чародейский портал",
			},
		},
	
		[251291] = {
			readable = "Arcane Portal",
			model = 197017,
			text = {
				en = "Arcane Portal",
				es = "Portal Arcano",
				de = "Arkanes Portal",
				fr = "Portail des Arcanes",
				it = "Portale Arcano",
				pt = "Portal Arcano",
				ru = "Чародейский портал",
			},
		},
	
		[251293] = {
			readable = "Arcane Portal",
			model = 197017,
			text = {
				en = "Arcane Portal",
				es = "Portal Arcano",
				de = "Arkanes Portal",
				fr = "Portail des Arcanes",
				it = "Portale Arcano",
				pt = "Portal Arcano",
				ru = "Чародейский портал",
			},
		},
	
		[251294] = {
			readable = "Arcane Portal",
			model = 197017,
			text = {
				en = "Arcane Portal",
				es = "Portal Arcano",
				de = "Arkanes Portal",
				fr = "Portail des Arcanes",
				it = "Portale Arcano",
				pt = "Portal Arcano",
				ru = "Чародейский портал",
			},
		},
	
		[251295] = {
			readable = "Arcane Portal",
			model = 197017,
			text = {
				en = "Arcane Portal",
				es = "Portal Arcano",
				de = "Arkanes Portal",
				fr = "Portail des Arcanes",
				it = "Portale Arcano",
				pt = "Portal Arcano",
				ru = "Чародейский портал",
			},
		},
	
		[251302] = {
			readable = "Portal to Dreadscar Rift",
			model = 1386636,
			text = {
				en = "Portal to Dreadscar Rift",
				es = "Portal a la Falla Cicatriz del Terror",
				de = "Portal zur Schreckensnarbe",
				fr = "Portail vers la faille de Scareffroi",
				it = "Portale per la Faglia Malosfregio",
				pt = "Portal para a Fenda Chagamedo",
				ru = "Портал в разлом Зловещего Шрама",
				ko = "공포흉터 균열로 통하는 차원문",
				cn = "通往恐痕裂隙的传送门",
			},
		},
	
		[251304] = {
			readable = "Portal to Sanctum of Light",
			model = 1387204,
			text = {
				en = "Portal to Sanctum of Light",
				es = "Portal al Sagrario de la Luz",
				de = "Portal zum Sanktum des Lichts",
				fr = "Portail vers le sanctum de la Lumière",
				it = "Portale per il Santuario della Luce",
				pt = "Portal para o Sacrário da Luz",
				ru = "Портал в Обитель Света",
				ko = "빛의 성소로 통하는 차원문",
				cn = "通往圣光秘殿的传送门",
			},
		},
	
		[251305] = {
			readable = "Portal to Sanctum of Light",
			model = 1387204,
			text = {
				en = "Portal to Sanctum of Light",
				es = "Portal al Sagrario de la Luz",
				de = "Portal zum Sanktum des Lichts",
				fr = "Portail vers le sanctum de la Lumière",
				it = "Portale per il Santuario della Luce",
				pt = "Portal para o Sacrário da Luz",
				ru = "Портал в Обитель Света",
				ko = "빛의 성소로 통하는 차원문",
				cn = "通往圣光秘殿的传送门",
			},
		},
	
		[251306] = {
			readable = "Portal to Netherlight Temple",
			model = 1386770,
			text = {
				en = "Portal to Netherlight Temple",
				es = "Portal al Templo de la Luz Abisal",
				de = "Portal zum Netherlichttempel",
				fr = "Portail vers le temple Halo-du-Néant",
				it = "Portale per il Tempio di Lucefatua",
				pt = "Portal para o Templo Eterluz",
				ru = "Портал в Храм света Пустоты",
				ko = "황천빛 사원으로 통하는 차원문",
				cn = "通往虚空之光神殿的传送门",
			},
		},
	
		[251307] = {
			readable = "Portal to Netherlight Temple",
			model = 1386770,
			text = {
				en = "Portal to Netherlight Temple",
				es = "Portal al Templo de la Luz Abisal",
				de = "Portal zum Netherlichttempel",
				fr = "Portail vers le temple Halo-du-Néant",
				it = "Portale per il Tempio di Lucefatua",
				pt = "Portal para o Templo Eterluz",
				ru = "Портал в Храм света Пустоты",
				ko = "황천빛 사원으로 통하는 차원문",
				cn = "通往虚空之光神殿的传送门",
			},
		},
	
		[251311] = {
			readable = "Portal to the Maelstrom",
			model = 1386694,
			text = {
				en = "Portal to the Maelstrom",
				es = "Portal a La Vorágine",
				de = "Portal zum Mahlstrom",
				fr = "Portail vers le Maelström",
				it = "Portale per il Maelstrom",
				pt = "Portal para Voragem",
				ru = "Портал к Водовороту",
				ko = "혼돈의 소용돌이로 통하는 차원문",
				cn = "通往大漩涡的传送门",
			},
		},
	
		[251313] = {
			readable = "Portal to Dalaran",
			model = 1387276,
			text = {
				en = "Portal to Dalaran",
				es = "Portal a Dalaran",
				de = "Portal nach Dalaran",
				fr = "Portail vers Dalaran",
				it = "Portale per Dalaran",
				pt = "Portal para Dalaran",
				ru = "Портал в Даларан",
				ko = "달라란으로 통하는 차원문",
				cn = "通往达拉然的传送门",
			},
		},
	
		[251314] = {
			readable = "Sargerite Keystone",
			model = 1273114,
			text = {
				en = "Sargerite Keystone",
				es = "Piedra angular sargerita",
				de = "Sargeritschlüsselstein",
				fr = "Clé sargerite",
				it = "Chiave di Sargeras",
				pt = "Pedra-chave de Sarguerita",
				ru = "Саргеритовый ключ",
			},
		},
	
		[251315] = {
			readable = "Portal to Peak of Serenity",
			model = 615883,
			text = {
				en = "Portal to Peak of Serenity",
				es = "Portal al Pico de la Serenidad",
				de = "Portal zum Gipfel der Ruhe",
				fr = "Portail vers le pic de la Sérénité",
				it = "Portale per il Picco della Serenità",
				pt = "Portal para o Pico da Serenidade",
				ru = "Портал на пик Безмятежности",
				ko = "평온의 봉우리로 통하는 차원문",
				cn = "通往晴日峰的传送门",
			},
		},
	
		[251316] = {
			readable = "Duskwatch Weaponry",
			model = 1377130,
			text = {
				en = "Duskwatch Weaponry",
				es = "Armería de la Guardia Umbría",
				de = "Waffen der Dämmerwache",
				fr = "Armement de la Garde crépusculaire",
				it = "Armi della Guardia del Vespro",
				pt = "Armamento da Vigia Crepuscular",
				ru = "Оружие Сумеречной стражи",
			},
		},
	
		[251323] = {
			readable = "Cultivated Manabloom",
			model = 1352489,
			text = {
				en = "Cultivated Manabloom",
				es = "Flor de maná cultivada",
				de = "Kultivierte Manablüte",
				fr = "Fleur de mana cultivée",
				it = "Boccioli di Mana Coltivati",
				pt = "Floramana Cultivada",
				ru = "Культивированный манацвет",
				ko = "배양된 마나꽃",
			},
		},
	
		[251324] = {
			readable = "Conspicuous Sand Pile",
			model = 1282165,
			text = {
				en = "Conspicuous Sand Pile",
				es = "Montón de arena llamativo",
				de = "Auffälliger Sandhaufen",
				fr = "Tas de sable voyant",
				it = "Cumulo di Sabbia in Rilievo",
				pt = "Pilha de Areia Evidente",
				ru = "Подозрительная кучка песка",
				ko = "수상한 모래 더미",
			},
		},
	
		[251329] = {
			readable = "Conspicuous Dirt Pile",
			model = 189528,
			text = {
				en = "Conspicuous Dirt Pile",
				es = "Montón de tierra llamativo",
				de = "Auffälliger Dreckhaufen",
				fr = "Tas de poussière voyant",
				it = "Cumulo di Terra in Rilievo",
				pt = "Pilha de Sujeira Evidente",
				ru = "Подозрительная куча земли",
				ko = "수상한 흙더미",
			},
		},
	
		[251330] = {
			readable = "Doodad_7sr_suramar_nightwellfx004",
			model = 1378259,
			text = {
				en = "Doodad_7sr_suramar_nightwellfx004",
				cn = "占位符",
			},
		},
	
		[251334] = {
			readable = "Conspicuous Sand Pile",
			model = 1282165,
			text = {
				en = "Conspicuous Sand Pile",
				es = "Montón de arena llamativo",
				de = "Auffälliger Sandhaufen",
				fr = "Tas de sable voyant",
				it = "Cumulo di Sabbia in Rilievo",
				pt = "Pilha de Areia Evidente",
				ru = "Подозрительная кучка песка",
				ko = "수상한 모래 더미",
			},
		},
	
		[251336] = {
			readable = "Gravestone",
			model = 364632,
			text = {
				en = "Gravestone",
				es = "Lápida",
				de = "Grabstein",
				fr = "Pierre tombale",
				it = "Lapide",
				pt = "Lápide",
				ru = "Могильный камень",
				cn = "墓碑",
			},
		},
	
		[251337] = {
			readable = "Barrel of Odd Smelling Brew",
			model = 531100,
			text = {
				en = "Barrel of Odd Smelling Brew",
				es = "Barril de brebaje de olor extraño",
				de = "Fass mit merkwürdig riechendem Gebräu",
				fr = "Tonneau de bière au fumet douteux",
				it = "Barile di Birra Puzzolente",
				pt = "Barril de Cerveja com Cheiro Estranho",
				ru = "Бочонок странно пахнущего пойла",
				ko = "이상한 냄새가 나는 술이 든 통",
			},
		},
	
		[251340] = {
			readable = "Gravestone",
			model = 364642,
			text = {
				en = "Gravestone",
				es = "Lápida",
				de = "Grabstein",
				fr = "Pierre tombale",
				it = "Lapide",
				pt = "Lápide",
				ru = "Могильный камень",
				cn = "墓碑",
			},
		},
	
		[251341] = {
			readable = "Gravestone",
			model = 364640,
			text = {
				en = "Gravestone",
				es = "Lápida",
				de = "Grabstein",
				fr = "Pierre tombale",
				it = "Lapide",
				pt = "Lápide",
				ru = "Могильный камень",
				cn = "墓碑",
			},
		},
	
		[251346] = {
			readable = "Memorial Plaque",
			model = 204142,
			text = {
				en = "Memorial Plaque",
				es = "Placa conmemorativa",
				de = "Gedenkplakette",
				fr = "Plaque du souvenir",
				it = "Placca Commemorativa",
				pt = "Placa do Memorial",
				ru = "Мемориальная табличка",
				cn = "纪念铭牌",
			},
		},
	
		[251348] = {
			readable = "Fel Crystal",
			model = 605726,
			text = {
				en = "Fel Crystal",
				es = "Cristal vil",
				de = "Teufelskristall",
				fr = "Gangrecristal",
				it = "Vilcristallo",
				pt = "Cristal Vil",
				ru = "Кристалл Скверны",
				ko = "지옥 수정",
				cn = "邪能水晶",
			},
		},
	
		[251352] = {
			readable = "Steak and Potatoes",
			model = 461266,
			text = {
				en = "Steak and Potatoes",
				es = "Filete con patatas",
				de = "Steak und Kartoffeln",
				fr = "Steak et patates",
				it = "Bistecca e Patate",
				pt = "Carne e Batata",
				ru = "Мясо с картошкой",
				ko = "스테이크와 감자",
				cn = "牛排土豆大餐",
			},
		},
	
		[251353] = {
			readable = "Rack of Ribs",
			model = 244185,
			text = {
				en = "Rack of Ribs",
				es = "Costillar",
				de = "Rippchen",
				fr = "Plat de côtelettes",
				it = "Carré di Costine",
				pt = "Costelas",
				ru = "Ребрышки",
				ko = "통갈비",
				cn = "肋排大餐",
			},
		},
	
		[251354] = {
			readable = "Wriggling Cocoon",
			model = 123285,
			text = {
				en = "Wriggling Cocoon",
				es = "Crisálida sinuosa",
				de = "Zappelnder Kokon",
				fr = "Cocon frétillant",
				it = "Bozzolo Scalpitante",
				pt = "Casulo Revolvente",
				ru = "Подрагивающий кокон",
				ko = "꿈틀거리는 고치",
			},
		},
	
		[251355] = {
			readable = "Damaged Diving Helmet",
			model = 311821,
			text = {
				en = "Damaged Diving Helmet",
				es = "Escafandra dañada",
				de = "Beschädigter Taucherhelm",
				fr = "Casque de plongée endommagé",
				pt = "Capacete de Mergulho Danificado",
				ru = "Поврежденный шлем для подводного плавания",
				ko = "손상된 잠수모",
				cn = "损坏的潜水头盔",
			},
		},
	
		[251356] = {
			readable = "Captured Fish",
			model = 310482,
			text = {
				en = "Captured Fish",
				es = "Pez capturado",
				de = "Gefangener Fisch",
				fr = "Poisson capturé",
				pt = "Peixe Capturado",
				ru = "Пойманная рыба",
			},
		},
	
		[251386] = {
			readable = "Captured Fish",
			model = 310482,
			text = {
				en = "Captured Fish",
				es = "Pez capturado",
				de = "Gefangener Fisch",
				fr = "Poisson capturé",
				it = "Pesce Catturato",
				pt = "Peixe Capturado",
				ru = "Пойманная рыба",
			},
		},
	
		[251387] = {
			readable = "Captured Fish",
			model = 310482,
			text = {
				en = "Captured Fish",
				es = "Pez capturado",
				de = "Gefangener Fisch",
				fr = "Poisson capturé",
				it = "Pesce Catturato",
				pt = "Peixe Capturado",
				ru = "Пойманная рыба",
			},
		},
	
		[251388] = {
			readable = "Captured Fish",
			model = 310482,
			text = {
				en = "Captured Fish",
				de = "Gefangener Fisch",
				fr = "Poisson capturé",
				it = "Pesce Catturato",
				pt = "Peixe Capturado",
				ru = "Пойманная рыба",
			},
		},
	
		[251389] = {
			readable = "Captured Fish",
			model = 310482,
			text = {
				en = "Captured Fish",
				es = "Pez capturado",
				de = "Gefangener Fisch",
				fr = "Poisson capturé",
				it = "Pesce Catturato",
				pt = "Peixe Capturado",
				ru = "Пойманная рыба",
			},
		},
	
		[251390] = {
			readable = "Captured Fish",
			model = 310482,
			text = {
				en = "Captured Fish",
				es = "Pez capturado",
				de = "Gefangener Fisch",
				fr = "Poisson capturé",
				it = "Pesce Catturato",
				pt = "Peixe Capturado",
				ru = "Пойманная рыба",
			},
		},
	
		[251411] = {
			readable = "Thistlefur Home",
			model = 1258915,
			text = {
				en = "Thistlefur Home",
				es = "Hogar Piel de Cardo",
				de = "Distelfellheim",
				fr = "Maison crin-de-chardon",
				it = "Casa dei Mantocardo",
				pt = "Lar Pelocardo",
				ru = "Дом Колючего Меха",
				ko = "엉겅퀴가죽 집",
				cn = "蓟皮之家",
			},
		},
	
		[251412] = {
			readable = "Ritual Stone",
			model = 1139506,
			text = {
				en = "Ritual Stone",
				es = "Piedra ritual",
				de = "Ritualstein",
				fr = "Pierre rituelle",
				it = "Pietra Rituale",
				pt = "Pedra Ritualística",
				ru = "Ритуальный камень",
				ko = "의식용 돌",
				cn = "仪式石",
			},
		},
	
		[251413] = {
			readable = "Ritual Stone",
			model = 1139506,
			text = {
				en = "Ritual Stone",
				es = "Piedra ritual",
				de = "Ritualstein",
				fr = "Pierre rituelle",
				it = "Pietra Rituale",
				pt = "Pedra Ritualística",
				ru = "Ритуальный камень",
				ko = "의식용 돌",
				cn = "仪式石",
			},
		},
	
		[251416] = {
			readable = "Ancient Mana Chunk",
			icon = 1466166,
			model = 1108691,
			text = {
				en = "Ancient Mana Chunk",
				es = "Trozo de maná antiguo",
				de = "Uralter Manabrocken",
				fr = "Morceau de mana ancestral",
				it = "Pezzo di Mana Antico",
				pt = "Lasca de Mana Ancestral",
				ru = "Кусок древней маны",
				ko = "고대 마나 덩이",
				cn = "远古魔力碎块",
			},
		},
	
		[251419] = {
			readable = "Moist Grizzlecomb",
			model = 903358,
			text = {
				en = "Moist Grizzlecomb",
				es = "Chumbogrís húmedo",
				de = "Feuchter Graukamm",
				fr = "Grisitchi tendre",
				it = "Crestabrada Umida",
				pt = "Cinzilo Suculento",
				ru = "Сочный кактус",
			},
		},
	
		[251422] = {
			readable = "Sack of Roasted Grain",
			model = 533077,
			text = {
				en = "Sack of Roasted Grain",
				es = "Saco de grano tostado",
				de = "Sack geröstetes Getreide",
				fr = "Sac de céréales grillées",
				it = "Sacco di Grano Tostato",
				pt = "Saco de Grãos Tostados",
				ru = "Мешок жареного зерна",
				ko = "구운 곡물이 든 자루",
			},
		},
	
		[251424] = {
			readable = "Sack of Roasted Grain",
			model = 533077,
			text = {
				en = "Sack of Roasted Grain",
				es = "Saco de grano tostado",
				de = "Sack geröstetes Getreide",
				fr = "Sac de céréales grillées",
				it = "Sacco di Grano Tostato",
				pt = "Saco de Grãos Tostados",
				ru = "Мешок жареного зерна",
				ko = "구운 곡물이 든 자루",
			},
		},
	
		[251425] = {
			readable = "Moist Grizzlecomb",
			model = 903358,
			text = {
				en = "Moist Grizzlecomb",
				es = "Chumbogrís húmedo",
				de = "Feuchter Graukamm",
				fr = "Grisitchi tendre",
				it = "Crestabrada Umida",
				pt = "Cinzilo Suculento",
				ru = "Сочный кактус",
				cn = "潮湿的刺肉果",
			},
		},
	
		[251431] = {
			readable = "Empowered Runestones",
			model = 1355114,
			text = {
				en = "Empowered Runestones",
				es = "Piedras rúnicas potenciadas",
				de = "Mächtiger Runenstein",
				fr = "Pierres runiques surpuissantes",
				it = "Pietre Runiche Potenziate",
				pt = "Pedras Rúnicas Energizadas",
				ru = "Усиленные рунические камни",
				ko = "강화된 룬석",
				cn = "强化符文石",
			},
		},
	
		[251432] = {
			readable = "Artillery Controls",
			model = 1310272,
			text = {
				en = "Artillery Controls",
				es = "Controles de artillería",
				de = "Artilleriesteuerung",
				fr = "Commandes d’artillerie",
				it = "Controlli dell'Artiglieria",
				pt = "Controles de Artilharia",
				ru = "Артиллерийский пульт управления",
			},
		},
	
		[251434] = {
			readable = "Snarled Bramble",
			model = 202400,
			text = {
				en = "Snarled Bramble",
				es = "Zarzas enredadas",
				de = "Verworrenes Dornengestrüpp",
				fr = "Fourré de ronces emmêlées",
				it = "Rovo Ingarbugliato",
				pt = "Espinheiro Emaranhado",
				ru = "Узловатые колючки",
				ko = "옹이 진 가시덩굴",
				cn = "纠缠的荆棘",
			},
		},
	
		[251435] = {
			readable = "Kyrtos's Portal",
			model = 1122549,
			text = {
				en = "Kyrtos's Portal",
				es = "Portal de Kyrtos",
				de = "Kyrtos' Portal",
				fr = "Portail de Kyrtos",
				it = "Portale di Kyrtos",
				pt = "Portal de Kyrtos",
				ru = "Портал Киртоса",
				ko = "카이르토스의 차원문",
				cn = "凯托斯的传送门",
			},
		},
	
		[251436] = {
			readable = "Legion Portal",
			model = 1122549,
			text = {
				en = "Legion Portal",
				es = "Portal de la Legión",
				de = "Legionsportal",
				fr = "Portail de la Légion",
				it = "Portale della Legione",
				pt = "Portal da Legião",
				ru = "Портал Легиона",
				ko = "군단 차원문",
				cn = "军团传送门",
			},
		},
	
		[251438] = {
			readable = "Doodad_icecrown_elevator02",
			model = 321125,
			text = {
				en = "Doodad_icecrown_elevator02",
				cn = "占位符",
			},
		},
	
		[251448] = {
			readable = "Doodad_icecrown_elevator01",
			model = 321125,
			text = {
				en = "Doodad_icecrown_elevator01",
				cn = "占位符",
			},
		},
	
		[251452] = {
			readable = "Drink Me!",
			model = 328193,
			text = {
				en = "Drink Me!",
				es = "¡Bébeme!",
				de = "Trink mich!",
				fr = "Buvez-moi !",
				it = "Bevimi!",
				pt = "Beba-me!",
				ru = "Выпей меня!",
				cn = "喝掉我！",
			},
		},
	
		[251466] = {
			readable = "Sigil of the Frostwing",
			model = 333853,
			text = {
				en = "Sigil of the Frostwing",
				es = "Sigilo de Alaescarcha",
				de = "Siegel der Frostschwingen",
				fr = "Cachet de l’Aile de givre",
				it = "Sigillo degli Alazzurra",
				pt = "Signo de Asa Gélida",
				ru = "Печать Ледокрылых",
				cn = "霜翼魔印",
			},
		},
	
		[251467] = {
			readable = "Plague Sigil",
			model = 333854,
			text = {
				en = "Plague Sigil",
				es = "Sigilo de peste",
				de = "Seuchensiegel",
				fr = "Cachet de peste",
				it = "Sigillo della Piaga",
				pt = "Signo da Peste",
				ru = "Печать Чумы",
				cn = "天灾魔印",
			},
		},
	
		[251468] = {
			readable = "Bloodwing Sigil",
			model = 333855,
			text = {
				en = "Bloodwing Sigil",
				es = "Sigilo Alasangre",
				de = "Blutschwingensiegel",
				fr = "Cachet aile-de-sang",
				it = "Sigillo Alacremisi",
				pt = "Signo Sanguinasa",
				ru = "Печать Кровокрыла",
				cn = "血翼魔印",
			},
		},
	
		[251482] = {
			readable = "Remains of the Fallen",
			model = 342410,
			text = {
				en = "Remains of the Fallen",
				es = "Restos de los caídos",
				de = "Überreste der Gefallenen",
				fr = "Vestiges des trépassés",
				it = "Resti dei Caduti",
				pt = "Restos Mortais dos Caídos",
				ru = "Останки павших",
				ko = "망자의 유해",
				cn = "死者遗体",
			},
		},
	
		[251490] = {
			readable = "Campfire",
			model = 589102,
			text = {
				en = "Campfire",
				es = "Hoguera",
				de = "Lagerfeuer",
				fr = "Feu de camp",
				it = "Fuoco da Campo",
				pt = "Fogueira do Acampamento",
				ru = "Костер",
				ko = "모닥불",
			},
		},
	
		[251492] = {
			readable = "Purified Water",
			model = 1360809,
			text = {
				en = "Purified Water",
				es = "Agua purificada",
				de = "Geläutertes Wasser",
				fr = "Eau purifiée",
				it = "Acqua Purificata",
				pt = "Água Purificada",
				ru = "Чистая вода",
				ko = "정화된 물",
				cn = "纯净之水",
			},
		},
	
		[251493] = {
			readable = "Shadefruit",
			model = 1368687,
			text = {
				en = "Shadefruit",
				es = "Frutasombría",
				de = "Schattenfrucht",
				fr = "Ombrefruit",
				it = "Fruttombrosa",
				pt = "Pomonegro",
				ru = "Темный фрукт",
				ko = "어둠열매",
				cn = "暗影莓",
			},
		},
	
		[251494] = {
			readable = "Silver Jasmine",
			model = 1119697,
			text = {
				en = "Silver Jasmine",
				es = "Jazmín de plata",
				de = "Silberjasmin",
				fr = "Jasmin d’argent",
				it = "Gelsomino Argentato",
				pt = "Jasmim-de-prata",
				ru = "Серебристый жасмин",
				ko = "은빛 재스민",
				cn = "银色茉莉",
			},
		},
	
		[251496] = {
			readable = "Naga Weaponry",
			model = 1096620,
			text = {
				en = "Naga Weaponry",
				es = "Armamento naga",
				de = "Nagawaffen",
				fr = "Armement naga",
				it = "Armi dei Naga",
				pt = "Armamento Naga",
				ru = "Оружие наг",
				ko = "나가 무기",
				cn = "纳迦武器",
			},
		},
	
		[251499] = {
			readable = "Honeyed Infusion",
			model = 1360808,
			text = {
				en = "Honeyed Infusion",
				es = "Infusión melosa",
				de = "Honiggesüßte Infusion",
				fr = "Infusion au miel",
				it = "Infusione al Miele",
				pt = "Infusão ao Mel",
				ru = "Медовая настойка",
				ko = "꿀을 탄 혼합물",
				cn = "蜂蜜酒",
			},
		},
	
		[251501] = {
			readable = "Sack of Roasted Grain",
			model = 533077,
			text = {
				en = "Sack of Roasted Grain",
				es = "Saco de grano tostado",
				de = "Sack geröstetes Getreide",
				fr = "Sac de céréales grillées",
				it = "Sacco di Grano Tostato",
				pt = "Saco de Grãos Tostados",
				ru = "Мешок жареного зерна",
				ko = "구운 곡물이 든 자루",
			},
		},
	
		[251503] = {
			readable = "Barrel of Odd Smelling Brew",
			model = 531097,
			text = {
				en = "Barrel of Odd Smelling Brew",
				es = "Barril de brebaje de olor extraño",
				de = "Fass mit merkwürdig riechendem Gebräu",
				fr = "Tonneau de bière au fumet douteux",
				it = "Barile di Birra Puzzolente",
				pt = "Barril de Cerveja com Cheiro Estranho",
				ru = "Бочонок странно пахнущего пойла",
				ko = "이상한 냄새가 나는 술이 든 통",
			},
		},
	
		[251504] = {
			readable = "Mass Grave",
			model = 342410,
			text = {
				en = "Mass Grave",
				es = "Fosa común",
				de = "Massengrab",
				fr = "Fosse commune",
				it = "Fossa Comune",
				pt = "Tumba Coletiva",
				ru = "Братская могила",
			},
		},
	
		[251505] = {
			readable = "Pure Water Core",
			model = 590160,
			text = {
				en = "Pure Water Core",
				es = "Núcleo de agua pura",
				de = "Reiner Wasserkern",
				fr = "Noyau d’eau pure",
				it = "Nucleo d'Acqua Pura",
				pt = "Núcleo de Água Puro",
				ru = "Источник чистой воды",
				ko = "순수한 물의 핵",
			},
		},
	
		[251506] = {
			readable = "Supple Nectar",
			model = 1360809,
			text = {
				en = "Supple Nectar",
				es = "Néctar suave",
				de = "Samtiger Nektar",
				fr = "Nectar moelleux",
				it = "Nettare Tenero",
				pt = "Néctar Suave",
				ru = "Бархатистый нектар",
				ko = "부드러운 감로수",
				cn = "顺滑的美酒",
			},
		},
	
		[251507] = {
			readable = "Unctuous Draught",
			model = 1360810,
			text = {
				en = "Unctuous Draught",
				es = "Jarabe untuoso",
				de = "Cremiges Gebräu",
				fr = "Breuvage capiteux",
				it = "Bevanda Corposa",
				pt = "Fórmula Untuosa",
				ru = "Маслянистая наливка",
				ko = "미끈미끈한 액체",
				cn = "油腻的生啤",
			},
		},
	
		[251510] = {
			readable = "Bunch of Bananas",
			model = 593220,
			text = {
				en = "Bunch of Bananas",
				es = "Montón de plátanos",
				de = "Büschel Bananen",
				fr = "Régime de bananes",
				it = "Cespo di Banane",
				pt = "Cacho de Bananas",
				ru = "Связка бананов",
				ko = "바나나 뭉치",
			},
		},
	
		[251515] = {
			readable = "Light-Forged Vessel",
			model = 1255595,
			text = {
				en = "Light-Forged Vessel",
				es = "Recipiente forjado por la Luz",
				de = "Lichtgeschmiedetes Gefäß",
				fr = "Réceptacle forgé par la Lumière",
				it = "Ricettacolo Forgiato nella Luce",
				pt = "Recipiente Forjado em Luz",
				ru = "Сосуд из Света",
				ko = "빛으로 벼려낸 장치",
				cn = "光铸容器",
			},
		},
	
		[251521] = {
			readable = "Gateway to the Black Temple",
			model = 1413577,
			text = {
				en = "Gateway to the Black Temple",
				es = "Portal al Templo Oscuro",
				de = "Tor zum Schwarzen Tempel",
				fr = "Portail vers le Temple noir",
				it = "Varco per il Tempio Nero",
				pt = "Portal para o Templo Negro",
				ru = "Врата в Черный храм",
			},
		},
	
		[251552] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[251554] = {
			readable = "Training Troops",
			model = 166432,
			text = {
				en = "Training Troops",
				es = "Tropas en prácticas",
				de = "Ausbildungstrupps",
				fr = "Entraînement des troupes",
				it = "Truppe in Addestramento",
				pt = "Tropas em Treinamento",
				ru = "Тренировка отрядов",
				ko = "병력 훈련",
			},
		},
	
		[251556] = {
			readable = "Energy Vessel",
			model = 1309273,
			text = {
				en = "Energy Vessel",
				es = "Recipiente de energía",
				de = "Energiegefäß",
				fr = "Récipient d’énergie",
				it = "Vassoio per l'Energia",
				pt = "Recipiente de Energia",
				ru = "Энергетический сосуд",
				ko = "마력 그릇",
				cn = "能量容器",
			},
		},
	
		[251557] = {
			readable = "Engraved Shield",
			model = 1326777,
			text = {
				en = "Engraved Shield",
				es = "Escudo grabado",
				de = "Gravierter Schild",
				fr = "Bouclier gravé",
				it = "Scudo Inciso",
				pt = "Escudo Entalhado",
				ru = "Чеканный щит",
				ko = "문양이 새겨진 방패",
				cn = "雕饰盾牌",
			},
		},
	
		[251558] = {
			readable = "Engraved Shield",
			model = 1326777,
			text = {
				en = "Engraved Shield",
				es = "Escudo grabado",
				de = "Gravierter Schild",
				fr = "Bouclier gravé",
				it = "Scudo Inciso",
				pt = "Escudo Entalhado",
				ru = "Чеканный щит",
				ko = "문양이 새겨진 방패",
				cn = "雕饰盾牌",
			},
		},
	
		[251559] = {
			readable = "Engraved Shield",
			model = 1326777,
			text = {
				en = "Engraved Shield",
				es = "Escudo grabado",
				de = "Gravierter Schild",
				fr = "Bouclier gravé",
				it = "Scudo Inciso",
				pt = "Escudo Entalhado",
				ru = "Чеканный щит",
				ko = "문양이 새겨진 방패",
				cn = "雕饰盾牌",
			},
		},
	
		[251560] = {
			readable = "Engraved Shield",
			model = 1326777,
			text = {
				en = "Engraved Shield",
				es = "Escudo grabado",
				de = "Gravierter Schild",
				fr = "Bouclier gravé",
				it = "Scudo Inciso",
				pt = "Escudo Entalhado",
				ru = "Чеканный щит",
				ko = "문양이 새겨진 방패",
				cn = "雕饰盾牌",
			},
		},
	
		[251561] = {
			readable = "Engraved Shield",
			model = 1326777,
			text = {
				en = "Engraved Shield",
				es = "Escudo grabado",
				de = "Gravierter Schild",
				fr = "Bouclier gravé",
				it = "Scudo Inciso",
				pt = "Escudo Entalhado",
				ru = "Чеканный щит",
				ko = "문양이 새겨진 방패",
				cn = "雕饰盾牌",
			},
		},
	
		[251563] = {
			readable = "Small Ley Crystal",
			model = 392109,
			text = {
				en = "Small Ley Crystal",
				es = "Cristal Ley pequeño",
				de = "Kleiner Leykristall",
				fr = "Petit cristal tellurique",
				it = "Cristallo di Faglia Piccolo",
				pt = "Cristal do Meridiano Pequeno",
				ru = "Маленький силовой кристалл",
				ko = "작은 지맥 수정",
				cn = "小块魔网水晶",
			},
		},
	
		[251564] = {
			readable = "|cFFFFFFFFStep 4:|r Page 655",
			icon = 1505961,
			model = 305393,
			text = {
				en = "|cFFFFFFFFStep 4:|r Page 655",
				es = "|cFFFFFFFFStep 4:|r Página 655",
				de = "|cFFFFFFFFSchritt 4:|r Seite 655",
				fr = "|cFFFFFFFFÉtape 4:|r Page 655",
				it = "|cFFFFFFFFStep 4:|r Pagina 655",
				pt = "|cFFFFFFFFStep 4:|r Página 655",
				ru = "|cFFFFFFFFШаг 4:|r Страница 655",
				ko = "[Page 655]",
				cn = "|cFFFFFFFF第4步:|r 第655页",
			},
		},
	
		[251565] = {
			readable = "Unfortified Arcwine",
			model = 1360746,
			text = {
				en = "Unfortified Arcwine",
				es = "Vino de arco no fortificado",
				de = "Nicht verstärkter Arkwein",
				fr = "Arquevin non fortifié",
				it = "Arcavino Leggero",
				pt = "Vinho Arcano Não Fortificado",
				ru = "Ненасыщенное чародейское вино",
				ko = "강화하지 않은 비전주",
				cn = "稀薄的魔力酒",
			},
		},
	
		[251571] = {
			readable = "Ashilvara, Verse 1",
			model = 936411,
			text = {
				en = "Ashilvara, Verse 1",
				es = "Ashilvara, verso 1",
				de = "Ashilvara, Erste Strophe",
				fr = "Ashilvara, verset 1",
				it = "Ashilvara, Verso 1",
				pt = "Ashilvara, Verso 1",
				ru = "\"Ашильвара\", строфа 1",
				ko = "아쉴바라, 1절",
				cn = "艾希瓦拉之歌，第一节",
			},
		},
	
		[251573] = {
			readable = "Legion Orb",
			model = 1125326,
			text = {
				en = "Legion Orb",
				es = "Orbe de la Legión",
				de = "Kugel der Legion",
				fr = "Orbe de la Légion",
				it = "Globo della Legione",
				pt = "Orbe da Legião",
				ru = "Сфера Легиона",
				ko = "군단 보주",
				cn = "军团宝珠",
			},
		},
	
		[251574] = {
			readable = "Legion Orb",
			model = 1125326,
			text = {
				en = "Legion Orb",
				es = "Orbe de la Legión",
				de = "Kugel der Legion",
				fr = "Orbe de la Légion",
				it = "Globo della Legione",
				pt = "Orbe da Legião",
				ru = "Сфера Легиона",
				ko = "군단 보주",
				cn = "军团宝珠",
			},
		},
	
		[251575] = {
			readable = "Legion Orb",
			model = 1125326,
			text = {
				en = "Legion Orb",
				es = "Orbe de la Legión",
				de = "Kugel der Legion",
				fr = "Orbe de la Légion",
				it = "Globo della Legione",
				pt = "Orbe da Legião",
				ru = "Сфера Легиона",
				ko = "군단 보주",
				cn = "军团宝珠",
			},
		},
	
		[251579] = {
			readable = "Illidari Gateway",
			model = 1268729,
			text = {
				en = "Illidari Gateway",
				es = "Portal Illidari",
				de = "Illidaritor",
				fr = "Porte illidari",
				it = "Varco degli Illidari",
				pt = "Portal Illidari",
				ru = "Врата иллидари",
				ko = "일리다리 관문",
				cn = "伊利达雷传送门",
			},
		},
	
		[251598] = {
			readable = "Otherworld Portal",
			model = 1268729,
			text = {
				en = "Otherworld Portal",
				es = "Portal a otro mundo",
				de = "Außerweltliches Portal",
				fr = "Portail vers un autre monde",
				it = "Portale Ultraterreno",
				pt = "Portal para Outro Mundo",
				ru = "Портал в иной мир",
			},
		},
	
		[251605] = {
			readable = "Fu Zan, the Wanderer's Companion",
			model = 353152,
			text = {
				en = "Fu Zan, the Wanderer's Companion",
				es = "Fu Zan, el Compañero del Errante",
				de = "Fu Zan, Gefährte des Wanderers",
				fr = "Fu Zan, compagnon de l’explorateur",
				it = "Fu Zan, Compagno del Viandante",
				pt = "Fu Zan, Companheiro do Andarilho",
				ru = "Фу Цань, Спутник Странников",
				ko = "푸 잔 - 방랑자의 친구",
			},
		},
	
		[251615] = {
			readable = "Dying Tree",
			model = 1000552,
			text = {
				en = "Dying Tree",
				es = "Árbol marchito",
				de = "Sterbender Baum",
				fr = "Arbre mourant",
				it = "Albero Morente",
				pt = "Árvore Morrendo",
				ru = "Умирающее древо",
			},
		},
	
		[251626] = {
			readable = "Thousand-Year Arcwine",
			model = 1360746,
			text = {
				en = "Thousand-Year Arcwine",
				es = "Vino de arco milenario",
				de = "Tausendjähriger Arkwein",
				fr = "Arquevin millénaire",
				it = "Arcavino Millenario",
				pt = "Vinho Arcano de Mil Anos roubado",
				ru = "Тысячелетнее чародейское вино",
				ko = "천 년 묵은 비전주",
				cn = "千年魔力酒",
			},
		},
	
		[251641] = {
			readable = "Suramar Leyline Map",
			model = 1365481,
			text = {
				en = "Suramar Leyline Map",
				es = "Mapa de líneas Ley de Suramar",
				de = "Leylinienkarte von Suramar",
				fr = "Carte des lignes telluriques de Suramar",
				it = "Mappa delle Linee di Faglia di Suramar",
				pt = "Mapa de Meridianos de Suramar",
				ru = "Карта силовых линий Сурамара",
				ko = "수라마르 지맥 지도",
				cn = "苏拉玛魔网地图",
			},
		},
	
		[251642] = {
			readable = "Maelstrom Pillar",
			model = 987009,
			text = {
				en = "Maelstrom Pillar",
				es = "Pilar de La Vorágine",
				de = "Mahlstromsäule",
				fr = "Pilier du Maelström",
				it = "Pilastro del Maelstrom",
				pt = "Pilar da Voragem",
				ru = "Столп Водоворота",
				ko = "소용돌이의 근원",
			},
		},
	
		[251643] = {
			readable = "Felblaze Portal Effect",
			model = 1260627,
			text = {
				en = "Felblaze Portal Effect",
				es = "Efecto de portal Llamarada Vil",
				de = "Teufelslohenportaleffekt",
				fr = "Effet de portail du Brasier infernal",
				it = "Effetto del Portale di Vilfiamma",
				ru = "Эффект портала пламени Скверны",
				ko = "지옥화염 차원문 효과",
				cn = "邪焰传送门效果",
			},
		},
	
		[251655] = {
			readable = "Moonblade",
			model = 1118880,
			text = {
				en = "Moonblade",
				es = "Filoluna",
				de = "Mondklinge",
				fr = "Lamelune",
				it = "Lamaluna",
				pt = "Lamiluna",
				ru = "Лунный клинок",
				ko = "신월도",
			},
		},
	
		[251656] = {
			readable = "Damaged Thunderfury",
			model = 144340,
			text = {
				en = "Damaged Thunderfury",
				es = "Trueno Furioso dañado",
				de = "Beschädigter Donnerzorn",
				fr = "Lame-tonnerre endommagée",
				it = "Furiatonante Danneggiata",
				pt = "Tormentária Danificada",
				ru = "Поврежденная Громовая Ярость",
				ko = "손상된 우레폭풍",
				cn = "损坏的雷霆之怒",
			},
		},
	
		[251665] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[251666] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
			},
		},
	
		[251668] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
			},
		},
	
		[251669] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
			},
		},
	
		[251673] = {
			readable = "Portal to Dalaran",
			model = 1387278,
			text = {
				en = "Portal to Dalaran",
				es = "Portal a Dalaran",
				de = "Portal nach Dalaran",
				fr = "Portail vers Dalaran",
				it = "Portale per Dalaran",
				pt = "Portal para Dalaran",
				ru = "Портал в Даларан",
				ko = "달라란으로 통하는 차원문",
				cn = "通往达拉然的传送门",
			},
		},
	
		[251676] = {
			readable = "Portal to Dalaran",
			model = 1387273,
			text = {
				en = "Portal to Dalaran",
				es = "Portal a Dalaran",
				de = "Portal nach Dalaran",
				fr = "Portail vers Dalaran",
				it = "Portale per Dalaran",
				pt = "Portal para Dalaran",
				ru = "Портал в Даларан",
				ko = "달라란으로 통하는 차원문",
				cn = "通往达拉然的传送门",
			},
		},
	
		[251677] = {
			readable = "Portal to Dalaran",
			model = 244119,
			text = {
				en = "Portal to Dalaran",
				es = "Portal a Dalaran",
				de = "Portal nach Dalaran",
				fr = "Portail vers Dalaran",
				it = "Portale per Dalaran",
				pt = "Portal para Dalaran",
				ru = "Портал в Даларан",
				ko = "달라란으로 통하는 차원문",
				cn = "通往达拉然的传送门",
			},
		},
	
		[251681] = {
			readable = "Weathered Parchment",
			model = 196602,
			text = {
				en = "Weathered Parchment",
				es = "Papiro deteriorado",
				de = "Verwittertes Pergament",
				fr = "Parchemin abîmé",
				it = "Cartapecora Logora",
				pt = "Pergaminho Desgastado",
				ru = "Иссохший пергамент",
				ko = "비바람에 시달린 두루마리",
				cn = "老化的羊皮纸",
			},
		},
	
		[251696] = {
			readable = "Council Notice",
			model = 936419,
			text = {
				en = "Council Notice",
				es = "Notificación del consejo",
				de = "Ratsmitteilung",
				fr = "Avis du conseil",
				it = "Nota del Concilio",
				pt = "Ordem do Conselho",
				ru = "Извещение Совета",
				ko = "의회 공고문",
			},
		},
	
		[251697] = {
			readable = "Forgotten Letter",
			model = 305395,
			text = {
				en = "Forgotten Letter",
				es = "Carta olvidada",
				de = "Vergessener Brief",
				fr = "Lettre oubliée",
				it = "Lettera Dimenticata",
				pt = "Carta Abandonada",
				ru = "Забытое письмо",
				ko = "잊힌 편지",
			},
		},
	
		[251698] = {
			readable = "Logbook of Ur'dan",
			model = 985165,
			text = {
				en = "Logbook of Ur'dan",
				es = "Cuaderno de Ur'dan",
				de = "Ur'dans Logbuch",
				fr = "Registre d’Ur’dan",
				it = "Registro di Ur'dan",
				pt = "Livro de Registro de Ur'dan",
				ru = "Журнал Ур'дана",
				ko = "우르단의 장부",
			},
		},
	
		[251699] = {
			readable = "Portal to Tol Barad",
			model = 165828,
			text = {
				en = "Portal to Tol Barad",
				es = "Portal a Tol Barad",
				de = "Portal nach Tol Barad",
				fr = "Portail vers Tol Barad",
				it = "Portale per Tol Barad",
				pt = "Portal para Tol Barad",
				ru = "Портал на Тол Барад",
				ko = "톨 바라드로 통하는 차원문",
			},
		},
	
		[251706] = {
			readable = "Crooked Tree Cauldron",
			model = 984595,
			text = {
				en = "Crooked Tree Cauldron",
				es = "Caldera del árbol retorcido",
				de = "Kessel des verwachsenen Baums",
				fr = "Chaudron de l’arbre Tordu",
				it = "Calderone dell'Albero Corrotto",
				pt = "Caldeirão da Árvore Contorcida",
				ru = "Котел Узловатого Древа",
				ko = "뒤틀린 나무 가마솥",
				cn = "扭曲之树大锅",
			},
		},
	
		[251713] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[251714] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[251716] = {
			readable = "Glimmering Treasure Chest",
			model = 1402270,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[251719] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[251720] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[251723] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[251724] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
			},
		},
	
		[251725] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[251726] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[251727] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
			},
		},
	
		[251728] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[251730] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[251732] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
			},
		},
	
		[251737] = {
			readable = "Treasure Chest",
			model = 1402264,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[251738] = {
			readable = "Treasure Chest",
			model = 1402264,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[251739] = {
			readable = "Glimmering Treasure Chest",
			model = 1349621,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[251740] = {
			readable = "Glimmering Treasure Chest",
			model = 1349621,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
			},
		},
	
		[251741] = {
			readable = "Glimmering Treasure Chest",
			model = 1349621,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[251742] = {
			readable = "Glimmering Treasure Chest",
			model = 1349621,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[251743] = {
			readable = "Glimmering Treasure Chest",
			model = 1349621,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[251744] = {
			readable = "Glimmering Treasure Chest",
			model = 1349621,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[251745] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
			},
		},
	
		[251746] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[251747] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
			},
		},
	
		[251748] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
			},
		},
	
		[251749] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Cofre del tesoro",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
			},
		},
	
		[251751] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
			},
		},
	
		[251753] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
			},
		},
	
		[251754] = {
			readable = "Glimmering Treasure Chest",
			model = 1349622,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[251755] = {
			readable = "Glimmering Treasure Chest",
			model = 1349622,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
			},
		},
	
		[251756] = {
			readable = "Glimmering Treasure Chest",
			model = 1349622,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
			},
		},
	
		[251757] = {
			readable = "Glimmering Treasure Chest",
			model = 1349622,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
			},
		},
	
		[251758] = {
			readable = "Glimmering Treasure Chest",
			model = 1349622,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
			},
		},
	
		[251759] = {
			readable = "Glimmering Treasure Chest",
			model = 1349622,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
			},
		},
	
		[251760] = {
			readable = "Portal to Highmountain",
			model = 197054,
			text = {
				en = "Portal to Highmountain",
				es = "Portal a Monte Alto",
				de = "Portal zum Hochberg",
				fr = "Portail vers Haut-Roc",
				it = "Portale per Alto Monte",
				pt = "Portal para Alta Montanha",
				ru = "Портал в Крутогорье",
				cn = "通往至高岭的传送门",
			},
		},
	
		[251761] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[251762] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[251763] = {
			readable = "Legion Portal",
			model = 1122549,
			text = {
				en = "Legion Portal",
				es = "Portal de la Legión",
				de = "Legionsportal",
				fr = "Portail de la Légion",
				it = "Portale della Legione",
				pt = "Portal da Legião",
				ru = "Портал Легиона",
			},
		},
	
		[251764] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[251766] = {
			readable = "Bloodflower",
			model = 1357456,
			text = {
				en = "Bloodflower",
				es = "Flor de sangre",
				de = "Blutblume",
				fr = "Fleur de sang",
				it = "Fiorsangue",
				pt = "Flor-de-sangue",
				ru = "Кровоцвет",
				ko = "피꽃",
				cn = "赤血花",
			},
		},
	
		[251771] = {
			readable = "Fel Engine Injector",
			model = 1125329,
			text = {
				en = "Fel Engine Injector",
				es = "Inyector de motor vil",
				de = "Teufelsmotoreinspritzdüse",
				fr = "Injecteur de moteur gangrené",
				it = "Viliniettore",
				pt = "Injetor de Motor Vil",
				ru = "Система впрыска двигателя Скверны",
				ko = "지옥 엔진 주입기",
				cn = "邪能引擎注射器",
			},
		},
	
		[251772] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[251774] = {
			readable = "Soul Configuration Matrix",
			model = 1311405,
			text = {
				en = "Soul Configuration Matrix",
				es = "Matriz de configuración de almas",
				de = "Seelenkonfigurationsmatrix",
				fr = "Matrice de configuration spirituelle",
				it = "Matrice di Configurazione dell'Anima",
				pt = "Matriz de Configuração de Alma",
				ru = "Матрица настройки душ",
				ko = "영혼 설정 장치",
				cn = "灵魂构造矩阵",
			},
		},
	
		[251776] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[251780] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[251782] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[251784] = {
			readable = "Vile Spirit Converter",
			model = 1310274,
			text = {
				en = "Vile Spirit Converter",
				es = "Transformador de espíritus malvados",
				de = "Umwandler für widerwärtige Geister",
				fr = "Convertisseur d’esprits vils",
				it = "Convertitore di Spirito Vile",
				pt = "Conversor de Espírito Torpe",
				ru = "Преобразователь злых духов",
				ko = "사악한 영혼 변환기",
				cn = "邪魂转化器",
			},
		},
	
		[251792] = {
			readable = "Small Treasure Chest",
			model = 1402264,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[251795] = {
			readable = "Summoning Ascendant",
			model = 166432,
			text = {
				en = "Summoning Ascendant",
				es = "Invocar ascendiente",
				de = "Beschwört Aszendenten",
				fr = "Invocation d’ascendant",
				it = "Evocazione Asceso",
				pt = "Evocando Ascendente",
				ru = "Призыв перерожденного",
				ko = "승천자 소환",
			},
		},
	
		[251820] = {
			readable = "Treasure Chest",
			model = 1314905,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[251840] = {
			readable = "Chains",
			model = 875607,
			text = {
				en = "Chains",
				es = "Cadenas",
				de = "Ketten",
				fr = "Chaînes",
				it = "Chanis",
				pt = "Correntes",
				ru = "Цепи",
				ko = "사슬",
				cn = "锁链",
			},
		},
	
		[251851] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[251853] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[251854] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[251856] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[251857] = {
			readable = "Treasure Chest",
			model = 1402264,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[251858] = {
			readable = "Mysterious Pearl",
			model = 338524,
			text = {
				en = "Mysterious Pearl",
				es = "Perla misteriosa",
				de = "Mysteriöse Perle",
				fr = "Perle mystérieuse",
				it = "Perla Misteriosa",
				pt = "Pérola Misteriosa",
				ru = "Таинственная жемчужина",
			},
		},
	
		[251870] = {
			readable = "The Sixtriggers' Premium Stash",
			model = 446673,
			text = {
				en = "The Sixtriggers' Premium Stash",
				es = "Alijo premium de Seis Gatillos",
				de = "Truhe mit dem wertvollsten Raubgut der Sechszünders",
				fr = "Planque fabuleuse des Six-Coups",
				it = "Scorta Preziosa di Seigrilletti",
				pt = "O Tesouro Especial de Hexatilho",
				ru = "Наилучший тайник Шестихвата",
				ko = "식스트리거 가문의 튼튼한 보관함",
			},
		},
	
		[251873] = {
			readable = "Wriggling Cocoon",
			model = 123285,
			text = {
				en = "Wriggling Cocoon",
				es = "Crisálida sinuosa",
				de = "Zappelnder Kokon",
				fr = "Cocon frétillant",
				it = "Bozzolo Scalpitante",
				pt = "Casulo Revolvente",
				ru = "Подрагивающий кокон",
				ko = "꿈틀거리는 고치",
			},
		},
	
		[251874] = {
			readable = "Wriggling Cocoon",
			model = 123285,
			text = {
				en = "Wriggling Cocoon",
				es = "Capullo sinuoso",
				de = "Zappelnder Kokon",
				fr = "Cocon frétillant",
				pt = "Casulo Revolvente",
				ru = "Подрагивающий кокон",
				ko = "꿈틀거리는 고치",
			},
		},
	
		[251878] = {
			readable = "Twinblades of the Deceiver",
			model = 353152,
			text = {
				en = "Twinblades of the Deceiver",
				es = "Hojas Gemelas del Impostor",
				de = "Zwillingsklingen des Betrügers",
				fr = "Lames jumelles du Trompeur",
				it = "Lame Gemelle dell'Ingannatore",
				pt = "Lâminas Gêmeas do Enganador",
				ru = "Парные клинки Искусителя",
				ko = "기만자의 쌍날검",
				cn = "欺诈者的双刃",
			},
		},
	
		[251879] = {
			readable = "Prison Manifest",
			model = 985165,
			text = {
				en = "Prison Manifest",
				es = "Manifiesto de prisión",
				de = "Gefängnisliste",
				fr = "Manifeste de la prison",
				it = "Registro della Prigione",
				pt = "Manifesto da Prisão",
				ru = "Список узников",
				ko = "감옥 명부",
			},
		},
	
		[251882] = {
			readable = "Fragment of Frostmourne",
			model = 1355058,
			text = {
				en = "Fragment of Frostmourne",
				es = "Fragmento de la Agonía de Escarcha",
				de = "Frostgramfragment",
				fr = "Fragment de Deuillegivre",
				it = "Frammento di Gelidanima",
				pt = "Fragmento de Gélido Lamento",
				ru = "Обломок Ледяной Скорби",
				cn = "霜之哀伤碎片",
			},
		},
	
		[251884] = {
			readable = "Fragment of Frostmourne",
			model = 1355057,
			text = {
				en = "Fragment of Frostmourne",
				es = "Fragmento de la Agonía de Escarcha",
				de = "Frostgramfragment",
				fr = "Fragment de Deuillegivre",
				it = "Frammento di Gelidanima",
				pt = "Fragmento de Gélido Lamento",
				ru = "Обломок Ледяной Скорби",
				cn = "霜之哀伤碎片",
			},
		},
	
		[251885] = {
			readable = "Fragment of Frostmourne",
			model = 1355056,
			text = {
				en = "Fragment of Frostmourne",
				es = "Fragmento de la Agonía de Escarcha",
				de = "Frostgramfragment",
				fr = "Fragment de Deuillegivre",
				it = "Frammento di Gelidanima",
				pt = "Fragmento de Gélido Lamento",
				ru = "Обломок Ледяной Скорби",
				cn = "霜之哀伤碎片",
			},
		},
	
		[251886] = {
			readable = "Fragment of Frostmourne",
			model = 1355055,
			text = {
				en = "Fragment of Frostmourne",
				es = "Fragmento de la Agonía de Escarcha",
				de = "Frostgramfragment",
				fr = "Fragment de Deuillegivre",
				it = "Frammento di Gelidanima",
				pt = "Fragmento de Gélido Lamento",
				ru = "Обломок Ледяной Скорби",
				cn = "霜之哀伤碎片",
			},
		},
	
		[251946] = {
			readable = "Moist Grizzleberries",
			model = 875390,
			text = {
				en = "Moist Grizzleberries",
				es = "Bayas grisáceas húmedas",
				de = "Saftige Grizzlybeeren",
				fr = "Griseilles juteuses",
				it = "Bacchebrade Umide",
				pt = "Frutagris Úmidas",
				ru = "Мокрая ворчуника",
				ko = "회색숲 물렁열매",
				cn = "潮湿的灰莓",
			},
		},
	
		[251949] = {
			readable = "Legion Portal",
			model = 1268729,
			text = {
				en = "Legion Portal",
				es = "Portal de la Legión",
				de = "Legionsportal",
				fr = "Portail de la Légion",
				it = "Portale della Legione",
				pt = "Portal da Legião",
				ru = "Портал Легиона",
				ko = "군단 차원문",
				cn = "军团传送门",
			},
		},
	
		[251950] = {
			readable = "Albino Barracuda School",
			model = 219406,
			text = {
				en = "Albino Barracuda School",
				es = "Banco de barracudas albinas",
				de = "Ein Schwarm Albinobarrakudas",
				fr = "Banc de barracudas albinos",
				it = "Banco di Barracuda Albini",
				ru = "Косяк белой барракуды",
			},
		},
	
		[251951] = {
			readable = "Heyman's Journal",
			model = 949621,
			text = {
				en = "Heyman's Journal",
				es = "Diario de Heyman",
				de = "Heymans Tagebuch",
				fr = "Journal de Heyman",
				it = "Diario di Heyman",
				ru = "Дневник Хеймана",
			},
		},
	
		[251953] = {
			readable = "Glimmering Treasure Chest",
			model = 1349622,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[251954] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[251959] = {
			readable = "Ancient Elven Chest",
			model = 196976,
			text = {
				en = "Ancient Elven Chest",
				es = "Cofre élfico antiguo",
				de = "Uralte Elfentruhe",
				fr = "Coffre elfique ancien",
				it = "Antica Corazza Elfica",
				pt = "Baú Élfico Antigo",
				ru = "Древний эльфийский сундук",
				ko = "고대 엘프 궤짝",
				cn = "上古精灵宝箱",
			},
		},
	
		[251960] = {
			readable = "The Raven's Eye Tablet",
			model = 1355115,
			text = {
				en = "The Raven's Eye Tablet",
				es = "Tablilla del ojo del cuervo",
				de = "Rabenaugentafel",
				fr = "Tablette de l’œil du corbeau",
				it = "Tavoletta dell'Occhio del Corvo",
				pt = "Tabuleta do Olho do Corvo",
				ru = "Скрижаль с легендой об Оке Ворона",
				ko = "까마귀의 눈 석판",
				cn = "渡鸦之眼石板",
			},
		},
	
		[251961] = {
			readable = "Portal to the Crumbling Depths",
			model = 418797,
			text = {
				en = "Portal to the Crumbling Depths",
				es = "Portal a Profundidades Desmoronadas",
				de = "Portal zu den Bruchtiefen",
				fr = "Portail vers les profondeurs Désagrégées",
				it = "Portale per le Profondità Disgregate",
				pt = "Portal para os Abismos Esfacelados",
				ru = "Портал в Гремящие глубины",
			},
		},
	
		[251966] = {
			readable = "Smuggled Weaponry",
			model = 166432,
			text = {
				en = "Smuggled Weaponry",
				es = "Armamento de contrabando",
				de = "Geschmuggelte Waffen",
				fr = "Armement de contrebande",
				it = "Armi di Contrabbando",
				pt = "Armamento Contrabandeado",
				ru = "Контрабандное оружие",
				ko = "밀수된 무기",
				cn = "走私来的武器",
			},
		},
	
		[251969] = {
			readable = "Dying Tree",
			model = 1000552,
			text = {
				en = "Dying Tree",
				es = "Árbol marchito",
				de = "Sterbender Baum",
				fr = "Arbre mourant",
				it = "Albero Morente",
				pt = "Árvore Morrendo",
				ru = "Умирающее древо",
			},
		},
	
		[251980] = {
			readable = "Nightmare Iris",
			model = 1346456,
			text = {
				en = "Nightmare Iris",
				es = "Iris de la Pesadilla",
				de = "Alptraumiris",
				fr = "Iris du Cauchemar",
				it = "Iride dell'Incubo",
				pt = "Iris do Pesadelo",
				ru = "Кошмарный портал",
				ko = "악몽 눈동자",
				cn = "梦魇之虹",
			},
		},
	
		[251988] = {
			readable = "Nighthold Focusing Statue",
			model = 1399903,
			text = {
				en = "Nighthold Focusing Statue",
				es = "Estatua de enfoque del Bastión Nocturno",
				de = "Fokusstatue der Nachtfestung",
				fr = "Statue de focalisation du palais Sacrenuit",
				it = "Statua del Focus della Rocca della Notte",
				pt = "Estátua de Concentração do Baluarte da Noite",
				ru = "Статуя сосредоточения Цитадели Ночи",
				ko = "밤의 요새 집중의 석상",
				cn = "暗夜要塞聚焦雕像",
			},
		},
	
		[251991] = {
			readable = "The Aegis of Aggramar",
			icon = 880012,
			model = 1361813,
			text = {
				en = "The Aegis of Aggramar",
				es = "Égida de Aggramar",
				de = "Die Aegis von Aggramar",
				fr = "Égide d’Aggramar",
				it = "Egida di Aggramar",
				pt = "A Égide de Aggramar",
				ru = "Эгида Агграмара",
				ko = "아그라마르의 아이기스",
				cn = "阿格拉玛之盾",
			},
		},
	
		[251992] = {
			readable = "The Aegis of Aggramar",
			model = 1361813,
			text = {
				en = "The Aegis of Aggramar",
				es = "Égida de Aggramar",
				de = "Die Aegis von Aggramar",
				fr = "Égide d’Aggramar",
				it = "Egida di Aggramar",
				pt = "A Égide de Aggramar",
				ru = "Эгида Агграмара",
				ko = "아그라마르의 아이기스",
				cn = "阿格拉玛之盾",
			},
		},
	
		[251993] = {
			readable = "Requisitioned Armaments",
			model = 166432,
			text = {
				en = "Requisitioned Armaments",
				es = "Armamento requisado",
				de = "Requirierte Waffen",
				fr = "Armement réquisitionné",
				it = "Armamenti Requisiti",
				pt = "Armamentos Requisitados",
				ru = "Заказанное вооружение",
				ko = "징발된 무장",
			},
		},
	
		[251995] = {
			readable = "Portal",
			model = 1413876,
			text = {
				en = "Portal",
				fr = "Portail",
				it = "Portale",
				ru = "Портал",
				ko = "차원문",
				cn = "传送门",
			},
		},
	
		[251996] = {
			readable = "Requisitioned Armaments",
			model = 166432,
			text = {
				en = "Requisitioned Armaments",
				es = "Armamento requisado",
				de = "Requirierte Waffen",
				fr = "Armement réquisitionné",
				it = "Armamenti Requisiti",
				pt = "Armamentos Requisitados",
				ru = "Заказанное вооружение",
				ko = "징발된 무장",
				cn = "征用的军备",
			},
		},
	
		[251997] = {
			readable = "Portal",
			model = 1413876,
			text = {
				en = "Portal",
				fr = "Portail",
				it = "Portale",
				ru = "Портал",
				ko = "차원문",
				cn = "传送门",
			},
		},
})
do ObjectDB[objectID] = objectData; end
