local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	
		[382001] = {
			readable = "Deactivated Signal Transmitter",
			model = 4627222,
			text = {
				en = "Deactivated Signal Transmitter",
				es = "Transmisor desactivado",
				de = "Deaktivierter Signaltransmitter",
				fr = "Transmetteur de signaux désactivé",
				it = "Trasmettitore di segnale disattivato",
				pt = "Transmissor de Sinal Desativado",
				ru = "Отключенный передатчик",
			},
		},
	
		[382003] = {
			readable = "Deactivated Signal Transmitter",
			model = 4627222,
			text = {
				en = "Deactivated Signal Transmitter",
				es = "Transmisor desactivado",
				de = "Deaktivierter Signaltransmitter",
				fr = "Transmetteur de signaux désactivé",
				pt = "Transmissor de Sinal Desativado",
				ru = "Отключенный передатчик",
				ko = "비활성화된 신호 송신기",
			},
		},
	
		[382029] = {
			readable = "Disturbed Dirt",
			model = 4539376,
			text = {
				en = "Disturbed Dirt",
				es = "Tierra removida",
				de = "Bewegte Erde",
				fr = "Terre retournée",
				it = "Terra Smossa",
				pt = "Poeira Revolvida",
				ru = "Потревоженная почва",
				ko = "흐트러진 흙",
				cn = "翻动过的泥土",
			},
		},
	
		[382030] = {
			readable = "Nectar Filled Panthis",
			model = 3720023,
			text = {
				en = "Nectar Filled Panthis",
				es = "Panthis llena de néctar",
				de = "Nektargefüllter Panthis",
				fr = "Panthis remplie de nectar",
				it = "Pantis Pieno di Nettare",
				pt = "Panthis Cheio de Néctar",
				ru = "Полный нектара пантис",
				ko = "감로로 가득한 판티스",
				cn = "装满花蜜的潘西斯花",
			},
		},
	
		[382031] = {
			readable = "Oily Dropcap",
			model = 3802901,
			text = {
				en = "Oily Dropcap",
				es = "Topetín aceitoso",
				de = "Ölige Tropfkappe",
				fr = "Amanite huileuse",
				it = "Gorcino Oleoso",
				pt = "Chapelão Oleoso",
				ru = "Маслянистый вензель",
				ko = "기름진 벙거지 버섯",
				cn = "油腻的垂帽菇",
			},
		},
	
		[382032] = {
			readable = "Flowering Inferno Pod",
			model = 3858163,
			text = {
				en = "Flowering Inferno Pod",
				es = "Vaina de inferno en floración",
				de = "Blühende Infernokapsel",
				fr = "Cosse d’inferno en fleur",
				it = "Capsula Infernale Fiorente",
				pt = "Casulo-do-inferno em Flor",
				ru = "Цветущий инфернальный стручок",
				ko = "피어나는 불지옥 깍지",
				cn = "开花的地狱火种荚",
			},
		},
	
		[382033] = {
			readable = "Djaradin Supply Jar",
			model = 4181201,
			text = {
				en = "Djaradin Supply Jar",
				es = "Tarro de suministros djaradin",
				de = "Vorratsglas der Djaradin",
				fr = "Bocal de réserves djaradines",
				it = "Giara dei Djaradin",
				pt = "Jarro de Suprimentos Djaradin",
				ru = "Кувшин с джарадинскими припасами",
				ko = "자라딘 보급품 단지",
				cn = "贾拉丁补给罐",
			},
		},
	
		[382034] = {
			readable = "Weapon Rack",
			model = 4216978,
			text = {
				en = "Weapon Rack",
				es = "Expositor de armas",
				de = "Waffenständer",
				fr = "Râtelier d’armes",
				it = "Rastrelliera delle Armi",
				pt = "Cavalete de Armas",
				ru = "Оружейная стойка",
			},
		},
	
		[382035] = {
			readable = "Weapon Rack",
			model = 4216979,
			text = {
				en = "Weapon Rack",
				es = "Expositor de armas",
				de = "Waffenständer",
				fr = "Râtelier d’armes",
				it = "Rastrelliera delle Armi",
				pt = "Cavalete de Armas",
				ru = "Оружейная стойка",
			},
		},
	
		[382037] = {
			readable = "Primalist Brazier",
			model = 4558021,
			text = {
				en = "Primalist Brazier",
				es = "Blandón de los Primalistas",
				de = "Primalistenkohlenpfanne",
				fr = "Brasero des Primalistes",
				it = "Braciere del Primalista",
				pt = "Braseiro Primevista",
				ru = "Жаровня воинов стихий",
				ko = "원시술사 화로",
				cn = "拜荒者火盆",
			},
		},
	
		[382038] = {
			readable = "Primalist Brazier",
			model = 4558021,
			text = {
				en = "Primalist Brazier",
				es = "Blandón de los Primalistas",
				de = "Primalistenkohlenpfanne",
				fr = "Brasero des Primalistes",
				it = "Braciere del Primalista",
				pt = "Braseiro Primevista",
				ru = "Жаровня воинов стихий",
				ko = "원시술사 화로",
			},
		},
	
		[382039] = {
			readable = "Primalist Brazier",
			model = 4558021,
			text = {
				en = "Primalist Brazier",
				es = "Blandón de los Primalistas",
				de = "Primalistenkohlenpfanne",
				fr = "Brasero des Primalistes",
				it = "Braciere del Primalista",
				pt = "Braseiro Primevista",
				ru = "Жаровня воинов стихий",
				ko = "원시술사 화로",
				cn = "拜荒者火盆",
			},
		},
	
		[382040] = {
			readable = "Primalist Brazier",
			model = 4558021,
			text = {
				en = "Primalist Brazier",
				es = "Blandón de los Primalistas",
				de = "Primalistenkohlenpfanne",
				fr = "Brasero des Primalistes",
				it = "Braciere del Primalista",
				pt = "Braseiro Primevista",
				ru = "Жаровня воинов стихий",
				ko = "원시술사 화로",
				cn = "拜荒者火盆",
			},
		},
	
		[382041] = {
			readable = "Primalist Brazier",
			model = 4558021,
			text = {
				en = "Primalist Brazier",
				es = "Blandón de los Primalistas",
				de = "Primalistenkohlenpfanne",
				fr = "Brasero des Primalistes",
				it = "Braciere del Primalista",
				pt = "Braseiro Primevista",
				ru = "Жаровня воинов стихий",
				ko = "원시술사 화로",
				cn = "拜荒者火盆",
			},
		},
	
		[382042] = {
			readable = "Primalist Brazier",
			model = 4558021,
			text = {
				en = "Primalist Brazier",
				es = "Blandón de los Primalistas",
				de = "Primalistenkohlenpfanne",
				fr = "Brasero des Primalistes",
				it = "Braciere del Primalista",
				pt = "Braseiro Primevista",
				ru = "Жаровня воинов стихий",
				ko = "원시술사 화로",
				cn = "拜荒者火盆",
			},
		},
	
		[382043] = {
			readable = "Medical Supplies",
			model = 4577059,
			text = {
				en = "Medical Supplies",
				es = "Suministros médicos",
				de = "Medizinische Vorräte",
				fr = "Fournitures médicales",
				it = "Rifornimenti Medici",
				pt = "Suprimentos Médicos",
				ru = "Медикаменты",
				ko = "의약품",
				cn = "医疗物资",
			},
		},
	
		[382047] = {
			readable = "Spear Rack",
			model = 3936835,
			text = {
				en = "Spear Rack",
				es = "Expositor de lanzas",
				de = "Speergestell",
				fr = "Râtelier de lances",
				it = "Rastrelliera di Lance",
				pt = "Cavalete de Lanças",
				ru = "Стойка с копьями",
			},
		},
	
		[382050] = {
			readable = "Shield Rack",
			model = 3936835,
			text = {
				en = "Shield Rack",
				es = "Expositor de escudos",
				de = "Schildgestell",
				fr = "Râtelier de boucliers",
				it = "Rastrelliera di Scudi",
				pt = "Cavalete de Escudo",
				ru = "Стойка для щитов",
			},
		},
	
		[382055] = {
			readable = "Ancient Book",
			model = 4298561,
			text = {
				en = "Ancient Book",
				es = "Libro antiguo",
				de = "Uraltes Buch",
				fr = "Livre ancien",
				it = "Libro Antico",
				pt = "Livro Ancestral",
				ru = "Древняя книга",
				ko = "고대의 책",
				cn = "远古之书",
			},
		},
	
		[382056] = {
			readable = "Ancient Book",
			model = 4298561,
			text = {
				en = "Ancient Book",
				es = "Libro antiguo",
				de = "Uraltes Buch",
				fr = "Livre ancien",
				it = "Libro Antico",
				pt = "Livro Ancestral",
				ru = "Древняя книга",
				ko = "고대의 책",
				cn = "远古之书",
			},
		},
	
		[382057] = {
			readable = "Ancient Book",
			model = 4298561,
			text = {
				en = "Ancient Book",
				es = "Libro antiguo",
				de = "Uraltes Buch",
				fr = "Livre ancien",
				it = "Libro Antico",
				pt = "Livro Ancestral",
				ru = "Древняя книга",
				ko = "고대의 책",
				cn = "远古之书",
			},
		},
	
		[382058] = {
			readable = "Ancient Book",
			model = 4298561,
			text = {
				en = "Ancient Book",
				es = "Libro antiguo",
				de = "Uraltes Buch",
				fr = "Livre ancien",
				it = "Libro Antico",
				pt = "Livro Ancestral",
				ru = "Древняя книга",
				ko = "고대의 책",
				cn = "远古之书",
			},
		},
	
		[382059] = {
			readable = "Digging Spot",
			model = 605598,
			text = {
				en = "Digging Spot",
				es = "Punto de excavación",
				de = "Grabungsstelle",
				fr = "Emplacement de fouille",
				it = "Punto di Scavo",
				pt = "Local de Escavação",
				ru = "Место для копания",
			},
		},
	
		[382060] = {
			readable = "Titan Chest",
			model = 4323481,
			text = {
				en = "Titan Chest",
				es = "Cofre titánico",
				de = "Titanentruhe",
				fr = "Coffre des Titans",
				it = "Cassa dei Titani",
				pt = "Baú Titânico",
				ru = "Сундук титанов",
				ko = "티탄 궤짝",
				cn = "泰坦箱子",
			},
		},
	
		[382061] = {
			readable = "Titan Urn",
			model = 4285578,
			text = {
				en = "Titan Urn",
				es = "Urna de titán",
				de = "Titanenurne",
				fr = "Urne des Titans",
				it = "Urna dei Titani",
				pt = "Urna de Titã",
				ru = "Урна титанов",
				ko = "티탄 항아리",
				cn = "泰坦瓮",
			},
		},
	
		[382062] = {
			readable = "Watcher Leg",
			model = 4532363,
			text = {
				en = "Watcher Leg",
				es = "Pierna de vigía",
				de = "Hüterbein",
				fr = "Jambe de gardien",
				it = "Gamba del Guardiano",
				pt = "Perna de Vigia",
				ru = "Нога стража",
				ko = "감시자 다리",
				cn = "看护者之腿",
			},
		},
	
		[382063] = {
			readable = "Titan Orb",
			model = 4609985,
			text = {
				en = "Titan Orb",
				es = "Orbe titánico",
				de = "Titanenkugel",
				fr = "Orbe des Titans",
				it = "Globo dei Titani",
				pt = "Orbe Titânico",
				ru = "Сфера титанов",
				ko = "티탄 보주",
				cn = "泰坦宝珠",
			},
		},
	
		[382067] = {
			readable = "Unstable Crystal",
			model = 4563732,
			text = {
				en = "Unstable Crystal",
				es = "Cristal inestable",
				de = "Instabiler Kristall",
				fr = "Cristal instable",
				it = "Cristallo Instabile",
				pt = "Cristal Instável",
				ru = "Нестабильный кристалл",
				ko = "불안정한 수정",
				cn = "不稳定的水晶",
			},
		},
	
		[382068] = {
			readable = "Barbed Tulip",
			model = 4000447,
			text = {
				en = "Barbed Tulip",
				es = "Tulipán con espinas",
				de = "Stacheltulpe",
				fr = "Tulipe acérée",
				it = "Tulipano Spinoso",
				pt = "Tulipa Farpada",
				ru = "Колючий тюльпан",
				ko = "미늘 돋친 튤립",
				cn = "倒刺郁金香",
			},
		},
	
		[382069] = {
			readable = "Overripe Lifebinder's Gift",
			model = 4191409,
			text = {
				en = "Overripe Lifebinder's Gift",
				es = "Don de la Protectora maduro",
				de = "Überreifes Geschenk der Lebensbinderin",
				fr = "Don de la Lieuse-de-Vie gâté",
				it = "Dono della Protettrice della Vita Troppo Maturo",
				pt = "Dádiva da Mãe da Vida Madura Demais",
				ru = "Переспелый дар Хранительницы Жизни",
				ko = "과숙한 생명의 어머니의 선물",
				cn = "过于成熟的生命缚誓者的礼物",
			},
		},
	
		[382070] = {
			readable = "Blocked Net Spot",
			model = 984230,
			text = {
				en = "Blocked Net Spot",
				es = "Punto de red bloqueado",
				de = "Blockierte Netzstelle",
				fr = "Emplacement de filet bloqué",
				it = "Punto Rete Bloccato",
				pt = "Local da Rede Bloqueado",
				ru = "Недоступная сеть",
				ko = "막힌 그물 지점",
				cn = "被阻塞的渔网点",
			},
		},
	
		[382071] = {
			readable = "Full Fishing Net",
			model = 984224,
			text = {
				en = "Full Fishing Net",
				es = "Red de pesca llena",
				de = "Gefülltes Fischernetz",
				fr = "Filet de pêche plein",
				it = "Rete da Pesca Piena",
				pt = "Rede de Pesca Cheia",
				ru = "Полная сеть",
				ko = "완전한 낚시 그물",
				cn = "完整的渔网",
			},
		},
	
		[382072] = {
			readable = "Full Fishing Net",
			model = 984226,
			text = {
				en = "Full Fishing Net",
				es = "Red de pesca llena",
				de = "Gefülltes Fischernetz",
				fr = "Filet de pêche plein",
				pt = "Rede de Pesca Cheia",
				ru = "Полная сеть",
				ko = "완전한 낚시 그물",
			},
		},
	
		[382074] = {
			readable = "Watcher Head",
			model = 4609989,
			text = {
				en = "Watcher Head",
				es = "Cabeza de vigía",
				de = "Hüterkopf",
				fr = "Tête de gardien",
				it = "Testa del Guardiano",
				pt = "Cabeça do Vigia",
				ru = "Голова стража",
				ko = "감시자 머리",
				cn = "看护者的头雕",
			},
		},
	
		[382075] = {
			readable = "Frozen Herb",
			model = 4208789,
			text = {
				en = "Frozen Herb",
				es = "Hierba congelada",
				de = "Gefrorenes Kraut",
				fr = "Herbe gelée",
				it = "Erba Congelata",
				pt = "Planta Congelada",
				ru = "Мерзлая трава",
				ko = "얼어붙은 약초",
				cn = "冰冷的草药",
			},
		},
	
		[382076] = {
			readable = "Titan Urn",
			model = 4285577,
			text = {
				en = "Titan Urn",
				es = "Urna de titán",
				de = "Titanenurne",
				fr = "Urne des Titans",
				it = "Urna dei Titani",
				pt = "Urna de Titã",
				ru = "Урна титанов",
				ko = "티탄 항아리",
				cn = "泰坦瓮",
			},
		},
	
		[382077] = {
			readable = "Watcher Arm",
			model = 4532362,
			text = {
				en = "Watcher Arm",
				es = "Brazo de vigía",
				de = "Hüterarm",
				fr = "Bras de gardien",
				it = "Braccio del Guardiano",
				pt = "Arma de Vigia",
				ru = "Рука стража",
				ko = "감시자 팔",
				cn = "看护者的手臂",
			},
		},
	
		[382078] = {
			readable = "Digging Spot",
			model = 605598,
			text = {
				en = "Digging Spot",
				es = "Punto de excavación",
				de = "Grabungsstelle",
				fr = "Emplacement de fouille",
				it = "Punto di Scavo",
				pt = "Local de Escavação",
				ru = "Место для копания",
			},
		},
	
		[382079] = {
			readable = "Dragonscale Expedition Flag",
			model = 4198200,
			text = {
				en = "Dragonscale Expedition Flag",
				es = "Bandera de la Expedición Dragontina",
				de = "Flagge der Drachenschuppenexpedition",
				fr = "Drapeau de l’expédition du Dracaret",
				it = "Bandiera della Spedizione delle Scaglie di Drago",
				pt = "Bandeira da Expedição Escama de Dragão",
				ru = "Флаг Драконьей экспедиции",
				ko = "용비늘 원정대 깃발",
				cn = "龙鳞探险队旗帜",
			},
		},
	
		[382082] = {
			readable = "Incendiary Runestone",
			model = 4485591,
			text = {
				en = "Incendiary Runestone",
				es = "Piedra rúnica incendiaria",
				de = "Flammender Runenstein",
				fr = "Pierre runique incendiaire",
				it = "Pietra Runica Incendiaria",
				pt = "Pedra Rúnica Incendiária",
				ru = "Опаляющий рунический камень",
				ko = "화염 룬석",
			},
		},
	
		[382085] = {
			readable = "Report: Infestation",
			model = 4209021,
			text = {
				en = "Report: Infestation",
				es = "Informe: infestación",
				de = "Bericht: Befall",
				fr = "Rapport : infestation",
				it = "Rapporto: Infestazione",
				pt = "Relatório: Infestação",
				ru = "Отчет: заражение",
				ko = "보고서: 들끓는 해충",
			},
		},
	
		[382086] = {
			readable = "Dragonscale Expedition Flag",
			model = 4198200,
			text = {
				en = "Dragonscale Expedition Flag",
				es = "Bandera de la Expedición Dragontina",
				de = "Flagge der Drachenschuppenexpedition",
				fr = "Drapeau de l’expédition du Dracaret",
				it = "Bandiera della Spedizione delle Scaglie di Drago",
				pt = "Bandeira da Expedição Escama de Dragão",
				ru = "Флаг Драконьей экспедиции",
				ko = "용비늘 원정대 깃발",
				cn = "龙鳞探险队旗帜",
			},
		},
	
		[382090] = {
			readable = "Shimmering Treasure Pool",
			model = 219411,
			text = {
				en = "Shimmering Treasure Pool",
				es = "Charco de tesoros centelleantes",
				de = "Schimmerndes Schatzbecken",
				fr = "Bassin au trésor scintillant",
				it = "Banco di Tesori Scintillanti",
				pt = "Poço do Tesouro Cintilante",
				ru = "Сверкающий пруд с сокровищами",
				ko = "일렁이는 보물 웅덩이",
				cn = "微光宝藏池",
			},
		},
	
		[382091] = {
			readable = "Serene Spa Glider",
			model = 609830,
			text = {
				en = "Serene Spa Glider",
				es = "Planeador de la Sauna de Sueños Serenos",
				de = "Ruhiger Badgleiter",
				fr = "Planeur du spa Rêves sereins",
				it = "Aliante della Spa Sereno",
				pt = "Planador do Spa Sereno",
				ru = "Планер \"Мирных снов\"",
				ko = "평온의 온천 활공기",
			},
		},
	
		[382092] = {
			readable = "Dragonscale Expedition Flag",
			model = 4198200,
			text = {
				en = "Dragonscale Expedition Flag",
				es = "Bandera de la Expedición Dragontina",
				de = "Flagge der Drachenschuppenexpedition",
				fr = "Drapeau de l’expédition du Dracaret",
				it = "Bandiera della Spedizione delle Scaglie di Drago",
				pt = "Bandeira da Expedição Escama de Dragão",
				ru = "Флаг Драконьей экспедиции",
				ko = "용비늘 원정대 깃발",
				cn = "龙鳞探险队旗帜",
			},
		},
	
		[382094] = {
			readable = "Dragonscale Expedition Flag",
			model = 4198200,
			text = {
				en = "Dragonscale Expedition Flag",
				es = "Bandera de la Expedición Dragontina",
				de = "Flagge der Drachenschuppenexpedition",
				fr = "Drapeau de l’expédition du Dracaret",
				it = "Bandiera della Spedizione delle Scaglie di Drago",
				pt = "Bandeira da Expedição Escama de Dragão",
				ru = "Флаг Драконьей экспедиции",
				ko = "용비늘 원정대 깃발",
				cn = "龙鳞探险队旗帜",
			},
		},
	
		[382099] = {
			readable = "Somewhat-Stabilized Arcana",
			model = 166432,
			text = {
				en = "Somewhat-Stabilized Arcana",
				es = "Arcana ligeramente estabilizada",
				de = "Einigermaßen stabilisiertes Arkana",
				fr = "Arcana vaguement stabilisée",
				it = "Arcano Abbastanza Stabilizzato",
				pt = "Arcana Meio Estabilizada",
				ru = "В какой-то мере стабилизированные чары",
				ko = "어느 정도 안정된 비전력",
				cn = "还算稳定的奥能",
			},
		},
	
		[382100] = {
			readable = "Repaired Titan Orb",
			model = 4485606,
			text = {
				en = "Repaired Titan Orb",
				es = "Orbe titánico reparado",
				de = "Reparierte Titanenkugel",
				fr = "Orbe de Titan réparé",
				ru = "Восстановленная сфера титанов",
			},
		},
	
		[382101] = {
			readable = "Dragonscale Expedition Flag",
			model = 4198200,
			text = {
				en = "Dragonscale Expedition Flag",
				es = "Bandera de la Expedición Dragontina",
				de = "Flagge der Drachenschuppenexpedition",
				fr = "Drapeau de l’expédition du Dracaret",
				it = "Bandiera della Spedizione delle Scaglie di Drago",
				pt = "Bandeira da Expedição Escama de Dragão",
				ru = "Флаг Драконьей экспедиции",
				ko = "용비늘 원정대 깃발",
				cn = "龙鳞探险队旗帜",
			},
		},
	
		[382103] = {
			readable = "Dragonscale Expedition Flag",
			model = 4198200,
			text = {
				en = "Dragonscale Expedition Flag",
				es = "Bandera de la Expedición Dragontina",
				de = "Flagge der Drachenschuppenexpedition",
				fr = "Drapeau de l’expédition du Dracaret",
				it = "Bandiera della Spedizione delle Scaglie di Drago",
				pt = "Bandeira da Expedição Escama de Dragão",
				ru = "Флаг Драконьей экспедиции",
				ko = "용비늘 원정대 깃발",
				cn = "龙鳞探险队旗帜",
			},
		},
	
		[382105] = {
			readable = "Dragonscale Expedition Flag",
			model = 4198200,
			text = {
				en = "Dragonscale Expedition Flag",
				es = "Bandera de la Expedición Dragontina",
				de = "Flagge der Drachenschuppenexpedition",
				fr = "Drapeau de l’expédition du Dracaret",
				it = "Bandiera della Spedizione delle Scaglie di Drago",
				pt = "Bandeira da Expedição Escama de Dragão",
				ru = "Флаг Драконьей экспедиции",
				ko = "용비늘 원정대 깃발",
				cn = "龙鳞探险队旗帜",
			},
		},
	
		[382107] = {
			readable = "Dragonscale Expedition Flag",
			model = 4198200,
			text = {
				en = "Dragonscale Expedition Flag",
				es = "Bandera de la Expedición Dragontina",
				de = "Flagge der Drachenschuppenexpedition",
				fr = "Drapeau de l’expédition du Dracaret",
				it = "Bandiera della Spedizione delle Scaglie di Drago",
				pt = "Bandeira da Expedição Escama de Dragão",
				ru = "Флаг Драконьей экспедиции",
				ko = "용비늘 원정대 깃발",
				cn = "龙鳞探险队旗帜",
			},
		},
	
		[382110] = {
			readable = "Dragonscale Expedition Flag",
			model = 4198200,
			text = {
				en = "Dragonscale Expedition Flag",
				es = "Bandera de la Expedición Dragontina",
				de = "Flagge der Drachenschuppenexpedition",
				fr = "Drapeau de l’expédition du Dracaret",
				it = "Bandiera della Spedizione delle Scaglie di Drago",
				pt = "Bandeira da Expedição Escama de Dragão",
				ru = "Флаг Драконьей экспедиции",
				ko = "용비늘 원정대 깃발",
				cn = "龙鳞探险队旗帜",
			},
		},
	
		[382112] = {
			readable = "Dragonscale Expedition Flag",
			model = 4198200,
			text = {
				en = "Dragonscale Expedition Flag",
				es = "Bandera de la Expedición Dragontina",
				de = "Flagge der Drachenschuppenexpedition",
				fr = "Drapeau de l’expédition du Dracaret",
				it = "Bandiera della Spedizione delle Scaglie di Drago",
				pt = "Bandeira da Expedição Escama de Dragão",
				ru = "Флаг Драконьей экспедиции",
				ko = "용비늘 원정대 깃발",
				cn = "龙鳞探险队旗帜",
			},
		},
	
		[382116] = {
			readable = "Dragonscale Expedition Flag",
			model = 4198200,
			text = {
				en = "Dragonscale Expedition Flag",
				es = "Bandera de la Expedición Dragontina",
				de = "Flagge der Drachenschuppenexpedition",
				fr = "Drapeau de l’expédition du Dracaret",
				it = "Bandiera della Spedizione delle Scaglie di Drago",
				pt = "Bandeira da Expedição Escama de Dragão",
				ru = "Флаг Драконьей экспедиции",
				ko = "용비늘 원정대 깃발",
				cn = "龙鳞探险队旗帜",
			},
		},
	
		[382118] = {
			readable = "Dragonscale Expedition Flag",
			model = 4198200,
			text = {
				en = "Dragonscale Expedition Flag",
				es = "Bandera de la Expedición Dragontina",
				de = "Flagge der Drachenschuppenexpedition",
				fr = "Drapeau de l’expédition du Dracaret",
				it = "Bandiera della Spedizione delle Scaglie di Drago",
				pt = "Bandeira da Expedição Escama de Dragão",
				ru = "Флаг Драконьей экспедиции",
				ko = "용비늘 원정대 깃발",
				cn = "龙鳞探险队旗帜",
			},
		},
	
		[382120] = {
			readable = "Dragonscale Expedition Flag",
			model = 4198200,
			text = {
				en = "Dragonscale Expedition Flag",
				es = "Bandera de la Expedición Dragontina",
				de = "Flagge der Drachenschuppenexpedition",
				fr = "Drapeau de l’expédition du Dracaret",
				it = "Bandiera della Spedizione delle Scaglie di Drago",
				pt = "Bandeira da Expedição Escama de Dragão",
				ru = "Флаг Драконьей экспедиции",
				ko = "용비늘 원정대 깃발",
				cn = "龙鳞探险队旗帜",
			},
		},
	
		[382123] = {
			readable = "Deep Rimefin Tuna Pool",
			model = 343863,
			text = {
				en = "Deep Rimefin Tuna Pool",
				es = "Charco profundo de atunes hieloaleta",
				de = "Tiefenraureifflossenthunfischschwarm",
				fr = "Banc de thons frimageoires des profondeurs",
				ru = "Косяк глубинного льдистого тунца",
			},
		},
	
		[382166] = {
			readable = "The Ruby Feast!",
			model = 4317329,
			text = {
				en = "The Ruby Feast!",
				es = "¡El Festín Rubí!",
				de = "Das Rubinfestmahl!",
				fr = "Au Festin rubis !",
				it = "Banchetto di Rubino!",
				pt = "Banquete Rubi!",
				ru = "Рубиновый Пир!",
				ko = "루비 연회장!",
				cn = "红玉盛宴！",
			},
		},
	
		[382168] = {
			readable = "The Ruby Feast!",
			model = 4317329,
			text = {
				en = "The Ruby Feast!",
				es = "¡El Festín Rubí!",
				de = "Das Rubinfestmahl!",
				fr = "Le Festin rubis !",
				it = "Banchetto di Rubino!",
				pt = "Banquete Rubi!",
				ru = "Рубиновый Пир!",
				ko = "루비 연회장!",
				cn = "红玉盛宴！",
			},
		},
	
		[382177] = {
			readable = "Sprung Trap",
			model = 3931003,
			text = {
				en = "Sprung Trap",
				es = "Trampa activada",
				de = "Ausgelöste Falle",
				fr = "Piège déclenché",
				it = "Trappola Attivata",
				pt = "Armadilha Disparada",
				ru = "Сработавшая ловушка",
				ko = "용수철 덫",
			},
		},
	
		[382180] = {
			readable = "Overheated Magma Thresher Pool",
			model = 219405,
			text = {
				en = "Overheated Magma Thresher Pool",
				es = "Charco de trilladores de magma sobrecalentado",
				de = "Überhitzter Magmadrescherschwarm",
				fr = "Banc de requins-renards magmatiques surchauffé",
				it = "Banco di Plesiosauri del Magma Surriscaldato",
				pt = "Cardume de Mangual de Magma Superaquecido",
				ru = "Перегретый пруд лавазубов",
				ko = "과열된 용암 상어 떼",
			},
		},
	
		[382181] = {
			readable = "Highly Spiced Haunch",
			model = 4288081,
			text = {
				en = "Highly Spiced Haunch",
				es = "Anca muy especiada",
				de = "Stark gewürzte Keule",
				fr = "Cuissot très épicé",
				it = "Cosciotto Molto Speziato",
				pt = "Flanco Muito Apimentado",
				ru = "Окорок с приправами",
				ko = "향신료를 듬뿍 바른 허벅지 고기",
				cn = "浓香腰肉",
			},
		},
	
		[382190] = {
			readable = "Coal-Fired Rib Rack",
			model = 4500574,
			text = {
				en = "Coal-Fired Rib Rack",
				es = "Costillar al carbón",
				de = "Kohlebefeuerte Rippchen",
				fr = "Carré de côtes cuites au charbon",
				it = "Costolette alla Brace",
				pt = "Costeletas no Carvão",
				ru = "Поджаренные на углях ребрышки",
				ko = "석탄에 구운 갈비",
				cn = "煤火肋架",
			},
		},
	
		[382191] = {
			readable = "Charred Porter",
			model = 1852897,
			text = {
				en = "Charred Porter",
				es = "Cerveza negra carbonizada",
				de = "Rauchiger Portwein",
				fr = "Porte-charbon",
				it = "Scura Carbonizzata",
				pt = "Porteiro Calcinado",
				ru = "Опаленный портер",
				ko = "구운 고급 스테이크",
				cn = "焦黑的波特酒",
			},
		},
	
		[382192] = {
			readable = "Lemon Silverleaf Tea",
			model = 4201170,
			text = {
				en = "Lemon Silverleaf Tea",
				es = "Té de hojaplata con limón",
				de = "Zitroniger Silberblatttee",
				fr = "Thé de feuillargent au citron",
				it = "Tè al Limone di Fogliargenta",
				pt = "Chá de Folha-prata com Limão",
				ru = "Чай с лимоном и сребролистом",
				ko = "레몬 은엽수잎 차",
				cn = "柠檬银叶茶",
			},
		},
	
		[382193] = {
			readable = "Chest of the Elements",
			model = 4216697,
			text = {
				en = "Chest of the Elements",
				es = "Cofre de los elementos",
				de = "Truhe der Elemente",
				fr = "Coffre des éléments",
				it = "Cassa degli Elementi",
				ru = "Сундук стихий",
				cn = "元素宝箱",
			},
		},
	
		[382194] = {
			readable = "Lemon Silverleaf Tea",
			model = 4201171,
			text = {
				en = "Lemon Silverleaf Tea",
				es = "Té de hojaplata con limón",
				de = "Zitroniger Silberblatttee",
				fr = "Thé de feuillargent au citron",
				it = "Tè al Limone di Fogliargenta",
				pt = "Chá de Folha-prata com Limão",
				ru = "Чай с лимоном и сребролистом",
				ko = "레몬 은엽수잎 차",
				cn = "柠檬银叶茶",
			},
		},
	
		[382195] = {
			readable = "Elemental Bound Chest",
			model = 4216698,
			text = {
				en = "Elemental Bound Chest",
				es = "Cofre reforzado elemental",
				de = "Elementargebundene Truhe",
				fr = "Coffre lié par les élémentaires",
				it = "Cassa Vincolata dagli Elementi",
				pt = "Baú Reforçado Elemental",
				ru = "Скованный сундук стихий",
				ko = "정기결속 보관함",
				cn = "元素束缚之箱",
			},
		},
	
		[382196] = {
			readable = "Cinna-Cinderbloom Tea",
			model = 4201172,
			text = {
				en = "Cinna-Cinderbloom Tea",
				es = "Té de flor de ceniza y canela",
				de = "Zimtiger Aschenblütentee",
				fr = "Thé de cendrelle à la cannelle",
				it = "Tè alla Cannellacenere",
				pt = "Chá de Cinzanilha com Canela",
				ru = "Чай с корицей и пепельником",
				ko = "계피 재투성이꽃 차",
				cn = "肉桂燃烬草茶",
			},
		},
	
		[382197] = {
			readable = "Cinna-Cinderbloom Tea",
			model = 4201170,
			text = {
				en = "Cinna-Cinderbloom Tea",
				es = "Té de flor de ceniza y canela",
				de = "Zimtiger Aschenblütentee",
				fr = "Thé de cendrelle à la cannelle",
				it = "Tè alla Cannellacenere",
				pt = "Chá de Cinzanilha com Canela",
				ru = "Чай с корицей и пепельником",
				ko = "계피 재투성이꽃 차",
				cn = "肉桂燃烬草茶",
			},
		},
	
		[382198] = {
			readable = "Aruunem Berrytart",
			model = 243036,
			text = {
				en = "Aruunem Berrytart",
				es = "Tarta de bayas de Aruunem",
				de = "Aruunembeerentörtchen",
				fr = "Tarte aux baies d’Aruunem",
				it = "Torta di Bacche di Aruunem",
				pt = "Torta de Amoras de Aruunem",
				ru = "Пирог из ягод Арууны",
				ko = "아루넴 딸기 타르트",
				cn = "阿鲁纳姆浆果挞",
			},
		},
	
		[382199] = {
			readable = "Aruunem Berrytart",
			model = 243034,
			text = {
				en = "Aruunem Berrytart",
				es = "Tarta de bayas de Aruunem",
				de = "Aruunembeerentörtchen",
				fr = "Tarte aux baies d’Aruunem",
				it = "Torta di Bacche di Aruunem",
				pt = "Torta de Amoras de Aruunem",
				ru = "Пирог из ягод Арууны",
				ko = "아루넴 딸기 타르트",
				cn = "阿鲁纳姆浆果挞",
			},
		},
	
		[382201] = {
			readable = "Stonetalon Bloom Skewer",
			model = 3870816,
			text = {
				en = "Stonetalon Bloom Skewer",
				es = "Brocheta de flores del Espolón",
				de = "Steinkrallenblütenspieß",
				fr = "Brochette fleurie des Serres-Rocheuses",
				it = "Spiedino di Boccioli di Petrartiglio",
				pt = "Espeto de Flor das Torres de Pedra",
				ru = "Ассорти Когтистых гор",
				ko = "돌발톱 꽃송이 꼬챙이",
				cn = "石爪花串",
			},
		},
	
		[382202] = {
			readable = "Druidic Dreamsalad",
			model = 1108841,
			text = {
				en = "Druidic Dreamsalad",
				es = "Ensalada onírica druídica",
				de = "Druidischer Traumsalat",
				fr = "Salade de rêve druidique",
				it = "Insalata di Sogni Druidica",
				pt = "Salada dos Sonhos Druídica",
				ru = "Друидический салат снов",
				ko = "드루이드 꿈 샐러드",
				cn = "德鲁伊梦境沙拉",
			},
		},
	
		[382203] = {
			readable = "Dragonfruit Punch",
			model = 309568,
			text = {
				en = "Dragonfruit Punch",
				es = "Ponche de frutadragón",
				de = "Drachenfruchtpunsch",
				fr = "Punch aux fruits du Dragon",
				it = "Punch di Frutto del Drago",
				pt = "Ponche de Fruta-do-dragão",
				ru = "Пунш из драконовых фруктов",
				ko = "용과 혼합주",
				cn = "巨龙果潘趣酒",
			},
		},
	
		[382204] = {
			readable = "Fine Taladorian Cheese Platter",
			model = 996183,
			text = {
				en = "Fine Taladorian Cheese Platter",
				es = "Tabla de quesos fina de Talador",
				de = "Feine Taladorkäseplatte",
				fr = "Plateau de fromages raffinés de Talador",
				it = "Tagliere di Formaggi Raffinati Taladoriano",
				pt = "Bandeja de Queijos Finos Taladorianos",
				ru = "Блюдо с изысканным таладорским сыром",
				ko = "고급 탈라도르 치즈 접시",
				cn = "精致塔拉多奶酪盘",
			},
		},
	
		[382205] = {
			readable = "Azsunian Poached Lobster",
			model = 1852909,
			text = {
				en = "Azsunian Poached Lobster",
				es = "Langosta azsuniana pochada",
				de = "Poschierter azsunianscher Hummer",
				fr = "Homard poché à l’azsunienne",
				it = "Aragosta di Azsuna",
				pt = "Lagosta Escaldada Azsuniana",
				ru = "Азсунский вареный омар",
				ko = "아즈스나산 바닷가재",
				cn = "阿苏纳水煮龙虾",
			},
		},
	
		[382208] = {
			readable = "Rare Vintage Arcwine",
			model = 1360813,
			text = {
				en = "Rare Vintage Arcwine",
				es = "Vino de arco añejo poco común",
				de = "Seltener Jahrgangsarkwein",
				fr = "Arquevin millésimé rare",
				it = "Arcavino d'Annata Rara",
				pt = "Vinho Arcano Vintage Raro",
				ru = "Редкое чародейское вино",
				ko = "희귀한 고급 비전주",
				cn = "稀有的魔力酒陈酿",
			},
		},
	
		[382209] = {
			readable = "Captain's Caramelized Catfish",
			model = 1852905,
			text = {
				en = "Captain's Caramelized Catfish",
				es = "Siluro del capitán caramelizado",
				de = "Karamellisierter Wels des Kapitäns",
				fr = "Poisson-chat caramélisé du capitaine",
				it = "Pescegatto Caramellizzato del Capitano",
				pt = "Bagre Caramelizado do Capitão",
				ru = "Капитанский сом в карамельном соусе",
				ko = "선장의 메기 설탕 볶음",
				cn = "船长的焦糖鲶鱼",
			},
		},
	
		[382210] = {
			readable = "Mantis Shrimp Cocktail",
			model = 1852917,
			text = {
				en = "Mantis Shrimp Cocktail",
				es = "Cóctel de gambas mantis",
				de = "Mantisgarnelencocktail",
				fr = "Cocktail de crevettes-mantes",
				it = "Cocktail di Gamberi Mantide",
				pt = "Coquetel de Camarão Mantídeo",
				ru = "Коктейль из раков-богомолов",
				ko = "사마귀 새우 칵테일",
				cn = "螳螂虾鸡尾酒",
			},
		},
	
		[382211] = {
			readable = "Mantis Shrimp Cocktail",
			model = 1852916,
			text = {
				en = "Mantis Shrimp Cocktail",
				es = "Cóctel de gambas mantis",
				de = "Mantisgarnelencocktail",
				fr = "Cocktail de crevettes-mantes",
				it = "Cocktail di Gamberi Mantide",
				pt = "Coquetel de Camarão Mantídeo",
				ru = "Коктейль из раков-богомолов",
				ko = "사마귀 새우 칵테일",
				cn = "螳螂虾鸡尾酒",
			},
		},
	
		[382213] = {
			readable = "Venrik's Goat Milk",
			model = 1852897,
			text = {
				en = "Venrik's Goat Milk",
				es = "Leche de cabra de Venrik",
				de = "Venriks Ziegenmilch",
				fr = "Lait de chèvre de Venrik",
				it = "Latte di Capra di Venrik",
				pt = "Leite de Cabra de Venrik",
				ru = "Козье молоко Венрика",
				ko = "벤리크의 산양유",
				cn = "文里克的羊奶",
			},
		},
	
		[382214] = {
			readable = "Seared Sea Mist Noodles",
			model = 3870812,
			text = {
				en = "Seared Sea Mist Noodles",
				es = "Fideos de niebla marina abrasados",
				de = "Gebratene Meeresnebelnudeln",
				fr = "Nouilles à la brume de mer sautées",
				it = "Spaghetti di Riso alla Nebbia Marina",
				pt = "Lámen de Névoa Marinha Grelhado",
				ru = "Опаленная лапша морских туманов",
				ko = "가열한 바다 안개 국수",
				cn = "焦烤海雾米线",
			},
		},
	
		[382215] = {
			readable = "Fried Emperor Wraps",
			model = 1707337,
			text = {
				en = "Fried Emperor Wraps",
				es = "Rollitos de emperador fritos",
				de = "Frittierte Kaisertaschen",
				fr = "Wraps impériaux frits",
				it = "Piadine Fritte dell'Imperatore",
				pt = "Rolinhos do Imperador Fritos",
				ru = "Императорский жареный рулет",
				ko = "튀긴 황제 말이",
				cn = "帝王炸卷",
			},
		},
	
		[382216] = {
			readable = "Fried Emperor Wraps",
			model = 1804493,
			text = {
				en = "Fried Emperor Wraps",
				es = "Rollitos de emperador fritos",
				de = "Frittierte Kaisertaschen",
				fr = "Wraps impériaux frits",
				it = "Piadine Fritte dell'Imperatore",
				pt = "Rolinhos do Imperador Fritos",
				ru = "Императорский жареный рулет",
				ko = "튀긴 황제 말이",
				cn = "帝王炸卷",
			},
		},
	
		[382217] = {
			readable = "Roquefort-Stuffed Peppers",
			model = 1804343,
			text = {
				en = "Roquefort-Stuffed Peppers",
				es = "Pimientos rellenos de roquefort",
				de = "Mit Roquefortkäse gefüllte Paprika",
				fr = "Poivrons farcis au roquefort",
				it = "Peperoni Ripieni di Formaggio",
				pt = "Pimentas Recheadas com Queijo Roquefort",
				ru = "Перцы с рокфором",
				ko = "양젖 치즈를 채워 넣은 고추",
				cn = "干酪馅胡椒",
			},
		},
	
		[382218] = {
			readable = "Picante Pomfruit Cake",
			model = 243001,
			text = {
				en = "Picante Pomfruit Cake",
				es = "Pastel de poma picante",
				de = "Pikanter Pomfruchtkuchen",
				fr = "Gâteau aux pommettes piquantes",
				it = "Torta di Pomo d'Oro Piccante",
				pt = "Bolo de Romã Picante",
				ru = "Пикантный тыблочный пирог",
				ko = "매콤한 석류사과 케이크",
				cn = "皮肯特梨果蛋糕",
			},
		},
	
		[382219] = {
			readable = "Ravenberry Panacotta Delight",
			model = 1368703,
			text = {
				en = "Ravenberry Panacotta Delight",
				es = "Delicia de panacota de bayas de cuervo",
				de = "Rabenbeerenpanacotta",
				fr = "Délice de panna cotta aux busseroles",
				it = "Panacea di Pannacotta alle Bacche",
				pt = "Deleite de Panacota de Fruta-corvo",
				ru = "Деликатесная панна-котта с вороникой",
				ko = "까마귀딸기 크림 별미",
				cn = "欢乐鸦莓奶冻",
			},
		},
	
		[382220] = {
			readable = "Moira's Choice Espresso",
			model = 1305117,
			text = {
				en = "Moira's Choice Espresso",
				es = "Bebedizo favorito de Moira",
				de = "Moiras Lieblingsespresso",
				fr = "Espresso sélectionné par Moira",
				it = "Espresso Delizia di Moira",
				pt = "Espresso Favorito da Moira",
				ru = "Эспрессо \"Выбор Мойры\"",
				ko = "모이라가 선택한 쌍화차",
				cn = "茉艾拉挚爱的浓缩咖啡",
			},
		},
	
		[382221] = {
			readable = "Moira's Choice Espresso",
			model = 1305131,
			text = {
				en = "Moira's Choice Espresso",
				es = "Bebedizo favorito de Moira",
				de = "Moiras Lieblingsespresso",
				fr = "Espresso sélectionné par Moira",
				it = "Espresso Delizia di Moira",
				pt = "Espresso Favorito da Moira",
				ru = "Эспрессо \"Выбор Мойры\"",
				ko = "모이라가 선택한 쌍화차",
				cn = "茉艾拉挚爱的浓缩咖啡",
			},
		},
	
		[382234] = {
			readable = "Lost Supplies",
			model = 3936818,
			text = {
				en = "Lost Supplies",
				es = "Provisiones extraviadas",
				de = "Verlorene Vorräte",
				fr = "Fournitures perdues",
				it = "Rifornimenti Perduti",
				pt = "Suprimentos Perdidos",
				ru = "Потерянные припасы",
			},
		},
	
		[382247] = {
			readable = "Lost Supplies",
			model = 4198216,
			text = {
				en = "Lost Supplies",
				es = "Provisiones extraviadas",
				de = "Verlorene Vorräte",
				fr = "Fournitures perdues",
				it = "Rifornimenti Perduti",
				pt = "Suprimentos Perdidos",
				ru = "Потерянные припасы",
				cn = "遗失的补给品",
			},
		},
	
		[382248] = {
			readable = "Lost Supplies",
			model = 3936818,
			text = {
				en = "Lost Supplies",
				es = "Provisiones extraviadas",
				de = "Verlorene Vorräte",
				fr = "Fournitures perdues",
				it = "Rifornimenti Perduti",
				ru = "Потерянные припасы",
				cn = "遗失的补给品",
			},
		},
	
		[382250] = {
			readable = "Lost Supplies",
			model = 3936818,
			text = {
				en = "Lost Supplies",
				es = "Provisiones extraviadas",
				de = "Verlorene Vorräte",
				fr = "Fournitures perdues",
				it = "Rifornimenti Perduti",
				ru = "Потерянные припасы",
				cn = "遗失的补给品",
			},
		},
	
		[382251] = {
			readable = "Lost Supplies",
			model = 3936818,
			text = {
				en = "Lost Supplies",
				es = "Provisiones extraviadas",
				de = "Verlorene Vorräte",
				fr = "Fournitures perdues",
				it = "Rifornimenti Perduti",
				pt = "Suprimentos Perdidos",
				ru = "Потерянные припасы",
			},
		},
	
		[382252] = {
			readable = "Lost Supplies",
			model = 3936818,
			text = {
				en = "Lost Supplies",
				es = "Provisiones extraviadas",
				de = "Verlorene Vorräte",
				fr = "Fournitures perdues",
				it = "Rifornimenti Perduti",
				pt = "Suprimentos Perdidos",
				ru = "Потерянные припасы",
				ko = "잃어버린 보급품",
			},
		},
	
		[382255] = {
			readable = "Lost Supplies",
			model = 3936818,
			text = {
				en = "Lost Supplies",
				es = "Provisiones extraviadas",
				de = "Verlorene Vorräte",
				fr = "Fournitures perdues",
				pt = "Suprimentos Perdidos",
				ru = "Потерянные припасы",
				ko = "잃어버린 보급품",
				cn = "遗失的补给品",
			},
		},
	
		[382256] = {
			readable = "Lost Supplies",
			model = 4198216,
			text = {
				en = "Lost Supplies",
				es = "Provisiones extraviadas",
				de = "Verlorene Vorräte",
				fr = "Fournitures perdues",
				it = "Rifornimenti Perduti",
				pt = "Suprimentos Perdidos",
				ru = "Потерянные припасы",
				cn = "遗失的补给品",
			},
		},
	
		[382257] = {
			readable = "Lost Supplies",
			model = 3936818,
			text = {
				en = "Lost Supplies",
				es = "Provisiones extraviadas",
				de = "Verlorene Vorräte",
				fr = "Fournitures perdues",
				pt = "Suprimentos Perdidos",
				ru = "Потерянные припасы",
			},
		},
	
		[382282] = {
			readable = "Blooming Ritherem",
			model = 3882676,
			text = {
				en = "Blooming Ritherem",
				es = "Ritherem floreciente",
				de = "Blühende Ritherem",
				fr = "Ruisselette florissante",
				it = "Ritherem Fiorente",
				pt = "Riterém em Flor",
				ru = "Цветущий риферем",
				ko = "활짝 핀 리테렘",
				cn = "绽放的莱瑟雷姆花",
			},
		},
	
		[382283] = {
			readable = "Oozing Claw Thistle",
			model = 4049234,
			text = {
				en = "Oozing Claw Thistle",
				es = "Cardo de garra rezumante",
				de = "Triefende Klauendistel",
				fr = "Chardon crochu suintant",
				it = "Cardartiglio Melmoso",
				pt = "Cardo de Garra Gosmento",
				ru = "Сочащийся когтистый чертополох",
				ko = "수액이 흐르는 발톱 엉겅퀴",
				cn = "渗液的爪棘",
			},
		},
	
		[382284] = {
			readable = "Mature Gift of the Grove",
			model = 3996863,
			text = {
				en = "Mature Gift of the Grove",
				es = "Regalo de la arboleda maduro",
				de = "Reifes Geschenk des Hains",
				fr = "Don du bosquet épanoui",
				it = "Dono Maturo del Boschetto",
				pt = "Dádiva do Bosque Adulta",
				ru = "Созревший дар рощи",
				ko = "다 자란 숲의 선물",
				cn = "成熟的林地赐福",
			},
		},
	
		[382285] = {
			readable = "Mature Terata",
			model = 3882687,
			text = {
				en = "Mature Terata",
				es = "Terata madura",
				de = "Reife Terata",
				fr = "Terata épanouie",
				it = "Terata Matura",
				pt = "Terata Adulta",
				ru = "Созревшая терата",
				ko = "다 자란 테라타",
				cn = "成熟的泰雷塔草",
			},
		},
	
		[382286] = {
			readable = "Singing River Bell",
			model = 3847782,
			text = {
				en = "Singing River Bell",
				es = "Campana del río cantarina",
				de = "Singendes Flussglöckchen",
				fr = "Cloche des rivières",
				it = "Campanula dei Fiumi Risonante",
				pt = "Sino do Rio Cantante",
				ru = "Поющий речной колокольчик",
				ko = "노래하는 강물 종",
				cn = "吟歌河铃花",
			},
		},
	
		[382287] = {
			readable = "Blooming Fangtooth",
			model = 3754698,
			text = {
				en = "Blooming Fangtooth",
				es = "Pez abisal floreciente",
				de = "Blühendes Fangzähnchen",
				fr = "Acérelle florissante",
				it = "Aringa Fiorente",
				pt = "Presadente em Flor",
				ru = "Цветущий клыкозуб",
				ko = "활짝 핀 송곳니꽃",
				cn = "绽放的獠牙花",
			},
		},
	
		[382288] = {
			readable = "Ripe Winter Berries",
			model = 3855392,
			text = {
				en = "Ripe Winter Berries",
				es = "Bayas invernales maduras",
				de = "Reife Winterbeeren",
				fr = "Baies d’hiver mûres",
				it = "Bacche Invernali Mature",
				pt = "Frutas de Inverno Maduras",
				ru = "Зрелые зимние ягоды",
				ko = "잘 여문 겨울 열매",
				cn = "成熟的冬莓",
			},
		},
	
		[382289] = {
			readable = "Pulsing Blightshroom",
			model = 4228210,
			text = {
				en = "Pulsing Blightshroom",
				es = "Champiñublo pulsante",
				de = "Pulsierender Pestling",
				fr = "Fongifléau palpitant",
				it = "Fungo del Morbo Pulsante",
				pt = "Pragumelo Pulsante",
				ru = "Пульсирующий гнилогриб",
				ko = "맥동하는 황폐버섯",
				cn = "脉动的荒菇",
			},
		},
	
		[382290] = {
			readable = "Mature Ley Bloom",
			model = 4421495,
			text = {
				en = "Mature Ley Bloom",
				es = "Flor Ley madura",
				de = "Reife Leyblüte",
				fr = "Telluflore mature",
				it = "Bocciolo di Faglia Adulto",
				pt = "Flor do Meridiano Adulta",
				ru = "Созревший силовой цветок",
				ko = "다 자란 지맥꽃",
				cn = "成熟的魔网花",
			},
		},
	
		[382291] = {
			readable = "Mature Highland Milkweed",
			model = 3952240,
			text = {
				en = "Mature Highland Milkweed",
				es = "Flor de algodoncillo de las Tierras Altas madura",
				de = "Reife Hochlandseidenpflanze",
				fr = "Herbe laiteuse mature des hautes-terres",
				it = "Asclepiade delle Alture Matura",
				pt = "Lactina do Planalto Adulta",
				ru = "Созревшая высокогорная молочная трава",
				ko = "다 자란 고원 박주가리",
				cn = "成熟的高原奶草",
			},
		},
	
		[382292] = {
			readable = "Ripe Cuppressa",
			model = 3947324,
			text = {
				en = "Ripe Cuppressa",
				es = "Cuppressa madura",
				de = "Reife Zypresse",
				fr = "Cuppressa mûre",
				it = "Cipresso Maturo",
				pt = "Cipestre Maduro",
				ru = "Зрелые кипарисовые ягоды",
				ko = "잘 여문 커프레사",
				cn = "成熟的柏木",
			},
		},
	
		[382293] = {
			readable = "Ripe Cuppressa",
			model = 4078315,
			text = {
				en = "Ripe Cuppressa",
				es = "Cuppressa madura",
				de = "Reife Zypresse",
				fr = "Cuppressa mûre",
				it = "Cipresso Maturo",
				pt = "Cipestre Maduro",
				ru = "Зрелые кипарисовые ягоды",
				ko = "잘 여문 커프레사",
				cn = "成熟的柏木",
			},
		},
	
		[382294] = {
			readable = "Blooming Titian Orchid",
			model = 4007093,
			text = {
				en = "Blooming Titian Orchid",
				es = "Orquídea titánica floreciente",
				de = "Blühende Tizianorchidee",
				fr = "Orchidée dorée en fleur",
				it = "Orchidea Tiziano Fiorente",
				pt = "Orquídea Títia em Flor",
				ru = "Цветущая орхидея титанов",
				ko = "활짝 핀 티치안 난초",
				cn = "绽放的褐兰",
			},
		},
	
		[382295] = {
			readable = "Blooming Magenta Titian Orchid",
			model = 4273173,
			text = {
				en = "Blooming Magenta Titian Orchid",
				es = "Orquídea titánica magenta floreciente",
				de = "Blühende Purpurtizianorchidee",
				fr = "Orchidée magenta doré en fleur",
				it = "Orchidea Tiziano Magenta Fiorente",
				pt = "Orquídea Títia Magenta em Flor",
				ru = "Цветущая пурпурная орхидея титанов",
				ko = "활짝 핀 자홍색 티치안 난초",
				cn = "绽放的品红褐兰",
			},
		},
	
		[382296] = {
			readable = "Mature Vine Flower",
			model = 4035131,
			text = {
				en = "Mature Vine Flower",
				es = "Flor de vid adulta",
				de = "Reife Rankenblume",
				fr = "Fleur de vigne épanouie",
				it = "Fiore di Viticcio Maturo",
				pt = "Flor de Trepadeira Adulta",
				ru = "Созревший вьюнок",
				ko = "다 자란 덩굴꽃",
				cn = "成熟的藤蔓花",
			},
		},
	
		[382297] = {
			readable = "Ripe Gratona",
			model = 4038389,
			text = {
				en = "Ripe Gratona",
				es = "Gratona madura",
				de = "Reife Gratona",
				fr = "Gratona mûre",
				it = "Gratona Matura",
				pt = "Gratona Madura",
				ru = "Зрелая гратона",
				ko = "잘 여문 그라토나",
				cn = "成熟的格拉托纳草",
			},
		},
	
		[382298] = {
			readable = "Thaldraszus Bloom",
			model = 4196644,
			text = {
				en = "Thaldraszus Bloom",
				es = "Flor de Thaldraszus",
				de = "Thaldraszusblüte",
				fr = "Fleur de Thaldraszus",
				it = "Bocciolo di Thaldraszus",
				pt = "Flor de Thaldraszus",
				ru = "Цветок Тальдразуса",
				ko = "탈드라서스 꽃송이",
				cn = "索德拉苏斯花",
			},
		},
	
		[382299] = {
			readable = "Sundered Flame Supply Crate",
			model = 3917382,
			text = {
				en = "Sundered Flame Supply Crate",
				es = "Cajón de suministros de la Llama Hendida",
				de = "Vorratskiste der Splitterflammen",
				fr = "Caisse de fournitures de la Flamme fracturée",
				it = "Cassa di Rifornimenti della Fiamma Frammentata",
				pt = "Caixote de Suprimentos da Chama Partida",
				ru = "Ящик с припасами Расколотого Пламени",
				ko = "분리된 불길 보급품 상자",
				cn = "碎裂之焰补给箱",
			},
		},
	
		[382300] = {
			readable = "Maruukai Supplies",
			model = 4182522,
			text = {
				en = "Maruukai Supplies",
				es = "Suministros de Maruukai",
				de = "Vorräte der Maruukai",
				fr = "Fournitures de Maruukaï",
				it = "Rifornimenti di Maruukai",
				pt = "Suprimentos Maruukai",
				ru = "Припасы Марукай",
				ko = "마루카이 보급품",
				cn = "马鲁凯补给",
			},
		},
	
		[382324] = {
			readable = "Nokhud Supplies",
			model = 4182522,
			text = {
				en = "Nokhud Supplies",
				es = "Suministros Nokhud",
				de = "Vorräte der Nokhud",
				fr = "Fournitures nokhuds",
				it = "Rifornimenti Nokhud",
				pt = "Suprimentos Nokhid",
				ru = "Нокхудские припасы",
				ko = "노쿠드 보급품",
				cn = "诺库德补给",
			},
		},
	
		[382325] = {
			readable = "Onyx Gem Cluster",
			model = 3532362,
			text = {
				en = "Onyx Gem Cluster",
				de = "Onyxedelsteinklumpen",
				fr = "Amas de gemmes d’onyx",
				it = "Formazione di Gemme d'Onice",
				pt = "Drusa de Gemas de Ônix",
				ru = "Друза оникса",
				cn = "玛瑙宝石簇",
			},
		},
	
		[382329] = {
			readable = "Traitor Cage",
			model = 4069153,
			text = {
				en = "Traitor Cage",
				es = "Jaula de traidor",
				de = "Verräterkäfig",
				fr = "Cage de traître",
				it = "Gabbia del Traditore",
				pt = "Jaula de Traição",
				ru = "Клетка предателя",
				ko = "배신자 우리",
				cn = "叛徒牢笼",
			},
		},
	
		[382346] = {
			readable = "Temporal Portal",
			model = 4622368,
			text = {
				en = "Temporal Portal",
				es = "Portal temporal",
				de = "Temporalportal",
				fr = "Portail temporel",
				it = "Portale Temporale",
				pt = "Portal Temporal",
				ru = "Временной портал",
				ko = "시간의 차원문",
				cn = "时光传送门",
			},
		},
	
		[382399] = {
			readable = "Fishing Pole",
			model = 984242,
			text = {
				en = "Fishing Pole",
				es = "Caña de pescar",
				de = "Angelrute",
				fr = "Canne à pêche",
				it = "Canna da Pesca",
				pt = "Vara de Pescar",
				ru = "Удочка",
				ko = "낚싯대",
				cn = "钓鱼竿",
			},
		},
	
		[382594] = {
			readable = "'Good Students' Reward Chest",
			model = 4216698,
			text = {
				en = "'Good Students' Reward Chest",
				es = "Cofre de recompensa de los \"buenos estudiantes\"",
				de = "Belohnungstruhe für 'gute Schüler'",
				fr = "Coffre de gratification des « élèves modèles »",
				it = "Cassa della Ricompensa \"Studenti Bravi\"",
				pt = "Baú de Recompensa dos \"Bons Alunos\"",
				ru = "Сундук с наградой для хороших студентов",
				ko = "'우등생' 보상 보관함",
			},
		},
	
		[382621] = {
			readable = "Revival Catalyst Console",
			icon = 4622448,
			model = 3998636,
			text = {
				en = "Revival Catalyst Console",
				es = "Consola del catalizador de reanimación",
				de = "Belebungskatalysatorkonsole",
				fr = "Console de catalyseur de rétablissement",
				it = "Console del Catalizzatore del Ripristino",
				pt = "Console de Catalisador de Revivescência",
				ru = "Консоль катализатора возрождения",
				ko = "소생의 촉매 장치",
				cn = "复苏化生控制台",
			},
		},
	
		[382622] = {
			readable = "Boat to Iskaara",
			model = 3857145,
			text = {
				en = "Boat to Iskaara",
				es = "Barco a Iskaara",
				de = "Boot nach Iskaara",
				ru = "Лодка, плывущая в Искару",
			},
		},
	
		[382680] = {
			readable = "Sleepyvine Tea",
			model = 4201172,
			text = {
				en = "Sleepyvine Tea",
				es = "Té de parra durmiente",
				de = "Schlafrebentee",
				fr = "Thé de bercevigne",
				it = "Tè del Dolcesonno",
				pt = "Chá de Sonoleia",
				ru = "Чай из сонной лозы",
				ko = "장대꽃 차",
				cn = "瞌睡藤茶",
			},
		},
})
do ObjectDB[objectID] = objectData; end
