local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	
		[375002] = {
			readable = "Force Field",
			model = 4069503,
			text = {
				en = "Force Field",
				es = "Campo de fuerza",
				de = "Kraftfeld",
				fr = "Champ de force",
				it = "Campo di Forza",
				pt = "Campo de Força",
				ru = "Силовое поле",
				ko = "역장",
				cn = "力场",
			},
		},
	
		[375004] = {
			readable = "Ritual Control Scepter",
			model = 4438971,
			text = {
				en = "Ritual Control Scepter",
				de = "Ritualsteuerszepter",
				fr = "Sceptre de contrôle du rituel",
				ru = "Контрольный скипетр ритуала",
				ko = "의식 제어 홀",
			},
		},
	
		[375015] = {
			readable = "Primordial Core",
			model = 4328435,
			text = {
				en = "Primordial Core",
				es = "Núcleo primordial",
				de = "Urzeitlicher Kern",
				fr = "Noyau primordial",
				it = "Nucleo Primordiale",
				pt = "Núcleo Primordial",
				ru = "Извечный сердечник",
				ko = "태고의 핵",
				cn = "原始之核",
			},
		},
	
		[375021] = {
			readable = "Perished Automa",
			model = 353152,
			text = {
				en = "Perished Automa",
				es = "Automa fenecido",
				de = "Zugrunde gegangenes Automa",
				fr = "Automa défunt",
				it = "Automa Defunto",
				pt = "Automa Falecido",
				ru = "Уничтоженный автом",
				ko = "닳디 닳은 자동기계",
				cn = "陨灭的自动体",
			},
		},
	
		[375024] = {
			readable = "Royal Coffers",
			model = 3936821,
			text = {
				en = "Royal Coffers",
				es = "Arcas reales",
				de = "Königliche Kästen",
				fr = "Coffres royaux",
				it = "Scrigni Reali",
				pt = "Cofres Reais",
				ru = "Королевская казна",
				ko = "왕실 궤짝",
			},
		},
	
		[375025] = {
			readable = "Teleporter",
			model = 4196518,
			text = {
				en = "Teleporter",
				es = "Teletransportador",
				fr = "Téléporteur",
				it = "Teletrasporto",
				pt = "Teleportador",
				ru = "Телепорт",
				ko = "순간이동기",
				cn = "传送器",
			},
		},
	
		[375031] = {
			readable = "Cradle of Nascence Door",
			model = 4060176,
			text = {
				en = "Cradle of Nascence Door",
				es = "Puerta de la Cuna del Nacimiento",
				de = "Tür der Wiege der Naszenz",
				fr = "Porte du Berceau des naissances",
				it = "Porta della Culla della Nascita",
				pt = "Porta do Berço da Nascença",
				ru = "Дверь Колыбели Зарождения",
				ko = "신생의 요람 문",
				cn = "初生摇篮之门",
			},
		},
	
		[375042] = {
			readable = "Haven Anima Diverter",
			model = 166432,
			text = {
				en = "Haven Anima Diverter",
				es = "Desviador de ánima del Refugio",
				de = "Animaumleiter der Zuflucht",
				fr = "Déviateur d’anima du Refuge",
				it = "Deviatore d'Animum Empireo",
				pt = "Desviador de Ânima do Refúgio",
				ru = "Анимаотвод Укрытия",
				ko = "안식처 령 전환기",
				cn = "安谧港心能转移器",
			},
		},
	
		[375044] = {
			readable = "Field Anima Diverter",
			model = 166432,
			text = {
				en = "Field Anima Diverter",
				es = "Desviador de ánima de campo",
				de = "Feldanimaumleiter",
				fr = "Déviateur d’anima portable",
				it = "Deviatore d'Animum da Campo",
				pt = "Desviador de Ânima de Campo",
				ru = "Переносной анимаотвод",
				ko = "현장 령 전환기",
				cn = "野战心能转移器",
			},
		},
	
		[375058] = {
			readable = "Toccatian Cache",
			model = 4248045,
			text = {
				en = "Toccatian Cache",
				es = "Alijo de tocata",
				de = "Toccatianische Truhe",
				fr = "Cache toccatienne",
				it = "Cassa Toccatiana",
				pt = "Baú Tocatiano",
				ru = "Токкатийский тайник",
				ko = "토카타 보관함",
				cn = "弹奏宝箱",
			},
		},
	
		[375059] = {
			readable = "Mezzonic Cache",
			model = 4248046,
			text = {
				en = "Mezzonic Cache",
				es = "Alijo mezzónico",
				de = "Mezzonische Truhe",
				fr = "Cache mezzonique",
				it = "Cassa Mezzonica",
				pt = "Baú Mezônico",
				ru = "Меццонийский тайник",
				ko = "메조 보관함",
				cn = "中音宝箱",
			},
		},
	
		[375060] = {
			readable = "Glissandian Cache",
			model = 4248047,
			text = {
				en = "Glissandian Cache",
				es = "Alijo glissandiano",
				de = "Glissandische Truhe",
				fr = "Cache glissandienne",
				it = "Cassa Glissandiana",
				pt = "Baú Glissandiano",
				ru = "Глиссандрийский тайник",
				ko = "글리산도 보관함",
				cn = "滑音宝箱",
			},
		},
	
		[375061] = {
			readable = "Fugueal Cache",
			model = 4248048,
			text = {
				en = "Fugueal Cache",
				es = "Alijo de fuga",
				de = "Fugalische Truhe",
				fr = "Cache fuguéale",
				it = "Cassa Fuguelica",
				pt = "Baú Fugueal",
				ru = "Фугийский тайник",
				ko = "푸가 보관함",
				cn = "赋格宝箱",
			},
		},
	
		[375062] = {
			readable = "Cantaric Cache",
			model = 4248049,
			text = {
				en = "Cantaric Cache",
				es = "Alijo cantárico",
				de = "Kantarische Truhe",
				fr = "Cache cantabilienne",
				it = "Cassa Cantarica",
				pt = "Baú Cantárico",
				ru = "Кантарийский тайник",
				ko = "노래의 보관함",
				cn = "声乐宝箱",
			},
		},
	
		[375064] = {
			readable = "Toccatian Cache",
			model = 4248045,
			text = {
				en = "Toccatian Cache",
				es = "Alijo de tocata",
				de = "Toccatianische Truhe",
				fr = "Cache toccatienne",
				it = "Cassa Toccatiana",
				pt = "Baú Tocatiano",
				ru = "Токкатийский тайник",
				ko = "토카타 보관함",
				cn = "弹奏宝箱",
			},
		},
	
		[375066] = {
			readable = "Mezzonic Cache",
			model = 4248046,
			text = {
				en = "Mezzonic Cache",
				es = "Alijo mezzónico",
				de = "Mezzonische Truhe",
				fr = "Cache mezzonique",
				it = "Cassa Mezzonica",
				pt = "Baú Mezônico",
				ru = "Меццонийский тайник",
				ko = "메조 보관함",
				cn = "中音宝箱",
			},
		},
	
		[375067] = {
			readable = "Glissandian Cache",
			model = 4248047,
			text = {
				en = "Glissandian Cache",
				es = "Alijo glissandiano",
				de = "Glissandische Truhe",
				fr = "Cache glissandienne",
				it = "Cassa Glissandiana",
				pt = "Baú Glissandiano",
				ru = "Глиссандрийский тайник",
				ko = "글리산도 보관함",
				cn = "滑音宝箱",
			},
		},
	
		[375068] = {
			readable = "Fugueal Cache",
			model = 4248048,
			text = {
				en = "Fugueal Cache",
				es = "Alijo de fuga",
				de = "Fugalische Truhe",
				fr = "Cache fuguéale",
				it = "Cassa Fuguelica",
				pt = "Baú Fugueal",
				ru = "Фугийский тайник",
				ko = "푸가 보관함",
				cn = "赋格宝箱",
			},
		},
	
		[375069] = {
			readable = "Cantaric Cache",
			model = 4248049,
			text = {
				en = "Cantaric Cache",
				es = "Alijo cantárico",
				de = "Kantarische Truhe",
				fr = "Cache cantabilienne",
				it = "Cassa Cantarica",
				pt = "Baú Cantárico",
				ru = "Кантарийский тайник",
				ko = "노래의 보관함",
				cn = "声乐宝箱",
			},
		},
	
		[375070] = {
			readable = "Teleporter",
			model = 4196518,
			text = {
				en = "Teleporter",
				es = "Teletransportador",
				fr = "Téléporteur",
				it = "Teletrasporto",
				pt = "Teleportador",
				ru = "Телепорт",
				ko = "순간이동기",
				cn = "传送器",
			},
		},
	
		[375071] = {
			readable = "Lush Nightshade",
			model = 3684822,
			text = {
				en = "Lush Nightshade",
				es = "Sombranoche exuberante",
				de = "Üppiger Nachtschatten",
				fr = "Belladone luxuriante",
				it = "Ombranotte Rigogliosa",
				pt = "Beladona Vistosa",
				ru = "Пышная беладонна",
				ko = "무성한 밤그늘",
				cn = "繁茂的夜影花",
			},
		},
	
		[375093] = {
			readable = "Stone Soup",
			model = 4236950,
			text = {
				en = "Stone Soup",
				es = "Sopa de piedras",
				de = "Steinsuppe",
				fr = "Soupe de cailloux",
				it = "Zuppa di Sassi",
				pt = "Sopa de Pedra",
				ru = "Каменный суп",
				ko = "돌멩이 수프",
				cn = "石头汤",
			},
		},
	
		[375094] = {
			readable = "Portal to Haven",
			model = 166523,
			text = {
				en = "Portal to Haven",
				es = "Portal al Refugio",
				de = "Portal zur Zuflucht",
				fr = "Portail vers le Refuge",
				it = "Portale per l'Empireo",
				pt = "Portal do Refúgio",
				ru = "Портал в Укрытие",
				ko = "안식처로 통하는 차원문",
				cn = "前往安谧港的传送门",
			},
		},
	
		[375096] = {
			readable = "Death Blossom",
			model = 3501540,
			text = {
				en = "Death Blossom",
				es = "Estrella mortal",
				de = "Todesblüte",
				fr = "Fatalée",
				it = "Bocciolo di Morte",
				pt = "Botão-da-morte",
				ru = "Смертоцвет",
				ko = "죽음의 꽃",
				cn = "绽亡花",
			},
		},
	
		[375097] = {
			readable = "Nightshade",
			model = 3684822,
			text = {
				en = "Nightshade",
				es = "Sombranoche",
				de = "Nachtschatten",
				fr = "Belladone",
				it = "Ombranotte",
				pt = "Beladona",
				ru = "Беладонна",
				ko = "밤그늘",
				cn = "夜影花",
			},
		},
	
		[375099] = {
			readable = "Death Blossom",
			model = 3501539,
			text = {
				en = "Death Blossom",
				es = "Estrella mortal",
				de = "Todesblüte",
				fr = "Fatalée",
				it = "Bocciolo di Morte",
				pt = "Botão-da-morte",
				ru = "Смертоцвет",
				ko = "죽음의 꽃",
				cn = "绽亡花",
			},
		},
	
		[375100] = {
			readable = "Death Blossom",
			model = 3501538,
			text = {
				en = "Death Blossom",
				es = "Estrella mortal",
				de = "Todesblüte",
				fr = "Fatalée",
				it = "Bocciolo di Morte",
				pt = "Botão-da-morte",
				ru = "Смертоцвет",
				ko = "죽음의 꽃",
				cn = "绽亡花",
			},
		},
	
		[375101] = {
			readable = "Death Blossom",
			model = 3501537,
			text = {
				en = "Death Blossom",
				es = "Estrella mortal",
				de = "Todesblüte",
				fr = "Fatalée",
				it = "Bocciolo di Morte",
				pt = "Botão-da-morte",
				ru = "Смертоцвет",
				ko = "죽음의 꽃",
				cn = "绽亡花",
			},
		},
	
		[375102] = {
			readable = "The Cure",
			model = 4209021,
			text = {
				en = "The Cure",
				fr = "Le remède",
				ru = "Лекарство",
			},
		},
	
		[375103] = {
			readable = "What Aspects Fear",
			model = 4209021,
			text = {
				en = "What Aspects Fear",
				de = "Was Aspekte fürchten",
				fr = "Ce que craignent les Aspects",
				ru = "То, чего страшатся Аспекты",
				ko = "위상이 두려워하는 것",
			},
		},
	
		[375104] = {
			readable = "The Vault",
			model = 4209021,
			text = {
				en = "The Vault",
				de = "Die Schatzkammer",
				fr = "Le caveau",
				ru = "Хранилище",
				ko = "금고",
			},
		},
	
		[375106] = {
			readable = "Instructional Bit",
			model = 4039278,
			text = {
				en = "Instructional Bit",
				es = "Píldora instructiva",
				de = "Instruktionselement",
				fr = "Fragment instructif",
				it = "Pezzetto Informativo",
				pt = "Pílula Instrutiva",
				ru = "Частичка знаний",
				ko = "유익한 정보",
				cn = "有教导性的碎片",
			},
		},
	
		[375108] = {
			readable = "Percolation Array",
			model = 3923426,
			text = {
				en = "Percolation Array",
				es = "Matriz de filtración",
				de = "Filtrationsanlage",
				fr = "Matrice de percolation",
				it = "Matrice di Filtrazione",
				pt = "Matriz de Percolação",
				ru = "Матрица фильтрации",
				ko = "삼투 배열 장치",
				cn = "渗流阵列",
			},
		},
	
		[375126] = {
			readable = "Resonant Echoism",
			model = 4196520,
			text = {
				en = "Resonant Echoism",
				es = "Onomatopeya resonante",
				de = "Resonante Lautmalerei",
				fr = "Échométrie résonnante",
				it = "Eco Risonante",
				pt = "Ecoismo Ressonante",
				ru = "Звукоподражательный резонанс",
				ko = "공명의 메아리",
				cn = "共振拟声",
			},
		},
	
		[375178] = {
			readable = "Orb Fragments",
			model = 3923443,
			text = {
				en = "Orb Fragments",
				es = "Fragmentos de orbe",
				de = "Kugelfragmente",
				fr = "Fragments d’orbe",
				it = "Frammenti di Globo",
				pt = "Fragmentos de Orbe",
				ru = "Фрагменты сферы",
				ko = "보주 파편",
				cn = "宝珠碎片",
			},
		},
	
		[375179] = {
			readable = "Orb Fragments",
			model = 3923444,
			text = {
				en = "Orb Fragments",
				es = "Fragmentos de orbe",
				de = "Kugelfragmente",
				fr = "Fragments d’orbe",
				it = "Frammenti di Globo",
				pt = "Fragmentos de Orbe",
				ru = "Фрагменты сферы",
				ko = "보주 파편",
				cn = "宝珠碎片",
			},
		},
	
		[375180] = {
			readable = "Orb Fragments",
			model = 3923445,
			text = {
				en = "Orb Fragments",
				es = "Fragmentos de orbe",
				de = "Kugelfragmente",
				fr = "Fragments d’orbe",
				it = "Frammenti di Globo",
				pt = "Fragmentos de Orbe",
				ru = "Фрагменты сферы",
				ko = "보주 파편",
				cn = "宝珠碎片",
			},
		},
	
		[375182] = {
			readable = "Feather-Plucker 3300 Gasket",
			model = 950732,
			text = {
				en = "Feather-Plucker 3300 Gasket",
				es = "Junta del Desplumeitor 3300",
				de = "Dichtung für den Federrupfer 3300",
				fr = "Joint de super-plumeur 3300",
				it = "Guarnizione dello Spiumatore 3300",
				pt = "Gaxeta do Ranca-pena 3300",
				ru = "Манжета от \"Перощипа 3300\"",
				ko = "깃털 뽑개 3300 마개",
			},
		},
	
		[375183] = {
			readable = "Feather-Plucker 3300 Bolts",
			model = 1842503,
			text = {
				en = "Feather-Plucker 3300 Bolts",
				es = "Tornillos del Desplumeitor 3300",
				de = "Bolzen für den Federrupfer 3300",
				fr = "Boulons de super-plumeur 3300",
				it = "Bulloni dello Spiumatore 3300",
				pt = "Parafusos do Ranca-pena 3300",
				ru = "Болты от \"Перощипа 3300\"",
				ko = "깃털 뽑개 3300 나사",
			},
		},
	
		[375184] = {
			readable = "Feather-Plucker 3300 Exhaust Pipe",
			model = 2348396,
			text = {
				en = "Feather-Plucker 3300 Exhaust Pipe",
				es = "Tubo de escape del Desplumeitor 3300",
				de = "Auspuffrohr für den Federrupfer 3300",
				fr = "Pot d’échappement de super-plumeur 3300",
				it = "Condotto di Scarico dello Spiumatore 3300",
				pt = "Cano de Descarga do Ranca-pena 3300",
				ru = "Выхлопная труба от \"Перощипа 3300\"",
				ko = "깃털 뽑개 3300 배출관",
				cn = "拔羽器3300型的排气管",
			},
		},
	
		[375188] = {
			readable = "Camber Alcove Arrangement",
			model = 4081526,
			text = {
				en = "Camber Alcove Arrangement",
				es = "Disposición de la Alcoba Combada",
				de = "Anordnung des Gewölbten Alkovens",
				fr = "Agencement de l’alcôve Concave",
				it = "Disposizione dell'Alcova della Curvatura",
				pt = "Arranjo da Alcova Arqueada",
				ru = "Конфигурация выступающего алькова",
				ko = "솟아난 벽감 정렬",
				cn = "拱曲凹室指向",
			},
		},
	
		[375189] = {
			readable = "Repertory Alcove Arrangement",
			model = 4081527,
			text = {
				en = "Repertory Alcove Arrangement",
				es = "Disposición de la Alcoba de Repertorio",
				de = "Anordnung des Bereichernden Alkovens",
				fr = "Agencement de l’alcôve du Répertoire",
				it = "Disposizione dell'Alcova del Repertorio",
				pt = "Arranjo da Alcova do Repertório",
				ru = "Конфигурация постоянного алькова",
				ko = "시초의 벽감 정렬",
				cn = "储备凹室指向",
			},
		},
	
		[375190] = {
			readable = "Rondure Alcove Arrangement",
			model = 4081530,
			text = {
				en = "Rondure Alcove Arrangement",
				es = "Disposición de la Alcoba Circular",
				de = "Anordnung des Runden Alkovens",
				fr = "Agencement de l’alcôve Incurvée",
				it = "Disposizione dell'Alcova Rotonda",
				pt = "Arranjo da Alcova Circular",
				ru = "Конфигурация округлого алькова",
				ko = "구체의 벽감 정렬",
				cn = "圆弧凹室指向",
			},
		},
	
		[375191] = {
			readable = "Dormant Alcove Arrangement",
			model = 4081531,
			text = {
				en = "Dormant Alcove Arrangement",
				es = "Disposición de la Alcoba Durmiente",
				de = "Anordnung des Inaktiven Alkovens",
				fr = "Agencement de l’alcôve Dormante",
				it = "Disposizione dell'Alcova Dormiente",
				pt = "Arranjo da Alcova Dormente",
				ru = "Конфигурация дремлющего алькова",
				ko = "휴면의 벽감 정렬",
				cn = "休眠凹室指向",
			},
		},
	
		[375192] = {
			readable = "Fulgore Alcove Arrangement",
			model = 4081535,
			text = {
				en = "Fulgore Alcove Arrangement",
				es = "Disposición de la Alcoba Refulgente",
				de = "Anordnung des Prächtigen Alkovens",
				fr = "Agencement de l’alcôve Aveuglante",
				it = "Disposizione dell'Alcova Fulgida",
				pt = "Arranjo da Alcova Fulgurante",
				ru = "Конфигурация ослепительного алькова",
				ko = "광휘의 벽감 정렬",
				cn = "灿烂凹室指向",
			},
		},
	
		[375193] = {
			readable = "Locus Shift",
			model = 4224814,
			text = {
				en = "Locus Shift",
				es = "Cambio de enclave",
				de = "Locusverschiebung",
				fr = "Transfert de locus",
				it = "Cambio di Locus",
				pt = "Deslocamento de Lócus",
				ru = "Сдвиг Локуса",
				ko = "공간 변환",
			},
		},
	
		[375205] = {
			readable = "Toccatian Cache",
			model = 4248045,
			text = {
				en = "Toccatian Cache",
				es = "Alijo de tocata",
				de = "Toccatianische Truhe",
				fr = "Cache toccatienne",
				it = "Cassa Toccatiana",
				pt = "Baú Tocatiano",
				ru = "Токкатийский тайник",
				ko = "토카타 보관함",
				cn = "弹奏宝箱",
			},
		},
	
		[375207] = {
			readable = "Mezzonic Cache",
			model = 4248046,
			text = {
				en = "Mezzonic Cache",
				es = "Alijo mezzónico",
				de = "Mezzonische Truhe",
				fr = "Cache mezzonique",
				it = "Cassa Mezzonica",
				pt = "Baú Mezônico",
				ru = "Меццонийский тайник",
				ko = "메조 보관함",
				cn = "中音宝箱",
			},
		},
	
		[375208] = {
			readable = "Glissandian Cache",
			model = 4248047,
			text = {
				en = "Glissandian Cache",
				es = "Alijo glissandiano",
				de = "Glissandische Truhe",
				fr = "Cache glissandienne",
				it = "Cassa Glissandiana",
				pt = "Baú Glissandiano",
				ru = "Глиссандрийский тайник",
				ko = "글리산도 보관함",
				cn = "滑音宝箱",
			},
		},
	
		[375209] = {
			readable = "Fugueal Cache",
			model = 4248048,
			text = {
				en = "Fugueal Cache",
				es = "Alijo de fuga",
				de = "Fugalische Truhe",
				fr = "Cache fuguéale",
				it = "Cassa Fuguelica",
				pt = "Baú Fugueal",
				ru = "Фугийский тайник",
				ko = "푸가 보관함",
				cn = "赋格宝箱",
			},
		},
	
		[375210] = {
			readable = "Cantaric Cache",
			model = 4248049,
			text = {
				en = "Cantaric Cache",
				es = "Alijo cantárico",
				de = "Kantarische Truhe",
				fr = "Cache cantabilienne",
				it = "Cassa Cantarica",
				pt = "Baú Cantárico",
				ru = "Кантарийский тайник",
				ko = "노래의 보관함",
				cn = "声乐宝箱",
			},
		},
	
		[375211] = {
			readable = "Locrian Swale",
			model = 4224815,
			text = {
				en = "Locrian Swale",
				es = "Zanja de Locris",
				de = "Lokrische Senke",
				fr = "Noue locrienne",
				it = "Striscia di Locrian",
				pt = "Vala Locriana",
				ru = "Локрийская призма",
				ko = "로크리아 마력석",
				cn = "音室引槽",
			},
		},
	
		[375222] = {
			readable = "Protoform Tool",
			model = 4196527,
			text = {
				en = "Protoform Tool",
				es = "Herramienta protoforma",
				de = "Protoformwerkzeug",
				fr = "Outil de protoformation",
				it = "Attrezzo Protoforma",
				pt = "Ferramenta de Protoforma",
				ru = "Инструмент протосинтеза",
				ko = "원생형태 도구",
				cn = "原生体工具",
			},
		},
	
		[375223] = {
			readable = "Repository Vault",
			model = 4196522,
			text = {
				en = "Repository Vault",
				es = "Cámara del repositorio",
				de = "Repositoriumsarchiv",
				fr = "Caveau de dépôt",
				it = "Scrigno del Deposito",
				pt = "Câmara de Reposição",
				ru = "Хранилище репозитория",
				ko = "보관소 금고",
				cn = "贮藏所宝箱",
			},
		},
	
		[375224] = {
			readable = "Ingress Override",
			model = 4081706,
			text = {
				en = "Ingress Override",
				es = "Anulador de acceso",
				de = "Zugangsumgehung",
				fr = "Code d’accès",
				it = "Annullamento Ingresso",
				pt = "Sobreposição de Entrada",
				ru = "Отмена доступа",
				ko = "입장 비상 정지",
				cn = "准入超控装置",
			},
		},
	
		[375227] = {
			readable = "Protoform Catalyst",
			model = 3923440,
			text = {
				en = "Protoform Catalyst",
				es = "Catalizador de protoforma",
				de = "Protoformkatalysator",
				fr = "Catalyseur protoformel",
				it = "Catalizzatore Protoforma",
				pt = "Catalisador de Protoforma",
				ru = "Катализатор протосинтеза",
				ko = "원생형태 촉매",
				cn = "原生体化生器",
			},
		},
	
		[375234] = {
			readable = "Hardened Draconium Deposit",
			model = 4572361,
			text = {
				en = "Hardened Draconium Deposit",
				es = "Depósito de draconio endurecido",
				de = "Gehärtetes Drakoniumvorkommen",
				fr = "Gisement de draconium durci",
				it = "Deposito Indurito di Draconium",
				pt = "Depósito de Dracônio Endurecido",
				ru = "Залежи каменистого драконита",
				ko = "굳은 드라코니움 광맥",
				cn = "硬化龙银矿脉",
			},
		},
	
		[375235] = {
			readable = "Molten Draconium Deposit",
			model = 4572358,
			text = {
				en = "Molten Draconium Deposit",
				es = "Depósito de draconio fundido",
				de = "Geschmolzenes Drakoniumvorkommen",
				fr = "Gisement de draconium fondu",
				it = "Deposito Fuso di Draconium",
				pt = "Depósito de Dracônio Derretido",
				ru = "Залежи раскаленного драконита",
				ko = "녹아내린 드라코니움 광맥",
				cn = "熔火龙银矿脉",
			},
		},
	
		[375238] = {
			readable = "Titan-Touched Draconium Deposit",
			model = 4572359,
			text = {
				en = "Titan-Touched Draconium Deposit",
				es = "Depósito de draconio tocado por los titanes",
				de = "Titanversetztes Drakoniumvorkommen",
				fr = "Gisement de draconium touché par les Titans",
				it = "Deposito Toccato dai Titani di Draconium",
				pt = "Depósito de Dracônio Tocado por Titãs",
				ru = "Залежи драконита, осененного титанами",
				ko = "티탄에 물든 드라코니움 광맥",
				cn = "泰坦点化的龙银矿脉",
			},
		},
	
		[375239] = {
			readable = "Primal Draconium Deposit",
			model = 4572360,
			text = {
				en = "Primal Draconium Deposit",
				es = "Depósito de draconio primigenio",
				de = "Urdrakoniumvorkommen",
				fr = "Gisement de draconium primordial",
				it = "Deposito Primordiale di Draconium",
				pt = "Depósito de Dracônio Primevo",
				ru = "Залежи изначального драконита",
				ko = "원시 드라코니움 광맥",
				cn = "原始龙银矿脉",
			},
		},
	
		[375240] = {
			readable = "Infurious Draconium Deposit",
			model = 4572362,
			text = {
				en = "Infurious Draconium Deposit",
				es = "Depósito de draconio furioso",
				de = "Wutentbranntes Drakoniumvorkommen",
				fr = "Gisement de draconium ardent",
				it = "Deposito Impetuoso di Draconium",
				pt = "Depósito de Dracônio em Fúria",
				ru = "Залежи ярого драконита",
				ko = "분노의 드라코니움 광맥",
			},
		},
	
		[375241] = {
			readable = "Bubble Poppy",
			model = 4498019,
			text = {
				en = "Bubble Poppy",
				es = "Amapola burbuja",
				de = "Blasenmohn",
				fr = "Pavot à bulle",
				it = "Papavero Bolla",
				pt = "Papoula Borbulhante",
				ru = "Пузырчатый мак",
				ko = "거품 백일홍",
				cn = "泡粟花",
			},
		},
	
		[375242] = {
			readable = "Titan-Touched Bubble Poppy",
			model = 4498019,
			text = {
				en = "Titan-Touched Bubble Poppy",
				es = "Amapola burbuja tocada por los titanes",
				de = "Titanenberührter Blasenmohn",
				fr = "Pavot à bulle touché par les Titans",
				it = "Papavero Bolla Toccato dai Titani",
				pt = "Papoula Borbulhante Tocada por Titãs",
				ru = "Осененный титанами пузырчатый мак",
				ko = "티탄에 물든 거품 백일홍",
				cn = "泰坦点化的泡粟花",
			},
		},
	
		[375243] = {
			readable = "Infurious Bubble Poppy",
			model = 4498019,
			text = {
				en = "Infurious Bubble Poppy",
				es = "Amapola burbuja furiosa",
				de = "Wutentbrannter Blasenmohn",
				fr = "Pavot à bulle ardent",
				it = "Papavero Bolla Impetuoso",
				pt = "Papoula Borbulhante em Fúria",
				ru = "Ярый пузырчатый мак",
				ko = "분노의 거품 백일홍",
			},
		},
	
		[375244] = {
			readable = "Frigid Bubble Poppy",
			model = 4498019,
			text = {
				en = "Frigid Bubble Poppy",
				es = "Amapola burbuja gélida",
				de = "Eisiger Blasenmohn",
				fr = "Pavot à bulle algide",
				it = "Papavero Bolla Gelato",
				pt = "Papoula Borbulhante Frígida",
				ru = "Морозный пузырчатый мак",
				ko = "혹한의 거품 백일홍",
				cn = "冷冽泡粟花",
			},
		},
	
		[375245] = {
			readable = "Windswept Bubble Poppy",
			model = 4498019,
			text = {
				en = "Windswept Bubble Poppy",
				es = "Amapola burbuja aventada",
				de = "Windgepeitschter Blasenmohn",
				fr = "Pavot à bulle balayé par le vent",
				it = "Papavero Bolla Scompigliato",
				pt = "Papoula Borbulhante Levada pelo Vento",
				ru = "Обветренный пузырчатый мак",
				ko = "바람결 거품 백일홍",
				cn = "啸风泡粟花",
			},
		},
	
		[375246] = {
			readable = "Decayed Bubble Poppy",
			model = 4498020,
			text = {
				en = "Decayed Bubble Poppy",
				es = "Amapola burbuja descompuesta",
				de = "Verrotteter Blasenmohn",
				fr = "Pavot à bulle décomposé",
				it = "Papavero Bolla Decaduto",
				pt = "Papoula Borbulhante Decrépita",
				ru = "Сгнивший пузырчатый мак",
				ko = "부패한 거품 백일홍",
				cn = "腐朽泡粟花",
			},
		},
	
		[375266] = {
			readable = "Rotting Sap",
			model = 4248599,
			text = {
				en = "Rotting Sap",
				es = "Savia putrefacta",
				de = "Modernder Saft",
				fr = "Sève putrescente",
				ru = "Прогнивший сок",
				ko = "부패하는 수액",
			},
		},
	
		[375270] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375272] = {
			readable = "Mawsworn Cache",
			model = 3677216,
			text = {
				en = "Mawsworn Cache",
				es = "Alijo jurafauces",
				de = "Schlundgebundene Truhe",
				fr = "Cache antrelige",
				it = "Scrigno dei Giurafauce",
				pt = "Cabedal Górjuro",
				ru = "Тайник Верных Утробе",
				ko = "나락살이 보관함",
				cn = "渊誓之箱",
			},
		},
	
		[375281] = {
			readable = "Stolen Relic",
			model = 3925326,
			text = {
				en = "Stolen Relic",
				es = "Reliquia robada",
				de = "Gestohlenes Relikt",
				fr = "Relique volée",
				it = "Reliquia Rubata",
				pt = "Relíquia Roubada",
				ru = "Украденная реликвия",
				ko = "도둑맞은 유물",
				cn = "失窃的圣物",
			},
		},
	
		[375282] = {
			readable = "Mawsteel Shard",
			model = 4253903,
			text = {
				en = "Mawsteel Shard",
				es = "Esquirla de acero de Las Fauces",
				de = "Schlundstahlsplitter",
				fr = "Éclat d’antracier",
				it = "Scheggia di Fauciacciaio",
				pt = "Estilhaço de Aço-da-gorja",
				ru = "Осколок стали Утробы",
				ko = "나락강철 조각",
				cn = "渊钢碎片",
			},
		},
	
		[375283] = {
			readable = "Percolation Array",
			model = 3923426,
			text = {
				en = "Percolation Array",
				es = "Matriz de filtración",
				de = "Filtrationsanlage",
				fr = "Matrice de percolation",
				it = "Matrice di Filtrazione",
				pt = "Matriz de Percolação",
				ru = "Матрица фильтрации",
				ko = "삼투 배열 장치",
				cn = "渗流阵列",
			},
		},
	
		[375284] = {
			readable = "Mawsteel Shard",
			model = 4253903,
			text = {
				en = "Mawsteel Shard",
				es = "Esquirla de acero de Las Fauces",
				de = "Schlundstahlsplitter",
				fr = "Éclat d’antracier",
				it = "Scheggia di Fauciacciaio",
				pt = "Estilhaço de Aço-da-gorja",
				ru = "Осколок стали Утробы",
				ko = "나락강철 조각",
				cn = "渊钢碎片",
			},
		},
	
		[375285] = {
			readable = "Mawsteel Shard",
			model = 4253903,
			text = {
				en = "Mawsteel Shard",
				es = "Esquirla de acero de Las Fauces",
				de = "Schlundstahlsplitter",
				fr = "Éclat d’antracier",
				it = "Scheggia di Fauciacciaio",
				pt = "Estilhaço de Aço-da-gorja",
				ru = "Осколок стали Утробы",
				ko = "나락강철 조각",
				cn = "渊钢碎片",
			},
		},
	
		[375286] = {
			readable = "Mawsteel Shard",
			model = 4253903,
			text = {
				en = "Mawsteel Shard",
				es = "Esquirla de acero de Las Fauces",
				de = "Schlundstahlsplitter",
				fr = "Éclat d’antracier",
				it = "Scheggia di Fauciacciaio",
				pt = "Estilhaço de Aço-da-gorja",
				ru = "Осколок стали Утробы",
				ko = "나락강철 조각",
				cn = "渊钢碎片",
			},
		},
	
		[375287] = {
			readable = "Crystallized Bolstering Spheroid",
			model = 166432,
			text = {
				en = "Crystallized Bolstering Spheroid",
				es = "Esferoide reforzador cristalizado",
				de = "Kristallisierte anstachelnde Sphäre",
				fr = "Sphéroïde de renforcement cristallisé",
				it = "Sferoide di Rinforzo Cristallizzato",
				pt = "Esferoide Encorajador Cristalizado",
				ru = "Кристаллизированная усиливающая сфера",
				ko = "수정 강화 회전체",
				cn = "晶脉强固球状体",
			},
		},
	
		[375290] = {
			readable = "Cypher Bound Chest",
			model = 4196523,
			text = {
				en = "Cypher Bound Chest",
				es = "Cofre vinculado a una clave",
				de = "Chiffrengebundene Truhe",
				fr = "Coffre lié par un cryptogramme",
				it = "Cassa Vincolata al Codice",
				pt = "Baú Travado por Cifra",
				ru = "Защищенный шифром сундук",
				ko = "암호결속 상자",
				cn = "密文束缚的宝箱",
			},
		},
	
		[375331] = {
			readable = "Elusive Progenium Deposit",
			model = 4182224,
			text = {
				en = "Elusive Progenium Deposit",
				es = "Depósito de progenio esquivo",
				de = "Flüchtiges Progeniumvorkommen",
				fr = "Gisement de progénium rarissime",
				it = "Deposito di Progenio Sfuggevole",
				pt = "Depósito de Progenium Esquivo",
				ru = "Ускользающие залежи эфемеры",
				ko = "교묘함의 창시석 광맥",
				cn = "隐秘的先磷矿脉",
			},
		},
	
		[375332] = {
			readable = "Elusive Rich Progenium Deposit",
			model = 4182225,
			text = {
				en = "Elusive Rich Progenium Deposit",
				es = "Depósito rico en progenio esquivo",
				de = "Flüchtiges reiches Progeniumvorkommen",
				fr = "Riche gisement de progénium rarissime",
				it = "Deposito Ricco di Progenio Sfuggevole",
				pt = "Depósito de Progenium Esquivo Abundante",
				ru = "Ускользающие богатые залежи эфемеры",
				ko = "교묘함의 풍부한 창시석 광맥",
				cn = "隐秘的富先磷矿脉",
			},
		},
	
		[375333] = {
			readable = "Elusive Rich Elethium Deposit",
			model = 3669080,
			text = {
				en = "Elusive Rich Elethium Deposit",
				es = "Depósito rico en eletio esquivo",
				de = "Flüchtiges reiches Elethiumvorkommen",
				fr = "Riche gisement d’éléthium rarissime",
				it = "Deposito Ricco di Elezio Sfuggevole",
				pt = "Depósito de Elétio Esquivo Abundante",
				ru = "Ускользающие богатые залежи элетия",
				ko = "교묘함의 풍부한 엘레튬 광맥",
				cn = "隐秘的富阴铁矿脉",
			},
		},
	
		[375337] = {
			readable = "Elusive First Flower",
			model = 4080349,
			text = {
				en = "Elusive First Flower",
				es = "Primera flor esquiva",
				de = "Flüchtige Erste Blume",
				fr = "Fondalée rarissime",
				it = "Primo Fiore Sfuggevole",
				pt = "Primeira Flor Esquiva",
				ru = "Ускользающий первоцвет",
				ko = "교묘함의 태초의 꽃",
				cn = "隐秘的初蕊花",
			},
		},
	
		[375338] = {
			readable = "Elusive Nightshade",
			model = 3684822,
			text = {
				en = "Elusive Nightshade",
				es = "Sombranoche esquiva",
				de = "Flüchtiger Nachtschatten",
				fr = "Belladone rarissime",
				it = "Ombranotte Sfuggevole",
				pt = "Beladona Esquiva",
				ru = "Ускользающая белладонна",
				ko = "교묘함의 밤그늘",
				cn = "隐秘的夜影花",
			},
		},
	
		[375340] = {
			readable = "Lush Elusive First Flower",
			model = 4218043,
			text = {
				en = "Lush Elusive First Flower",
				es = "Primera flor esquiva exuberante",
				de = "Üppige flüchtige Erste Blume",
				fr = "Fondalée luxuriante rarissime",
				it = "Primo Fiore Lussureggiante Sfuggevole",
				pt = "Primeira Flor Esquiva Vicejante",
				ru = "Пышный ускользающий первоцвет",
				ko = "무성한 교묘함의 태초의 꽃",
				cn = "繁茂而隐秘的初蕊花",
			},
		},
	
		[375341] = {
			readable = "Lush Elusive Nightshade",
			model = 3684822,
			text = {
				en = "Lush Elusive Nightshade",
				es = "Sombranoche esquiva exuberante",
				de = "Üppiger flüchtiger Nachtschatten",
				fr = "Belladone luxuriante rarissime",
				it = "Ombranotte Lussureggiante Sfuggevole",
				pt = "Beladona Esquiva Vicejante",
				ru = "Пышная ускользающая белладонна",
				ko = "무성한 교묘함의 밤그늘",
				cn = "繁茂而隐秘的夜影花",
			},
		},
	
		[375354] = {
			readable = "Domination Cache",
			model = 3677216,
			text = {
				en = "Domination Cache",
				es = "Alijo de dominación",
				de = "Herrschaftstruhe",
				fr = "Cache de domination",
				it = "Scrigno del Dominio",
				pt = "Depósito da Dominação",
				ru = "Тайник Господства",
				ko = "지배의 보관함",
				cn = "统御之箱",
			},
		},
	
		[375362] = {
			readable = "Avian Nest",
			model = 1003213,
			text = {
				en = "Avian Nest",
				es = "Nido aviario",
				de = "Ornidennest",
				fr = "Nid d’oiseau",
				it = "Nido di Aviano",
				pt = "Ninho de Avícola",
				ru = "Гнездо авиана",
				ko = "새 둥지",
				cn = "元鸟之巢",
			},
		},
	
		[375363] = {
			readable = "Mawsworn Supply Chest",
			model = 3677216,
			text = {
				en = "Mawsworn Supply Chest",
				es = "Cofre de suministros jurafauces",
				de = "Schlundgebundene Vorratstruhe",
				fr = "Coffre de fournitures antreliges",
				it = "Cassa di Rifornimenti dei Giurafauce",
				pt = "Baú de Suprimentos Górjuro",
				ru = "Сундук с припасами Верных Утробе",
				ko = "나락살이 보급품 상자",
				cn = "渊誓补给宝箱",
			},
		},
	
		[375366] = {
			readable = "Tarachnid Eggs",
			model = 915963,
			text = {
				en = "Tarachnid Eggs",
				es = "Huevos de tarácnido",
				de = "Tarachnideneier",
				fr = "Œufs de tarachnidé",
				it = "Uova di Taracnide",
				pt = "Ovos de Taracnídeo",
				ru = "Яйца тарахнидов",
				ko = "원시거미 알",
				cn = "元蛛卵",
			},
		},
	
		[375368] = {
			readable = "Creation Catalyst Console",
			icon = 4216936,
			model = 3923426,
			text = {
				en = "Creation Catalyst Console",
				es = "Consola de catalizador de creación",
				de = "Schöpfungskatalysatorkonsole",
				fr = "Console de catalyseur de création",
				it = "Console del Catalizzatore della Creazione",
				pt = "Console de Catalisador de Criação",
				ru = "Консоль катализатора творения",
				ko = "창조의 촉매 장치",
				cn = "造物化生控制台",
			},
		},
	
		[375369] = {
			readable = "Gnawed Valise",
			model = 3846065,
			text = {
				en = "Gnawed Valise",
				es = "Valija mordisqueada",
				de = "Angenagter Handkoffer",
				fr = "Malle rongée",
				it = "Borsa Morsicata",
				pt = "Valise Roída",
				ru = "Изгрызенная сумка",
				ko = "갉아먹은 가방",
				cn = "被咬过的旅行袋",
			},
		},
	
		[375370] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375371] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375373] = {
			readable = "Discarded Automa Scrap",
			model = 4201719,
			text = {
				en = "Discarded Automa Scrap",
				es = "Chatarra de Automa desechada",
				de = "Weggeworfener Automaschrott",
				fr = "Débris d’Automa abandonné",
				it = "Pezzo di Automa Scartato",
				pt = "Sucata de Automa Descartada",
				ru = "Выброшенные обломки автома",
				ko = "버려진 자동기계 고철",
				cn = "被抛弃的自动体残片",
			},
		},
	
		[375376] = {
			readable = "Fallen Vault",
			model = 4198154,
			text = {
				en = "Fallen Vault",
				es = "Caja fuerte caída",
				de = "Gefallenes Gewölbe",
				fr = "Caveau déchu",
				it = "Cassaforte Caduta",
				pt = "Cofre dos Caídos",
				ru = "Хранилище Павших",
				ko = "몰락한 금고",
				cn = "陨落宝箱",
			},
		},
	
		[375377] = {
			readable = "Forgotten Translocator",
			model = 3923427,
			text = {
				en = "Forgotten Translocator",
				es = "Trasladador olvidado",
				de = "Vergessener Translokator",
				fr = "Transposeur oublié",
				it = "Traslocatore Dimenticato",
				pt = "Translocador Esquecido",
				ru = "Забытый транслокатор",
				ko = "잊힌 위치변환기",
				cn = "被遗忘的传送器",
			},
		},
	
		[375382] = {
			readable = "Crushed Supply Crate",
			model = 4261537,
			text = {
				en = "Crushed Supply Crate",
				es = "Cajón de suministros destrozado",
				de = "Zerschmetterte Vorratskiste",
				fr = "Caisse de fournitures écrasée",
				it = "Cassa di Rifornimenti Frantumata",
				pt = "Caixote de Suprimentos Esmagado",
				ru = "Раздавленный ящик с припасами",
				ko = "으스러진 보급품 상자",
				cn = "被压坏的补给箱",
			},
		},
	
		[375383] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375384] = {
			readable = "Fallen Rock",
			model = 3605394,
			text = {
				en = "Fallen Rock",
				es = "Roca desprendida",
				de = "Herabgestürzter Fels",
				fr = "Rocher effondré",
				it = "Roccia Caduta",
				pt = "Rocha Caída",
				ru = "Упавший камень",
				ko = "떨어진 바위",
				cn = "掉落的岩石",
			},
		},
	
		[375385] = {
			readable = "Fallen Rock",
			model = 3605393,
			text = {
				en = "Fallen Rock",
				es = "Roca desprendida",
				de = "Herabgestürzter Fels",
				fr = "Rocher effondré",
				it = "Roccia Caduta",
				pt = "Rocha Caída",
				ru = "Упавший камень",
				ko = "떨어진 바위",
				cn = "掉落的岩石",
			},
		},
	
		[375387] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375388] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375389] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375390] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375391] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375392] = {
			readable = "Repair Tool",
			model = 4273120,
			text = {
				en = "Repair Tool",
				es = "Herramienta de reparación",
				de = "Reparaturwerkzeug",
				fr = "Outil de réparation",
				it = "Strumento di Riparazione",
				pt = "Ferramenta de Reparos",
				ru = "Ремонтный инструмент",
				ko = "수리 도구",
				cn = "修理工具",
			},
		},
	
		[375393] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375396] = {
			readable = "Lumpy Sand Pile",
			model = 4370753,
			text = {
				en = "Lumpy Sand Pile",
				es = "Montón de arena aglomerada",
				de = "Klumpiger Sandhaufen",
				fr = "Tas de sable irrégulier",
				it = "Cumulo di Sabbia Grumoso",
				pt = "Monte de Areia Irregular",
				ru = "Комковатая куча песка",
				ko = "덩어리진 모래 더미",
				cn = "鼓起的沙堆",
			},
		},
	
		[375397] = {
			readable = "Glinting Sand Pile",
			model = 4370753,
			text = {
				en = "Glinting Sand Pile",
				es = "Montón de arena destellante",
				de = "Glitzernder Sandhaufen",
				fr = "Tas de sable luisant",
				it = "Cumulo di Sabbia Scintillante",
				pt = "Monte de Areia Brilhante",
				ru = "Блестящая куча песка",
				ko = "반짝이는 모래 더미",
				cn = "反光的沙堆",
			},
		},
	
		[375398] = {
			readable = "Shifting Sand Pile",
			model = 4370753,
			text = {
				en = "Shifting Sand Pile",
				es = "Montón de arena cambiante",
				de = "Unbeständiger Sandhaufen",
				fr = "Tas de sable changeant",
				it = "Cumulo di Sabbia Mutevole",
				pt = "Monte de Areia Cambiante",
				ru = "Скользящая куча песка",
				ko = "흐르는 모래 더미",
				cn = "流动的沙堆",
			},
		},
	
		[375399] = {
			readable = "Humming Sand Pile",
			model = 4370753,
			text = {
				en = "Humming Sand Pile",
				es = "Montón de arena zumbante",
				de = "Summender Sandhaufen",
				fr = "Tas de sable bourdonnant",
				it = "Cumulo di Sabbia Ronzante",
				pt = "Monte de Areia Murmurante",
				ru = "Гудящая куча песка",
				ko = "고동치는 모래 더미",
				cn = "嗡鸣的沙堆",
			},
		},
	
		[375400] = {
			readable = "Misshapen Sand Pile",
			model = 4370753,
			text = {
				en = "Misshapen Sand Pile",
				es = "Montón de arena deforme",
				de = "Verformter Sandhaufen",
				fr = "Tas de sable difforme",
				it = "Cumulo di Sabbia Deforme",
				pt = "Monte de Areia Disforme",
				ru = "Деформированная куча песка",
				ko = "기형적인 모래 더미",
				cn = "畸形的沙堆",
			},
		},
	
		[375401] = {
			readable = "Sparkling Sand Pile",
			model = 4370753,
			text = {
				en = "Sparkling Sand Pile",
				es = "Montón de arena chispeante",
				de = "Funkelnder Sandhaufen",
				fr = "Tas de sable étincelant",
				it = "Cumulo di Sabbia Sfavillante",
				pt = "Monte de Areia Cintilante",
				ru = "Сверкающая куча песка",
				ko = "빛나는 모래 더미",
				cn = "闪耀的沙堆",
			},
		},
	
		[375402] = {
			readable = "Ticking Sand Pile",
			model = 4370753,
			text = {
				en = "Ticking Sand Pile",
				es = "Montón de arena con tictac",
				de = "Tickender Sandhaufen",
				fr = "Tas de sable cliquetant",
				it = "Cumulo di Sabbia Ticchettante",
				pt = "Monte de Areia Tiquetaqueante",
				ru = "Щелкающая куча песка",
				ko = "똑딱이는 모래 더미",
				cn = "脉动的沙堆",
			},
		},
	
		[375403] = {
			readable = "Pulp-Covered Relic",
			model = 4254628,
			text = {
				en = "Pulp-Covered Relic",
				es = "Reliquia cubierta de pulpa",
				de = "Breibedecktes Relikt",
				fr = "Relique couverte de pulpe",
				it = "Reliquia Coperta di Poltiglia",
				pt = "Relíquia Coberta de Massa Polposa",
				ru = "Измазанная реликвия",
				ko = "걸쭉한 수액으로 뒤덮인 유물",
				cn = "被粘浆覆盖的圣物",
			},
		},
	
		[375404] = {
			readable = "Sandworn Chest",
			model = 4196523,
			text = {
				en = "Sandworn Chest",
				es = "Cofre erosionado por la arena",
				de = "Sandgeschliffene Truhe",
				fr = "Coffre érodé",
				it = "Cassa Consumata dalla Sabbia",
				pt = "Baú Desgastado pela Areia",
				ru = "Пустынный сундук",
				ko = "모래에 바랜 상자",
				cn = "沙蚀宝箱",
			},
		},
	
		[375405] = {
			readable = "Filched Artifact",
			model = 4039279,
			text = {
				en = "Filched Artifact",
				es = "Artefacto birlado",
				de = "Geklautes Artefakt",
				fr = "Artéfact chipé",
				it = "Manufatto Rubato",
				pt = "Artefato Furtado",
				ru = "Украденный артефакт",
				ko = "훔친 유물",
				cn = "被窃的神器",
			},
		},
	
		[375408] = {
			readable = "Architect's Reserve",
			model = 4196523,
			text = {
				en = "Architect's Reserve",
				es = "Reserva del arquitecto",
				de = "Reserve des Architekten",
				fr = "Réserve de l’architecte",
				it = "Riserva dell'Architetto",
				pt = "Reserva do Arquiteto",
				ru = "Запасы архитектора",
				ko = "설계사의 비축물",
				cn = "造物师的贮藏",
			},
		},
	
		[375411] = {
			readable = "Mistaken Ovoid",
			model = 4228011,
			text = {
				en = "Mistaken Ovoid",
				es = "Ovoide equivocado",
				de = "Verwechseltes Ovoid",
				fr = "Ovoïde incorrect",
				it = "Ovoide Sbagliato",
				pt = "Ovoide Equivocado",
				ru = "Неуместный яйцеобразный объект",
				ko = "오해하기 쉬운 계란형 물체",
				cn = "误放的元蛋",
			},
		},
	
		[375413] = {
			readable = "Drowned Broker Supplies",
			model = 3920034,
			text = {
				en = "Drowned Broker Supplies",
				es = "Suministros de los Especuladores ahogados",
				de = "Vorräte des ertrunkenen Mittlers",
				fr = "Fournitures de négociant noyé",
				it = "Rifornimenti degli Alienatori Annegati",
				pt = "Suprimentos do Corretor Afogado",
				ru = "Затонувшие припасы брокеров",
				ko = "물에 빠진 중개자 보급품",
				cn = "溺亡掮灵补给品",
			},
		},
	
		[375422] = {
			readable = "Overgrown Protofruit",
			model = 4201284,
			text = {
				en = "Overgrown Protofruit",
				es = "Protofruta cubierta de maleza",
				de = "Überwucherte Protofrucht",
				fr = "Protofruit surdimensionné",
				it = "Protofrutto Ipertrofico",
				pt = "Protofruta Superdesenvolvida",
				ru = "Перезревший протофрукт",
				ko = "너무 자란 원생열매",
				cn = "过熟的原型水果",
			},
		},
	
		[375423] = {
			readable = "Offering to the First Ones",
			model = 3925326,
			text = {
				en = "Offering to the First Ones",
				es = "Ofrenda para los Primeros",
				de = "Opfergabe an die Ersten",
				fr = "Offrande aux Fondateurs",
				it = "Offerte ai Primi",
				pt = "Oferenda aos Primogênitos",
				ru = "Подношение Предвечным",
				ko = "태초의 존재에게 바쳐진 공물",
				cn = "初诞者供品",
			},
		},
	
		[375478] = {
			readable = "Protomineral Extractor",
			model = 4274744,
			text = {
				en = "Protomineral Extractor",
				es = "Extractor de protominerales",
				de = "Protomineralienextraktor",
				fr = "Extracteur de proto-minerai",
				it = "Estrattore di Proto-Minerale",
				pt = "Extrator Protomineral",
				ru = "Экстрактор протоминералов",
				ko = "원생광물 추출기",
				cn = "原型矿物提取器",
			},
		},
	
		[375479] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375480] = {
			readable = "Portal to Torghast",
			model = 166523,
			text = {
				en = "Portal to Torghast",
				es = "Portal a Torghast",
				de = "Portal nach Torghast",
				fr = "Portail vers Tourment",
				it = "Portale: Torgast",
				pt = "Portal para a Thanator",
				ru = "Портал в Торгаст",
				ko = "토르가스트로 통하는 차원문",
			},
		},
	
		[375481] = {
			readable = "Pilfered Curio",
			model = 4039287,
			text = {
				en = "Pilfered Curio",
				es = "Bibelot birlado",
				de = "Stibitzte Kuriosität",
				fr = "Bibelot chapardé",
				it = "Stranezza Sottratta",
				pt = "Badulaque Furtado",
				ru = "Украденная диковинка",
				ko = "도둑맞은 골동품",
				cn = "偷来的饰物",
			},
		},
	
		[375483] = {
			readable = "Stolen Scroll",
			model = 3836264,
			text = {
				en = "Stolen Scroll",
				es = "Pergamino robado",
				de = "Gestohlene Schriftrolle",
				fr = "Parchemin volé",
				it = "Pergamena Rubata",
				pt = "Pergaminho Enrolado",
				ru = "Украденный свиток",
				ko = "도난당한 두루마리",
				cn = "被盗的卷轴",
			},
		},
	
		[375484] = {
			readable = "Grateful Boon",
			model = 4261537,
			text = {
				en = "Grateful Boon",
				es = "Favor agradecido",
				de = "Dankbares Geschenk",
				fr = "Bénédiction de reconnaissance",
				it = "Dono Grato",
				pt = "Bênção Agradecida",
				ru = "Благодарственный дар",
				ko = "감사의 은혜",
				cn = "感恩之赐",
			},
		},
	
		[375485] = {
			readable = "Protoflora Harvester",
			model = 4238675,
			text = {
				en = "Protoflora Harvester",
				es = "Cosechador de protoflora",
				de = "Protofloraernter",
				fr = "Moissonneur de protoflore",
				it = "Mietitore di Protoflora",
				pt = "Ceifador de Protoflora",
				ru = "Сборщик протофлоры",
				ko = "원생식물 수확기",
				cn = "原型植物收割者",
			},
		},
	
		[375486] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375492] = {
			readable = "Syntactic Vault",
			model = 4196523,
			text = {
				en = "Syntactic Vault",
				es = "Caja fuerte sintáctica",
				de = "Syntaktisches Gewölbe",
				fr = "Coffre syntaxique",
				it = "Scrigno Sintattico",
				pt = "Câmara Sintática",
				ru = "Синтаксическое хранилище",
				ko = "구문론 금고",
				cn = "句法宝箱",
			},
		},
	
		[375493] = {
			readable = "Ripened Protopear",
			model = 4201286,
			text = {
				en = "Ripened Protopear",
				es = "Protopera madura",
				de = "Reife Protobirne",
				fr = "Proto-poire mûre",
				it = "Protopera Matura",
				pt = "Protopera Madura",
				ru = "Созревшая протогруша",
				cn = "成熟的元梨",
			},
		},
	
		[375494] = {
			readable = "Rondure Cache",
			model = 3527748,
			text = {
				en = "Rondure Cache",
				es = "Alijo circular",
				de = "Rundtruhe",
				fr = "Cache incurvée",
				it = "Cassa Arrotondata",
				pt = "Baú Circular",
				ru = "Сундук из округлого алькова",
				ko = "구체의 보관함",
				cn = "圆弧宝箱",
			},
		},
	
		[375495] = {
			readable = "Undulating Foliage",
			model = 4039277,
			text = {
				en = "Undulating Foliage",
				es = "Follaje ondulante",
				de = "Wogendes Blattwerk",
				fr = "Feuillage ondulant",
				it = "Fogliame Ondeggiante",
				pt = "Folhagem Farfalhante",
				ru = "Колыхающаяся листва",
				ko = "진동하는 식생",
				cn = "波动植物",
			},
		},
	
		[375496] = {
			readable = "Bushel of Progenitor Produce",
			model = 4201288,
			text = {
				en = "Bushel of Progenitor Produce",
				es = "Celemín de productos de progenitor",
				de = "Ein Scheffel Progenitorerzeugnisse",
				fr = "Boisseau de denrées des Progéniteurs",
				it = "Carico di Prodotti dei Progenitori",
				pt = "Saca de Produtos Agrícolas Progenitores",
				ru = "Груда фруктов Прародителей",
				ko = "창시자 생산물 뭉치",
				cn = "一蒲式耳的元尊农产品",
			},
		},
	
		[375498] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375501] = {
			readable = "Edict: Weyrns",
			model = 4235619,
			text = {
				en = "Edict: Weyrns",
				de = "Edikt: Weyrns",
				fr = "Édit : weyrns",
				pt = "Édito: Weyrns",
				ru = "Эдикт: вирны",
				ko = "칙령: 웨이른 부대",
			},
		},
	
		[375502] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375503] = {
			readable = "Edict: Obsidian Warders",
			model = 4235619,
			text = {
				en = "Edict: Obsidian Warders",
				de = "Edikt: Obsidianwächter",
				fr = "Édit : les gardes d’obsidienne",
				pt = "Édito: Guardadores Obsidianos",
				ru = "Эдикт: Обсидиановые Хранители",
				ko = "칙령: 흑요석 수호병단",
			},
		},
	
		[375512] = {
			readable = "Teleporter",
			model = 3923427,
			text = {
				en = "Teleporter",
				es = "Teletransportador",
				fr = "Téléporteur",
				it = "Teletrasporto",
				pt = "Teleportador",
				ru = "Телепорт",
				ko = "순간이동기",
				cn = "传送器",
			},
		},
	
		[375513] = {
			readable = "Royal Key",
			model = 970206,
			text = {
				en = "Royal Key",
				es = "Llave regia",
				de = "Königlicher Schlüssel",
				fr = "Clé royale",
				it = "Chiave Reale",
				pt = "Chave da Realeza",
				ru = "Королевский ключ",
				ko = "왕실 열쇠",
			},
		},
	
		[375516] = {
			readable = "Lost Comb",
			model = 1950289,
			text = {
				en = "Lost Comb",
				es = "Panal perdido",
				de = "Verlorene Wabe",
				fr = "Rayon de miel égaré",
				it = "Favo Perduto",
				pt = "Pente Perdido",
				ru = "Потерянные соты",
				ko = "잃어버린 벌집",
				cn = "失落的蜂巢",
			},
		},
	
		[375517] = {
			readable = "Suspicious Rubble Pile",
			model = 4210792,
			text = {
				en = "Suspicious Rubble Pile",
				es = "Montón de escombros sospechoso",
				de = "Verdächtig aussehender Trümmerhaufen",
				fr = "Tas de gravats suspect",
				it = "Mucchio di Macerie Sospetto",
				pt = "Pilha de Destroços Suspeita",
				ru = "Подозрительная куча обломков",
				ko = "수상한 잔해 무더기",
				cn = "可疑的碎石堆",
			},
		},
	
		[375527] = {
			readable = "Bloomthorn Vine",
			model = 4285702,
			text = {
				en = "Bloomthorn Vine",
				es = "Vid de florespina",
				de = "Blühdornranke",
				fr = "Liane de florépine",
				it = "Viticcio Sbocciaspina",
				pt = "Cipó Florespinho",
				ru = "Лоза шипоцвета",
				ko = "만개가시 덩굴",
				cn = "花棘藤蔓",
			},
		},
	
		[375530] = {
			readable = "Forgotten Treasure Vault",
			model = 4196523,
			text = {
				en = "Forgotten Treasure Vault",
				es = "Cámara del tesoro olvidada",
				de = "Vergessener Schatztresor",
				fr = "Salle du trésor oubliée",
				it = "Tesoro Dimenticato",
				pt = "Cofre do Tesouro Esquecido",
				ru = "Забытый склад сокровищ",
				ko = "잊힌 보물 금고",
				cn = "被遗忘的宝库",
			},
		},
	
		[375536] = {
			readable = "Xy'rath's Booby-Trapped Cache",
			model = 3920034,
			text = {
				en = "Xy'rath's Booby-Trapped Cache",
				es = "Alijo bomba de Xy'rath",
				de = "Xy'raths präparierte Truhe",
				fr = "Cache piégée de Xy’rath",
				it = "Cassa Esplosiva di Xy'rath",
				pt = "Baú Minado de Xy'rath",
				ru = "Заминированный тайник Зи'рата",
				ko = "자이라스의 덫이 설치된 보관함",
				cn = "赛·拉兹的陷阱宝箱",
			},
		},
	
		[375538] = {
			readable = "Lost Ovoid",
			model = 3527748,
			text = {
				en = "Lost Ovoid",
				es = "Ovoide perdido",
				de = "Verlorener Ovoid",
				fr = "Ovoïde perdu",
				it = "Ovoide Perduto",
				pt = "Ovoide Perdido",
				ru = "Потерянный яйцеобразный объект",
				ko = "잃어버린 계란형 물체",
				cn = "失落的元蛋",
			},
		},
	
		[375543] = {
			readable = "Progenitor Console 02",
			model = 3923427,
			text = {
				en = "Progenitor Console 02",
				es = "Consola de progenitor 02",
				de = "Progenitorkonsole 02",
				fr = "Console des Progéniteurs 02",
				it = "Console dei Progenitori 02",
				pt = "Console do Progenitor 02",
				ru = "Консоль Прародителей 02",
				ko = "창시자 장치 02",
				cn = "元尊控制台",
			},
		},
	
		[375544] = {
			readable = "Wooden Figurine",
			model = 201094,
			text = {
				en = "Wooden Figurine",
				es = "Figurilla de madera",
				de = "Holzstatuette",
				fr = "Figurine en bois",
				pt = "Estatueta de Madeira",
				ru = "Деревянная статуэтка",
			},
		},
	
		[375642] = {
			readable = "Lost Supplies",
			model = 3936818,
			text = {
				en = "Lost Supplies",
				es = "Provisiones extraviadas",
				de = "Verlorene Vorräte",
				fr = "Fournitures perdues",
				it = "Rifornimenti Perduti",
				pt = "Suprimentos Perdidos",
				ru = "Потерянные припасы",
				cn = "遗失的补给品",
			},
		},
	
		[375654] = {
			readable = "Abandoned Orb",
			model = 4226692,
			text = {
				en = "Abandoned Orb",
				es = "Orbe abandonado",
				de = "Zurückgelassene Kugel",
				fr = "Orbe abandonné",
				it = "Globo Abbandonato",
				pt = "Orbe Abandonado",
				ru = "Забытая сфера",
				ko = "버려진 보주",
				cn = "被遗弃的宝珠",
			},
		},
	
		[375657] = {
			readable = "Abandoned Bulwark",
			model = 4039287,
			text = {
				en = "Abandoned Bulwark",
				es = "Baluarte abandonado",
				de = "Verlassenes Bollwerk",
				fr = "Rempart abandonné",
				it = "Barricata Abbandonata",
				pt = "Baluarte Abandonado",
				ru = "Забытый бастион",
				ko = "버려진 보루",
				cn = "被遗弃的壁垒",
			},
		},
	
		[375658] = {
			readable = "Cervid Override",
			model = 4039280,
			text = {
				en = "Cervid Override",
				es = "Anulación de cérvido",
				de = "Cervidenbeherrschung",
				fr = "Cervidé dompté",
				it = "Annullamento Cervide",
				pt = "Sobremontaria de Cervídeo",
				ru = "Устройство управления сервидом",
				ko = "원시사슴 덮어쓰기",
				cn = "元鹿超控装置",
			},
		},
	
		[375659] = {
			readable = "Mysterious Fruit",
			model = 4201284,
			text = {
				en = "Mysterious Fruit",
				es = "Fruta misteriosa",
				de = "Mysteriöse Frucht",
				fr = "Fruit mystérieux",
				it = "Frutto Misterioso",
				pt = "Fruta Misteriosa",
				ru = "Таинственный фрукт",
				ko = "수수께끼의 열매",
				cn = "神秘水果",
			},
		},
	
		[375660] = {
			readable = "Mysterious Fruit",
			model = 4201285,
			text = {
				en = "Mysterious Fruit",
				es = "Fruta misteriosa",
				de = "Mysteriöse Frucht",
				fr = "Fruit mystérieux",
				it = "Frutto Misterioso",
				pt = "Fruta Misteriosa",
				ru = "Таинственный фрукт",
				ko = "수수께끼의 열매",
				cn = "神秘水果",
			},
		},
	
		[375661] = {
			readable = "Mysterious Fruit",
			model = 4201286,
			text = {
				en = "Mysterious Fruit",
				es = "Fruta misteriosa",
				de = "Mysteriöse Frucht",
				fr = "Fruit mystérieux",
				it = "Frutto Misterioso",
				pt = "Fruta Misteriosa",
				ru = "Таинственный фрукт",
				ko = "수수께끼의 열매",
				cn = "神秘水果",
			},
		},
	
		[375662] = {
			readable = "Mysterious Fruit",
			model = 4201287,
			text = {
				en = "Mysterious Fruit",
				es = "Fruta misteriosa",
				de = "Mysteriöse Frucht",
				fr = "Fruit mystérieux",
				it = "Frutto Misterioso",
				pt = "Fruta Misteriosa",
				ru = "Таинственный фрукт",
				ko = "수수께끼의 열매",
				cn = "神秘水果",
			},
		},
	
		[375663] = {
			readable = "Primeval Snare",
			model = 4039284,
			text = {
				en = "Primeval Snare",
				es = "Cepo primigenio",
				de = "Primitive Schlinge",
				fr = "Piège primitif",
				it = "Rallentamento Primevo",
				pt = "Enleio Primevo",
				ru = "Первозданный силок",
				ko = "원시의 덫",
				cn = "原始诱捕器",
			},
		},
	
		[375664] = {
			readable = "Elation Sphere",
			model = 4039277,
			text = {
				en = "Elation Sphere",
				es = "Esfera de euforia",
				de = "Sphäre der Euphorie",
				fr = "Sphère d’allégresse",
				it = "Sfera dell'Estasi",
				pt = "Esfera da Euforia",
				ru = "Сфера Восторга",
				ko = "기쁨의 구체",
				cn = "雀跃之球",
			},
		},
	
		[375665] = {
			readable = "Diminutive Simulator",
			model = 4214138,
			text = {
				en = "Diminutive Simulator",
				es = "Simulador diminuto",
				de = "Schrumpfsimulator",
				fr = "Simulateur d’atrophie",
				it = "Simulatore Riduttivo",
				pt = "Simulador de Diminutivos",
				ru = "Симулятор уменьшения",
				ko = "축소의 모의 장치",
				cn = "小微模拟器",
			},
		},
	
		[375666] = {
			readable = "Towering Simulator",
			model = 4214138,
			text = {
				en = "Towering Simulator",
				es = "Simulador enorme",
				de = "Vergrößerungssimulator",
				fr = "Simulateur de croissance",
				it = "Simulatore Torreggiante",
				pt = "Simulador Imponente",
				ru = "Симулятор увеличения",
				ko = "확대의 모의 장치",
				cn = "高耸模拟器",
			},
		},
	
		[375667] = {
			readable = "Teleporter",
			model = 3923427,
			text = {
				en = "Teleporter",
				es = "Teletransportador",
				fr = "Téléporteur",
				it = "Teletrasporto",
				pt = "Teleportador",
				ru = "Телепорт",
				ko = "순간이동기",
				cn = "传送器",
			},
		},
	
		[375668] = {
			readable = "Misty Treasure Chest",
			model = 4216698,
			text = {
				en = "Misty Treasure Chest",
				es = "Arqueta brumosa",
				de = "Neblige Schatzkiste",
				fr = "Coffre au trésor brumeux",
				it = "Cassa del Tesoro Nebbiosa",
				pt = "Baú do Tesouro Nebuloso",
				ru = "Окутанный туманом сундук сокровищ",
				ko = "안개의 보물 상자",
				cn = "迷雾宝箱",
			},
		},
	
		[375673] = {
			readable = "Climbing Gear",
			model = 534613,
			text = {
				en = "Climbing Gear",
				es = "Equipamiento de escalada",
				de = "Kletterausrüstung",
				fr = "Équipement d’escalade",
				it = "Equipaggiamento da Arrampicata",
				pt = "Equipamento de Escalada",
				ru = "Снаряжение скалолаза",
				ko = "등반 장비",
				cn = "攀登装备",
			},
		},
	
		[375687] = {
			readable = "Water Keg",
			model = 4198221,
			text = {
				en = "Water Keg",
				es = "Barril de agua",
				de = "Wasserfass",
				fr = "Tonneau d’eau",
				it = "Barilotto d'Acqua",
				pt = "Barrilete de Água",
				ru = "Бочка с водой",
				ko = "물통",
				cn = "水桶",
			},
		},
	
		[375690] = {
			readable = "Locrian Swale",
			model = 4224815,
			text = {
				en = "Locrian Swale",
				es = "Zanja de Locris",
				de = "Lokrische Senke",
				fr = "Noue locrienne",
				it = "Striscia di Locrian",
				pt = "Vala Locriana",
				ru = "Локрийская призма",
				ko = "로크리아 마력석",
				cn = "音室引槽",
			},
		},
	
		[375692] = {
			readable = "Locrian Valve",
			model = 3923430,
			text = {
				en = "Locrian Valve",
				es = "Válvula de Locris",
				de = "Lokrisches Ventil",
				fr = "Valve locrienne",
				it = "Valvola di Locrian",
				pt = "Válvula Locriana",
				ru = "Локрийский клапан",
				ko = "로크리아 밸브",
				cn = "音室阀门",
			},
		},
	
		[375693] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375694] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375746] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de prototipo",
				de = "Prototypbauplan",
				fr = "Schéma de prototype",
				it = "Schema di Prototipo",
				pt = "Diagrama de Protótipo",
				ru = "Чертеж прототипа",
				ko = "원형 설계도",
				cn = "原型体设计方案",
			},
		},
	
		[375748] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375757] = {
			readable = "Runic Syllable",
			model = 4081531,
			text = {
				en = "Runic Syllable",
				es = "Sílaba rúnica",
				de = "Runensilbe",
				fr = "Syllabe runique",
				it = "Sillaba Runica",
				pt = "Sílaba Rúnica",
				ru = "Рунический слог",
				ko = "룬 음절",
				cn = "符文音节",
			},
		},
	
		[375758] = {
			readable = "Runic Syllable",
			model = 4081528,
			text = {
				en = "Runic Syllable",
				es = "Sílaba rúnica",
				de = "Runensilbe",
				fr = "Syllabe runique",
				it = "Sillaba Runica",
				pt = "Sílaba Rúnica",
				ru = "Рунический слог",
				ko = "룬 음절",
				cn = "符文音节",
			},
		},
	
		[375759] = {
			readable = "Runic Syllable",
			model = 4081525,
			text = {
				en = "Runic Syllable",
				es = "Sílaba rúnica",
				de = "Runensilbe",
				fr = "Syllabe runique",
				it = "Sillaba Runica",
				pt = "Sílaba Rúnica",
				ru = "Рунический слог",
				ko = "룬 음절",
				cn = "符文音节",
			},
		},
	
		[375760] = {
			readable = "Runic Syllable",
			model = 4081533,
			text = {
				en = "Runic Syllable",
				es = "Sílaba rúnica",
				de = "Runensilbe",
				fr = "Syllabe runique",
				it = "Sillaba Runica",
				pt = "Sílaba Rúnica",
				ru = "Рунический слог",
				ko = "룬 음절",
				cn = "符文音节",
			},
		},
	
		[375761] = {
			readable = "Runic Syllable",
			model = 4081529,
			text = {
				en = "Runic Syllable",
				es = "Sílaba rúnica",
				de = "Runensilbe",
				fr = "Syllabe runique",
				it = "Sillaba Runica",
				pt = "Sílaba Rúnica",
				ru = "Рунический слог",
				ko = "룬 음절",
				cn = "符文音节",
			},
		},
	
		[375762] = {
			readable = "Runic Syllable",
			model = 4081527,
			text = {
				en = "Runic Syllable",
				es = "Sílaba rúnica",
				de = "Runensilbe",
				fr = "Syllabe runique",
				it = "Sillaba Runica",
				pt = "Sílaba Rúnica",
				ru = "Рунический слог",
				ko = "룬 음절",
				cn = "符文音节",
			},
		},
	
		[375763] = {
			readable = "Syntactic Seal",
			model = 4039284,
			text = {
				en = "Syntactic Seal",
				es = "Sello sintáctico",
				de = "Syntaktisches Siegel",
				fr = "Sceau syntaxique",
				it = "Sigillo Sintattico",
				pt = "Selo Sintático",
				ru = "Синтаксическая печать",
				ko = "구문론 인장",
				cn = "句法封印",
			},
		},
	
		[375765] = {
			readable = "Forgotten Pump",
			model = 353152,
			text = {
				en = "Forgotten Pump",
				es = "Bomba olvidada",
				de = "Vergessene Pumpe",
				fr = "Pompe oubliée",
				it = "Pompa Dimenticata",
				pt = "Bomba Esquecida",
				ru = "Забытый насос",
				ko = "잊힌 펌프",
				cn = "被遗忘的水泵",
			},
		},
	
		[375766] = {
			readable = "Dangerous Orb of Power",
			model = 4214138,
			text = {
				en = "Dangerous Orb of Power",
				es = "Orbe de poder peligroso",
				de = "Gefährliche Kugel der Macht",
				fr = "Dangereux orbe de puissance",
				it = "Globo del Potere Pericoloso",
				pt = "Orbe de Poder Perigoso",
				ru = "Опасная сфера могущества",
				ko = "위험한 힘의 보주",
				cn = "危险的能量宝珠",
			},
		},
	
		[375775] = {
			readable = "Locrian Valve",
			model = 3923430,
			text = {
				en = "Locrian Valve",
				es = "Válvula de Locris",
				de = "Lokrisches Ventil",
				fr = "Valve locrienne",
				it = "Valvola di Locrian",
				pt = "Válvula Locriana",
				ru = "Локрийский клапан",
				ko = "로크리아 밸브",
				cn = "音室阀门",
			},
		},
	
		[375827] = {
			readable = "Crate of Provisions",
			model = 197150,
			text = {
				en = "Crate of Provisions",
				de = "Kiste mit Vorräten",
				fr = "Caisse de provisions",
				pt = "Caixote de Provisões",
				ru = "Ящик с провизией",
			},
		},
	
		[375839] = {
			readable = "Lillith's Dinner Table",
			model = 198598,
			text = {
				en = "Lillith's Dinner Table",
			},
		},
	
		[375841] = {
			readable = "Invincible",
			model = 199985,
			text = {
				en = "Invincible",
			},
		},
	
		[375844] = {
			readable = "Gunther's Books",
			model = 198056,
			text = {
				en = "Gunther's Books",
			},
		},
	
		[375846] = {
			readable = "Crate of Candles",
			model = 199634,
			text = {
				en = "Crate of Candles",
			},
		},
	
		[375875] = {
			readable = "Mausoleum Trigger",
			model = 201070,
			text = {
				en = "Mausoleum Trigger",
				de = "Mausoleumsauslöser",
				fr = "Déclencheur du mausolée",
				it = "Mausoleo",
				pt = "Gatilho do Mausoléu",
				ru = "Инициатор мавзолея",
			},
		},
	
		[375879] = {
			readable = "Egress Phrase",
			model = 4267690,
			text = {
				en = "Egress Phrase",
				es = "Frase de egreso",
				de = "Losung",
				fr = "Formule de sortie",
				it = "Frase di Uscita",
				pt = "Frase Egressa",
				ru = "Слова ухода",
				ko = "출구의 구절",
				cn = "准出短语",
			},
		},
	
		[375886] = {
			readable = "Treasures of the First Ones",
			model = 4196523,
			text = {
				en = "Treasures of the First Ones",
				es = "Tesoros de los Primeros",
				de = "Schätze der Ersten",
				fr = "Trésors des Fondateurs",
				it = "Tesori dei Primi",
				pt = "Tesouros dos Primogênitos",
				ru = "Сокровища Предвечных",
				ko = "태초의 존재의 보물",
				cn = "初诞者的财宝",
			},
		},
	
		[375887] = {
			readable = "Worldbreaker Cell",
			model = 609081,
			text = {
				en = "Worldbreaker Cell",
				es = "Celda rompemundos",
				de = "Weltenbrecherzelle",
				fr = "Cellule brise-monde",
				it = "Cella del Devastamondi",
				pt = "Cela dos Quebramundos",
				ru = "Клетка разрушителей миров",
				ko = "세계파괴자 감방",
				cn = "灭世者牢笼",
			},
		},
	
		[375889] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375893] = {
			readable = "High Value Cache",
			model = 3920034,
			text = {
				en = "High Value Cache",
				es = "Alijo de gran valor",
				de = "Sehr wertvoller Schatz",
				fr = "Cache précieuse",
				it = "Scrigno di Grande Valore",
				pt = "Baú de Alto Valor",
				ru = "Тайник с ценностями",
				ko = "진귀한 보관함",
				cn = "价值连城的宝箱",
			},
		},
	
		[375895] = {
			readable = "Automa Console",
			model = 4198154,
			text = {
				en = "Automa Console",
				es = "Consola de Automa",
				de = "Automakonsole",
				fr = "Console d’Automa",
				it = "Console degli Automa",
				pt = "Console de Automa",
				ru = "Консоль автомов",
				ko = "자동기계 제어장치",
				cn = "自动体控制台",
			},
		},
	
		[375900] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375901] = {
			readable = "Treasures of the First Ones",
			model = 4196523,
			text = {
				en = "Treasures of the First Ones",
				es = "Tesoros de los Primeros",
				de = "Schätze der Ersten",
				fr = "Trésors des Fondateurs",
				it = "Tesori dei Primi",
				pt = "Tesouros dos Primogênitos",
				ru = "Сокровища Предвечных",
				ko = "태초의 존재의 보물",
				cn = "初诞者的财宝",
			},
		},
	
		[375902] = {
			readable = "Torn Ethereal Drape",
			model = 1503243,
			text = {
				en = "Torn Ethereal Drape",
				es = "Mantón etéreo deshilachado",
				de = "Zerfleddertes Astraltuch",
				fr = "Drapé éthérien déchiré",
				it = "Drappo Etereo Strappato",
				pt = "Clâmide Etérea Rasgada",
				ru = "Рваная призрачная пелерина",
				ko = "찢겨 나간 실체 없는 외투",
				cn = "破旧的虚渺披风",
			},
		},
	
		[375903] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375905] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375906] = {
			readable = "Automa Console",
			model = 4198154,
			text = {
				en = "Automa Console",
				es = "Consola de Automa",
				de = "Automakonsole",
				fr = "Console d’Automa",
				it = "Console degli Automa",
				pt = "Console de Automa",
				ru = "Консоль автомов",
				ko = "자동기계 제어장치",
				cn = "自动体控制台",
			},
		},
	
		[375907] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375908] = {
			readable = "Automa Console",
			model = 4198154,
			text = {
				en = "Automa Console",
				es = "Consola de Automa",
				de = "Automakonsole",
				fr = "Console d’Automa",
				it = "Console degli Automa",
				pt = "Console de Automa",
				ru = "Консоль автомов",
				ko = "자동기계 제어장치",
				cn = "自动体控制台",
			},
		},
	
		[375909] = {
			readable = "Harp",
			model = 192078,
			text = {
				en = "Harp",
				es = "Arpa",
				de = "Harfe",
				ru = "Арфа",
			},
		},
	
		[375910] = {
			readable = "Automa Console",
			model = 4198154,
			text = {
				en = "Automa Console",
				es = "Consola de Automa",
				de = "Automakonsole",
				fr = "Console d’Automa",
				it = "Console degli Automa",
				pt = "Console de Automa",
				ru = "Консоль автомов",
				ko = "자동기계 제어장치",
				cn = "自动体控制台",
			},
		},
	
		[375913] = {
			readable = "Automa Console",
			model = 4198154,
			text = {
				en = "Automa Console",
				es = "Consola de Automa",
				de = "Automakonsole",
				fr = "Console d’Automa",
				it = "Console degli Automa",
				pt = "Console de Automa",
				ru = "Консоль автомов",
				ko = "자동기계 제어장치",
				cn = "自动体控制台",
			},
		},
	
		[375915] = {
			readable = "Glimmer of Serenity",
			model = 4176991,
			text = {
				en = "Glimmer of Serenity",
				es = "Fulgor de la serenidad",
				de = "Schimmer des Gleichmuts",
				fr = "Lueur de sérénité",
				it = "Barlume della Serenità",
				pt = "Fulgor da Serenidade",
				ru = "Искра безмятежности",
				ko = "평온의 미명",
				cn = "平静微光",
			},
		},
	
		[375949] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375950] = {
			readable = "Bauble of Pure Innovation",
			model = 4176996,
			text = {
				en = "Bauble of Pure Innovation",
				es = "Adorno de innovación pura",
				de = "Schmuckstück der reinen Innovation",
				fr = "Babiole d’innovation pure",
				it = "Ninnolo di Pura Innovazione",
				pt = "Bugiganga de Inovação Pura",
				ru = "Шар чистой изобретательности",
				ko = "순수한 혁신의 보석",
				cn = "纯粹创新饰珠",
			},
		},
	
		[375972] = {
			readable = "Wanted: Custos",
			model = 3836252,
			text = {
				en = "Wanted: Custos",
				es = "Se busca: Custos",
				de = "Gesucht: Custos",
				fr = "On recherche : Custos",
				it = "Ricercato: Custos",
				pt = "Procura-se: Custoz",
				ru = "Разыскивается: Кустос",
				ko = "현상 수배: 쿠스토스",
				cn = "通缉：库斯托斯",
			},
		},
	
		[375973] = {
			readable = "Firim in Exile, Part 1",
			model = 3836262,
			text = {
				en = "Firim in Exile, Part 1",
				es = "Firim en el exilio, primera parte",
				de = "Firim im Exil, Teil 1",
				fr = "L’exil de Firim, 1re partie",
				it = "Firim in Esilio, Parte 1",
				pt = "Firim no Exílio, Parte 1",
				ru = "Фирим в изгнании, часть 1",
				ko = "피림의 추방기 제1부",
				cn = "流亡者菲历姆，第一章",
			},
		},
	
		[375974] = {
			readable = "Crystallized Echo of the First Song",
			model = 1687825,
			text = {
				en = "Crystallized Echo of the First Song",
				es = "Eco cristalizado de la primera canción",
				de = "Kristallisiertes Echo des Ersten Lieds",
				fr = "Écho du premier chant cristallisé",
				it = "Eco Cristallizzata del Primo Canto",
				pt = "Eco Cristalizado da Primeira Canção",
				ru = "Кристаллизованное эхо первой песни",
				ko = "결정화된 태초의 노래의 메아리",
				cn = "原初之歌的晶化回响",
			},
		},
	
		[375977] = {
			readable = "Firim's Research Notes",
			model = 3836266,
			text = {
				en = "Firim's Research Notes",
				es = "Notas de investigación de Firim",
				de = "Firims Forschungsnotizen",
				fr = "Notes de recherche de Firim",
				it = "Appunti di Ricerca di Firim",
				pt = "Anotações de Pesquisa de Firim",
				ru = "Исследовательские записи Фирима",
				ko = "피림의 연구 일지",
				cn = "菲历姆的研究笔记",
			},
		},
	
		[375981] = {
			readable = "Protoform Schematic",
			model = 4196520,
			text = {
				en = "Protoform Schematic",
				es = "Esquema de protoforma",
				de = "Protoformbauplan",
				fr = "Schéma de protoforme",
				it = "Schema di Protoforma",
				pt = "Diagrama de Protoforma",
				ru = "Схема протосинтеза",
				ko = "원생형태 설계도",
				cn = "原生体设计方案",
			},
		},
	
		[375982] = {
			readable = "Firim in Exile, Part 2",
			model = 3836262,
			text = {
				en = "Firim in Exile, Part 2",
				es = "Firim en el exilio, segunda parte",
				de = "Firim im Exil, Teil 2",
				fr = "L’exil de Firim, 2e partie",
				it = "Firim in Esilio, Parte 2",
				pt = "Firim no Exílio, Parte 2",
				ru = "Фирим в изгнании, часть 2",
				ko = "피림의 추방기 제2부",
				cn = "流亡者菲历姆，第二章",
			},
		},
	
		[375983] = {
			readable = "Firim in Exile, Part 3",
			model = 3836262,
			text = {
				en = "Firim in Exile, Part 3",
				es = "Firim en el exilio, tercera parte",
				de = "Firim im Exil, Teil 3",
				fr = "L’exil de Firim, 3e partie",
				it = "Firim in Esilio, Parte 3",
				pt = "Firim no Exílio, Parte 3",
				ru = "Фирим в изгнании, часть 3",
				ko = "피림의 추방기 제3부",
				cn = "流亡者菲历姆，第三章",
			},
		},
	
		[375984] = {
			readable = "Firim in Exile, Part 4",
			model = 3836262,
			text = {
				en = "Firim in Exile, Part 4",
				es = "Firim en el exilio, cuarta parte",
				de = "Firim im Exil, Teil 4",
				fr = "L’exil de Firim, 4e partie",
				it = "Firim in Esilio, Parte 4",
				pt = "Firim no Exílio, Parte 4",
				ru = "Фирим в изгнании, часть 4",
				ko = "피림의 추방기 제4부",
				cn = "流亡者菲历姆，第四章",
			},
		},
	
		[375985] = {
			readable = "Firim in Exile, Part 5",
			model = 3836262,
			text = {
				en = "Firim in Exile, Part 5",
				es = "Firim en el exilio, quinta parte",
				de = "Firim im Exil, Teil 5",
				fr = "L’exil de Firim, 5e partie",
				it = "Firim in Esilio, Parte 5",
				pt = "Firim no Exílio, Parte 5",
				ru = "Фирим в изгнании, часть 5",
				ko = "피림의 추방기 제5부",
				cn = "流亡者菲历姆，第五章",
			},
		},
	
		[375986] = {
			readable = "Firim in Exile, Part 6",
			model = 3836262,
			text = {
				en = "Firim in Exile, Part 6",
				es = "Firim en el exilio, sexta parte",
				de = "Firim im Exil, Teil 6",
				fr = "L’exil de Firim, 6e partie",
				it = "Firim in Esilio, Parte 6",
				pt = "Firim no Exílio, Parte 6",
				ru = "Фирим в изгнании, часть 6",
				ko = "피림의 추방기 제6부",
				cn = "流亡者菲历姆，第六章",
			},
		},
	
		[375987] = {
			readable = "Firim in Exile, Part 7",
			model = 3836262,
			text = {
				en = "Firim in Exile, Part 7",
				es = "Firim en el exilio, séptima parte",
				de = "Firim im Exil, Teil 7",
				fr = "L’exil de Firim, 7e partie",
				it = "Firim in Esilio, Parte 7",
				pt = "Firim no Exílio, Parte 7",
				ru = "Фирим в изгнании, часть 7",
				ko = "피림의 추방기 제7부",
				cn = "流亡者菲历姆，第七章",
			},
		},
	
		[375988] = {
			readable = "Firim in Exile, Epilogue",
			model = 3836262,
			text = {
				en = "Firim in Exile, Epilogue",
				es = "Firim en el exilio, epílogo",
				de = "Firim im Exil, Epilog",
				fr = "L’exil de Firim, épilogue",
				pt = "Firim no Exílio, Epílogo",
				ru = "Фирим в изгнании, эпилог",
				ko = "피림의 추방기 후일담",
				cn = "流亡者菲历姆，尾声",
			},
		},
	
		[375998] = {
			readable = "Enlightened Incense Burner",
			model = 3997990,
			text = {
				en = "Enlightened Incense Burner",
				es = "Quemador de incienso de los Iluminados",
				de = "Räuchergefäß der Erleuchteten",
				fr = "Brûle-encens des Éclairés",
				it = "Incensiere degli Illuminati",
				pt = "Incensório dos Iluminados",
				ru = "Курильница Просветленных",
				ko = "깨달음의 향로",
				cn = "开悟者香炉",
			},
		},
})
do ObjectDB[objectID] = objectData; end
