local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	
		[160445] = {
			readable = "Sha'ni Proudtusk's Remains",
			model = 199680,
			text = {
				en = "Sha'ni Proudtusk's Remains",
				es = "Restos de Sha'ni Colmillo Orgulloso",
				de = "Sha'ni Ehrenhauers Überreste",
				fr = "Restes de Sha'ni Fière-défense",
				ru = "Останки Ша'ни Гордый Клык",
			},
		},
	
		[160836] = {
			readable = "Relic Coffer",
			icon = 132596,
			model = 196976,
			text = {
				en = "Relic Coffer",
				es = "Arca de reliquias",
				de = "Reliktkasten",
				fr = "Coffret à relique",
				it = "Reliquiario",
				pt = "Arca de Relíquia",
				ru = "Реликварий",
				ko = "유물 금고",
				cn = "古物宝库",
			},
		},
	
		[160840] = {
			readable = "Soft Dirt Mound",
			model = 189528,
			text = {
				en = "Soft Dirt Mound",
				es = "Montículo de tierra blanda",
				de = "Weicher Erdhaufen",
				fr = "Monticule de terre",
				ru = "Куча рыхлой земли",
			},
		},
	
		[160845] = {
			readable = "Dark Coffer",
			icon = 132597,
			model = 196976,
			text = {
				en = "Dark Coffer",
				es = "Arca oscura",
				de = "Dunkler Kasten",
				fr = "Coffre sombre",
				it = "Forziere Oscuro",
				pt = "Cofre Sombrio",
				ru = "Черный ящик",
				ko = "검은 금고",
				cn = "黑暗宝箱",
			},
		},
	
		[161495] = {
			readable = "Secret Safe",
			icon = 132595,
			model = 196976,
			text = {
				en = "Secret Safe",
				es = "Caja fuerte secreta",
				de = "Geheimsafe",
				fr = "Coffre secret",
				it = "Cassaforte Segreta",
				pt = "Cofre Secreto",
				ru = "Потайной сейф",
				ko = "비밀 금고",
				cn = "秘密保险箱",
			},
		},
	
		[161504] = {
			readable = "A Small Pack",
			model = 200442,
			text = {
				en = "A Small Pack",
				es = "Un paquetito",
				de = "Ein kleines Pack",
				fr = "Un petit paquet",
				pt = "Um Pacote Pequeno",
				ru = "Небольшая сумка",
				ko = "작은 배낭",
				cn = "小背包",
			},
		},
	
		[161505] = {
			readable = "A Wrecked Raft",
			icon = 132594,
			model = 190677,
			text = {
				en = "A Wrecked Raft",
				es = "Una balsa estropeada",
				de = "Ein havariertes Floß",
				fr = "Une épave de radeau",
				it = "Zattera Distrutta",
				pt = "Bote Naufragado",
				ru = "Разбитый плот",
				ko = "난파된 나룻배",
				cn = "破碎的木筏",
			},
		},
	
		[161513] = {
			readable = "Farm Chicken Egg",
			model = 201375,
			text = {
				en = "Farm Chicken Egg",
				es = "Huevo de gallina de granja",
				de = "Hofhuhnei",
				fr = "Œuf de poulet fermier",
				it = "Uovo di Gallina della Fattoria",
				pt = "Ovo de Galinha Caipira",
				ru = "Деревенское куриное яйцо",
				ko = "농장 달걀",
			},
		},
	
		[161521] = {
			readable = "Research Equipment",
			icon = 132594,
			model = 198085,
			text = {
				en = "Research Equipment",
				es = "Equipo de investigación",
				de = "Forscherausrüstung",
				fr = "Equipement de recherche",
				it = "Equipaggiamento Scientifico",
				pt = "Equipamento de Pesquisa",
				ru = "Исследовательское оборудование",
				ko = "탐사 장비",
				cn = "研究设备",
			},
		},
	
		[161526] = {
			readable = "Crate of Foodstuffs",
			icon = 132594,
			model = 197150,
			text = {
				en = "Crate of Foodstuffs",
				es = "Cajón de comestibles",
				de = "Kiste mit Lebensmitteln",
				fr = "Caisse de nourriture",
				it = "Cassa di Cibo",
				pt = "Caixote de Comestíveis",
				ru = "Ящик с провизией",
				ko = "식량 상자",
				cn = "食物箱",
			},
		},
	
		[161527] = {
			readable = "Dinosaur Bone",
			model = 199754,
			text = {
				en = "Dinosaur Bone",
				es = "Hueso de dinosaurio",
				de = "Dinosaurierknochen",
				fr = "Os de dinosaure",
				it = "Osso di Dinosauro",
				pt = "Osso de Dinossauro",
				ru = "Кость динозавра",
				ko = "공룡 뼈",
				cn = "恐龙骨头",
			},
		},
	
		[161557] = {
			readable = "Milly's Harvest",
			icon = 134014,
			model = 189806,
			text = {
				en = "Milly's Harvest",
				es = "Cosecha de Milly",
				de = "Millys Ernte",
				fr = "Récolte de Milly",
				pt = "Colheita da Madel",
				ru = "Урожай Милли",
				ko = "밀리의 수확물",
				cn = "米莉的葡萄",
			},
		},
	
		[161752] = {
			readable = "Tool Bucket",
			icon = 134063,
			model = 198069,
			text = {
				en = "Tool Bucket",
				es = "Cubo de herramientas",
				de = "Werkzeugkiste",
				fr = "Seau d'outils",
				it = "Secchio degli Attrezzi",
				pt = "Balde de Ferramentas",
				ru = "Ведро с инструментами",
				ko = "연장통",
				cn = "工具篮",
			},
		},
	
		[164658] = {
			readable = "Blue Power Crystal",
			model = 202748,
			text = {
				en = "Blue Power Crystal",
				es = "Cristal de poder azul",
				de = "Blauer Machtkristall",
				fr = "Cristal de puissance bleu",
				it = "Cristallo Energetico Blu",
				pt = "Cristal de Poder Azul",
				ru = "Синий кристалл силы",
				ko = "푸른 마력의 수정",
				cn = "蓝色能量水晶",
			},
		},
	
		[164659] = {
			readable = "Green Power Crystal",
			icon = 134105,
			model = 202750,
			text = {
				en = "Green Power Crystal",
				es = "Cristal de poder verde",
				de = "Grüner Machtkristall",
				fr = "Cristal de puissance vert",
				it = "Cristallo Energetico Verde",
				pt = "Cristal de Poder Verde",
				ru = "Зеленый кристалл силы",
				ko = "녹색 마력의 수정",
				cn = "绿色能量水晶",
			},
		},
	
		[164660] = {
			readable = "Red Power Crystal",
			model = 202752,
			text = {
				en = "Red Power Crystal",
				es = "Cristal de poder rojo",
				de = "Roter Machtkristall",
				fr = "Cristal de puissance rouge",
				it = "Cristallo Energetico Rosso",
				pt = "Cristal de Poder Vermelho",
				ru = "Красный кристалл силы",
				ko = "붉은 마력의 수정",
				cn = "红色能量水晶",
			},
		},
	
		[164661] = {
			readable = "Yellow Power Crystal",
			icon = 134136,
			model = 202754,
			text = {
				en = "Yellow Power Crystal",
				es = "Cristal de poder amarillo",
				de = "Gelber Machtkristall",
				fr = "Cristal de puissance jaune",
				it = "Cristallo Energetico Giallo",
				pt = "Cristal de Poder Amarelo",
				ru = "Желтый кристалл силы",
				ko = "노란 마력의 수정",
				cn = "黄色能量水晶",
			},
		},
	
		[164662] = {
			readable = "Equipment Boxes",
			model = 198085,
			text = {
				en = "Equipment Boxes",
				es = "Cajas de equipamiento",
				de = "Ausrüstungskästen",
				fr = "Boîtes d'équipement",
				ru = "Ящики cо старой одеждой",
			},
		},
	
		[164689] = {
			readable = "Monument of Franclorn Forgewright",
			model = 203024,
			text = {
				en = "Monument of Franclorn Forgewright",
				es = "Monumento a Franclorn Forjador",
				de = "Denkmal für Franclorn Schmiedevater",
				fr = "Monument de Franclorn Le Forgebusier",
				it = "Monumento a Franclorn Forgiabruna",
				pt = "Monumento de Franclorn Forjífice",
				ru = "Монумент Франклорну Искуснику",
				ko = "프랑클론 포지라이트의 기념비",
				cn = "弗兰克罗恩·铸铁的雕像",
			},
		},
	
		[164690] = {
			readable = "Krom'zar's Banner",
			model = 201581,
			text = {
				en = "Krom'zar's Banner",
				es = "Estandarte de Krom'zar",
				de = "Krom'zars Flagge",
				fr = "Bannière de Krom'zar",
				it = "Stendardo di Krom'zar",
				pt = "Estandarte de Krom'zar",
				ru = "Знамя Кром'зара",
				ko = "크롬자르의 깃발",
			},
		},
	
		[164778] = {
			readable = "Blue Power Crystal",
			icon = 134133,
			model = 202749,
			text = {
				en = "Blue Power Crystal",
				es = "Cristal de poder azul",
				de = "Blauer Machtkristall",
				fr = "Cristal de puissance bleu",
				it = "Cristallo Energetico Blu",
				pt = "Cristal de Poder Azul",
				ru = "Синий кристалл силы",
				ko = "푸른 마력의 수정",
				cn = "蓝色能量水晶",
			},
		},
	
		[164779] = {
			readable = "Green Power Crystal",
			model = 202751,
			text = {
				en = "Green Power Crystal",
				es = "Cristal de poder verde",
				de = "Grüner Machtkristall",
				fr = "Cristal de puissance vert",
				it = "Cristallo Energetico Verde",
				pt = "Cristal de Poder Verde",
				ru = "Зеленый кристалл силы",
				ko = "녹색 마력의 수정",
				cn = "绿色能量水晶",
			},
		},
	
		[164780] = {
			readable = "Red Power Crystal",
			icon = 134130,
			model = 202753,
			text = {
				en = "Red Power Crystal",
				es = "Cristal de poder rojo",
				de = "Roter Machtkristall",
				fr = "Cristal de puissance rouge",
				it = "Cristallo Energetico Rosso",
				pt = "Cristal de Poder Vermelho",
				ru = "Красный кристалл силы",
				ko = "붉은 마력의 수정",
				cn = "红色能量水晶",
			},
		},
	
		[164781] = {
			readable = "Yellow Power Crystal",
			model = 202755,
			text = {
				en = "Yellow Power Crystal",
				es = "Cristal de poder amarillo",
				de = "Gelber Machtkristall",
				fr = "Cristal de puissance jaune",
				it = "Cristallo Energetico Giallo",
				pt = "Cristal de Poder Amarelo",
				ru = "Желтый кристалл силы",
				ko = "노란 마력의 수정",
				cn = "黄色能量水晶",
			},
		},
	
		[164798] = {
			readable = "Evoroot",
			model = 199220,
			text = {
				en = "Evoroot",
				es = "Raíz del mal",
				de = "Evowurzel",
				fr = "Evoracine",
				ru = "Корень вечерника",
			},
		},
	
		[164820] = {
			readable = "Dark Keeper Nameplate",
			icon = 236444,
			model = 203051,
			text = {
				en = "Dark Keeper Nameplate",
				es = "Placa de Guarda oscuro",
				de = "Namensschild des Dunkelbewahrers",
				fr = "Nom du Gardien noir",
				it = "Targa del Guardiano Oscuro",
				pt = "Placa de Identificação do Guardião Sombrio",
				ru = "Табличка с именем темного хранителя",
				ko = "암흑의 문지기 명판",
				cn = "黑暗守护者的标示牌",
			},
		},
	
		[164821] = {
			readable = "Dark Keeper Nameplate",
			model = 203051,
			text = {
				en = "Dark Keeper Nameplate",
				es = "Placa de Guarda oscuro",
				de = "Namensschild des Dunkelbewahrers",
				fr = "Nom du Gardien noir",
				it = "Targa del Guardiano Oscuro",
				pt = "Placa de Identificação do Guardião Sombrio",
				ru = "Табличка с именем темного хранителя",
				ko = "암흑의 문지기 명판",
				cn = "黑暗守护者的标示牌",
			},
		},
	
		[164822] = {
			readable = "Dark Keeper Nameplate",
			model = 203051,
			text = {
				en = "Dark Keeper Nameplate",
				es = "Placa de Guarda oscuro",
				de = "Namensschild des Dunkelbewahrers",
				fr = "Nom du Gardien noir",
				it = "Targa del Guardiano Oscuro",
				pt = "Placa de Identificação do Guardião Sombrio",
				ru = "Табличка с именем темного хранителя",
				ko = "암흑의 문지기 명판",
				cn = "黑暗守护者的标示牌",
			},
		},
	
		[164823] = {
			readable = "Dark Keeper Nameplate",
			model = 203051,
			text = {
				en = "Dark Keeper Nameplate",
				es = "Placa de Guarda oscuro",
				de = "Namensschild des Dunkelbewahrers",
				fr = "Nom du Gardien noir",
				it = "Targa del Guardiano Oscuro",
				pt = "Placa de Identificação do Guardião Sombrio",
				ru = "Табличка с именем темного хранителя",
				ko = "암흑의 문지기 명판",
				cn = "黑暗守护者的标示牌",
			},
		},
	
		[164824] = {
			readable = "Dark Keeper Nameplate",
			model = 203051,
			text = {
				en = "Dark Keeper Nameplate",
				es = "Placa de Guarda oscuro",
				de = "Namensschild des Dunkelbewahrers",
				fr = "Nom du Gardien noir",
				it = "Targa del Guardiano Oscuro",
				pt = "Placa de Identificação do Guardião Sombrio",
				ru = "Табличка с именем темного хранителя",
				ko = "암흑의 문지기 명판",
				cn = "黑暗守护者的标示牌",
			},
		},
	
		[164825] = {
			readable = "Dark Keeper Nameplate",
			model = 203051,
			text = {
				en = "Dark Keeper Nameplate",
				es = "Placa de Guarda oscuro",
				de = "Namensschild des Dunkelbewahrers",
				fr = "Nom du Gardien noir",
				it = "Targa del Guardiano Oscuro",
				pt = "Placa de Identificação do Guardião Sombrio",
				ru = "Табличка с именем темного хранителя",
				ko = "암흑의 문지기 명판",
				cn = "黑暗守护者的标示牌",
			},
		},
	
		[164867] = {
			readable = "WANTED",
			icon = 134939,
			model = 199473,
			text = {
				en = "WANTED",
				es = "SE BUSCA",
				de = "GESUCHT",
				fr = "AVIS DE RECHERCHE",
				it = "RICERCATO",
				pt = "PROCURA-SE",
				ru = "РАЗЫСКИВАЕТСЯ",
				ko = "현상 수배!",
				cn = "通缉",
			},
		},
	
		[164868] = {
			readable = "KILL ON SIGHT",
			icon = 134939,
			model = 199477,
			text = {
				en = "KILL ON SIGHT",
				es = "MATAR INMEDIATAMENTE",
				de = "SOFORT TÖTEN",
				fr = "TUER À VUE",
				it = "UCCIDERE A VISTA",
				pt = "SE VIR, MATE",
				ru = "УБИТЬ НА МЕСТЕ",
				ko = "사살 지령",
				cn = "格杀勿论",
			},
		},
	
		[164869] = {
			readable = "Spectral Chalice",
			icon = 133748,
			model = 203016,
			text = {
				en = "Spectral Chalice",
				es = "Cáliz espectral",
				de = "Spektraler Kelch",
				fr = "Calice spectral",
				it = "Calice Spettrale",
				pt = "Cálice Espectral",
				ru = "Призрачный кубок",
				ko = "유령의 성배",
				cn = "鬼魂之杯",
			},
		},
	
		[164881] = {
			readable = "Cleansed Night Dragon",
			model = 201870,
			text = {
				en = "Cleansed Night Dragon",
				de = "Gesäuberter Nachtdrache",
				fr = "Dragon nocturne purifié",
				ru = "Очищенный Ночной дракон",
			},
		},
	
		[164882] = {
			readable = "Cleansed Songflower",
			model = 201872,
			text = {
				en = "Cleansed Songflower",
				es = "Melodía limpia",
				de = "Gesäuberte Liedblume",
				fr = "Fleur-de-chant purifiée",
				ru = "Очищенный песнецвет",
			},
		},
	
		[164883] = {
			readable = "Cleansed Whipper Root",
			model = 201874,
			text = {
				en = "Cleansed Whipper Root",
				ru = "Очищенный кнутокорень",
			},
		},
	
		[164884] = {
			readable = "Cleansed Windblossom",
			model = 201876,
			text = {
				en = "Cleansed Windblossom",
				es = "Flor del viento limpia",
				de = "Gesäuberte Windblüte",
				fr = "Fleur-de-vent purifiée",
				ru = "Очищенный ветроцвет",
				ko = "정화된 바람꽃",
			},
		},
	
		[164885] = {
			readable = "Corrupted Night Dragon",
			model = 201871,
			text = {
				en = "Corrupted Night Dragon",
				es = "Dragón nocturno corrupto",
				de = "Verderbter Nachtdrache",
				fr = "Dragon nocturne corrompu",
				pt = "Dragão Noturno Corrompido",
				ru = "Оскверненный Ночной дракон",
				ko = "오염된 어둠용풀",
				cn = "被腐化的夜龙草",
			},
		},
	
		[164886] = {
			readable = "Corrupted Songflower",
			model = 201873,
			text = {
				en = "Corrupted Songflower",
				es = "Melodía corrupta",
				de = "Verderbte Liedblume",
				fr = "Fleur-de-chant corrompue",
				pt = "Flor da Canção Corrompida",
				ru = "Оскверненный песнецвет",
				ko = "오염된 노래꽃",
				cn = "被腐化的轻歌花",
			},
		},
	
		[164887] = {
			readable = "Corrupted Windblossom",
			model = 201877,
			text = {
				en = "Corrupted Windblossom",
				es = "Flor del viento corrupta",
				de = "Verderbte Windblüte",
				fr = "Fleur-de-vent corrompue",
				pt = "Botão Selvagem Corrompido",
				ru = "Оскверненный ветроцвет",
				ko = "오염된 바람꽃",
				cn = "被腐化的迎风花",
			},
		},
	
		[164888] = {
			readable = "Corrupted Whipper Root",
			model = 201875,
			text = {
				en = "Corrupted Whipper Root",
				es = "Blancoria corrupta",
				de = "Verderbte Peitscherwurzel",
				fr = "Navetille corrompue",
				pt = "Raiz-açoite Corrompida",
				ru = "Гнилой кнутокорень",
				ko = "오염된 채찍뿌리",
				cn = "被腐化的鞭根草",
			},
		},
	
		[164909] = {
			readable = "Wrecked Row Boat",
			model = 190677,
			text = {
				en = "Wrecked Row Boat",
				es = "Restos de un bote de remos",
				de = "Havariertes Ruderboot",
				fr = "Épave de barque",
				it = "Barca a Remi Distrutta",
				pt = "Canoa Destruída",
				ru = "Разбитая гребная лодка",
				ko = "난파된 나룻배",
				cn = "破损的独木舟",
			},
		},
	
		[164910] = {
			readable = "Ornate Chest",
			icon = 132594,
			model = 196979,
			text = {
				en = "Ornate Chest",
				es = "Cofre ornamentado",
				de = "Verschnörkelte Truhe",
				fr = "Coffre orné",
				it = "Cassa Ornata",
				pt = "Baú Ornamentado",
				ru = "Украшенный сундук",
				ko = "화려한 궤짝",
				cn = "华丽的箱子",
			},
		},
	
		[164911] = {
			readable = "Thunderbrew Lager Keg",
			model = 201058,
			text = {
				en = "Thunderbrew Lager Keg",
				es = "Barril de cerveza Cebatruenos",
				de = "Fässchen mit Donnerbräu Lagerbier",
				fr = "Tonneau de Tonnebière",
				it = "Barile di Birra dei Birratuono",
				pt = "Barril de Cervaforte",
				ru = "Бочонок громоварского светлого",
				ko = "썬더브루 맥주통",
				cn = "雷霆啤酒",
			},
		},
	
		[164953] = {
			readable = "Large Leather Backpacks",
			model = 198989,
			text = {
				en = "Large Leather Backpacks",
				es = "Mochilas de piel grandes",
				de = "Große Lederrucksäcke",
				fr = "Grands sacs à dos en cuir",
				it = "Grosse Sacche in Pelle",
				pt = "Mochilas Grandes de Couro",
				ru = "Большие кожаные рюкзаки",
				ko = "큰 가죽 배낭",
				cn = "大皮包",
			},
		},
	
		[164954] = {
			readable = "Zukk'ash Pod",
			model = 219553,
			text = {
				en = "Zukk'ash Pod",
				es = "Vaina de Zukk'ash",
				de = "Kapsel der Zukk'ash",
				fr = "Alvéole de Zukk'ash",
				it = "Baccello Zukk'ash",
				pt = "Carapaça de Zukk'ash",
				ru = "Кокон Зукк'аш",
				ko = "주크애쉬 고치",
				cn = "祖卡什虫茧",
			},
		},
	
		[164955] = {
			readable = "Northern Crystal Pylon",
			icon = 134087,
			model = 202759,
			text = {
				en = "Northern Crystal Pylon",
				es = "Torre de cristal del Norte",
				de = "Nördlicher Kristallpylon",
				fr = "Pylône de cristal nord",
				it = "Pilastro di Cristallo Settentrionale",
				pt = "Torre de Cristal Norte",
				ru = "Северный хрустальный пилон",
				ko = "북쪽 수정탑",
				cn = "北部水晶塔",
			},
		},
	
		[164956] = {
			readable = "Western Crystal Pylon",
			icon = 134087,
			model = 202759,
			text = {
				en = "Western Crystal Pylon",
				es = "Torre de cristal del Oeste",
				de = "Westlicher Kristallpylon",
				fr = "Pylône de cristal ouest",
				it = "Pilastro di Cristallo Occidentale",
				pt = "Torre de Cristal Oeste",
				ru = "Западный хрустальный пилон",
				ko = "서쪽 수정탑",
				cn = "西部水晶塔",
			},
		},
	
		[164957] = {
			readable = "Eastern Crystal Pylon",
			icon = 134087,
			model = 202759,
			text = {
				en = "Eastern Crystal Pylon",
				es = "Torre de cristal del Este",
				de = "Östlicher Kristallpylon",
				fr = "Pylône de cristal est",
				it = "Pilastro di Cristallo Orientale",
				pt = "Torre de Cristal Oriental",
				ru = "Восточный хрустальный пилон",
				ko = "동쪽 수정탑",
				cn = "东部水晶塔",
			},
		},
	
		[164958] = {
			readable = "Bloodpetal Sprout",
			icon = 134001,
			model = 201087,
			text = {
				en = "Bloodpetal Sprout",
				es = "Brote Sangrepétalo",
				de = "Blutblütensprössling",
				fr = "Pousse de Pétale-de-sang",
				it = "Germoglio Petalorosso",
				pt = "Broto de Pétala Sangrenta",
				ru = "Росток кровоцвета",
				ko = "붉은꽃잎덩굴손 씨눈",
				cn = "血瓣花苗",
			},
		},
	
		[165554] = {
			readable = "Heart of the Mountain",
			icon = 134085,
			model = 203112,
			text = {
				en = "Heart of the Mountain",
				es = "El corazón de la montaña",
				de = "Herz des Berges",
				fr = "Cœur de la montagne",
				it = "Cuore della Montagna",
				pt = "Coração da Montanha",
				ru = "Сердце Горы",
				ko = "산의 정수",
				cn = "山脉之心",
			},
		},
	
		[165658] = {
			readable = "Dark Iron Deposit",
			model = 189103,
			text = {
				en = "Dark Iron Deposit",
				es = "Depósito de hierro negro",
				de = "Dunkeleisenvorkommen",
				fr = "Gisement de sombrefer",
				it = "Deposito di Ferroscuro",
				pt = "Depósito de Ferro Negro",
				ru = "Залежи черного железа",
				ko = "검은무쇠 광맥",
				cn = "黑铁矿脉",
			},
		},
	
		[165738] = {
			readable = "Dark Iron Ale Mug",
			model = 198360,
			text = {
				en = "Dark Iron Ale Mug",
				es = "Jarra de cerveza Hierro Negro",
				de = "Dunkeleisenbierbecher",
				fr = "Chope de bière sombrefer",
				it = "Boccale di Birra dei Ferroscuro",
				pt = "Caneca de Cerveja Ferro Negro",
				ru = "Кружка эля клана Черного Железа",
				ko = "검은무쇠 맥주잔",
				cn = "黑铁酒杯",
			},
		},
	
		[165739] = {
			readable = "Grim Guzzler Boar",
			model = 198228,
			text = {
				en = "Grim Guzzler Boar",
				es = "Jabalí Tragapenas",
				de = "Fleisch aus dem 'Grimmigen Säufer'",
				fr = "Sanglier du Sinistre écluseur",
				it = "Cinghiale del Torvo Beone",
				pt = "Javali do Glutão Implacável",
				ru = "Мясо вепря из \"Угрюмого обжоры\"",
				ko = "주정뱅이 선술집 멧돼지",
				cn = "野猪肉",
			},
		},
	
		[166805] = {
			readable = "Tablet of the Seven - TEST",
			model = 189538,
			text = {
				en = "Tablet of the Seven - TEST",
			},
		},
	
		[166863] = {
			readable = "Fresh Threshadon Carcass",
			icon = 133972,
			model = 202781,
			text = {
				en = "Fresh Threshadon Carcass",
				es = "Cadáver reciente de trillanodonte",
				de = "Frisches Dreschadongerippe",
				fr = "Carcasse fraîche de battrodon",
				it = "Carcassa Fresca di Plesiosauro",
				pt = "Carcaça de Manguadonte Fresca",
				ru = "Свежий труп жесткозуба",
				ko = "방금 죽은 트레샤돈 시체",
				cn = "新鲜的蛇颈龙肉",
			},
		},
	
		[166872] = {
			readable = "Supply Crate",
			model = 200960,
			text = {
				en = "Supply Crate",
				es = "Cajón de suministros",
				de = "Vorratskiste",
				fr = "Caisse de fournitures",
				it = "Cassa di Rifornimenti",
				pt = "Caixote de Suprimentos",
				ru = "Ящик с припасами",
				ko = "보급품 상자",
				cn = "补给箱",
			},
		},
	
		[169217] = {
			readable = "Un'Goro Flat Rock",
			model = 189718,
			text = {
				en = "Un'Goro Flat Rock",
				es = "Roca lisa Un'Goro",
				de = "Flacher Fels von Un'Goro",
				fr = "Plateau d'Un'Goro",
				it = "Pietra Piatta di Un'Goro",
				pt = "Rocha Lisa de Un'Goro",
				ru = "Плоская скала Ун'Горо",
				ko = "운고로 너럭바위",
				cn = "安戈洛平石",
			},
		},
	
		[169243] = {
			readable = "Chest of The Seven",
			icon = 985959,
			model = 200953,
			text = {
				en = "Chest of The Seven",
				es = "Cofre de los Siete",
				de = "Truhe der Sieben",
				fr = "Coffre des sept",
				it = "Cassa dei Sette",
				pt = "Baú dos Sete",
				ru = "Сундук Семерых",
				ko = "일곱 현자의 궤짝",
				cn = "七贤之箱",
			},
		},
	
		[169294] = {
			readable = "Tablet of the Seven",
			model = 189538,
			text = {
				en = "Tablet of the Seven",
				es = "Tablilla de los Siete",
				de = "Schrifttafel der Sieben",
				fr = "Tablette des Sept",
				it = "Tavoletta dei Sette",
				pt = "Tabuletas dos Sete",
				ru = "Табличка Семерых",
				ko = "일곱 현자의 서판",
				cn = "七贤石板",
			},
		},
})
do ObjectDB[objectID] = objectData; end
