local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	
		[240003] = {
			readable = "Strange Sapphire",
			icon = 134131,
			model = 249606,
			text = {
				en = "Strange Sapphire",
				es = "Zafiro extraño",
				de = "Merkwürdiger Saphir",
				fr = "Saphir étrange",
				it = "Strano Zaffiro",
				pt = "Safira Estranha",
				ru = "Странный сапфир",
				ko = "이상한 사파이어",
				cn = "古怪的蓝宝石",
			},
		},
	
		[240006] = {
			readable = "Horde Banner",
			model = 999438,
			text = {
				en = "Horde Banner",
				es = "Estandarte de la Horda",
				de = "Hordebanner",
				fr = "Bannière de la Horde",
				it = "Stendardo dell'Orda",
				pt = "Estandarte da Horda",
				ru = "Знамя Орды",
				ko = "호드 깃발",
			},
		},
	
		[240010] = {
			readable = "Convenient Hiding Spot",
			model = 878865,
			text = {
				en = "Convenient Hiding Spot",
				es = "Escondite conveniente",
				de = "Geeignetes Versteck",
				fr = "Cachette pratique",
				it = "Nascondiglio Comodo",
				pt = "Esconderijo Conveniente",
				ru = "Укромное место",
			},
		},
	
		[240012] = {
			readable = "Soul Gem",
			model = 1042749,
			text = {
				en = "Soul Gem",
				es = "Gema de alma",
				de = "Seelenedelstein",
				fr = "Gemme d’âme",
				it = "Gemma dell'Anima",
				pt = "Gema Anímica",
				ru = "Самоцвет души",
				ko = "영혼 보석",
				cn = "灵魂宝石",
			},
		},
	
		[240016] = {
			readable = "Artificer's Journal",
			model = 916183,
			text = {
				en = "Artificer's Journal",
				es = "Diario de artificiero",
				de = "Tagebuch des Konstrukteurs",
				fr = "Journal de l’artificier",
				it = "Diario dell'Ingegnere",
				pt = "Diário do Artífice",
				ru = "Дневник механолога",
				ko = "기술병의 일지",
				cn = "技师的日记",
			},
		},
	
		[240033] = {
			readable = "Dim Ley Crystal",
			model = 1108689,
			text = {
				en = "Dim Ley Crystal",
				es = "Cristal Ley oscuro",
				de = "Trüber Leykristall",
				fr = "Cristal tellurique terne",
				it = "Cristallo di Faglia Fioco",
				pt = "Cristal do Meridiano Tênue",
				ru = "Тусклый силовой кристалл",
				ko = "희미한 지맥 수정",
				cn = "黯淡的魔网水晶",
			},
		},
	
		[240053] = {
			readable = "Place Crystal",
			model = 201271,
			text = {
				en = "Place Crystal",
				es = "Colocar cristal",
				de = "Kristallmarkierung",
				fr = "Placer le cristal",
				it = "Indicatore Cristallo",
				pt = "Colocar Cristal",
				ru = "Разместить кристалл",
			},
		},
	
		[240071] = {
			readable = "Mogor's Cache",
			model = 953811,
			text = {
				en = "Mogor's Cache",
				es = "Alijo de Mogor",
				de = "Mogors Schatztruhe",
				fr = "Cache de Mogor",
				it = "Cassa di Mogor",
				pt = "Baú de Mogor",
				ru = "Припасы Могора",
			},
		},
	
		[240075] = {
			readable = "Soul Harvester",
			model = 1243752,
			text = {
				en = "Soul Harvester",
				es = "Cosechador de almas",
				de = "Seelenernter",
				fr = "Moissonneuse d’âmes",
				it = "Mietitore d'Anime",
				pt = "Ceifalmas",
				ru = "Пожинатель душ",
				ko = "영혼 수확기",
				cn = "灵魂收割器",
			},
		},
	
		[240111] = {
			readable = "Siegeyard",
			model = 985113,
			text = {
				en = "Siegeyard",
				es = "Campo de asedio",
				de = "Belagerungshof",
				fr = "Cour de siège",
				it = "Campo d'Assedio",
				pt = "Área de Cerco",
				ru = "Осадный двор",
				ko = "공성진지",
				cn = "攻城战场",
			},
		},
	
		[240121] = {
			readable = "Soul Harvester",
			model = 1243752,
			text = {
				en = "Soul Harvester",
				es = "Cosechador de almas",
				de = "Seelenernter",
				fr = "Moissonneuse d’âmes",
				it = "Mietitore d'Anime",
				pt = "Ceifalmas",
				ru = "Пожинатель душ",
				ko = "영혼 수확기",
				cn = "灵魂收割器",
			},
		},
	
		[240122] = {
			readable = "Soul Harvester",
			model = 1243752,
			text = {
				en = "Soul Harvester",
				es = "Cosechador de almas",
				de = "Seelenernter",
				fr = "Moissonneur d’âmes",
				it = "Mietitore d'Anime",
				pt = "Ceifalmas",
				ru = "Пожинатель душ",
				ko = "영혼 수확기",
				cn = "灵魂收割器",
			},
		},
	
		[240123] = {
			readable = "Soul Harvester",
			model = 1243752,
			text = {
				en = "Soul Harvester",
				es = "Cosechador de almas",
				de = "Seelenernter",
				fr = "Moissonneur d’âmes",
				it = "Mietitore d'Anime",
				pt = "Ceifalmas",
				ru = "Пожинатель душ",
				ko = "영혼 수확기",
				cn = "灵魂收割器",
			},
		},
	
		[240124] = {
			readable = "Orb of Dominion",
			model = 1026612,
			text = {
				en = "Orb of Dominion",
				es = "Orbe de dominio",
				de = "Kugel der Herrschaft",
				fr = "Orbe d’assujettissement",
				it = "Globo del Dominio",
				pt = "Orbe do Domínio",
				ru = "Сфера владычества",
			},
		},
	
		[240147] = {
			readable = "Grimoire of the Nameless Void",
			model = 965217,
			text = {
				en = "Grimoire of the Nameless Void",
				es = "Grimorio del Vacío anónimo",
				de = "Foliant der namenlosen Leere",
				fr = "Grimoire du Vide sans nom",
				it = "Grimorio del Vuoto Sconosciuto",
				pt = "Grimório do Vazio Inominável",
				ru = "Гримуар безымянной пустоты",
			},
		},
	
		[240165] = {
			readable = "Grimoire of Haste",
			model = 916168,
			text = {
				en = "Grimoire of Haste",
				es = "Grimorio de celeridad",
				de = "Grimoire der Eile",
				fr = "Grimoire de hâte",
				it = "Libro Arcano della Celerità",
				pt = "Grimório da Aceleração",
				ru = "Гримуар поспешности",
				ko = "가속의 고서",
				cn = "急速魔典",
			},
		},
	
		[240173] = {
			readable = "Sargerei Soulcharger",
			model = 192702,
			text = {
				en = "Sargerei Soulcharger",
				es = "Cargaalmas Sargerei",
				de = "Seelenbrunnen der Sargerei",
				fr = "Chargeur de l’âme sargereï",
				it = "Caricatore d'Anima dei Sargerei",
				pt = "Revigorante Anímico Sargerei",
				ru = "Саргерайский источник душ",
				ko = "살게레이 영혼샘",
				cn = "萨格雷灵魂控制器",
			},
		},
	
		[240190] = {
			readable = "Tanaan Camu Seed",
			model = 193027,
			text = {
				en = "Tanaan Camu Seed",
				es = "Semilla de camu de Tanaan",
				de = "Camusamen von Tanaan",
				fr = "Graine de camu de Tanaan",
				it = "Seme di Camu di Tanaan",
				pt = "Semente de Camu de Tanaan",
				ru = "Семя танаанского каму",
				ko = "타나안 카무 씨앗",
				cn = "塔纳安卡穆之种",
			},
		},
	
		[240194] = {
			readable = "Spire of Woe",
			model = 1467308,
			text = {
				en = "Spire of Woe",
				es = "Púa de la aflicción",
				de = "Pfeiler des Kummers",
				fr = "Flèche de malheur",
				it = "Spira del Dolore",
				pt = "Pináculo do Infortúnio",
				ru = "Шпиль страдания",
				ko = "비통의 첨탑",
				cn = "哀伤尖塔",
			},
		},
	
		[240210] = {
			readable = "Skyfire Parachute",
			model = 534613,
			text = {
				en = "Skyfire Parachute",
				es = "Paracaídas de El Abrasacielos",
				de = "Fallschirm der Himmelsfeuer",
				fr = "Parachute du Brûleciel",
				it = "Paracadute della Fuoco Celeste",
				pt = "Paraquedas do Celesfogo",
				ru = "Парашют \"Небесного огня\"",
				ko = "하늘불꽃호 낙하산",
			},
		},
	
		[240215] = {
			readable = "Ashes of a Fallen Crusader",
			model = 193184,
			text = {
				en = "Ashes of a Fallen Crusader",
				es = "Cenizas de un cruzado caído",
				de = "Asche eines gefallenen Kreuzfahrers",
				fr = "Cendres d’un croisé déchu",
				it = "Ceneri del Crociato Caduto",
				pt = "Cinzas de um Cruzado Caído",
				ru = "Прах павшего рыцаря",
				ko = "타락한 성전사의 재",
				cn = "阵亡北伐军的骨灰",
			},
		},
	
		[240222] = {
			readable = "Cache of Infernals",
			model = 192333,
			text = {
				en = "Cache of Infernals",
				es = "Alijo de infernales",
				de = "Höllenbestienvorrat",
				fr = "Cache d’infernaux",
				it = "Cassa di Infernali",
				pt = "Esconderijo de Infernais",
				ru = "Склад инферналов",
				ko = "지옥불정령의 보관 장소",
				cn = "地狱火宝箱",
			},
		},
	
		[240235] = {
			readable = "Skyfire Propeller",
			model = 1128012,
			text = {
				en = "Skyfire Propeller",
				es = "Hélice de El Abrasacielos",
				de = "Rotor der Himmelsfeuer",
				fr = "Propulseur du Brûleciel",
				it = "Elica della Fuoco Celeste",
				pt = "Hélice do Celesfogo",
				ru = "Винт \"Небесного огня\"",
				ko = "하늘불꽃호 프로펠러",
				cn = "天火号螺旋桨",
			},
		},
	
		[240267] = {
			readable = "Cracked Ley Crystal",
			model = 1332821,
			text = {
				en = "Cracked Ley Crystal",
				es = "Cristal Ley rajado",
				de = "Gesprungener Leykristall",
				fr = "Cristal tellurique fêlé",
				it = "Cristallo di Faglia Spaccato",
				pt = "Cristal do Meridiano Rachado",
				ru = "Потрескавшийся силовой кристалл",
				ko = "금이 간 지맥 수정",
				cn = "开裂的魔网水晶",
			},
		},
	
		[240286] = {
			readable = "Crystal Oscillator",
			model = 255125,
			text = {
				en = "Crystal Oscillator",
				es = "Oscilador de cristal",
				de = "Kristalloszillator",
				fr = "Oscillateur de cristal",
				it = "Oscillatore di Cristallo",
				pt = "Oscilador de Cristal",
				ru = "Кристаллический осциллятор",
				ko = "수정 진동자",
				cn = "水晶振荡器",
			},
		},
	
		[240289] = {
			readable = "Weathered Axe",
			icon = 132416,
			model = 1015733,
			text = {
				en = "Weathered Axe",
				es = "Hacha deteriorada",
				de = "Verwitterte Axt",
				fr = "Hache abîmée",
				it = "Ascia Logora",
				pt = "Machado Desgastado",
				ru = "Потертый топор",
				cn = "风化的斧子",
			},
		},
	
		[240317] = {
			readable = "Iskar's Tome of Shadows",
			model = 382932,
			text = {
				en = "Iskar's Tome of Shadows",
				es = "Escrito de las Sombras de Iskar",
				de = "Iskars Foliant der Schatten",
				fr = "Tome des ombres d’Iskar",
				it = "Tomo delle Ombre di Iskar",
				pt = "Tomo das Sombras de Iskar",
				ru = "Фолиант теней Искара",
				ko = "이스카르의 어둠의 고서",
				cn = "艾斯卡的暗影之书",
			},
		},
	
		[240323] = {
			readable = "Libram of Fel Knowledge",
			model = 1125315,
			text = {
				en = "Libram of Fel Knowledge",
				es = "Tratado sobre conocimiento vil",
				de = "Buchband der Dämonenkunde",
				fr = "Libram de savoir gangrené",
				it = "Libram della Conoscenza Vile",
				pt = "Incunábulo do Conhecimento Vil",
				ru = "Манускрипт знаний Скверны",
				ko = "지옥 지식의 성서",
				cn = "邪魔知识圣契",
			},
		},
	
		[240345] = {
			readable = "Inscribed Ruin",
			model = 975358,
			text = {
				en = "Inscribed Ruin",
				es = "Ruina con inscripciones",
				de = "Ruineninschrift",
				fr = "Ruine gravée",
				it = "Rovine Incise",
				pt = "Ruína Inscrita",
				ru = "Покрытая письменами развалина",
				ko = "문양이 새겨진 잔해",
				cn = "铭文废墟",
			},
		},
	
		[240346] = {
			readable = "Olive Sprig",
			model = 1278256,
			text = {
				en = "Olive Sprig",
				es = "Rama de olivo",
				de = "Olivenzweig",
				fr = "Rameau d’olivier",
				it = "Ramoscello d'Olivo",
				pt = "Ramo de Oliveira",
				ru = "Побег оливы",
				ko = "올리브 가지",
				cn = "橄榄树枝",
			},
		},
	
		[240347] = {
			readable = "Message to Iskar",
			model = 968334,
			text = {
				en = "Message to Iskar",
				es = "Mensaje a Iskar",
				de = "Nachricht an Iskar",
				fr = "Message à Iskar",
				it = "Messaggio per Iskar",
				pt = "Mensagem para Iskar",
				ru = "Послание Искару",
				ko = "이스카르에게 보내는 전갈",
				cn = "给艾斯卡的信",
			},
		},
	
		[240348] = {
			readable = "Shrine to Terokk",
			model = 191859,
			text = {
				en = "Shrine to Terokk",
				es = "Santuario de Terokk",
				de = "Terokkschrein",
				fr = "Sanctuaire de Terokk",
				it = "Santuario di Terokk",
				pt = "Altar de Terokk",
				ru = "Святилище Терокка",
				ko = "테로크의 제단",
				cn = "泰罗克圣坛",
			},
		},
	
		[240353] = {
			readable = "Seemingly Unguarded Treasure",
			model = 200136,
			text = {
				en = "Seemingly Unguarded Treasure",
				es = "Tesoro aparentemente sin vigilancia",
				de = "Scheinbar unbehüteter Schatz",
				fr = "Trésor apparemment pas gardé",
				it = "Tesoro Apparentemente Incustodito",
				pt = "Tesouro Aparentemente Desprotegido",
				ru = "Похоже, никем не охраняемые сокровища",
				ko = "아무도 지키지 않는 듯한 보물",
				cn = "看似无人看守的宝藏",
			},
		},
	
		[240354] = {
			readable = "Genuinely Unguarded Treasure",
			model = 200136,
			text = {
				en = "Genuinely Unguarded Treasure",
				es = "Tesoro realmente sin vigilancia",
				de = "Tatsächlich unbehüteter Schatz",
				fr = "Trésor vraiment pas gardé",
				it = "Tesoro Non Sorvegliato",
				pt = "Tesouro Desprotegido de Verdade",
				ru = "Точно никем не охраняемые сокровища",
				cn = "看似无人看守的宝藏",
			},
		},
	
		[240357] = {
			readable = "Strange Stone",
			model = 851097,
			text = {
				en = "Strange Stone",
				es = "Piedra extraña",
				de = "Merkwürdiger Stein",
				fr = "Pierre étrange",
				it = "Strana Pietra",
				pt = "Pedra Estranha",
				ru = "Странный камень",
				ko = "이상한 돌",
			},
		},
	
		[240358] = {
			readable = "Strange Stone",
			model = 917943,
			text = {
				en = "Strange Stone",
				es = "Piedra extraña",
				de = "Merkwürdiger Stein",
				fr = "Pierre étrange",
				it = "Strana Pietra",
				pt = "Pedra Estranha",
				ru = "Странный камень",
				ko = "이상한 돌",
			},
		},
	
		[240360] = {
			readable = "Drained Blood Crystal",
			model = 192714,
			text = {
				en = "Drained Blood Crystal",
				es = "Cristal de sangre drenado",
				de = "Erschöpfter Blutkristall",
				fr = "Cristal de sang drainé",
				it = "Cristallo di Sangue Prosciugato",
				pt = "Cristal de Sangue Drenado",
				ru = "Опустошенный кровавый кристалл",
				ko = "고갈된 핏빛 수정",
				cn = "枯竭的血水晶",
			},
		},
	
		[240365] = {
			readable = "Tethering Post",
			model = 969525,
			text = {
				en = "Tethering Post",
				es = "Poste de amarre",
				de = "Anbindepfosten",
				fr = "Poteau d’attache",
				it = "Posto di Legatura",
				pt = "Poste de Amarração",
				ru = "Столбик для привязи",
				ko = "밧줄 기둥",
				cn = "牧桩",
			},
		},
	
		[240414] = {
			readable = "Blackrock Cargo Car",
			model = 996698,
			text = {
				en = "Blackrock Cargo Car",
				es = "Vagón de carga Roca Negra",
				de = "Schwarzfelsgüterwaggon",
				fr = "Wagon de marchandises rochenoire",
				it = "Veicolo Merci dei Roccianera",
				pt = "Carro de Carga da Rocha Negra",
				ru = "Грузовой вагон Черной горы",
				ko = "검은바위 화물차",
				cn = "黑石货车",
			},
		},
	
		[240425] = {
			readable = "Dark Scryer",
			model = 1101712,
			text = {
				en = "Dark Scryer",
				es = "Arúspice oscuro",
				de = "Dunkler Wahrsager",
				fr = "Scrutateur des ténèbres",
				it = "Veggente Oscuro",
				pt = "Áugure Sombrio",
				ru = "Темный провидец",
				ko = "암흑 점술 도구",
				cn = "黑暗占星者",
			},
		},
	
		[240517] = {
			readable = "Explosive Charges",
			model = 968120,
			text = {
				en = "Explosive Charges",
				es = "Cargas explosivas",
				de = "Sprengladungen",
				fr = "Charges explosives",
				it = "Cariche Esplosive",
				pt = "Cargas Explosivas",
				ru = "Взрывчатка",
				ko = "폭발물",
				cn = "炸弹",
			},
		},
	
		[240518] = {
			readable = "Detonator",
			model = 979393,
			text = {
				en = "Detonator",
				es = "Detonador",
				de = "Zünder",
				fr = "Détonateur",
				it = "Detonatore",
				pt = "Detonador",
				ru = "Детонатор",
				ko = "기폭장치",
				cn = "引爆器",
			},
		},
	
		[240519] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[240525] = {
			readable = "Detonator",
			model = 979393,
			text = {
				en = "Detonator",
				es = "Detonador",
				de = "Zünder",
				fr = "Détonateur",
				it = "Detonatore",
				pt = "Detonador",
				ru = "Детонатор",
				ko = "기폭장치",
			},
		},
	
		[240535] = {
			readable = "Legion Cage",
			model = 1125322,
			text = {
				en = "Legion Cage",
				es = "Jaula de la Legión",
				de = "Käfig der Legion",
				fr = "Cage de la Légion",
				it = "Gabbia della Legione",
				pt = "Jaula da Legião",
				ru = "Клетка Легиона",
				ko = "군단 우리",
				cn = "军团牢笼",
			},
		},
	
		[240543] = {
			readable = "Stolen Captain's Chest",
			model = 953811,
			text = {
				en = "Stolen Captain's Chest",
				es = "Cofre del capitán robado",
				de = "Gestohlene Kapitänskiste",
				fr = "Coffre volé du capitaine",
				it = "Cassa del Capitano Rubata",
				pt = "Baú do Capitão Roubado",
				ru = "Украденный сундук капитана",
				ko = "도둑맞은 선장의 궤짝",
				cn = "失窃的船长宝箱",
			},
		},
	
		[240547] = {
			readable = "Orc Skull",
			model = 1097781,
			text = {
				en = "Orc Skull",
				es = "Calavera de orco",
				de = "Orcschädel",
				fr = "Crâne d’Orc",
				it = "Teschio di Orco",
				pt = "Crânio de Orc",
				ru = "Череп орка",
				ko = "오크 해골",
				cn = "兽人头骨",
			},
		},
	
		[240552] = {
			readable = "Tidestone Core",
			model = 1134486,
			text = {
				en = "Tidestone Core",
				es = "Núcleo de la Piedramar",
				de = "Kern des Gezeitensteins",
				fr = "Cœur de la Pierre-des-Marées",
				it = "Nucleo della Pietra delle Maree",
				pt = "Núcleo de Pedramar",
				ru = "Ядро Приливного Камня",
				ko = "해일석 핵",
				cn = "潮汐之石核心",
			},
		},
	
		[240567] = {
			readable = "Salvage Goods",
			model = 1006536,
			text = {
				en = "Salvage Goods",
				es = "Bienes recuperados",
				de = "Bergungsgut",
				fr = "Marchandises de récupération",
				it = "Merci della Rappresaglia della Regina",
				pt = "Mercadorias Recuperadas",
				ru = "Спасенные припасы",
				ko = "인양된 물품",
				cn = "回收的货物",
			},
		},
	
		[240568] = {
			readable = "Bass Blaster",
			model = 219382,
			text = {
				en = "Bass Blaster",
				es = "Revientabajos",
				de = "Bass-Blaster",
				fr = "Caisson de basses",
				it = "Equalizzatore dei Bassi",
				pt = "Bomba de Grave",
				ru = "Басовая примочка",
				ko = "저음 증폭기",
			},
		},
	
		[240569] = {
			readable = "Salvage Goods",
			model = 1006537,
			text = {
				en = "Salvage Goods",
				es = "Bienes recuperados",
				de = "Bergungsgut",
				fr = "Marchandises de récupération",
				it = "Merci della Rappresaglia della Regina",
				pt = "Mercadorias Recuperadas",
				ru = "Спасенные припасы",
				ko = "인양된 물품",
				cn = "回收的货物",
			},
		},
	
		[240570] = {
			readable = "Eye Holder",
			model = 1097379,
			text = {
				en = "Eye Holder",
				es = "Recipiente del ojo",
				de = "Augenhalter",
				fr = "Socle oculaire",
				it = "Poggiaocchio",
				pt = "Suporte de Olho",
				ru = "Вместилище глаз",
				ko = "눈 보관함",
				cn = "眼球存放处",
			},
		},
	
		[240575] = {
			readable = "Laz-Tron Disc Reader",
			model = 197760,
			text = {
				en = "Laz-Tron Disc Reader",
				es = "Lector de discos Lasertron",
				de = "Laz-Tron-Laufwerk",
				fr = "Lecteur de disques Laz-tron",
				it = "Mangiaschede Lasertronico",
				pt = "Toca-disco-tron",
				ru = "Устройство для считывания лаз-троновых дисков",
			},
		},
	
		[240577] = {
			readable = "The Blade of Kra'nak",
			icon = 916552,
			model = 1064785,
			text = {
				en = "The Blade of Kra'nak",
				es = "El filo de Kra'nak",
				de = "Die Klinge von Kra'nak",
				fr = "Lame de Kra’nak",
				it = "Lama di Kra'nak",
				pt = "A Lâmina de Kra'nak",
				ru = "Меч Кра'нака",
				ko = "크라나크의 칼날",
				cn = "卡纳克之刃",
			},
		},
	
		[240580] = {
			readable = "Jewel of Hellfire",
			icon = 1137541,
			model = 192714,
			text = {
				en = "Jewel of Hellfire",
				es = "Joya de Fuego Infernal",
				de = "Höllenfeuerjuwel",
				fr = "Joyau des Flammes infernales",
				it = "Gioiello del Fuoco Infernale",
				pt = "Joia do Fogo do Inferno",
				ru = "Самоцвет Адского Пламени",
				ko = "지옥불 보석",
				cn = "地狱火珠宝",
			},
		},
	
		[240586] = {
			readable = "Cursed Bones",
			model = 190437,
			text = {
				en = "Cursed Bones",
				es = "Huesos malditos",
				de = "Verfluchte Knochen",
				fr = "Ossements maudits",
				it = "Ossa Maledette",
				pt = "Ossos Amaldiçoados",
				ru = "Проклятые кости",
				ko = "저주받은 뼈",
				cn = "被诅咒的骨头",
			},
		},
	
		[240600] = {
			readable = "Volatile Barrel",
			model = 194845,
			text = {
				en = "Volatile Barrel",
				es = "Barril volátil",
				de = "Explosives Fass",
				fr = "Tonneau instable",
				it = "Barile Instabile",
				pt = "Barril Volátil",
				ru = "Бочка с нестабильной субстанцией",
				ko = "불안정한 통",
				cn = "爆裂桶",
			},
		},
	
		[240601] = {
			readable = "Spirit Lodge Work Order",
			model = 1033921,
			text = {
				en = "Spirit Lodge Work Order",
				es = "Pedido del recinto de los espíritus",
				de = "Arbeitsauftrag des Geisterhauses",
				fr = "Commande de l’autel des esprits",
				it = "Produzione del Rifugio degli Spiriti",
				pt = "Ordem de Serviço da Tenda dos Espíritos",
				ru = "Заказ из Обители Духов",
				ko = "정기의 오두막 제품",
				cn = "灵魂小屋产品订单",
			},
		},
	
		[240602] = {
			readable = "Mage Tower Work Order",
			model = 950137,
			text = {
				en = "Mage Tower Work Order",
				es = "Pedido de la torre de magos",
				de = "Arbeitsauftrag des Magierturms",
				fr = "Commande de la tour des mages",
				it = "Produzione della Torre della Magia",
				pt = "Ordem de Serviço da Torre dos Magos",
				ru = "Заказ из башни магов",
				ko = "마법사 탑 제품",
				cn = "法师塔产品订单",
			},
		},
	
		[240603] = {
			readable = "Cursed Seaweed",
			model = 438016,
			text = {
				en = "Cursed Seaweed",
				es = "Algas malditas",
				de = "Verfluchter Seetang",
				fr = "Algue maudite",
				it = "Alga Marina Maledetta",
				pt = "Algas Marinhas Amaldiçoadas",
				ru = "Проклятые водоросли",
				ko = "저주받은 해초",
				cn = "被诅咒的海草",
			},
		},
	
		[240605] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[240608] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[240609] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[240612] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[240614] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[240616] = {
			readable = "Frozen Supplies",
			icon = 133647,
			model = 874403,
			text = {
				en = "Frozen Supplies",
				es = "Suministros congelados",
				de = "Vereiste Vorräte",
				fr = "Fournitures gelées",
				it = "Forniture Congelate",
				pt = "Suprimentos Congelados",
				ru = "Замороженные припасы",
				cn = "冰封的补给品",
			},
		},
	
		[240617] = {
			readable = "Lost Sentinel's Pouch",
			icon = 133642,
			model = 571710,
			text = {
				en = "Lost Sentinel's Pouch",
				es = "Faltriquera del centinela perdido",
				de = "Beutel der verlorenen Schildwache",
				fr = "Bourse de la sentinelle perdue",
				it = "Sacca della Sentinella Perduta",
				pt = "Bolsa da Sentinela Perdida",
				ru = "Мешок потерявшегося часового",
				cn = "遗失的哨兵袋子",
			},
		},
	
		[240619] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[240622] = {
			readable = "Warden's Scroll Case",
			model = 521201,
			text = {
				en = "Warden's Scroll Case",
				es = "Tubo de pergamino del celador",
				de = "Schriftrollenbehälter des Wächters",
				fr = "Étui à parchemin du gardien",
				it = "Portapergamene del Custode",
				pt = "Estojo de Pergaminhos do Guardião",
				ru = "Футляр для свитков Стражницы",
				ko = "감시자의 두루마리 통",
				cn = "守望者的卷轴匣",
			},
		},
	
		[240623] = {
			readable = "Sylvanas' Strongbox",
			icon = 1041430,
			model = 195121,
			text = {
				en = "Sylvanas' Strongbox",
				es = "Caja fuerte de Sylvanas",
				de = "Sylvanas' Schließkiste",
				fr = "Coffre de Sylvanas",
				it = "Forziere di Sylvanas",
				pt = "Caixa-forte de Sylvana",
				ru = "Сейф Сильваны",
				cn = "希尔瓦娜斯的保险箱",
			},
		},
	
		[240624] = {
			readable = "Faerie Dragon Nest",
			icon = 841541,
			model = 975382,
			text = {
				en = "Faerie Dragon Nest",
				es = "Nido de dragón feérico",
				de = "Feendrachennest",
				fr = "Nid de dragon féerique",
				it = "Nido di Drago Fatato",
				pt = "Ninho de Dragoleta",
				ru = "Гнездо чудесного дракончика",
				cn = "精灵龙巢穴",
			},
		},
	
		[240625] = {
			readable = "High Priestess' Reliquary",
			icon = 1769068,
			model = 942843,
			text = {
				en = "High Priestess' Reliquary",
				es = "Relicario de la suma sacerdotisa",
				de = "Re­li­qui­ar der Hohepriesterin",
				fr = "Reliquaire de la grande prêtresse",
				it = "Reliquiario della Gran Sacerdotessa",
				pt = "Relicário da Alta-sacerdotisa",
				ru = "Реликварий верховной жрицы",
				ko = "대여사제의 성물함",
				cn = "高阶祭司的匣子",
			},
		},
	
		[240629] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[240630] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[240631] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[240634] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[240635] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[240637] = {
			readable = "Glimmering Treasure Chest",
			model = 1349622,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[240638] = {
			readable = "Disputed Treasure",
			model = 1349621,
			text = {
				en = "Disputed Treasure",
				es = "Tesoro disputado",
				de = "Umkämpfter Schatz",
				fr = "Coffre au trésor",
				it = "Tesoro Conteso",
				pt = "Tesouro Disputado",
				ru = "Оспариваемые сокровища",
				ko = "논란의 보물 상자",
				cn = "有争议的宝藏",
			},
		},
	
		[240639] = {
			readable = "Glimmering Treasure Chest",
			model = 1349622,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[240641] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[240642] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[240643] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[240644] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[240645] = {
			readable = "Glimmering Treasure Chest",
			model = 1349622,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[240646] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[240649] = {
			readable = "Small Treasure Chest",
			model = 1402263,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[240650] = {
			readable = "Ritual Circle",
			model = 986958,
			text = {
				en = "Ritual Circle",
				es = "Círculo ritual",
				de = "Ritualkreis",
				fr = "Cercle rituel",
				it = "Circolo del Rituale",
				pt = "Círculo Ritual",
				ru = "Ритуальный круг",
				ko = "의식 진",
				cn = "仪式圆环",
			},
		},
	
		[240651] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[240652] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[240653] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[240654] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[240655] = {
			readable = "Glimmering Treasure Chest",
			model = 1349622,
			text = {
				en = "Glimmering Treasure Chest",
				es = "Arqueta brillante",
				de = "Glitzernde Schatztruhe",
				fr = "Coffre au trésor scintillant",
				it = "Cassa del Tesoro Luccicante",
				pt = "Baú do Tesouro Luzente",
				ru = "Сверкающий сундук с сокровищами",
				ko = "반짝이는 보물 상자",
				cn = "闪闪发光的宝箱",
			},
		},
	
		[240657] = {
			readable = "Small Treasure Chest",
			model = 1349620,
			text = {
				en = "Small Treasure Chest",
				es = "Arqueta pequeña",
				de = "Kleine Schatztruhe",
				fr = "Petit coffre au trésor",
				it = "Cassa del Tesoro Piccola",
				pt = "Baú do Tesouro Pequeno",
				ru = "Маленький сундук с сокровищами",
				ko = "작은 보물 상자",
				cn = "小宝箱",
			},
		},
	
		[240665] = {
			readable = "Ley Portal",
			model = 166523,
			text = {
				en = "Ley Portal",
				es = "Portal Ley",
				de = "Leyportal",
				fr = "Portail tellurique",
				it = "Portale della Faglia",
				pt = "Portal Meridional",
				ru = "Силовой портал",
				ko = "지맥 차원문",
				cn = "魔网传送门",
			},
		},
	
		[240666] = {
			readable = "Ley Portal",
			model = 166523,
			text = {
				en = "Ley Portal",
				es = "Portal Ley",
				de = "Leyportal",
				fr = "Portail tellurique",
				it = "Portale della Faglia",
				pt = "Portal Meridional",
				ru = "Силовой портал",
				ko = "지맥 차원문",
				cn = "魔网传送门",
			},
		},
	
		[240677] = {
			readable = "Climbing Treads",
			model = 1005465,
			text = {
				en = "Climbing Treads",
				es = "Botines de escalada",
				de = "Kletterschuhe",
				fr = "Bottines d’escalade",
				it = "Stivaletti da Arrampicata",
				pt = "Botinas de Escalada",
				ru = "Горные ботфорты",
				ko = "등산 신발",
				cn = "登山鞋",
			},
		},
	
		[240681] = {
			readable = "Oiled Cloak",
			model = 198148,
			text = {
				en = "Oiled Cloak",
				es = "Capa aceitada",
				de = "Gefetteter Umhang",
				fr = "Cape huilée",
				it = "Mantello Cerato",
				pt = "Manto Oleado",
				ru = "Промасленный плащ",
				ko = "기름 묻은 망토",
				cn = "浸油斗篷",
			},
		},
	
		[240685] = {
			readable = "Fel Soul Drainer",
			model = 1042749,
			text = {
				en = "Fel Soul Drainer",
				es = "Drenador de almas vil",
				de = "Dämonischer Seelentrinker",
				fr = "Drain d’âme gangrené",
				it = "Vilrisucchiatore di Anime",
				pt = "Drenador de Almas Vil",
				ru = "Конденсатор душ Скверны",
			},
		},
	
		[240686] = {
			readable = "Fel Soul Drainer",
			model = 1042749,
			text = {
				en = "Fel Soul Drainer",
				es = "Drenador de almas vil",
				de = "Dämonischer Seelentrinker",
				fr = "Drain d’âme gangrené",
				it = "Vilrisucchiatore di Anime",
				pt = "Drenador de Almas Vil",
				ru = "Конденсатор душ Скверны",
			},
		},
	
		[240688] = {
			readable = "Corrupted Soul Focus",
			model = 937587,
			text = {
				en = "Corrupted Soul Focus",
				es = "Enfoque de alma corrupta",
				de = "Verderbter Seelenfokus",
				fr = "Focalisateur d’âme corrompue",
				it = "Focus d'Anima Corrotto",
				pt = "Foco Anímico Corrompido",
				ru = "Оскверненное средоточие душ",
			},
		},
	
		[240690] = {
			readable = "Treasure Chest",
			model = 1349621,
			text = {
				en = "Treasure Chest",
				es = "Arqueta",
				de = "Schatztruhe",
				fr = "Coffre au trésor",
				it = "Cassa del Tesoro",
				pt = "Baú do Tesouro",
				ru = "Сундук с сокровищами",
				ko = "보물 상자",
				cn = "宝箱",
			},
		},
	
		[240788] = {
			readable = "Bubble",
			model = 1119940,
			text = {
				en = "Bubble",
				es = "Burbuja",
				de = "Blase",
				fr = "Bulle",
				it = "Bolla",
				pt = "Bolha",
				ru = "Пузырь",
				ko = "거품",
				cn = "气泡",
			},
		},
	
		[240855] = {
			readable = "Tome of Secrets",
			icon = 133736,
			model = 916178,
			text = {
				en = "Tome of Secrets",
				es = "Escrito de secretos",
				de = "Foliant der Geheimnisse",
				fr = "Grimoire des secrets",
				it = "Tomo dei Segreti",
				pt = "Tomo dos Segredos",
				ru = "Книга тайн",
				ko = "비법의 고서",
				cn = "隐秘之书",
			},
		},
	
		[240885] = {
			readable = "Portal to Vol'mar",
			model = 1237455,
			text = {
				en = "Portal to Vol'mar",
				es = "Portal a Vol'mar",
				de = "Portal nach Vol'mar",
				fr = "Portail vers Vol’mar",
				it = "Portale per Vol'mar",
				pt = "Portal para Vol'mar",
				ru = "Портал в Вол'мар",
			},
		},
	
		[240886] = {
			readable = "Portal to Lion's Watch",
			model = 1237456,
			text = {
				en = "Portal to Lion's Watch",
				es = "Portal a la Avanzada de León",
				de = "Portal zur Löwenwacht",
				fr = "Portail vers le guet du Lion",
				it = "Portale per il Presidio del Leone",
				pt = "Portal para a Vigília do Leão",
				ru = "Портал в Львиный дозор",
			},
		},
	
		[240888] = {
			readable = "Letter from Kilrogg",
			model = 985170,
			text = {
				en = "Letter from Kilrogg",
				es = "Carta de Kilrogg",
				de = "Brief von Kilrogg",
				fr = "Lettre de Kilrogg",
				it = "Lettera da Kilrogg",
				pt = "Carta de Kilrogg",
				ru = "Письмо от Килрогга",
				ko = "킬로그의 편지",
				cn = "基尔罗格的信",
			},
		},
	
		[240889] = {
			readable = "Magril's Journal",
			model = 985165,
			text = {
				en = "Magril's Journal",
				es = "Diario de Magril",
				de = "Magrils Tagebuch",
				fr = "Journal de Magril",
				it = "Diario di Magril",
				pt = "Diário de Magril",
				ru = "Дневник Магрила",
				ko = "마그릴의 일지",
				cn = "玛格尔的日记",
			},
		},
	
		[240914] = {
			readable = "Ammunition Pile",
			model = 959550,
			text = {
				en = "Ammunition Pile",
				es = "Montón de munición",
				de = "Munitionsstapel",
				fr = "Pile de munitions",
				it = "Mucchio di Munizioni",
				pt = "Pilha de Munição",
				ru = "Груда боеприпасов",
				ko = "탄약 더미",
				cn = "弹药堆",
			},
		},
})
do ObjectDB[objectID] = objectData; end
