-------------------------------------------
--     S E C R E T S     M O D U L E     --
-------------------------------------------

root(ROOTS.Secrets, {
	header(HEADERS.Spell, 231215, bubbleDownSelf({ ["timeline"] = { ADDED_7_2_0 } }, {	-- Sun Darter Hatchling
		["displayID"] = 74529,
		["description"] = createLocalizationString({
			readable = "***This secret requires you to have debug mode enabled to see the consumables/steps. To enable debug mode right click the ATT icon on the minimap, navigate to the general tab and check the \"|Cff15abffDebug Mode|r |cFFFFFFFF(Show Everything)|r\" box.*** \n\nIt also requires the battle pet Perky Pug from the Dungeons and Raids achievement Looking For Multitudes.\n\nEnjoy!\n\n!Note If coords are not plotting, you might need to make a standalone item, plot it, and then plot again from the main list.",
			constant = "THIS_SECRET_REQUIRES_YOU_TO_HAVE_DEBUG_MODE",
			export = true,
			text = {
				en = "***This secret requires you to have debug mode enabled to see the consumables/steps. To enable debug mode right click the ATT icon on the minimap, navigate to the general tab and check the \"|Cff15abffDebug Mode|r |cFFFFFFFF(Show Everything)|r\" box.*** \n\nIt also requires the battle pet Perky Pug from the Dungeons and Raids achievement Looking For Multitudes.\n\nEnjoy!\n\n!Note If coords are not plotting, you might need to make a standalone item, plot it, and then plot again from the main list.",
				-- TODO: de = "",
				-- TODO: es = "",
				-- TODO: mx = "",
				-- TODO: fr = "",
				-- TODO: it = "",
				-- TODO: ko = "",
				-- TODO: pt = "",
				-- TODO: ru = "",
				cn = "***此秘密需要你开启调试模式才能看到消耗品/步骤。要开启调试模式，请右键点击小地图上的 ATT 图标，进入“通用”标签页，勾选“|Cff15abff调试模式|r |cFFFFFFFF（显示全部）|r”复选框。*** \n\n它还需要来自地下城与团队副本成就“寻找大军”的战斗宠物活泼的哈巴狗。\n\n祝你好运！\n\n!注意：如果坐标没有标出，你可能需要创建一个独立物品，标出它，然后再从主列表中标出一次。",
				-- TODO: tw = "",
			},
		}),
		["groups"] = {
			o(9999908, {	-- Step 1: Gather Consumables.
				["description"] = createLocalizationString({
					readable = "|cFFFFFFFFSTEP 1:|r Gather the following quantity of consumables:",
					constant = "CFFFFFFFFSTEP_1_R_GATHER_THE_FOLLOWING_QUANTITY",
					export = true,
					text = {
						en = "|cFFFFFFFFSTEP 1:|r Gather the following quantity of consumables:",
						-- TODO: de = "",
						-- TODO: es = "",
						-- TODO: mx = "",
						-- TODO: fr = "",
						-- TODO: it = "",
						-- TODO: ko = "",
						-- TODO: pt = "",
						-- TODO: ru = "",
						cn = "|cFFFFFFFF第 1 步：|r 收集以下数量的消耗品：",
						-- TODO: tw = "",
					},
				}),
				["groups"] = {
					i(38320, {	-- Dire Brew
						["description"] = createLocalizationString({
							readable = "Qty:1\n\nObtained from Dark Iron Brewer in BRD.\n\nWalk/fly to BRD, or use the Direbrew's Remote obtained from Brewfest. Once inside the instance, take a left through the gate, and then right through another gate. Go through the door on the left, and click the Shadowforge Lock at the back of the room. Backtrack to the door, go up the ramp and take a left down the hallway. Continue down the hallway, until it opens up. Take the first right into \"The Manufactory\". Head right and through the door at the back of the room, over the bridge and into \"The Grim Guzzler\". Go up the stairs on the right and in the back of the room on the left is the Dark Iron Brewer. Talk to him until he passes out, and loot the Dire Brew that spawns.",
							constant = "QTY_1_OBTAINED_FROM_DARK_IRON_BREWER_IN_BRD",
							export = true,
							text = {
								en = "Qty:1\n\nObtained from Dark Iron Brewer in BRD.\n\nWalk/fly to BRD, or use the Direbrew's Remote obtained from Brewfest. Once inside the instance, take a left through the gate, and then right through another gate. Go through the door on the left, and click the Shadowforge Lock at the back of the room. Backtrack to the door, go up the ramp and take a left down the hallway. Continue down the hallway, until it opens up. Take the first right into \"The Manufactory\". Head right and through the door at the back of the room, over the bridge and into \"The Grim Guzzler\". Go up the stairs on the right and in the back of the room on the left is the Dark Iron Brewer. Talk to him until he passes out, and loot the Dire Brew that spawns.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "数量：1\n\n从黑石深渊的黑铁酿酒师处获得。\n\n步行或飞往黑石深渊，或使用从美酒节获得的德雷布遥控器。进入副本后，向左穿过大门，然后向右穿过另一道门。穿过左侧的门，点击房间后方的暗炉锁。沿原路回到那道门，走上斜坡，然后向左沿走廊前进。沿走廊一直走到开阔处。在第一个路口右转进入“制造厂”。向右前进，穿过房间后方的门，过桥进入“恐怖酒杯”。走上右侧的楼梯，房间后部左侧就是黑铁酿酒师。与他交谈直到他醉倒，然后拾取刷出的恐怖酒。",
								-- TODO: tw = "",
							},
						}),
						["groups"] = {
							n(144128, {	-- Dark Iron Brewer
								["coords"] = {
									{ 21.0, 38.3, BURNING_STEPPES },	-- Blackrock Mountain
									{ 55.0, 84.5, BLACKROCK_MOUNTAIN_LEVEL3 },	-- Entrance by MC
									{ 39.0, 18.3, BLACKROCK_MOUNTAIN_LEVEL3 },	-- BRD Entrance
									{ 49.8, 60.9, 243 },	-- Inside Instance
									{ 49.8, 31.6, BLACKROCK_DEPTHS },	-- Inside Instance
								},
							}),
						},
					}),
					i(44958, {	-- Ethereal Oil
						["description"] = createLocalizationString({
							readable = "Qty:1\n\nPurchase on the AH or make your own (Alchemy).",
							constant = "QTY_1_PURCHASE_ON_THE_AH_OR_MAKE_YOUR_OWN",
							export = true,
							text = {
								en = "Qty:1\n\nPurchase on the AH or make your own (Alchemy).",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "数量：1\n\n在拍卖行购买或自行制作（炼金术）。",
								-- TODO: tw = "",
							},
						}),
					}),
					i(18258, {	-- Gordok Ogre Suit
						["description"] = createLocalizationString({
							readable = "Qty:1\n\nPurchase on the AH, make your own (pre Cata Tailors/Leatherworkers only), or head to Dire Maul North.\n\nOnce inside find Knot Thimblejack near Guard Slip'kik, and complete his quest for the suit.",
							constant = "QTY_1_PURCHASE_ON_THE_AH_MAKE_YOUR_OWN_PRE_CATA",
							export = true,
							text = {
								en = "Qty:1\n\nPurchase on the AH, make your own (pre Cata Tailors/Leatherworkers only), or head to Dire Maul North.\n\nOnce inside find Knot Thimblejack near Guard Slip'kik, and complete his quest for the suit.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "数量：1\n\n在拍卖行购买，自己制作（仅限大灾变前的裁缝/制皮），或前往厄运之槌北区。\n\n进入后，在卫兵斯利基克附近找到诺特·希姆加克，完成他的任务即可获得这套衣服。",
								-- TODO: tw = "",
							},
						}),
					}),
					i(103789, {	-- "Little Princess" Costume
						["description"] = createLocalizationString({
							readable = "Qty:1\n\nPurchase on the AH or from the vendors below:",
							constant = "QTY_1_PURCHASE_ON_THE_AH_OR_FROM_THE_VENDORS",
							export = true,
							text = {
								en = "Qty:1\n\nPurchase on the AH or from the vendors below:",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "数量：1\n\n在拍卖行或从下列商人处购买：",
								-- TODO: tw = "",
							},
						}),
						["groups"] = {
							n(142065, {	-- Dana Pull
								["description"] = createLocalizationString({
									readable = "Boralus",
									constant = "BORALUS",
									export = true,
									text = {
										en = "Boralus",
										-- TODO: de = "",
										-- TODO: es = "",
										-- TODO: mx = "",
										-- TODO: fr = "",
										-- TODO: it = "",
										-- TODO: ko = "",
										-- TODO: pt = "",
										-- TODO: ru = "",
										cn = "伯拉勒斯",
										-- TODO: tw = "",
									},
								}),
								["coord"] = { 50.8, 46.0, BORALUS },
								["races"] = ALLIANCE_ONLY,
							}),
							n(98725, {	-- Lio the Lioness <Battle Pet Master>
								["description"] = createLocalizationString({
									readable = "Legion Dalaran or Garrison",
									constant = "LEGION_DALARAN_OR_GARRISON",
									export = true,
									text = {
										en = "Legion Dalaran or Garrison",
										-- TODO: de = "",
										-- TODO: es = "",
										-- TODO: mx = "",
										-- TODO: fr = "",
										-- TODO: it = "",
										-- TODO: ko = "",
										-- TODO: pt = "",
										-- TODO: ru = "",
										cn = "军团再临达拉然或要塞",
										-- TODO: tw = "",
									},
								}),
								["coords"] = {
									{ 59.2, 39.6, LEGION_DALARAN },
									{ 29.2, 40.4, LUNARFALL },
								},
								["races"] = ALLIANCE_ONLY,
							}),
							n(141614, {	-- Koari <Pet Supplies>
								["description"] = createLocalizationString({
									readable = "Dazar'alor",
									constant = "DAZAR_ALOR",
									export = true,
									text = {
										en = "Dazar'alor",
										-- TODO: de = "",
										-- TODO: es = "",
										-- TODO: mx = "",
										-- TODO: fr = "",
										-- TODO: it = "",
										-- TODO: ko = "",
										-- TODO: pt = "",
										-- TODO: ru = "",
										cn = "达萨罗",
										-- TODO: tw = "",
									},
								}),
								["coord"] = { 34.8, 13.1, DAZARALOR },
								["races"] = HORDE_ONLY,
							}),
							n(115287, {	-- Serr'ah <Battle Pet Master>
								["description"] = "~L.LEGION_DALARAN_OR_GARRISON",
								["coords"] = {
									{ 58.6, 38.0, LEGION_DALARAN },
									{ 32.6, 42.8, FROSTWALL },
								},
								["races"] = HORDE_ONLY,
							}),
							n(73293, {	-- Whizzig <Merchant of Time>
								["description"] = createLocalizationString({
									readable = "Limited time vendor on Timeless Isle",
									constant = "LIMITED_TIME_VENDOR_ON_TIMELESS_ISLE",
									export = true,
									text = {
										en = "Limited time vendor on Timeless Isle",
										-- TODO: de = "",
										-- TODO: es = "",
										-- TODO: mx = "",
										-- TODO: fr = "",
										-- TODO: it = "",
										-- TODO: ko = "",
										-- TODO: pt = "",
										-- TODO: ru = "",
										cn = "永恒岛上的限时商人",
										-- TODO: tw = "",
									},
								}),
								["coords"] = {
									{ 41.6, 47.2, TIMELESS_ISLE },
									{ 35.0, 52.8, TIMELESS_ISLE },
									{ 42.8, 59.4, TIMELESS_ISLE },
									{ 40.0, 63.0, TIMELESS_ISLE },
								},
							}),
						},
					}),
					i(22845, {	-- Major Arcane Protection Potion
						["description"] = "~L.QTY_1_PURCHASE_ON_THE_AH_OR_MAKE_YOUR_OWN",
					}),
					i(22841, {	-- Major Fire Protection Potion
						["description"] = "~L.QTY_1_PURCHASE_ON_THE_AH_OR_MAKE_YOUR_OWN",
					}),
					i(22842, {	-- Major Frost Protection Potion
						["description"] = "~L.QTY_1_PURCHASE_ON_THE_AH_OR_MAKE_YOUR_OWN",
					}),
					i(22847, {	-- Major Holy Protection Potion
						["description"] = "~L.QTY_1_PURCHASE_ON_THE_AH_OR_MAKE_YOUR_OWN",
					}),
					i(22844, {	-- Major Nature Protection Potion
						["description"] = "~L.QTY_1_PURCHASE_ON_THE_AH_OR_MAKE_YOUR_OWN",
					}),
					i(22846, {	-- Major Shadow Protection Potion
						["description"] = "~L.QTY_1_PURCHASE_ON_THE_AH_OR_MAKE_YOUR_OWN",
					}),
					i(8529, {	-- Noggenfogger Elixir
						["description"] = createLocalizationString({
							readable = "Qty:20\n\nPurchase from Sprinkle Noggenfogger in Tanaris.",
							constant = "QTY_20_PURCHASE_FROM_SPRINKLE_NOGGENFOGGER_IN",
							export = true,
							text = {
								en = "Qty:20\n\nPurchase from Sprinkle Noggenfogger in Tanaris.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "数量：20\n\n从塔纳利斯的斯普林克·诺格弗格处购买。",
								-- TODO: tw = "",
							},
						}),
						["groups"] = {
							n(98844, {	-- Sprinkle Noggenfogger
								["coord"] = { 51.2, 29.8, TANARIS },
							}),
						},
					}),
					n(37865, {	-- Perky Pug
						["description"] = createLocalizationString({
							readable = "Qty:1\n\nObtained from the Dungeons & Raids achievement \"Looking for Multitudes\".",
							constant = "QTY_1_OBTAINED_FROM_THE_DUNGEONS_RAIDS",
							export = true,
							text = {
								en = "Qty:1\n\nObtained from the Dungeons & Raids achievement \"Looking for Multitudes\".",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "数量：1\n\n从地下城与团队副本成就“寻求大众”获得。",
								-- TODO: tw = "",
							},
						}),
					}),
					i(40195, {	-- Pygmy Oil
						["description"] = createLocalizationString({
							readable = "Qty:20\n\nPurchase on the AH or make your own (Alchemy).",
							constant = "QTY_20_PURCHASE_ON_THE_AH_OR_MAKE_YOUR_OWN",
							export = true,
							text = {
								en = "Qty:20\n\nPurchase on the AH or make your own (Alchemy).",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "数量：20\n\n在拍卖行购买或自己制作（炼金术）。",
								-- TODO: tw = "",
							},
						}),
					}),
					i(89373, {	-- Scotty's Lucky Coin
						["description"] = createLocalizationString({
							readable = "Qty:1\n\nObtained from killing Scotty in Townlong Steppes.\n\nScotty's behind the Mantid house in the middle of the tree, so either walk around the left side of the house, or fly just above the house down into the crevice.",
							constant = "QTY_1_OBTAINED_FROM_KILLING_SCOTTY_IN_TOWNLONG",
							export = true,
							text = {
								en = "Qty:1\n\nObtained from killing Scotty in Townlong Steppes.\n\nScotty's behind the Mantid house in the middle of the tree, so either walk around the left side of the house, or fly just above the house down into the crevice.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "数量：1\n\n在螳螂高原击杀斯科蒂获得。\n\n斯科蒂在螳螂妖房屋后方、树的中部，所以你可以从房屋左侧绕过去，或者从房屋正上方飞下进入裂缝。",
								-- TODO: tw = "",
							},
						}),
						["groups"] = {
							n(66162, {	-- Scotty
								["coord"] = { 21.6, 46.5, TOWNLONG_STEPPES },
							}),
						},
					}),
					i(955, {	-- Scroll of Intellect
						["description"] = createLocalizationString({
							readable = "Qty:1\n\nPurchase on the AH, make your own (Inscription), or buy in limited quantities from the vendors below:",
							constant = "QTY_1_PURCHASE_ON_THE_AH_MAKE_YOUR_OWN",
							export = true,
							text = {
								en = "Qty:1\n\nPurchase on the AH, make your own (Inscription), or buy in limited quantities from the vendors below:",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "数量：1\n\n在拍卖行购买，自己制作（铭文），或从下列商人处限量购买：",
								-- TODO: tw = "",
							},
						}),
						["groups"] = {
							n(1316, {	-- Adair Gilroy <Librarian>
								["description"] = createLocalizationString({
									readable = "Stormwind",
									constant = "STORMWIND",
									export = true,
									text = {
										en = "Stormwind",
										-- TODO: de = "",
										-- TODO: es = "",
										-- TODO: mx = "",
										-- TODO: fr = "",
										-- TODO: it = "",
										-- TODO: ko = "",
										-- TODO: pt = "",
										-- TODO: ru = "",
										cn = "暴风城",
										-- TODO: tw = "",
									},
								}),
								["coord"] = { 51.8, 74.8, STORMWIND_CITY },
								["races"] = ALLIANCE_ONLY,
							}),
							n(958, {	-- Dawn Brightstar <Arcane Goods>
								["description"] = createLocalizationString({
									readable = "Elwynn Forest",
									constant = "ELWYNN_FOREST",
									export = true,
									text = {
										en = "Elwynn Forest",
										-- TODO: de = "",
										-- TODO: es = "",
										-- TODO: mx = "",
										-- TODO: fr = "",
										-- TODO: it = "",
										-- TODO: ko = "",
										-- TODO: pt = "",
										-- TODO: ru = "",
										cn = "艾尔文森林",
										-- TODO: tw = "",
									},
								}),
								["coord"] = { 64.8, 69.2, ELWYNN_FOREST },
								["races"] = ALLIANCE_ONLY,
							}),
							n(16224, {	-- Rathis Tomber <Trade Supplies>
								["description"] = createLocalizationString({
									readable = "Ghostlands",
									constant = "GHOSTLANDS",
									export = true,
									text = {
										en = "Ghostlands",
										-- TODO: de = "",
										-- TODO: es = "",
										-- TODO: mx = "",
										-- TODO: fr = "",
										-- TODO: it = "",
										-- TODO: ko = "",
										-- TODO: pt = "",
										-- TODO: ru = "",
										cn = "幽魂之地",
										-- TODO: tw = "",
									},
								}),
								["coord"] = { 47.2, 28.6, GHOSTLANDS },
								["races"] = HORDE_ONLY,
							}),
							n(4581, {	-- Rathis Tomber <Trade Supplies>
								["description"] = createLocalizationString({
									readable = "Undercity",
									constant = "UNDERCITY",
									export = true,
									text = {
										en = "Undercity",
										-- TODO: de = "",
										-- TODO: es = "",
										-- TODO: mx = "",
										-- TODO: fr = "",
										-- TODO: it = "",
										-- TODO: ko = "",
										-- TODO: pt = "",
										-- TODO: ru = "",
										cn = "幽暗城",
										-- TODO: tw = "",
									},
								}),
								["coord"] = { 77.6, 38.6, UNDERCITY },
								["races"] = HORDE_ONLY,
							}),
						},
					}),
					i(12820, {	-- Winterfall Firewater
						["description"] = createLocalizationString({
							readable = "Qty:1\n\nPurchase on the AH, or farm Winterfall furbolgs in Winterspring.",
							constant = "QTY_1_PURCHASE_ON_THE_AH_OR_FARM_WINTERFALL",
							export = true,
							text = {
								en = "Qty:1\n\nPurchase on the AH, or farm Winterfall furbolgs in Winterspring.",
								-- TODO: de = "",
								-- TODO: es = "",
								-- TODO: mx = "",
								-- TODO: fr = "",
								-- TODO: it = "",
								-- TODO: ko = "",
								-- TODO: pt = "",
								-- TODO: ru = "",
								cn = "数量：1\n\n在拍卖行购买，或在冬泉谷刷冬泉熊怪。",
								-- TODO: tw = "",
							},
						}),
					}),
				},
			}),
			o(9999909, {	-- Step 2: Cavern of Consumption
				["description"] = createLocalizationString({
					readable = "|cFFFFFFFFSTEP 2:|r Once you have gathered all of the consumables go to Caverns of Consumption on the North coast of Winterspring, and travel through the cavern to the fire barrier.\n\n***Before you continue, make sure you have 30-40 mins to finish the remaining steps***",
					constant = "CFFFFFFFFSTEP_2_R_ONCE_YOU_HAVE_GATHERED_ALL_OF",
					export = true,
					text = {
						en = "|cFFFFFFFFSTEP 2:|r Once you have gathered all of the consumables go to Caverns of Consumption on the North coast of Winterspring, and travel through the cavern to the fire barrier.\n\n***Before you continue, make sure you have 30-40 mins to finish the remaining steps***",
						-- TODO: de = "",
						-- TODO: es = "",
						-- TODO: mx = "",
						-- TODO: fr = "",
						-- TODO: it = "",
						-- TODO: ko = "",
						-- TODO: pt = "",
						-- TODO: ru = "",
						cn = "|cFFFFFFFF第 2 步：|r 收集齐所有消耗品后，前往冬泉谷北海岸的吞噬洞穴，穿过洞穴抵达火焰屏障。\n\n***在继续之前，请确保你有 30-40 分钟来完成剩余步骤***",
						-- TODO: tw = "",
					},
				}),
				["coords"] = {
					{ 57.2, 14.0, KALIMDOR },	-- Cave Entrance
				},
			}),
			o(9999910, {	-- Step 3: Fire Barrier
				["description"] = createLocalizationString({
					readable = "|cFFFFFFFFSTEP 3:|r Use the Major Fire Protection Potion, and pass through the Fire Barrier.",
					constant = "CFFFFFFFFSTEP_3_R_USE_THE_MAJOR_FIRE_PROTECTION",
					export = true,
					text = {
						en = "|cFFFFFFFFSTEP 3:|r Use the Major Fire Protection Potion, and pass through the Fire Barrier.",
						-- TODO: de = "",
						-- TODO: es = "",
						-- TODO: mx = "",
						-- TODO: fr = "",
						-- TODO: it = "",
						-- TODO: ko = "",
						-- TODO: pt = "",
						-- TODO: ru = "",
						cn = "|cFFFFFFFF第 3 步：|r 使用强效火焰防护药水，穿过火焰屏障。",
						-- TODO: tw = "",
					},
				}),
			}),
			o(9999911, {	-- Step 4: Prismatic Barrier
				["description"] = createLocalizationString({
					readable = "|cFFFFFFFFSTEP 4:|r Use the rest of the Major Potions and pass through the Prismatic Barrier.",
					constant = "CFFFFFFFFSTEP_4_R_USE_THE_REST_OF_THE_MAJOR",
					export = true,
					text = {
						en = "|cFFFFFFFFSTEP 4:|r Use the rest of the Major Potions and pass through the Prismatic Barrier.",
						-- TODO: de = "",
						-- TODO: es = "",
						-- TODO: mx = "",
						-- TODO: fr = "",
						-- TODO: it = "",
						-- TODO: ko = "",
						-- TODO: pt = "",
						-- TODO: ru = "",
						cn = "|cFFFFFFFF第 4 步：|r 使用剩余的强效药水，穿过棱彩屏障。",
						-- TODO: tw = "",
					},
				}),
			}),
			o(9999912, {	-- Step 5: Diligent Watcher
				["description"] = createLocalizationString({
					readable = "|cFFFFFFFFSTEP 5:|r Use Noggenfogger Elixir until you turn into a Skeleton, then walk past the Diligent Watcher.",
					constant = "CFFFFFFFFSTEP_5_R_USE_NOGGENFOGGER_ELIXIR_UNTIL",
					export = true,
					text = {
						en = "|cFFFFFFFFSTEP 5:|r Use Noggenfogger Elixir until you turn into a Skeleton, then walk past the Diligent Watcher.",
						-- TODO: de = "",
						-- TODO: es = "",
						-- TODO: mx = "",
						-- TODO: fr = "",
						-- TODO: it = "",
						-- TODO: ko = "",
						-- TODO: pt = "",
						-- TODO: ru = "",
						cn = "|cFFFFFFFF第 5 步：|r 使用诺格弗格药剂直到你变成骷髅，然后走过勤勉的守望者。",
						-- TODO: tw = "",
					},
				}),
				["cost"] = {
					{ "i", 8529, 1 },	-- Noggenfogger Elixir
				},
			}),
			o(9999913, {	-- Step 6: Vine Barrier
				["description"] = createLocalizationString({
					readable = "|cFFFFFFFFSTEP 6:|r On the right will be a Wall of Vines. Use Scotty's Lucky Coin, pass through the vines, and loot a Water Stone from the water.",
					constant = "CFFFFFFFFSTEP_6_R_ON_THE_RIGHT_WILL_BE_A_WALL",
					export = true,
					text = {
						en = "|cFFFFFFFFSTEP 6:|r On the right will be a Wall of Vines. Use Scotty's Lucky Coin, pass through the vines, and loot a Water Stone from the water.",
						-- TODO: de = "",
						-- TODO: es = "",
						-- TODO: mx = "",
						-- TODO: fr = "",
						-- TODO: it = "",
						-- TODO: ko = "",
						-- TODO: pt = "",
						-- TODO: ru = "",
						cn = "|cFFFFFFFF第 6 步：|r 右侧会有一堵藤蔓之墙。使用斯科蒂的幸运硬币，穿过藤蔓，并从水中拾取一块水之石。",
						-- TODO: tw = "",
					},
				}),
				["cost"] = {
					{ "i", 89373, 1 },	-- Scotty's Lucky Coin
				},
				["groups"] = {
					o(272434, {	-- Water Stone
						["coord"] = { 47.9, 1.5, WINTERSPRING },
						["groups"] = { i(147455) },	-- Water Stone
					}),
				},
			}),
			o(9999914, {	-- Step 7: Water Barrier
				["description"] = createLocalizationString({
					readable = "|cFFFFFFFFSTEP 7:|r Use the Water Stone, backtrack to the Blue Barrier and walk through ever so slightly.",
					constant = "CFFFFFFFFSTEP_7_R_USE_THE_WATER_STONE_BACKTRACK",
					export = true,
					text = {
						en = "|cFFFFFFFFSTEP 7:|r Use the Water Stone, backtrack to the Blue Barrier and walk through ever so slightly.",
						-- TODO: de = "",
						-- TODO: es = "",
						-- TODO: mx = "",
						-- TODO: fr = "",
						-- TODO: it = "",
						-- TODO: ko = "",
						-- TODO: pt = "",
						-- TODO: ru = "",
						cn = "|cFFFFFFFF第 7 步：|r 使用水之石，返回蓝色屏障处并非常小心地穿过去。",
						-- TODO: tw = "",
					},
				}),
				["cost"] = {
					{ "i", 147455, 1 },	-- Water Stone
				},
			}),
			o(9999915, {	-- Step 8: Stone Watcher
				["description"] = createLocalizationString({
					readable = "|cFFFFFFFFSTEP 8:|r Use the Dire Brew and walk past the Stone Watcher.",
					constant = "CFFFFFFFFSTEP_8_R_USE_THE_DIRE_BREW_AND_WALK",
					export = true,
					text = {
						en = "|cFFFFFFFFSTEP 8:|r Use the Dire Brew and walk past the Stone Watcher.",
						-- TODO: de = "",
						-- TODO: es = "",
						-- TODO: mx = "",
						-- TODO: fr = "",
						-- TODO: it = "",
						-- TODO: ko = "",
						-- TODO: pt = "",
						-- TODO: ru = "",
						cn = "|cFFFFFFFF第 8 步：|r 使用恐怖酿造，走过石之守望者。",
						-- TODO: tw = "",
					},
				}),
			}),
			o(9999916, {	-- Step 9: Ethereal Barrier
				["description"] = createLocalizationString({
					readable = "|cFFFFFFFFSTEP 9:|r Go up the ramp on the right to the Purple Transparent Barrier. Use Ethereal Oil and walk through the barrier to the Strange Stone in the back.",
					constant = "CFFFFFFFFSTEP_9_R_GO_UP_THE_RAMP_ON_THE_RIGHT",
					export = true,
					text = {
						en = "|cFFFFFFFFSTEP 9:|r Go up the ramp on the right to the Purple Transparent Barrier. Use Ethereal Oil and walk through the barrier to the Strange Stone in the back.",
						-- TODO: de = "",
						-- TODO: es = "",
						-- TODO: mx = "",
						-- TODO: fr = "",
						-- TODO: it = "",
						-- TODO: ko = "",
						-- TODO: pt = "",
						-- TODO: ru = "",
						cn = "|cFFFFFFFF第 9 步：|r 沿右侧斜坡上去，到达紫色透明屏障。使用虚灵之油，穿过屏障到达后方的奇怪的石头。",
						-- TODO: tw = "",
					},
				}),
			}),
			o(9999917, {	-- Step 10: Strange Stone
				["description"] = createLocalizationString({
					readable = "|cFFFFFFFFSTEP 10:|r At the Strange Stone, use the Gordok Ogre Suit & Wintefall Firewater. Select the Strange Stones dialogue \"Stick arm in stone\" and receive Sign of the Second debuff.",
					constant = "CFFFFFFFFSTEP_10_R_AT_THE_STRANGE_STONE_USE_THE",
					export = true,
					text = {
						en = "|cFFFFFFFFSTEP 10:|r At the Strange Stone, use the Gordok Ogre Suit & Wintefall Firewater. Select the Strange Stones dialogue \"Stick arm in stone\" and receive Sign of the Second debuff.",
						-- TODO: de = "",
						-- TODO: es = "",
						-- TODO: mx = "",
						-- TODO: fr = "",
						-- TODO: it = "",
						-- TODO: ko = "",
						-- TODO: pt = "",
						-- TODO: ru = "",
						cn = "|cFFFFFFFF第 10 步：|r 在奇怪的石头处，使用戈多克食人魔装和冬泉火酒。选择奇怪的石头的对话“把手臂伸进石头”，并获得第二印记减益。",
						-- TODO: tw = "",
					},
				}),	-- n(54213)	-- Strange Stone
			}),
			o(9999918, {	-- Step 11: Metal Gate
				["description"] = createLocalizationString({
					readable = "|cFFFFFFFFSTEP 11:|r Backtrack to the gate and use the Pygmy Oil until you turn into a Pygmy. Walk through the gate to the Wisdom Cube.",
					constant = "CFFFFFFFFSTEP_11_R_BACKTRACK_TO_THE_GATE_AND",
					export = true,
					text = {
						en = "|cFFFFFFFFSTEP 11:|r Backtrack to the gate and use the Pygmy Oil until you turn into a Pygmy. Walk through the gate to the Wisdom Cube.",
						-- TODO: de = "",
						-- TODO: es = "",
						-- TODO: mx = "",
						-- TODO: fr = "",
						-- TODO: it = "",
						-- TODO: ko = "",
						-- TODO: pt = "",
						-- TODO: ru = "",
						cn = "|cFFFFFFFF第 11 步：|r 返回大门处，使用俾格米油直到你变成俾格米人。穿过大门前往智慧方块。",
						-- TODO: tw = "",
					},
				}),
			}),
			o(9999919, {	-- Step 12: Wisdom Cube
				["description"] = createLocalizationString({
					readable = "|cFFFFFFFFSTEP 12:|r At the Wisdom Cube summon Perky Pug and use the Little Princess Costume on it. Select the Wisdom Cubes dialogue \"<Place arm beneath cube.>\" and receive Sign of the First debuff.",
					constant = "CFFFFFFFFSTEP_12_R_AT_THE_WISDOM_CUBE_SUMMON",
					export = true,
					text = {
						en = "|cFFFFFFFFSTEP 12:|r At the Wisdom Cube summon Perky Pug and use the Little Princess Costume on it. Select the Wisdom Cubes dialogue \"<Place arm beneath cube.>\" and receive Sign of the First debuff.",
						-- TODO: de = "",
						-- TODO: es = "",
						-- TODO: mx = "",
						-- TODO: fr = "",
						-- TODO: it = "",
						-- TODO: ko = "",
						-- TODO: pt = "",
						-- TODO: ru = "",
						cn = "|cFFFFFFFF第 12 步：|r 在智慧方块处召唤精力充沛的哈巴狗，并对它使用小公主套装。选择智慧方块的对话“<把手臂放在方块下方。>”，并获得第一印记减益。",
						-- TODO: tw = "",
					},
				}),	-- n(53730)	-- Wisdom Cube
			}),
			o(9999920, {	-- Step 13: Tarnished Plaque
				["description"] = createLocalizationString({
					readable = "|cFFFFFFFFSTEP 13a:|r Backtrack down the ramp to the now opened gate. DO NOT JUMP OFF. Enter the room and on a pillar on the right will be a Tarnished Plaque. Click on it.\n\nThe Tarnished Plaque reads:\n\n\"The greatest of achievments begins\nwith the smallest leap of the mind.\"\n\n|cFFFFFFFFSTEP 13b:|r After reading the Tarnished Plaque, click off at least one buff and use the Scroll of Intellect.",
					constant = "CFFFFFFFFSTEP_13A_R_BACKTRACK_DOWN_THE_RAMP_TO",
					export = true,
					text = {
						en = "|cFFFFFFFFSTEP 13a:|r Backtrack down the ramp to the now opened gate. DO NOT JUMP OFF. Enter the room and on a pillar on the right will be a Tarnished Plaque. Click on it.\n\nThe Tarnished Plaque reads:\n\n\"The greatest of achievments begins\nwith the smallest leap of the mind.\"\n\n|cFFFFFFFFSTEP 13b:|r After reading the Tarnished Plaque, click off at least one buff and use the Scroll of Intellect.",
						-- TODO: de = "",
						-- TODO: es = "",
						-- TODO: mx = "",
						-- TODO: fr = "",
						-- TODO: it = "",
						-- TODO: ko = "",
						-- TODO: pt = "",
						-- TODO: ru = "",
						cn = "|cFFFFFFFF第 13a 步：|r 沿斜坡返回现已打开的大门。不要跳下去。进入房间，右侧的一根柱子上会有一块失去光泽的牌匾。点击它。\n\n失去光泽的牌匾上写着：\n\n“最伟大的成就，\n始于心灵最小的一跃。”\n\n|cFFFFFFFF第 13b 步：|r 阅读失去光泽的牌匾后，至少取消一个增益，并使用智力卷轴。",
						-- TODO: tw = "",
					},
				}),
			}),
			o(272487, {	-- Step 14: Oddly-Colored Egg
				["coord"] = { 50.9, 2.3, WINTERSPRING },
				["modelScale"] = 2,
				["questID"] = 48022,
				["isWeekly"] = true,
				["description"] = createLocalizationString({
					readable = "|cFFFFFFFFSTEP 14:|r DO NOT JUMP IN WATER. Walk to the edge of water on the right, behind the plaque, where the cavern slopes down into the water. Walk across the water and loot the egg.\n\nCongrats on your new pet!!! \n\n!Don't forget to turn off debug mode now that you are done.",
					constant = "CFFFFFFFFSTEP_14_R_DO_NOT_JUMP_IN_WATER_WALK_TO",
					export = true,
					text = {
						en = "|cFFFFFFFFSTEP 14:|r DO NOT JUMP IN WATER. Walk to the edge of water on the right, behind the plaque, where the cavern slopes down into the water. Walk across the water and loot the egg.\n\nCongrats on your new pet!!! \n\n!Don't forget to turn off debug mode now that you are done.",
						-- TODO: de = "",
						-- TODO: es = "",
						-- TODO: mx = "",
						-- TODO: fr = "",
						-- TODO: it = "",
						-- TODO: ko = "",
						-- TODO: pt = "",
						-- TODO: ru = "",
						cn = "|cFFFFFFFF第 14 步：|r 不要跳进水里。走到右侧水边、牌匾后方岩洞向水中倾斜的位置。走过水面并拾取蛋。\n\n恭喜你获得新宠物！！！\n\n！完成后别忘了关闭调试模式。",
						-- TODO: tw = "",
					},
				}),
				["groups"] = { i(142223) },	-- Sun Darter Hatchling (PET!)
			}),
		},
	})),
});
