-------------------------------------------
--     S E C R E T S     M O D U L E     --
-------------------------------------------

root(ROOTS.Secrets, header(HEADERS.Item, 162690, bubbleDownSelf({ ["timeline"] = { ADDED_8_0_1_LAUNCH } }, {	-- Waist of Time
	["description"] = createLocalizationString({
		readable = "***Quest tracking enabled is required to see all the steps.***\n\nYou will need uncommon quality Windwool Hood, Deathsilk Shoulders, Netherweave Tunic, Frostwoven Leggings, as well as Proximo's Rudius, Rough Wooden Staff, Punctured Pelt, and Formula: Enchant Ring - Striking later on in the secret. It is recommended that you have flying and the Ever-Shifting Mirror toy for ease of travel between Draenor and Outland.",
		constant = "QUEST_TRACKING_ENABLED_IS_REQUIRED_TO_SEE_ALL_4",
		export = true,
		text = {
			en = "***Quest tracking enabled is required to see all the steps.***\n\nYou will need uncommon quality Windwool Hood, Deathsilk Shoulders, Netherweave Tunic, Frostwoven Leggings, as well as Proximo's Rudius, Rough Wooden Staff, Punctured Pelt, and Formula: Enchant Ring - Striking later on in the secret. It is recommended that you have flying and the Ever-Shifting Mirror toy for ease of travel between Draenor and Outland.",
			-- TODO: de = "",
			-- TODO: es = "",
			-- TODO: mx = "",
			-- TODO: fr = "",
			-- TODO: it = "",
			-- TODO: ko = "",
			-- TODO: pt = "",
			-- TODO: ru = "",
			cn = "***必须开启任务追踪才能看到所有步骤。***\n\n在该秘密的后续过程中，你需要优秀品质的风绒兜帽、亡丝护肩、灵纹外套、霜纹护腿，以及普罗克西莫的短剑、粗糙的木杖、穿孔的毛皮和公式：附魔戒指 - 打击。建议你拥有飞行能力以及永变之镜玩具，以便在德拉诺和外域之间往来。",
			-- TODO: tw = "",
		},
	}),
	["lvl"] = 110,
	["groups"] = {
		hqt(52829, name(HEADERS.NPC, 141941, {	-- Summon Baa'l
			["displayID"] = 80456,	-- Baa'l
			["sourceQuests"] = { 52828 },
			["description"] = createLocalizationString({
				readable = "Summon Baa'l from Pet Journal.\n\nSouls fEast on the enDless shrieKing, in darKNess they writhe and scream, yOu WiLl join thEm, toGether forEver morE!",
				constant = "SUMMON_BAA_L_FROM_PET_JOURNAL_SOULS_FEAST_ON",
				export = true,
				text = {
					en = "Summon Baa'l from Pet Journal.\n\nSouls fEast on the enDless shrieKing, in darKNess they writhe and scream, yOu WiLl join thEm, toGether forEver morE!",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "从宠物手册中召唤巴尔。\n\n灵魂以无尽的尖啸为食，在黑暗中扭动与尖叫，你也将加入他们，永远在一起！",
					-- TODO: tw = "",
				},
			}),
		})),
		o(294096, {	-- Lit Orb	-- Summoned Baal' at this location and 52829 triggered, possibly his emote text  "Souls fEast on the enDless shrieKing, in darKNess they writhe and scream, yOu WiLl join thEm, toGether forEver morE!"
			["model"] = 1046021,
			["questID"] = 52830,	-- Orb click
			["sourceQuests"] = { 52829 },
			["description"] = createLocalizationString({
				readable = "Your journey continues in Spires of Arak. You must have summoned Baa'l at least once before you can continue. \n\nInside the small basket \n\nThe Orb Reads: \n\n\"<Something is written here.>\n\nPassive Ice Veins\"",
				constant = "YOUR_JOURNEY_CONTINUES_IN_SPIRES_OF_ARAK_YOU",
				export = true,
				text = {
					en = "Your journey continues in Spires of Arak. You must have summoned Baa'l at least once before you can continue. \n\nInside the small basket \n\nThe Orb Reads: \n\n\"<Something is written here.>\n\nPassive Ice Veins\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "你的旅程将在阿拉克峰继续。你必须至少召唤过巴阿尔一次才能继续。\n\n在小篮子里\n\n宝珠上写着：\n\n“<这里写着些什么。>\n\n被动冰脉”",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 35.5, 32.0, SPIRES_OF_ARAK },	-- Lit Orb
		}),
		o(294097, {	-- Strange Seed
			["model"] = 940623,
			["modelScale"] = 2,
			["questID"] = 52831,
			["sourceQuests"] = { 52830 },
			["description"] = createLocalizationString({
				readable = "Stormwind City\n\nThe Strange Seed reads: \n\n\"<Something is written here.>\n\nSadness, Keynoted\"",
				constant = "STORMWIND_CITY_THE_STRANGE_SEED_READS_SOMETHING",
				export = true,
				text = {
					en = "Stormwind City\n\nThe Strange Seed reads: \n\n\"<Something is written here.>\n\nSadness, Keynoted\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "暴风城\n\n奇怪的种子上面写着：\n\n“<这里写着什么。>\n\n悲伤，主旨”",
					-- TODO: tw = "",
				},
			}),
			["coords"] = {
				{ 17.5, 56.5, ELWYNN_FOREST },
				{ 43.3, 77.9, EASTERN_KINGDOMS },
			},
		}),
		o(294098, {	-- Tiny Frog
			["model"] = 367326,
			["modelScale"] = .5,
			["questID"] = 52898,
			["sourceQuests"] = { 52831 },
			["description"] = createLocalizationString({
				readable = "Spires of Arak\n\nUnderwater on top of the large rock. \n\nThe Tiny Frog says:\n\n\"<Something is written here.>\n\nDog wig moss?\"",
				constant = "SPIRES_OF_ARAK_UNDERWATER_ON_TOP_OF_THE_LARGE",
				export = true,
				text = {
					en = "Spires of Arak\n\nUnderwater on top of the large rock. \n\nThe Tiny Frog says:\n\n\"<Something is written here.>\n\nDog wig moss?\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "阿拉克峰\n\n在水下的大岩石上。\n\n小青蛙说着：\n\n“<这里写着什么。>\n\n狗假发苔藓？”",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 53.5, 10.8, SPIRES_OF_ARAK },	-- Tiny Frog
		}),
		o(294099, {	-- Brittle Bone
			["model"] = 774346,
			["modelScale"] = .5,
			["questID"] = 52899,
			["sourceQuests"] = { 52898 },
			["description"] = createLocalizationString({
				readable = "Blades Edge Mountains\n\nOn the ground next to a crystal. \n\nThe Brittle Bone reads:\n\n\"<Something is written here.>\n\nRage, Shank Sever\"",
				constant = "BLADES_EDGE_MOUNTAINS_ON_THE_GROUND_NEXT_TO_A",
				export = true,
				text = {
					en = "Blades Edge Mountains\n\nOn the ground next to a crystal. \n\nThe Brittle Bone reads:\n\n\"<Something is written here.>\n\nRage, Shank Sever\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "刀锋山\n\n在地面上，一块水晶旁边。\n\n脆骨上写着：\n\n“<这里写着一些东西。>\n\n愤怒，切断刺穿”",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 33.6, 58.2, BLADES_EDGE_MOUNTAINS },	-- Brittle Bone
		}),
		o(294100, {	-- Misplaced Candle
			["model"] = 1307043,
			["questID"] = 52900,
			["sourceQuests"] = { 52899 },
			["description"] = createLocalizationString({
				readable = "Spires of Arak\n\nNext to a large candle. \n\nThe Misplaced Candle reads:\n\n\"<Something is written here.>\n\nRankest Goldfish\"",
				constant = "SPIRES_OF_ARAK_NEXT_TO_A_LARGE_CANDLE_THE",
				export = true,
				text = {
					en = "Spires of Arak\n\nNext to a large candle. \n\nThe Misplaced Candle reads:\n\n\"<Something is written here.>\n\nRankest Goldfish\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "阿拉克峰\n\n在大蜡烛旁边。\n\n错位的蜡烛上写着：\n\n“<这里写着什么。>\n\n奇臭金鱼”",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 67.9, 41.0, SPIRES_OF_ARAK },	-- Misplaced Candle
		}),
		o(294101, {	-- Odd Cup
			["model"] = 1822968,
			["modelScale"] = .5,
			["questID"] = 52901,
			["sourceQuests"] = { 52900 },
			["description"] = createLocalizationString({
				readable = "Draenor SMV\n\nBrown cup, next to the fire. \n\nThe Odd Cup reads:\n\n\"<Something is written here.>\n\nEase off fruit...\"",
				constant = "DRAENOR_SMV_BROWN_CUP_NEXT_TO_THE_FIRE_THE_ODD",
				export = true,
				text = {
					en = "Draenor SMV\n\nBrown cup, next to the fire. \n\nThe Odd Cup reads:\n\n\"<Something is written here.>\n\nEase off fruit...\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "德拉诺 影月谷\n\n火堆旁边的棕色杯子。 \n\n古怪的杯子上写着：\n\n“<这里写着一些东西。>\n\n少吃点水果……”",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 45.7, 26.2, DRAENOR_SHADOWMOON_VALLEY },	-- Odd Cup
		}),
		o(294102, {	-- Interesting Rock
			["model"] = 939054,
			["modelScale"] = .5,
			["questID"] = 52902,
			["sourceQuests"] = { 52901 },
			["description"] = createLocalizationString({
				readable = "Outland SMV\n\nOn top of the mountain.\n\nThe Interesting Rock reads:\n\n\"<Something is written here.>\n\nThe BIG Bull\"",
				constant = "OUTLAND_SMV_ON_TOP_OF_THE_MOUNTAIN_THE",
				export = true,
				text = {
					en = "Outland SMV\n\nOn top of the mountain.\n\nThe Interesting Rock reads:\n\n\"<Something is written here.>\n\nThe BIG Bull\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "外域 影月谷\n\n在山顶上。\n\n这块有趣的石头写着：\n\n“<上面写着一些东西。>\n\n大公牛”",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 51.6, 43.8, SHADOWMOON_VALLEY },	-- Interesting Rock
		}),
		o(294103, {	-- Blooming Lily
			["model"] = 343460,
			["questID"] = 52903,
			["sourceQuests"] = { 52902 },
			["description"] = createLocalizationString({
				readable = "Swamp of Sorrows\n\nUnder the tree, on top of the water.\n\nThe Blooming Lily reads:\n\n\"<Something is written here.>\n\nJaws open nooks!\"",
				constant = "SWAMP_OF_SORROWS_UNDER_THE_TREE_ON_TOP_OF_THE",
				export = true,
				text = {
					en = "Swamp of Sorrows\n\nUnder the tree, on top of the water.\n\nThe Blooming Lily reads:\n\n\"<Something is written here.>\n\nJaws open nooks!\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "悲伤沼泽\n\n在树下，水面之上。\n\n盛开的百合上写着：\n\n“<这里写着什么。>\n\n巨口张开角落！”",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 58.0, 31.6, SWAMP_OF_SORROWS },	-- Blooming Lily
		}),
		o(294104, {	-- Pretty Flower
			["model"] = 1124095,
			["modelScale"] = .5,
			["questID"] = 52904,
			["sourceQuests"] = { 52903 },
			["description"] = createLocalizationString({
				readable = "Eastern Plaguelands\n\nInside the crypt, on top of the sarcophagus lid\n\nThe Pretty Flower reads:\n\n\"<Something is written here.>\n\nDead Rune Thug\"",
				constant = "EASTERN_PLAGUELANDS_INSIDE_THE_CRYPT_ON_TOP_OF",
				export = true,
				text = {
					en = "Eastern Plaguelands\n\nInside the crypt, on top of the sarcophagus lid\n\nThe Pretty Flower reads:\n\n\"<Something is written here.>\n\nDead Rune Thug\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "东瘟疫之地\n\n在墓穴内，石棺盖的顶部\n\n美丽的花朵上面写着：\n\n“<这里写着一些东西。>\n\n死亡的符文暴徒”",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 24.0, 78.0, EASTERN_PLAGUELANDS },	-- Pretty Flower
		}),
		o(294105, {	-- Old Book
			["model"] = 244161,
			["modelScale"] = .5,
			["questID"] = 52905,
			["sourceQuests"] = { 52904 },
			["description"] = createLocalizationString({
				readable = "Deadwind Pass\n\nInside the old church, near the table.\n\nThe Old Book reads:\n\n\"<Something is written here.>\n\n...A Stage Deception\"",
				constant = "DEADWIND_PASS_INSIDE_THE_OLD_CHURCH_NEAR_THE",
				export = true,
				text = {
					en = "Deadwind Pass\n\nInside the old church, near the table.\n\nThe Old Book reads:\n\n\"<Something is written here.>\n\n...A Stage Deception\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "逆风小径\n\n在旧教堂内，桌子附近。\n\n古旧的书上写着：\n\n“<这里写着一些东西。>\n\n……一场舞台骗局”",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 41.2, 78.9, DEADWIND_PASS },	-- Old Book
		}),
		o(294106, {	-- Dead Fish
			["model"] = 189087,
			["modelScale"] = .5,
			["questID"] = 52906,
			["sourceQuests"] = { 52905 },
			["description"] = createLocalizationString({
				readable = "Blackrock Mountain\n\nRoom next to LBRS entrance, next to the fire.\n\nThe Dead Fish says:\n\n\"<Something is written here.>\n\nNecropolis Expos!\"",
				constant = "BLACKROCK_MOUNTAIN_ROOM_NEXT_TO_LBRS_ENTRANCE",
				export = true,
				text = {
					en = "Blackrock Mountain\n\nRoom next to LBRS entrance, next to the fire.\n\nThe Dead Fish says:\n\n\"<Something is written here.>\n\nNecropolis Expos!\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "黑石山\n\n在黑石塔下层入口旁边的房间，火堆旁。\n\n死鱼上写着：\n\n“<这里写着一些东西。>\n\n死灵城展览！”",
					-- TODO: tw = "",
				},
			}),
			["coords"] = {
				{ 21.0, 38.2, BURNING_STEPPES },	-- Entrance
				{ 77.9, 44.3, BLACKROCK_MOUNTAIN },	-- Dead Fish
			},
		}),
		o(294107, {	-- Scratched Board
			["model"] = 625180,
			["modelScale"] = 3,
			["questID"] = 52907,
			["sourceQuests"] = { 52906 },
			["description"] = createLocalizationString({
				readable = "Duskwood\n\nUnderneath the large plank.\n\nThe Scratched Board reads:\n\n\"<Something is written here.>\n\nThe net saves.\"",
				constant = "DUSKWOOD_UNDERNEATH_THE_LARGE_PLANK_THE",
				export = true,
				text = {
					en = "Duskwood\n\nUnderneath the large plank.\n\nThe Scratched Board reads:\n\n\"<Something is written here.>\n\nThe net saves.\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "暮色森林\n\n在大木板下方。\n\n划痕木板上面写着：\n\n“<这里写着一些东西。>\n\n渔网会拯救你。”",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 52.0, 62.4, DUSKWOOD },	-- Scratched Board
		}),
		o(294108, {	-- Lost Ring
			["model"] = 242730,
			["questID"] = 52908,
			["sourceQuests"] = { 52907 },
			["description"] = createLocalizationString({
				readable = "Hillsbrad Foothills\n\nJust inside the clocktower, left pile of bones.\n\nThe Lost Ring reads:\n\n\"<Something is written here.>\n\nTerrible grunt.\"",
				constant = "HILLSBRAD_FOOTHILLS_JUST_INSIDE_THE_CLOCKTOWER",
				export = true,
				text = {
					en = "Hillsbrad Foothills\n\nJust inside the clocktower, left pile of bones.\n\nThe Lost Ring reads:\n\n\"<Something is written here.>\n\nTerrible grunt.\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "希尔斯布莱德丘陵\n\n就在钟楼内，左侧的骨堆。\n\n失落的戒指上写着：\n\n“<这里写着一些字。>\n\n糟糕的步兵。”",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 44.6, 26.4, 25 },	-- Lost Ring
		}),
		o(294109, {	-- Spoiled Apple
			["model"] = 960844,
			["modelScale"] = .5,
			["questID"] = 52909,
			["sourceQuests"] = { 52908 },
			["description"] = createLocalizationString({
				readable = "Badlands\n\nInside the larger building, on the table, next to the roasted boar.\n\nThe Spoiled Apple reads:\n\n\"<Something is written here.>\n\nLeave Nets, Often\"",
				constant = "BADLANDS_INSIDE_THE_LARGER_BUILDING_ON_THE",
				export = true,
				text = {
					en = "Badlands\n\nInside the larger building, on the table, next to the roasted boar.\n\nThe Spoiled Apple reads:\n\n\"<Something is written here.>\n\nLeave Nets, Often\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "荒芜之地\n\n在较大的那栋建筑内，桌子上，烤野猪旁边。\n\n腐烂的苹果上写着：\n\n“<这里写着一些东西。>\n\n常常留下渔网”",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 90.1, 37.9, BADLANDS },	-- Spoiled Apple
		}),
		o(294110, {	-- Broken Tooth
			["model"] = 442505,
			["questID"] = 52910,
			["sourceQuests"] = { 52909 },
			["description"] = createLocalizationString({
				readable = "Blasted Lands\n\nBase of the statue, near a candle. The tooth is present in both the past and present.\n\nThe Broken tooth reads:\n\n\"<Something is written here.>\n\nBrash remains.\"",
				constant = "BLASTED_LANDS_BASE_OF_THE_STATUE_NEAR_A_CANDLE",
				export = true,
				text = {
					en = "Blasted Lands\n\nBase of the statue, near a candle. The tooth is present in both the past and present.\n\nThe Broken tooth reads:\n\n\"<Something is written here.>\n\nBrash remains.\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "诅咒之地\n\n雕像底部，蜡烛旁边。这颗牙齿在过去和现在都存在。\n\n破碎的牙齿上写着：\n\n“<这里写着一些东西。>\n\n鲁莽的残骸。”",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 36.8, 27.6, BLASTED_LANDS },	-- Broken Tooth
		}),
		o(294111, {	-- Worn Helm
			["model"] = 197882,
			["modelScale"] = .5,
			["questID"] = 52911,
			["sourceQuests"] = { 52910 },
			["description"] = createLocalizationString({
				readable = "Burning Steppes\n\nEquipped on the larger brown skeletons head.\n\nThe Worn Helm reads:\n\n\"<Something is written here.>\n\nSensed the Figs...\"",
				constant = "BURNING_STEPPES_EQUIPPED_ON_THE_LARGER_BROWN",
				export = true,
				text = {
					en = "Burning Steppes\n\nEquipped on the larger brown skeletons head.\n\nThe Worn Helm reads:\n\n\"<Something is written here.>\n\nSensed the Figs...\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "燃烧平原\n\n装备在较大的棕色骷髅头上。\n\n破旧的头盔上写着：\n\n\"<这里写着一些东西。>\n\n感应到了无花果……\"",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 27.1, 47.0, BURNING_STEPPES },	-- Worn Helm
		}),
		o(294112, {	-- Leafy Leaf
			["model"] = 523642,
			["modelScale"] = 2,
			["questID"] = 52912,
			["sourceQuests"] = { 52911 },
			["description"] = createLocalizationString({
				readable = "Northrend Dalaran\n\nIn front of the left planter.\n\nThe Leafy Leaf reads:\n\n\"<Something is written here.>\n\nPhantasmal Hosts?\"",
				constant = "NORTHREND_DALARAN_IN_FRONT_OF_THE_LEFT_PLANTER",
				export = true,
				text = {
					en = "Northrend Dalaran\n\nIn front of the left planter.\n\nThe Leafy Leaf reads:\n\n\"<Something is written here.>\n\nPhantasmal Hosts?\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "诺森德达拉然\n\n在左侧花盆前。\n\n茂盛的叶子上写着：\n\n“<这里写着一些东西。>\n\n幻影宿主？”",
					-- TODO: tw = "",
				},
			}),	-- Punctured Pelt purchase while on this?
			["coord"] = { 42.75, 20.18, NORTHREND_DALARAN },	-- Leafy Leaf
		}),
		o(294113, {	-- Musty Cloth
			["model"] = 1360796,
			["questID"] = 52913,
			["sourceQuests"] = { 52912 },
			["description"] = createLocalizationString({
				readable = "Terrokar Forrest\n\nInside the crate, inside the tent, near the Shadow Labs entrance.\n\nThe Musty Cloth reads:\n\n\"<Something is written here.>\n\nScarce odds, still.\"",
				constant = "TERROKAR_FORREST_INSIDE_THE_CRATE_INSIDE_THE",
				export = true,
				text = {
					en = "Terrokar Forrest\n\nInside the crate, inside the tent, near the Shadow Labs entrance.\n\nThe Musty Cloth reads:\n\n\"<Something is written here.>\n\nScarce odds, still.\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "泰罗卡森林\n\n在帐篷里的箱子内，靠近暗影迷宫入口。\n\n发霉的布上写着：\n\n“<这里写着什么。>\n\n胜算仍然渺茫。”",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 40.2, 72.5, TEROKKAR_FOREST },	-- Musty Cloth
		}),
		o(294114, {	-- Broken Tablet
			["model"] = 202596,
			["modelScale"] = 2,
			["questID"] = 52914,
			["sourceQuests"] = { 52913 },
			["description"] = createLocalizationString({
				readable = "Twilight Highlands\n\nOn the ground next to the mace.\n\nThe Broken Tablet reads:\n\n\"<Something is written here.>\n\nStarfish droplets!\"",
				constant = "TWILIGHT_HIGHLANDS_ON_THE_GROUND_NEXT_TO_THE",
				export = true,
				text = {
					en = "Twilight Highlands\n\nOn the ground next to the mace.\n\nThe Broken Tablet reads:\n\n\"<Something is written here.>\n\nStarfish droplets!\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "暮光高地\n\n在钉锤旁边的地面上。\n\n破损的石碑上写着：\n\n“<这里写着一些东西。>\n\n海星水滴！”",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 17.1, 57.9, TWILIGHT_HIGHLANDS },	-- Broken Tablet
		}),
		o(294115, {	-- Ashed Torch
			["model"] = 341882,
			["modelScale"] = 2,
			["questID"] = 52915,
			["sourceQuests"] = { 52914 },
			["description"] = createLocalizationString({
				readable = "Feralas\n\nMiddle of the remains and table, sticking out of the ground.\n\nThe Ashed Torch reads:\n\n\"<Something is written here.>\n\n...a daft tormenter's fog.\"",
				constant = "FERALAS_MIDDLE_OF_THE_REMAINS_AND_TABLE",
				export = true,
				text = {
					en = "Feralas\n\nMiddle of the remains and table, sticking out of the ground.\n\nThe Ashed Torch reads:\n\n\"<Something is written here.>\n\n...a daft tormenter's fog.\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "菲拉斯\n\n在残骸和桌子中间，从地面中伸出。\n\n灰烬火把上面写着：\n\n“<这里写着一些东西。>\n\n……一个愚蠢折磨者的迷雾。”",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 60.8, 67.8, FERALAS },	-- Ashed Torch
		}),
		o(294312, {	-- Grimmy's List of Friends
			["model"] = 305392,
			["modelScale"] = .5,
			["questID"] = 52916,
			["sourceQuests"] = { 52915 },
			["description"] = createLocalizationString({
				readable = "Head to the past version of Arathi Highlands, and click on the note on the table inside Grimmy's house.\n\nGrimmy's List of Friends reads:\n\n\"List of My Friends?\nFirst is SN, you always smelled so good\nSecond is TM, you smelled like burning\nwood\nThird is FD, though you smelled like fel\nLast is OM, I hated that fishy smell\"",
				constant = "HEAD_TO_THE_PAST_VERSION_OF_ARATHI_HIGHLANDS",
				export = true,
				text = {
					en = "Head to the past version of Arathi Highlands, and click on the note on the table inside Grimmy's house.\n\nGrimmy's List of Friends reads:\n\n\"List of My Friends?\nFirst is SN, you always smelled so good\nSecond is TM, you smelled like burning\nwood\nThird is FD, though you smelled like fel\nLast is OM, I hated that fishy smell\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "前往阿拉希高地的过去版本，点击格里米屋内桌子上那张纸条。\n\n格里米的朋友名单上写着：\n\n“我的朋友名单？\n第一个是 SN，你身上总是那么好闻\n第二个是 TM，你闻起来像烧焦的\n木头\n第三个是 FD，虽然你闻起来像邪能\n最后是 OM，我讨厌那股鱼腥味”",
					-- TODO: tw = "",
				},
			}),
			["coords"] = {
				{ 38.2, 90.1, ARATHI_HIGHLANDS },	-- Zidormi
				{ 85.4, 73.6, ARATHI_HIGHLANDS },	-- Grimmy's List of Friends
			},
		}),
		hqt(52917, {	-- Grimmy Dialogue
			["name"] = "Grimmy Dialogue",
			["description"] = createLocalizationString({
				readable = "Equip the Windwool Hood, Deathsilk Shoulders, Netherweave Tunic, and Frostwoven Leggings, and talk to Grimmy. Select his dialogue \"It's me, your friend. Got any secrets to tell me about?\"",
				constant = "EQUIP_THE_WINDWOOL_HOOD_DEATHSILK_SHOULDERS",
				export = true,
				text = {
					en = "Equip the Windwool Hood, Deathsilk Shoulders, Netherweave Tunic, and Frostwoven Leggings, and talk to Grimmy. Select his dialogue \"It's me, your friend. Got any secrets to tell me about?\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "装备风绒兜帽、亡丝护肩、灵纹外套和霜纹护腿，然后与格里米交谈。选择他的对话“是我，你的朋友。有什么秘密要告诉我吗？”",
					-- TODO: tw = "",
				},
			}),
			["sourceQuests"] = { 52916 },
			["provider"] = { "n", 138578 },	-- Grimmy
			-- ["coord"] = { 85.3, 73.6, ARATHI_HIGHLANDS },	-- Grimmy Dialogue
		}),
		o(294314, {	-- Grimmy's List of Enemies
			["model"] = 305391,
			["questID"] = 52918,
			["sourceQuests"] = { 52917 },
			["description"] = createLocalizationString({
				readable = "After selecting the Grimmy dialogue, a note appears on his bedstand. Click it. Grimmy's List of Enemies reads:\n\n\"You flaunted your virility, and red was\nnever to my liking\nThough I wanted to slap you, I always\nfound you striking.\n\nYou Always though you knew what was\nbest, but not everyone likes greens,\nThough I waved your way, I pictured\nyour shredded hide in my dreams.\n??\nYour bread was bad, you diseased lout,\nit made me sick.\nI woudl cheerily beat you with a stick.\n??\nLast you, I'm not eve going to think of\na rhyme for you, Mugs.\nI will dance on your grave, you were\nuniquely terrible.\"\n\nGo to each of the following NPCs with Proximo's Rudius, Rough Wooden Staff, Punctured Pelt, and Formula: Enchant Ring - Striking, and emote to them.",
				constant = "AFTER_SELECTING_THE_GRIMMY_DIALOGUE_A_NOTE",
				export = true,
				text = {
					en = "After selecting the Grimmy dialogue, a note appears on his bedstand. Click it. Grimmy's List of Enemies reads:\n\n\"You flaunted your virility, and red was\nnever to my liking\nThough I wanted to slap you, I always\nfound you striking.\n\nYou Always though you knew what was\nbest, but not everyone likes greens,\nThough I waved your way, I pictured\nyour shredded hide in my dreams.\n??\nYour bread was bad, you diseased lout,\nit made me sick.\nI woudl cheerily beat you with a stick.\n??\nLast you, I'm not eve going to think of\na rhyme for you, Mugs.\nI will dance on your grave, you were\nuniquely terrible.\"\n\nGo to each of the following NPCs with Proximo's Rudius, Rough Wooden Staff, Punctured Pelt, and Formula: Enchant Ring - Striking, and emote to them.",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "选择格里米的对话后，他的床头柜上会出现一张便条。点击它。格里米的敌人名单上写着：\n\n“你炫耀你的雄风，而红色\n从来不合我的口味\n虽然我想扇你一巴掌，我却总\n觉得你很醒目。\n\n你总以为自己知道什么最\n好，可不是人人都喜欢绿色，\n虽然我朝你挥了挥手，我在梦里\n却想着你被撕碎的皮囊。\n??\n你的面包很难吃，你这病恹恹的蠢货，\n它让我恶心。\n我会乐意用棍子揍你一顿。\n??\n最后是你，我甚至懒得为你\n想一句押韵的话，Mugs。\n我会在你的坟头跳舞，你真是\n独一无二地糟糕。”\n\n带着普罗克西莫的短剑、粗糙的木杖、穿孔的兽皮和公式：附魔戒指 - 打击，前往以下每个 NPC 处，并对他们做表情动作。",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 85.3, 73.7, ARATHI_HIGHLANDS },	-- Grimmy's List of Enemies
		}),
		n(47121, {	-- Aquinastrasz <Vermillion Redoubt Flight Master>
			["questID"] = 52822,
			["sourceQuests"] = { 52918 },
			["description"] = createLocalizationString({
				readable = "Twilight Highlands\n\n/slap",
				constant = "TWILIGHT_HIGHLANDS_SLAP",
				export = true,
				text = {
					en = "Twilight Highlands\n\n/slap",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "暮光高地\n\n/slap",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 28.5, 24.9, TWILIGHT_HIGHLANDS },	-- Aquinastrasz <Vermillion Redoubt Flight Master>
		}),
		n(36034, {	-- Karnum Marshweaver <The Cenarion Circle>
			["questID"] = 52823,
			["sourceQuests"] = { 52918 },
			["description"] = createLocalizationString({
				readable = "Desolace\n\n/wave",
				constant = "DESOLACE_WAVE",
				export = true,
				text = {
					en = "Desolace\n\n/wave",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "凄凉之地\n\n/wave",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 57.5, 47.7, DESOLACE },	-- Karnum Marshweaver <The Cenarion Circle>
		}),
		n(28792, {	-- Noggra <General Goods>
			["questID"] = 52824,
			["sourceQuests"] = { 52918 },
			["description"] = createLocalizationString({
				readable = "Zul'drak\n\n/cheer",
				constant = "ZUL_DRAK_CHEER",
				export = true,
				text = {
					en = "Zul'drak\n\n/cheer",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "祖达克\n\n/cheer",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 40.6, 68.7, ZULDRAK },	-- Noggra <General Goods>
		}),
		n(62877, {	-- Stained Mug <Innkeeper>
			["questID"] = 52826,
			["sourceQuests"] = { 52918 },
			["description"] = createLocalizationString({
				readable = "Kun-Lai Summit\n\n/dance",
				constant = "KUN_LAI_SUMMIT_DANCE",
				export = true,
				text = {
					en = "Kun-Lai Summit\n\n/dance",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "昆莱山\n\n/dance",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 44.4, 90.3, KUN_LAI_SUMMIT },	-- Stained Mug <Innkeeper>
		}),
		n(138578, {	-- Grimmy Dialogue
			["questID"] = 52919,
			["sourceQuests"] = { 52826, 52824, 52823, 52822, },
			["description"] = createLocalizationString({
				readable = "Return to Grimmy and select his new dialogue\n\n\"I've sent some messages to your enemies, now about those secrets...\"",
				constant = "RETURN_TO_GRIMMY_AND_SELECT_HIS_NEW_DIALOGUE_I",
				export = true,
				text = {
					en = "Return to Grimmy and select his new dialogue\n\n\"I've sent some messages to your enemies, now about those secrets...\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "回到格里米处并选择他的新对话\n\n“我已经给你的敌人捎去了些消息，现在来说说那些秘密……”",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 85.3, 73.6, ARATHI_HIGHLANDS },	-- Grimmy Dialogue
		}),
		o(294315, {	-- Grimmy's Favorite Recipe
			["model"] = 936411,
			["modelScale"] = .5,
			["questID"] = 52920,
			["sourceQuests"] = { 52919 },
			["description"] = createLocalizationString({
				readable = "After selecting Grimmy's dialogue, a new note appears by the fireplace. Click it. Grimmy's Favorite Recipe reads:\n\n\"A pinch of turmeric and a pound of salt,\nif it comes out poorly it's your own\nfault.\n\nPay attention to the broth, and stir,stir,\nstir!\nThen add a big handful of boar fur.\n\nLast you need a little sour,\nget the kick with a little gunpowder!\"",
				constant = "AFTER_SELECTING_GRIMMY_S_DIALOGUE_A_NEW_NOTE",
				export = true,
				text = {
					en = "After selecting Grimmy's dialogue, a new note appears by the fireplace. Click it. Grimmy's Favorite Recipe reads:\n\n\"A pinch of turmeric and a pound of salt,\nif it comes out poorly it's your own\nfault.\n\nPay attention to the broth, and stir,stir,\nstir!\nThen add a big handful of boar fur.\n\nLast you need a little sour,\nget the kick with a little gunpowder!\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "选择格里米的对话后，壁炉旁会出现一张新的便条。点击它。格里米最爱的食谱上写着：\n\n“一撮姜黄加一磅盐，\n要是做砸了那可得怪你\n自己。\n\n留意汤底，搅啊搅，\n搅！\n然后加一大把野猪毛。\n\n最后你需要一点酸味，\n再加一点火药提提劲！”",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 85.3, 74.0, ARATHI_HIGHLANDS },	-- Grimmy's Favorite Recipe
		}),
		o(294335, {	-- Rotten Potato
			["model"] = 2020463,
			["modelScale"] = .5,
			["questID"] = 52921,
			["sourceQuests"] = { 52920 },
			["description"] = createLocalizationString({
				readable = "Go outside and find the Rotten Potato. You will need to get exactly 144 stacks of Rotten Potato by clicking the potato. After getting 144 stacks of the buff, go back and talk to Grimmy and select his new dialogue option\"How do I smell?\"\n\nGrimmy's new dialogue says:\n\n\"Oh, my, just like my mother used to after she made her famous pie.\n\nVery well, I will show you...my life's work!\n\nIt's in the chest out back, and it's all yours!\n\nI hope it was worth it!\"",
				constant = "GO_OUTSIDE_AND_FIND_THE_ROTTEN_POTATO_YOU_WILL",
				export = true,
				text = {
					en = "Go outside and find the Rotten Potato. You will need to get exactly 144 stacks of Rotten Potato by clicking the potato. After getting 144 stacks of the buff, go back and talk to Grimmy and select his new dialogue option\"How do I smell?\"\n\nGrimmy's new dialogue says:\n\n\"Oh, my, just like my mother used to after she made her famous pie.\n\nVery well, I will show you...my life's work!\n\nIt's in the chest out back, and it's all yours!\n\nI hope it was worth it!\"",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "走到外面找到腐烂的土豆。你需要通过点击土豆来获得正好 144 层腐烂的土豆。获得 144 层增益后，回去与格里米交谈，并选择他的新对话选项“我闻起来怎么样？”\n\n格里米的新对话内容是：\n\n“哦天哪，就像我母亲做完她那道著名的馅饼之后一样。\n\n好吧，我会向你展示……我一生的作品！\n\n就在后面的箱子里，全都归你了！\n\n希望这一切都值得！”",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 88.4, 69.2, ARATHI_HIGHLANDS },	-- Rotten Potato
		}),
		o(294703, {	-- Grimmy's Rusty Lockbox
			["questID"] = 52922,
			["sourceQuests"] = { 52921 },
			["description"] = createLocalizationString({
				readable = "After asking Grimmy how you smell, go outside behind and above his house, and on the hill will be Grimmy's Rusty Lockbox waiting for you to open it.",
				constant = "AFTER_ASKING_GRIMMY_HOW_YOU_SMELL_GO_OUTSIDE",
				export = true,
				text = {
					en = "After asking Grimmy how you smell, go outside behind and above his house, and on the hill will be Grimmy's Rusty Lockbox waiting for you to open it.",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "问过格里米你闻起来怎么样之后，走到他房子后面上方的屋外，山丘上会有格里米的生锈锁箱等着你打开。",
					-- TODO: tw = "",
				},
			}),
			["coord"] = { 85.1, 73.3, ARATHI_HIGHLANDS },	-- Grimmy's Rusty Lockbox
			["groups"] = {
				i(162690),	-- Waist of Time
			},
		}),
	},
})));
