name: Bug
description: Something broken?
labels: ["Addon Bug"]
body:
- type: dropdown
  id: flavour
  attributes:
    label: What version(s) of WoW are you using?
    multiple: true
    options:
      - Retail
      - Cata Classic
      - WotLK Classic
      - Classic Era
      - Hardcore
      - Season of Discovery
      - Anniversary Realms
      - Hardcore Anniversary Realms
  validations:
    required: true
  validations:
    required: true
- type: dropdown
  attributes:
    label: What version of ATT?
    options:
      - git
      - Latest alpha
      - Latest release
  validations:
    required: true
- type: input
  attributes:
    label: the build number of ATT.
  validations:
    required: true
- type: textarea
  attributes:
    label: What isn't working? What was supposed to happen?
  validations:
    required: true
- type: textarea
  attributes:
    label: Are you experiencing any lua errors
    description: These appear when using the BugSack+BugGrabber addons, or enabling script errors with `/console scriptErrors 1`
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
  validations:
    required: false