
local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[561159] = {
		readable = "Stolen Enchanting Supplies",
		model = 189092,
		text = {
			en = "Stolen Enchanting Supplies",
			es = "Suministros de encantamiento robados",
			mx = "Suministros de encantamiento robados",
			de = "Gestohlene Verzauberkunstmaterialien",
			fr = "Fournitures d’enchantement volées",
			ru = "Украденные предметы для наложения чар",
			ko = "도난당한 마법부여용품",
		},
	},
	[562105] = {
		readable = "Waterlogged Axe",
		text = {
			en = "Waterlogged Axe",
			es = "Hacha empapada",
			mx = "Hacha calada",
			de = "Durchnässte Axt",
			fr = "Hache détrempée",
			ru = "Отсыревший топор",
			ko = "흠뻑 젖은 도끼",
			tw = "浸水的斧頭",
		},
	},
	[562106] = {
		readable = "Waterlogged Toolbox",
		model = 197621,
		text = {
			en = "Waterlogged Toolbox",
			es = "Caja de herramientas empapada",
			mx = "Caja de herramientas calada",
			de = "Durchnässter Werkzeugkasten",
			fr = "Boîte à outils détrempée",
			pt = "Caixa de Ferramentas Encharcada",
			ru = "Отсыревший ящик с инструментами",
			ko = "물에 젖은 도구상자",
			tw = "浸水的工具箱",
		},
	},
	[562114] = {
		readable = "Mining Tools",
		model = 198069,
		text = {
			en = "Mining Tools",
			es = "Herramientas de minería",
			mx = "Herramientas de minería",
			de = "Bergbauwerkzeuge",
			fr = "Outils de minage",
			pt = "Ferramentas de Mineração",
			ru = "Орудия горняка",
			ko = "채광용 연장",
			tw = "採礦工具",
		},
	},
	[562131] = {
		readable = "Applejack Still",
		model = 189611,
		text = {
			en = "Applejack Still",
			es = "Alambique de sidra de manzana",
			de = "Apfelschnapsbrenner",
			fr = "Alambic à calva",
			pt = "Alambique de Aguardente de Maçã",
			ru = "Аппарат для перегонки яблочного бренди",
			ko = "사과주 증류기",
			tw = "蘋果白蘭地蒸餾器",
		},
	},
	[563442] = {
		readable = "Kobold Tracks",
		model = 202786,
		text = {
			en = "Kobold Tracks",
			es = "Rastros kóbold",
			de = "Koboldspuren",
			fr = "Empreintes kobold",
			pt = "Rastros de Kobold",
			ru = "Кобольдские следы",
			ko = "코볼트 발자취",
			tw = "狗頭人足跡",
		},
	},
	[576179] = {
		readable = "Supply Cache",
		text = {
			en = "Supply Cache",
			es = "Cajón de provisiones",
			de = "Vorratskiste",
			fr = "Cache de fournitures",
			pt = "Baú de Suprimentos",
			ru = "Тайник с припасами",
			ko = "보급품 상자",
			cn = "补给箱",
		},
	},
	[610954] = {
		readable = "Bounty Available: Vulgara the Insatiable!",
		text = {
			en = "Bounty Available: Vulgara the Insatiable!",
			es = "Recompensa disponible: ¡Vulgara el Insaciable!",
			mx = "Recompensa disponible: ¡Vulgara, la Insaciable!",
			de = "Kopfgeld verfügbar: Vulgara der Unersättliche!",
			fr = "Prime disponible : Vulgara l’Insatiable",
			pt = "Recompensa: Vulgara, Insaciável!",
			ru = "Обещана награда: Вулгара Ненасытный",
			ko = "진행 중인 현상 수배: 탐욕의 불가라",
			cn = "悬赏：贪得无厌的乌尔加拉！",
		},
	},
	[617674] = {
		readable = "Arvensus Shadowsong",
		text = {
			en = "Arvensus Shadowsong",
			es = "Arvensus Cantosombrío",
			de = "Arvensus Shadowsong",
			fr = "Arvensus Chantelombre",
			pt = "Arvensus Cantonegro",
			ru = "Арвенсий Песня Теней",
			ko = "아르벤수스 섀도송",
			cn = "阿文苏斯·影歌",
		},
	},
	[617675] = {
		readable = "Raani Windgazer",
		text = {
			en = "Raani Windgazer",
			es = "Raani Observaviento",
			de = "Raani Windgazer",
			fr = "Mire-vent raani",
			pt = "Raani Fitaventos",
			ru = "Раани Взор Ветров",
			ko = "라니 윈드게이저",
			cn = "凝风者拉尼",
		},
	},
	[617704] = {
		readable = "Bloody Note",
		text = {
			en = "Bloody Note",
		},
	},
})
do ObjectDB[objectID] = objectData; end
