---------------------------------------------
--    C R A F T A B L E S   M O D U L E    --
---------------------------------------------
root(ROOTS.Craftables, {
	prof(ALCHEMY),
	prof(BLACKSMITHING, {
		prof(ARMORSMITH, {
			["description"] = createLocalizationString({
				readable = "These items can only be crafted by Blacksmiths who have completed the Art of the Armorsmith quest chain.",
				constant = "THESE_ITEMS_CAN_ONLY_BE_CRAFTED_BY_BLACKSMITHS",
				export = true,
				text = {
					en = "These items can only be crafted by Blacksmiths who have completed the Art of the Armorsmith quest chain.",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "这些物品只能由完成了“护甲锻造的艺术”任务线的锻造师制作。",
					-- TODO: tw = "",
				},
			}),
		}),
		prof(WEAPONSMITH, {
			["description"] = createLocalizationString({
				readable = "These items can only be crafted by Blacksmiths who have completed the Way of the Weaponsmith quest chain.",
				constant = "THESE_ITEMS_CAN_ONLY_BE_CRAFTED_BY_BLACKSMITHS_2",
				export = true,
				text = {
					en = "These items can only be crafted by Blacksmiths who have completed the Way of the Weaponsmith quest chain.",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "这些物品只能由完成了“武器锻造之道”任务线的锻造师制作。",
					-- TODO: tw = "",
				},
			}),
			["groups"] = {
				prof(MASTER_AXESMITH, {
					["description"] = createLocalizationString({
						readable = "These items can only be crafted by Master Axesmith specialized Weaponsmiths.",
						constant = "THESE_ITEMS_CAN_ONLY_BE_CRAFTED_BY_MASTER",
						export = true,
						text = {
							en = "These items can only be crafted by Master Axesmith specialized Weaponsmiths.",
							-- TODO: de = "",
							-- TODO: es = "",
							-- TODO: mx = "",
							-- TODO: fr = "",
							-- TODO: it = "",
							-- TODO: ko = "",
							-- TODO: pt = "",
							-- TODO: ru = "",
							cn = "这些物品只能由选择了斧类武器大师专精的武器锻造师制作。",
							-- TODO: tw = "",
						},
					}),
				}),
				prof(MASTER_HAMMERSMITH, {
					["description"] = createLocalizationString({
						readable = "These items can only be crafted by Master Hammersmith specialized Weaponsmiths.",
						constant = "THESE_ITEMS_CAN_ONLY_BE_CRAFTED_BY_MASTER_2",
						export = true,
						text = {
							en = "These items can only be crafted by Master Hammersmith specialized Weaponsmiths.",
							-- TODO: de = "",
							-- TODO: es = "",
							-- TODO: mx = "",
							-- TODO: fr = "",
							-- TODO: it = "",
							-- TODO: ko = "",
							-- TODO: pt = "",
							-- TODO: ru = "",
							cn = "这些物品只能由选择了锤类武器大师专精的武器锻造师制作。",
							-- TODO: tw = "",
						},
					}),
				}),
				prof(MASTER_SWORDSMITH, {
					["description"] = createLocalizationString({
						readable = "These items can only be crafted by Master Swordsmith specialized Weaponsmiths.",
						constant = "THESE_ITEMS_CAN_ONLY_BE_CRAFTED_BY_MASTER_3",
						export = true,
						text = {
							en = "These items can only be crafted by Master Swordsmith specialized Weaponsmiths.",
							-- TODO: de = "",
							-- TODO: es = "",
							-- TODO: mx = "",
							-- TODO: fr = "",
							-- TODO: it = "",
							-- TODO: ko = "",
							-- TODO: pt = "",
							-- TODO: ru = "",
							cn = "这些物品只能由选择了剑类武器大师专精的武器锻造师制作。",
							-- TODO: tw = "",
						},
					}),
				}),
				n(WEAPONS, {
					["description"] = createLocalizationString({
						readable = "These can be crafted by any Weaponsmith.",
						constant = "THESE_CAN_BE_CRAFTED_BY_ANY_WEAPONSMITH",
						export = true,
						text = {
							en = "These can be crafted by any Weaponsmith.",
							-- TODO: de = "",
							-- TODO: es = "",
							-- TODO: mx = "",
							-- TODO: fr = "",
							-- TODO: it = "",
							-- TODO: ko = "",
							-- TODO: pt = "",
							-- TODO: ru = "",
							cn = "这些物品可由任意武器锻造师制作。",
							-- TODO: tw = "",
						},
					}),
				}),
			},
		}),
	}),
	prof(COOKING),
	prof(ENCHANTING),
	prof(ENGINEERING, {
		prof(GNOMISH_ENGINEERING, {
			["description"] = createLocalizationString({
				readable = "These items can only be crafted by Engineers who have completed the Gnomish Engineering quest chain.",
				constant = "THESE_ITEMS_CAN_ONLY_BE_CRAFTED_BY_ENGINEERS",
				export = true,
				text = {
					en = "These items can only be crafted by Engineers who have completed the Gnomish Engineering quest chain.",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "这些物品只能由完成了侏儒工程学任务线的工程师制作。",
					-- TODO: tw = "",
				},
			}),
		}),
		prof(GOBLIN_ENGINEERING, {
			["description"] = createLocalizationString({
				readable = "These items can only be crafted by Engineers who have completed the Goblin Engineering quest chain.",
				constant = "THESE_ITEMS_CAN_ONLY_BE_CRAFTED_BY_ENGINEERS_2",
				export = true,
				text = {
					en = "These items can only be crafted by Engineers who have completed the Goblin Engineering quest chain.",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "这些物品只能由完成了地精工程学任务线的工程师制作。",
					-- TODO: tw = "",
				},
			}),
		}),
	}),
	prof(FIRST_AID),
	prof(FISHING, {
		["description"] = createLocalizationString({
			readable = "If you struggle to catch an open water fish in a given zone, try a different spot or a different body of water. There might be local variations of which fish you can reliably catch from a given spot.",
			constant = "IF_YOU_STRUGGLE_TO_CATCH_AN_OPEN_WATER_FISH_IN",
			export = true,
			text = {
				en = "If you struggle to catch an open water fish in a given zone, try a different spot or a different body of water. There might be local variations of which fish you can reliably catch from a given spot.",
				-- TODO: de = "",
				-- TODO: es = "",
				-- TODO: mx = "",
				-- TODO: fr = "",
				-- TODO: it = "",
				-- TODO: ko = "",
				-- TODO: pt = "",
				-- TODO: ru = "",
				cn = "如果你在某个区域难以钓到开阔水域的鱼，可以换个钓点或换片水域。同一钓点能稳定钓到的鱼可能存在地域差异。",
				-- TODO: tw = "",
			},
		}),
	}),
	prof(HERBALISM, {
		["description"] = createLocalizationString({
			readable = "It is beneficial to gather all herbs in the area even if you only need specific herbs because the node spawns are often connected.",
			constant = "IT_IS_BENEFICIAL_TO_GATHER_ALL_HERBS_IN_THE",
			export = true,
			text = {
				en = "It is beneficial to gather all herbs in the area even if you only need specific herbs because the node spawns are often connected.",
				-- TODO: de = "",
				-- TODO: es = "",
				-- TODO: mx = "",
				-- TODO: fr = "",
				-- TODO: it = "",
				-- TODO: ko = "",
				-- TODO: pt = "",
				-- TODO: ru = "",
				cn = "即使你只需要特定草药，也建议采完该区域的所有草药，因为节点刷新往往是相互关联的。",
				-- TODO: tw = "",
			},
		}),
	}),
	prof(LEATHERWORKING, {
		prof(10656, {	-- Dragonscale Leatherworking
			["description"] = createLocalizationString({
				readable = "These items can only be crafted by Leatherworkers who have completed the associated quest.",
				constant = "THESE_ITEMS_CAN_ONLY_BE_CRAFTED_BY",
				export = true,
				text = {
					en = "These items can only be crafted by Leatherworkers who have completed the associated quest.",
					-- TODO: de = "",
					-- TODO: es = "",
					-- TODO: mx = "",
					-- TODO: fr = "",
					-- TODO: it = "",
					-- TODO: ko = "",
					-- TODO: pt = "",
					-- TODO: ru = "",
					cn = "这些物品只能由完成了相关任务的制皮师制作。",
					-- TODO: tw = "",
				},
			}),
		}),
		prof(10658, {	-- Elemental Leatherworking
			["description"] = "~L.THESE_ITEMS_CAN_ONLY_BE_CRAFTED_BY",
		}),
		prof(10660, {	-- Tribal Leatherworking
			["description"] = "~L.THESE_ITEMS_CAN_ONLY_BE_CRAFTED_BY",
		}),
	}),
	prof(MINING, {
		["description"] = createLocalizationString({
			readable = "Mining veins are usually found on uneven terrain and mountainsides as well as inside caves. It is beneficial to mine all veins in the area even if you only need specific ore because the node spawns are often connected.",
			constant = "MINING_VEINS_ARE_USUALLY_FOUND_ON_UNEVEN",
			export = true,
			text = {
				en = "Mining veins are usually found on uneven terrain and mountainsides as well as inside caves. It is beneficial to mine all veins in the area even if you only need specific ore because the node spawns are often connected.",
				-- TODO: de = "",
				-- TODO: es = "",
				-- TODO: mx = "",
				-- TODO: fr = "",
				-- TODO: it = "",
				-- TODO: ko = "",
				-- TODO: pt = "",
				-- TODO: ru = "",
				cn = "矿脉通常出现在起伏的地形、山坡以及洞穴中。即使你只需要特定矿石，也建议采完该区域的所有矿脉，因为节点刷新往往是相互关联的。",
				-- TODO: tw = "",
			},
		}),
	}),
	prof(POISONS, {
		["classes"] = { ROGUE },
	}),
	prof(SKINNING, {
		["description"] = createLocalizationString({
			readable = "The following items can be gathered by skinning creatures out in the world.",
			constant = "THE_FOLLOWING_ITEMS_CAN_BE_GATHERED_BY_SKINNING",
			export = true,
			text = {
				en = "The following items can be gathered by skinning creatures out in the world.",
				-- TODO: de = "",
				-- TODO: es = "",
				-- TODO: mx = "",
				-- TODO: fr = "",
				-- TODO: it = "",
				-- TODO: ko = "",
				-- TODO: pt = "",
				-- TODO: ru = "",
				cn = "以下物品可以通过在野外剥皮生物来采集。",
				-- TODO: tw = "",
			},
		}),
	}),
	prof(TAILORING),
});
