/* Independent system JXA tests. Every fixture and result stays outside the checkout. */
ObjC.import('Foundation');
function run(args) {
    'use strict';
    var base=String(args[0]), evidence=String(args[1]), filter=String(args[2]||'');
    var coreText=ObjC.unwrap($.NSString.stringWithContentsOfFileEncodingError(base+'/att-core.js',$.NSUTF8StringEncoding,Ref()));
    (0,eval)(coreText);
    ATT.base=base;
    var loadedHashes={'att-core.js':ATT.hashBytes(coreText)};
    ['att-artifact.js','att-snapshot.js','att-store.js'].forEach(function(name){var contents=ATT.readText(base+'/'+name,2*1024*1024);loadedHashes[name]=ATT.hashBytes(contents);(0,eval)(contents);});
    ['att-deploy.sh','test-script.sh','test-script.js'].forEach(function(name){loadedHashes[name]=ATT.hashFile(base+'/'+name);});
    var A=ATT, root=A.real(evidence), reports=[], tests=[], serial=0, started=Date.now(), failures=0, activeCase=null;
    var checkout=A.git(base,['rev-parse','--show-toplevel']).trim();
    if(A.overlap(checkout,root)) A.fail('Test evidence and fixtures must be outside the worktree');
    A.mkdir(root);
    if(filter!=='--worker'&&filter!=='--list'&&A.exists(root+'/script-test-results.json'))A.fail('Evidence directory already contains results; choose a new directory to preserve prior evidence');
    function assert(ok,message) { if(!ok) throw new Error(message||'Assertion failed'); }
    function equal(expected,actual,message) { assert(A.canonical(expected)===A.canonical(actual),message||'Expected '+A.canonical(expected)+'; actual '+A.canonical(actual)); }
    function reject(fn,pattern) { var caught=null;try { fn(); } catch(e) { caught=e; }assert(caught,'Expected refusal');assert(caught.name!=='ReferenceError'&&caught.name!=='TypeError'&&caught.name!=='SyntaxError','Implementation exception is not an expected refusal: '+caught);if(pattern)assert(pattern.test(String(caught)), 'Unexpected refusal: '+caught);if(activeCase)activeCase.expected_refusals.push(String(caught));return String(caught); }
    function copy(value) { return A.strictParse(A.canonical(value)); }
    function test(name,fn) { tests.push({name:name,fn:fn}); }
    function dir(label) { var p=root+'/fixtures/'+String(++serial)+'-'+label.replace(/[^A-Za-z0-9._-]/g,'_');A.mkdir(p);if(activeCase)activeCase.fixture_directories.push(p);return p; }
    function write(p,text) { A.writeBytes(p,text,!A.exists(p));return p; }
    function command(argv,cwd,options) { var r=A.exec(argv,cwd,options);assert(r.code===0,'Command failed: '+argv.join(' ')+'\n'+r.stderr);return r.stdout; }
    function git(p,argv) { return command(['/usr/bin/git','-c','core.hooksPath=/dev/null','-c','commit.gpgsign=false','-c','user.name=ATT Script Fixture','-c','user.email=att-fixture.invalid@example.invalid'].concat(argv),p,{env:{GIT_TERMINAL_PROMPT:'0',GIT_CONFIG_GLOBAL:'/dev/null',GIT_CONFIG_SYSTEM:'/dev/null'}}); }
    function id(commit,profile) { return {commit:commit||'1111111111111111111111111111111111111111',object_format:'sha1',flavor:'retail',profile:profile||'fixture',recipe:'fixture-v1'}; }
    function fileInfo(p) { return {sha256:A.hashFile(p),size:A.size(p)}; }
    function crc32(bytes) { var crc=0xffffffff;for(var i=0;i<bytes.length;i++){crc^=bytes[i];for(var b=0;b<8;b++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0; }
    function le(out,value,count) { for(var i=0;i<count;i++)out.push((value>>>i*8)&255); }
    function ascii(text) { return text.split('').map(function(c){return c.charCodeAt(0);}); }
    function storedZip(rows,options) {
        options=options||{};var local=[],central=[], offsets=[];
        rows.forEach(function(row){
            var name=ascii(row.name),data=typeof row.text==='string'?A.bytes(A.nsdata(row.text)):row.bytes||[], crc=crc32(data),offset=local.length;
            var flags=row.flags||0,method=row.method||0,size=row.size===undefined?data.length:row.size,compressed=row.compressedSize===undefined?data.length:row.compressedSize;
            offsets.push(offset);le(local,0x04034b50,4);le(local,row.version||20,2);le(local,row.localFlags===undefined?flags:row.localFlags,2);le(local,row.localMethod===undefined?method:row.localMethod,2);le(local,0,2);le(local,0,2);le(local,crc,4);le(local,compressed,4);le(local,size,4);le(local,name.length,2);le(local,0,2);local=local.concat(name,data);
            le(central,0x02014b50,4);le(central,row.madeBy===undefined?0x0314:row.madeBy,2);le(central,row.version||20,2);le(central,flags,2);le(central,method,2);le(central,0,2);le(central,0,2);le(central,crc,4);le(central,compressed,4);le(central,size,4);le(central,name.length,2);le(central,0,2);le(central,0,2);le(central,row.disk||0,2);le(central,0,2);le(central,row.attributes===undefined?0x81a40000:row.attributes,4);le(central,row.offset===undefined?offset:row.offset,4);central=central.concat(name);
        });
        var out=local.concat(central);le(out,0x06054b50,4);le(out,options.disk||0,2);le(out,options.centralDisk||0,2);le(out,options.count===undefined?rows.length:options.count,2);le(out,options.count===undefined?rows.length:options.count,2);le(out,central.length,4);le(out,local.length,4);le(out,0,2);
        return out.concat(options.trailing||[]);
    }
    function artifactFixture(options) {
        options=options||{};var p=dir('artifact'),identity=options.identity||id(),rows=options.rows||[{name:'Standard/a.lua',text:'fixture=true\n'}];
        var prefix='db-'+identity.object_format+'-'+identity.commit,zip=p+'/'+prefix+'.zip',manifest=p+'/'+prefix+'.sha256',metadata=p+'/'+prefix+'.metadata.json';
        write(zip,storedZip(rows,options.zipOptions));var files={}, lines=[];
        (options.manifestRows||rows).filter(function(row){return !/\/$/.test(row.name);}).sort(function(a,b){return a.name<b.name?-1:a.name>b.name?1:0;}).forEach(function(row){var data=typeof row.text==='string'?row.text:row.bytes||[],digest=A.hashBytes(data);files[row.name]={sha256:digest,size:Number(A.nsdata(data).length)};lines.push(digest+'  '+row.name);});
        write(manifest,lines.join('\n')+'\n');var contract={schema:2,repository:'ATTWoWAddon/AllTheThings',commit:identity.commit,git_object_format:identity.object_format,archive:{name:prefix+'.zip',sha256:A.hashFile(zip),size:A.size(zip)},manifest:{name:prefix+'.sha256',sha256:A.hashFile(manifest),size:A.size(manifest)},files:files,products:[{flavor:identity.flavor,profile:identity.profile,recipe:identity.recipe,root:'Standard',files:Object.keys(files).sort()}],producer:{fresh_staging:true,required_flavors:[identity.flavor],completed_flavors:[identity.flavor]}};
        if(options.change)options.change(contract);write(metadata,A.canonical(contract)+'\n');
        return {root:p,identity:identity,zip:zip,manifest:manifest,metadata:metadata,contract:contract,extract:function(extra){return A.verifyAndExtract(zip,manifest,metadata,p+'/extracted-'+A.uuid(),identity,extra||{});},refresh:function(){contract.archive.sha256=A.hashFile(zip);contract.archive.size=A.size(zip);contract.manifest.sha256=A.hashFile(manifest);contract.manifest.size=A.size(manifest);write(metadata,A.canonical(contract)+'\n');}};
    }
    function sourceFixture(options) {
        options=options||{};var p=dir('source'),source=p+'/source';A.mkdir(source);git(source,['init','-q']);
        var files={
            'AllTheThings.toc':'## Title: Script fixture\nsrc/base.lua\ndb\\[Game]\\ReferenceDB.lua\ndb\\[Game]\\Database.xml\nAllTheThings.lua\n',
            'AllTheThings.lua':'ATTFixture = true\n','Bindings.xml':'<Bindings/>\n','src/base.lua':'local fixture = true\n',
            '.gitattributes':'*.lua text eol=crlf\n','.gitignore':'src/ignored.lua\n',
            'db/Standard/tracked.lua':'tracked DB must stay preserved\n','.contrib/private.lua':'must not ship\n','assets/fixture.txt':'runtime asset\n'
        };
        Object.keys(options.files||{}).forEach(function(name){files[name]=options.files[name];});
        Object.keys(files).forEach(function(name){if(files[name]!==null)write(source+'/'+name,files[name]);});
        if(options.symlink)command(['/bin/ln','-s',options.symlink.target,source+'/'+options.symlink.name]);
        git(source,['add','-A']);git(source,['commit','-qm','[Tests] Create isolated fixture.\n\nAssisted-by: GPT-6']);
        var identity=id(git(source,['rev-parse','HEAD']).trim()),db=p+'/verified-db',manifest={},dbFiles={
            'Standard/ReferenceDB.lua':'reference = true\n','Standard/LocalizationDB.lua':'local localization = true\n',
            'Standard/Category.lua':'category = true\n','Standard/Database.xml':'<Ui><Script file="LocalizationDB.lua"/><Script file="Category.lua"/></Ui>\n'
        };
        Object.keys(options.dbFiles||{}).forEach(function(name){dbFiles[name]=options.dbFiles[name];});
        Object.keys(dbFiles).forEach(function(name){if(dbFiles[name]!==null){write(db+'/'+name,dbFiles[name]);manifest[name]=A.hashFile(db+'/'+name);}});
        var artifact={identity:identity,extractedDb:db,manifest:manifest,files:{},productRoot:'Standard',productFiles:Object.keys(manifest).sort(),provenance:'fixture'};
        Object.keys(manifest).forEach(function(name){artifact.files[name]=fileInfo(db+'/'+name);});
        return {root:p,source:source,identity:identity,artifact:artifact,build:function(stage){return A.buildSnapshot(source,identity,artifact,stage||p+'/stage-'+A.uuid());}};
    }
    function storeFixture(options) {
        options=options||{};var fixture=sourceFixture(),target=fixture.root+'/fake-AddOns/AllTheThings',store=new A.Store(fixture.source,fixture.root+'/store',target,options);store.initialize();
        fixture.store=store;fixture.target=target;fixture.publish=function(identity){identity=identity||fixture.identity;var stage=store.newStage();var artifact=copy(fixture.artifact);artifact.identity=identity;var built=A.buildSnapshot(fixture.source,identity,artifact,stage);return store.publish(stage,identity,function(){return true;});};
        return fixture;
    }
    function probe(state) { return function(){return {state:state};}; }
    function plantedCache(f) {
        var cache=f.root+'/cache',slot=cache+'/'+A.identityKey(f.identity),receipt={schema:1,identity:copy(f.identity),audit_sha256:null,metadata:true,files:{}};
        A.mkdir(slot);[f.zip,f.manifest,f.metadata].forEach(function(path){var name=path.slice(path.lastIndexOf('/')+1);A.writeBytes(slot+'/'+name,A.readBytes(path,4*1024*1024),true);receipt.files[name]=fileInfo(slot+'/'+name);});
        A.exclusiveJSON(slot+'/receipt.json',receipt);return {root:cache,slot:slot,receipt:receipt};
    }
    function cliFixture() {
        var f=sourceFixture();var configured=A.cli(['configure','--source',f.source,'--store',f.root+'/cli-store','--target',f.root+'/fake-AddOns/AllTheThings','--flavor','retail','--profile','fixture','--recipe','fixture-v1']);
        equal('configured',configured.status);f.configured=configured;f.config=A.readJSON(configured.config);f.entry=f.config.bundle+'/att-deploy.sh';return f;
    }
    function pinnedCall(f,args,opts) { return A.exec(['/bin/sh',f.entry,'--pinned',f.config.bundle_sha256,'--config',f.configured.config].concat(args),f.source,opts||{}); }
    function activeIdentity(fixture) { return fixture.store.active().manifest.identity; }
    function worker(job) {
        var store=new A.Store(job.source,job.store,job.target,{probe:probe('closed'),fault:function(point){if(point===job.point){A.writeBytes(job.signal,point,true);A.exec(['/bin/kill','-KILL',String($.NSProcessInfo.processInfo.processIdentifier)]);throw new Error('SIGKILL did not terminate worker');}}});
        if(job.mode==='initialize')return A.canonical(store.initialize());
        if(job.mode==='hold-lock')return A.withLock(job.lock,3000,function(){A.writeBytes(job.signal,'held',true);A.exec(['/bin/sleep',String(job.seconds||1)]);return 'lease released';});
        store.validateOwner();return A.withLock(store.root+'/store.lock',3000,function(){store.activate(job.candidate,job.identity,function(){return true;},true);return 'worker completed';});
    }
    if(args[2]==='--worker')return worker(A.readJSON(String(args[3])));
    function spawn(argv,cwd,logs) { var task=$.NSTask.alloc.init,handles=[];task.launchPath=argv[0];task.arguments=argv.slice(1);if(cwd)task.currentDirectoryPath=cwd;if(logs){write(logs+'.stdout','');write(logs+'.stderr','');task.standardOutput=$.NSFileHandle.fileHandleForWritingAtPath(logs+'.stdout');task.standardError=$.NSFileHandle.fileHandleForWritingAtPath(logs+'.stderr');handles=[task.standardOutput,task.standardError];}else{task.standardOutput=$.NSFileHandle.fileHandleWithNullDevice;task.standardError=$.NSFileHandle.fileHandleWithNullDevice;}task.launch;handles.forEach(function(h){h.closeFile;});return task; }
    function waitFor(path) { var retries=0;while(!A.exists(path)&&retries++<100)command(['/bin/sleep','0.01']);assert(A.exists(path),'Fixture process did not signal readiness'); }
    function headerPipeFixture(p,send) {
        var fifo=p+'/headers.fifo',headers=write(p+'/headers',''),errors=write(p+'/reader.stderr',''),head=$.NSTask.alloc.init,output=$.NSFileHandle.fileHandleForWritingAtPath(headers),error=$.NSFileHandle.fileHandleForWritingAtPath(errors),keeper=-1,result=null;
        assert($.mkfifo(fifo,384)===0,'Cannot create private fixture FIFO');head.launchPath='/usr/bin/head';head.arguments=['-c','65537',fifo];head.standardOutput=output;head.standardError=error;head.launch;
        try {
            var deadline=Date.now()+1000;while(keeper<0){keeper=$.open(fifo,1|4|16777216);if(keeper<0){assert(Date.now()<deadline,'Header reader did not become ready');$.NSThread.sleepForTimeInterval(0.005);}}
            result=send(fifo,head);$.close(keeper);keeper=-1;deadline=Date.now()+2000;while(head.running){assert(Date.now()<deadline,'Header reader failed to finish after writer close');$.NSThread.sleepForTimeInterval(0.01);}head.waitUntilExit;
            result.header_code=Number(head.terminationStatus);result.header_bytes=A.size(headers);result.header_file=headers;A.atomicJSON(p+'/proof.json',result);return result;
        } finally {if(keeper>=0)$.close(keeper);if(head.running){$.kill(Number(head.processIdentifier),9);head.waitUntilExit;}output.closeFile;error.closeFile;A.remove(fifo);}
    }

    test('json valid nested data and prototype key',function(){equal('{"__proto__":null,"a":[true,null,1]}',A.canonical(A.strictParse('{"a":[true,null,1],"__proto__":null}')));assert(Object.prototype.hasOwnProperty.call(A.strictParse('{"__proto__":1}'),'__proto__'));});
    test('json duplicate literal key',function(){reject(function(){A.strictParse('{"a":1,"a":2}');},/Duplicate/);});
    test('json escaped duplicate key',function(){reject(function(){A.strictParse('{"a":1,"\\u0061":2}');},/Duplicate/);});
    ['{"a":1,}','[1,]','{"a" 1}','true false','01','1e999','"bad\nstring"','{"a":NaN}'].forEach(function(text,i){test('json malformed grammar '+i,function(){reject(function(){A.strictParse(text);});});});
    test('json bounded depth',function(){reject(function(){A.strictParse('[[[0]]]',1);},/nesting/);});
    test('json bounded text',function(){reject(function(){A.strictParse('{"a":1}',64,3);},/size/);});
    test('json unsafe integer',function(){reject(function(){A.strictParse('9007199254740992');},/exact range/);});
    ['"\\ud800"','"\\udc00"','"\\ud800a"'].forEach(function(text,i){test('json rejects unpaired surrogate '+i,function(){reject(function(){A.strictParse(text);},/surrogate|Unicode/);});});
    test('canonical recursive ordinal keys',function(){equal('{"a":{"b":2,"z":1},"z":0}',A.canonical({z:0,a:{z:1,b:2}}));});
    test('identity exact five fields and full sha256',function(){equal(id(),A.identity(id()));var sha=id(new Array(65).join('a'));sha.object_format='sha256';equal(sha,A.identity(sha));});
    ['short','uppercase','extra','case field','unsupported format','unsafe flavor','missing recipe'].forEach(function(kind){test('identity rejects '+kind,function(){var v=id();if(kind==='short')v.commit='1234567';if(kind==='uppercase')v.commit=new Array(41).join('A');if(kind==='extra')v.extra=1;if(kind==='case field'){v.Commit=v.commit;delete v.commit;}if(kind==='unsupported format')v.object_format='md5';if(kind==='unsafe flavor')v.flavor='../retail';if(kind==='missing recipe')delete v.recipe;reject(function(){A.identity(v);});});});
    [function(v){return [v];},function(){return 1234567890;},function(v){return {toString:function(){return v;}};}].forEach(function(make,i){test('identity rejects coerced commit type '+i,function(){var v=id();v.commit=make(v.commit);reject(function(){A.identity(v);},/Identity|SHA|string/);});});
    test('identity key distinguishes full profile recipe flavor',function(){var a=id(),b=copy(a),c=copy(a),d=copy(a);b.profile='other';c.recipe='other';d.flavor='era';var keys=[a,b,c,d].map(A.identityKey);equal(4,new Set(keys).size);});
    test('exclusive JSON cannot replace winner',function(){var p=dir('exclusive')+'/owner.json';A.exclusiveJSON(p,{owner:'first'});reject(function(){A.exclusiveJSON(p,{owner:'second'});});equal({owner:'first'},A.readJSON(p));});
    test('atomic JSON replaces complete value',function(){var p=dir('atomic')+'/state.json';A.atomicJSON(p,{one:1});A.atomicJSON(p,{two:2});equal({two:2},A.readJSON(p));});
    test('filesystem dangling and parent symlinks refused',function(){var p=dir('links');command(['/bin/ln','-s',p+'/absent',p+'/dangling']);reject(function(){A.readText(p+'/dangling');});reject(function(){A.writeBytes(p+'/dangling','bad',true);});A.mkdir(p+'/real');command(['/bin/ln','-s',p+'/real',p+'/parent']);reject(function(){A.writeBytes(p+'/parent/file','bad',true);});});
    test('bounded file reader refuses oversize',function(){var p=dir('bounded')+'/file';write(p,'1234');reject(function(){A.readBytes(p,3);},/limit/);});
    test('native SHA256 matches standard text and binary reference',function(){equal('e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',A.hashBytes(''));equal('ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad',A.hashBytes('abc'));var p=dir('native-hash')+'/binary';write(p,[0,1,2,127,128,254,255]);var expected=command(['/usr/bin/shasum','-a','256','--',p]).slice(0,64);equal(expected,A.hashFile(p));equal(expected,A.hashBytes(A.readBytes(p,100)));});
    test('bounded UTF8 reader rejects malformed byte sequence',function(){var p=dir('invalid-utf8')+'/text';write(p,[0xc3,0x28]);reject(function(){A.readText(p,100);},/UTF-8/);});
    test('native process executor enforces deadline',function(){var start=Date.now();reject(function(){A.exec(['/bin/sleep','2'],null,{timeoutMilliseconds:100});},/time|limit/);assert(Date.now()-start<2000,'Deadline did not terminate owned child');});
    test('native process executor enforces captured output bound',function(){reject(function(){A.exec(['/usr/bin/yes','fixture'],null,{maxOutput:64,timeoutMilliseconds:1000});},/output limit/);});
    test('native process executor enforces streamed output file bound',function(){var p=dir('bounded-child-output')+'/output';reject(function(){A.exec(['/usr/bin/yes','fixture'],null,{stdoutFile:p,maxFileOutput:64,maxOutput:64,timeoutMilliseconds:1000});},/output limit/);});
    test('native process stdinFile reads exact bounded regular input',function(){var p=dir('stdin-file'),input=write(p+'/input','fixture stdin\n'),r=A.exec(['/bin/cat'],null,{stdinFile:input,maxInputBytes:14,timeoutMilliseconds:1000});equal(0,r.code);equal('fixture stdin\n',r.stdout);});
    test('native process stdinFile refuses oversize before launching child',function(){var p=dir('stdin-limit'),input=write(p+'/input','12345'),sentinel=p+'/executed';reject(function(){A.exec(['/bin/sh','-c','printf unsafe > "$1"','stdin-fixture',sentinel],null,{stdinFile:input,maxInputBytes:4,timeoutMilliseconds:1000});},/input exceeds byte limit/);assert(!A.exists(sentinel));});
    test('native process stdinFile refuses FIFO symlink and relative path',function(){var p=dir('stdin-special'),regular=write(p+'/regular','fixture'),fifo=p+'/fifo';command(['/usr/bin/mkfifo',fifo]);command(['/bin/ln','-s',regular,p+'/link']);reject(function(){A.exec(['/bin/cat'],null,{stdinFile:fifo,timeoutMilliseconds:1000});},/regular/);reject(function(){A.exec(['/bin/cat'],null,{stdinFile:p+'/link',timeoutMilliseconds:1000});},/link|regular/i);reject(function(){A.exec(['/bin/cat'],p,{stdinFile:'regular',timeoutMilliseconds:1000});},/absolute regular/);});
    test('native process stdinFile rejects invalid input bound',function(){var p=dir('stdin-bound'),input=write(p+'/input','fixture');[0,-1,1.5,1073741825].forEach(function(max){reject(function(){A.exec(['/bin/cat'],null,{stdinFile:input,maxInputBytes:max,timeoutMilliseconds:1000});},/input limit/);});});
    test('Git object replacement cannot change requested source bytes',function(){var f=sourceFixture(),original=f.identity.commit;write(f.source+'/src/base.lua','replacement data\n');git(f.source,['add','src/base.lua']);git(f.source,['commit','-qm','[Tests] Add isolated replacement.\n\nAssisted-by: GPT-6']);var replacement=git(f.source,['rev-parse','HEAD']).trim();git(f.source,['replace',original,replacement]);var unprotected=A.exec(['/bin/sh','-c','exec /usr/bin/git -C "$1" show "$2"','replace-fixture',f.source,original+':src/base.lua'],null,{env:{GIT_NO_REPLACE_OBJECTS:null}});equal(0,unprotected.code);equal('replacement data\n',unprotected.stdout);equal('local fixture = true\n',A.git(f.source,['show',original+':src/base.lua']));var protectedResult=A.exec(['/usr/bin/git','-C',f.source,'show',original+':src/base.lua'],null,{env:{GIT_NO_REPLACE_OBJECTS:'0'}});equal(0,protectedResult.code);equal('local fixture = true\n',protectedResult.stdout);});
    test('offline curl header FIFO survives initial writer close and reopen',function(){var p=dir('offline-curl-fifo'),input=write(p+'/input','fixture body\n'),url=ObjC.unwrap($.NSURL.fileURLWithPath(input).absoluteString),proof=headerPipeFixture(p,function(fifo,head){var empty=A.exec(['/bin/sh','-c',': > "$1"','header-fixture',fifo],null,{timeoutMilliseconds:1000});equal(0,empty.code);assert(head.running,'Header reader reached premature EOF');var r=A.exec(['/usr/bin/curl','-q','--silent','--show-error','--proto','=file','--max-time','1','--dump-header',fifo,'--output',p+'/body','--write-out','%{http_code}',url],null,{timeoutMilliseconds:2000,maxOutput:65536});equal(0,r.code,r.stderr);equal('000',r.stdout);equal('fixture body\n',A.readText(p+'/body'));assert(head.running,'Keep-writer lease failed during curl reopen');return {scope:'offline system curl file fixture; no production HTTP URL gate bypass',writer_code:r.code,curl_http_code:r.stdout,body_sha256:A.hashFile(p+'/body')};});equal(0,proof.header_code);assert(proof.header_bytes<=65536);assert(!A.exists(p+'/headers.fifo'));});
    test('offline header FIFO oversized sender gets SIGPIPE at strict cap',function(){var p=dir('offline-header-limit'),proof=headerPipeFixture(p,function(fifo){var r=A.exec(['/bin/sh','-c','exec /bin/dd if=/dev/zero bs=1024 count=200 > "$1"','header-limit-fixture',fifo],null,{timeoutMilliseconds:2000,maxOutput:65536});assert(r.code===13||r.code===141,'Expected SIGPIPE sender termination; actual '+r.code);return {scope:'offline header transport limit fixture',writer_code:r.code,attempted_bytes:200*1024};});equal(0,proof.header_code);equal(65537,proof.header_bytes);reject(function(){A.readText(proof.header_file,65536);},/limit/);assert(!A.exists(p+'/headers.fifo'));});
    test('path overlap case Unicode and component boundary',function(){var p=dir('overlap');assert(A.overlap(p+'/Case',p+'/case/sub'));assert(A.overlap(p+'/é',p+'/e\u0301/sub'));assert(!A.overlap(p+'/one',p+'/oner'));});
    ['../a','/absolute','a/../b','a\\b','NUL.txt','a:stream','a/','a.','a /b'].forEach(function(path){test('path rejects '+path,function(){reject(function(){A.safeRelative(path);});});});

    test('artifact valid stored ZIP exact product',function(){var f=artifactFixture(),result=f.extract();equal(f.identity,result.identity);equal(['Standard/a.lua'],result.productFiles);equal('fixture=true\n',A.readText(result.extractedDb+'/Standard/a.lua'));equal('schema2',result.provenance);});
    ['commit','object format','repository','profile','recipe','flavor','archive name','manifest name','archive hash','manifest hash','file hash','file size','extra file','empty products','incomplete product','duplicate product','fresh staging','flavor completion'].forEach(function(kind){test('artifact rejects metadata '+kind,function(){var f=artifactFixture({change:function(c){if(kind==='commit')c.commit=new Array(41).join('2');if(kind==='object format')c.git_object_format='sha256';if(kind==='repository')c.repository='Other/AllTheThings';if(kind==='profile')c.products[0].profile='other';if(kind==='recipe')c.products[0].recipe='other';if(kind==='flavor')c.products[0].flavor='era';if(kind==='archive name')c.archive.name='db-wrong.zip';if(kind==='manifest name')c.manifest.name='db-wrong.sha256';if(kind==='archive hash')c.archive.sha256=new Array(65).join('0');if(kind==='manifest hash')c.manifest.sha256=new Array(65).join('0');if(kind==='file hash')c.files['Standard/a.lua'].sha256=new Array(65).join('0');if(kind==='file size')c.files['Standard/a.lua'].size++;if(kind==='extra file')c.files['Standard/extra.lua']={sha256:new Array(65).join('0'),size:0};if(kind==='empty products')c.products=[];if(kind==='incomplete product')c.products[0].files=[];if(kind==='duplicate product')c.products.push(copy(c.products[0]));if(kind==='fresh staging')c.producer.fresh_staging=false;if(kind==='flavor completion')c.producer.completed_flavors=[];}});reject(function(){f.extract();});});});
    test('artifact duplicate metadata JSON key refused',function(){var f=artifactFixture(),text=A.readText(f.metadata);write(f.metadata,text.replace('{','{"schema":2,'));reject(function(){f.extract();},/Duplicate/);});
    test('artifact schema1 cannot silently pass',function(){var f=artifactFixture();f.contract.schema=1;write(f.metadata,A.canonical(f.contract));reject(function(){f.extract();});});
    test('artifact missing metadata refused',function(){var f=artifactFixture();reject(function(){A.verifyAndExtract(f.zip,f.manifest,null,f.root+'/extract',f.identity,{});});});
    test('artifact explicit immutable historical audit',function(){var f=artifactFixture(),audit=copy(f.contract);audit.schema=1;audit.kind='att-local-audited-contract';audit.audit={scope:'isolated-historical-acceptance',profile_evidence:'Fixture audit explicitly attests only these bytes.'};var path=f.root+'/audit.json';write(path,A.canonical(audit));var result=A.verifyAndExtract(f.zip,f.manifest,null,f.root+'/audit-extract',f.identity,{allowLocalAudit:true,auditPath:path,auditSha256:A.hashFile(path)});assert(result.provenance.indexOf('local-audited:')===0);});
    ['no opt in','no pin','wrong pin'].forEach(function(kind){test('artifact audit rejects '+kind,function(){var f=artifactFixture(),path=f.root+'/audit.json',audit=copy(f.contract);audit.schema=1;audit.kind='att-local-audited-contract';audit.audit={scope:'isolated-historical-acceptance',profile_evidence:'Fixture only'};write(path,A.canonical(audit));var opts={allowLocalAudit:true,auditPath:path,auditSha256:A.hashFile(path)};if(kind==='no opt in')opts.allowLocalAudit=false;if(kind==='no pin')delete opts.auditSha256;if(kind==='wrong pin')opts.auditSha256=new Array(65).join('0');reject(function(){A.verifyAndExtract(f.zip,f.manifest,null,f.root+'/extract',f.identity,opts);});});});
    ['traversal','absolute','backslash','colon','case collision','prefix case collision','file directory collision','duplicate entry','symlink','device','DOS reparse','encrypted','strong encrypted','unsupported method','local flag mismatch','local method mismatch','ZIP64 size sentinel','ZIP64 count sentinel','ZIP64 offset sentinel','multi disk','bad offset','trailing bytes','undeclared extra','missing entry'].forEach(function(kind){test('artifact ZIP refuses '+kind,function(){var rows=[{name:'Standard/a.lua',text:'fixture=true\n'}],manifestRows=null,zipOptions={};
        if(['traversal','absolute','backslash','colon','case collision','prefix case collision','file directory collision','duplicate entry'].indexOf(kind)>=0)manifestRows=copy(rows);
        if(kind==='traversal')rows[0].name='Standard/../outside.lua';if(kind==='absolute')rows[0].name='/outside.lua';if(kind==='backslash')rows[0].name='Standard\\a.lua';if(kind==='colon')rows[0].name='Standard/a.lua:stream';
        if(kind==='case collision')rows.push({name:'Standard/A.lua',text:'other'});if(kind==='prefix case collision')rows.push({name:'standard/b.lua',text:'other'});if(kind==='file directory collision')rows.push({name:'Standard/a.lua/child',text:'other'});if(kind==='duplicate entry')rows.push(copy(rows[0]));
        if(kind==='symlink')rows[0].attributes=0xa1ff0000;if(kind==='device')rows[0].attributes=0x21a40000;if(kind==='DOS reparse')rows[0].attributes=0x81a40400;if(kind==='encrypted')rows[0].flags=1;if(kind==='strong encrypted')rows[0].flags=64;if(kind==='unsupported method')rows[0].method=99;if(kind==='local flag mismatch')rows[0].localFlags=1;if(kind==='local method mismatch')rows[0].localMethod=8;if(kind==='ZIP64 size sentinel')rows[0].size=0xffffffff;if(kind==='ZIP64 count sentinel')zipOptions.count=65535;if(kind==='ZIP64 offset sentinel')rows[0].offset=0xffffffff;if(kind==='multi disk')zipOptions.disk=1;if(kind==='bad offset')rows[0].offset=1;if(kind==='trailing bytes')zipOptions.trailing=[0];
        if(kind==='undeclared extra'){manifestRows=copy(rows);rows.push({name:'Standard/extra.lua',text:'extra'});}if(kind==='missing entry'){manifestRows=copy(rows);rows=[];}
        var f=artifactFixture({rows:rows,manifestRows:manifestRows,zipOptions:zipOptions});reject(function(){f.extract();});assert(!A.exists(f.root+'/outside.lua'),'Archive escaped destination');
    });});
    test('artifact digest mismatch despite valid CRC and metadata declaration',function(){var f=artifactFixture();write(f.zip,storedZip([{name:'Standard/a.lua',text:'wrong bytes!!\n'}]));f.refresh();reject(function(){f.extract();});});
    test('artifact archive limit',function(){var f=artifactFixture();reject(function(){f.extract({limits:{maxArchiveBytes:22}});});});
    test('artifact expanded file limit',function(){var f=artifactFixture();reject(function(){f.extract({limits:{maxFileBytes:1}});});});
    test('artifact manifest and metadata limits',function(){var f=artifactFixture();reject(function(){f.extract({limits:{maxManifestBytes:1}});});reject(function(){f.extract({limits:{maxMetadataBytes:1}});});});
    test('artifact no extraction over existing destination',function(){var f=artifactFixture(),destination=f.root+'/exists';A.mkdir(destination);write(destination+'/user.lua','keep');reject(function(){A.verifyAndExtract(f.zip,f.manifest,f.metadata,destination,f.identity,{});});equal('keep',A.readText(destination+'/user.lua'));});
    test('artifact offline cache freshly revalidates exact bytes',function(){var f=artifactFixture(),cache=plantedCache(f);var first=A.artifactFetch(f.identity,cache.root,{offline:true}),second=A.artifactFetch(f.identity,cache.root,{offline:true});equal('fixture=true\n',A.readText(first.extractedDb+'/Standard/a.lua'));assert(first.extractedDb!==second.extractedDb,'Cache use must produce separately verified extraction');});
    ['changed archive','changed metadata','extra file','extra directory','receipt identity','receipt hash','redirected archive'].forEach(function(kind){test('artifact cache refuses '+kind,function(){var f=artifactFixture(),cache=plantedCache(f),archive=f.zip.slice(f.zip.lastIndexOf('/')+1),metadata=f.metadata.slice(f.metadata.lastIndexOf('/')+1);
        if(kind==='changed archive')write(cache.slot+'/'+archive,'changed');if(kind==='changed metadata')write(cache.slot+'/'+metadata,'{}');if(kind==='extra file')write(cache.slot+'/user','keep');if(kind==='extra directory')A.mkdir(cache.slot+'/extra');if(kind==='receipt identity'){cache.receipt.identity.profile='other';A.atomicJSON(cache.slot+'/receipt.json',cache.receipt);}if(kind==='receipt hash'){cache.receipt.files[archive].sha256=new Array(65).join('0');A.atomicJSON(cache.slot+'/receipt.json',cache.receipt);}if(kind==='redirected archive'){A.remove(cache.slot+'/'+archive);command(['/bin/ln','-s',f.zip,cache.slot+'/'+archive]);}reject(function(){A.artifactFetch(f.identity,cache.root,{offline:true});},/Cache|Cached|cache|regular|Symlink/);
    });});
    test('artifact offline never substitutes a different profile slot',function(){var f=artifactFixture(),cache=plantedCache(f),wrong=copy(f.identity);wrong.profile='other';reject(function(){A.artifactFetch(wrong,cache.root,{offline:true});},/unavailable offline/);});
    test('public download URL allows only three canonical HTTPS hosts',function(){['github.com','objects.githubusercontent.com','release-assets.githubusercontent.com'].forEach(function(host){equal('https://'+host+'/asset',A.validatePublicUrl('https://'+host+'/asset'));});});
    ['http://github.com/asset','file:///etc/passwd','https://github.com.evil.test/asset','https://evil.test/github.com/asset','https://user@github.com/asset','https://github.com:444/asset','https://github.com/asset#fragment','https://github.com/asset\nheader','https://github.com/with space'].forEach(function(url,i){test('public download URL refuses unsafe redirect target '+i,function(){reject(function(){A.validatePublicUrl(url);},/HTTPS allowlist/);});});

    test('snapshot full runtime export excludes tracked DB and tooling',function(){var f=sourceFixture(),built=f.build(),m=built.manifest;assert(A.regular(built.addonRoot+'/src/base.lua'));assert(A.regular(built.addonRoot+'/assets/fixture.txt'));assert(!A.exists(built.addonRoot+'/.contrib/private.lua'));assert(!A.exists(built.addonRoot+'/db/Standard/tracked.lua'));equal('tracked DB must stay preserved\n',A.readText(f.source+'/db/Standard/tracked.lua'));equal(f.identity,m.identity);equal(m,A.verifySnapshot(built.addonRoot));});
    test('snapshot Git archive attributes preserve exact bytes',function(){var f=sourceFixture(),built=f.build();var file=f.root+'/expected.lua';command(['/usr/bin/git','-c','core.hooksPath=/dev/null','archive','--format=tar',f.identity.commit,'src/base.lua'],f.source,{stdoutFile:f.root+'/expected.tar'});command(['/usr/bin/tar','-xOf',f.root+'/expected.tar','src/base.lua'],f.source,{stdoutFile:file});equal(A.hashFile(file),A.hashFile(built.addonRoot+'/src/base.lua'));});
    ['tracked','untracked','ignored','tracked DB','assume unchanged','skip worktree'].forEach(function(kind){test('snapshot protects local '+kind,function(){var f=sourceFixture();if(kind==='tracked')write(f.source+'/src/base.lua','user edit\n');if(kind==='untracked')write(f.source+'/src/user.lua','user edit\n');if(kind==='ignored')write(f.source+'/src/ignored.lua','user edit\n');if(kind==='tracked DB')write(f.source+'/db/Standard/tracked.lua','user DB edit\n');if(kind==='assume unchanged')git(f.source,['update-index','--assume-unchanged','src/base.lua']);if(kind==='skip worktree')git(f.source,['update-index','--skip-worktree','src/base.lua']);reject(function(){f.build();},/local|index flags/);});});
    ['missing reference','case reference','root escape','unknown placeholder','external entity','malformed XML','include cycle','localization order','missing localization','missing root TOC','runtime symlink','LFS pointer'].forEach(function(kind){test('snapshot rejects '+kind,function(){var options={files:{},dbFiles:{}};
        if(kind==='missing reference')options.files['AllTheThings.toc']='missing.lua\n';if(kind==='case reference')options.files['AllTheThings.toc']='Src/base.lua\n';if(kind==='root escape')options.files['AllTheThings.toc']='../escape.lua\n';if(kind==='unknown placeholder')options.files['AllTheThings.toc']='db/[Unknown]/Database.xml\n';
        if(kind==='external entity')options.files['Bindings.xml']='<!DOCTYPE x [<!ENTITY y SYSTEM "file:///etc/passwd">]><Bindings>&y;</Bindings>';if(kind==='malformed XML')options.files['Bindings.xml']='<Bindings>';if(kind==='include cycle'){options.files['Bindings.xml']='<Bindings><Include file="Cycle.xml"/></Bindings>';options.files['Cycle.xml']='<Ui><Include file="Bindings.xml"/></Ui>';}
        if(kind==='localization order')options.dbFiles['Standard/Database.xml']='<Ui><Script file="Category.lua"/><Script file="LocalizationDB.lua"/></Ui>';if(kind==='missing localization')options.dbFiles['Standard/LocalizationDB.lua']=null;if(kind==='missing root TOC')options.files['AllTheThings.toc']=null;if(kind==='runtime symlink')options.symlink={name:'src/link.lua',target:'base.lua'};if(kind==='LFS pointer')options.files['src/base.lua']='version https://git-lfs.github.com/spec/v1\noid sha256:'+new Array(65).join('a')+'\nsize 1\n';var f=sourceFixture(options);reject(function(){f.build();});
    });});
    test('snapshot rejects changed verified artifact',function(){var f=sourceFixture();write(f.artifact.extractedDb+'/Standard/Category.lua','changed');reject(function(){f.build();},/artifact changed/);});
    test('snapshot rejects identity mismatch before export',function(){var f=sourceFixture();f.artifact.identity=copy(f.artifact.identity);f.artifact.identity.profile='other';equal('fixture',f.identity.profile);reject(function(){f.build();},/identity/);});
    test('snapshot verifies extra and edited files',function(){var f=sourceFixture(),b=f.build();write(b.addonRoot+'/src/user.lua','user');reject(function(){A.verifySnapshot(b.addonRoot);});A.remove(b.addonRoot+'/src/user.lua');write(b.addonRoot+'/src/base.lua','user');reject(function(){A.verifySnapshot(b.addonRoot);});});
    test('snapshot prevents occupied stage overwrite',function(){var f=sourceFixture(),stage=f.root+'/occupied';write(stage+'/user','keep');reject(function(){f.build(stage);});equal('keep',A.readText(stage+'/user'));});

    test('store full generation publish activate and recover',function(){var f=storeFixture(),candidate=f.publish();assert(!A.exists(f.target));f.store.activate(candidate,f.identity,function(){return true;},true,probe('closed'));equal(f.identity,activeIdentity(f));var state=f.store.recover();equal(f.identity,state.active_identity);equal(null,state.staged);});
    test('store reopened after activation accepts its owned target pointer',function(){var f=storeFixture(),candidate=f.publish();f.store.activate(candidate,f.identity,function(){return true;},true,probe('closed'));var reopened=new A.Store(f.source,f.store.root,f.target);reopened.validateOwner();equal(f.identity,reopened.recover().active_identity);equal(f.identity,reopened.active().manifest.identity);});
    ['Wow','WowClassic','WowClassicEra','WowB','WowT','WorldOfWarcraft','/Applications/World of Warcraft/WorldOfWarcraft'].forEach(function(name){test('process scan refuses known client executable '+name,function(){equal('running',A.classifyProcessScan(0,'/usr/bin/git\n'+name+'\n').state);});});
    test('process scan unknown on failed or empty scan',function(){equal('unknown',A.classifyProcessScan(1,'/usr/bin/git\n').state);equal('unknown',A.classifyProcessScan(0,' \n').state);equal('closed',A.classifyProcessScan(0,'/usr/bin/git\n/usr/bin/osascript\n').state);});
    test('store refuses nonempty unmanaged store',function(){var f=sourceFixture(),rootPath=f.root+'/foreign';write(rootPath+'/user','keep');var store=new A.Store(f.source,rootPath,f.root+'/target');reject(function(){store.initialize();});equal('keep',A.readText(rootPath+'/user'));});
    test('store owner paths cannot be substituted',function(){var f=storeFixture(),owner=A.readJSON(f.store.ownerPath);owner.target=f.root+'/other';A.atomicJSON(f.store.ownerPath,owner);reject(function(){f.store.validateOwner();},/ownership/);});
    test('store actual competing initializers keep one exclusive owner',function(){var f=sourceFixture(),job={mode:'initialize',source:f.source,store:f.root+'/owner-race-store',target:f.root+'/owner-race-target'},jobPath=write(f.root+'/owner-race-job.json',A.canonical(job)),argv=['/usr/bin/osascript','-l','JavaScript',base+'/test-script.js',base,root,'--worker',jobPath],first=spawn(argv),second=spawn(argv);first.waitUntilExit;second.waitUntilExit;equal(0,Number(first.terminationStatus));equal(0,Number(second.terminationStatus));var store=new A.Store(job.source,job.store,job.target),owner=store.validateOwner();assert(/^[0-9a-f]{32}$/.test(owner.store_id));equal(owner,A.readJSON(store.ownerPath));});
    test('store requires separate source store target',function(){var f=sourceFixture();reject(function(){new A.Store(f.source,f.source+'/store',f.root+'/target');},/separate/);reject(function(){new A.Store(f.source,f.root+'/store',f.root+'/store/target');},/separate/);});
    test('store preserves existing actual target directory',function(){var f=storeFixture(),candidate=f.publish();write(f.target+'/user.lua','keep');reject(function(){f.store.activate(candidate,f.identity,function(){return true;},true,probe('closed'));});equal('keep',A.readText(f.target+'/user.lua'));});
    ['unknown','running'].forEach(function(state){test('store activation refuses '+state+' client and preserves full active version',function(){var f=storeFixture(),previous=f.publish();f.store.activate(previous,f.identity,function(){return true;},true,probe('closed'));var next=copy(f.identity);next.profile='next';var candidate=f.publish(next);reject(function(){f.store.activate(candidate,next,function(){return true;},true,probe(state));},/running or unknown/);equal(f.identity,activeIdentity(f));equal(previous,A.readLink(f.target));equal(next,A.verifySnapshot(candidate).identity);});});
    test('store activation requires explicit client closed confirmation',function(){var f=storeFixture(),candidate=f.publish();reject(function(){f.store.activate(candidate,f.identity,function(){return true;},false,probe('closed'));},/client-closed/);});
    test('store final client probe rechecks before swap',function(){var f=storeFixture(),candidate=f.publish(),count=0;reject(function(){f.store.activate(candidate,f.identity,function(){return true;},true,function(){return {state:++count===1?'closed':'running'};});});assert(!A.exists(f.target));f.store.recover();assert(!A.exists(f.store.journalPath));});
    test('store publish rejects stale desired source',function(){var f=storeFixture(),stage=f.store.newStage();f.build(stage);reject(function(){f.store.publish(stage,f.identity,function(){return false;});},/Desired source/);assert(!A.exists(f.target));});
    test('store final desired source rechecks after journal',function(){var f=storeFixture(),candidate=f.publish(),count=0;reject(function(){f.store.activate(candidate,f.identity,function(){return ++count===1;},true,probe('closed'));},/Desired source/);assert(!A.exists(f.target));f.store.recover();});
    test('store activation rejects wrong full profile',function(){var f=storeFixture(),candidate=f.publish(),wrong=copy(f.identity);wrong.profile='other';reject(function(){f.store.activate(candidate,wrong,function(){return true;},true,probe('closed'));},/identity/);assert(!A.exists(f.target));});
    test('store active user edits prevent replacement and noop',function(){var f=storeFixture(),candidate=f.publish();f.store.activate(candidate,f.identity,function(){return true;},true,probe('closed'));write(candidate+'/src/base.lua','user edit');reject(function(){f.store.activate(candidate,f.identity,function(){return true;},true,probe('closed'));});equal('user edit',A.readText(candidate+'/src/base.lua'));});
    test('store reuses only exact intact published generation',function(){var f=storeFixture(),first=f.publish(),second=f.publish();equal(first,second);assert(A.walk(f.store.abandoned).some(function(x){return x.type==='directory';}));write(first+'/src/base.lua','user');reject(function(){f.publish();});});
    test('store recovery preserves but abandons interrupted owned stage',function(){var f=storeFixture(),stage=f.store.newStage();write(stage+'/user-fixture','unfinished');f.store.recover();assert(!A.exists(stage));assert(A.walk(f.store.abandoned).some(function(x){return x.relative.endsWith('/user-fixture');}));});
    test('store recovery refuses foreign staging and preserves it',function(){var f=storeFixture(),stage=f.store.staging+'/'+new Array(33).join('a');A.mkdir(stage);write(stage+'/stage.json',A.canonical({store_id:new Array(33).join('b')}));write(stage+'/user','keep');reject(function(){f.store.recover();},/Foreign stage/);equal('keep',A.readText(stage+'/user'));});
    ['after_activation_journal','before_pointer_replace','after_pointer_replace','after_activation_state'].forEach(function(point){test('store actual killed worker recovery '+point,function(){var f=storeFixture(),previous=f.publish();f.store.activate(previous,f.identity,function(){return true;},true,probe('closed'));var next=copy(f.identity);next.profile='next';var candidate=f.publish(next),job={source:f.source,store:f.store.root,target:f.target,candidate:candidate,identity:next,point:point,signal:f.root+'/killed-at'};var jobPath=write(f.root+'/worker-job.json',A.canonical(job)),task=spawn(['/usr/bin/osascript','-l','JavaScript',base+'/test-script.js',base,root,'--worker',jobPath],null,f.root+'/worker');task.waitUntilExit;assert(Number(task.terminationStatus)!==0,'Worker did not die');assert(A.regular(job.signal),'Worker failed before requested checkpoint: '+A.readText(f.root+'/worker.stderr',1024*1024));equal(point,A.readText(job.signal));var recovered=f.store.recover();var switched=point==='after_pointer_replace'||point==='after_activation_state';assert(!!recovered.active);equal(switched?next:f.identity,activeIdentity(f));equal(f.identity,A.verifySnapshot(previous).identity);equal(next,A.verifySnapshot(candidate).identity);assert(!A.exists(f.store.journalPath));});});
    test('native lockf serializes contenders and retains inode',function(){var p=dir('lockf'),lock=write(p+'/lock',''),entered=p+'/entered',held=p+'/held';var first=spawn(['/usr/bin/lockf','-k','-t','3',lock,'/bin/sh','-c','printf held > "$1"; /bin/sleep 1','att-lock-fixture',held]);var count=0;while(!A.exists(held)&&count++<100)command(['/bin/sleep','0.01']);assert(A.exists(held),'First lock was not held');var second=A.exec(['/usr/bin/lockf','-k','-t','0',lock,'/bin/sh','-c','printf entered > "$1"','att-lock-fixture',entered]);assert(second.code!==0,'Concurrent contender acquired lock');assert(!A.exists(entered));first.waitUntilExit;equal(0,Number(first.terminationStatus));command(['/usr/bin/lockf','-k','-t','1',lock,'/bin/sh','-c','printf entered > "$1"','att-lock-fixture',entered]);equal('entered',A.readText(entered));assert(A.regular(lock));});
    test('native flock competing child times out without entering mutation',function(){var f=sourceFixture(),lock=write(f.root+'/native.lock',''),job={mode:'hold-lock',source:f.source,store:f.root+'/unused-store',target:f.root+'/unused-target',lock:lock,signal:f.root+'/lease-held',seconds:1},jobPath=write(f.root+'/native-lock-job.json',A.canonical(job)),child=spawn(['/usr/bin/osascript','-l','JavaScript',base+'/test-script.js',base,root,'--worker',jobPath]);waitFor(job.signal);var entered=false;reject(function(){A.withLock(lock,50,function(){entered=true;});},/lock|lease/i);assert(!entered,'Contender entered mutation');child.waitUntilExit;equal(0,Number(child.terminationStatus));A.withLock(lock,100,function(){entered=true;});assert(entered);});
    test('native flock callback failure releases same process lease',function(){var p=dir('native-exception'),lock=write(p+'/lock','');reject(function(){A.withLock(lock,100,function(){throw new Error('Fixture callback');});},/Fixture callback/);equal('acquired',A.withLock(lock,100,function(){return 'acquired';}));});
    test('native flock killed owned holder automatically releases lease',function(){var f=sourceFixture(),lock=write(f.root+'/native.lock',''),job={mode:'hold-lock',source:f.source,store:f.root+'/unused-store',target:f.root+'/unused-target',lock:lock,signal:f.root+'/lease-held',seconds:10},jobPath=write(f.root+'/native-kill-job.json',A.canonical(job)),child=spawn(['/usr/bin/osascript','-l','JavaScript',base+'/test-script.js',base,root,'--worker',jobPath]);waitFor(job.signal);command(['/bin/kill','-KILL',String(child.processIdentifier)]);child.waitUntilExit;assert(Number(child.terminationStatus)!==0);equal('reacquired',A.withLock(lock,1000,function(){return 'reacquired';}));});
    test('native flock refuses FIFO and redirected lock without blocking',function(){var p=dir('native-special'),fifo=p+'/fifo',target=write(p+'/regular','');command(['/usr/bin/mkfifo',fifo]);command(['/bin/ln','-s',target,p+'/link']);reject(function(){A.withLock(fifo,100,function(){});},/regular|lock|special/i);reject(function(){A.withLock(p+'/link',100,function(){});},/link|regular|lock/i);});
    test('CLI installed bundle status executes actual native lock',function(){var f=cliFixture(),r=pinnedCall(f,['status']);equal(0,r.code,r.stderr);equal('status',A.strictParse(r.stdout).status);assert(!A.exists(f.config.target),'Status unexpectedly deployed');});
    test('CLI status waits for native lease before its recovery mutation',function(){var f=cliFixture(),child=null,state=f.config.store+'/state.json';assert(!A.exists(state));A.withLock(f.config.store+'/store.lock',1000,function(){child=spawn(['/bin/sh',f.entry,'--pinned',f.config.bundle_sha256,'--config',f.configured.config,'status'],f.source);command(['/bin/sleep','1']);assert(child.running,'CLI exited before native lease was released');assert(!A.exists(state),'CLI recovered while another native lease was held');});child.waitUntilExit;equal(0,Number(child.terminationStatus));equal(1,A.readJSON(state).schema_version);});
    test('CLI rejects changed script before any JXA load',function(){var f=cliFixture(),sentinel=f.root+'/executed',payload='ObjC.import("Foundation"); $.NSString.stringWithString("unsafe").writeToFileAtomicallyEncodingError('+JSON.stringify(sentinel)+',true,$.NSUTF8StringEncoding,Ref()); function run(){return "unsafe";}';write(f.config.bundle+'/att-core.js',payload);var r=pinnedCall(f,['status']);assert(r.code!==0,'Changed core executed');assert(/changed/.test(r.stderr),'Expected explicit SHA refusal');assert(!A.exists(sentinel),'Unverified core ran');});
    test('trusted literal bootstrap refuses modified entry before it executes',function(){var f=cliFixture(),bootstrap=A.bootstrapScript(f.config,f.configured.config,['status']),sentinel=f.root+'/entry-executed';write(f.entry,'#!/bin/sh\nprintf unsafe > '+A.shellQuote(sentinel)+'\nexit 0\n');var r=A.exec(['/bin/sh','-c',bootstrap],f.source);assert(r.code!==0);assert(/changed/.test(r.stderr));assert(!A.exists(sentinel),'Unverified installed entry ran');});
    test('actual managed Git hook checks bundle before loading changed core',function(){var f=cliFixture();A.cli(['install-hooks','--source',f.source]);var sentinel=f.root+'/hook-core-executed',payload='ObjC.import("Foundation"); $.NSString.stringWithString("unsafe").writeToFileAtomicallyEncodingError('+JSON.stringify(sentinel)+',true,$.NSUTF8StringEncoding,Ref()); function run(){return "unsafe";}';write(f.config.bundle+'/att-core.js',payload);var r=A.exec(['/usr/bin/git','checkout','--detach',f.identity.commit],f.source,{env:{GIT_TERMINAL_PROMPT:'0'}});equal(0,r.code,'Hook caused Git checkout failure: '+r.stderr);assert(/changed/.test(r.stderr),'Managed hook did not detect altered core');assert(!A.exists(sentinel),'Hook loaded an unverified core');assert(!A.exists(f.config.store+'/worker-status.json'));A.ensureSourceClean(f.source);});
    test('CLI rejects unexpected script bundle inventory',function(){var f=cliFixture();write(f.config.bundle+'/unexpected.js','unsafe');var r=pinnedCall(f,['status']);assert(r.code!==0);assert(/Unexpected/.test(r.stderr));});
    test('CLI rejects inventory mutation before JXA load',function(){var f=cliFixture();write(f.config.bundle+'/inventory.txt','changed');var r=pinnedCall(f,['status']);assert(r.code!==0);assert(/inventory changed/.test(r.stderr));});
    test('CLI FIFO config refuses without blocking',function(){var f=cliFixture();A.remove(f.configured.config);command(['/usr/bin/mkfifo',f.configured.config]);var start=Date.now(),r=pinnedCall(f,['status'],{timeoutMilliseconds:3000});assert(r.code!==0);assert(/regular/.test(r.stderr));assert(Date.now()-start<3000,'FIFO config read blocked');});
    test('CLI direct locked invocation from checkout refused',function(){var r=A.exec(['/bin/sh',base+'/att-deploy.sh','__locked','unused','status','','online']);assert(r.code!==0);assert(/internal|locked|Expected configure/i.test(r.stderr));});
    test('CLI preserves custom hooks instead of installing over them',function(){var f=cliFixture(),custom=f.root+'/custom-hooks';write(custom+'/post-checkout','#!/bin/sh\n# owner hook\n');git(f.source,['config','--local','core.hooksPath',custom]);var before=A.hashFile(custom+'/post-checkout');reject(function(){A.cli(['install-hooks','--source',f.source]);},/custom hooks|Deployment worker failed/);equal(before,A.hashFile(custom+'/post-checkout'));equal(custom,git(f.source,['config','--local','--get','core.hooksPath']).trim());});
    test('CLI linked worktree hook installation refused',function(){var f=cliFixture(),linked=f.root+'/linked';git(f.source,['worktree','add','-q','--detach',linked,f.identity.commit]);var c=A.cli(['configure','--source',linked,'--store',f.root+'/linked-store','--target',f.root+'/linked-AddOns/AllTheThings','--flavor','retail','--profile','fixture','--recipe','fixture-v1']);reject(function(){A.cli(['install-hooks','--source',linked]);},/Linked worktrees|Deployment worker failed/);assert(!A.exists(f.root+'/linked-store/hooks'),'Linked worktree changed shared hooks');});
    test('CLI config checkout alias cannot bypass containment',function(){var f=sourceFixture(),alias=f.root+'/SOURCE/att-config.json';reject(function(){A.cli(['configure','--source',f.source,'--config',alias,'--store',f.root+'/cli-store','--target',f.root+'/fake-AddOns/AllTheThings','--flavor','retail','--profile','fixture','--recipe','fixture-v1']);},/Configuration|checkout|contain/);assert(!A.exists(f.source+'/att-config.json'));});
    ['store','target','target child'].forEach(function(kind){test('CLI config cannot overlap '+kind,function(){var f=sourceFixture(),store=f.root+'/cli-store',target=f.root+'/fake-AddOns/AllTheThings',config=kind==='store'?store:kind==='target'?target:target+'/config.json';reject(function(){A.cli(['configure','--source',f.source,'--config',config,'--store',store,'--target',target,'--flavor','retail','--profile','fixture','--recipe','fixture-v1']);},/config|Configuration|overlap/i);assert(!A.exists(target));assert(!A.exists(store));});});
    test('CLI reconfiguration cannot change owned paths or profiles',function(){var f=cliFixture(),owner=A.readJSON(f.config.store+'/owner.json');reject(function(){A.cli(['configure','--source',f.source,'--store',f.config.store,'--target',f.root+'/other-target','--flavor','retail','--profile','fixture','--recipe','fixture-v1']);},/Reconfiguration/);reject(function(){A.cli(['configure','--source',f.source,'--store',f.config.store,'--target',f.config.target,'--flavor','retail','--profile','other','--recipe','fixture-v1']);},/Reconfiguration/);equal(owner,A.readJSON(f.config.store+'/owner.json'));equal(f.config,A.readJSON(f.configured.config));});
    test('tool sources remain stable throughout test run',function(){Object.keys(loadedHashes).forEach(function(name){equal(loadedHashes[name],A.hashFile(base+'/'+name),'Tool source changed during test run: '+name);});});

    var selected=tests.filter(function(t){return !filter||t.name.toLowerCase().indexOf(filter.toLowerCase())>=0;});
    if(filter==='--list')return A.canonical({count:tests.length,names:tests.map(function(t){return t.name;})});
    assert(selected.length>0,'No cases match the requested filter');
    function report() { A.atomicJSON(root+'/script-test-results.json',{schema_version:1,recorded_at:new Date().toISOString(),runtime:'macOS system JXA / JavaScriptCore + Foundation',tools_directory:A.real(base),loaded_source_sha256:loadedHashes,evidence_directory:root,filter:filter,total:selected.length,completed:reports.length,passed:reports.filter(function(r){return r.status==='passed';}).length,failed:failures,elapsed_milliseconds:Date.now()-started,results:reports,limitations:['Windows PowerShell preparation and Windows activation are not executed by this macOS suite.','Store process probes in fixture activation are typed test functions; real Mac process probing is checked separately in public A/B acceptance.','No network or public artifact downloads occur in this fixture suite.']}); }
    selected.forEach(function(t){var start=Date.now(),result={name:t.name,status:'passed',fixture_directories:[],expected_refusals:[]};activeCase=result;try{t.fn();console.log('PASS '+t.name);}catch(e){failures++;result.status='failed';result.error=String(e);result.stack=e.stack?String(e.stack):'';console.log('FAIL '+t.name+' : '+e);}activeCase=null;result.milliseconds=Date.now()-start;reports.push(result);report();});
    var summary='Tests: '+selected.length+'; passed: '+(selected.length-failures)+'; failed: '+failures+'; seconds: '+((Date.now()-started)/1000).toFixed(3);console.log(summary);
    if(failures)throw new Error(summary+'; evidence: '+root+'/script-test-results.json');return summary;
}
